Repository electron/electron, pull requests merged in 2018-11, with the labels that each got.

#15512 fix: explicitly set `windowsHide` to the old node default
  npm/cli.js
Labels: target/2-0-x, target/3-0-x

#15519 docs: add Size as an option for pageSize in docs for printToPDF
  docs/api/web-contents.md
  docs/api/webview-tag.md
Labels: target/2-0-x, target/3-0-x, target/4-0-x

#15520 chore: publish to the latest tag correctly when releasing old versions
  script/publish-to-npm.js
Labels: target/1-8-x, target/2-0-x

#15518 fix: use sendToAll method correctly in chrome-api
  lib/renderer/chrome-api.js
Labels: target/4-0-x

#15546 docs: fix the "second-instance" event handler signature in the docs
  docs/api/breaking-changes.md
Labels: target/4-0-x

#15566 build: make pyyaml an optional dependency (backport: 4-0-x)
  .circleci/config.yml
  DEPS
Labels: 4-0-x, backport

#15562 feat: add remote.require() / remote.getGlobal() filtering (backport: 4-0-x)
  atom/browser/api/atom_api_event.cc
  atom/common/node_bindings.cc
  docs/api/app.md
  docs/api/web-contents.md
  filenames.gni
  lib/browser/api/web-contents.js
  lib/browser/rpc-server.js
  spec/api-app-spec.js
  spec/api-remote-spec.js
  spec/static/main.js
Labels: 4-0-x, backport

#15395 build: store the patches config in a json file
  DEPS
  patches/common/config.json
  script/apply_all_patches.py
Labels: target/4-0-x

#15355 fix: use NSURL path for receipt url
  atom/browser/mac/in_app_purchase.mm
Labels: target/3-0-x, target/4-0-x

#15587 fix: update the "SSL_get_tlsext_status_type" patch
  patches/common/boringssl/.patches
  patches/common/boringssl/implement-SSL_get_tlsext_status_type.patch
  patches/common/boringssl/implement_ssl_get_tlsext_status_type.patch
Labels: target/4-0-x

#15595 chore: add simple set/unset loginitem spec
  spec/api-app-spec.js
Labels: target/3-0-x, target/4-0-x

#15606 build: add v8_context_snapshot_generator to mksnapshot zip
  BUILD.gn
Labels: target/4-0-x

#15610 fix: correctly package Login Helper in mas builds
  BUILD.gn
Labels: target/4-0-x

#15542 feat: allow registering multiple shortcuts
  atom/browser/api/atom_api_global_shortcut.cc
  atom/browser/api/atom_api_global_shortcut.h
  docs/api/global-shortcut.md
  spec/api-global-shortcut-spec.js
Labels: semver/minor

#15502 fix: correctly display zoom in accelerator on mac
  patches/common/chromium/.patches
  patches/common/chromium/fix_zoom_display.patch
Labels: target/4-0-x

#15586 chore: remove the 'get-patch' script
  script/README.md
  script/get-patch
Labels: target/4-0-x

#15401 fix: don't append Shift modifier text twice to accelerators (backport: 4-0-x)
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_menu.h
  patches/common/chromium/accelerator.patch
  spec/api-menu-item-spec.js
Labels: 4-0-x

#15521 fix: send NSView* as the response to getNativeWindowHandle() instead of a null handle
  atom/browser/api/atom_api_top_level_window.cc
  atom/browser/native_window.h
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  atom/browser/native_window_views.h
Labels: target/3-0-x, target/4-0-x

#15143 refactor: printing
  BUILD.gn
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/atom_browser_client.cc
  atom/browser/atom_print_preview_message_handler.cc
  atom/browser/atom_print_preview_message_handler.h
  atom/browser/browser_process_impl.cc
  atom/browser/browser_process_impl.h
  atom/browser/common_web_contents_delegate.cc
  atom/browser/printing/print_preview_message_handler.cc
  atom/browser/printing/print_preview_message_handler.h
  atom/common/api/features.cc
  atom/renderer/printing/print_render_frame_helper_delegate.cc
  atom/renderer/printing/print_render_frame_helper_delegate.h
  atom/renderer/renderer_client_base.cc
  atom/utility/atom_content_utility_client.cc
  chromium_src/BUILD.gn
  electron_strings.grdp
  lib/browser/api/web-contents.js
  manifests/electron_content_browser_manifest_overlay.json
  patches/common/chromium/printing.patch
  spec/api-browser-window-spec.js
  spec/api-web-contents-spec.js
Labels: target/4-0-x

#15627 ci: add testing for mksnapshot
  .circleci/config.yml
  appveyor.yml
  script/verify-mksnapshot.py
  spec/fixtures/snapshot-items-available.js
  spec/fixtures/testsnap.js
  vsts.yml
Labels: target/4-0-x

#15094 fix: Menu accelerators not working
  atom/browser/native_window_views.cc
  atom/browser/ui/views/root_view.cc
  atom/browser/ui/views/root_view.h
  spec/api-menu-spec.js
Labels: target/3-0-x, target/4-0-x

#15660 fix: NSWindow crash happening on macos 10.9
  atom/browser/native_window_mac.mm
Labels: target/3-0-x, target/4-0-x

#15656 fix: no longer require submenu for services menuitem
  atom/browser/ui/cocoa/atom_menu_controller.mm
  default_app/menu.js
  docs/api/menu.md
Labels: target/4-0-x

#15662 fix: Menu accelerators not working (#15094) (backport: 4-0-x)
  atom/browser/native_window_views.cc
  atom/browser/ui/views/root_view.cc
  atom/browser/ui/views/root_view.h
  spec/api-menu-spec.js
Labels: 4-0-x, backport

#15674 feat: expose showAboutPanel for MacOS
  atom/browser/api/atom_api_app.cc
  docs/api/app.md
Labels: enhancement :sparkles:, semver/minor, target/4-0-x

#15675 docs: remove unsafe eval section of security tutorial
  docs/tutorial/security.md
Labels: target/4-0-x

#15596 fix: bypass DOM storage quota
  patches/common/chromium/.patches
  patches/common/chromium/dom_storage_limits.patch
  patches/common/chromium/dom_storage_map.patch
  spec/chromium-spec.js
Labels: target/4-0-x

#15677 feat: allow partial setting of window bounds
  docs/api/browser-window.md
  lib/browser/api/browser-window.js
  spec/api-browser-window-spec.js
Labels: enhancement :sparkles:, semver/minor, target/4-0-x

#15698 fix: window.opener in sandboxed renderer no longer null (backport: 4-0-x)
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  brightray/browser/browser_main_parts.cc
  lib/browser/guest-window-manager.js
  patches/common/chromium/frame_host_manager.patch
  spec/api-browser-window-affinity-spec.js
  spec/api-browser-window-spec.js
  spec/chromium-spec.js
  spec/fixtures/api/sandbox.html
  spec/fixtures/module/preload-sandbox.js
Labels: 4-0-x, backport

#15688 fix: bypass DOM storage quota (backport: 4-0-x)
  patches/common/chromium/.patches
  patches/common/chromium/dom_storage_limits.patch
  patches/common/chromium/dom_storage_map.patch
  spec/chromium-spec.js
Labels: 4-0-x, backport

#15716 build: use different directory for generated breakpad symbols
  .circleci/config.yml
  appveyor.yml
  script/dump-symbols.py
  script/upload-symbols.py
  script/zip-symbols.py
  vsts.yml
Labels: target/4-0-x

#15699 feat: allow partial setting of window bounds
  docs/api/browser-window.md
  lib/browser/api/browser-window.js
  spec/api-browser-window-spec.js
Labels: 4-0-x, backport

#15751 docs: mention the limits of nativeWindowOpen (4-0-x)
  docs/api/browser-window.md
Labels: target/3-0-x

#15756 fix: revert: "window.open site instance should belong to the same bro…
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  brightray/browser/browser_main_parts.cc
  lib/browser/guest-window-manager.js
  patches/common/chromium/frame_host_manager.patch
  spec/api-browser-window-affinity-spec.js
  spec/api-browser-window-spec.js
  spec/chromium-spec.js
  spec/fixtures/api/sandbox.html
  spec/fixtures/module/preload-sandbox.js
Labels: merged/4-0-x

#15766 docs: add note about win_delay_load_hook
  docs/api/breaking-changes.md
  docs/tutorial/using-native-node-modules.md
Labels: target/4-0-x

#15672 fix: no longer require submenu for services menuitem
  atom/browser/ui/cocoa/atom_menu_controller.mm
  default_app/main.js
  docs/api/menu.md
Labels: 3-0-x

#15035 feat: Add app.getLocaleCountryCode() method for region detection
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_app.h
  docs/api/app.md
  spec/api-app-spec.js
Labels: semver/minor

#15563 fix: load the chrome.* API on chrome-extension pages in sandbox mode
  atom/renderer/atom_sandboxed_renderer_client.cc
  lib/sandboxed_renderer/init.js
Labels: target/2-0-x, target/3-0-x, target/4-0-x

#15784 fix: schedule a paint after BrowserView's background is set
  atom/browser/native_browser_view_views.cc
Labels: target/2-0-x, target/3-0-x, target/4-0-x

#15770 build: fix native_mksnapshot build
  .circleci/config.yml
  build/args/native_mksnapshot.gn
  build/zip.py
  patches/common/v8/.patches
  patches/common/v8/do_not_run_arm_arm64_mksnapshot_binaries.patch
Labels: target/4-0-x

#15723 feat: add registerAccelerator flag to allow menu items to optionally skip accelerator registration
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_menu.h
  atom/browser/ui/accelerator_util.cc
  atom/browser/ui/atom_menu_model.cc
  atom/browser/ui/atom_menu_model.h
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.js
  lib/browser/api/menu-item.js
  lib/browser/api/menu.js
Labels: target/3-0-x, target/4-0-x

#12686 fix: handle window.open events in BrowserView
  atom/browser/native_window_mac.mm
  lib/browser/api/browser-window.js
  lib/browser/api/web-contents.js
  spec/api-browser-view-spec.js
Labels: semver/minor

#13852 feat: add activate option to webContents.openDevTools
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/ui/cocoa/atom_inspectable_web_contents_view.h
  atom/browser/ui/cocoa/atom_inspectable_web_contents_view.mm
  atom/browser/ui/inspectable_web_contents.h
  atom/browser/ui/inspectable_web_contents_impl.cc
  atom/browser/ui/inspectable_web_contents_impl.h
  atom/browser/ui/inspectable_web_contents_view.h
  atom/browser/ui/inspectable_web_contents_view_mac.h
  atom/browser/ui/inspectable_web_contents_view_mac.mm
  atom/browser/ui/views/inspectable_web_contents_view_views.cc
  atom/browser/ui/views/inspectable_web_contents_view_views.h
  docs/api/web-contents.md
  spec/api-web-contents-spec.js
Labels: semver/minor

#15733 fix: osr windows respect display scale factor
  atom/browser/osr/osr_render_widget_host_view.cc
  atom/browser/osr/osr_render_widget_host_view.h
Labels: app-feedback-program, target/4-0-x

#15805 fix: prevent bluetooth device list from growing without bound
  atom/browser/lib/bluetooth_chooser.cc
  atom/browser/lib/bluetooth_chooser.h
  electron_paks.gni
Labels: bug :beetle:, semver/patch, target/2-0-x, target/3-0-x, target/4-0-x, wip

#14865 fix: checkboxes not rendering in mojave
  patches/common/chromium/.patches
  patches/common/chromium/mac_fix_form_control_rendering_on_10_14_mojave.patch
Labels: target/2-0-x, target/3-0-x, target/4-0-x

#15884 fix: ignore unused freopen result
  atom/app/atom_main.cc
Labels: target/4-0-x

#15836 fix: backport patch that ensures that cookie store is always created
  atom/browser/net/url_request_context_getter.cc
  patches/common/chromium/.patches
  patches/common/chromium/ensure_cookie_store.patch
  spec/api-session-spec.js
  spec/fixtures/api/cookie-app/main.js
  spec/fixtures/api/cookie-app/package.json
Labels: target/4-0-x

#15887 ci: clean git before building
  vsts.yml
Labels: target/3-0-x, target/3-1-x

#15900 chore: improve granular release cleanup
  script/release-artifact-cleanup.js
Labels: target/3-0-x, target/3-1-x, target/4-0-x
