Repository electron/electron, pull requests merged in 2018-08, with the labels that each got.

#13845 fix: some APIs modified for ASAR support cannot be util.promisify'ed
  lib/common/asar.js
  spec/asar-spec.js
Labels: target/2-0-x, target/3-0-x

#13920 fix: Improve --enable-features/--disable-features handling
  atom/browser/atom_browser_main_parts.cc
  brightray/browser/browser_main_parts.cc
  brightray/browser/browser_main_parts.h
Labels: target/2-0-x, target/3-0-x

#13903 docs: dipToScreenRect / screenToDipRect - window can be null
  docs/api/screen.md
Labels: target/3-0-x

#13802 docs: [gn] update build instructions
  docs/development/build-instructions-gn.md
Labels: semver/not-consumer-facing

#13828 ci: [gn] add Mac support to VSTS build
  vsts-gn.yml
Labels: semver/not-consumer-facing

#13898 chore: Merge PR #13359 from electron/release-notes-generator
  package-lock.json
  package.json
  script/release-notes/.gitignore
  script/release-notes/index.js
  script/release-notes/legacy-pr-semantic-map.csv
Labels: target/2-0-x

#13966 fix: Prevent menu update while it's open (backport: 2-0-x)
  atom/browser/api/atom_api_menu_mac.mm
Labels: backport

#13973 feat: add location url to "Node.js Integration with Remote Content" warning
  lib/renderer/security-warnings.js
Labels: target/3-0-x

#13941 fix: ipcRemote.sendSync() in lib/isolated_renderer/init.js
  lib/isolated_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/api/isolated.html
  spec/webview-spec.js
Labels: bug/regression :leftwards_arrow_with_hook:, target/3-0-x

#13999 docs: fix typos in security.md
  docs/tutorial/security.md
Labels: documentation :notebook:, target/3-0-x

#13542 feat: Add creationTime function to process
  atom/common/api/atom_bindings.cc
  atom/common/api/atom_bindings.h
  docs/api/process.md
  package-lock.json
  package.json
  spec/api-process-spec.js
Labels: semver/nonbreaking-feature

#13306 feat: On macOS, Closing Notifications Triggers the 'close' Event
  brightray/browser/mac/cocoa_notification.h
  brightray/browser/mac/cocoa_notification.mm
  brightray/browser/mac/notification_center_delegate.mm
Labels: semver/nonbreaking-feature

#14049 fix: Fix flaky sandbox tests
  spec/fixtures/api/mixed-sandbox-app/main.js
Labels: target/2-0-x, target/3-0-x

#14058 fix: notify request context shutdown on IO before cleanup
  atom/browser/api/atom_api_cookies.cc
  atom/browser/api/atom_api_cookies.h
  atom/browser/api/atom_api_protocol.h
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_web_request.cc
  atom/browser/atom_browser_context.cc
  atom/browser/atom_browser_context.h
  atom/browser/net/atom_url_request.cc
  atom/browser/net/url_request_fetch_job.cc
  atom/browser/net/url_request_fetch_job.h
  atom/browser/request_context_delegate.cc
  atom/browser/request_context_delegate.h
  atom/common/options_switches.cc
  atom/common/options_switches.h
  brightray/browser/browser_context.cc
  brightray/browser/browser_context.h
  brightray/browser/inspectable_web_contents_impl.cc
  brightray/browser/url_request_context_getter.cc
  brightray/browser/url_request_context_getter.h
  brightray/common/switches.cc
  brightray/common/switches.h
  filenames.gypi
Labels: target/3-0-x

#14102 fix: add a hidden option to disable remote dereferencing
  lib/browser/objects-registry.js
Labels: target/2-0-x, target/3-0-x

#14125 docs: fix electron.d.ts typings
  docs/api/web-frame.md
Labels: target/1-8-x, target/2-0-x, target/3-0-x

#13869 fix: use OOPIF for webview tag
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/api/atom_api_web_view_manager.cc
  atom/browser/common_web_contents_delegate.cc
  atom/browser/common_web_contents_delegate.h
  atom/browser/web_contents_zoom_controller.cc
  atom/browser/web_contents_zoom_controller.h
  atom/browser/web_view_guest_delegate.cc
  atom/browser/web_view_guest_delegate.h
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
  atom/renderer/renderer_client_base.cc
  atom/renderer/renderer_client_base.h
  brightray/browser/browser_main_parts.cc
  brightray/browser/inspectable_web_contents.cc
  brightray/browser/inspectable_web_contents.h
  brightray/browser/inspectable_web_contents_impl.cc
  brightray/browser/inspectable_web_contents_impl.h
  brightray/browser/mac/bry_inspectable_web_contents_view.h
  brightray/browser/mac/bry_inspectable_web_contents_view.mm
  brightray/browser/views/inspectable_web_contents_view_views.cc
  lib/browser/guest-view-manager.js
  lib/renderer/web-view/guest-view-internal.js
  lib/renderer/web-view/web-view-attributes.js
  lib/renderer/web-view/web-view-constants.js
  lib/renderer/web-view/web-view.js
  spec/chromium-spec.js
  spec/webview-spec.js
Labels: target/3-0-x

#13992 fix: Stricter Testing For Menu Items
  docs/api/menu-item.md
  lib/browser/api/menu.js
  spec/api-menu-spec.js
Labels: enhancement :sparkles:

#14186 fix: add dist tags for release branches
  script/publish-to-npm.js
Labels: target/3-0-x

#14177 fix: electron path for postinstall
  npm/install.js
Labels: target/3-0-x

#14196 fix: Dialog does not close on ESCAPE if defaultId is set (Mac)
  atom/browser/ui/message_box_mac.mm
Labels: target/2-0-x, target/3-0-x

#14207 chore: match the bump commit exactly, reverts should not count
  script/prepare-release.js
Labels: target/2-0-x, target/3-0-x

#14212 chore: add option to return next version from prepare-release
  script/prepare-release.js
Labels: target/2-0-x, target/3-0-x

#14074 fix: enable osr
  atom/browser/osr/osr_render_widget_host_view.cc
  atom/browser/osr/osr_render_widget_host_view.h
  atom/browser/osr/osr_render_widget_host_view_mac.mm
  brightray/browser/browser_main_parts.cc
  features.gypi
Labels: target/3-0-x

#14220 chore: remove autorelease check logic
  script/prepare-release.js
Labels: target/2-0-x, target/3-0-x

#13505 feat: expose missing process APIs in sandboxed renderers
  atom/common/api/atom_bindings.cc
  atom/common/api/atom_bindings.h
  atom/common/node_bindings.cc
  atom/common/node_bindings.h
  atom/renderer/atom_sandboxed_renderer_client.cc
  atom/renderer/atom_sandboxed_renderer_client.h
  docs/api/process.md
  lib/browser/rpc-server.js
  lib/sandboxed_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/module/preload-sandbox.js
Labels: semver/nonbreaking-feature

#14230 Print error when removed webview attribute is used
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  docs/api/breaking-changes.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  lib/browser/api/web-contents.js
  lib/renderer/web-view/web-view.js
Labels: target/3-0-x

#14231 fix: add method and referrer properties to app login event
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_app.h
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  atom/browser/browser.cc
  atom/browser/browser.h
  atom/browser/browser_observer.h
  atom/browser/login_handler.cc
  atom/browser/login_handler.h
  atom/browser/net/atom_network_delegate.cc
  atom/browser/net/atom_network_delegate.h
  atom/common/options_switches.cc
  atom/common/options_switches.h
  brightray/browser/network_delegate.cc
  brightray/browser/network_delegate.h
  brightray/browser/url_request_context_getter.cc
  brightray/filenames.gypi
Labels: target/3-0-x

#14253 fix: opt into location services once device service has been started
  BUILD.gn
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  atom/browser/atom_browser_main_parts.cc
  atom/browser/atom_browser_main_parts.h
  atom/browser/atom_permission_manager.cc
  atom/browser/fake_location_provider.cc
  atom/browser/fake_location_provider.h
  atom/common/api/features.cc
  electron.gyp
  filenames.gypi
  spec/chromium-spec.js
  spec/fixtures/pages/geolocation/index.html
Labels: target/3-0-x

#14286 refactor: use std::string instead of base::string16 for IPC channel names
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/common/api/api_messages.h
  atom/common/api/remote_callback_freer.cc
  atom/common/api/remote_object_freer.cc
  atom/renderer/api/atom_api_renderer_ipc.cc
  atom/renderer/api/atom_api_renderer_ipc.h
  atom/renderer/atom_render_frame_observer.cc
  atom/renderer/atom_render_frame_observer.h
  atom/renderer/atom_sandboxed_renderer_client.cc
  spec/api-ipc-renderer-spec.js
  spec/fixtures/pages/ping-pong.html
Labels: enhancement :sparkles:, platform/all

#13808 fix: issue 10962, crash when open devtool
  brightray/browser/inspectable_web_contents_impl.cc
Labels: app-feedback-program, target/2-0-x, target/3-0-x

#14312 fix: don't expose view APIs when not enabled
  atom/common/api/features.cc
  lib/browser/api/module-list.js
Labels: target/3-0-x

#14322 fix: don't crash on tray.setContextMenu(null)
  atom/browser/api/atom_api_tray.cc
  atom/browser/ui/tray_icon_cocoa.mm
  docs/api/tray.md
  spec/api-tray-spec.js
Labels: target/1-8-x, target/2-0-x, target/3-0-x

#14297 fix: dont parse arguments after a -- in the inspector
  atom/browser/node_debugger.cc
  atom/common/node_bindings.cc
Labels: target/1-7-x, target/1-8-x, target/2-0-x, target/3-0-x

#14310 fix: don't expose desktopCapturer in sandboxed renderers when the feature is disabled
  lib/browser/rpc-server.js
  lib/sandboxed_renderer/api/exports/electron.js
  lib/sandboxed_renderer/api/module-list.js
  lib/sandboxed_renderer/init.js
Labels: target/3-0-x

#14334 fix: dont parse arguments after a -- in the inspector (#14297) (2-0-x)
  atom/browser/node_debugger.cc
  atom/common/node_bindings.cc
Labels: target/1-7-x, target/1-8-x

#14283 feat: 'will-move' event for windows.
  atom/browser/api/atom_api_top_level_window.cc
  atom/browser/api/atom_api_top_level_window.h
  atom/browser/native_window.cc
  atom/browser/native_window.h
  atom/browser/native_window_observer.h
  atom/browser/native_window_views_win.cc
  docs/api/browser-window.md
Labels: semver/minor

#13925 feat: add session.setPermissionCheckHandler
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/atom_permission_manager.cc
  atom/browser/atom_permission_manager.h
  atom/browser/web_contents_permission_helper.cc
  atom/browser/web_contents_permission_helper.h
  docs/api/session.md
  spec/chromium-spec.js
  spec/static/main.js
Labels: semver/minor

#14347 fix: crash when tray is destroyed
  atom/browser/ui/tray_icon_cocoa.mm
Labels: target/1-8-x, target/2-0-x, target/3-0-x

#14107 fix: create persistent channel ID store when cookie store is persistent
  brightray/BUILD.gn
  brightray/brightray.gyp
  brightray/browser/url_request_context_getter.cc
Labels: target/3-0-x

#14324 fix: use OS process handle to clear object registry
  atom/browser/api/atom_api_web_contents.cc
  atom/renderer/renderer_client_base.cc
  lib/browser/objects-registry.js
  spec/fixtures/api/render-view-deleted.html
Labels: target/3-0-x

#14344 fix: emit focus/blur events for webview
  lib/browser/guest-view-manager.js
  lib/renderer/init.js
  lib/renderer/web-view/guest-view-internal.js
  lib/renderer/web-view/web-view.js
  spec/webview-spec.js
Labels: target/3-0-x

#14369 docs: keyboard listeners no longer work on webview
  docs/api/breaking-changes.md
Labels: target/3-0-x

#14296 feat: Add electron version to framework
  BUILD.gn
  atom/common/resources/mac/Info.plist
Labels: enhancement :sparkles:, semver/minor

#13851 fix: allow Tray with title only (without icon) on Mac
  atom/browser/ui/tray_icon_cocoa.mm
  spec/api-tray-spec.js
Labels: semver/patch, target/2-0-x, target/3-0-x

#13497 test: update power/notification specs to expect
  spec/api-notification-spec.js
  spec/api-power-monitor-spec.js
  spec/api-power-save-blocker-spec.js
Labels: semver/minor

#14400 fix: use flexbox to style webview
  docs/api/webview-tag.md
  lib/renderer/web-view/web-view.js
Labels: target/3-0-x

#14122 feat: allow window above full screen windows on mac
  atom/browser/api/atom_api_top_level_window.cc
  atom/browser/api/atom_api_top_level_window.h
  atom/browser/native_window.h
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  atom/browser/native_window_views.h
  docs/api/browser-window.md
Labels: semver/minor
