Repository electron/electron, pull requests merged in 2018-03, with the labels that each got.

#12234 fix: Incorrect warnings in webviews
  lib/renderer/security-warnings.js
Labels: target/2-0-x

#12228 Parent's visibility trumps inherited 'show' option
  lib/browser/guest-window-manager.js
  spec/chromium-spec.js
Labels: target/1-8-x, target/2-0-x

#12241 spec: isolate sw file scheme spec storage with temp partition
  spec/chromium-spec.js
Labels: target/2-0-x

#12190 Ensure that a document has been created before sending IPC messages
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/api/event.cc
  atom/browser/api/event.h
  atom/browser/api/event_emitter.cc
  atom/browser/api/event_emitter.h
  atom/common/api/api_messages.h
  atom/common/api/remote_callback_freer.cc
  atom/common/api/remote_object_freer.cc
  atom/renderer/api/atom_api_renderer_ipc.cc
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/atom_render_frame_observer.cc
  atom/renderer/atom_render_frame_observer.h
  atom/renderer/atom_render_view_observer.cc
  atom/renderer/atom_render_view_observer.h
  atom/renderer/atom_renderer_client.cc
  atom/renderer/atom_sandboxed_renderer_client.cc
  atom/renderer/renderer_client_base.cc
Labels: merged/2-0-x

#12253 fix: Ensure that `getLastCrashReport()` is actually the last crash report
  lib/common/api/crash-reporter.js
  spec/api-crash-reporter-spec.js
Labels: target/1-8-x, target/2-0-x

#12254 browser: fix crash when using getWebPreferences api with devtools webContents
  atom/browser/api/atom_api_web_contents.cc
  spec/api-web-contents-spec.js
Labels: merged/2-0-x

#12198 Fixed passing of exception to the system crash handler
  atom/common/crash_reporter/crash_reporter_win.cc
Labels: target/1-8-x, target/2-0-x

#12217 Enable easy rebuild of native modules for unreleased electron
  package.json
  script/serve-node-headers.py
  script/upload-node-checksums.py
Labels: target/1-8-x, target/2-0-x

#12257 add missing report.length > 1 assertion
  spec/api-crash-reporter-spec.js
Labels: target/2-0-x

#11807 feat(powerMonitor): expose interface to query system idle state
  atom/browser/api/atom_api_power_monitor.cc
  atom/browser/api/atom_api_power_monitor.h
  atom/browser/atom_browser_main_parts.cc
  docs/api/power-monitor.md
  spec/api-power-monitor-spec.js
Labels: pending-feature-release

#12263 fix remote setInterval flake
  spec/node-spec.js
Labels: target/1-8-x, target/2-0-x

#12266 fix remote setInterval flake (1.8.x)
  spec/node-spec.js
Labels: backport

#12265 fix remote setInterval flake (2.0.x)
  spec/node-spec.js
Labels: backport

#12282 Fix require on network share path
  lib/renderer/init.js
Labels: target/1-8-x, target/2-0-x

#12193 Fixes electron/electron#12147
  lib/browser/api/navigation-controller.js
Labels: target/1-8-x, target/2-0-x

#12272 Set appropriate defaults for webview options
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/web_contents_preferences.cc
  atom/browser/web_contents_preferences.h
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  spec/api-browser-window-spec.js
  spec/chromium-spec.js
  spec/fixtures/pages/window-opener-no-web-view-tag.html
  spec/fixtures/pages/window-opener-web-view.html
Labels: target/1-7-x

#12271 Set appropriate defaults for webview options
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/web_contents_preferences.cc
  atom/browser/web_contents_preferences.h
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  lib/renderer/security-warnings.js
  spec/api-browser-window-spec.js
  spec/chromium-spec.js
  spec/fixtures/pages/window-opener-no-web-view-tag.html
  spec/fixtures/pages/window-opener-web-view.html
Labels: target/2-0-x

#12294 Backport (1-7-x) - Set appropriate defaults for webview options
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/web_contents_preferences.cc
  atom/browser/web_contents_preferences.h
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  spec/api-browser-window-spec.js
  spec/chromium-spec.js
  spec/fixtures/pages/window-opener-no-web-view-tag.html
  spec/fixtures/pages/window-opener-web-view.html
Labels: backport

#12274 Document BrowserView.{destroy,isDestroyed}
  docs/api/browser-view.md
  spec/api-browser-view-spec.js
Labels: target/1-8-x, target/2-0-x

#12309 fix: Correctly detect insecure resources
  lib/renderer/security-warnings.js
Labels: target/2-0-x

#12325 Check menu.popup options are an object
  lib/browser/api/menu.js
  spec/api-menu-spec.js
Labels: target/2-0-x

#12300 Better GTK+ Menu color support
  atom/browser/native_window_views.cc
  atom/browser/ui/views/menu_bar.cc
  atom/browser/ui/views/menu_bar.h
  atom/browser/ui/views/submenu_button.cc
  atom/browser/ui/views/submenu_button.h
Labels: target/2-0-x

#12351 Update CI to use Node.js 8
  .circleci/config.yml
  Dockerfile
  Dockerfile.arm64v8
  Dockerfile.armv7
  Dockerfile.circleci
  Jenkinsfile.arm64
Labels: target/1-7-x, target/1-8-x, target/2-0-x

#12342 Remove the race condition between new process creation and context release
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/atom_browser_client.cc
  atom/common/options_switches.cc
  atom/common/options_switches.h
  lib/browser/rpc-server.js
  lib/renderer/api/remote.js
Labels: target/2-0-x

#12348 Update draggable regions when changing BrowserView
  atom/browser/api/atom_api_browser_view.cc
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window_mac.mm
  atom/browser/native_browser_view.cc
  atom/browser/native_browser_view.h
  atom/browser/native_browser_view_mac.h
  atom/browser/native_browser_view_mac.mm
  atom/browser/native_browser_view_views.cc
  atom/browser/native_browser_view_views.h
Labels: target/1-8-x, target/2-0-x

#12388 Use appname as trayicon's default tooltip on Linux
  atom/browser/ui/tray_icon_gtk.cc
Labels: target/2-0-x

#12395 Fix dark mode tray highlighting bug
  atom/browser/ui/tray_icon_cocoa.mm
Labels: target/2-0-x

#12093 Workspace notifications support on macOS
  atom/browser/api/atom_api_system_preferences.cc
  atom/browser/api/atom_api_system_preferences.h
  atom/browser/api/atom_api_system_preferences_mac.mm
  docs/api/system-preferences.md
Labels: platform/macOS

#12404 Fix: Do not block main process for async dialog
  atom/browser/ui/file_dialog_mac.mm
Labels: target/1-8-x, target/2-0-x

#12426 Provide an easy way to use a local build of Electron
  .gitignore
  docs/api/environment-variables.md
  npm/index.js
  npm/install.js
Labels: pending-feature-release

#12428 update doc for setProgressBar
  docs/api/browser-window.md
Labels: target/1-8-x, target/2-0-x

#12449 Fix disabling accelerators
  lib/browser/api/menu.js
Labels: target/1-8-x, target/2-0-x
