Repository electron/electron, pull requests merged in 2018-05, with the labels that each got.

#12756 Support policy
  README.md
  docs/README.md
  docs/development/issues.md
  docs/tutorial/support.md
  docs/tutorial/supported-platforms.md
Labels: target/2-0-x

#12741 Fix crash when releasing a script context that never had node injected
  atom/renderer/atom_renderer_client.cc
Labels: target/2-0-x

#12822 Fix the type information in in-app-purchase.md
  docs/api/in-app-purchase.md
Labels: target/2-0-x

#12825 Fix invisible menu items no longer triggering
  lib/browser/api/menu.js
Labels: target/2-0-x

#12362 Add menu item order control
  docs/api/menu.md
  filenames.gypi
  lib/browser/api/menu-utils.js
  lib/browser/api/menu.js
  spec/api-menu-spec.js
Labels: semver/breaking-change

#12841 fix: listeners out of limit warning
  lib/renderer/content-scripts-injector.js
Labels: target/2-0-x

#12656 add app.isPackaged
  docs/api/app.md
  lib/browser/api/app.js
  spec/api-app-spec.js
Labels: semver/nonbreaking-feature

#12922 Fix contents.setSize(options) documentation in web-contents.md
  docs/api/web-contents.md
Labels: documentation :notebook:, target/1-8-x, target/2-0-x

#12844 fix: support multiple inherited ubuntu session for indicators
  lib/browser/init.js
Labels: bug :beetle:, platform/linux/ubuntu, target/2-0-x

#12991 build: don't upload aliased arm builds anymore
  script/upload.py
Labels: semver/breaking-change

#13003 Only expand maximum size constraint if there was a constraint originally
  atom/browser/native_window.cc
Labels: target/2-0-x

#12877 Refactor sandbox preload initialization.
  lib/browser/rpc-server.js
  lib/renderer/api/remote.js
  lib/sandboxed_renderer/init.js
Labels: target/2-0-x

#12977 Add a tag to libchromiumcontent when a release is created.
  script/release.js
Labels: target/1-7-x, target/1-8-x, target/2-0-x

#13065 Do not capture cookies and credentials in net log
  brightray/browser/net_log.cc
Labels: bug/regression :leftwards_arrow_with_hook:
