Repository electron/electron, pull requests merged in 2018-04, with the labels that each got.

#12488 WebFrame.setVisualZoomLevelLimits sets user-agent scale constraints
  atom/renderer/api/atom_api_web_frame.cc
Labels: target/1-8-x, target/2-0-x

#12511 Handle in-app-purchase less fatally on non-Darwin
  lib/browser/api/in-app-purchase.js
Labels: target/2-0-x

#12485 add moveTop API to move window z-oder to top for win32, mac
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window.h
  atom/browser/native_window.h
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  atom/browser/native_window_views.h
  docs/api/browser-window.md
Labels: pending-feature-release

#12417 Add a display_id parameter to the desktopCapturer API.
  atom/browser/api/atom_api_desktop_capturer.cc
  atom/browser/api/atom_api_desktop_capturer.h
  docs/api/structures/desktop-capturer-source.md
  lib/browser/desktop-capturer.js
  lib/renderer/api/desktop-capturer.js
  spec/api-desktop-capturer-spec.js
Labels: pending-feature-release

#12281 Mouse forward on macOS
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
  docs/api/browser-window.md
Labels: pending-feature-release

#12527 Fix event leak on reuse of touchbar item
  lib/browser/api/touch-bar.js
Labels: target/1-8-x, target/2-0-x

#12556 Correct the default of allowRunningInsecureContent as per docs
  atom/browser/web_contents_preferences.cc
Labels: target/1-7-x, target/1-8-x, target/2-0-x

#12694 handle remote exception
  lib/browser/rpc-server.js
  lib/renderer/api/remote.js
  spec/api-remote-spec.js
  spec/fixtures/module/exception.js
Labels: semver/nonbreaking-feature

#12582 Add sccache option to bootstrap
  script/bootstrap.py
  toolchain.gypi
Labels: target/1-8-x, target/2-0-x

#12714 Screen Lock / Unlock events
  atom/browser/api/atom_api_power_monitor.cc
  atom/browser/api/atom_api_power_monitor.h
  atom/browser/api/atom_api_power_monitor_mac.mm
  atom/browser/api/atom_api_power_monitor_win.cc
  docs/api/power-monitor.md
  electron.gyp
  filenames.gypi
Labels: semver/nonbreaking-feature
