Repository electron/electron, pull requests merged in 2019-07, with the labels that each got.

#19018 docs: fix heading level for power-monitor docs
  docs/api/power-monitor.md
Labels: 5-0-x, backport, target/4-2-x

#18995 fix: Correct modal focus behavior on macOS
  shell/browser/ui/cocoa/atom_ns_window_delegate.mm
  spec/api-browser-window-spec.js
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19040 docs: fix typo in 5-0-x api docs
  docs/api/breaking-changes.md
Labels: documentation :notebook:

#19000 feat: improve callback value for webContents.print()
  docs/api/web-contents.md
  patches/chromium/printing.patch
Labels: component/printing, semver/minor

#19064 fix: post_task include error
  atom/browser/ui/tray_icon_cocoa.mm
Labels: 4-2-x, backport, fast-track 🚅

#19055 docs: make the dialog example work out of the box on all 3 platforms
  docs/api/dialog.md
Labels: documentation :notebook:, new-pr 🌱

#19071 docs: fix undefined isMac in menu example
  docs/api/menu.md
Labels: new-pr 🌱

#19037 fix: silent printing mode
  patches/common/chromium/blink_world_context.patch
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/command-ismediakey.patch
  patches/common/chromium/disable_color_correct_rendering.patch
  patches/common/chromium/disable_user_gesture_requirement_for_beforeunload_dialogs.patch
  patches/common/chromium/printing.patch
  patches/common/chromium/render_widget_host_view_base.patch
  patches/common/chromium/viz_osr.patch
  patches/common/chromium/web_contents.patch
Labels: 6-0-x, backport

#19013 fix: dark mode tray opacity on Mojave
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/browser/ui/tray_icon_cocoa.mm
Labels: component/tray, fast-track 🚅, target/5-0-x

#19090 chore: remove unused BrowserWindow.fromDevToolsWebContents
  lib/browser/api/browser-window.js
  spec/api-browser-window-spec.js
Labels: new-pr 🌱

#19098 chore: fix node ref to point to the ref that was merged
  DEPS
Labels: fast-track 🚅

#19072 chore: deprecate some NSVisualEffectMaterial types
  docs/api/browser-window.md
  shell/browser/native_window_mac.mm
  spec/ts-smoke/electron/main.ts
Labels: platform/macOS,  catalina

#19100 test: disable IAP tests that hit Apple servers
  spec/api-in-app-purchase-spec.js
Labels: fast-track 🚅, target/3-1-x, target/4-2-x, target/5-0-x

#19101 fix: handle no env in externsion world set up
  shell/renderer/atom_renderer_client.cc
Labels: new-pr 🌱, target/6-0-x

#19103 fix: use binding.ipc instead of binding.sendTo which is undefined
  lib/renderer/ipc-renderer-internal.ts
Labels: new-pr 🌱, target/6-0-x

#19102 build: ensure that we bundle the correct version of @types/node
  npm/package.json
  spec-main/types-spec.ts
Labels: target/6-0-x

#19094 feat: implement net module with NetworkService
  filenames.gni
  shell/browser/api/atom_api_net.cc
  shell/browser/api/atom_api_url_request.h
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/api/atom_api_url_request_ns.h
Labels: new-pr 🌱

#19077 fix: check parent-child relationship in canAccessWindow
  lib/browser/guest-window-manager.js
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19132 Revert "feat: only allow bundled preload scripts (#17308)"
  docs/api/breaking-changes.md
  docs/api/browser-window.md
  docs/api/session.md
  docs/api/webview-tag.md
  filenames.gni
  lib/browser/rpc-server.js
  lib/common/path-utils.ts
  lib/renderer/init.ts
  spec/api-web-contents-spec.js
Labels: 6-0-x, backport

#19139 refactor: don't expose isPromise as an internal module
  filenames.auto.gni
  lib/browser/rpc-server.js
  lib/common/api/module-list.js
  lib/common/is-promise.ts
  lib/renderer/api/remote.js
  lib/sandboxed_renderer/api/module-list.js
Labels: new-pr 🌱

#19158 fix: dump correct breakpad symbols on macOS
  .circleci/config.yml
  BUILD.gn
  appveyor.yml
  build/dump_syms.py
  build/extract_symbols.gni
  script/dump-symbols.py
  tools/win/generate_breakpad_symbols.py
Labels: 4-2-x, new-pr 🌱

#19155 fix: dump correct breakpad symbols on macOS
  .circleci/config.yml
  BUILD.gn
  appveyor.yml
  build/dump_syms.py
  build/extract_symbols.gni
  script/dump-symbols.py
  tools/win/generate_breakpad_symbols.py
Labels: 6-0-x, new-pr 🌱

#19157 fix: dump correct breakpad symbols on macOS
  .circleci/config.yml
  BUILD.gn
  appveyor.yml
  build/dump_syms.py
  build/extract_symbols.gni
  script/dump-symbols.py
  tools/win/generate_breakpad_symbols.py
Labels: 5-0-x, new-pr 🌱

#19126 docs: remove non-existent `appearance-changed` event
  docs/api/system-preferences.md
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19144 fix: Windows OnSecreenKeyboard for various mouse events (4-2-x)
  patches/common/chromium/.patches
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/crashpad_http_status.patch
  patches/common/chromium/do_not_show_virtual_keyboard_for_all_mouse_inputs.patch
  patches/common/chromium/enable_quic_proxies_for_https_urls.patch
  patches/common/chromium/filesystem_harden_against_overflows_of_operationid_a_bit_better.patch
  patches/common/chromium/fire_caret_location_change_when_focus_moves_from_ui_to_content.patch
  patches/common/chromium/intersection-observer.patch
  patches/common/chromium/mac_fix_form_control_rendering_on_10_14_mojave.patch
  patches/common/chromium/make_--explicitly-allowed-ports_work_with_networkservice.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/setup_the_observer_before_calling_displayvirtualkeyboard.patch
  patches/common/chromium/tabbed_window_lagging.patch
  patches/common/chromium/webview_cross_drag.patch
Labels: 4-2-x

#19171 ci: do not use the MOCHA_FILE env variable
  .circleci/config.yml
  script/spec-runner.js
Labels: target/6-0-x

#19172 ci: add check for dist zip file changes
  .circleci/config.yml
  appveyor.yml
  script/generate-zip-manifest.py
  script/zip_manifests/check-zip-manifest.py
  script/zip_manifests/dist_zip.linux.arm.manifest
  script/zip_manifests/dist_zip.linux.arm64.manifest
  script/zip_manifests/dist_zip.linux.x64.manifest
  script/zip_manifests/dist_zip.linux.x86.manifest
  script/zip_manifests/dist_zip.mac.x64.manifest
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  script/zip_manifests/dist_zip.win.ia32.manifest
  script/zip_manifests/dist_zip.win.x64.manifest
Labels: 6-0-x, backport

#18990 fix: do not wait on promise returned by remote APIs
  docs/api/webview-tag.md
  lib/common/web-view-methods.js
  lib/renderer/web-view/web-view-attributes.ts
  spec/webview-spec.js
Labels: in-flight/6-0-x

#19175 ci: add check for dist zip file changes
  .circleci/config.yml
  appveyor.yml
  build/zip.py
  script/generate-zip-manifest.py
  script/zip_manifests/check-zip-manifest.py
  script/zip_manifests/dist_zip.linux.arm.manifest
  script/zip_manifests/dist_zip.linux.arm64.manifest
  script/zip_manifests/dist_zip.linux.x64.manifest
  script/zip_manifests/dist_zip.linux.x86.manifest
  script/zip_manifests/dist_zip.mac.x64.manifest
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  script/zip_manifests/dist_zip.win.ia32.manifest
  script/zip_manifests/dist_zip.win.x64.manifest
Labels: 4-2-x, backport

#19142 docs: precise nodeIntegrationInSubFrames and node integration for nativeWindowOpen
  docs/api/breaking-changes.md
  docs/api/browser-window.md
Labels: 6-0-x, backport

#19199 refactor: improve function deprecation module
  lib/common/api/deprecate.ts
  spec/api-deprecations-spec.js
  typings/internal-electron.d.ts
Labels: 6-0-x, backport

#19193 fix: don't package resources/inspector in dist.zip
  build/zip.py
Labels: new-pr 🌱

#18773 feat: provide the frame URL with permission requests and checks
  atom/browser/atom_permission_manager.cc
  atom/browser/atom_permission_manager.h
  docs/api/session.md
Labels: backport, fast-track 🚅, target/4-2-x

#19202 chore: deprecate `Tray.setHighlightMode`
  docs/api/breaking-changes.md
  docs/api/tray.md
  lib/browser/api/tray.js
Labels: new-pr 🌱, target/6-0-x

#19173 ci: add check for dist zip file changes
  .circleci/config.yml
  appveyor.yml
  script/generate-zip-manifest.py
  script/zip_manifests/check-zip-manifest.py
  script/zip_manifests/dist_zip.linux.arm.manifest
  script/zip_manifests/dist_zip.linux.arm64.manifest
  script/zip_manifests/dist_zip.linux.x64.manifest
  script/zip_manifests/dist_zip.linux.x86.manifest
  script/zip_manifests/dist_zip.mac.x64.manifest
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  script/zip_manifests/dist_zip.win.ia32.manifest
  script/zip_manifests/dist_zip.win.x64.manifest
Labels: 5-0-x, backport

#19110 feat: add object to subscribe notification callback
  docs/api/system-preferences.md
  shell/browser/api/atom_api_system_preferences.h
  shell/browser/api/atom_api_system_preferences_mac.mm
Labels: semver/minor

#19211 chore: deprecate `Tray.setHighlightMode`
  docs/api/breaking-changes.md
  docs/api/tray.md
  lib/browser/api/tray.js
Labels: 6-0-x, backport, target/5-0-x

#19198 fix: <webview> not working in scriptable popups
  shell/browser/web_contents_preferences.cc
  spec/api-browser-window-spec.js
  spec/fixtures/api/new-window-webview-preload.js
  spec/fixtures/api/new-window-webview.html
  spec/static/main.js
Labels: in-flight/5-0-x, target/6-0-x

#19213 chore: revert key -> main change in window delegate listener
  shell/browser/ui/cocoa/atom_ns_window_delegate.mm
  spec/api-browser-window-spec.js
Labels: new-pr 🌱, target/4-2-x, target/5-0-x, target/6-0-x

#19203 docs: specify possible values for ProcessMetric.type
  docs/api/structures/process-metric.md
Labels: documentation :notebook:, target/6-0-x

#19238 chore: revert key -> main change in window delegate listener
  atom/browser/ui/cocoa/atom_ns_window_delegate.mm
  spec/api-browser-window-spec.js
Labels: 5-0-x, backport

#19239 chore: revert key -> main change in window delegate listener
  atom/browser/ui/cocoa/atom_ns_window_delegate.mm
  spec/api-browser-window-spec.js
Labels: 4-2-x, backport

#19228 fix: add support for prefers-color-scheme CSS query
  shell/browser/atom_browser_client.cc
Labels: target/6-0-x

#19247 docs: Update incorrect author name
  docs/tutorial/testing-on-headless-ci.md
Labels: new-pr 🌱

#19104 fix: serialize messages being sent over chrome message ports
  lib/renderer/chrome-api.ts
Labels: target/5-0-x, target/6-0-x

#19216 fix: exit non-silently when running as root on Linux
  shell/app/atom_main_delegate.cc
Labels: target/5-0-x, target/6-0-x

#18916 feat: app.moveToApplicationsFolder conflict handling
  docs/api/app.md
  shell/browser/api/atom_api_app.cc
  shell/browser/ui/cocoa/atom_bundle_mover.h
  shell/browser/ui/cocoa/atom_bundle_mover.mm
Labels: semver/minor

#19196 docs: differentiate static/instance class props
  docs/api/browser-window.md
  docs/styleguide.md
Labels: documentation :notebook:, target/5-0-x, target/6-0-x

#19258 fix: don't try to dump swiftshader symbols on mac
  BUILD.gn
Labels: 4-2-x, fast-track 🚅, target/5-0-x

#19262 fix: don't try to generate swiftshader symbols on arm
  BUILD.gn
Labels: 4-2-x, fast-track 🚅

#19038 fix: silent printing mode
  patches/common/chromium/printing.patch
Labels: 5-0-x, backport

#18924 chore: update to Node.js v12.4.0
  BUILD.gn
  DEPS
  shell/browser/javascript_environment.cc
  shell/browser/node_debugger.cc
  shell/common/api/atom_api_asar.cc
  shell/common/node_bindings.cc
  shell/renderer/atom_renderer_client.cc
  shell/renderer/atom_sandboxed_renderer_client.cc
  shell/renderer/web_worker_observer.cc
  tools/js2c.py
Labels: target/6-0-x

#19206 fix: <webview> not working in scriptable popups
  atom/browser/web_contents_preferences.cc
  spec/api-browser-window-spec.js
  spec/fixtures/api/new-window-webview-preload.js
  spec/fixtures/api/new-window-webview.html
  spec/static/main.js
Labels: 5-0-x, backport

#19263 refactor: replace SetHiddenValue() with mate::Dictionary::SetHidden()
  shell/renderer/renderer_client_base.cc
Labels: new-pr 🌱

#19292 build: move our node fork to our patch system
  DEPS
  patches/common/config.json
  patches/common/node/.patches
  patches/common/node/2019-04-23_version_12_0_0_current.patch
  patches/common/node/allow_embedder_to_reuse_the_per_process_nativemoduleloader.patch
  patches/common/node/build_add_gn_build_files.patch
  patches/common/node/build_allow_embedders_to_override_the_node_module_version_define.patch
  patches/common/node/call_process_log_from_fallback_stream_on_windows.patch
  patches/common/node/chore_add_ability_to_prevent_warn_non_context-aware_native_modules.patch
  patches/common/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/common/node/export_environment_knodecontexttagptr.patch
  patches/common/node/export_nativemodule.patch
  patches/common/node/expose_get_builtin_module_function.patch
  patches/common/node/feat_add_flags_for_low-level_hooks_and_exceptions.patch
  patches/common/node/feat_add_new_built_with_electron_variable_to_config_gypi.patch
  patches/common/node/feat_add_original-fs_module.patch
  patches/common/node/feat_add_uv_loop_watcher_queue_code.patch
  patches/common/node/feat_initialize_asar_support.patch
  patches/common/node/fix_add_default_values_for_enable_lto_and_build_v8_with_gn_in.patch
  patches/common/node/fix_build_and_expose_inspector_agent.patch
  patches/common/node/fix_do_not_define_debugoptions_s_constructors_in_header.patch
  patches/common/node/fix_don_t_create_console_window_when_creating_process.patch
  patches/common/node/fix_export_debugoptions.patch
  patches/common/node/fix_export_libuv_symbols_73.patch
  patches/common/node/fix_export_node_abort_and_assert.patch
  patches/common/node/fix_expose_internalcallbackscope.patch
  patches/common/node/fix_expose_traceeventhelper.patch
  patches/common/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
  patches/common/node/fix_key_gen_apis_are_not_available_in_boringssl.patch
  patches/common/node/fix_make_it_possible_to_change_nobrowserglobals_at_runtime.patch
  patches/common/node/fix_use_bssl_bn_bn2bin_padded_for_ossl_s_bn_bn2binpad.patch
  patches/common/node/fix_wrong_uses_node_allocator_condition.patch
  patches/common/node/fixme_add_back_nativemoduleloader_compileandcall.patch
  patches/common/node/fixme_comment_trace_event_macro.patch
  patches/common/node/fixme_remove_async_id_assertion_check.patch
  patches/common/node/fixme_use_redefined_version_of_internalmodulestat.patch
  patches/common/node/fsevents_fix_file_event_reporting.patch
  patches/common/node/http2_fix_tracking_received_data_for_maxsessionmemory.patch
  patches/common/node/inherit_electron_crashpad_pipe_name_in_child_process.patch
  patches/common/node/make_module_globalpaths_a_reference.patch
  patches/common/node/pass_all_globals_through_require.patch
  patches/common/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
  patches/common/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
  patches/common/node/src_disable_node_use_v8_platform_in_node_options.patch
  patches/common/node/src_only_run_preloadmodules_if_the_preload_array_is_not_empty.patch
  patches/common/node/src_read_break_node_first_line_from_the_inspect_options.patch
  patches/common/node/src_use_check_false_in_switch_default_case.patch
Labels: fast-track 🚅

#19288 refactor: use NativeTheme dark mode detection on macOS 10.14+
  shell/browser/api/atom_api_system_preferences_mac.mm
  shell/browser/ui/tray_icon_cocoa.mm
Labels: new-pr 🌱, target/5-0-x, target/6-0-x

#19260 fix: don't execute preload scripts for internal <iframe> in <webview> when nodeIntegrationInSubFrames is enabled
  shell/renderer/atom_render_frame_observer.cc
  shell/renderer/atom_renderer_client.cc
  shell/renderer/atom_sandboxed_renderer_client.cc
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
  spec/api-subframe-spec.js
  spec/fixtures/sub-frames/webview-iframe-preload.js
Labels: target/5-0-x, target/6-0-x

#19298 fix: don't execute preload scripts for internal <iframe> in <webview> when nodeIntegrationInSubFrames is enabled
  atom/renderer/atom_render_frame_observer.cc
  atom/renderer/atom_renderer_client.cc
  atom/renderer/atom_sandboxed_renderer_client.cc
  atom/renderer/renderer_client_base.cc
  atom/renderer/renderer_client_base.h
  spec/api-subframe-spec.js
  spec/fixtures/sub-frames/webview-iframe-preload.js
Labels: 6-0-x, backport

#19300 feat: migrate webRequest module to NetworkService (Part 1)
  filenames.gni
  shell/browser/api/atom_api_session.cc
  shell/browser/api/atom_api_web_request_ns.cc
  shell/browser/api/atom_api_web_request_ns.h
Labels: new-pr 🌱

#19312 chore: upgrade node to 12.6.0
  DEPS
  patches/node/.patches
  patches/node/build_add_gn_build_files.patch
  patches/node/build_modify_js2c_py_to_allow_injection_of_original-fs_and_custom_embedder_js.patch
  patches/node/chore_add_ability_to_prevent_warn_non_context-aware_native_modules.patch
  patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/node/chore_read_nobrowserglobals_from_global_not_process.patch
  patches/node/chore_remove_unused_private_runtimeagent_member_env.patch
  patches/node/export_environment_knodecontexttagptr.patch
  patches/node/feat_add_flags_for_low-level_hooks_and_exceptions.patch
  patches/node/feat_add_uv_loop_watcher_queue_code.patch
  patches/node/feat_initialize_asar_support.patch
  patches/node/fix_add_default_values_for_enable_lto_and_build_v8_with_gn_in.patch
  patches/node/fix_build_and_expose_inspector_agent.patch
  patches/node/fix_do_not_define_debugoptions_s_constructors_in_header.patch
  patches/node/fix_export_debugoptions.patch
  patches/node/fix_export_node_abort_and_assert.patch
  patches/node/fix_expose_internalcallbackscope.patch
  patches/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
  patches/node/fix_extern_the_nativemoduleenv_and_options_parser_for_debug_builds.patch
  patches/node/fix_key_gen_apis_are_not_available_in_boringssl.patch
  patches/node/fix_use_bssl_bn_bn2bin_padded_for_ossl_s_bn_bn2binpad.patch
  patches/node/fixme_comment_trace_event_macro.patch
  patches/node/fixme_revert_crypto_add_support_for_rsa-pss_keys.patch
  patches/node/fixme_use_redefined_version_of_internalmodulestat.patch
  patches/node/fsevents_fix_file_event_reporting.patch
  patches/node/inherit_electron_crashpad_pipe_name_in_child_process.patch
  patches/node/make_module_globalpaths_a_reference.patch
  patches/node/pass_all_globals_through_require.patch
  patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
  patches/node/src_add_missing_option_parser_template_for_the_debugoptionsparser.patch
  patches/node/src_disable_node_use_v8_platform_in_node_options.patch
  patches/node/src_expose_maybeinitializecontext_to_allow_existing_contexts.patch
  patches/node/src_only_run_preloadmodules_if_the_preload_array_is_not_empty.patch
  patches/node/src_read_break_node_first_line_from_the_inspect_options.patch
  patches/node/src_use_check_false_in_switch_default_case.patch
Labels: new-pr 🌱

#19310 refactor: use NativeTheme dark mode detection on macOS 10.15+
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/browser/ui/tray_icon_cocoa.mm
Labels: 5-0-x, backport

#19309 refactor: use NativeTheme dark mode detection on macOS 10.15+
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/browser/ui/tray_icon_cocoa.mm
Labels: 6-0-x, backport

#19299 fix: don't execute preload scripts for internal <iframe> in <webview> when nodeIntegrationInSubFrames is enabled
  atom/renderer/atom_render_frame_observer.cc
  atom/renderer/atom_renderer_client.cc
  atom/renderer/atom_sandboxed_renderer_client.cc
  atom/renderer/renderer_client_base.cc
  atom/renderer/renderer_client_base.h
  spec/api-subframe-spec.js
  spec/fixtures/sub-frames/webview-iframe-preload.js
Labels: 5-0-x, backport

#19297 chore: upgrade transitive lodash dependency
  spec/yarn.lock
  yarn.lock
Labels: fast-track 🚅

#19315 fix: delay handling occlusion events to avoid flicker on macOS
  patches/common/chromium/.patches
  patches/common/chromium/chore_add_debounce_on_the_updatewebcontentsvisibility_method_to.patch
Labels: 5-0-x, backport

#19308 docs: describe how to install Meiryo font on Windows 10
  docs/development/testing.md
Labels: documentation :notebook:

#19317 fix: bootstrap the node environment after we setup the InspectorAgent
  patches/node/.patches
  patches/node/chore_split_createenvironment_into_createenvironment_and.patch
  shell/browser/atom_browser_main_parts.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/atom_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: fast-track 🚅, target/6-0-x

#19332 fix: bootstrap the node environment after we setup the InspectorAgent (#19317)
  atom/browser/atom_browser_main_parts.cc
  atom/common/node_bindings.cc
  atom/common/node_bindings.h
  atom/renderer/atom_renderer_client.cc
  atom/renderer/web_worker_observer.cc
  patches/node/.patches
  patches/node/chore_split_createenvironment_into_createenvironment_and.patch
Labels: 6-0-x, backport, fast-track 🚅

#19347 fix: backport patch for leaking HTML5 video elements
  patches/common/chromium/.patches
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/crashpad_http_status.patch
  patches/common/chromium/mac_fix_form_control_rendering_on_10_14_mojave.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/mediacontrols_disconnect_observers_when_controls_are_hidden.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/tabbed_window_lagging.patch
  patches/common/chromium/webview_cross_drag.patch
Labels: fast-track 🚅

#19314 fix: preserve zoom button state on macOS when alwaysOnTop is set
  shell/browser/native_window_mac.mm
Labels: target/5-0-x, target/6-0-x

#19319 fix: emit swipe event on macOS
  shell/browser/api/atom_api_browser_window.cc
Labels: semver/patch, target/4-2-x, target/5-0-x, target/6-0-x

#19333 docs: update Electron Packager links
  docs/api/system-preferences.md
  docs/tutorial/application-distribution.md
  docs/tutorial/application-packaging.md
  docs/tutorial/boilerplates-and-clis.md
  docs/tutorial/code-signing.md
  docs/tutorial/mac-app-store-submission-guide.md
  docs/tutorial/snapcraft.md
  docs/tutorial/windows-store-guide.md
Labels: documentation :notebook:

#19349 fix: correctly convert MessageBoxType
  shell/common/native_mate_converters/message_box_converter.cc
Labels: semver/patch

#19345 docs: improve EventEmitter md formatting
  docs/api/auto-updater.md
  docs/api/browser-window.md
  docs/api/client-request.md
  docs/api/download-item.md
  docs/api/incoming-message.md
  docs/api/ipc-main.md
  docs/api/ipc-renderer.md
  docs/api/notification.md
  docs/api/screen.md
  docs/api/web-contents.md
  package.json
  yarn.lock
Labels: documentation :notebook:

#19371 docs: update public electron timeline
  docs/tutorial/electron-timelines.md
Labels: new-pr 🌱

#19382 chore: changed line endings from crlf to lf in manifests.cc/h
  shell/app/manifests.cc
  shell/app/manifests.h
Labels: new-pr 🌱

#19400 chore: omit superceded Chromium updates from notes
  script/release/notes/notes.js
Labels: fast-track 🚅

#19396 docs: fix bad link in notifications tut
  docs/tutorial/notifications.md
Labels: 4-2-x, backport

#19416 docs: make setBounds take a Partial<Rectangle>
  docs/api/browser-window.md
  yarn.lock
Labels: new-pr 🌱

#19365 fix: remove TLS destruction
  shell/app/atom_main.cc
Labels: target/6-0-x

#19418 test: don't run codesigning spec on forks
  spec-main/api-autoupdater-darwin-spec.ts
Labels: target/6-0-x

#19404 build: unify YARN_VERSION variable usage and ensure CI uses yarn not npm
  .circleci/config.yml
  appveyor.yml
  script/lib/utils.js
  script/spec-runner.js
  script/yarn.js
Labels: fast-track 🚅

#19401 docs: fix broken link in ipcMain docs
  docs/api/ipc-main.md
Labels: in-flight/6-0-x

#19432 chore: pass base::StringPiece args by value
  native_mate/native_mate/converter.cc
  native_mate/native_mate/converter.h
  native_mate/native_mate/dictionary.h
  native_mate/native_mate/object_template_builder.cc
  native_mate/native_mate/object_template_builder.h
  shell/browser/api/atom_api_screen.cc
  shell/browser/api/event_emitter.h
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/crash_reporter/crash_reporter_crashpad.cc
  shell/common/crash_reporter/crash_reporter_crashpad.h
  shell/common/gin_util.h
Labels: new-pr 🌱

#19337 fix: throw on invalid webRequest filters
  docs/api/web-request.md
  shell/browser/api/atom_api_web_request.cc
  spec-main/api-net-spec.ts
Labels: semver/patch, target/5-0-x, target/6-0-x

#19456 revert: use circleci v2.1
  .circleci/config.yml
Labels: fast-track 🚅

#19449 fix: activate the uv_loop on incoming IPC messages
  lib/renderer/init.ts
Labels: new-pr 🌱, target/6-0-x

#19448 docs: fix types for traceConfig recording_mode
  docs/api/structures/trace-config.md
Labels: documentation :notebook:, target/6-0-x

#19437 fix: clearing of the backgroundColor property on TouchBarButton
  shell/browser/ui/cocoa/atom_touch_bar.mm
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19463 fix: correctly emit BrowserWindow alwaysOnTop status in change event
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: platform/linux, platform/windows, semver/patch, target/5-0-x, target/6-0-x

#19480 docs: fix app.getPath types so that "name" is a string enum
  docs/api/app.md
  spec-main/api-app-spec.ts
Labels: new-pr 🌱

#19479 docs: fix type information for contents.sendInputEvent
  docs/api/structures/input-event.md
  docs/api/structures/keyboard-input-event.md
  docs/api/structures/mouse-input-event.md
  docs/api/structures/mouse-wheel-input-event.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  filenames.auto.gni
Labels: new-pr 🌱

#19478 docs: add support for readonly,deprecated and platform doc annotations
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/dialog.md
  docs/api/net-log.md
  docs/api/process.md
  docs/api/remote.md
  docs/api/session.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  lib/browser/api/app.ts
  package.json
  yarn.lock
Labels: new-pr 🌱

#19470 docs: fix GPU infoType typings
  docs/api/app.md
  spec-main/api-app-spec.ts
Labels: documentation :notebook:, new-pr 🌱

#19375 chore: clean up BrowserView/TopLevelWindow New impl
  shell/browser/api/atom_api_browser_view.cc
  shell/browser/api/atom_api_top_level_window.cc
Labels: semver/patch

#19462 feat: emit always-on-top-changed on macOS
  docs/api/browser-window.md
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: enhancement :sparkles:, platform/macOS, semver/minor

#19483 fix: remove .pdb from symbol file names
  build/dump_syms.py
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19469 fix: use GetAuraColor to get theme dependant menu bg color
  shell/browser/ui/views/menu_bar.cc
Labels: target/6-0-x

#19494 fix: refactoring regression in LocationProxy
  lib/renderer/window-setup.ts
  spec/chromium-spec.js
Labels: 6-0-x

#19417 docs: add return value description to BrowserWindow#get(Content)Bounds
  docs/api/browser-window.md
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19465 fix: [wc|bw]-created events do not emit an event object
  lib/browser/api/browser-window.js
  lib/browser/api/web-contents.js
  shell/browser/api/atom_api_event.cc
  shell/browser/api/event_emitter.cc
  shell/browser/api/event_emitter.h
Labels: semver/patch

#19461 docs: update supported versions section
  docs/tutorial/support.md
Labels: documentation :notebook:

#19517 docs: fix broken link in ipcMain docs
  docs/api/ipc-main.md
Labels: 6-0-x, new-pr 🌱

#19370 feat: add getBounds() method for BrowserView
  docs/api/browser-view.md
  shell/browser/api/atom_api_browser_view.cc
  shell/browser/api/atom_api_browser_view.h
  shell/browser/native_browser_view.h
  shell/browser/native_browser_view_mac.h
  shell/browser/native_browser_view_mac.mm
  shell/browser/native_browser_view_views.cc
  shell/browser/native_browser_view_views.h
  spec-main/api-browser-view-spec.ts
Labels: semver/minor

#19330 fix: tray.displayBalloon() does not work with custom icon on Windows
  shell/browser/api/atom_api_tray.cc
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#19395 docs: fix bad link in notifications tut
  docs/tutorial/notifications.md
Labels: 3-1-x

#19506 fix: correctly emit BrowserWindow alwaysOnTop status
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  docs/api/browser-window.md
  spec/api-browser-window-spec.js
Labels: 5-0-x, backport

#19436 fix: make process.uptime() return the correct time
  patches/node/.patches
  patches/node/fix_set_uptime_offset_in_correct_init_method.patch
  script/node-disabled-tests.json
Labels: target/5-0-x, target/6-0-x

#19534 fix: correctly emit BrowserWindow alwaysOnTop status
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  docs/api/browser-window.md
  spec/api-browser-window-spec.js
Labels: 6-0-x, backport

#19513 docs: fix invalid code block language tags
  docs/api/native-image.md
  docs/tutorial/application-distribution.md
  docs/tutorial/electron-versioning.md
  docs/tutorial/first-app.md
  docs/tutorial/installation.md
  docs/tutorial/linux-desktop-actions.md
  docs/tutorial/security.md
  docs/tutorial/snapcraft.md
  docs/tutorial/using-native-node-modules.md
  docs/tutorial/windows-store-guide.md
Labels: documentation :notebook:

#19514 fix: throw better error on getPath('logs')
  docs/api/app.md
  shell/browser/api/atom_api_app.cc
Labels: target/6-0-x

#19537 docs: update badges
  README.md
Labels: 6-0-x, backport

#19523 fix: set default dock bounce type
  shell/browser/api/atom_api_app.cc
Labels: target/6-0-x

#18981 feat: migrate custom macOS tray view to native one
  docs/api/tray.md
  lib/browser/api/tray.js
  shell/browser/api/atom_api_tray.cc
  shell/browser/api/atom_api_tray.h
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/tray_icon.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
Labels: platform/macOS,  catalina

#19329 docs: add missing MenuItem roles
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.js
  lib/browser/devtools.ts
  spec-main/api-menu-item-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: documentation :notebook:, target/6-0-x, target/7-0-x

#19545 fix: throw better error on getPath('logs')
  atom/browser/api/atom_api_app.cc
  docs/api/app.md
Labels: 6-0-x, backport

#19257 fix: use WeakPtr to detect deletion to avoid crash on application menu
  patches/chromium/.patches
  patches/chromium/fix_use_weakptr_to_detect_deletion.patch
Labels: target/5-0-x, target/6-0-x, target/7-0-x
