Repository electron/electron, pull requests merged in 2019-08, with the labels that each got.

#19560 fix: use WeakPtr to detect deletion to avoid crash on application menu
  patches/common/chromium/.patches
  patches/common/chromium/fix_use_weakptr_to_detect_deletion.patch
Labels: 6-0-x, backport

#19557 fix: expose setMenuBarVisibility again
  shell/browser/api/atom_api_top_level_window.cc
Labels: new-pr 🌱, target/7-0-x

#19561 fix: use WeakPtr to detect deletion to avoid crash on application menu
  patches/common/chromium/.patches
  patches/common/chromium/fix_use_weakptr_to_detect_deletion.patch
Labels: 5-0-x, backport

#19566 fix: make process.uptime() return the correct time
  patches/common/node/.patches
  patches/common/node/fix_set_uptime_offset_in_correct_init_method.patch
Labels: 5-0-x, backport

#19567 fix: make process.uptime() return the correct time
  patches/node/.patches
  patches/node/chore_split_createenvironment_into_createenvironment_and.patch
  patches/node/fix_set_uptime_offset_in_correct_init_method.patch
Labels: 6-0-x, backport

#19568 test: add test for invalid cookie url
  spec/api-session-spec.js
Labels: 6-0-x, backport

#19570 fix: throw on invalid webRequest filters
  atom/browser/api/atom_api_web_request.cc
  docs/api/web-request.md
  spec/api-net-spec.js
Labels: 6-0-x, backport, target/5-0-x

#19572 fix: set size of GTK about panel icon
  atom/browser/browser_linux.cc
  docs/api/app.md
Labels: 6-0-x, backport, target/5-0-x

#19573 doc: add missing MenuItem roles
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.js
  spec/api-menu-item-spec.js
  spec/ts-smoke/electron/main.ts
Labels: 6-0-x, backport

#19619 fix: destroy tray on current tick
  atom/browser/api/atom_api_tray.cc
  spec/api-tray-spec.js
Labels: 5-0-x, backport

#19601 fix: crash on window.print()
  patches/chromium/printing.patch
Labels: semver/patch, target/5-0-x, target/6-0-x, target/7-0-x

#19586 fix: handle edge behavior for about panel on Linux
  shell/browser/browser_linux.cc
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#19585 docs: remove implicit 'any' and 'Object' types from the docs
  docs/api/app.md
  docs/api/auto-updater.md
  docs/api/browser-window.md
  docs/api/client-request.md
  docs/api/content-tracing.md
  docs/api/crash-reporter.md
  docs/api/debugger.md
  docs/api/incoming-message.md
  docs/api/ipc-main.md
  docs/api/net.md
  docs/api/protocol.md
  docs/api/structures/extension-info.md
  docs/api/structures/trace-config.md
  docs/api/system-preferences.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  filenames.auto.gni
  package.json
  spec-main/api-browser-window-spec.ts
  spec-main/api-net-spec.ts
  spec-main/api-system-preferences-spec.ts
  spec/ts-smoke/electron/main.ts
  yarn.lock
Labels: target/7-0-x

#19553 fix: make child windows not crash when ipc messages are received
  lib/browser/guest-window-manager.js
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/atom_render_frame_observer.cc
  shell/renderer/atom_renderer_client.cc
  shell/renderer/electron_api_service_impl.cc
Labels: target/6-0-x, target/7-0-x

#19629 docs: clean up the native module tutorial
  docs/tutorial/using-native-node-modules.md
Labels: 5-0-x, backport, documentation :notebook:

#19599 fix: clearRecentDocuments role on Windows
  shell/browser/browser_win.cc
Labels: platform/windows, semver/patch, target/5-0-x, target/6-0-x, target/7-0-x

#19608 docs: update link to webContents.send
  docs/api/ipc-main.md
Labels: documentation :notebook:

#19647 fix: the callback of beginFrameSubscription should pass NativeImage instead of Buffer
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/frame_subscriber.cc
  atom/browser/api/frame_subscriber.h
  spec/api-browser-window-spec.js
Labels: 5-0-x, backport

#19640 fix: clearRecentDocuments role on Windows
  atom/browser/browser_win.cc
Labels: 5-0-x, backport

#19634 fix: handle edge behavior for about panel on Linux
  atom/browser/browser_linux.cc
Labels: 5-0-x, backport

#19628 docs: explanation on using protocols with partitions
  docs/api/protocol.md
Labels: 5-0-x, backport

#19627 fix: ensure the webContents is not destroyed before communicating
  lib/browser/chrome-extension.js
Labels: 5-0-x, backport

#19652 test: fix dirtyChai spec failures
  package.json
  spec-main/api-browser-view-spec.ts
  spec-main/api-browser-window-spec.ts
  yarn.lock
Labels: fast-track 🚅

#19635 fix: handle edge behavior for about panel on Linux
  atom/browser/browser_linux.cc
Labels: 6-0-x, backport

#19427 chore: keep references to active menus to prevent gc
  shell/browser/api/atom_api_menu.cc
Labels: app-feedback-program

#19648 feat: migrate webRequest module to NetworkService (part 3)
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
Labels: new-pr 🌱

#19535 fix: normalize behavior of `win.setOpacity()` for invalid number values across operating systems
  docs/api/browser-window.md
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#19598 fix: crash on print cancellation and silent print settings
  patches/chromium/printing.patch
  shell/browser/api/atom_api_web_contents.cc
Labels: target/7-0-x

#19654 fix: serialize messages being sent over chrome message ports
  lib/renderer/chrome-api.js
Labels: 5-0-x, backport

#19673 fix: normalize behavior of `win.setOpacity()` for invalid number values across operating systems
  docs/api/browser-window.md
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: 7-0-x, backport

#19639 fix: return correct bounds on will-resize
  shell/browser/ui/cocoa/atom_ns_window_delegate.mm
Labels: platform/macOS, target/5-0-x, target/6-0-x, target/7-0-x

#19677 fix: crash on window.print()
  patches/common/chromium/printing.patch
Labels: 6-0-x, backport

#19678 fix: crash on window.print()
  patches/common/chromium/printing.patch
Labels: 5-0-x, backport

#19675 docs: update hasShadow to show it works on win and linux
  docs/api/browser-window.md
  spec-main/api-browser-window-spec.ts
Labels: documentation :notebook:, target/5-0-x, target/6-0-x, target/7-0-x

#19688 feat: allow customization of print page header and footer
  docs/api/web-contents.md
  shell/browser/api/atom_api_web_contents.cc
Labels: component/printing, semver/minor

#19657 fix: avoid losing focus on inputs when opening menu (Windows/Linux)
  shell/browser/ui/views/menu_bar.cc
Labels: semver/patch, target/5-0-x, target/6-0-x, target/7-0-x

#19704 fix: return correct bounds on will-resize
  atom/browser/ui/cocoa/atom_ns_window_delegate.mm
Labels: 6-0-x, backport

#19692 docs: update hasShadow for win and linux
  docs/api/browser-window.md
  spec/api-browser-window-spec.js
Labels: 6-0-x, backport, target/5-0-x

#19718 fix: don't handle browser messages before document element is created
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_api_service_impl.h
  shell/renderer/renderer_client_base.cc
  spec-main/api-web-contents-spec.ts
  spec/fixtures/pages/send-after-node.html
Labels: fast-track 🚅, in-flight/6-0-x, target/7-0-x

#19719 fix: don't handle browser messages before document element is created (6-0-x)
  atom/renderer/electron_api_service_impl.cc
  atom/renderer/electron_api_service_impl.h
  atom/renderer/renderer_client_base.cc
  spec-main/api-web-contents-spec.ts
  spec/fixtures/pages/send-after-node.html
Labels: fast-track 🚅

#19690 fix: crash in window.print()
  docs/api/web-contents.md
  patches/chromium/printing.patch
  spec-main/api-web-contents-spec.ts
  spec/fixtures/pages/window-print.html
Labels: component/printing, target/7-0-x

#19669 feat: add dontAddToRecent to Windows showOpenDialog
  docs/api/dialog.md
  lib/browser/api/dialog.js
  shell/browser/ui/file_dialog.h
  shell/browser/ui/file_dialog_win.cc
Labels: platform/windows, semver/minor

#19672 feat: add property customization to save dialogs
  docs/api/dialog.md
  lib/browser/api/dialog.js
  shell/browser/common_web_contents_delegate.cc
  shell/browser/ui/file_dialog.h
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/file_dialog_mac.mm
  shell/browser/ui/file_dialog_win.cc
  shell/browser/web_dialog_helper.cc
Labels: semver/minor

#19727 chore: revert "fix: activate the uv_loop on incoming IPC messages"
  lib/renderer/init.ts
Labels: new-pr 🌱, target/6-0-x, target/7-0-x

#19725 fix: proper l10n on Linux dialog buttons
  shell/browser/ui/file_dialog_gtk.cc
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#19734 refactor: move net converter to gin
  filenames.gni
  shell/browser/api/atom_api_dialog.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  shell/common/gin_converters/net_converter_gin_adapter.h
  shell/common/gin_converters/std_converter.h
  shell/common/gin_converters/value_converter_gin_adapter.h
  shell/common/native_mate_converters/net_converter.h
Labels: new-pr 🌱

#19739 chore: revert "fix: activate the uv_loop on incoming IPC messages" (6-0-x)
  lib/renderer/init.ts
Labels: new-pr 🌱

#19705 fix: return correct bounds on will-resize
  atom/browser/ui/cocoa/atom_ns_window_delegate.mm
Labels: 5-0-x, backport

#19656 feat: add new nativeTheme API
  docs/api/native-theme.md
  docs/api/system-preferences.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/system-preferences.js
  lib/browser/api/system-preferences.ts
  lib/common/api/deprecate.ts
  lib/common/api/module-list.js
  lib/common/api/native-theme.ts
  shell/browser/api/atom_api_system_preferences.cc
  shell/common/api/atom_api_native_theme.cc
  shell/common/api/atom_api_native_theme.h
  shell/common/node_bindings.cc
  spec-main/api-native-theme-spec.ts
  spec/api-deprecate-spec.js
  typings/internal-electron.d.ts
Labels: semver/minor, target/7-0-x

#19723 fix: normalize behavior of `win.setOpacity()` for invalid number values across operating systems
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  spec/api-browser-window-spec.js
Labels: 6-0-x, backport

#19710 fix: make sure that menu bar gets focus even when you click an item to focus it first
  shell/browser/ui/views/menu_bar.cc
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#18926 feat: Implement BrowserWindow.getMediaSourceId() and BrowserWindow.moveAbove(mediaSourceId)
  docs/api/browser-window.md
  shell/browser/api/atom_api_top_level_window.cc
  shell/browser/api/atom_api_top_level_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/ui/x/x_window_utils.cc
  shell/browser/ui/x/x_window_utils.h
  spec-main/api-browser-window-spec.ts
  spec/api-desktop-capturer-spec.js
Labels: semver/minor

#19742 fix: ensure child_process.fork() doesn't modify main process env
  patches/node/inherit_electron_crashpad_pipe_name_in_child_process.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#19756 fix: use GTK3 stock i18n strings
  shell/browser/ui/file_dialog_gtk.cc
Labels: in-flight/6-0-x, target/3-1-x, target/4-2-x, target/5-0-x, target/7-0-x

#19759 docs: add exemplary fiddle for `launch in fiddle` feat
  docs/api/screen.md
  docs/fiddles/screen/fit-screen/main.js
Labels: target/6-0-x, target/7-0-x

#19787 fix: compilation failure after chromium upgrade
  shell/browser/api/atom_api_web_request_ns.cc
  shell/common/api/atom_api_native_theme.cc
Labels: fast-track 🚅

#19782 docs: MessageBoxOptions.icon should allow type string
  docs/api/dialog.md
Labels: component/typescript, documentation :notebook:, new-pr 🌱, target/5-0-x, target/6-0-x, target/7-0-x

#19781 fix: return property enum type in open/save dialogs
  lib/browser/api/dialog.js
Labels: bug/regression :leftwards_arrow_with_hook:, new-pr 🌱

#19760 fix: use i18nized strings in gtk dialog buttons
  atom/browser/ui/file_dialog_gtk.cc
Labels: semver/patch

#19778 docs: add missing return desc
  docs/api/dialog.md
Labels: new-pr 🌱, target/6-0-x, target/7-0-x

#19801 fix: use i18nized strings in gtk dialog buttons
  atom/browser/ui/file_dialog_gtk.cc
Labels: 5-0-x, backport

#19806 ci: fix flaky test on arm (5-0-x)
  spec/api-web-contents-view-spec.js
  spec/fixtures/api/leak-exit-webcontentsview.js
  vsts-arm32v7.yml
  vsts-arm64v8.yml
Labels: 5-0-x

#19808 fix: disable LayoutNG to prevent random crashes in selection calcuations
  atom/browser/atom_browser_main_parts.cc
Labels: fast-track 🚅

#19724 fix: normalize behavior of `win.setOpacity()` for invalid number values across operating systems
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  spec/api-browser-window-spec.js
Labels: 5-0-x, backport

#19828 fix: always use new site instance for a new navigation.
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  patches/common/chromium/frame_host_manager.patch
Labels: 5-0-x, backport

#19786 docs: add exemplary fiddle for `launch in fiddle` feat
  docs/api/screen.md
  docs/fiddles/screen/fit-screen/main.js
Labels: 6-0-x, backport

#19827 fix: always use new site instance for a new navigation
  patches/chromium/frame_host_manager.patch
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
Labels: 7-0-x, backport

#19826 fix: always use new site instance for a new navigation
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  patches/common/chromium/frame_host_manager.patch
Labels: 6-0-x, backport

#19830 ci: upgrades-wg owns DEPS
  .github/CODEOWNERS
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#19834 ci: upgrades-wg owns DEPS
  .github/CODEOWNERS
Labels: 6-0-x, backport

#19653 fix: fall back to default logs path in getPath('logs')
  docs/api/app.md
  native_mate/native_mate/arguments.h
  shell/browser/api/atom_api_app.cc
  shell/browser/api/atom_api_app.h
  shell/browser/api/atom_api_app_mac.mm
  shell/common/native_mate_converters/value_converter.h
  spec-main/api-app-spec.ts
Labels: target/6-0-x, target/7-0-x

#19804 docs: update documentation under tutorials
  docs/tutorial/security.md
Labels: documentation :notebook:, target/6-0-x, target/7-0-x

#19841 feat: migrate webRequest module to NetworkService (Part 8)
  shell/browser/api/atom_api_web_request_ns.cc
  shell/browser/net/proxying_url_loader_factory.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  spec/api-web-request-spec.js
Labels: new-pr 🌱

#19871 fix: add default media usage strings to info.plist
  shell/browser/resources/mac/Info.plist
Labels: fast-track 🚅, new-pr 🌱, target/5-0-x, target/6-0-x, target/7-0-x

#19780 build: start building Windows on Arm builds
  appveyor.yml
  azure-pipelines-woa.yml
  script/release/ci-release-build.js
  script/zip_manifests/dist_zip.win.arm64.manifest
Labels: target/6-0-x, target/7-0-x

#19860 feat: add openbsd support in the node module
  npm/install.js
Labels: semver/minor

#19876 fix: extern Parse impl for Windows debug builds
  patches/node/fix_extern_the_nativemoduleenv_and_options_parser_for_debug_builds.patch
Labels: new-pr 🌱, target/6-0-x, target/7-0-x

#19878 fix: notify views of contentView size change
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: in-flight/4-2-x, in-flight/5-0-x, in-flight/6-0-x, new-pr 🌱, target/7-0-x

#19873 fix: mitigate white screen flash after occlusion by disabling compositor recycling
  patches/chromium/.patches
  patches/chromium/chore_add_debounce_on_the_updatewebcontentsvisibility_method_to.patch
  patches/chromium/disable_compositor_recycling.patch
  spec-main/api-browser-window-spec.ts
Labels: fast-track 🚅, target/6-0-x, target/7-0-x

#19901 fix: remove white screen flicker by disabling compositor recycling
  patches/chromium/.patches
  patches/chromium/chore_add_debounce_on_the_updatewebcontentsvisibility_method_to.patch
  patches/chromium/cross_site_document_resource_handler.patch
  patches/chromium/fix_disabling_compositor_recycling.patch
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱

#19900 fix: remove white screen flicker by disabling compositor recycling
  patches/common/chromium/.patches
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/chore_add_debounce_on_the_updatewebcontentsvisibility_method_to.patch
  patches/common/chromium/fix_disabling_compositor_recycling.patch
  spec/api-browser-window-spec.js
Labels: new-pr 🌱

#19894 docs: clarify dock.bounce usage
  docs/api/dock.md
Labels: documentation :notebook:, new-pr 🌱, target/5-0-x, target/6-0-x, target/7-0-x

#19845 fix: ensure child_process.fork() doesn't modify main process env
  patches/node/inherit_electron_crashpad_pipe_name_in_child_process.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
Labels: 6-0-x, backport

#19888 fix: notify views of content view size change (6-0-x)
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
Labels: 6-0-x, backport

#19913 build: use a lower process count for publish builds with no sccache
  .circleci/config.yml
Labels: target/6-0-x, target/7-0-x

#19897 fix: crash on input file handler dialog
  shell/browser/web_dialog_helper.cc
Labels: target/7-0-x

#19914 feat: enable picture-in-picture mode for video tags
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  chromium_src/BUILD.gn
  electron_strings.grdp
  patches/chromium/.patches
  patches/chromium/picture-in-picture.patch
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
  shell/browser/common_web_contents_delegate.cc
  shell/browser/common_web_contents_delegate.h
  shell/browser/feature_list.cc
  shell/common/api/features.cc
  spec/api-web-contents-spec.js
  spec/fixtures/api/picture-in-picture.html
  typings/internal-ambient.d.ts
Labels: 7-0-x, backport, new-pr 🌱

#19912 fix: command-line scheme switch values' spillover
  shell/app/atom_content_client.cc
Labels: needs-manual-bp/4-2-x, target/5-0-x, target/6-0-x, target/7-0-x

#19883 fix: adjust window size in NCCALCSIZE instead of adding insets
  shell/browser/native_window_views_win.cc
  shell/browser/ui/views/root_view.cc
  shell/browser/ui/views/root_view.h
Labels: target/6-0-x, target/7-0-x

#19928 fix: handle WM_GETMINMAXINFO instead of letting chromium do it
  shell/browser/native_window_views_win.cc
Labels: target/6-0-x, target/7-0-x

#19998 chore: cache URLLoaderFactory per-session
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/atom_browser_context.cc
  shell/browser/atom_browser_context.h
  shell/browser/net/atom_url_loader_factory.cc
Labels: new-pr 🌱, target/7-0-x

#20010 fix: i18n of gtk msgbox buttons
  atom/browser/ui/file_dialog_gtk.cc
  atom/browser/ui/message_box_gtk.cc
  atom/browser/ui/util_gtk.cc
  atom/browser/ui/util_gtk.h
  filenames.gni
Labels: new-pr 🌱

#20014 fix: nws13n: make ses.setUserAgent work
  patches/chromium/.patches
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  shell/browser/api/atom_api_session.cc
  spec-main/api-session-spec.ts
Labels: new-pr 🌱, target/7-0-x

#20007 fix: i18n of gtk msgbox buttons
  atom/browser/ui/file_dialog_gtk.cc
  atom/browser/ui/message_box_gtk.cc
  atom/browser/ui/util_gtk.cc
  atom/browser/ui/util_gtk.h
  filenames.gni
Labels: 6-0-x, backport

#20003 chore: add missing includes
  shell/browser/native_window.cc
  shell/browser/native_window.h
Labels: new-pr 🌱

#20019 fix: Revert "fix: make sure that menu bar gets focus even when you click an item to focus it first"
  shell/browser/ui/views/menu_bar.cc
Labels: new-pr 🌱, target/5-0-x, target/6-0-x, target/7-0-x

#20021 chore: cache URLLoaderFactory per-session (7-0-x)
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/atom_browser_context.cc
  shell/browser/atom_browser_context.h
  shell/browser/net/atom_url_loader_factory.cc
Labels: new-pr 🌱

#20020 fix: honor cursor blink rate
  shell/browser/api/atom_api_web_contents.cc
Labels: target/5-0-x, target/6-0-x, target/7-0-x

#20051 fix: ensure that the "top" coordinate of the inner frame is correct
  shell/browser/native_window_views_win.cc
Labels: fast-track 🚅, target/6-0-x, target/7-0-x
