Repository electron/electron, pull requests merged in 2019-12, with the labels that each got.

#21341 build: fix building with enable_builtin_spellchecker = false
  BUILD.gn
  chromium_src/BUILD.gn
  shell/browser/api/atom_api_session.cc
Labels: 8-x-y, backport

#21344 chore: delete the security issue template
  .github/ISSUE_TEMPLATE/security_report.md
Labels: new-pr 🌱

#21345 docs: fix duplicate "close"
  docs/api/menu-item.md
Labels: new-pr 🌱

#21342 fix: ensure no node globals passively leak when nodeIntegration is disabled
  lib/renderer/init.ts
  spec-main/api-browser-window-spec.ts
  spec/fixtures/api/globals.html
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21343 fix: focus with OOPIF embedded inside <webview>
  patches/chromium/.patches
  patches/chromium/add_trustedauthclient_to_urlloaderfactory.patch
  patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch
  patches/chromium/fix_focusowningwebcontents_to_handle_renderwidgethosts_for_oopifs.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/printing.patch
  patches/chromium/put_back_deleted_colors_for_autofill.patch
Labels: 8-x-y, backport

#21037 fix: backgroundThrottling rwh assignment
  patches/chromium/.patches
  patches/chromium/feat_allow_disbaling_blink_scheduler_throttling_per_renderview.patch
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21304 refactor: rewrite the net module to simplify state tracking
  docs/api/client-request.md
  filenames.gni
  lib/browser/api/net.js
  shell/browser/api/atom_api_net.cc
  shell/browser/api/atom_api_net.h
  shell/browser/api/atom_api_url_loader.cc
  shell/browser/api/atom_api_url_loader.h
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/api/atom_api_url_request_ns.h
  shell/browser/atom_browser_context.cc
  shell/common/native_mate_converters/net_converter.cc
  shell/common/native_mate_converters/net_converter.h
  shell/renderer/electron_api_service_impl.cc
  spec-main/api-net-spec.ts
Labels: 7-1-x, backport

#21278 ci: generate debug symbols on Linux
  .circleci/config.yml
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/config.py
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload.py
  script/strip-binaries.py
  script/zip-symbols.py
Labels: 8-x-y, backport

#21349 chore: remove unused crash_service.cc
  shell/common/crash_reporter/win/crash_service.cc
  shell/common/crash_reporter/win/crash_service.h
  shell/common/crash_reporter/win/crash_service_main.cc
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21380 fix: prevent silent failure when DOM storage quota exceeded
  patches/chromium/dom_storage_limits.patch
  spec/chromium-spec.js
Labels: 8-x-y, backport

#21372 fix: Fix compositor recycling when creating new BrowserView
  shell/browser/api/atom_api_web_contents.cc
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21398 chore: minor "trailing whitespace" patch warnings
  patches/chromium/mas_no_private_api.patch
  patches/chromium/put_back_deleted_colors_for_autofill.patch
Labels: new-pr 🌱

#21386 fix: pass noLink correctly on Windows
  lib/browser/api/dialog.js
  shell/browser/ui/message_box.h
  shell/browser/ui/message_box_win.cc
  shell/common/gin_converters/message_box_converter.cc
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21402 fix: avoid context bridge crash when window closes
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.cc
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.h
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21396 fix: Fix compositor recycling when creating new BrowserView (6-1-x)
  atom/browser/api/atom_api_web_contents.cc
Labels: 6-1-x, backport

#21419 fix: do not use messages after move
  shell/browser/api/atom_api_web_contents.cc
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21411 docs: fix return type of getPrinters
  docs/api/web-contents.md
  lib/browser/api/web-contents.js
Labels: documentation :notebook:, new-pr 🌱, target/7-1-x, target/8-x-y

#21388 fix: fix ClientRequest.getUploadProgress
  lib/browser/api/net.js
  spec-main/api-net-spec.ts
Labels: target/7-1-x, target/8-x-y

#21406 fix: pass noLink and checkboxChecked correctly on Windows
  lib/browser/api/dialog.js
  shell/browser/ui/message_box.h
  shell/browser/ui/message_box_win.cc
  shell/common/native_mate_converters/message_box_converter.cc
Labels: 7-1-x, backport

#21436 fix: hiding window menu should work on startup
  lib/browser/init.ts
  shell/browser/native_window_views.cc
  spec-main/api-menu-spec.ts
  spec-main/fixtures/api/test-menu-null/main.js
  spec-main/fixtures/api/test-menu-null/package.json
  spec-main/fixtures/api/test-menu-visibility/main.js
  spec-main/fixtures/api/test-menu-visibility/package.json
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21441 chore: workflows and pipeline state were split in the circle API
  script/release/ci-release-build.js
Labels: fast-track 🚅, target/8-x-y

#21378 chore: remove unused crash_service.c
  atom/common/crash_reporter/win/crash_service.cc
  atom/common/crash_reporter/win/crash_service.h
  atom/common/crash_reporter/win/crash_service_main.cc
Labels: 6-1-x, backport

#21434 fix: window menu should handle keys correctly
  patches/chromium/.patches
  patches/chromium/accessible_pane_view.patch
  shell/browser/ui/views/menu_bar.h
Labels: target/7-1-x, target/8-x-y

#21462 fix: restore accessibility window title on macOS
  shell/browser/ui/cocoa/atom_ns_window.mm
Labels: new-pr 🌱, target/6-1-x, target/7-1-x, target/8-x-y

#21449 fix: hiding window menu should work on startup (7-1-x)
  lib/browser/init.ts
  shell/browser/native_window_views.cc
  spec-main/api-menu-spec.ts
  spec-main/fixtures/api/test-menu-null/main.js
  spec-main/fixtures/api/test-menu-null/package.json
  spec-main/fixtures/api/test-menu-visibility/main.js
  spec-main/fixtures/api/test-menu-visibility/package.json
Labels: 7-1-x, backport

#21469 fix: restore POST forms that open a new window with target=_blank
  shell/common/gin_converters/net_converter.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/form-with-data.html
Labels: new-pr 🌱, target/8-x-y

#21442 fix: MediaKey globalShortcuts not working on macOS
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  patches/chromium/command-ismediakey.patch
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21454 fix: name and expirationDate should be optional when setting cookie
  shell/browser/api/atom_api_cookies.cc
  spec-main/api-net-spec.ts
  spec-main/api-session-spec.ts
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21477 fix: name and expirationDate should be optional when setting cookie (8-x-y)
  shell/browser/api/atom_api_cookies.cc
  spec-main/api-net-spec.ts
  spec-main/api-session-spec.ts
Labels: 8-x-y, backport, target/7-1-x

#21447 fix: avoid Electron.dsym files in the main app bundle
  .circleci/config.yml
  build/zip.py
Labels: target/7-1-x, target/8-x-y

#21487 fix: avoid Electron.dsym files in the main app bundle
  .circleci/config.yml
  build/zip.py
Labels: 7-1-x, backport

#21473 fix: sourcemaps over file:// not loading with network service
  shell/browser/ui/inspectable_web_contents_impl.cc
Labels: target/7-1-x, target/8-x-y

#20988 fix: disable more private macOS APIs in MAS build (5-0-x)
  patches/common/chromium/.patches
  patches/common/chromium/mas_disable_custom_window_frame.patch
  patches/common/chromium/mas_disable_remote_accessibility.patch
  patches/common/chromium/mas_disable_remote_layer.patch
  patches/common/chromium/mas_disable_spi_file_type_mappings.patch
Labels: 5-0-x, backport

#20970 fix: disable more private macOS APIs in MAS build (6-1-x)
  patches/common/chromium/.patches
  patches/common/chromium/mas_disable_custom_window_frame.patch
  patches/common/chromium/mas_disable_remote_accessibility.patch
  patches/common/chromium/mas_disable_remote_layer.patch
  patches/common/chromium/mas_disable_spi_file_type_mappings.patch
Labels: 6-1-x, backport

#21488 fix: quit after Chromium is fully started
  shell/browser/browser.cc
  spec-main/fixtures/api/leak-exit-webcontentsview.js
  spec/fixtures/api/command-line/main.js
  spec/fixtures/api/cookie-app/main.js
  spec/fixtures/api/ipc-main-listeners/main.js
  spec/fixtures/api/leak-exit-browserview.js
  spec/fixtures/api/leak-exit-webcontents.js
  spec/fixtures/api/locale-check/main.js
Labels: target/6-1-x, target/7-1-x, target/8-x-y, wip ⚒

#21497 fix: workaround for hang when preventDefault-ing nativeWindowOpen (7-1-x)
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
  spec-main/api-web-contents-spec.ts
Labels: fast-track 🚅

#21495 chore: fix patch linter
  package.json
  patches/boringssl/expose_aes-cfb.patch
  patches/chromium/.patches
  patches/chromium/blink-worker-enable-csp-in-file-scheme.patch
  patches/chromium/blink_world_context.patch
  patches/chromium/build_gn.patch
  patches/chromium/can_create_window.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/feat_allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/gin_enable_disable_v8_platform.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
  patches/chromium/picture-in-picture.patch
  patches/chromium/render_widget_host_view_base.patch
  patches/chromium/render_widget_host_view_mac.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_cross_drag.patch
  patches/chromium/worker_context_will_destroy.patch
  patches/node/build_add_gn_build_files.patch
  patches/node/chore_handle_default_configuration_not_being_set_in_the_electron_env.patch
  patches/node/feat_add_new_built_with_electron_variable_to_config_gypi.patch
  patches/node/fix_call_initializecontextruntime_in_initializecontext.patch
  patches/node/fix_export_debugoptions.patch
  patches/node/fixme_comment_trace_event_macro.patch
  patches/node/fixme_remove_async_id_assertion_check.patch
  patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
  patches/v8/build_gn.patch
  patches/v8/dcheck.patch
  script/lint.js
Labels: new-pr 🌱

#21496 fix: enforce parent-child relationship in custom postMessage() handler
  lib/browser/guest-window-manager.js
Labels: new-pr 🌱, target/6-1-x, target/7-1-x, target/8-x-y

#21501 fix: avoid contextBridge crash when RenderFrame address is reused
  shell/renderer/api/atom_api_context_bridge.cc
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.cc
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.h
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21498 refactor: export internalWindowOpen from guest-window-manager
  lib/browser/api/web-contents.js
  lib/browser/guest-window-manager.js
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21526 fix: select box not rendered properly with OOPIF
  patches/chromium/.patches
  patches/chromium/only_apply_transform_when_outermost_outer_webcontents.patch
Labels: 7-1-x

#21529 fix: enforce parent-child relationship in custom postMessage() handler
  lib/browser/guest-window-manager.js
Labels: 6-1-x, backport

#21491 docs: update installation docs to reflect latest @electron/get changes
  docs/tutorial/installation.md
Labels: documentation :notebook:, target/7-1-x, target/8-x-y

#21528 fix: enforce parent-child relationship in custom postMessage() handler
  lib/browser/guest-window-manager.js
Labels: 7-1-x, backport

#21542 refactor: export internalWindowOpen from guest-window-manager
  lib/browser/api/web-contents.js
  lib/browser/guest-window-manager.js
Labels: 7-1-x, backport

#21541 docs: update webContents.printToPDF() example for promisified API
  docs/api/web-contents.md
Labels: documentation :notebook:, new-pr 🌱, target/7-1-x, target/8-x-y

#21543 refactor: export internalWindowOpen from guest-window-manager
  filenames.auto.gni
  lib/browser/api/web-contents.js
  lib/browser/guest-window-manager.js
Labels: 6-1-x, backport

#21547 fix: MediaKey globalShortcuts not working on macOS
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  patches/chromium/command-ismediakey.patch
Labels: 8-x-y, backport

#21548 fix: MediaKey globalShortcuts not working on macOS
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  patches/chromium/command-ismediakey.patch
Labels: 7-1-x, backport

#21569 build: free up macos disk space on Mac publish
  .circleci/config.yml
Labels: fast-track 🚅, target/8-x-y

#21568 chore: make release branch pattern more robust
  script/lib/utils.js
Labels: fast-track 🚅

#21571 fix: set enable_negotiate_port to false in allowNTLMCredentialsForDomains
  shell/browser/api/atom_api_session.cc
Labels: fast-track 🚅, in-flight/7-1-x, target/8-x-y

#21572 fix: set enable_negotiate_port to false in allowNTLMCredentialsForDom…
  shell/browser/api/atom_api_session.cc
Labels: 7-1-x, backport, fast-track 🚅

#21641 docs: fix shell.openPath documentation
  docs/api/shell.md
Labels: documentation :notebook:, new-pr 🌱

#21630 fix: SimpleURLLoaderWrapper redirects (#21566)
  lib/browser/api/net.js
Labels: target/7-1-x, target/8-x-y

#21642 fix: highlight buttons correctly when defaultId passed
  shell/browser/ui/message_box_mac.mm
Labels: new-pr 🌱, target/7-1-x, target/8-x-y
