Repository electron/electron, pull requests merged in 2019-06, with the labels that each got.

#18575 refactor: lazy load V8 module in browser/init
  lib/browser/init.ts
Labels: new-pr 🌱, performance :checkered_flag:

#18571 perf: lazily create the anchor tag used for URL resolving
  lib/renderer/window-setup.ts
Labels: performance :checkered_flag:

#18555 refactor: make autoHideMenuBar a property on BrowserWindows
  atom/browser/api/atom_api_top_level_window.cc
  docs/api/browser-window.md
  docs/api/modernization/property-updates.md
  lib/browser/api/browser-window.js
  spec/api-browser-window-spec.js
Labels: semver/minor

#18546 build: remove Vulkan mock ICD
  build/zip.py
  script/dist_zip.linux.arm.manifest
  script/dist_zip.linux.arm64.manifest
  script/dist_zip.linux.x64.manifest
  script/dist_zip.linux.x86.manifest
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18589 build: install python-dbusmock via pip for a Docker container
  Dockerfile
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18564 fix: [turbofan] Fix wrong typing of SpeculativeSafeIntegerSubtract
  patches/common/v8/.patches
  patches/common/v8/turbofan_fix_wrong_typing_of_speculativesafeintegersubtract.patch
Labels: 4-2-x, backport, security 🔒

#18281 fix: don't export private V8 symbols that can cause native node modules to crash
  patches/common/v8/.patches
  patches/common/v8/do_not_export_private_v8_symbols_on_windows.patch
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18574 refactor: lazy load child_process in the crash-reporter module
  lib/browser/crash-reporter-init.js
Labels: new-pr 🌱, performance :checkered_flag:

#17634 fix: Issue 914497: QUIC proxying breaks end-to-end encryption
  patches/common/chromium/.patches
  patches/common/chromium/enable_quic_proxies_for_https_urls.patch
Labels: 4-2-x, backport, security 🔒

#18588 build: strip swiftshader binaries
  script/strip-binaries.py
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18227 docs: Fix incorrect dialog docs
  docs/api/dialog.md
Labels: target/6-0-x

#18576 refactor: lazily hook into child_process in asar_init
  lib/common/asar.js
Labels: performance :checkered_flag:

#18596 build: remove Vulkan mock ICD
  build/zip.py
Labels: 6-0-x, backport

#18594 build: remove Vulkan mock ICD
  build/zip.py
Labels: 4-2-x, backport

#18582 refactor: remove menu-will-close / setTimeout workaround
  lib/browser/devtools.js
Labels: new-pr 🌱

#18577 refactor: remove electron.asar and embed JS in binary
  BUILD.gn
  DEPS
  atom/common/node_bindings.cc
  lib/browser/init.ts
  lib/common/reset-search-paths.ts
  lib/renderer/callbacks-registry.js
  lib/renderer/init.ts
  lib/worker/init.js
  script/dist_zip.linux.arm.manifest
  script/dist_zip.linux.arm64.manifest
  script/dist_zip.linux.x64.manifest
  script/dist_zip.linux.x86.manifest
  script/dist_zip.mac.x64.manifest
  script/dist_zip.mac_mas.x64.manifest
  spec/asar-spec.js
  typings/internal-ambient.d.ts
Labels: performance :checkered_flag:

#18608 refactor: mojofy zoom api
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/common/api/api.mojom
  atom/common/api/api_messages.h
  atom/renderer/api/atom_api_web_frame.cc
Labels: new-pr 🌱

#18471 docs: change pyobjc link in macos build instruction
  docs/development/build-instructions-macos.md
Labels: documentation :notebook:, target/5-0-x, target/6-0-x

#18561 fix: Fix SVG crash for v0 distribution into foreignObject
  patches/common/chromium/.patches
  patches/common/chromium/fix_svg_crash_for_v0_distribution_into_foreignobject.patch
Labels: 4-2-x, backport, security 🔒

#18569 fix: [turbofan] Restrict redundancy elimination from widening types
  patches/common/v8/.patches
  patches/common/v8/turbofan_restrict_redundancy_elimination_from_widening_types.patch
Labels: 4-2-x, backport, security 🔒

#18566 fix: Prevent glDeleteQueries from deleting a live Query
  patches/common/config.json
  patches/common/swiftshader/.patches
  patches/common/swiftshader/prevent_gldeletequeries_from_deleting_a_live_query.patch
Labels: 4-2-x, backport, security 🔒

#18620 fix: don't export private V8 symbols that can cause native node modules to crash
  patches/common/v8/.patches
  patches/common/v8/do_not_export_private_v8_symbols_on_windows.patch
Labels: 5-0-x, backport

#18595 build: remove Vulkan mock ICD
  build/zip.py
Labels: 5-0-x, backport

#18619 fix: don't export private V8 symbols that can cause native node modules to crash
  patches/common/v8/.patches
  patches/common/v8/do_not_export_private_v8_symbols_on_windows.patch
Labels: 6-0-x, backport

#18621 fix: don't export private V8 symbols that can cause native node modules to crash
  patches/common/v8/.patches
  patches/common/v8/do_not_export_private_v8_symbols_on_windows.patch
Labels: 4-2-x, backport

#18627 build: move Windows release builds to AppVeyor cloud
  .env.example
  script/ci-release-build.js
Labels: 3-1-x, backport

#18568 fix: [parser] LiteralBuffer::ExpandBuffer always grows
  patches/common/v8/.patches
  patches/common/v8/parser_literalbuffer_expandbuffer_always_grows.patch
Labels: 4-2-x, backport, security 🔒

#18572 fix: [FileSystem] Harden against overflows of OperationID a bit better
  patches/common/chromium/.patches
  patches/common/chromium/filesystem_harden_against_overflows_of_operationid_a_bit_better.patch
Labels: 4-2-x, backport, security 🔒

#18563 fix: UAP in ImageBitmapLoader/FileReaderLoader
  patches/common/chromium/.patches
  patches/common/chromium/fix_uap_in_imagebitmaploader_filereaderloader.patch
Labels: 4-2-x, backport, security 🔒

#18562 fix: ValueSerializer: Report if buffer expansion fails during WriteHostObject
  patches/common/v8/.patches
  patches/common/v8/valueserializer_report_if_buffer_expansion_fails_during.patch
Labels: 4-2-x, backport, security 🔒

#18613 docs: ensure that optionality matches between documented params and signatures
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/content-tracing.md
  docs/api/in-app-purchase.md
  docs/api/ipc-main.md
  docs/api/ipc-renderer.md
  docs/api/menu.md
  docs/api/native-image.md
  docs/api/notification.md
  docs/api/web-contents.md
  docs/api/web-request.md
  docs/api/webview-tag.md
  package.json
  yarn.lock
Labels: new-pr 🌱, target/5-0-x, target/6-0-x

#18630 fix: ensure correct ordering of sendSync w.r.t. send
  atom/renderer/api/atom_api_renderer_ipc.cc
  spec-main/api-ipc-spec.ts
Labels: new-pr 🌱

#18635 fix: reject the executeJavaScript promise when it fails to execute the script
  atom/renderer/api/atom_api_web_frame.cc
Labels: new-pr 🌱

#18565 fix: Check array element length in ValueDeserializer
  patches/common/v8/.patches
  patches/common/v8/check_array_element_length_in_valuedeserializer.patch
Labels: 4-2-x, backport, security 🔒

#18631 feat: promisify systemPreferences notification methods
  atom/browser/api/atom_api_system_preferences.h
  atom/browser/api/atom_api_system_preferences_mac.mm
  docs/api/modernization/promisification.md
  docs/api/system-preferences.md
Labels: semver/major

#18530 fix: Issue 924843: DCHECK failure in IsAligned(DistanceTo(target), kInstrSize) in instructions-arm64.cc
  patches/common/v8/.patches
  patches/common/v8/liftoff-correctly-unuse-labels.patch
Labels: 4-2-x, backport, security 🔒

#18668 fix: emit IPC event in correct context if isolation and sandbox enabled
  atom/renderer/atom_sandboxed_renderer_client.cc
  spec/api-ipc-renderer-spec.js
  spec/fixtures/module/preload-inject-ipc.js
  spec/fixtures/module/preload-ipc-ping-pong.js
  spec/fixtures/pages/ping-pong.html
Labels: 3-1-x, backport

#18578 docs: Add missing document links to docs/readme
  docs/README.md
  docs/tutorial/app-feedback-program.md
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:

#18567 fix: Fixed all OOB accesses in VertexProgram and PixelProgram
  patches/common/swiftshader/.patches
  patches/common/swiftshader/fix_undefined_behavior_in_offset.patch
  patches/common/swiftshader/fixed_all_oob_accesses_in_vertexprogram_and_pixelprogram.patch
Labels: 4-2-x, backport, security 🔒

#18659 feat: allow resigning current NSUserActivity
  atom/browser/api/atom_api_app.cc
  atom/browser/browser.h
  atom/browser/browser_mac.mm
  atom/browser/mac/atom_application.h
  atom/browser/mac/atom_application.mm
  docs/api/app.md
Labels: enhancement :sparkles:, platform/macOS, semver/minor

#18665 fix: use isEqual instead of pointer equality to convert NSAppearance
  atom/browser/api/atom_api_system_preferences_mac.mm
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18666 fix: use effectiveAppearance to check dark mode on mojave and above
  atom/browser/ui/tray_icon_cocoa.mm
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18556 fix: set nativeWindowOpen when sandboxed
  atom/browser/atom_browser_client.cc
  atom/browser/web_contents_preferences.cc
  atom/browser/web_contents_preferences.h
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  spec/webview-spec.js
Labels: 6-0-x, backport

#18657 fix: properly pass openExternal activate option
  atom/common/platform_util_mac.mm
  spec/api-shell-spec.js
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18705 chore: revert promisified systemPreferences notification methods
  atom/browser/api/atom_api_system_preferences.h
  atom/browser/api/atom_api_system_preferences_mac.mm
  docs/api/modernization/promisification.md
  docs/api/system-preferences.md
Labels: fast-track 🚅

#18713 chore: fix duplicate error string
  atom/renderer/api/atom_api_web_frame.cc
Labels: new-pr 🌱

#18722 fix: properly pass openExternal activate option (6-0-x)
  atom/common/platform_util_mac.mm
  spec/api-shell-spec.js
Labels: 6-0-x, backport

#18724 fix: modify new promise object for dialog methods to match old callback api
  lib/browser/api/dialog.js
  lib/common/api/deprecate.ts
  typings/internal-electron.d.ts
Labels: 6-0-x, backport

#18624 fix: lost window.opener after cross-origin navigation
  patches/common/chromium/frame_host_manager.patch
  spec/api-browser-window-spec.js
  spec/fixtures/api/window-open-preload.js
  spec/network-helper.js
Labels: 6-0-x, backport

#18735 spec: move window.open postMessage test to main runner to fix flake
  spec-main/chromium-spec.ts
  spec-main/window-helpers.ts
  spec/chromium-spec.js
  spec/fixtures/pages/window-open-postMessage-driver.html
  spec/fixtures/pages/window-open-postMessage.html
Labels: new-pr 🌱

#18726 feat: migrate protocol module to NetworkService (Part 12)
  atom/browser/net/atom_url_loader_factory.cc
  atom/browser/net/url_pipe_loader.cc
  atom/browser/net/url_pipe_loader.h
  atom/common/native_mate_converters/net_converter.cc
Labels: new-pr 🌱

#18614 fix: lost window.opener after cross-origin navigation
  patches/common/chromium/blink_initialization_order.patch
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/color_chooser_mac.patch
  patches/common/chromium/command-ismediakey.patch
  patches/common/chromium/cross_site_document_resource_handler.patch
  patches/common/chromium/disable_color_correct_rendering.patch
  patches/common/chromium/disable_hidden.patch
  patches/common/chromium/disable_time_ticks_dcheck.patch
  patches/common/chromium/fix_disable_usage_of_pthread_fchdir_np_and_pthread_chdir_np_in_mas.patch
  patches/common/chromium/fix_disable_usage_of_setapplicationisdaemon_and.patch
  patches/common/chromium/fix_test_compilation_error.patch
  patches/common/chromium/frame_host_manager.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/notification_provenance.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/support_mixed_sandbox_with_zygote.patch
  patches/common/chromium/unsandboxed_ppapi_processes_skip_zygote.patch
  patches/common/chromium/webview_cross_drag.patch
  spec/api-browser-window-spec.js
  spec/fixtures/api/window-open-preload.js
  spec/network-helper.js
Labels: 5-0-x, backport

#18720 fix: correct isDownloadable docs to match impl
  atom/browser/api/atom_api_in_app_purchase.cc
  atom/browser/mac/in_app_purchase_product.h
  atom/browser/mac/in_app_purchase_product.mm
  docs/api/structures/product.md
Labels: semver/patch, target/5-0-x, target/6-0-x

#17400 fix: callback values for printing cancellation and success
  patches/chromium/blink-worker-enable-csp-in-file-scheme.patch
  patches/chromium/blink_local_frame.patch
  patches/chromium/blink_world_context.patch
  patches/chromium/build_add_electron_tracing_category.patch
  patches/chromium/can_create_window.patch
  patches/chromium/cross_site_document_resource_handler.patch
  patches/chromium/desktop_media_list.patch
  patches/chromium/disable_user_gesture_requirement_for_beforeunload_dialogs.patch
  patches/chromium/exclude-a-few-test-files-from-build.patch
  patches/chromium/frame_host_manager.patch
  patches/chromium/printing.patch
Labels: component/printing, semver/patch, target/5-0-x, target/6-0-x

#18751 test: add test for invalid cookie url
  docs/api/cookies.md
  spec-main/api-session-spec.js
Labels: new-pr 🌱, target/6-0-x

#18483 fix: use crashpad on Windows
  BUILD.gn
  DEPS
  appveyor.yml
  atom/app/atom_main.cc
  atom/app/atom_main_delegate.cc
  atom/app/node_main.cc
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  atom/browser/ui/inspectable_web_contents.h
  atom/browser/ui/inspectable_web_contents_impl.cc
  atom/browser/ui/inspectable_web_contents_impl.h
  atom/common/api/api.mojom
  atom/common/atom_constants.cc
  atom/common/atom_constants.h
  atom/common/crash_reporter/crash_reporter.cc
  atom/common/crash_reporter/crash_reporter.h
  atom/common/crash_reporter/crash_reporter_crashpad.cc
  atom/common/crash_reporter/crash_reporter_crashpad.h
  atom/common/crash_reporter/crash_reporter_linux.cc
  atom/common/crash_reporter/crash_reporter_linux.h
  atom/common/crash_reporter/crash_reporter_mac.h
  atom/common/crash_reporter/crash_reporter_mac.mm
  atom/common/crash_reporter/crash_reporter_win.cc
  atom/common/crash_reporter/crash_reporter_win.h
  atom/common/crash_reporter/win/crash_service_main.cc
  atom/common/crash_reporter/win/crash_service_main.h
  atom/renderer/electron_api_service_impl.cc
  atom/renderer/electron_api_service_impl.h
  docs/api/crash-reporter.md
  filenames.gni
  lib/browser/crash-reporter-init.js
  lib/common/crash-reporter.js
  patches/chromium/.patches
  patches/chromium/crashpad_pid_check.patch
  patches/chromium/partially_revert_fb4ab3be3fc0024d00358d5b7816d3215a8ff20c.patch
  spec/api-crash-reporter-spec.js
  spec/fixtures/api/crash-restart.html
  spec/fixtures/api/crash.html
  spec/static/main.js
Labels: 6-0-x

#18759 docs: fix editMenu menu role etc types
  docs/api/menu-item.md
Labels: 5-0-x, backport, documentation :notebook:

#18554 feat: Add option to conditionally disable site instance patches
  DEPS
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_app.h
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  atom/common/options_switches.cc
  atom/common/options_switches.h
  atom/renderer/atom_renderer_client.cc
  docs/api/app.md
  patches/common/chromium/.patches
  patches/common/chromium/blink_local_frame.patch
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/cross_site_document_resource_handler.patch
  patches/common/chromium/frame_host_manager.patch
  patches/common/chromium/woa_compiler_workaround.patch
  spec-main/api-app-spec.ts
  spec/fixtures/api/site-instance-overrides/index.html
  spec/fixtures/api/site-instance-overrides/main.js
  spec/fixtures/api/site-instance-overrides/package.json
  spec/fixtures/api/site-instance-overrides/preload.js
Labels: 6-0-x, backport, performance :checkered_flag:

#18757 feat: provide the frame URL with permission requests and checks
  atom/browser/api/atom_api_session.cc
  atom/browser/atom_permission_manager.cc
  atom/browser/atom_permission_manager.h
  docs/api/session.md
Labels: new-pr 🌱, target/3-1-x, target/4-2-x, target/5-0-x, target/6-0-x

#18736 fix: HTML fullscreen request for sub frames
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/common_web_contents_delegate.cc
  atom/browser/common_web_contents_delegate.h
Labels: target/5-0-x, target/6-0-x

#18780 docs: fix invalid optional declaration
  docs/api/session.md
Labels: fast-track 🚅, new-pr 🌱

#18764 refactor: use app.commandLine.getSwitchValue() for parsing --user-data-dir
  lib/browser/api/app.ts
Labels: new-pr 🌱

#18748 fix: correct isDownloadable docs to match impl
  atom/browser/api/atom_api_in_app_purchase.cc
  atom/browser/mac/in_app_purchase_product.h
  atom/browser/mac/in_app_purchase_product.mm
  docs/api/structures/product.md
Labels: 5-0-x, backport

#18781 fix: HTML fullscreen request for sub frames (#18736)
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/common_web_contents_delegate.cc
  atom/browser/common_web_contents_delegate.h
Labels: 5-0-x, backport

#18766 fix: use crashpad on Windows (6-0-x)
  BUILD.gn
  DEPS
  appveyor.yml
  atom/app/atom_main.cc
  atom/app/atom_main_delegate.cc
  atom/app/node_main.cc
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  atom/browser/ui/inspectable_web_contents.h
  atom/browser/ui/inspectable_web_contents_impl.cc
  atom/browser/ui/inspectable_web_contents_impl.h
  atom/common/api/api.mojom
  atom/common/atom_constants.cc
  atom/common/atom_constants.h
  atom/common/crash_reporter/crash_reporter.cc
  atom/common/crash_reporter/crash_reporter.h
  atom/common/crash_reporter/crash_reporter_crashpad.cc
  atom/common/crash_reporter/crash_reporter_crashpad.h
  atom/common/crash_reporter/crash_reporter_linux.cc
  atom/common/crash_reporter/crash_reporter_linux.h
  atom/common/crash_reporter/crash_reporter_mac.h
  atom/common/crash_reporter/crash_reporter_mac.mm
  atom/common/crash_reporter/crash_reporter_win.cc
  atom/common/crash_reporter/crash_reporter_win.h
  atom/common/crash_reporter/win/crash_service_main.cc
  atom/common/crash_reporter/win/crash_service_main.h
  atom/renderer/electron_api_service_impl.cc
  atom/renderer/electron_api_service_impl.h
  docs/api/crash-reporter.md
  filenames.gni
  lib/browser/crash-reporter-init.js
  lib/common/crash-reporter.js
  patches/common/chromium/.patches
  patches/common/chromium/crashpad_pid_check.patch
  patches/common/chromium/partially_revert_fb4ab3be3fc0024d00358d5b7816d3215a8ff20c.patch
  spec/api-crash-reporter-spec.js
  spec/fixtures/api/crash-restart.html
  spec/fixtures/api/crash.html
  spec/static/main.js
Labels: 6-0-x, backport

#18686 fix: crash in BrowserWindow destructor after win.webContents.destroy()
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
Labels: target/3-1-x, target/4-2-x, target/5-0-x, target/6-0-x

#18793 fix: crash in BrowserWindow destructor after win.webContents.destroy()
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
Labels: 6-0-x, backport

#18756 fix: throw error on invalid URLs when setting cookie
  atom/browser/api/atom_api_cookies.cc
  docs/api/cookies.md
  spec/api-session-spec.js
Labels: backport, semver/minor, target/4-2-x

#18770 fix: use is_valid for cookie url validation
  atom/browser/api/atom_api_cookies.cc
  docs/api/cookies.md
Labels: target/6-0-x

#18779 build: use yarn to install arm modules
  vsts-arm-test-steps.yml
Labels: target/5-0-x, target/6-0-x

#18783 docs: add specific options for MenuItem.role
  docs/api/menu-item.md
Labels: documentation :notebook:, new-pr 🌱, target/5-0-x, target/6-0-x

#18804 fix: callback values for printing cancellation and success
  patches/common/chromium/printing.patch
Labels: 5-0-x, backport

#18809 test: deflake focus handling test
  spec-main/chromium-spec.ts
  spec/chromium-spec.js
Labels: new-pr 🌱

#18794 fix: crash in BrowserWindow destructor after win.webContents.destroy()
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
Labels: 5-0-x, backport

#18795 fix: crash in BrowserWindow destructor after win.webContents.destroy()
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
Labels: 4-2-x, backport

#18796 fix: crash in BrowserWindow destructor after win.webContents.destroy()
  atom/browser/api/atom_api_browser_window.cc
  atom/browser/api/atom_api_browser_window.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
Labels: 3-1-x, backport

#18744 docs: reorganize application distribution links in table of contents
  docs/README.md
Labels: documentation :notebook:

#18545 fix: Issue 924843: DCHECK failure in IsAligned(DistanceTo(target), kInstrSize) in instructions-arm64.cc
  patches/common/v8/.patches
  patches/common/v8/liftoff_correctly_unuse_labels.patch
Labels: 5-0-x, backport, security 🔒

#18519 docs: add information about persistence and removal of DevTools Extensions
  docs/tutorial/devtools-extension.md
Labels: documentation :notebook:

#18800 docs: better explain supported release line levels
  docs/tutorial/support.md
Labels: documentation :notebook:, target/4-2-x, target/5-0-x, target/6-0-x

#18838 docs: better explain supported release line levels
  docs/tutorial/support.md
Labels: 6-0-x, backport

#18839 docs: better explain supported release line levels
  docs/tutorial/support.md
Labels: 5-0-x, backport

#18840 docs: better explain supported release line levels
  docs/tutorial/support.md
Labels: 4-2-x, backport

#18818 fix: Uncaught TypeError: Cannot set property 'innerText' of null in default-app
  default_app/renderer.js
Labels: 4-2-x

#18819 fix: Uncaught TypeError: Cannot set property 'innerText' of null in default-app
  default_app/renderer.js
Labels: 5-0-x

#18803 fix: callback values for printing cancellation and success
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/crashpad_pid_check.patch
  patches/common/chromium/printing.patch
Labels: 6-0-x, backport

#18847 refactor: replace atom_version and friends with electron_version
  BUILD.gn
  atom/app/atom_library_main.mm
  atom/app/atom_main_delegate_mac.mm
  atom/app/node_main.cc
  atom/browser/api/atom_api_net_log.cc
  atom/browser/api/atom_api_power_save_blocker.cc
  atom/browser/browser_linux.cc
  atom/browser/browser_win.cc
  atom/browser/ui/file_dialog_win.cc
  atom/browser/ui/message_box_win.cc
  atom/common/api/electron_bindings.cc
  atom/common/application_info.cc
  atom/common/application_info_linux.cc
  atom/common/atom_version.h
  atom/common/crash_reporter/crash_reporter.cc
  atom/common/electron_version.h
  script/bump-version.js
Labels: new-pr 🌱

#18835 chore: update codeowners in 5-0-x
  .github/CODEOWNERS
Labels: 5-0-x, backport

#18836 chore: update codeowners in 4
  .github/CODEOWNERS
Labels: 4-2-x, backport

#18845 fix: use effectiveAppearance to check dark mode on mojave and above
  atom/browser/ui/tray_icon_cocoa.mm
Labels: 6-0-x, backport, target/4-2-x, target/5-0-x

#18849 refactor: auto generate Info.plist to avoid bumping during releases
  BUILD.gn
  atom/app/resources/mac/loginhelper-Info.plist
  atom/browser/resources/mac/Info.plist
  atom/common/resources/mac/Info.plist
  atom/renderer/resources/mac/Info.plist
  script/bump-version.js
Labels: new-pr 🌱

#18844 chore: fix current branch fetch on master
  script/lib/utils.js
Labels: fast-track 🚅, target/5-0-x, target/6-0-x

#18843 fix: use is_valid for cookie url validation
  atom/browser/api/atom_api_cookies.cc
  docs/api/cookies.md
Labels: 6-0-x, backport

#18856 docs: add example on handling the webPrefs change
  docs/api/breaking-changes.md
Labels: 6-0-x, backport, target/5-0-x

#18848 chore: remove unused enum
  atom/browser/api/atom_api_session.h
Labels: new-pr 🌱

#18867 build: enforce frozen lockfile on the lint stage
  .circleci/config.yml
Labels: fast-track 🚅

#18837 chore: improve current branch fetching
  script/lib/utils.js
  script/prepare-release.js
  script/publish-to-npm.js
  script/release-artifact-cleanup.js
Labels: 4-2-x, backport

#18868 chore: roll node to fix http2 memory leak
  DEPS
Labels: new-pr 🌱, target/5-0-x, target/6-0-x

#18883 chore: roll node to fix http2 memory leak
  DEPS
Labels: 5-0-x, backport

#18882 chore: roll node to fix http2 memory leak
  DEPS
Labels: 6-0-x, backport

#18661 fix: delay handling occlusion events to avoid flicker on macOS
  patches/chromium/.patches
  patches/chromium/chore_add_debounce_on_the_updatewebcontentsvisibility_method_to.patch
Labels: target/6-0-x

#18763 fix: app.getAppPath() returning default-app path when no package.json found
  default_app/main.ts
  spec-main/api-app-spec.ts
  spec/fixtures/api/app-path/lib/index.js
  spec/fixtures/api/app-path/package.json
Labels: target/3-1-x, target/4-2-x, target/5-0-x, target/6-0-x

#18891 docs: Document our existing language policy
  CONTRIBUTING.md
Labels: new-pr 🌱

#18887 fix: building with enable_run_as_node disabled
  atom/common/crash_reporter/crash_reporter.cc
Labels: fast-track 🚅, target/6-0-x

#18091 revert: only allow bundled preload scripts
  docs/api/breaking-changes.md
  docs/api/browser-window.md
  docs/api/session.md
  docs/api/webview-tag.md
  filenames.auto.gni
  lib/browser/rpc-server.js
  lib/common/path-utils.ts
  lib/renderer/init.ts
  spec/api-web-contents-spec.js
Labels: target/6-0-x

#18870 fix: bundle swiftshader and ANGLE libraries on mac
  BUILD.gn
  script/dist_zip.mac.x64.manifest
  script/dist_zip.mac_mas.x64.manifest
Labels: app-feedback-program, target/6-0-x

#18881 chore: revert "chore: reformat C++ code to make the linter happy"
  atom/common/node_bindings.cc
Labels: new-pr 🌱

#18899 fix: typo in comment
  lib/renderer/init.ts
Labels: new-pr 🌱

#18798 fix: set nativeWindowOpen when sandboxed
  atom/browser/atom_browser_client.cc
  atom/browser/web_contents_preferences.cc
  atom/browser/web_contents_preferences.h
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  spec/webview-spec.js
Labels: 5-0-x, backport

#18797 fix: set nativeWindowOpen when sandboxed
  atom/browser/atom_browser_client.cc
  atom/browser/web_contents_preferences.cc
  atom/browser/web_contents_preferences.h
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  spec/webview-spec.js
Labels: 4-2-x, backport

#18884 test: de-flake ses.protocol test
  spec-main/api-session-spec.js
Labels: new-pr 🌱

#18677 refactor: make savePath a property on DownloadItem
  docs/api/download-item.md
  docs/api/modernization/property-updates.md
  shell/browser/api/atom_api_download_item.cc
  spec-main/api-session-spec.js
Labels: semver/minor

#18904 fix: bundle swiftshader and ANGLE libraries on mac
  BUILD.gn
Labels: 6-0-x, backport

#18906 chore: fix branch trimming for blast-off releases
  script/lib/utils.js
Labels: 4-2-x, backport

#18907 chore: fix branch trimming for blast-off releases
  script/lib/utils.js
Labels: new-pr 🌱, target/5-0-x, target/6-0-x

#18894 fix: app.getAppPath() returning default-app path when no package.json found
  default_app/main.js
  spec/api-app-spec.js
  spec/fixtures/api/app-path/lib/index.js
  spec/fixtures/api/app-path/package.json
Labels: 5-0-x, backport

#18902 chore: use manual invocation of npx yarn
  vsts-arm-test-steps.yml
Labels: target/5-0-x

#18854 fix: sanitize invalid custom protocol headers
  shell/browser/net/url_request_async_asar_job.cc
  spec/api-protocol-spec.js
Labels: target/5-0-x, target/6-0-x

#18898 refactor: session.{clearCache,getCacheSize} nws13n
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
Labels: 5-0-x, backport, target/4-2-x

#18930 build: account for remotes in branch parsing
  script/lib/utils.js
Labels: fast-track 🚅, target/4-2-x, target/6-0-x

#18910 docs: fix spelling and grammar errors
  docs/api/app.md
  docs/api/breaking-changes.md
  docs/api/browser-view.md
  docs/api/browser-window.md
  docs/api/chrome-command-line-switches.md
  docs/api/client-request.md
  docs/api/clipboard.md
  docs/api/cookies.md
  docs/api/crash-reporter.md
  docs/api/download-item.md
  docs/api/structures/cpu-usage.md
  docs/api/structures/ipc-main-event.md
  docs/api/structures/trace-config.md
  docs/faq.md
  docs/styleguide.md
  docs/tutorial/automated-testing-with-a-custom-driver.md
  docs/tutorial/boilerplates-and-clis.md
  docs/tutorial/testing-on-headless-ci.md
Labels: documentation :notebook:

#18927 fix: sanitize invalid custom protocol headers
  atom/browser/net/url_request_async_asar_job.cc
  spec/api-protocol-spec.js
Labels: 6-0-x, backport

#18895 fix: app.getAppPath() returning default-app path when no package.json found
  default_app/main.js
  spec/api-app-spec.js
  spec/fixtures/api/app-path/lib/index.js
  spec/fixtures/api/app-path/package.json
Labels: 4-2-x, backport

#18949 fix: make isDarkMode correctly detect dark mode in the auto setting on catalina
  shell/browser/api/atom_api_system_preferences_mac.mm
Labels: new-pr 🌱, target/4-2-x, target/5-0-x, target/6-0-x

#18948 fix: override the timers module impls to activate the uv loop
  lib/common/init.ts
  spec/node-spec.js
Labels: new-pr 🌱, target/4-2-x, target/5-0-x, target/6-0-x

#18956 test: move screen api tests to main process
  spec-main/api-screen-spec.ts
  spec/api-screen-spec.js
Labels: new-pr 🌱

#18947 fix: remove unused variables in specs
  spec/api-subframe-spec.js
Labels: new-pr 🌱

#18928 fix: sanitize invalid custom protocol headers
  atom/browser/net/url_request_async_asar_job.cc
  spec/api-protocol-spec.js
Labels: 5-0-x, backport

#18962 test: fix flakiness of test BrowserWindow.moveTop
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱

#18955 docs: update badges
  README.md
Labels: documentation :notebook:, new-pr 🌱

#18965 fix: override the timers module impls to activate the uv loop
  lib/common/init.js
Labels: 5-0-x, backport, target/4-2-x

#18880 fix: make tray not block main process
  shell/browser/api/atom_api_menu.h
  shell/browser/ui/atom_menu_model.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
Labels: target/4-2-x, target/5-0-x, target/6-0-x

#18964 feat: show optional authors in gtk about panel
  docs/api/app.md
  shell/browser/browser.h
  shell/browser/browser_linux.cc
Labels: enhancement :sparkles:, platform/linux

#18156 docs: precise nodeIntegrationInSubFrames and node integration for nativeWindowOpen
  docs/api/breaking-changes.md
  docs/api/browser-window.md
Labels: documentation :notebook:, target/6-0-x

#18957 fix: set size of GTK about panel icon
  docs/api/app.md
  shell/browser/browser_linux.cc
Labels: platform/linux

#18977 chore: use ScopedPumpMessagesInPrivateModes in tray
  shell/browser/api/atom_api_menu.h
  shell/browser/ui/atom_menu_model.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
Labels: component/tray

#18992 fix: Observer removal from an empty collection causes access violation
  atom/browser/api/atom_api_web_contents.h
Labels: 4-2-x, backport

#18985 docs: menuItem.registerAccelerator not available on macOS
  docs/api/menu-item.md
Labels: documentation :notebook:

#18979 fix: silent printing mode
  patches/chromium/crashpad_pid_check.patch
  patches/chromium/printing.patch
Labels: component/printing, target/5-0-x, target/6-0-x

#19015 docs: fix heading level for power-monitor docs
  docs/api/power-monitor.md
Labels: new-pr 🌱, target/4-2-x, target/5-0-x

#19016 fix: delay emitting screen events by a tick to avoid re-entrancy crash
  shell/browser/api/atom_api_screen.cc
Labels: new-pr 🌱, target/4-2-x, target/5-0-x, target/6-0-x

#18976 fix: webview crash on iframe removal
  patches/common/chromium/.patches
  patches/common/chromium/disable_detach_webview_frame.patch
  patches/common/chromium/frame_host_manager.patch
  patches/common/chromium/portals_fix_crash_when_detaching_oopif_from_portal.patch
Labels: 5-0-x, backport

#19026 docs: UploadData does not have contentType
  docs/api/protocol.md
  docs/api/structures/protocol-response-upload-data.md
  docs/api/structures/protocol-response.md
  docs/api/structures/upload-data.md
  filenames.auto.gni
Labels: fast-track 🚅

#18969 fix: make tray not block main process
  atom/browser/ui/tray_icon_cocoa.h
  atom/browser/ui/tray_icon_cocoa.mm
Labels: 6-0-x, backport, target/4-2-x, target/5-0-x

#18984 feat: add a series of new printing options
  docs/api/web-contents.md
  shell/browser/api/atom_api_web_contents.cc
Labels: component/printing
