Repository electron/electron, pull requests merged in 2019-11, with the labels that each got.

#20879 fix: use Unicode version of ShellExecute() in OpenExternalOnWorkerThread()
  shell/common/platform_util_win.cc
Labels: new-pr 🌱, target/7-0-x, target/8-x-y

#20871 refactor: migrates util::Promise to gin
  filenames.gni
  shell/browser/api/atom_api_app.cc
  shell/browser/api/atom_api_app.h
  shell/browser/api/atom_api_content_tracing.cc
  shell/browser/api/atom_api_cookies.cc
  shell/browser/api/atom_api_cookies.h
  shell/browser/api/atom_api_data_pipe_holder.cc
  shell/browser/api/atom_api_debugger.cc
  shell/browser/api/atom_api_debugger.h
  shell/browser/api/atom_api_dialog.cc
  shell/browser/api/atom_api_in_app_purchase.cc
  shell/browser/api/atom_api_in_app_purchase.h
  shell/browser/api/atom_api_net_log.cc
  shell/browser/api/atom_api_net_log.h
  shell/browser/api/atom_api_protocol.cc
  shell/browser/api/atom_api_session.cc
  shell/browser/api/atom_api_session.h
  shell/browser/api/atom_api_system_preferences.h
  shell/browser/api/atom_api_system_preferences_mac.mm
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/gpuinfo_manager.cc
  shell/browser/api/gpuinfo_manager.h
  shell/browser/api/save_page_handler.cc
  shell/browser/api/save_page_handler.h
  shell/browser/atom_download_manager_delegate.cc
  shell/browser/browser.cc
  shell/browser/browser.h
  shell/browser/browser_mac.mm
  shell/browser/printing/print_preview_message_handler.cc
  shell/browser/printing/print_preview_message_handler.h
  shell/browser/ui/certificate_trust.h
  shell/browser/ui/certificate_trust_mac.mm
  shell/browser/ui/certificate_trust_win.cc
  shell/browser/ui/file_dialog.h
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/file_dialog_mac.mm
  shell/browser/ui/file_dialog_win.cc
  shell/browser/web_dialog_helper.cc
  shell/common/api/atom_api_shell.cc
  shell/common/api/electron_bindings.cc
  shell/common/api/electron_bindings.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/promise_util.cc
  shell/common/promise_util.h
  shell/renderer/api/atom_api_context_bridge.cc
  shell/renderer/api/atom_api_renderer_ipc.cc
  shell/renderer/api/atom_api_web_frame.cc
Labels: new-pr 🌱

#20912 build: allow CircleCI timeout and retry to be set via env variables (7-0-x)
  script/release/ci-release-build.js
Labels: 7-0-x, backport

#20896 build: allow CircleCI timeout and retry to be set via env variables
  script/release/ci-release-build.js
Labels: merged/7-0-x, target/8-x-y

#20880 docs: Update the sccache name
  .circleci/config.yml
  docs/development/build-instructions-gn.md
Labels: 5-0-x, backport

#20920 chore: add patch info for setAspectRatio
  patches/chromium/feat_unset_window_aspect_ratio_on_linux.patch
Labels: fast-track 🚅

#20922 fix: trim branch name before comparing to master (#19853)
  script/lib/utils.js
Labels: 5-0-x, backport

#20924 fix: backport patch for webaudio
  patches/common/chromium/.patches
  patches/common/chromium/fix_disabling_compositor_recycling.patch
  patches/common/chromium/mojo-js_change_how_js_sends_mojo_messages.patch
  patches/common/chromium/obtain_graph_process_lock_when_nullifying_the_buffer_in_reverb.patch
Labels: 6-1-x, fast-track 🚅

#20904 fix: don't copy tray image when it's set
  shell/browser/ui/tray_icon_cocoa.mm
Labels: target/6-1-x, target/7-0-x, target/8-x-y

#20925 fix: capture the promise global to avoid userland mutation
  build/webpack/webpack.config.base.js
  filenames.auto.gni
  lib/common/asar.js
  lib/common/webpack-globals-provider.ts
  spec/api-remote-spec.js
  spec/static/main.js
Labels: target/7-0-x, target/8-x-y

#20939 fix: don't export __esModule = true by electron.ts
  lib/browser/api/exports/electron.ts
  lib/renderer/api/exports/electron.ts
  lib/sandboxed_renderer/api/exports/electron.ts
Labels: target/8-x-y

#20938 fix: cannot access nativeTheme via electron.remote
  lib/browser/api/module-keys.js
  spec/api-remote-spec.js
  spec/static/main.js
Labels: target/7-0-x, target/8-x-y

#20948 fix: proper i18n of recentDocuments item
  shell/browser/ui/cocoa/atom_menu_controller.mm
Labels: new-pr 🌱, target/7-0-x, target/8-x-y

#20789 feat: add a new contextBridge module
  default_app/index.html
  default_app/index.ts
  default_app/preload.ts
  docs/api/context-bridge.md
  filenames.auto.gni
  filenames.gni
  lib/renderer/api/context-bridge.ts
  lib/renderer/api/module-list.js
  lib/sandboxed_renderer/api/module-list.js
  native_mate/native_mate/arguments.h
  native_mate/native_mate/dictionary.h
  shell/common/native_mate_converters/blink_converter.cc
  shell/common/native_mate_converters/blink_converter.h
  shell/common/node_bindings.cc
  shell/common/promise_util.h
  shell/renderer/api/atom_api_context_bridge.cc
  shell/renderer/api/atom_api_context_bridge.h
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.cc
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.h
  spec-main/api-context-bridge-spec.ts
  spec-main/fixtures/api/context-bridge/can-bind-preload.js
  spec-main/fixtures/api/context-bridge/empty.html
  spec/asar-spec.js
Labels: 7-1-x, backport, semver/minor

#20946 fix: capture the promise global to avoid userland mutation
  build/webpack/webpack.config.base.js
  filenames.auto.gni
  lib/common/asar.js
  lib/common/webpack-globals-provider.ts
  spec/api-remote-spec.js
  spec/static/main.js
Labels: 8-x-y, backport

#20947 fix: capture the promise global to avoid userland mutation
  build/webpack/webpack.config.base.js
  filenames.auto.gni
  lib/common/asar.js
  lib/common/webpack-globals-provider.ts
  spec/api-remote-spec.js
  spec/static/main.js
Labels: 7-1-x, backport

#20959 chore: fix build with enable_electron_extensions
  shell/browser/extensions/atom_extensions_browser_client.cc
  shell/browser/extensions/atom_extensions_browser_client.h
Labels: new-pr 🌱

#20961 fix: cannot access nativeTheme via electron.remote
  lib/browser/api/module-keys.js
  spec/api-remote-spec.js
  spec/static/main.js
Labels: 7-1-x, backport

#20975 chore: upgrade ts generator for better type safety
  docs/api/protocol.md
  docs/api/structures/protocol-response-upload-data.md
  package.json
  spec-main/api-protocol-spec.ts
  yarn.lock
Labels: new-pr 🌱

#20962 fix: allow iframe-initiated HTML fullscreen to exit while in macOS fullscreen
  shell/browser/common_web_contents_delegate.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/fullscreen-ipif.html
  spec/fixtures/pages/fullscreen-oopif.html
Labels: new-pr 🌱, target/6-1-x, target/7-1-x, target/8-x-y

#20780 docs: update installation instructions for proxies
  docs/tutorial/installation.md
Labels: documentation :notebook:, target/7-1-x, target/8-x-y

#20950 docs: fix win.setIcon ts type
  docs/api/browser-window.md
  spec/ts-smoke/electron/main.ts
Labels: target/7-1-x, target/8-x-y

#20963 fix: Fix broken globalShortcuts.registerAll() on non-macOS platforms
  shell/browser/api/atom_api_global_shortcut.cc
Labels: new-pr 🌱, target/6-1-x, target/7-1-x, target/8-x-y

#20977 chore: upgrade ts generator for better type safety
  docs/api/protocol.md
  docs/api/structures/protocol-response-upload-data.md
  package.json
  spec-main/api-protocol-spec.ts
  yarn.lock
Labels: 7-1-x, backport

#20987 chore: emit the document-start and document-end events in a sandboxed renderers
  lib/sandboxed_renderer/init.js
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#20985 fix: correctly emplace optional values in the value converter
  shell/common/native_mate_converters/value_converter.h
Labels: fast-track 🚅, target/7-1-x

#20399 feat: add app.getApplicationNameForProtocol API
  docs/api/app.md
  shell/browser/api/atom_api_app.cc
  shell/browser/browser.h
  shell/browser/browser_linux.cc
  shell/browser/browser_mac.mm
  shell/browser/browser_win.cc
  spec-main/api-app-spec.ts
Labels: api-review-requested

#21020 fix: allow iframe-initiated HTML fullscreen to exit while in macOS fullscreen (6-1-x)
  atom/browser/common_web_contents_delegate.cc
  spec/chromium-spec.js
  spec/fixtures/pages/fullscreen-ipif.html
  spec/fixtures/pages/fullscreen-oopif.html
Labels: 6-1-x, backport

#21019 fix: crash on exit in aura platforms with webview
  shell/browser/web_view_manager.cc
Labels: in-flight/7-1-x, new-pr 🌱, target/8-x-y

#21022 fix: crash on exit in aura platforms with webview
  patches/chromium/.patches
  patches/chromium/fix_disabling_compositor_recycling.patch
  patches/chromium/x11_and_ozone_move_closing_logic_to_dwthplatform.patch
  shell/browser/web_view_manager.cc
Labels: 7-1-x, backport

#20726 feat: deprecate <webview>.getWebContents()
  docs/api/breaking-changes.md
  docs/api/webview-tag.md
  lib/renderer/web-view/web-view-impl.ts
  spec/fixtures/pages/webview-devtools.html
Labels: target/8-x-y

#21038 fix: webrequest api typings
  docs/api/web-request.md
Labels: 7-1-x, backport

#21021 fix: allow iframe-initiated HTML fullscreen to exit while in macOS fullscreen (7-1-x)
  shell/browser/common_web_contents_delegate.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/fullscreen-ipif.html
  spec/fixtures/pages/fullscreen-oopif.html
Labels: 7-1-x, backport

#21026 fix: refactor printing for mojo
  patches/chromium/printing.patch
  shell/browser/api/atom_api_web_contents.cc
Labels: needs-manual-bp/8-x-y

#21044 chore: remove unnecessary patches
  patches/node/.patches
  patches/node/export_environment_knodecontexttagptr.patch
  patches/node/fix_export_node_abort_and_assert.patch
  patches/node/fix_extern_the_nativemoduleenv_and_options_parser_for_debug_builds.patch
Labels: new-pr 🌱

#21048 docs: correct the syntax to caniuse.com link
  docs/tutorial/performance.md
Labels: new-pr 🌱

#20954 fix: implement 'login' event for WebContents
  docs/api/app.md
  docs/api/web-contents.md
  lib/browser/api/app.ts
  lib/browser/api/web-contents.js
  shell/browser/api/atom_api_app.cc
  shell/browser/api/atom_api_app.h
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
  shell/browser/browser.cc
  shell/browser/browser.h
  shell/browser/browser_observer.h
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  spec-main/api-app-spec.ts
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
Labels: target/7-1-x, target/8-x-y

#20827 docs: change invalid `bash session` language tag
  docs/development/patches.md
Labels: documentation :notebook:

#20825 fix: NativeImage serialization of <webview>.capturePage() result
  filenames.auto.gni
  lib/browser/guest-view-manager.js
  lib/browser/remote/server.ts
  lib/browser/rpc-server.js
  lib/common/api/clipboard.js
  lib/common/remote/type-utils.ts
  lib/common/type-utils.ts
  lib/common/web-view-methods.ts
  lib/renderer/api/remote.js
  lib/renderer/web-view/web-view-impl.ts
  spec/webview-spec.js
  typings/internal-electron.d.ts
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21042 fix: allow iframe-initiated HTML fullscreen to exit while in macOS fullscreen (8-x-y)
  shell/browser/common_web_contents_delegate.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/fullscreen-ipif.html
  spec/fixtures/pages/fullscreen-oopif.html
Labels: 8-x-y, backport

#21059 fix: refactor printing for mojo
  patches/chromium/printing.patch
  shell/browser/api/atom_api_web_contents.cc
Labels: 8-x-y, backport

#20934 docs: document webkitdirectory breaking change
  docs/api/breaking-changes.md
Labels: documentation :notebook:, target/7-1-x, target/8-x-y

#20764 feat: add 'screen' to systemPreferences.getMediaAccessStatus()
  chromium_src/BUILD.gn
  docs/api/desktop-capturer.md
  docs/api/system-preferences.md
  shell/browser/api/atom_api_system_preferences_mac.mm
  spec-main/api-system-preferences-spec.ts
Labels: target/8-x-y

#21115 chore: remove outdated v8 compat patch
  patches/v8/.patches
  patches/v8/deps_provide_more_v8_backwards_compatibility.patch
Labels: new-pr 🌱

#21114 chore: remove unused promisify code
  docs/api/modernization/promisification.md
  docs/api/process.md
  lib/common/api/deprecate.ts
  spec-main/api-deprecate-spec.ts
  typings/internal-electron.d.ts
Labels: new-pr 🌱

#21099 fix: webRequest should be able to modify CORS headers
  shell/browser/api/atom_api_web_request.cc
  shell/browser/api/atom_api_web_request.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  spec-main/api-web-request-spec.ts
Labels: target/7-1-x, target/8-x-y

#21104 fix: NativeImage serialization of <webview>.capturePage() result
  filenames.auto.gni
  lib/browser/guest-view-manager.js
  lib/browser/rpc-server.js
  lib/common/api/clipboard.js
  lib/common/type-utils.ts
  lib/common/web-view-methods.ts
  lib/renderer/web-view/web-view-impl.ts
  spec/webview-spec.js
  typings/internal-electron.d.ts
Labels: 7-1-x, backport

#21105 fix: NativeImage serialization of <webview>.capturePage() result
  filenames.gni
  lib/browser/guest-view-manager.js
  lib/browser/rpc-server.js
  lib/common/api/clipboard.js
  lib/common/type-utils.js
  lib/common/web-view-methods.js
  lib/renderer/web-view/web-view-impl.ts
  spec/webview-spec.js
  typings/internal-electron.d.ts
Labels: 6-1-x, backport

#21103 fix: NativeImage serialization of <webview>.capturePage() result
  filenames.auto.gni
  lib/browser/guest-view-manager.js
  lib/browser/remote/server.ts
  lib/browser/rpc-server.js
  lib/common/api/clipboard.js
  lib/common/remote/type-utils.ts
  lib/common/type-utils.ts
  lib/common/web-view-methods.ts
  lib/renderer/api/remote.js
  lib/renderer/web-view/web-view-impl.ts
  spec/webview-spec.js
  typings/internal-electron.d.ts
Labels: 8-x-y, backport

#21116 feat: add 'screen' to systemPreferences.getMediaAccessStatus()
  chromium_src/BUILD.gn
  docs/api/desktop-capturer.md
  docs/api/system-preferences.md
  shell/browser/api/atom_api_system_preferences_mac.mm
  shell/browser/mac/atom_application.h
  spec-main/api-system-preferences-spec.ts
Labels: 8-x-y, backport, new-pr 🌱

#21117 feat: add app.getApplicationNameForProtocol API (8-x-y)
  docs/api/app.md
  shell/browser/api/atom_api_app.cc
  shell/browser/browser.h
  shell/browser/browser_linux.cc
  shell/browser/browser_mac.mm
  shell/browser/browser_win.cc
  spec-main/api-app-spec.ts
Labels: 8-x-y, backport, new-pr 🌱

#21122 fix: webRequest should be able to modify CORS headers (8-x-y)
  shell/browser/api/atom_api_web_request_ns.cc
  shell/browser/api/atom_api_web_request_ns.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  spec-main/api-web-request-spec.ts
Labels: 8-x-y, backport

#21098 fix: implement login event for WebContents
  docs/api/app.md
  docs/api/web-contents.md
  lib/browser/api/app.ts
  lib/browser/api/web-contents.js
  shell/browser/api/atom_api_app.cc
  shell/browser/api/atom_api_app.h
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
  shell/browser/browser.cc
  shell/browser/browser.h
  shell/browser/browser_observer.h
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  spec-main/api-app-spec.ts
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
Labels: 8-x-y, backport

#21134 chore: Reset version for 8-x-y
  ELECTRON_VERSION
  package.json
  shell/browser/resources/win/atom.rc
Labels: new-pr 🌱

#21123 fix: webRequest should be able to modify CORS headers (7-1-x)
  docs/api/web-request.md
  shell/browser/api/atom_api_web_request_ns.cc
  shell/browser/api/atom_api_web_request_ns.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  spec-main/api-web-request-spec.ts
  spec/fixtures/pages/jquery.html
Labels: 7-1-x, backport

#21100 fix: incorrect size of windows on differently scaled monitors
  shell/browser/native_window_views_win.cc
Labels: in-flight/6-1-x, in-flight/7-1-x, in-flight/8-x-y

#21139 fix: incorrect size of windows on differently scaled monitors
  shell/browser/native_window_views_win.cc
Labels: 8-x-y, backport

#21138 fix: incorrect size of windows on differently scaled monitors
  shell/browser/native_window_views_win.cc
Labels: 7-1-x, backport

#21137 fix: incorrect size of windows on differently scaled monitors
  atom/browser/native_window_views_win.cc
Labels: 6-1-x, backport

#21097 fix: implement login event for WebContents
  docs/api/app.md
  docs/api/web-contents.md
  lib/browser/api/app.ts
  lib/browser/api/web-contents.js
  shell/browser/api/atom_api_app.cc
  shell/browser/api/atom_api_app.h
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
  shell/browser/browser.cc
  shell/browser/browser.h
  shell/browser/browser_observer.h
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  spec-main/api-app-spec.ts
  spec-main/api-session-spec.js
  spec-main/api-web-contents-spec.ts
Labels: 7-1-x, backport

#21141 fix: backport libuv patch for uv_spawn() ENOMEM on empty env
  patches/node/.patches
  patches/node/win-fix-uv_spawn-ENOMEM-on-empty-env.patch
Labels: 6-1-x, backport

#21140 fix: backport libuv patch for uv_spawn() ENOMEM on empty env
  patches/node/.patches
  patches/node/win-fix-uv_spawn-ENOMEM-on-empty-env.patch
Labels: 7-1-x, in-flight/6-1-x

#21132 build: missing include in windows release builds
  patches/breakpad/.patches
  patches/breakpad/chore_fix_ftbfs_from_stl_features_used_but_not_included.patch
  patches/chromium/.patches
  patches/chromium/fix_add_missing_include_algorithm_as_needed.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/put_back_deleted_colors_for_autofill.patch
  patches/config.json
  script/lib/git.py
Labels: 8-x-y, backport

#21113 fix: stream protocols sometimes flake out
  shell/browser/net/node_stream_loader.cc
Labels: target/7-1-x, target/8-x-y

#21166 docs: fix `isMactemplateImage` type definition
  docs/api/native-image.md
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21188 fix: crash using v8 Date.toLocale* api with invalid locales
  patches/common/v8/.patches
  patches/common/v8/fix_crash_under_lb_lu_locale.patch
Labels: 6-1-x, new-pr 🌱

#21164 fix: allow chromium to handle WM_NCCALCSIZE for frameless windows
  filenames.gni
  script/lib/utils.js
  shell/browser/native_window_views_win.cc
  shell/browser/ui/views/atom_views_delegate.cc
  shell/browser/ui/views/atom_views_delegate.h
  shell/browser/ui/views/atom_views_delegate_win.cc
  shell/browser/ui/win/atom_desktop_window_tree_host_win.cc
  shell/browser/ui/win/atom_desktop_window_tree_host_win.h
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21184 build: use python3 to download external binaries
  DEPS
  script/lib/config.py
  script/lib/util.py
Labels: target/8-x-y

#21193 build: use symbol_level 1 for 32bit linux releases
  .circleci/config.yml
Labels: fast-track 🚅, target/8-x-y

#21178 docs: document webkitdirectory breaking change
  docs/api/breaking-changes.md
Labels: 7-1-x, backport

#21205 fix: allow chromium to handle WM_NCCALCSIZE for frameless windows
  filenames.gni
  shell/browser/native_window_views_win.cc
  shell/browser/ui/views/atom_views_delegate.cc
  shell/browser/ui/views/atom_views_delegate.h
  shell/browser/ui/views/atom_views_delegate_win.cc
  shell/browser/ui/win/atom_desktop_window_tree_host_win.cc
  shell/browser/ui/win/atom_desktop_window_tree_host_win.h
Labels: 7-1-x, backport

#21175 test: skip flaky <webview>.capturePage() test on Windows
  spec/webview-spec.js
Labels: 6-1-x, 7-1-x, 8-x-y

#21206 fix: allow chromium to handle WM_NCCALCSIZE for frameless windows
  atom/browser/native_window_views_win.cc
  atom/browser/ui/views/atom_views_delegate.cc
  atom/browser/ui/views/atom_views_delegate.h
  atom/browser/ui/views/atom_views_delegate_win.cc
  atom/browser/ui/win/atom_desktop_window_tree_host_win.cc
  atom/browser/ui/win/atom_desktop_window_tree_host_win.h
  filenames.gni
Labels: 6-1-x, backport

#21192 fix: disable Touch Bar typing suggestions with autocorrect=off and spellcheck=false
  patches/chromium/.patches
  patches/chromium/can_create_window.patch
  patches/chromium/disable_color_correct_rendering.patch
  patches/chromium/make_autocorrect_off_and_spellcheck_false_disable_touch_bar_typing.patch
Labels: 7-1-x, new-pr 🌱

#21207 chore: Revert "Bump v8.0.0-beta.3"
  ELECTRON_VERSION
  package.json
  shell/browser/resources/win/atom.rc
Labels: fast-track 🚅

#21191 fix: disable Touch Bar typing suggestions with autocorrect=off and spellcheck=false
  patches/common/chromium/.patches
  patches/common/chromium/make_autocorrect_off_and_spellcheck_false_disable_touch_bar_typing.patch
Labels: 6-1-x, new-pr 🌱

#21209 docs: document webkitdirectory breaking change
  docs/api/breaking-changes.md
Labels: 8-x-y, backport

#21185 docs: document the channel param for `event.reply`
  docs/api/structures/ipc-main-event.md
Labels: new-pr 🌱

#21215 build: use python3 to download external binaries (#21184)
  .circleci/config.yml
Labels: 6-1-x, backport

#21169 fix: menu should not be garbage-collected when popuping
  shell/browser/api/atom_api_menu.cc
  shell/browser/api/atom_api_menu.h
  shell/browser/api/atom_api_menu_mac.h
  shell/browser/api/atom_api_menu_mac.mm
  shell/browser/api/atom_api_menu_views.cc
  shell/browser/api/atom_api_menu_views.h
  shell/browser/ui/cocoa/atom_menu_controller.h
  shell/browser/ui/cocoa/atom_menu_controller.mm
  spec-main/api-menu-spec.ts
Labels: target/5-0-x, target/6-1-x, target/7-1-x, target/8-x-y

#21224 fix: menu should not be garbage-collected when popuping (8-x-y)
  native_mate/native_mate/function_template.h
  shell/browser/api/atom_api_menu.cc
  shell/browser/api/atom_api_menu.h
  shell/browser/api/atom_api_menu_mac.h
  shell/browser/api/atom_api_menu_mac.mm
  shell/browser/api/atom_api_menu_views.cc
  shell/browser/api/atom_api_menu_views.h
  shell/browser/ui/cocoa/atom_menu_controller.h
  shell/browser/ui/cocoa/atom_menu_controller.mm
  shell/common/gin_helper/function_template.h
  spec-main/api-menu-spec.ts
Labels: 8-x-y, backport

#21221 fix: focus with OOPIF embedded inside <webview>
  patches/common/chromium/.patches
  patches/common/chromium/fix_focusowningwebcontents_to_handle_renderwidgethosts_for_oopifs.patch
Labels: 6-1-x, backport

#21219 fix: focus with OOPIF embedded inside <webview>
  patches/chromium/.patches
  patches/chromium/fix_focusowningwebcontents_to_handle_renderwidgethosts_for_oopifs.patch
  patches/chromium/fix_missing_algorithm_include.patch
  patches/chromium/printing.patch
Labels: in-flight/6-1-x, in-flight/7-1-x, new-pr 🌱, target/8-x-y

#21223 fix: focus with OOPIF embedded inside <webview>
  patches/chromium/.patches
  patches/chromium/fix_focusowningwebcontents_to_handle_renderwidgethosts_for_oopifs.patch
Labels: 7-1-x, backport

#21226 fix: menu should not be garbage-collected when popuping (6-1-x)
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_menu.h
  atom/browser/api/atom_api_menu_mac.h
  atom/browser/api/atom_api_menu_mac.mm
  atom/browser/api/atom_api_menu_views.cc
  atom/browser/api/atom_api_menu_views.h
  atom/browser/ui/cocoa/atom_menu_controller.h
  atom/browser/ui/cocoa/atom_menu_controller.mm
  native_mate/native_mate/function_template.h
Labels: 6-1-x, backport

#21232 build: update release build endpoint from /jobs to /job
  script/release/ci-release-build.js
Labels: fast-track 🚅, target/8-x-y

#21225 fix: menu should not be garbage-collected when popuping (7-1-x)
  native_mate/native_mate/function_template.h
  shell/browser/api/atom_api_menu.cc
  shell/browser/api/atom_api_menu.h
  shell/browser/api/atom_api_menu_mac.h
  shell/browser/api/atom_api_menu_mac.mm
  shell/browser/api/atom_api_menu_views.cc
  shell/browser/api/atom_api_menu_views.h
  shell/browser/ui/cocoa/atom_menu_controller.h
  shell/browser/ui/cocoa/atom_menu_controller.mm
  spec-main/api-menu-spec.ts
Labels: 7-1-x, backport

#21227 fix: menu should not be garbage-collected when popuping (5-0-x)
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_menu.h
  atom/browser/api/atom_api_menu_mac.h
  atom/browser/api/atom_api_menu_mac.mm
  atom/browser/api/atom_api_menu_views.cc
  atom/browser/api/atom_api_menu_views.h
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/ui/cocoa/atom_menu_controller.h
  atom/browser/ui/cocoa/atom_menu_controller.mm
  atom/common/native_mate_converters/callback.h
  atom/common/native_mate_converters/once_callback.h
  filenames.gni
  native_mate/native_mate/function_template.h
Labels: 5-0-x, backport

#21135 fix: implement 'login' event for net.ClientRequest
  docs/api/app.md
  docs/api/client-request.md
  docs/api/web-contents.md
  lib/browser/api/net.js
  patches/chromium/.patches
  patches/chromium/add_trustedauthclient_to_urlloaderfactory.patch
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/api/atom_api_url_request_ns.h
  shell/browser/atom_browser_context.cc
  shell/browser/atom_browser_context.h
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  spec-main/api-net-spec.ts
  spec-main/api-session-spec.js
  spec-main/api-web-contents-spec.ts
Labels: 7-1-x, backport

#21235 docs: remove string literal type from window events
  docs/api/browser-window.md
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21247 ci: handle network drive not being available
  appveyor.yml
Labels: target/7-1-x, target/8-x-y

#21187 fix: record cpu_profiler data for main process
  shell/app/atom_main_delegate.cc
  shell/app/atom_main_delegate.h
  shell/browser/atom_browser_main_parts.cc
  shell/browser/atom_browser_main_parts.h
Labels: target/7-1-x, target/8-x-y

#21241 fix: conversion of NativeImage from path
  shell/browser/api/atom_api_web_contents.cc
  shell/common/api/atom_api_native_image.cc
  shell/common/api/atom_api_native_image.h
  shell/common/api/atom_api_native_image_mac.mm
  shell/common/gin_converters/image_converter.cc
  spec-main/api-web-contents-spec.ts
Labels: 8-x-y

#21190 feat: expose executeJavaScriptInIsolatedWorld on webContents
  docs/api/web-contents.md
  lib/browser/api/web-contents.js
  spec-main/api-web-contents-spec.ts
Labels: semver/minor, target/8-x-y

#21264 fix: avert use-after-free crash in contextBridge
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.cc
Labels: target/7-1-x, target/8-x-y

#21263 fix: reloadIgnoringCache() should ignore the cache
  lib/browser/navigation-controller.js
  shell/browser/api/atom_api_web_contents.cc
Labels: target/7-1-x, target/8-x-y

#21277 fix: record cpu_profiler data for main process
  shell/app/atom_main_delegate.cc
  shell/app/atom_main_delegate.h
  shell/browser/atom_browser_main_parts.cc
  shell/browser/atom_browser_main_parts.h
Labels: 7-1-x, backport

#21284 fix: reloadIgnoringCache() should ignore the cache
  lib/browser/navigation-controller.js
  shell/browser/api/atom_api_web_contents.cc
Labels: 7-1-x, backport

#21055 fix: allow reading body from non-2xx responses in net.request
  shell/browser/api/atom_api_url_request.cc
  spec-main/api-net-spec.ts
  spec-main/api-session-spec.ts
Labels: target/7-1-x, target/8-x-y

#21133 fix: implement 'login' event for net.ClientRequest
  docs/api/app.md
  docs/api/client-request.md
  docs/api/web-contents.md
  lib/browser/api/net.js
  patches/chromium/.patches
  patches/chromium/add_trustedauthclient_to_urlloaderfactory.patch
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/api/atom_api_url_request_ns.h
  shell/browser/atom_browser_context.cc
  shell/browser/atom_browser_context.h
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  shell/browser/net/asar/asar_url_loader.cc
  spec-main/api-net-spec.ts
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
Labels: 8-x-y, backport

#21285 fix: allow reading body from non-2xx responses in net.request (#21055)
  shell/browser/api/atom_api_url_request_ns.cc
  spec-main/api-net-spec.ts
  spec-main/api-session-spec.ts
Labels: 8-x-y, backport, target/7-1-x

#21266 feat: add session.addWordToSpellCheckerDictionary to allow custom words in the dictionary
  docs/api/session.md
  shell/browser/api/atom_api_session.cc
  shell/browser/api/atom_api_session.h
Labels: semver/minor, target/8-x-y

#21276 fix: record cpu_profiler data for main process (#21187)
  shell/app/atom_main_delegate.cc
  shell/app/atom_main_delegate.h
  shell/browser/atom_browser_main_parts.cc
  shell/browser/atom_browser_main_parts.h
Labels: 8-x-y, backport

#21286 fix: restore --ignore-connections-limit functionality
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21287 chore: add deprecation warning for the default of allowRendererProcessReuse
  default_app/default_app.ts
  lib/browser/api/web-contents.js
  shell/browser/api/atom_api_app.cc
  shell/browser/api/atom_api_app.h
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
  spec/fixtures/api/window-all-closed/main.js
Labels: fast-track 🚅

#21244 refactor: rewrite the net module to simplify state tracking
  docs/api/client-request.md
  filenames.gni
  lib/browser/api/net.js
  shell/browser/api/atom_api_net.cc
  shell/browser/api/atom_api_net.h
  shell/browser/api/atom_api_url_loader.cc
  shell/browser/api/atom_api_url_loader.h
  shell/browser/api/atom_api_url_request.cc
  shell/browser/api/atom_api_url_request.h
  shell/browser/atom_browser_context.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  shell/renderer/electron_api_service_impl.cc
  spec-main/api-net-spec.ts
Labels: target/7-1-x, target/8-x-y

#21279 ci: generate debug symbols on Linux
  .circleci/config.yml
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/config.py
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload.py
  script/strip-binaries.py
  script/zip-symbols.py
Labels: 7-1-x, backport

#21299 fix: restore --ignore-connections-limit functionality
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
Labels: 7-1-x, backport

#21280 ci: generate debug symbols on Linux
  .circleci/config.yml
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/config.py
  script/lib/util.py
  script/release.js
  script/strip-binaries.py
  script/upload.py
  script/zip-symbols.py
Labels: 6-1-x, backport

#21298 fix: restore --ignore-connections-limit functionality
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
Labels: 8-x-y, backport

#20884 build: disable `strip_absolute_paths_from_debug_symbols` on debug.gn(ref #20775)
  build/args/testing.gn
Labels: target/7-1-x, target/8-x-y

#21303 refactor: rewrite the net module to simplify state tracking
  docs/api/client-request.md
  filenames.gni
  lib/browser/api/net.js
  shell/browser/api/atom_api_net.cc
  shell/browser/api/atom_api_net.h
  shell/browser/api/atom_api_url_loader.cc
  shell/browser/api/atom_api_url_loader.h
  shell/browser/api/atom_api_url_request_ns.cc
  shell/browser/api/atom_api_url_request_ns.h
  shell/browser/atom_browser_context.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  shell/renderer/electron_api_service_impl.cc
  spec-main/api-net-spec.ts
Labels: 8-x-y, backport

#21334 build: fix building with enable_builtin_spellchecker = false
  BUILD.gn
  chromium_src/BUILD.gn
  shell/browser/api/atom_api_session.cc
Labels: target/8-x-y
