Repository electron/electron, pull requests merged in 2019-02, with the labels that each got.

#16671 fix: shutdown after message loop is ready
  atom/browser/atom_browser_main_parts.cc
  atom/browser/browser.cc
  atom/browser/browser.h
  spec/api-app-spec.js
  spec/api-browser-view-spec.js
  spec/api-web-contents-spec.js
  spec/api-web-contents-view-spec.js
Labels: 5-0-x

#16661 docs: fix referrer typedef in OnCompletedDetails
  docs/api/web-request.md
Labels: target/4-0-x, target/5-0-x

#16659 fix: show proper clerk notes in release notes script
  script/release-notes/notes.js
Labels: target/4-0-x, target/5-0-x

#16643 fix: deprecate promise functions properly
  lib/browser/api/app.js
  lib/browser/api/session.js
  lib/browser/api/web-contents.js
  lib/common/api/deprecate.js
  lib/renderer/api/desktop-capturer.js
  spec/api-app-spec.js
  spec/api-browser-window-spec.js
  spec/api-deprecations-spec.js
  spec/api-desktop-capturer-spec.js
  spec/api-protocol-spec.js
Labels: 5-0-x, backport

#16615 feat: Add API to inspect a Shared Worker
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  docs/api/web-contents.md
  docs/api/webview-tag.md
  lib/browser/api/browser-window.js
  lib/common/web-view-methods.js
Labels: semver/minor, target/5-0-x

#16656 ci: Move MacOS CI to CircleCI (5-0-x)
  .circleci/config.yml
  script/ci-release-build.js
  spec/api-app-spec.js
  vsts.yml
Labels: 5-0-x, backport

#16642 feat: promisify contentTracing recording APIs
  atom/browser/api/atom_api_content_tracing.cc
  docs/api/content-tracing.md
  docs/api/promisification.md
  lib/browser/api/content-tracing.js
  spec/api-content-tracing-spec.js
Labels: 5-0-x, backport

#16624 feat: promisify contentTracing.getCategories()
  atom/browser/api/atom_api_content_tracing.cc
  docs/api/content-tracing.md
  docs/api/promisification.md
  lib/browser/api/content-tracing.js
Labels: 5-0-x, backport

#16702 feat: promisify cookies api
  atom/browser/api/atom_api_cookies.cc
  atom/browser/api/atom_api_cookies.h
  docs/api/cookies.md
  docs/api/promisification.md
  lib/browser/api/session.js
  spec/api-net-spec.js
  spec/api-session-spec.js
  spec/fixtures/api/cookie-app/main.js
Labels: 5-0-x, backport

#16647 fix: use async save dialog for anchor download attribute (4-0-x)
  atom/browser/atom_download_manager_delegate.cc
  atom/browser/atom_download_manager_delegate.h
Labels: 4-0-x, backport

#16694 fix: show proper clerk notes in release notes script
  script/release-notes/notes.js
Labels: 4-0-x, backport

#16720 chore: fix falsy comments edge case in release notes
  script/release-notes/notes.js
Labels: target/5-0-x

#16715 chore: remove unused variable in removeWindow
  atom/browser/api/atom_api_top_level_window.cc
Labels: target/5-0-x

#16719 feat: support capslock and numlock as accelerators
  atom/common/keyboard_util.cc
  docs/api/accelerator.md
Labels: target/5-0-x

#16374 fix: crash when calling setProgressBar on macOS
  atom/browser/native_window_mac.mm
Labels: target/3-1-x, target/4-0-x, target/5-0-x

#16654 fix: correctly handle IPC for promise-based methods
  lib/browser/guest-view-manager.js
  lib/common/web-view-methods.js
  lib/renderer/web-view/web-view.js
Labels: 4-0-x, backport

#16708 chore: backport updated release upload code
  package-lock.json
  package.json
  script/release.js
Labels: 5-0-x, backport

#16738 fix: do not increase ref-counting in wrong thread
  atom/browser/api/atom_api_cookies.cc
Labels: 5-0-x

#16697 feat: allow Menu.buildFromTemplate() to accept MenuItems
  docs/api/menu.md
  lib/browser/api/menu.js
  spec/api-menu-spec.js
Labels: target/5-0-x

#16767 docs: added webContents.getType() method
  docs/api/web-contents.md
Labels: target/4-0-x, target/5-0-x

#16785 chore: depend on mojo audio and video in BUILD.gn
  BUILD.gn
Labels: target/5-0-x

#16800 chore: dont log 100000000 chars of URL
  lib/browser/navigation-controller.js
Labels: target/5-0-x

#16815 chore: improve existing error preservation in promisify
  lib/common/api/deprecate.js
  spec/api-deprecations-spec.js
Labels: target/5-0-x

#16629 feat: implement BrowserWindow.moveTop on X11
  atom/browser/api/atom_api_top_level_window.cc
  atom/browser/api/atom_api_top_level_window.h
  atom/browser/native_window.h
  atom/browser/native_window_views.cc
  atom/browser/native_window_views.h
  atom/browser/ui/x/x_window_utils.cc
  atom/browser/ui/x/x_window_utils.h
  docs/api/browser-window.md
  spec/api-browser-window-spec.js
Labels: semver/minor

#16782 chore: add standalone function deprecation helper
  lib/common/api/deprecate.js
  spec/api-deprecations-spec.js
Labels: target/5-0-x

#16839 chore: disable get/setLoginItemSettings specs on MAS
  spec/api-app-spec.js
Labels: target/2-0-x

#16838 chore: disable get/setLoginItemSettings specs on MAS
  spec/api-app-spec.js
Labels: target/3-1-x, target/4-0-x

#16834 fix: don't construct submenu if it's invisible
  atom/browser/ui/cocoa/atom_menu_controller.mm
Labels: target/4-0-x, target/5-0-x

#16832 fix: display empty menu item for non-visible submenus
  atom/browser/ui/cocoa/atom_menu_controller.mm
Labels: target/4-0-x, target/5-0-x

#16840 chore: make crash-reporter specs not use URL module
  spec/fixtures/api/crash-restart.html
  spec/fixtures/api/crash.html
Labels: target/4-0-x, target/5-0-x

#16770 Fix memory leak when using webFrame and spell checker
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
  filenames.gni
  lib/renderer/api/web-frame.js
  spec/api-web-frame-spec.js
Labels: target/5-0-x

#16835 fix: enable property having no effect on submenus
  atom/browser/ui/cocoa/atom_menu_controller.mm
Labels: target/4-0-x, target/5-0-x

#16867 fix: failed "creates offscreen window with correct size" spec on Mac with Retina display
  spec/api-browser-window-spec.js
Labels: target/4-0-x, target/5-0-x

#16308 fix: enable autofill popups on mac
  BUILD.gn
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/common_web_contents_delegate.cc
  atom/browser/common_web_contents_delegate.h
  atom/browser/common_web_contents_delegate_views.cc
  atom/browser/ui/autofill_popup.cc
  atom/browser/ui/cocoa/views_delegate_mac.mm
  atom/browser/ui/views/autofill_popup_view.cc
  chromium_src/BUILD.gn
  patches/common/chromium/.patches
  patches/common/chromium/autofill_size_calculation.patch
Labels: target/5-0-x

#16875 ci: Refactor mksnapshot test so that it doesn't stall.
  appveyor.yml
  script/verify-mksnapshot.py
  spec/fixtures/snapshot-items-available/main.js
  spec/fixtures/snapshot-items-available/package.json
Labels: target/5-0-x

#16887 fix: release-notes interop with clerk
  script/release-notes/notes.js
Labels: target/4-0-x, target/5-0-x

#16870 feat: add new components to Display structure
  atom/common/native_mate_converters/gfx_converter.cc
  docs/api/structures/display.md
  spec/api-screen-spec.js
Labels: semver/minor

#16822 fix: backport patch to sync exposed crypto
  patches/common/boringssl/.patches
  patches/common/boringssl/sync_sorted_ciphers.patch
  spec/node-spec.js
Labels: target/5-0-x

#16908 build: ensure that the uploaded symbol path is correct for our symbol server
  script/upload-symbols.py
Labels: target/3-0-x, target/3-1-x, target/4-0-x, target/5-0-x

#16904 feat: promisify app.dock.show()
  atom/browser/browser.h
  atom/browser/browser_mac.mm
  docs/api/app.md
  spec/api-app-spec.js
Labels: semver/major

#16447 feat: add file preview for GTK file picker
  atom/browser/ui/file_dialog_gtk.cc
Labels: target/5-0-x

#16882 ci: Move MacOS builds to CircleCI (5-0-x)
  .circleci/config.yml
  script/ci-release-build.js
  script/update-external-binaries.py
  spec/api-app-spec.js
  spec/version-bump-spec.js
  vsts.yml
Labels: 5-0-x, backport

#16801 chore: Add new webFrame IsolatedWorldInfo API and deprecate
  atom/renderer/api/atom_api_web_frame.cc
  docs/api/breaking-changes.md
  docs/api/web-frame.md
  lib/renderer/api/web-frame.js
Labels: target/5-0-x

#16941 fix: pass result to chrome.tabs.executeScript callback
  lib/renderer/chrome-api.js
Labels: target/4-0-x, target/5-0-x

#16707 feat: add Touch ID authentication support for macOS
  BUILD.gn
  atom/browser/api/atom_api_system_preferences.cc
  atom/browser/api/atom_api_system_preferences.h
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/browser/mac/atom_application.h
  docs/api/system-preferences.md
Labels: semver/minor, target/5-0-x

#16742 feat: promisify webContents.savePage()
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/atom_api_web_contents.h
  atom/browser/api/save_page_handler.cc
  atom/browser/api/save_page_handler.h
  docs/api/promisification.md
  docs/api/web-contents.md
  lib/browser/api/web-contents.js
  spec/api-browser-window-spec.js
  spec/ts-smoke/electron/main.ts
Labels: semver/major

#16920 fix: disable Chromium sandbox v2 in MAS builds
  BUILD.gn
  atom/app/atom_main.cc
Labels: target/5-0-x

#16970 docs: update dialog documentation for "undefined" ret vals
  docs/api/dialog.md
Labels: target/4-0-x, target/5-0-x

#16966 docs: document the Event interface
  docs/api/structures/event.md
  package.json
Labels: target/4-0-x, target/5-0-x

#16991 chore: move ts-smoke tests to core
  docs/api/global-shortcut.md
  package.json
  script/lint.js
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
  spec/ts-smoke/runner.js
  spec/ts-smoke/tsconfig.json
Labels: 5-0-x, backport

#17001 docs: update chromium version in 5.0.0 release schedule
  docs/tutorial/electron-timelines.md
Labels: target/5-0-x

#16992 build: make torque patch more specific for native arm builds
  patches/common/v8/build-torque-with-x64-toolchain-on-arm.patch
  vsts-arm-test-steps.yml
  vsts-arm64v8.yml
Labels: target/5-0-x

#16599 feat: add process.getSystemVersion()
  atom/common/api/atom_bindings.cc
  docs/api/process.md
  spec/api-process-spec.js
Labels: semver/minor

#16978 chore: add Then helper for native promises
  atom/common/promise_util.h
Labels: target/5-0-x

#17050 chore: properly template the Then promise helper
  atom/common/promise_util.h
Labels: target/5-0-x

#16954 feat: show user gesture type in click event
  atom/browser/api/event_emitter.cc
  docs/api/structures/keyboard-event.md
  lib/browser/api/menu.js
Labels: semver/minor

#17091 test: fix race condition in debugger spec
  spec/api-debugger-spec.js
Labels: new-pr 🌱

#17052 fix: carry through arguments in webContents.print()
  atom/browser/api/atom_api_web_contents.cc
  lib/browser/api/web-contents.js
Labels: target/4-0-x, target/5-0-x

#17065 docs: fix MenuItem `windowMenu` role description
  docs/api/menu-item.md
Labels: target/5-0-x

#17102 chore: finalize dropping support for OS X Mavericks (version 10.9)
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/browser/browser_mac.mm
  atom/browser/mac/atom_application.h
  atom/browser/mac/atom_application.mm
  atom/browser/mac/atom_application_delegate.mm
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
  atom/browser/notifications/mac/cocoa_notification.h
  atom/browser/notifications/mac/cocoa_notification.mm
  atom/browser/notifications/mac/notification_center_delegate.mm
  atom/browser/ui/cocoa/atom_ns_window.h
  atom/browser/ui/cocoa/atom_ns_window.mm
  atom/browser/ui/cocoa/atom_ns_window_delegate.mm
  atom/common/platform_util_mac.mm
Labels: target/5-0-x

#17113 chore: make util::Promise a move-only type (5-0-x)
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_content_tracing.cc
  atom/browser/api/atom_api_cookies.cc
  atom/browser/api/atom_api_debugger.cc
  atom/browser/api/atom_api_debugger.h
  atom/browser/api/atom_api_protocol.cc
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/gpuinfo_manager.cc
  atom/browser/api/gpuinfo_manager.h
  atom/browser/browser.cc
  atom/browser/browser.h
  atom/common/api/atom_api_shell.cc
  atom/common/api/atom_bindings.cc
  atom/common/api/atom_bindings.h
  atom/common/platform_util.h
  atom/common/platform_util_linux.cc
  atom/common/platform_util_mac.mm
  atom/common/platform_util_win.cc
  atom/common/promise_util.cc
  atom/common/promise_util.h
  native_mate/native_mate/arguments.h
Labels: 5-0-x, backport, new-pr 🌱

#17066 chore: augment promisifyMultiArg deprecation
  lib/browser/api/content-tracing.js
  lib/common/api/deprecate.ts
  typings/internal-electron.d.ts
Labels: target/5-0-x

#17124 chore: roll chromium 73.0.3683.54
  DEPS
  patches/common/chromium/blink_world_context.patch
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/content_browser_main_loop.patch
  patches/common/chromium/dcheck.patch
  patches/common/chromium/disable_color_correct_rendering.patch
  patches/common/chromium/disable_detach_webview_frame.patch
  patches/common/chromium/disable_user_gesture_requirement_for_beforeunload_dialogs.patch
  patches/common/chromium/frame_host_manager.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/printing.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/support_mixed_sandbox_with_zygote.patch
  patches/common/chromium/web_contents.patch
  patches/common/v8/.patches
  patches/common/v8/build-torque-with-x64-toolchain-on-arm.patch
  patches/common/v8/disallow_implicit_constructors_for_macroassembler.patch
  patches/common/v8/do_not_run_arm_arm64_mksnapshot_binaries.patch
Labels: target/5-0-x

#17123 fix: set cancelId to 1 when defaultId == 0 and no 'cancel' button
  lib/browser/api/dialog.js
Labels: target/3-1-x, target/4-0-x, target/5-0-x

#17121 refactor: make shell.ShowItemInFolder asynchronous
  atom/common/platform_util.h
  atom/common/platform_util_linux.cc
  atom/common/platform_util_mac.mm
  atom/common/platform_util_win.cc
  docs/api/shell.md
Labels: needs-manual-bp/5-0-x

#16994 chore: replace usage of deprecated beginSheetModalForWindow API
  atom/browser/ui/message_box_mac.mm
  docs/api/dialog.md
Labels: target/5-0-x

#17128 chore: Remove transparency hack
  atom/browser/api/atom_api_web_contents.cc
Labels: new-pr 🌱

#17046 docs: Fix types and missing property in WebRequest APIs
  docs/api/web-request.md
Labels: target/5-0-x

#17158 chore: remove an unused header
  atom/renderer/api/atom_api_web_frame.h
Labels: semver/patch

#16853 feat: allow MenuItems to work optionally when hidden
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_menu.h
  atom/browser/mac/atom_application.h
  atom/browser/ui/atom_menu_model.cc
  atom/browser/ui/atom_menu_model.h
  atom/browser/ui/cocoa/atom_menu_controller.mm
  docs/api/menu-item.md
  lib/browser/api/menu-item.js
  lib/browser/api/menu.js
Labels: semver/minor, target/5-0-x
