Repository electron/electron, pull requests merged in 2019-04, with the labels that each got.

#17651 chore: fix typos in feature request template instructions
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: new-pr 🌱

#17590 docs: clarify cookie domain normalization
  docs/api/cookies.md
  docs/api/structures/cookie.md
Labels: documentation :notebook:, target/4-1-x, target/5-0-x

#17616 fix: make devtools extensions load correctly
  atom/browser/api/atom_api_web_contents.cc
  atom/renderer/atom_render_frame_observer.cc
  lib/browser/chrome-extension.js
Labels: 5-0-x, backport

#17361 refactor: make applicationMenu a property on app
  docs/api/app.md
  lib/browser/api/app.ts
  lib/browser/api/top-level-window.js
  spec-main/api-app-spec.ts
Labels: semver/minor

#17625 build: optionally exclude some parts of patches from being applied
  script/lib/git.py
Labels: target/4-1-x, target/5-0-x

#17659 fix: crashes in RenderFrameImpl::OnSelectPopupMenuItem(s)
  patches/common/chromium/.patches
  patches/common/chromium/fix_crashes_in_renderframeimpl_onselectpopupmenuitem_s.patch
Labels: 4-1-x

#17658 fix: re-entracy problem with InvalidateFrameSinkId().
  patches/common/chromium/.patches
  patches/common/chromium/fix_re-entracy_problem_with_invalidateframesinkid.patch
Labels: 4-1-x

#17548 fix: the callback of beginFrameSubscription should pass NativeImage instead of Buffer
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/api/frame_subscriber.cc
  atom/browser/api/frame_subscriber.h
  spec/api-browser-window-spec.js
Labels: target/5-0-x

#17362 refactor: make accessibilitySupportEnabled a property on app
  atom/browser/api/atom_api_app.cc
  docs/api/app.md
  docs/api/modernization/property-updates.md
  lib/browser/api/app.ts
  lib/common/api/deprecate.ts
  spec-main/api-app-spec.ts
  spec/api-deprecations-spec.js
  typings/internal-electron.d.ts
Labels: semver/minor

#17679 test: remove non-applicable processMemoryInfo specs
  spec/api-browser-window-spec.js
  spec/fixtures/api/sandbox.html
Labels: target/5-0-x

#17698 fix: crash when passing empty string to recording
  atom/browser/api/atom_api_content_tracing.cc
  spec/api-content-tracing-spec.js
Labels: target/4-1-x, target/5-0-x

#17704 fix: report module name when require fails in sandboxed renderers
  lib/sandboxed_renderer/init.js
Labels: 4-1-x, backport

#17703 fix: report module name when require fails in sandboxed renderers
  lib/sandboxed_renderer/init.js
Labels: 3-1-x, backport

#17705 fix: report module name when require fails in sandboxed renderers
  lib/sandboxed_renderer/init.js
Labels: 5-0-x, backport

#17766 fix: crash when alt key pressed with falsy menu bar visiblity
  atom/browser/ui/views/root_view.cc
Labels: target/5-0-x

#17773 fix: incorrect default path setting for dl items
  atom/browser/atom_download_manager_delegate.cc
Labels: target/5-0-x

#17738 docs: note desktop audio limitation on macOS
  docs/api/desktop-capturer.md
Labels: target/3-1-x, target/4-1-x, target/5-0-x

#17712 fix: ensure the sandboxed preloads globals do not leak
  BUILD.gn
  build/js_wrap.gni
  build/js_wrap.py
  spec/api-browser-window-spec.js
  spec/fixtures/api/no-leak.html
  spec/fixtures/module/empty.js
Labels: target/5-0-x

#17800 fix: handle remote-debugging-port=0 correctly
  atom/browser/ui/devtools_manager_delegate.cc
  default_app/main.ts
  lib/browser/api/app.ts
  lib/browser/init.ts
  typings/internal-electron.d.ts
Labels: new-pr 🌱, target/5-0-x

#17796 fix: reset the NSUserNotication handle on dismiss
  atom/browser/notifications/mac/cocoa_notification.mm
Labels: target/3-1-x, target/4-1-x, target/5-0-x

#17817 fix: handle remote-debugging-port=0 correctly
  atom/browser/ui/devtools_manager_delegate.cc
  default_app/main.js
  lib/browser/api/app.js
  lib/browser/init.js
Labels: 5-0-x, backport, new-pr 🌱

#17464 fix: maintain a ref count for objects sent over remote
  atom/common/api/atom_api_v8_util.cc
  atom/common/api/remote_object_freer.cc
  atom/common/api/remote_object_freer.h
  lib/browser/objects-registry.js
  lib/browser/rpc-server.js
  lib/renderer/api/remote.js
  spec-main/window-helpers.ts
  spec/window-helpers.js
Labels: target/5-0-x

#17825 fix: maintain a ref count for objects sent over remote
  atom/common/api/atom_api_v8_util.cc
  atom/common/api/remote_object_freer.cc
  atom/common/api/remote_object_freer.h
  lib/browser/objects-registry.js
  lib/browser/rpc-server.js
  lib/renderer/api/remote.js
  spec/window-helpers.js
Labels: new-pr 🌱

#17823 fix: skip zygote for unsandboxed ppapi processes
  patches/common/chromium/.patches
  patches/common/chromium/unsandboxed_ppapi_processes_skip_zygote.patch
Labels: new-pr 🌱, target/5-0-x

#17815 docs: note desktop audio limitation on macOS
  docs/api/desktop-capturer.md
Labels: 4-1-x, backport

#17816 docs: note desktop audio limitation on macOS
  docs/api/desktop-capturer.md
Labels: 3-1-x, backport

#17818 docs: fix doc linter warnings
  docs/api/browser-window.md
  docs/api/process.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
Labels: new-pr 🌱

#17809 fix: emit process 'loaded' event in sandboxed renderers
  atom/renderer/atom_sandboxed_renderer_client.cc
  lib/sandboxed_renderer/api/ipc-renderer.js
  lib/sandboxed_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/module/preload-sandbox.js
Labels: 3-1-x, backport

#17807 fix: emit process 'loaded' event in sandboxed renderers
  atom/renderer/atom_sandboxed_renderer_client.cc
  lib/sandboxed_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/module/preload-sandbox.js
Labels: 4-1-x, backport

#17808 fix: emit process 'loaded' event in sandboxed renderers
  atom/renderer/atom_sandboxed_renderer_client.cc
  lib/sandboxed_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/module/preload-sandbox.js
Labels: 5-0-x, backport

#17829 fix: skip zygote for unsandboxed ppapi processes (backport: 5-0-x)
  patches/common/chromium/.patches
  patches/common/chromium/unsandboxed_ppapi_processes_skip_zygote.patch
Labels: new-pr 🌱

#17842 chore: remove superfluous ScopedAllowBaseSync in desktopCapturer
  atom/browser/api/atom_api_desktop_capturer.cc
Labels: new-pr 🌱, target/5-0-x

#17830 fix: ensure the sandboxed preloads globals do not leak
  BUILD.gn
  build/js_wrap.gni
  build/js_wrap.py
  spec/api-browser-window-spec.js
  spec/fixtures/api/no-leak.html
  spec/fixtures/module/empty.js
Labels: 5-0-x, backport

#17538 fix: port OSR code to new viz compositor codepath
  BUILD.gn
  atom/browser/api/atom_api_web_contents.cc
  atom/browser/native_window_mac.mm
  atom/browser/osr/osr_host_display_client.cc
  atom/browser/osr/osr_host_display_client.h
  atom/browser/osr/osr_host_display_client_mac.mm
  atom/browser/osr/osr_output_device.cc
  atom/browser/osr/osr_output_device.h
  atom/browser/osr/osr_render_widget_host_view.cc
  atom/browser/osr/osr_render_widget_host_view.h
  atom/browser/osr/osr_render_widget_host_view_mac.mm
  atom/browser/osr/osr_video_consumer.cc
  atom/browser/osr/osr_video_consumer.h
  atom/browser/osr/osr_web_contents_view.cc
  atom/browser/osr/osr_web_contents_view.h
  atom/browser/ui/autofill_popup.cc
  atom/browser/ui/views/autofill_popup_view.cc
  buildflags/buildflags.gni
  patches/common/chromium/.patches
  patches/common/chromium/compositor_delegate.patch
  patches/common/chromium/viz_osr.patch
  spec/api-browser-window-spec.js
Labels: app-feedback-program

#17826 docs: document occasional mismatch between NSImageName and string
  docs/api/native-image.md
Labels: target/4-1-x, target/5-0-x

#17844 fix: copy pixels in NativeImage::CreateFromBitmap
  atom/common/api/atom_api_native_image.cc
Labels: new-pr 🌱

#17843 fix: copy pixels in AddImageSkiaRepFromBuffer
  atom/common/api/atom_api_native_image.cc
Labels: new-pr 🌱, target/3-1-x, target/4-1-x, target/5-0-x

#17862 fix: copy pixels in AddImageSkiaRepFromBuffer (4-1-x)
  atom/common/api/atom_api_native_image.cc
Labels: 4-1-x, backport, new-pr 🌱

#17863 fix: copy pixels in AddImageSkiaRepFromBuffer (5-0-x)
  atom/common/api/atom_api_native_image.cc
Labels: 5-0-x, backport, new-pr 🌱

#17861 fix: copy pixels in AddImageSkiaRepFromBuffer (3-1-x)
  atom/common/api/atom_api_native_image.cc
Labels: 3-1-x, backport, new-pr 🌱

#17759 docs: explanation on using protocols with partitions
  docs/api/protocol.md
Labels: target/4-1-x, target/5-0-x

#17841 refactor: make app logs dir creation opt-in
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_app.h
  atom/browser/api/atom_api_app_mac.mm
  atom/browser/atom_browser_main_parts.cc
  atom/browser/atom_browser_main_parts.h
  atom/browser/atom_browser_main_parts_mac.mm
  docs/api/app.md
  filenames.gni
Labels: semver/major

#17879 fix: drain tasks before shutting down isolate (master)
  atom/browser/javascript_environment.cc
Labels: new-pr 🌱

#17877 fix: drain tasks before shutting down isolate (5-0-x)
  atom/browser/javascript_environment.cc
Labels: new-pr 🌱

#17875 fix: execute session preload scripts in sandboxed renderers (4-1-x)
  lib/browser/rpc-server.js
  lib/sandboxed_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/module/get-global-preload.js
  spec/fixtures/module/set-global-preload-3.js
Labels: 4-1-x, backport

#17904 docs: Update AFP info
  docs/tutorial/app-feedback-program.md
Labels: new-pr 🌱

#17903 docs: edit Release Timelines doc format and add title
  docs/tutorial/electron-timelines.md
Labels: new-pr 🌱

#17906 refactor: allow embedder overriding of internal FS calls
  DEPS
  lib/common/asar.js
  spec/fixtures/api/electron-main-module/app.asar
  spec/fixtures/api/electron-main-module/app/index.js
  spec/fixtures/api/electron-main-module/app/node_modules/some-module/main2.js
  spec/fixtures/api/electron-main-module/app/node_modules/some-module/package.json
  spec/node-spec.js
Labels: fast-track 🚅, new-pr 🌱

#17886 fix: crash when run from SMB network share
  atom/browser/atom_browser_main_parts_mac.mm
Labels: target/3-1-x, target/4-1-x, target/5-0-x, target/6-0-x

#17922 refactor: initialize feature list earlier
  atom/app/atom_main_delegate.cc
  atom/browser/atom_browser_main_parts.cc
  atom/browser/atom_browser_main_parts.h
  atom/browser/feature_list.cc
  atom/browser/feature_list.h
  filenames.gni
Labels: new-pr 🌱

#17930 fix: allow creating service for temporary partitions (nws13n)
  atom/browser/net/network_context_service_factory.cc
  atom/browser/net/network_context_service_factory.h
Labels: new-pr 🌱

#17931 fix: allow access to the profile dir in mac network sandbox (nws13n)
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
Labels: new-pr 🌱

#17927 fix: permission handler regression in default app
  default_app/default_app.ts
Labels: new-pr 🌱, target/6-0-x

#17624 docs: clean up the native module tutorial
  docs/tutorial/using-native-node-modules.md
Labels: target/5-0-x, target/6-0-x

#17924 chore: Bind=>BindRepeating for constructors
  atom/browser/api/atom_api_app.h
  atom/browser/api/atom_api_app_mas.mm
  atom/browser/api/atom_api_auto_updater.cc
  atom/browser/api/atom_api_browser_view.cc
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_net.cc
  atom/browser/api/atom_api_notification.cc
  atom/browser/api/atom_api_top_level_window.cc
  atom/browser/api/atom_api_tray.cc
  atom/browser/api/atom_api_view.cc
Labels: target/5-0-x, target/6-0-x

#17932 refactor: migrate cookie api to network service
  atom/browser/api/atom_api_cookies.cc
  spec/api-session-spec.js
Labels: new-pr 🌱

#17941 chore: support converting OnceCallback to V8
  atom/browser/api/atom_api_web_contents.cc
  atom/common/native_mate_converters/callback.h
  atom/common/native_mate_converters/once_callback.h
  filenames.gni
  native_mate/native_mate/converter.h
Labels: new-pr 🌱

#17557 fix: crash when failed to get devices in desktopCapturer
  atom/browser/api/atom_api_desktop_capturer.cc
  lib/browser/desktop-capturer.js
Labels: target/5-0-x, target/6-0-x

#17865 docs: move organizational info docs to new directory
  docs/README.md
  docs/api/breaking-changes.md
  docs/app-feedback-program.md
  docs/development/issues.md
  docs/development/releasing.md
  docs/electron-timelines.md
  docs/electron-versioning.md
  docs/support.md
  docs/tutorial/about.md
  docs/tutorial/supported-platforms.md
Labels: documentation :notebook:

#17958 docs: add azure vm spinup tutorial
  docs/development/azure-vm-setup.md
Labels: documentation :notebook:, target/5-0-x, target/6-0-x

#17363 feat: make badgeCount a property on app
  atom/browser/api/atom_api_app.cc
  docs/api/app.md
  docs/api/modernization/property-updates.md
  lib/browser/api/app.ts
  spec-main/api-app-spec.ts
Labels: semver/minor

#17959 docs: remove outdated refs to protocol.registerStandardSchemes
  docs/api/protocol.md
Labels: documentation :notebook:, target/5-0-x, target/6-0-x

#17961 docs: add information about contributing
  README.md
Labels: documentation :notebook:

#17971 docs: add example on handling the webPrefs change
  docs/api/breaking-changes.md
Labels: target/5-0-x, target/6-0-x

#17991 build: rebase patches to fix master build
  patches/common/boringssl/.patches
  patches/common/boringssl/support_get_versions_with_get_min_max_proto_version_for_context.patch
Labels: fast-track 🚅

#18006 chore: add base workflow file
  .github/main.workflow
Labels: new-pr 🌱

#17921 chore: upgrade chromium to 76
  DEPS
  atom/browser/api/atom_api_app.cc
  atom/browser/browser_win.cc
  atom/browser/notifications/win/notification_presenter_win.cc
  atom/browser/ui/views/autofill_popup_view.cc
  atom/browser/ui/views/menu_delegate.cc
  atom/browser/ui/views/root_view.cc
  atom/common/platform_util_win.cc
  patches/common/chromium/.patches
  patches/common/chromium/disable_custom_libcxx_on_windows.patch
Labels: fast-track 🚅

#18039 chore: disable release notes GH Action
  .github/main.workflow
Labels: fast-track 🚅

#18029 refactor: rewire the desktop capturer API to remove race conditions
  atom/browser/api/atom_api_desktop_capturer.cc
  lib/browser/desktop-capturer.js
Labels: new-pr 🌱, target/5-0-x, target/6-0-x

#17715 docs: update nodeIntegration section for new defaults
  docs/tutorial/first-app.md
  docs/tutorial/security.md
Labels: documentation :notebook:, target/5-0-x, target/6-0-x

#18022 docs: correct doc for registerFileProtocol
  docs/api/protocol.md
Labels: documentation :notebook:, target/5-0-x, target/6-0-x

#18044 feat: upgrade to Node 12
  DEPS
  atom/browser/node_debugger.cc
  atom/common/api/atom_api_asar.cc
  atom/common/node_includes.h
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/atom_sandboxed_renderer_client.cc
  build/args/all.gn
  lib/common/asar.js
  lib/common/asar_init.js
  lib/content_script/init.js
  lib/isolated_renderer/init.js
  lib/renderer/init.ts
  spec/asar-spec.js
Labels: 6-0-x, backport, fast-track 🚅, new-pr 🌱

#18035 chore: convert some apis incl. View APIs from base::Bind
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_net_log.cc
  atom/browser/api/atom_api_power_monitor.cc
  atom/browser/api/atom_api_web_contents_view.cc
  atom/browser/api/views/atom_api_box_layout.cc
  atom/browser/api/views/atom_api_button.cc
  atom/browser/api/views/atom_api_label_button.cc
  atom/browser/api/views/atom_api_layout_manager.cc
  atom/browser/api/views/atom_api_md_text_button.cc
  atom/browser/api/views/atom_api_resize_area.cc
  atom/browser/api/views/atom_api_text_field.cc
  atom/common/api/atom_api_crash_reporter.cc
  atom/common/api/electron_bindings.cc
  atom/renderer/renderer_client_base.cc
Labels: new-pr 🌱

#18030 feat: migrate protocol module to NetworkService (Part 3)
  atom/browser/net/atom_url_loader_factory.cc
  atom/browser/net/atom_url_loader_factory.h
Labels: new-pr 🌱

#17985 build: disable Vulkan validation layers
  build/args/all.gn
Labels: target/4-1-x, target/5-0-x, target/6-0-x

#17987 build: revert disabling Vulkan support (4-1-x)
  build/args/all.gn
Labels: 4-1-x, backport

#18051 docs: update nodeIntegration section for new defaults (5-0-x)
  docs/tutorial/first-app.md
  docs/tutorial/security.md
Labels: 5-0-x, backport

#18036 refactor: native_mate => gin (cookies API)
  atom/browser/api/atom_api_cookies.cc
  atom/browser/api/atom_api_cookies.h
  atom/browser/api/event_emitter.h
  native_mate/native_mate/wrappable.cc
  native_mate/native_mate/wrappable_base.h
Labels: new-pr 🌱

#17986 build: revert disabling Vulkan support (5-0-x)
  build/args/all.gn
Labels: 5-0-x, backport

#18064 build: fix issues for stable release we fixed in 5-0-x
  script/bump-version.js
  script/lib/version-utils.js
  script/prepare-release.js
Labels: target/6-0-x

#17701 refactor: make name a prop on app
  atom/browser/api/atom_api_app.cc
  default_app/main.ts
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/crash-reporter.md
  docs/api/menu.md
  docs/api/modernization/property-updates.md
  lib/browser/api/app.ts
  lib/browser/api/menu-item-roles.js
  lib/browser/crash-reporter-init.js
  lib/browser/init.ts
  spec-main/api-app-spec.ts
  spec/api-crash-reporter-spec.js
  spec/api-menu-item-spec.js
  spec/api-notification-dbus-spec.js
Labels: semver/minor, target/6-0-x

#17955 build: ensure consistent lock files across multiple machines
  .eslintrc.json
  .gitignore
  BUILD.gn
  DEPS
  atom/common/node_bindings.cc
  build/npm.gni
  build/tsc.gni
  package-lock.json
  package.json
  script/bump-version.js
  script/generate-deps-hash.js
  script/lib/npx.py
  script/lint.js
  script/spec-runner.js
  spec/package-lock.json
  spec/package.json
  spec/yarn.lock
  yarn.lock
Labels: target/6-0-x

#18074 build: fix master build by updating the yarn.lock after race merge
  yarn.lock
Labels: fast-track 🚅

#18028 fix: ensure the inspector agent is shutdown before cleaning up the node env
  atom/app/node_main.cc
  atom/browser/atom_browser_main_parts.cc
  atom/browser/node_debugger.cc
  atom/browser/node_debugger.h
  spec/fixtures/module/delay-exit.js
  spec/node-spec.js
Labels: target/5-0-x, target/6-0-x

#18046 fix: explicitly focus window on win.show()
  atom/browser/native_window_views.cc
Labels: target/4-1-x, target/5-0-x, target/6-0-x
