Repository electron/electron, pull requests merged in 2019-03, with the labels that each got.

#17178 refactor: prevent node macros from overriding base
  atom/common/node_includes.h
Labels: new-pr 🌱

#17191 chore: bump chromium to 73.0.3683.61 (master)
  DEPS
  patches/common/chromium/.patches
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/command-ismediakey.patch
  patches/common/chromium/disable_color_correct_rendering.patch
  patches/common/chromium/fix_backup_includes_for_ptrace_get_thread_area_on_arm_arm64.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/scroll_bounce_flag.patch
  patches/common/chromium/webview_cross_drag.patch
Labels: new-pr 🌱

#17192 chore: bump chromium to 73.0.3683.61 (5-0-x)
  DEPS
  patches/common/chromium/.patches
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/can_create_window.patch
  patches/common/chromium/command-ismediakey.patch
  patches/common/chromium/disable_color_correct_rendering.patch
  patches/common/chromium/fix_backup_includes_for_ptrace_get_thread_area_on_arm_arm64.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/scroll_bounce_flag.patch
  patches/common/chromium/webview_cross_drag.patch
Labels: new-pr 🌱

#17164 fix: check for pane focus before removing it.
  atom/browser/ui/views/menu_bar.cc
Labels: semver/patch, target/5-0-x

#17218 fix: correct chrome version in chrome_version.h
  atom/common/chrome_version.h
Labels: new-pr 🌱

#16973 feat: promisify dialog.showOpenDialog()
  atom/browser/api/atom_api_dialog.cc
  atom/browser/common_web_contents_delegate.cc
  atom/browser/ui/file_dialog.h
  atom/browser/ui/file_dialog_gtk.cc
  atom/browser/ui/file_dialog_mac.mm
  atom/browser/ui/file_dialog_win.cc
  atom/browser/web_dialog_helper.cc
  docs/api/dialog.md
  docs/api/promisification.md
  lib/browser/api/dialog.js
  lib/browser/chrome-devtools.js
  spec/ts-smoke/electron/main.ts
Labels: semver/major

#17214 docs: Fixed typo in registerSchemesAsPrivileged reference
  docs/api/protocol.md
Labels: target/4-0-x, target/5-0-x

#17054 feat: promisify dialog.showSaveDialog()
  atom/browser/api/atom_api_dialog.cc
  atom/browser/atom_download_manager_delegate.cc
  atom/browser/common_web_contents_delegate.cc
  atom/browser/ui/file_dialog.h
  atom/browser/ui/file_dialog_gtk.cc
  atom/browser/ui/file_dialog_mac.mm
  atom/browser/ui/file_dialog_win.cc
  atom/browser/web_dialog_helper.cc
  docs/api/dialog.md
  docs/api/promisification.md
  lib/browser/api/dialog.js
Labels: semver/major

#17227 fix: backport upstream fixes for color chooser dialogs
  patches/common/chromium/.patches
  patches/common/chromium/color_chooser.patch
  patches/common/chromium/color_chooser_mac.patch
  patches/common/chromium/color_chooser_win.patch
Labels: target/5-0-x

#17220 fix: bad assertion in crypto functions that use BN_bn2bin_padded
  DEPS
  spec/node-spec.js
Labels: target/5-0-x

#17221 fix: make StreamSubscriber ref counted
  atom/browser/api/stream_subscriber.cc
  atom/browser/api/stream_subscriber.h
  atom/browser/net/url_request_stream_job.cc
  atom/browser/net/url_request_stream_job.h
Labels: target/4-0-x, target/5-0-x

#17256 fix: FileReader: Make a copy of the ArrayBuffer when returning partial results (4-0-x)
  patches/common/chromium/.patches
  patches/common/chromium/merge_m72_filereader_make_a_copy_of_the_arraybuffer_when_returning.patch
Labels: new-pr 🌱

#17165 fix: run subframe preload bundles in isolated context
  atom/renderer/atom_render_frame_observer.cc
  spec/api-subframe-spec.js
  spec/fixtures/sub-frames/preload.js
Labels: target/5-0-x

#17274 fix: gn check errors in release build
  BUILD.gn
Labels: new-pr 🌱

#16218 fix: support chrome extensions in sandboxed renderer
  atom/renderer/atom_sandboxed_renderer_client.cc
  atom/renderer/atom_sandboxed_renderer_client.h
  lib/renderer/content-scripts-injector.ts
  lib/renderer/init.ts
  lib/sandboxed_renderer/init.js
  spec/content-script-spec.js
  spec/fixtures/extensions/content-script-document-end/end.js
  spec/fixtures/extensions/content-script-document-end/manifest.json
  spec/fixtures/extensions/content-script-document-idle/idle.js
  spec/fixtures/extensions/content-script-document-idle/manifest.json
  spec/fixtures/extensions/content-script-document-start/manifest.json
  spec/fixtures/extensions/content-script-document-start/start.js
Labels: semver/minor

#17278 build: fix incorrect reference to this.skip
  spec/api-browser-window-spec.js
Labels: target/4-0-x, target/5-0-x

#17249 feat: promisify session.clearStorageData()
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  docs/api/promisification.md
  docs/api/session.md
  lib/browser/api/session.js
  spec/api-session-spec.js
  spec/chromium-spec.js
Labels: semver/major

#17229 feat: promisify ses.clearHostResolverCache()
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  docs/api/promisification.md
  docs/api/session.md
  lib/browser/api/session.js
  spec/api-session-spec.js
Labels: semver/minor

#17219 fix: crash in ECDH.setPrivateKey
  patches/common/boringssl/.patches
  patches/common/boringssl/handle_pub_key_null_in_ec_key_set_public_key.patch
  spec/node-spec.js
Labels: target/4-0-x, target/5-0-x

#17222 feat: promisify session proxy methods
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  atom/common/promise_util.h
  docs/api/promisification.md
  docs/api/session.md
  lib/browser/api/session.js
  spec/api-session-spec.js
Labels: semver/major

#17297 fix: crash in ECDH.setPrivateKey (backport: 4-0-x)
  patches/common/boringssl/.patches
  patches/common/boringssl/handle_pub_key_null_in_ec_key_set_public_key.patch
  spec/node-spec.js
Labels: new-pr 🌱

#17185 feat: promisify session cache methods
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  docs/api/promisification.md
  docs/api/session.md
  docs/styleguide.md
  lib/browser/api/session.js
Labels: semver/minor

#17259 feat: promisify session.clearAuthCache()
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  docs/api/promisification.md
  docs/api/session.md
  lib/browser/api/session.js
  spec/api-session-spec.js
Labels: semver/minor

#17323 fix: remove label/image from segment if they are mutated to null
  atom/browser/ui/cocoa/atom_touch_bar.mm
Labels: new-pr 🌱, target/3-1-x, target/4-0-x, target/5-0-x

#17277 build: move macos release builds to CircleCI (3-1-x)
  .circleci/config.yml
  script/ci-release-build.js
  vsts.yml
Labels: target/3-0-x

#17300 test: robustify sendInputEvent beforeEach hook
  spec/api-web-contents-spec.js
Labels: target/4-0-x, target/5-0-x

#17357 chore: fix default_app showMessageBox
  default_app/default_app.ts
Labels: new-pr 🌱

#17291 fix: improve focused menu bar item visibility
  atom/browser/ui/views/submenu_button.cc
Labels: target/5-0-x

#17344 fix: don't crash when nativeImage.createFromBuffer() is called with invalid buffer
  atom/common/api/atom_api_native_image.cc
  spec/api-native-image-spec.js
Labels: target/3-1-x, target/4-0-x, target/5-0-x

#17355 feat: promisify In-App Purchase
  atom/browser/api/atom_api_in_app_purchase.cc
  atom/browser/api/atom_api_in_app_purchase.h
  atom/browser/mac/in_app_purchase.h
  atom/browser/mac/in_app_purchase.mm
  atom/browser/mac/in_app_purchase_product.h
  atom/browser/mac/in_app_purchase_product.mm
  docs/api/in-app-purchase.md
  docs/api/promisification.md
  docs/tutorial/in-app-purchases.md
  lib/browser/api/in-app-purchase.js
  spec/api-in-app-purchase-spec.js
Labels: semver/minor

#17303 feat: promisify session.getBlobData()
  atom/browser/api/atom_api_session.cc
  atom/browser/api/atom_api_session.h
  atom/browser/atom_blob_reader.cc
  atom/browser/atom_blob_reader.h
  docs/api/promisification.md
  docs/api/session.md
  lib/browser/api/session.js
  spec/api-session-spec.js
Labels: semver/major

#17359 feat: add native emoji picker
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_app.h
  atom/browser/browser.h
  atom/browser/browser_linux.cc
  atom/browser/browser_mac.mm
  atom/browser/browser_win.cc
  docs/api/app.md
Labels: semver/minor

#17181 feat: promisify dialog.showCertificateTrustDialog()
  atom/browser/ui/certificate_trust.h
  atom/browser/ui/certificate_trust_mac.mm
  atom/browser/ui/certificate_trust_win.cc
  docs/api/dialog.md
  docs/api/promisification.md
  lib/browser/api/dialog.js
Labels: semver/major

#17226 feat: enable NodeIntegrationInSubFrames for webview
  docs/api/webview-tag.md
  lib/browser/guest-view-manager.js
  lib/renderer/web-view/web-view-attributes.ts
  lib/renderer/web-view/web-view-constants.ts
  lib/renderer/web-view/web-view-element.ts
  spec/api-subframe-spec.js
  spec/fixtures/sub-frames/frame-container-webview.html
  spec/fixtures/sub-frames/frame-with-frame-container-webview.html
Labels: target/5-0-x

#17401 fix: throw error when inserting menu items out-of-range
  lib/browser/api/menu.js
  spec/api-menu-spec.js
Labels: target/3-1-x, target/4-0-x, target/5-0-x

#17380 fix: pass the correct HostPort into the node inspector
  atom/browser/node_debugger.cc
  spec/node-spec.js
Labels: target/5-0-x

#17385 feat: add tray.getTitle()
  atom/browser/api/atom_api_tray.cc
  atom/browser/api/atom_api_tray.h
  atom/browser/ui/tray_icon.cc
  atom/browser/ui/tray_icon.h
  atom/browser/ui/tray_icon_cocoa.h
  atom/browser/ui/tray_icon_cocoa.mm
  docs/api/tray.md
  spec/api-tray-spec.js
Labels: semver/minor

#17376 docs: document modernization initiative more clearly
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/content-tracing.md
  docs/api/cookies.md
  docs/api/debugger.md
  docs/api/desktop-capturer.md
  docs/api/dialog.md
  docs/api/in-app-purchase.md
  docs/api/modernization/overview.md
  docs/api/modernization/promisification.md
  docs/api/modernization/property-updates.md
  docs/api/net-log.md
  docs/api/protocol.md
  docs/api/session.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  docs/api/webview-tag.md
  filenames.auto.gni
Labels: documentation :notebook:

#17454 docs: fix typo
  docs/api/webview-tag.md
Labels: new-pr 🌱

#17412 chore: remove special handling for dialog methods in remote module
  lib/browser/api/dialog.js
  lib/browser/rpc-server.js
  spec/api-ipc-main-spec.js
Labels: semver/major

#17441 test: fix isEmpty() checks in nativeImage tests
  spec/api-native-image-spec.js
Labels: new-pr 🌱

#17382 feat: add systemPreferences.getAnimationSettings()
  atom/browser/api/atom_api_system_preferences.cc
  atom/browser/api/atom_api_system_preferences.h
  docs/api/system-preferences.md
  spec/api-system-preferences-spec.js
Labels: semver/minor

#17405 feat: expose colorSpace to display object
  atom/common/native_mate_converters/gfx_converter.cc
  docs/api/structures/display.md
  spec/api-screen-spec.js
Labels: semver/minor

#17443 fix: check the result when calling js function
  atom/common/native_mate_converters/callback.h
  atom/common/native_mate_converters/v8_value_converter.cc
  atom/renderer/api/atom_api_spell_check_client.cc
  native_mate/native_mate/wrappable.cc
  spec/api-browser-window-spec.js
Labels: target/5-0-x

#17469 fix: use a more unique identifier for NSUserNotification instances
  atom/browser/notifications/mac/cocoa_notification.mm
Labels: new-pr 🌱, target/3-1-x, target/4-1-x, target/5-0-x

#17467 docs: Use correct image URL on `docs/tutorial/windows-taskbar.md`
  docs/tutorial/windows-taskbar.md
Labels: new-pr 🌱

#17463 fix: take foreground visibility into account for win.isVisible() on macOS
  atom/browser/native_window_mac.mm
Labels: target/4-1-x, target/5-0-x

#17458 docs: clarify documentation for getLastCrashReport
  docs/api/crash-reporter.md
Labels: documentation :notebook:, target/4-1-x, target/5-0-x

#17497 fix: backport KDE icon size fix
  patches/common/chromium/.patches
  patches/common/chromium/fix_system_tray_icons_being_cropped_under_kde.patch
Labels: 4-1-x, new-pr 🌱

#17474 fix: close context menu before popup
  atom/browser/ui/win/notify_icon.cc
  spec/api-tray-spec.js
Labels: target/5-0-x

#17525 fix: correctly return properties on the netLog module
  lib/browser/api/net-log.js
Labels: target/4-1-x, target/5-0-x

#17404 feat: allow windows to be excluded from the windows menu
  atom/browser/api/atom_api_top_level_window.cc
  atom/browser/api/atom_api_top_level_window.h
  atom/browser/native_window.h
  atom/browser/native_window_mac.h
  atom/browser/native_window_mac.mm
  atom/browser/native_window_views.cc
  atom/browser/native_window_views.h
  docs/api/browser-window.md
Labels: semver/minor

#17547 fix: set default_id and cancel_id correctly on confirm dialogs
  atom/browser/atom_javascript_dialog_manager.cc
Labels: target/5-0-x

#17546 fix: use file path as key for safeDialogs on filesystem
  atom/browser/atom_javascript_dialog_manager.cc
Labels: target/5-0-x

#17577 fix: handle a race condition between preload scripts executing and navigations
  atom/browser/api/atom_api_web_contents.cc
Labels: target/3-1-x, target/4-1-x, target/5-0-x

#17565 fix: update patch to make Windows key work with global shortcuts
  patches/common/chromium/command-ismediakey.patch
Labels: in-flight/5-0-x

#17582 fix: add patch for framework file permissions
  patches/common/chromium/.patches
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/crashpad_http_status.patch
  patches/common/chromium/mac_fix_form_control_rendering_on_10_14_mojave.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/set_proper_permissions_for_package_s_framework_directory.patch
  patches/common/chromium/webview_cross_drag.patch
Labels: 4-1-x, new-pr 🌱

#17593 fix: ensure dots in content script patterns aren't used as wildcards
  lib/renderer/content-scripts-injector.ts
Labels: in-flight/5-0-x, new-pr 🌱

#17594 fix: ensure dots in content script patterns aren't used as wildcards
  lib/renderer/content-scripts-injector.js
Labels: new-pr 🌱, target/2-0-x, target/3-1-x, target/4-1-x

#17614 fix: make devtools extensions load correctly
  atom/browser/api/atom_api_web_contents.cc
  atom/renderer/atom_render_frame_observer.cc
  lib/browser/chrome-extension.js
  lib/renderer/chrome-api.ts
Labels: in-flight/5-0-x
