Repository electron/electron, pull requests merged in 2019-01, with the labels that each got.

#15938 chore: publish nightlies to electron-nightly
  script/publish-to-npm.js
Labels: target/3-0-x, target/3-1-x, target/4-0-x

#16180 chore: update deprecated LSGetApplicationForURL
  atom/common/platform_util_mac.mm
Labels: target/4-0-x

#16261 fix: error if a11y support changed before ready
  atom/browser/api/atom_api_app.cc
  atom/browser/api/atom_api_app.h
  docs/api/app.md
Labels: target/4-0-x

#16262 fix: don't register some shortcuts without accessibility
  atom/browser/api/atom_api_global_shortcut.cc
  atom/browser/api/atom_api_system_preferences.cc
  atom/browser/api/atom_api_system_preferences.h
  atom/browser/api/atom_api_system_preferences_mac.mm
  docs/api/global-shortcut.md
  docs/api/system-preferences.md
Labels: 4-0-x, backport

#16267 docs: Update reference to xcode 8.3.3
  docs/development/build-instructions-macos.md
Labels: target/3-0-x, target/3-1-x, target/4-0-x

#16279 chore: add additional logging during asset upload
  script/upload-to-github.js
Labels: target/4-0-x

#16273 chore: @electron/nightly => electron-nightly
  script/publish-to-npm.js
Labels: needs-manual-bp/3-0-x, needs-manual-bp/3-1-x, target/4-0-x

#16252 fix: security: improve IPC validation in guest-view-manager
  lib/browser/guest-view-manager.js
  lib/browser/rpc-server.js
Labels: target/4-0-x

#16309 fix: register accelerator if role has no registerAccelerator
  lib/browser/api/menu-item-roles.js
Labels: target/4-0-x

#16203 build: extract external binaries config
  DEPS
  script/external-binaries.json
  script/update-external-binaries.py
Labels: target/4-0-x

#16320 docs: instructions to get Notifications working on Win 10 Update added
  docs/tutorial/notifications.md
Labels: target/3-0-x, target/3-1-x, target/4-0-x

#16329 fix: properly determine if WebContents is offscreen in WebContentsDelegate
  atom/browser/common_web_contents_delegate.cc
Labels: bug :beetle:, component/dialog, platform/macOS, semver/patch, target/3-1-x, target/4-0-x

#16353 chore: fix tag cleanup
  script/release-artifact-cleanup.js
Labels: target/3-0-x, target/3-1-x, target/4-0-x

#16350 fix: beep on Ubuntu
  atom/common/platform_util_linux.cc
Labels: target/4-0-x

#16347 test: allow retries for flaky mas loginitem specs
  spec/api-app-spec.js
Labels: target/3-1-x, target/4-0-x

#15711 build: fix the build with enable_run_as_node disabled
  atom/app/atom_main.cc
  atom/common/api/features.cc
  spec/asar-spec.js
  spec/modules-spec.js
  spec/node-spec.js
Labels: target/4-0-x

#16352 fix: emit IPC event in correct context if isolation and sandbox enabled
  atom/renderer/atom_sandboxed_renderer_client.cc
  spec/api-ipc-renderer-spec.js
  spec/fixtures/module/preload-inject-ipc.js
  spec/fixtures/module/preload-ipc-ping-pong.js
  spec/fixtures/pages/ping-pong.html
Labels: target/4-0-x

#16276 fix: don't register some shortcuts without accessibility
  atom/browser/api/atom_api_global_shortcut.cc
  atom/browser/api/atom_api_system_preferences.h
  atom/browser/api/atom_api_system_preferences_mac.mm
  atom/common/platform_util.h
  atom/common/platform_util_mac.mm
  docs/api/global-shortcut.md
Labels: target/3-0-x

#16395 chore: backport cleanup changes to 3-1-x
  script/release-artifact-cleanup.js
Labels: target/3-0-x

#16433 fix: correctly handle IPC for promise-based methods
  lib/browser/guest-view-manager.js
  lib/common/web-view-methods.js
  lib/renderer/web-view/web-view-impl.js
Labels: target/3-1-x, target/4-0-x

#16451 chore: always try to nuke tags
  script/release-artifact-cleanup.js
Labels: target/3-1-x, target/4-0-x

#16472 fix: prevent double-destroy of window
  atom/browser/api/atom_api_browser_window.cc
Labels: target/4-0-x

#16480 fix: takeHeapSnapshot() using public IPC channel for internal implementation
  atom/renderer/atom_render_frame_observer.cc
  lib/browser/api/web-contents.js
Labels: target/4-0-x

#16485 docs: fix web-request.md listener signatures in electron.d.ts
  docs/api/web-request.md
Labels: target/3-1-x, target/4-0-x

#16369 build: fail a build if "npm install" fails
  DEPS
  script/lib/npm.py
Labels: target/4-0-x

#16493 build: fix individual asset downloading in release script
  package-lock.json
  package.json
  script/release.js
Labels: target/5-0-x

#16448 fix: correctly destroy spellcheck client
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
Labels: target/3-1-x, target/4-0-x

#16500 fix: check process.isMainFrame in sandboxed_renderer/init.js
  lib/renderer/web-view/web-view-init.js
  lib/sandboxed_renderer/init.js
Labels: target/3-1-x, target/4-0-x, target/5-0-x

#16506 docs: cancel is optional in OnHeadersReceivedResponse
  docs/api/web-request.md
Labels: target/4-0-x, target/5-0-x

#16524 fix: correctly destroy spellcheck client
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
Labels: 4-0-x, backport

#16532 fix: registerStreamProtocol callback with large chunks
  atom/browser/net/url_request_stream_job.cc
  spec/api-protocol-spec.js
Labels: in-flight/4-0-x, target/5-0-x

#16540 fix: registerStreamProtocol callback with large chunks (backport: 4-0-x)
  atom/browser/net/url_request_stream_job.cc
  spec/api-protocol-spec.js
Labels: 4-0-x, backport

#16454 fix: expose ripemd160 hash from boringssl
  patches/common/boringssl/.patches
  patches/common/boringssl/expose_ripemd160.patch
  patches/common/chromium/boringssl_build_gn.patch
  spec/node-spec.js
Labels: target/4-0-x, target/5-0-x

#16538 fix: execute session preload scripts in sandboxed renderers
  lib/browser/rpc-server.js
  lib/sandboxed_renderer/init.js
  spec/api-browser-window-spec.js
  spec/fixtures/module/get-global-preload.js
  spec/fixtures/module/set-global-preload-3.js
Labels: target/5-0-x

#16416 chore: Move webFrame scheme privilege methods to main process
  atom/app/atom_content_client.cc
  atom/browser/api/atom_api_protocol.cc
  atom/browser/api/atom_api_protocol.h
  atom/browser/atom_browser_client.cc
  atom/browser/atom_browser_client.h
  atom/common/options_switches.cc
  atom/common/options_switches.h
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
  atom/renderer/renderer_client_base.cc
  docs/api/breaking-changes.md
  docs/api/protocol.md
  docs/api/structures/custom-scheme.md
  docs/api/web-frame.md
  spec/api-protocol-spec.js
  spec/api-session-spec.js
  spec/api-web-frame-spec.js
  spec/package-lock.json
  spec/static/main.js
Labels: target/5-0-x

#15892 feat: add registerAccelerator flag to allow menu items to optionally skip accelerator registration (backport: 3-1-x)
  atom/browser/api/atom_api_menu.cc
  atom/browser/api/atom_api_menu.h
  atom/browser/ui/accelerator_util.cc
  atom/browser/ui/atom_menu_model.cc
  atom/browser/ui/atom_menu_model.h
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.js
  lib/browser/api/menu-item.js
  lib/browser/api/menu.js
Labels: target/3-0-x

#16526 fix: correctly destroy spellcheck client
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
Labels: 3-1-x, backport

#16525 fix: correctly destroy spellcheck client
  atom/renderer/api/atom_api_web_frame.cc
  atom/renderer/api/atom_api_web_frame.h
Labels: 5-0-x, backport

#16565 fix: don't forward IPC filtering events to app for dev-tools and extensions
  lib/browser/api/web-contents.js
Labels: target/5-0-x

#16597 docs: remove nonexistent contentTracing methods
  docs/api/content-tracing.md
  docs/api/promisification.md
Labels: target/5-0-x

#16517 fix: enable and update osr
  atom/browser/osr/osr_render_widget_host_view.cc
  atom/browser/osr/osr_render_widget_host_view.h
  atom/browser/osr/osr_render_widget_host_view_mac.mm
  atom/browser/osr/osr_web_contents_view.cc
  atom/browser/osr/osr_web_contents_view.h
  buildflags/buildflags.gni
Labels: target/5-0-x

#16601 fix: update docs for protocol API
  atom/browser/api/atom_api_protocol.cc
  docs/api/protocol.md
  docs/api/structures/custom-scheme.md
  package-lock.json
  package.json
  spec/static/main.js
Labels: semver/major, target/5-0-x

#16628 fix: move open handling to web-contents.js
  lib/browser/api/browser-window.js
  lib/browser/api/web-contents.js
Labels: 3-1-x, target/3-0-x

#16612 fix: Use async save dialog for anchor download attribute
  atom/browser/atom_download_manager_delegate.cc
  atom/browser/atom_download_manager_delegate.h
Labels: bug :beetle:, target/4-0-x, target/5-0-x

#16584 feat: promisify contentTracing recording APIs
  atom/browser/api/atom_api_content_tracing.cc
  docs/api/content-tracing.md
  docs/api/promisification.md
  lib/browser/api/content-tracing.js
  spec/api-content-tracing-spec.js
Labels: target/5-0-x

#16630 fix: move open handling to web-contents.js
  lib/browser/api/browser-window.js
  lib/browser/api/web-contents.js
Labels: 2-0-x, backport

#16621 chore: fix 'browserView' typo
  lib/browser/api/web-contents.js
Labels: target/5-0-x

#16646 chore: Fix typo in AtomDownloadManagerDelegate::OnDownloadSaveDialogDone
  atom/browser/atom_download_manager_delegate.cc
Labels: target/5-0-x

#16623 fix: handle window.open() in web-contents.js
  lib/browser/api/browser-window.js
  lib/browser/api/web-contents.js
  spec/api-browser-view-spec.js
Labels: 4-0-x

#16610 ci: Run Windows Electron tests first to show those failures first
  appveyor.yml
  spec/api-app-spec.js
  spec/api-browser-view-spec.js
  spec/api-web-contents-spec.js
  spec/api-web-contents-view-spec.js
Labels: target/5-0-x

#16663 build: hack around GitHub upload API failure / flake
  script/upload-to-github.js
Labels: target/2-0-x, target/3-0-x, target/3-1-x, target/4-0-x, target/5-0-x
