Repository electron/electron, pull requests merged in 2020-10, with the labels that each got.

#25657 chore: cherry-pick 52dceba66599 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-52dceba66599.patch
Labels: 8-x-y, backport-check-skip

#25726 docs: rename launch-failure -> launch-failed to match C++ code
  docs/api/app.md
  docs/api/web-contents.md
Labels: new-pr 🌱, target/10-x-y, target/11-x-y, target/9-x-y

#25702 fix: crash when application launched from UNUserNotificationCenter notification
  shell/browser/mac/electron_application_delegate.mm
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25744 fix: gdi printing in silent printing mode
  patches/chromium/printing.patch
Labels: 11-x-y, backport

#25740 fix: gdi printing in silent printing mode
  patches/chromium/printing.patch
Labels: 10-x-y, backport

#25748 chore: fix nmv for Electron v11
  build/args/all.gn
Labels: fast-track 🚅

#25749 chore: fix nmv for Electron v12
  build/args/all.gn
Labels: fast-track 🚅

#25580 feat: add webContents.forcefullyCrashRenderer() to forcefully terminate a renderer process
  chromium_src/BUILD.gn
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec-main/api-web-contents-spec.ts
Labels: backport/approved ✅, target/11-x-y

#25656 chore: cherry-pick 52dceba66599 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-52dceba66599.patch
Labels: 9-x-y, backport-check-skip

#25765 fix: no more need to hijack process.stdout on Win32
  BUILD.gn
  lib/browser/init.ts
  patches/node/.patches
  patches/node/call_process_log_from_fallback_stream_on_windows.patch
  shell/app/node_main.cc
  shell/common/api/electron_bindings.cc
  shell/common/api/electron_bindings.h
  spec-main/node-spec.ts
  spec/fixtures/module/run-as-node.js
  spec/node-spec.js
Labels: new-pr 🌱

#25768 docs: trim trailing whitespace
  docs/tutorial/boilerplates-and-clis.md
Labels: new-pr 🌱

#25772 chore: use no-op ShouldAbortOnUncaughtException cb
  shell/common/node_bindings.cc
Labels: target/10-x-y, target/11-x-y

#25799 test: improve app 'session-created' event spec
  spec-main/api-session-spec.ts
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25080 fix: window.open doesn't work correctly in child window
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec-main/api-web-contents-spec.ts
Labels: target/11-x-y

#25724 fix: gdi printing in silent printing mode
  patches/chromium/printing.patch
Labels: 9-x-y, backport

#24945 feat: add ability to close connections for a session
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: api-review/approved ✅

#25777 fix: wasm code generation in the renderer
  patches/chromium/.patches
  patches/chromium/chore_expose_v8_initialization_isolate_callbacks.patch
  patches/node/.patches
  patches/node/chore_expose_v8_initialization_isolate_callbacks.patch
  shell/common/node_bindings.cc
Labels: target/10-x-y, target/11-x-y

#25798 fix: session argument of app 'session-created' event
  lib/browser/api/app.ts
  shell/browser/api/electron_api_session.cc
Labels: backport-check-skip

#25795 feat: add support for preventing the system context menu
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/browser/native_window_views_win.cc
Labels: backport/approved ✅, target/11-x-y

#25794 docs: update link to `did-fail-load` events
  docs/api/web-contents.md
Labels: documentation :notebook:

#25645 chore: cherry-pick 7e5c7b5964 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-7e5c7b5964.patch
Labels: 9-x-y, backport-check-skip

#25646 chore: cherry-pick 7e5c7b5964 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-7e5c7b5964.patch
Labels: 8-x-y, backport-check-skip

#25637 chore: cherry-pick abc6ab85e704 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-abc6ab85e704.patch
Labels: 8-x-y, backport-check-skip

#25815 test: improve app 'session-created' event spec
  spec-main/api-session-spec.ts
Labels: 9-x-y, backport

#25820 fix: notifications successfully never timeout with included flag
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25851 chore: update chore_expose_v8_initialization_isolate_callbacks.patch
  patches/node/chore_expose_v8_initialization_isolate_callbacks.patch
Labels: fast-track 🚅

#25464 feat: add webFrameMain API to the main process
  docs/README.md
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/module-list.ts
  lib/browser/api/module-names.ts
  lib/browser/api/web-frame-main.ts
  package.json
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_converters/frame_converter.cc
  shell/common/gin_converters/frame_converter.h
  shell/common/node_bindings.cc
  spec-main/api-web-frame-main-spec.ts
  yarn.lock
Labels: api-review/approved ✅

#25641 chore: cherry-pick adc731d678c4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-adc731d678c4.patch
Labels: 9-x-y, backport-check-skip

#25638 chore: cherry-pick abc6ab85e704 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-abc6ab85e704.patch
Labels: 9-x-y, backport-check-skip

#25862 fix: notifications successfully never timeout with included flag
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: 9-x-y, backport

#25856 chore: cherry-pick 8629cd7f8af3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-8629cd7f8af3.patch
Labels: 10-x-y, backport-check-skip

#25853 chore: cherry-pick ffed0925f2 from WebRTC.
  patches/config.json
  patches/usrsctp/.patches
  patches/usrsctp/fix_a_use-after-free_bug_for_the_userland_stack.patch
Labels: 10-x-y, backport-check-skip

#25832 fix: NativeImage.getScaleFactors returns correct scales
  shell/common/api/electron_api_native_image.cc
  spec-main/api-remote-spec.ts
  spec/api-native-image-spec.js
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25864 fix: update squirrel.mac to handle bug in Big Sur
  DEPS
  patches/squirrel.mac/build_add_gn_config.patch
  spec-main/api-autoupdater-darwin-spec.ts
Labels: target/11-x-y

#25896 chore: cherry-pick b7ccc3f6cc from chromium
  patches/chromium/.patches
  patches/chromium/avoid_use-after-free.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#25869 fix: uv loop polling when render process reuse enabled
  shell/renderer/electron_renderer_client.cc
  spec-main/api-browser-window-spec.ts
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25911 chore: cherry-pick f06a6cb3a38e from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f06a6cb3a38e.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#25923 fix: uv loop polling when render process reuse enabled
  shell/renderer/electron_renderer_client.cc
  spec-main/api-browser-window-spec.ts
Labels: 10-x-y, backport

#25760 docs: Added revised version of the quick start guide
  docs/README.md
  docs/api/synopsis.md
  docs/api/touch-bar-button.md
  docs/api/touch-bar-color-picker.md
  docs/api/touch-bar-group.md
  docs/api/touch-bar-label.md
  docs/api/touch-bar-other-items-proxy.md
  docs/api/touch-bar-popover.md
  docs/api/touch-bar-scrubber.md
  docs/api/touch-bar-segmented-control.md
  docs/api/touch-bar-slider.md
  docs/api/touch-bar-spacer.md
  docs/api/touch-bar.md
  docs/images/simplest-electron-app.png
  docs/tutorial/application-architecture.md
  docs/tutorial/first-app.md
  docs/tutorial/quick-start.md
  docs/tutorial/windows-arm.md
Labels: documentation :notebook:

#25927 build: fix 11-x-y compiler errors
  appveyor.yml
  patches/v8/.patches
  patches/v8/fix_correct_calling_convention_for_windows_on_arm.patch
Labels: fast-track 🚅

#25926 fix: notifications successfully never timeout with included flag
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: 10-x-y, backport

#25924 fix: uv loop polling when render process reuse enabled
  shell/renderer/electron_renderer_client.cc
  spec-main/api-browser-window-spec.ts
Labels: 9-x-y, backport

#25922 fix: uv loop polling when render process reuse enabled
  shell/renderer/electron_renderer_client.cc
  spec-main/api-browser-window-spec.ts
Labels: 11-x-y, backport

#25897 chore: cherry-pick b7ccc3f6cc from chromium
  patches/chromium/.patches
  patches/chromium/avoid_use-after-free.patch
Labels: 8-x-y, backport-check-skip

#25893 chore: cherry-pick b7ccc3f6cc from chromium
  patches/chromium/.patches
  patches/chromium/avoid_use-after-free.patch
Labels: 10-x-y, backport-check-skip

#25859 chore: cherry-pick 3b5f65c0aeca from chromium
  patches/chromium/.patches
  patches/chromium/reland_add_more_checks_for_chrome_debugger_extensions.patch
Labels: 9-x-y, backport-check-skip

#25902 fix: notifications successfully never timeout with included flag
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: 11-x-y, backport, target/10-x-y

#25929 docs: rename launch-failure -> launch-failed to match C++ code
  docs/api/app.md
  docs/api/web-contents.md
Labels: 10-x-y, backport

#25930 docs: rename launch-failure -> launch-failed to match C++ code
  docs/api/app.md
  docs/api/web-contents.md
Labels: 9-x-y, backport

#25891 fix: pass require.resolve paths option to wrapped method
  lib/common/reset-search-paths.ts
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25921 docs: move breaking-changes-ns.md contents to breaking-changes.md
  docs/breaking-changes-ns.md
  docs/breaking-changes.md
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25932 fix: ensure ready-to-show event is fired
  lib/browser/api/web-contents.js
  package.json
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/common/api/api.mojom
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_render_frame_observer.h
Labels: 10-x-y, backport

#25860 chore: cherry-pick 3b5f65c0aeca from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3b5f65c0aeca.patch
Labels: 8-x-y, backport-check-skip

#25855 chore: cherry-pick ffed0925f2 from WebRTC.
  patches/usrsctp/.patches
  patches/usrsctp/fix_a_use-after-free_bug_for_the_userland_stack.patch
Labels: 8-x-y, backport-check-skip

#25854 chore: cherry-pick ffed0925f2 from WebRTC.
  patches/config.json
  patches/usrsctp/.patches
  patches/usrsctp/fix_a_use-after-free_bug_for_the_userland_stack.patch
Labels: 9-x-y, backport-check-skip

#25857 chore: cherry-pick 8629cd7f8af3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-8629cd7f8af3.patch
Labels: 9-x-y, backport-check-skip

#25852 chore: cherry-pick b1b3ccbd57 from chromium.
  patches/chromium/.patches
  patches/chromium/don_t_create_providers_if_context_is_lost.patch
Labels: 10-x-y, backport-check-skip

#25931 fix: order menu items before filtering excess separators
  lib/browser/api/menu-utils.js
  lib/browser/api/menu.js
  spec-main/api-menu-spec.ts
Labels: 10-x-y, backport

#25949 docs: fix protocol.registerFileProtocol() usage in session.md
  docs/api/session.md
Labels: new-pr 🌱

#25940 fix: maximized frameless window bleeding to other monitors
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Labels: target/10-x-y, target/11-x-y, target/8-x-y, target/9-x-y

#25939 docs: revised the drag and drop feature page
  docs/images/drag-and-drop.gif
  docs/tutorial/native-file-drag-drop.md
Labels: documentation :notebook:

#25991 chore: fix visibility tests on windows
  appveyor.yml
  azure-pipelines-woa.yml
Labels: 11-x-y, backport-check-skip, new-pr 🌱

#25992 chore: update chore_expose_v8_initialization_isolate_callbacks.patch
  patches/chromium/chore_expose_v8_initialization_isolate_callbacks.patch
Labels: fast-track 🚅

#26001 chore: fix visibility tests for woa
  azure-pipelines-woa.yml
Labels: fast-track 🚅

#26004 fix: disable PDF annotation button
  shell/browser/extensions/api/resources_private/resources_private_api.cc
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#25959 fix: Save As PDF from PDF Preview
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25060 feat: Expose renderer spellcheck API
  docs/api/web-frame.md
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_renderer_client.h
  spec-main/spellchecker-spec.ts
Labels: api-review/approved ✅

#25956 fix: correct null pointer checks in autoresizing browser views
  shell/browser/native_browser_view_views.cc
Labels: 11-x-y, backport

#25951 fix: correct null pointer checks in autoresizing browser views
  shell/browser/native_browser_view_views.cc
Labels: merged/11-x-y, target/10-x-y, target/9-x-y

#25973 chore: tweak branch detection in release notes.
  script/release/notes/notes.js
Labels: target/11-x-y

#26035 fix: pass module resolution paths to wrapped function
  lib/common/reset-search-paths.ts
Labels: 9-x-y, backport

#26011 build: fix invocation of cpplint on Windows
  script/lint.js
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#26044 docs: Update native file drag and drop
  docs/tutorial/native-file-drag-drop.md
Labels: new-pr 🌱

#25989 fix: crash when printing
  patches/chromium/printing.patch
Labels: target/11-x-y

#25941 docs: revised the recent documents feature page
  docs/images/recent-documents.png
  docs/tutorial/recent-documents.md
Labels: documentation :notebook:

#25958 perf: remove GC timer that fired once per minute.
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25985 docs: revised the macos dock menu feature page
  docs/images/macos-dock-menu.png
  docs/tutorial/macos-dock.md
Labels: documentation :notebook:

#25629 feat: add support for share menu on macOS
  docs/api/menu-item.md
  docs/api/share-menu.md
  docs/api/structures/sharing-item.md
  filenames.auto.gni
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/menu.ts
  lib/browser/api/module-list.ts
  lib/browser/api/module-names.ts
  lib/browser/api/share-menu.ts
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/ui/cocoa/electron_menu_controller.h
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/browser/ui/electron_menu_model.cc
  shell/browser/ui/electron_menu_model.h
  shell/common/gin_helper/dictionary.h
  typings/internal-electron.d.ts
Labels: api-review/approved ✅

#25974 chore: bump @electron/docs-parser to get fix
  package.json
  yarn.lock
Labels: backport-check-skip

#25901 docs: revised Notifications feature page
  docs/images/message-notification-renderer.png
  docs/images/notification-main.png
  docs/images/notification-renderer.png
  docs/tutorial/notifications.md
Labels: documentation :notebook:

#26064 fix: crash in printing on Windows
  patches/chromium/.patches
  patches/chromium/fix_use_electron_generated_resources.patch
  patches/chromium/use_electron_resources_in_icon_reader_service.patch
  patches/chromium/use_electron_resources_in_pdf_util.patch
Labels: 10-x-y, backport

#26066 fix: crash in printing on Windows
  patches/chromium/.patches
  patches/chromium/fix_use_electron_generated_resources.patch
  patches/chromium/use_electron_resources_in_pdf_util.patch
Labels: 9-x-y, backport

#26063 fix: wasm code generation in the renderer
  patches/chromium/.patches
  patches/chromium/chore_expose_v8_initialization_isolate_callbacks.patch
  patches/node/.patches
  patches/node/chore_expose_v8_initialization_isolate_callbacks.patch
  shell/common/node_bindings.cc
Labels: 10-x-y, backport

#26070 chore: cherry-pick b977dff8 from freetype
  patches/config.json
  patches/freetype/.patches
  patches/freetype/test_early_to_prevent_overflow.patch
Labels: 10-x-y, backport, backport-check-skip

#26067 fix: Save As PDF from PDF Preview
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
Labels: 9-x-y, backport

#21004 feat: add net.online / net.isOnline()
  docs/api/net.md
  lib/browser/api/net.ts
  shell/browser/api/electron_api_net.cc
  spec-main/api-net-spec.ts
  typings/internal-ambient.d.ts
Labels: api-review/approved ✅

#26017 docs: revised the online-offline event detection feature page
  docs/images/online-event-detection.png
  docs/tutorial/online-offline-events.md
Labels: documentation :notebook:

#25818 feat: add disabledCipherSuites option to setSSLConfig
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  spec-main/api-session-spec.ts
Labels: api-review/approved ✅

#26069 chore: cherry-pick b977dff8 from freetype
  patches/config.json
  patches/freetype/.patches
  patches/freetype/test_early_to_prevent_overflow.patch
Labels: 9-x-y, backport-check-skip

#25874 feat: add webPreferences.enablePreferredSizeMode
  docs/api/browser-window.md
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/web_contents_preferences.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: api-review/approved ✅

#26084 revert: reply notifs sometimes destroyed too early
  shell/browser/notifications/mac/notification_center_delegate.mm
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: 8-x-y, backport

#26083 revert: reply notifs sometimes destroyed too early
  shell/browser/notifications/mac/notification_center_delegate.mm
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: 9-x-y, backport

#26008 docs: revised the web embeds feature page
  docs/tutorial/web-embeds.md
Labels: documentation :notebook:

#26078 fix: release NSAlert properly
  shell/browser/ui/message_box_mac.mm
Labels: new-pr 🌱, target/10-x-y, target/11-x-y, target/8-x-y, target/9-x-y

#26048 docs: add discord link to docs community page
  docs/tutorial/support.md
Labels: target/10-x-y

#26095 fix: return early on promise rejection
  shell/browser/api/electron_api_session.cc
Labels: new-pr 🌱, target/10-x-y, target/11-x-y, target/9-x-y

#26036 chore: backport fix for ARIA TreeGrid rows not being announced by VoiceOver
  patches/chromium/.patches
  patches/chromium/cherry-pick-2f5b8357dca2.patch
Labels: 11-x-y, backport-check-skip

#26109 chore: prefer empty() check for readability
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/browser_win.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/native_window_views_win.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/message_box_win.cc
  shell/common/gin_converters/guid_converter.h
  shell/renderer/api/electron_api_context_bridge.cc
Labels: new-pr 🌱, target/10-x-y, target/11-x-y, target/9-x-y

#26068 chore: cherry-pick b977dff8 from freetype
  patches/config.json
  patches/freetype/.patches
  patches/freetype/test_early_to_prevent_overflow.patch
Labels: 8-x-y, backport-check-skip

#26003 docs: revised the application progress bar feature page
  docs/images/dock-progress-bar.png
  docs/images/linux-progress-bar.png
  docs/images/macos-progress-bar.png
  docs/images/mission-control-progress-bar.png
  docs/tutorial/progress-bar.md
Labels: documentation :notebook:

#26096 fix: setSimpleFullScreen shows traffic lights in frameless window
  shell/browser/native_window_mac.mm
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#26119 fix: re-enable the spellchecker when new language list set
  shell/browser/api/electron_api_session.cc
  spec-main/spec-helpers.ts
  spec-main/spellchecker-spec.ts
Labels: fast-track 🚅, target/11-x-y

#26129 fix: re-enable the spellchecker when new language list set
  shell/browser/api/electron_api_session.cc
  spec-main/spec-helpers.ts
  spec-main/spellchecker-spec.ts
Labels: 11-x-y, backport

#26131 revert: "fix: reply notifs sometimes destroyed too early" (#25247)
  shell/browser/notifications/mac/notification_center_delegate.mm
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: 11-x-y, backport

#26140 fix: ensure ready-to-show event is fired
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  spec-main/api-browser-window-spec.ts
Labels: 8-x-y, backport

#26121 ci: cleanup up test app directories
  spec-main/api-crash-reporter-spec.ts
  spec-main/fixtures/api/ipc-main-listeners/package.json
  spec-main/fixtures/api/net-log/package.json
  spec-main/fixtures/apps/crash/package.json
  spec-main/fixtures/apps/remote-control/package.json
  spec-main/fixtures/auto-update/check/package.json
  spec-main/fixtures/auto-update/initial/package.json
  spec/fixtures/api/app-path/package.json
  spec/fixtures/api/command-line/package.json
  spec/fixtures/api/default-menu/package.json
  spec/fixtures/api/locale-check/package.json
  spec/fixtures/api/site-instance-overrides/package.json
  spec/fixtures/api/window-all-closed/package.json
  spec/fixtures/snapshot-items-available/package.json
Labels: 9-x-y, backport

#26081 build: move to ACR for docker image storage
  .circleci/config.yml
Labels: 8-x-y, backport

#26062 fix: crash in printing on Windows
  patches/chromium/.patches
  patches/chromium/fix_use_electron_generated_resources.patch
  patches/chromium/use_electron_resources_in_icon_reader_service.patch
  patches/chromium/use_electron_resources_in_pdf_util.patch
Labels: 11-x-y, backport

#26018 docs: revised the represented file feature page
  docs/images/represented-file.png
  docs/tutorial/represented-file.md
Labels: documentation :notebook:

#26141 fix: Close protocol response streams when aborted
  shell/browser/net/node_stream_loader.cc
  spec-main/api-protocol-spec.ts
  spec-main/fixtures/pages/jquery.html
Labels: 8-x-y, backport

#26159 chore: prefer empty() check for readability
  shell/browser/api/electron_api_top_level_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/native_window_views_win.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/message_box_win.cc
  shell/common/gin_converters/guid_converter.h
  shell/renderer/api/electron_api_context_bridge.cc
Labels: 10-x-y, backport, target/9-x-y

#26157 chore: prefer empty() check for readability
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/browser_win.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/native_window_views_win.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/message_box_win.cc
  shell/common/gin_converters/guid_converter.h
  shell/renderer/api/electron_api_context_bridge.cc
Labels: 11-x-y, backport

#26156 chore: bump @electron/docs-parser version
  package.json
  yarn.lock
Labels: 10-x-y, backport

#26155 chore: bump @electron/docs-parser version
  package.json
  yarn.lock
Labels: 11-x-y, backport

#26118 docs: revised linux desktop actions page
  docs/tutorial/linux-desktop-actions.md
Labels: documentation :notebook:

#26171 docs: fix app 'ready' event arguments
  docs/api/app.md
Labels: fast-track 🚅, target/10-x-y, target/11-x-y, target/9-x-y

#25836 fix: delay emitting powerMonitor events on windows
  shell/browser/api/electron_api_power_monitor.h
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: target/10-x-y, target/11-x-y

#26120 docs: revised windows taskbar page
  docs/tutorial/windows-taskbar.md
Labels: documentation :notebook:

#24937 feat: Added support for all proxy modes
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec-main/api-session-spec.ts
Labels: api-review/approved ✅

#26182 chore: change some for loops to range-based
  chromium_src/chrome/browser/process_singleton_posix.cc
  chromium_src/chrome/browser/ui/views/frame/global_menu_bar_registrar_x11.cc
  shell/browser/api/electron_api_app.cc
  shell/common/api/electron_api_v8_util.cc
  shell/common/api/electron_bindings.cc
Labels: new-pr 🌱, target/10-x-y, target/11-x-y, target/9-x-y

#26165 refactor: Chromium code style for enum classes
  shell/app/electron_content_client.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_contents_mac.mm
  shell/browser/api/process_metric.cc
  shell/browser/api/process_metric.h
  shell/browser/browser.h
  shell/browser/browser_win.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/net/proxying_websocket.cc
  shell/browser/net/proxying_websocket.h
  shell/browser/ui/cocoa/electron_bundle_mover.h
  shell/browser/ui/cocoa/electron_bundle_mover.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  shell/browser/ui/tray_icon.h
  shell/browser/ui/win/jump_list.cc
  shell/browser/ui/win/jump_list.h
  shell/browser/ui/win/notify_icon.cc
  shell/browser/web_contents_zoom_controller.cc
  shell/browser/web_contents_zoom_controller.h
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: new-pr 🌱

#26176 chore: tidy up usage of PendingRemote
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.cc
Labels: new-pr 🌱

#25030 fix: transparently package bundles as zip archives
  BUILD.gn
  filenames.gni
  shell/browser/file_select_helper.cc
  shell/browser/file_select_helper.h
  shell/browser/file_select_helper_mac.mm
  shell/browser/web_dialog_helper.cc
Labels: target/10-x-y, target/11-x-y

#25999 docs: revised the keyboard shortcuts feature page
  docs/images/local-shortcut.png
  docs/tutorial/keyboard-shortcuts.md
Labels: documentation :notebook:

#26185 fix: set app locale after user's script is loaded
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_delegate.h
  shell/browser/electron_browser_main_parts.cc
  spec-main/chromium-spec.ts
  spec/fixtures/api/locale-check/main.js
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#26122 ci: cleanup up test app directories
  spec-main/fixtures/api/net-log/package.json
  spec/fixtures/api/app-path/package.json
  spec/fixtures/api/command-line/package.json
  spec/fixtures/api/default-menu/package.json
  spec/fixtures/api/ipc-main-listeners/package.json
  spec/fixtures/api/locale-check/package.json
  spec/fixtures/api/site-instance-overrides/package.json
  spec/fixtures/api/window-all-closed/package.json
  spec/fixtures/auto-update/check/package.json
  spec/fixtures/auto-update/initial/package.json
  spec/fixtures/snapshot-items-available/package.json
Labels: 8-x-y, backport

#26230 perf: improve heap snapshot performance
  patches/v8/.patches
  patches/v8/perf_make_getpositioninfoslow_faster.patch
Labels: 11-x-y, backport-check-skip

#26229 perf: improve heap snapshot performance
  patches/v8/.patches
  patches/v8/perf_make_getpositioninfoslow_faster.patch
Labels: 10-x-y, backport-check-skip

#26214 chore: cherry-pick 9591642a0896 from pdfium
  patches/pdfium/.patches
  patches/pdfium/cherry-pick-9591642a0896.patch
Labels: 8-x-y, backport-check-skip

#26213 chore: cherry-pick 9591642a0896 from pdfium
  patches/pdfium/.patches
  patches/pdfium/cherry-pick-9591642a0896.patch
Labels: 9-x-y, backport-check-skip

#26228 perf: improve heap snapshot performance
  patches/v8/.patches
  patches/v8/perf_make_getpositioninfoslow_faster.patch
Labels: 9-x-y, backport-check-skip

#26196 chore: cherry-pick 88f263f401b4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-88f263f401b4.patch
Labels: 10-x-y, backport-check-skip

#25373 feat: honor `nativeTheme.themeSource = 'dark'` before creating BrowserWindow on Windows
  BUILD.gn
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/win/dark_mode.cc
  shell/browser/win/dark_mode.h
  shell/common/api/features.cc
  typings/internal-ambient.d.ts
Labels: component/native-theme, platform/windows, semver/minor, target/10-x-y, target/11-x-y

#26191 chore: cherry-pick 1ed869ad4bb3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1ed869ad4bb3.patch
Labels: 9-x-y, backport-check-skip

#26208 chore: cherry-pick 6a4cd97d6691 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-6a4cd97d6691.patch
Labels: 8-x-y, backport-check-skip

#26198 chore: cherry-pick 88f263f401b4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-88f263f401b4.patch
Labels: 8-x-y, backport-check-skip

#26199 chore: cherry-pick 6aa1e71fbd09 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-6aa1e71fbd09.patch
Labels: 10-x-y, backport-check-skip

#26212 chore: cherry-pick 9591642a0896 from pdfium
  patches/config.json
  patches/pdfium/.patches
  patches/pdfium/cherry-pick-9591642a0896.patch
Labels: 10-x-y, backport-check-skip

#26203 chore: cherry-pick 30261f9de11e from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-30261f9de11e.patch
Labels: 10-x-y, backport-check-skip

#26194 chore: cherry-pick 229fdaf8fc05 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-229fdaf8fc05.patch
Labels: 9-x-y, backport-check-skip

#26200 chore: cherry-pick 6aa1e71fbd09 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-6aa1e71fbd09.patch
Labels: 9-x-y, backport-check-skip

#26201 chore: cherry-pick 6aa1e71fbd09 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-6aa1e71fbd09.patch
Labels: 8-x-y, backport-check-skip

#26195 chore: cherry-pick 229fdaf8fc05 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-229fdaf8fc05.patch
Labels: 8-x-y, backport-check-skip

#26232 build: only check patch diffs in testing builds
  .circleci/config.yml
  patches/chromium/rename_the_v8_context_snapshot_on_arm64_macos_builds.patch
Labels: fast-track 🚅, target/10-x-y, target/11-x-y, target/9-x-y

#26197 chore: cherry-pick 88f263f401b4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-88f263f401b4.patch
Labels: 9-x-y, backport-check-skip

#26207 chore: cherry-pick 6a4cd97d6691 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-6a4cd97d6691.patch
Labels: 9-x-y, backport-check-skip

#26206 chore: cherry-pick 6a4cd97d6691 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-6a4cd97d6691.patch
Labels: 10-x-y, backport-check-skip

#26190 chore: cherry-pick 1ed869ad4bb3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1ed869ad4bb3.patch
Labels: 10-x-y, backport-check-skip

#26192 chore: cherry-pick 1ed869ad4bb3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1ed869ad4bb3.patch
Labels: 8-x-y, backport-check-skip

#26193 chore: cherry-pick 229fdaf8fc05 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-229fdaf8fc05.patch
Labels: 10-x-y, backport-check-skip
