Repository electron/electron, pull requests merged in 2020-02, with the labels that each got.

#21997 fix: bind spellchecker receivers correctly in the renderer
  filenames.gni
  shell/renderer/browser_exposed_renderer_interfaces.cc
  shell/renderer/browser_exposed_renderer_interfaces.h
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
Labels: target/8-x-y

#21994 ci: fix ELECTRON_OUT_DIR
  .circleci/config.yml
Labels: target/7-1-x, target/8-x-y

#22011 fix: default printer if none is provided
  patches/chromium/printing.patch
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
Labels: 8-x-y, backport

#22013 chore: wrap cb with default invocation
  shell/browser/printing/print_preview_message_handler.cc
Labels: target/8-x-y

#22019 ci: fix ELECTRON_OUT_DIR
  .circleci/config.yml
Labels: 8-x-y, backport

#22020 ci: fix ELECTRON_OUT_DIR
  .circleci/config.yml
Labels: 7-1-x, backport

#22035 fix: crash on boot with --log-net-log
  shell/browser/electron_browser_context.cc
Labels: new-pr 🌱

#22041 fix: check WebContents in OnGetDefaultPrinter
  shell/browser/api/electron_api_web_contents.cc
Labels: new-pr 🌱

#22044 fix: delay deletion of Wrappable objects
  shell/common/gin_helper/wrappable.cc
Labels: new-pr 🌱

#22036 chore: wrap cb with default invocation
  shell/browser/printing/print_preview_message_handler.cc
Labels: 8-x-y, backport

#22060 chore: print more logging for failed tests
  spec-main/api-menu-spec.ts
  spec-main/api-web-contents-view-spec.ts
Labels: new-pr 🌱

#22034 docs: clarify requirements for GOOGLE_API_KEY
  docs/api/environment-variables.md
Labels: documentation :notebook:, target/9-x-y

#22070 build: copy chromedriver.zip to proper directory for release
  .circleci/config.yml
Labels: fast-track 🚅, target/9-x-y

#22016 fix: add Chromium patch to fix RTL window buttons
  patches/chromium/.patches
  patches/chromium/fix_use_native_window_button_positions_when_macos_locale_is_rtl.patch
Labels: semver/major

#21110 feat: enable passing Node.js cli flags
  docs/api/command-line-switches.md
  docs/api/environment-variables.md
  patches/node/.patches
  patches/node/feat_enable_passing_cli_flags.patch
  script/node-disabled-tests.json
  shell/app/node_main.cc
  shell/browser/node_debugger.cc
  shell/common/node_bindings.cc
  spec-main/node-spec.ts
Labels: wip ⚒

#21914 test: get native unit tests running
  script/spec-runner.js
Labels: target/9-x-y

#22075 ci: fix build failure on doc only changes
  .circleci/config.yml
  script/doc-only-change.js
Labels: target/8-x-y, target/9-x-y

#22074 build: copy chromedriver to correct location
  .circleci/config.yml
  script/strip-binaries.py
Labels: fast-track 🚅, target/9-x-y

#22093 chore: remove debugging log
  lib/renderer/api/remote.js
Labels: new-pr 🌱, target/9-x-y

#22094 build: preserve timestamps when stripping files
  .circleci/config.yml
  script/strip-binaries.py
Labels: fast-track 🚅, target/9-x-y

#22104 build: use newer version of xcode/macOS sdk
  .circleci/config.yml
Labels: fast-track 🚅, target/9-x-y

#22072 fix: flash plugin
  shell/browser/net/system_network_context_manager.cc
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22056 fix: use a WeakPtr so we do not UAF the store in FunctionLifetimeMonitor
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.h
  shell/renderer/api/electron_api_context_bridge.cc
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22039 feat: add session.removeWordFromSpellCheckerDictionary API
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: target/9-x-y

#22123 chore: Revert "notes: Adding Github CI to testing documentation"
  docs/tutorial/testing-on-headless-ci.md
Labels: documentation :notebook:, new-pr 🌱

#22125 fix: fire close event upon closing modal BrowserWindow in macOS
  atom/browser/native_window_mac.mm
Labels: 6-1-x, backport

#22101 feat: add session.listWordsFromSpellCheckerDictionary API
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: target/9-x-y

#22040 fix: make webRequest work with WebSocket
  docs/api/web-request.md
  filenames.gni
  shell/browser/api/electron_api_web_request.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/net/proxying_websocket.cc
  shell/browser/net/proxying_websocket.h
  shell/browser/net/web_request_api_interface.h
  spec-main/api-web-request-spec.ts
  spec-main/fixtures/api/webrequest.html
  spec-main/package.json
  spec-main/yarn.lock
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22121 refactor: use NSVisualEffectMaterial* constants directly
  shell/browser/native_window_mac.mm
Labels: target/9-x-y

#22142 build: fix spellchecker deps
  patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch
Labels: target/8-x-y, target/9-x-y

#22145 ci: strip mksnapshot binaries on Linux
  .circleci/config.yml
  BUILD.gn
Labels: target/7-1-x

#22152 fix: keep references to active menus created by api Menu
  atom/browser/api/atom_api_menu.cc
Labels: 6-1-x, backport

#22126 ci: Speed up release
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: target/9-x-y

#22150 fix: highlight buttons correctly when defaultId passed
  atom/browser/ui/message_box_mac.mm
Labels: 6-1-x, backport

#22124 fix: don't crash on invalid certs
  shell/browser/api/electron_api_app.cc
  spec-main/api-app-spec.ts
  spec-main/index.js
Labels: 8-x-y, backport

#22151 fix: keep references to active menus created by api Menu
  shell/browser/api/atom_api_menu.cc
Labels: 7-1-x, backport

#22134 fix: make webRequest work with WebSocket (8-x-y)
  docs/api/web-request.md
  filenames.gni
  shell/browser/api/electron_api_web_request_ns.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/net/proxying_websocket.cc
  shell/browser/net/proxying_websocket.h
  shell/browser/net/web_request_api_interface.h
  spec-main/api-web-request-spec.ts
  spec-main/fixtures/api/webrequest.html
  spec-main/package.json
  spec-main/yarn.lock
Labels: 8-x-y, backport

#22141 fix: make webRequest work with WebSocket (7-1-x)
  docs/api/web-request.md
  filenames.gni
  script/spec-runner.js
  shell/browser/api/atom_api_web_request_ns.h
  shell/browser/atom_browser_client.cc
  shell/browser/atom_browser_client.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/net/proxying_websocket.cc
  shell/browser/net/proxying_websocket.h
  shell/browser/net/web_request_api_interface.h
  spec-main/api-web-request-spec.ts
  spec-main/fixtures/api/webrequest.html
  spec-main/package.json
  spec-main/yarn.lock
Labels: 7-1-x, backport

#22132 fix: bug when repositioning traffic lights in RTL mode
  shell/browser/native_window_mac.mm
Labels: target/8-x-y, target/9-x-y

#22170 build: fix release script to work with sudowoodo
  script/release/ci-release-build.js
Labels: 9-x-y, fast-track 🚅

#22149 refactor: use NSVisualEffectMaterial* constants directly
  shell/browser/native_window_mac.mm
Labels: 8-x-y, backport

#22165 fix: no-arg console.log is undefined
  lib/browser/init.ts
Labels: new-pr 🌱, target/7-1-x, target/8-x-y, target/9-x-y

#22012 chore: default to sys printer and prevent bad default crash
  docs/api/web-contents.md
  patches/chromium/printing.patch
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
  spec-main/api-web-contents-spec.ts
Labels: 7-1-x, backport

#22153 fix: crash when restoring minimized hidden window
  atom/browser/native_window_views.h
  atom/browser/native_window_views_win.cc
  spec/api-browser-window-spec.js
Labels: 6-1-x, backport

#21794 feat: enable pdf viewer
  BUILD.gn
  buildflags/buildflags.gni
  chromium_src/BUILD.gn
  electron_paks.gni
  electron_resources.grd
  filenames.gni
  patches/chromium/.patches
  patches/chromium/hack_plugin_response_interceptor_to_point_to_electron.patch
  patches/chromium/use_electron_resources_in_pdf_util.patch
  shell/app/electron_content_client.cc
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/extensions/api/BUILD.gn
  shell/browser/extensions/api/resources_private/resources_private_api.cc
  shell/browser/extensions/api/resources_private/resources_private_api.h
  shell/browser/extensions/api/streams_private/streams_private_api.cc
  shell/browser/extensions/api/streams_private/streams_private_api.h
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/api/tabs/tabs_api.h
  shell/browser/extensions/electron_browser_context_keyed_service_factories.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/extensions/electron_component_extension_resource_manager.h
  shell/browser/extensions/electron_extension_loader.h
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/extensions/electron_extension_system.h
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/browser/extensions/electron_extensions_api_client.h
  shell/browser/extensions/electron_extensions_browser_api_provider.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/extensions/electron_extensions_browser_client.h
  shell/browser/plugins/plugin_utils.cc
  shell/browser/plugins/plugin_utils.h
  shell/browser/ui/inspectable_web_contents_impl.cc
  shell/common/electron_constants.cc
  shell/common/electron_constants.h
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/_permission_features.json
  shell/common/extensions/api/resources_private.idl
  shell/common/extensions/api/tabs.json
  shell/common/extensions/electron_extensions_api_provider.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
  spec-main/chromium-spec.ts
  spec-main/fixtures/cat.pdf
  spec-main/fixtures/pages/pdf-in-iframe.html
  spec/fixtures/pages/pdf-in-iframe.html
  spec/fixtures/pages/pdf-in-nested-iframe.html
Labels: in-flight/9-x-y

#22164 fix: crash on custom printing margins
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22131 feat: enable pdf viewer
  BUILD.gn
  buildflags/buildflags.gni
  chromium_src/BUILD.gn
  electron_paks.gni
  electron_resources.grd
  filenames.gni
  patches/chromium/.patches
  patches/chromium/hack_plugin_response_interceptor_to_point_to_electron.patch
  patches/chromium/use_electron_resources_in_pdf_util.patch
  shell/app/electron_content_client.cc
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/extensions/api/BUILD.gn
  shell/browser/extensions/api/resources_private/resources_private_api.cc
  shell/browser/extensions/api/resources_private/resources_private_api.h
  shell/browser/extensions/api/streams_private/streams_private_api.cc
  shell/browser/extensions/api/streams_private/streams_private_api.h
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/api/tabs/tabs_api.h
  shell/browser/extensions/electron_browser_context_keyed_service_factories.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/extensions/electron_component_extension_resource_manager.h
  shell/browser/extensions/electron_extension_loader.h
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/extensions/electron_extension_system.h
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/browser/extensions/electron_extensions_api_client.h
  shell/browser/extensions/electron_extensions_browser_api_provider.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/extensions/electron_extensions_browser_client.h
  shell/browser/plugins/plugin_utils.cc
  shell/browser/plugins/plugin_utils.h
  shell/browser/ui/inspectable_web_contents_impl.cc
  shell/common/electron_constants.cc
  shell/common/electron_constants.h
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/_permission_features.json
  shell/common/extensions/api/resources_private.idl
  shell/common/extensions/api/tabs.json
  shell/common/extensions/electron_extensions_api_provider.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
  spec-main/chromium-spec.ts
  spec-main/fixtures/cat.pdf
  spec-main/fixtures/pages/pdf-in-iframe.html
  spec/fixtures/pages/pdf-in-iframe.html
  spec/fixtures/pages/pdf-in-nested-iframe.html
Labels: 9-x-y, backport

#22186 fix: crash on custom printing margins
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
Labels: 8-x-y, backport

#22190 chore: update NMV for Electron 10
  build/args/all.gn
Labels: new-pr 🌱

#22189 chore: update NMV for Electron 9
  build/args/all.gn
Labels: fast-track 🚅

#22202 fix: add patch to route mouse event navigations through the WebContentDelegate
  patches/chromium/.patches
  patches/chromium/fix_route_mouse_event_navigations_through_the_web_contents_delegate.patch
Labels: new-pr 🌱, target/8-x-y, target/9-x-y

#22187 fix: crash on custom printing margins
  shell/browser/api/atom_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
Labels: 7-1-x, backport

#22191 fix: don't include breakpad_symbols dir in dsym.zip
  script/lib/util.py
Labels: target/6-1-x, target/7-1-x, target/8-x-y, target/9-x-y

#22203 ci: enable goma for all testing builds
  .circleci/config.yml
  appveyor.yml
  script/start-goma.ps1
Labels: 9-x-y, backport

#22257 build: preserve timestamps when stripping files
  script/strip-binaries.py
Labels: 8-x-y, backport, target/6-1-x, target/7-1-x

#22256 docs: remove accidental deprecation
  docs/api/system-preferences.md
Labels: new-pr 🌱, target/7-1-x, target/8-x-y, target/9-x-y

#22205 fix: add patch to route mouse event navigations through the WebConten…
  patches/chromium/.patches
  patches/chromium/fix_route_mouse_event_navigations_through_the_web_contents_delegate.patch
Labels: 8-x-y, backport

#22282 build: only strip binaries on linux
  .circleci/config.yml
Labels: fast-track 🚅, target/6-1-x, target/7-1-x

#22258 docs: Correct Electron 9 stable date
  docs/tutorial/electron-timelines.md
Labels: new-pr 🌱

#22271 chore: remove libcc from release note generator
  script/release/notes/notes.js
Labels: new-pr 🌱, target/8-x-y, target/9-x-y

#22262 docs: clean up protocol docs
  docs/api/app.md
Labels: documentation :notebook:, target/7-1-x, target/8-x-y, target/9-x-y

#20624 feat: add API for receiving logs from service workers
  docs/api/service-workers.md
  docs/api/session.md
  docs/api/structures/service-worker-info.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/session.js
  package.json
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_service_worker_context.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec-main/api-service-workers-spec.ts
  spec-main/fixtures/api/service-workers/index.html
  spec-main/fixtures/api/service-workers/logs.html
  spec-main/fixtures/api/service-workers/sw-logs.js
  spec-main/fixtures/api/service-workers/sw.js
  spec/package.json
  spec/yarn.lock
  yarn.lock
Labels: target/9-x-y

#22314 ci: fix ELECTRON_OUT_DIR
  .circleci/config.yml
Labels: 6-1-x, backport

#22274 fix: typo in crash reporter constructor
  lib/common/crash-reporter.js
Labels: target/8-x-y, target/9-x-y

#22206 fix: revert {Atom => Electron}Application rename
  shell/app/electron_main_delegate_mac.mm
  shell/browser/browser_mac.mm
  shell/browser/electron_browser_main_parts_mac.mm
  shell/browser/mac/electron_application.h
  shell/browser/mac/electron_application.mm
  shell/browser/resources/mac/Info.plist
  shell/common/resources/mac/MainMenu.xib
Labels: target/8-x-y, target/9-x-y

#22188 fix: emit will-navigate for sandboxed contents
  shell/browser/common_web_contents_delegate.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
  spec-main/api-browser-window-spec.ts
  spec/fixtures/pages/will-navigate.html
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22310 ci: update to CircleCI v2 config and APIs
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: target/6-1-x

#22177 feat: [extensions] support extension.getBackgroundPage (#21951)
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/extension.json
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/lazy-background-page/background.js
  spec-main/fixtures/extensions/lazy-background-page/get-background-page.js
  spec-main/fixtures/extensions/lazy-background-page/page-get-background.html
  spec-main/fixtures/extensions/lazy-background-page/page-runtime-get-background.html
  spec-main/fixtures/extensions/lazy-background-page/runtime-get-background-page.js
  spec-main/fixtures/extensions/ui-page/bare-page.html
  spec-main/fixtures/extensions/ui-page/manifest.json
  spec-main/fixtures/extensions/ui-page/page-get-background.html
  spec-main/fixtures/extensions/ui-page/page-script-load.html
  spec-main/fixtures/extensions/ui-page/script.js
Labels: 9-x-y, backport

#20965 fix: disable remote layer APIs in MAS build
  patches/chromium/.patches
  patches/chromium/mas_disable_remote_layer.patch
  shell/app/electron_main_delegate.cc
Labels: in-flight/7-1-x, in-flight/8-x-y, merged/5-1-x, merged/6-1-x, target/9-x-y

#22298 fix: disable remote layer APIs in MAS build (8-x-y)
  patches/chromium/.patches
  patches/chromium/mas_disable_remote_layer.patch
  shell/app/electron_main_delegate.cc
Labels: 8-x-y, backport

#22299 fix: disable remote layer APIs in MAS build (7-1-x)
  patches/chromium/.patches
  patches/chromium/mas_disable_remote_layer.patch
  shell/app/atom_main_delegate.cc
Labels: 7-1-x, backport

#22326 fix: revert {Atom => Electron}Application rename (#22206)
  shell/app/electron_main_delegate_mac.mm
  shell/browser/browser_mac.mm
  shell/browser/electron_browser_main_parts_mac.mm
  shell/browser/mac/electron_application.h
  shell/browser/mac/electron_application.mm
  shell/browser/resources/mac/Info.plist
  shell/common/resources/mac/MainMenu.xib
Labels: 8-x-y, backport

#22212 fix(extensions): set lowest isolated world id
  filenames.gni
  shell/common/world_ids.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_render_frame_observer.h
  shell/renderer/extensions/electron_extensions_renderer_client.cc
  shell/renderer/renderer_client_base.cc
Labels: target/9-x-y

#22328 fix: emit will-navigate for sandboxed contents (#22188)
  shell/browser/common_web_contents_delegate.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
  spec-main/api-browser-window-spec.ts
  spec/fixtures/pages/will-navigate.html
Labels: 8-x-y, backport

#22338 fix: crash in seccomp-bpf sandbox with glibc 2.31
  patches/chromium/.patches
  patches/chromium/allow_restricted_clock_nanosleep_in_linux_sandbox.patch
Labels: 7-1-x, in-flight/6-1-x

#22366 refactor: saner blink_initialization_order.patch (#22054)
  patches/chromium/.patches
  patches/chromium/add_didinstallconditionalfeatures.patch
  patches/chromium/blink_initialization_order.patch
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_render_frame_observer.h
Labels: 9-x-y, backport

#22336 feat: set app.enableRendererProcessReuse to true by default
  docs/api/browser-window.md
  docs/api/service-workers.md
  docs/breaking-changes.md
  script/spec-runner.js
  shell/browser/electron_browser_client.h
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-affinity-spec.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-remote-spec.ts
  spec-main/api-web-contents-spec.ts
Labels: target/9-x-y

#22342 fix: don't run environment bootstrapper
  patches/node/.patches
  patches/node/build_add_gn_build_files.patch
  patches/node/chore_prevent_warn_non_context-aware_native_modules_being_loaded.patch
  patches/node/chore_split_createenvironment_into_createenvironment_and.patch
  patches/node/fix_don_t_preparemainexecution_twice.patch
  patches/node/fix_key_gen_apis_are_not_available_in_boringssl.patch
  patches/node/revert_crypto_add_oaeplabel_option.patch
  script/node-disabled-tests.json
  shell/app/node_main.cc
  shell/browser/electron_browser_main_parts.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: target/8-x-y, target/9-x-y

#22353 fix: pass safeDialogs preference to dialog properly
  shell/browser/electron_javascript_dialog_manager.cc
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22382 fix: add patch to set the base download URL rather than override it completely
  patches/chromium/.patches
  patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch
  shell/browser/api/electron_api_session.cc
Labels: fast-track 🚅, target/8-x-y, target/9-x-y

#22329 fix: emit will-navigate for sandboxed contents (#22188)
  shell/browser/common_web_contents_delegate.cc
  shell/renderer/atom_sandboxed_renderer_client.cc
  shell/renderer/atom_sandboxed_renderer_client.h
  spec-main/api-browser-window-spec.ts
  spec/fixtures/pages/will-navigate.html
Labels: 7-1-x, backport

#22339 fix: crash in seccomp-bpf sandbox with glibc 2.31
  patches/common/chromium/.patches
  patches/common/chromium/allow_restricted_clock_nanosleep_in_linux_sandbox.patch
Labels: 6-1-x, backport

#22272 fix: guard against duplicate TouchBarItem IDs
  lib/browser/api/touch-bar.js
  spec-main/api-touch-bar-spec.ts
Labels: target/8-x-y, target/9-x-y

#22367 fix: port CL that fixes ARIA tree impl for macOS
  patches/chromium/.patches
  patches/chromium/expose_aria_trees_as_tables_for_macos_accessibility.patch
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22386 fix: allow persistent media salts
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  spec-main/chromium-spec.ts
Labels: new-pr 🌱, target/8-x-y, target/9-x-y

#22383 docs: improve documentation on spellchecker download URL
  docs/api/session.md
Labels: documentation :notebook:, target/8-x-y, target/9-x-y

#22099 chore: add tests for the spellchecker
  spec-main/fixtures/chromium/spellchecker.html
  spec-main/spellchecker-spec.ts
Labels: wip ⚒

#22160 fix: revive offscreen rendering support
  BUILD.gn
  build/args/all.gn
  patches/chromium/.patches
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
  shell/browser/osr/osr_host_display_client.cc
  shell/browser/osr/osr_host_display_client.h
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/osr/osr_video_consumer.h
Labels: target/9-x-y

#22401 feat: set app.enableRendererProcessReuse to true by default (#22336)
  docs/api/browser-window.md
  script/spec-runner.js
  shell/browser/electron_browser_client.h
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-affinity-spec.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-remote-spec.ts
  spec-main/api-web-contents-spec.ts
Labels: 9-x-y, backport, new-pr 🌱

#22426 fix: backport v8 patch for type inference issue
  patches/v8/.patches
  patches/v8/fix_bug_in_receiver_maps_inference.patch
Labels: fast-track 🚅, target/8-x-y

#22428 fix: backport v8 patch for type inference issue
  patches/v8/.patches
  patches/v8/fix_bug_in_receiver_maps_inference.patch
Labels: fast-track 🚅

#22429 fix: backport v8 patch for type inference issue
  patches/common/v8/.patches
  patches/common/v8/fix_bug_in_receiver_maps_inference.patch
Labels: fast-track 🚅

#22419 chore: bump chromium to 80.0.3987.128
  DEPS
  patches/chromium/can_create_window.patch
  patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch
  patches/chromium/command-ismediakey.patch
  patches/chromium/disable_color_correct_rendering.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch
  patches/chromium/feat_allow_disbaling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/fix_add_executable_to_chromedriver_s_rpath_for_electron_8.patch
  patches/chromium/fix_route_mouse_event_navigations_through_the_web_contents_delegate.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
  patches/chromium/web_contents.patch
Labels: 8-x-y, new-pr 🌱

#22435 fix: OOB access in ReadableStream::Close
  patches/chromium/.patches
  patches/chromium/move_readablestream_requests_onto_the_stack_before_iteration.patch
  patches/chromium/streams_convert_state_dchecks_to_checks.patch
Labels: 7-1-x, fast-track 🚅, new-pr 🌱

#22436 fix: OOB access in ReadableStream::Close
  patches/common/chromium/.patches
  patches/common/chromium/move_readablestream_requests_onto_the_stack_before_iteration.patch
  patches/common/chromium/streams_convert_state_dchecks_to_checks.patch
Labels: 6-1-x, fast-track 🚅, new-pr 🌱

#22397 chore: ensure correct scopes are in place
  shell/app/node_main.cc
Labels: target/8-x-y, target/9-x-y

#22410 fix: prevent potential modal window close segfault
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: target/7-1-x, target/8-x-y, target/9-x-y

#22444 fix: dictionaries download path should be in userdata
  shell/browser/api/electron_api_app.cc
  shell/browser/electron_browser_context.cc
Labels: new-pr 🌱, target/8-x-y, target/9-x-y
