Repository electron/electron, pull requests merged in 2020-08, with the labels that each got.

#24766 fix: crash when navigating from a page with webview that has inherited zoom level
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/web_view_guest_delegate.cc
  shell/browser/web_view_guest_delegate.h
  spec-main/webview-spec.ts
  spec/fixtures/pages/webview-zoom-inherited.html
Labels: 8-x-y, backport

#24483 fix(extensions): bypass cors in requests made from background pages
  shell/browser/electron_browser_client.cc
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/ui-page/manifest.json
Labels: target/10-x-y, target/9-x-y

#24816 docs: remove reference to remote from faq
  docs/faq.md
Labels: documentation :notebook:

#24818 fix: duplicate suspend/resume events
  shell/browser/api/electron_api_power_monitor_mac.mm
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24831 fix: use non-symbols in isURLInstance check
  patches/node/.patches
  patches/node/lib_use_non-symbols_in_isurlinstance_check.patch
  spec/node-spec.js
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24854 fix: increase max crash key value length
  docs/api/crash-reporter.md
  shell/common/crash_keys.cc
  spec-main/api-crash-reporter-spec.ts
Labels: 9-x-y, backport

#24853 fix: increase max crash key value length
  docs/api/crash-reporter.md
  shell/common/crash_keys.cc
  spec-main/api-crash-reporter-spec.ts
Labels: 10-x-y, backport

#24847 fix: do not render inactive titlebar as active on Windows
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24666 chore: add Trop annotations to release notes.
  script/release/notes/index.js
  script/release/notes/notes.js
  spec-main/fixtures/release-notes/cache/electron-electron-commit-0600420bac25439fc2067d51c6aaa4ee11770577
  spec-main/fixtures/release-notes/cache/electron-electron-commit-2955c67c4ea712fa22773ac9113709fc952bfd49
  spec-main/fixtures/release-notes/cache/electron-electron-commit-2fad53e66b1a2cb6f7dad88fe9bb62d7a461fe98
  spec-main/fixtures/release-notes/cache/electron-electron-commit-467409458e716c68b35fa935d556050ca6bed1c4
  spec-main/fixtures/release-notes/cache/electron-electron-commit-89eb309d0b22bd4aec058ffaf983e81e56a5c378
  spec-main/fixtures/release-notes/cache/electron-electron-commit-8bc0c92137f4a77dc831ca644a86a3e48b51a11e
  spec-main/fixtures/release-notes/cache/electron-electron-commit-a6ff42c190cb5caf8f3e217748e49183a951491b
  spec-main/fixtures/release-notes/cache/electron-electron-issue-20214-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-21497-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-21891-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-21946-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-22750-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-22770-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-22828-comments
  spec-main/fixtures/release-notes/cache/electron-electron-pull-20214
  spec-main/fixtures/release-notes/cache/electron-electron-pull-20620
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21497
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21591
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21891
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21946
  spec-main/fixtures/release-notes/cache/electron-electron-pull-22750
  spec-main/fixtures/release-notes/cache/electron-electron-pull-22770
  spec-main/fixtures/release-notes/cache/electron-electron-pull-22828
  spec-main/package.json
  spec-main/release-notes-spec.ts
  spec-main/yarn.lock
Labels: 10-x-y, backport

#24866 chore: add V8 crash information to crashReporter
  shell/common/api/electron_api_v8_util.cc
  shell/common/api/electron_bindings.cc
  spec-main/api-crash-reporter-spec.ts
  typings/internal-ambient.d.ts
Labels: 10-x-y, backport

#24868 fix: add handle scope in SelectClientCertificate
  shell/browser/api/electron_api_app.cc
Labels: target/10-x-y, target/9-x-y

#24881 fix: send guid with linux crashes
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_crash_reporter.h
  shell/browser/electron_browser_client.cc
  spec-main/api-crash-reporter-spec.ts
Labels: target/10-x-y, target/9-x-y

#24919 chore: update patches
  patches/chromium/command-ismediakey.patch
  patches/chromium/crash_allow_setting_more_options.patch
  patches/chromium/disable_compositor_recycling.patch
  patches/chromium/fix_provide_axtextchangevaluestartmarker_a11y_value_change.patch
  patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch
  patches/chromium/mas-cfisobjc.patch
  patches/chromium/mas_blink_no_private_api.patch
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/render_widget_host_view_mac.patch
  patches/chromium/webview_cross_drag.patch
  patches/squirrel.mac/fix_ensure_that_self_is_retained_until_the_racsignal_is_complete.patch
Labels: new-pr 🌱

#24922 chore: revert adding Trop annotations to release notes
  script/release/notes/index.js
  script/release/notes/notes.js
  spec-main/fixtures/release-notes/cache/electron-electron-commit-0600420bac25439fc2067d51c6aaa4ee11770577
  spec-main/fixtures/release-notes/cache/electron-electron-commit-2955c67c4ea712fa22773ac9113709fc952bfd49
  spec-main/fixtures/release-notes/cache/electron-electron-commit-2fad53e66b1a2cb6f7dad88fe9bb62d7a461fe98
  spec-main/fixtures/release-notes/cache/electron-electron-commit-467409458e716c68b35fa935d556050ca6bed1c4
  spec-main/fixtures/release-notes/cache/electron-electron-commit-89eb309d0b22bd4aec058ffaf983e81e56a5c378
  spec-main/fixtures/release-notes/cache/electron-electron-commit-8bc0c92137f4a77dc831ca644a86a3e48b51a11e
  spec-main/fixtures/release-notes/cache/electron-electron-commit-a6ff42c190cb5caf8f3e217748e49183a951491b
  spec-main/fixtures/release-notes/cache/electron-electron-issue-20214-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-21497-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-21891-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-21946-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-22750-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-22770-comments
  spec-main/fixtures/release-notes/cache/electron-electron-issue-22828-comments
  spec-main/fixtures/release-notes/cache/electron-electron-pull-20214
  spec-main/fixtures/release-notes/cache/electron-electron-pull-20620
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21497
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21591
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21891
  spec-main/fixtures/release-notes/cache/electron-electron-pull-21946
  spec-main/fixtures/release-notes/cache/electron-electron-pull-22750
  spec-main/fixtures/release-notes/cache/electron-electron-pull-22770
  spec-main/fixtures/release-notes/cache/electron-electron-pull-22828
  spec-main/package.json
  spec-main/release-notes-spec.ts
  spec-main/yarn.lock
Labels: backport-check-skip, new-pr 🌱

#24838 fix: provide AXTextChangeValueStartMarker for macOS a11y value change notifications
  patches/chromium/.patches
  patches/chromium/provide_axtextchangevaluestartmarker_for_macos_a11y_value_change.patch
Labels: 10-x-y, backport

#24921 fix: add deps on the new devtools highlighter
  BUILD.gn
  electron_paks.gni
Labels: new-pr 🌱

#24927 build: in release notes script, do not assume electron dirname
  script/release/notes/notes.js
Labels: fast-track 🚅

#24894 chore: cherry-pick c7c412a36c from webrtc
  patches/webrtc/.patches
  patches/webrtc/check_for_null_before_accessing_sctptransport_map.patch
Labels: 7-3-x, backport-check-skip

#24885 chore: cherry-pick 26df3fdc25 from v8
  patches/v8/.patches
  patches/v8/fix_alreadycalled_checking_in_element_closures.patch
Labels: 9-x-y, backport-check-skip

#24886 chore: cherry-pick c7c412a36c from webrtc
  patches/webrtc/.patches
  patches/webrtc/check_for_null_before_accessing_sctptransport_map.patch
Labels: 8-x-y, backport-check-skip

#24887 chore: cherry-pick c7c412a36c from webrtc
  patches/webrtc/.patches
  patches/webrtc/check_for_null_before_accessing_sctptransport_map.patch
Labels: 9-x-y, backport-check-skip

#24913 fix: pdf viewer template strings
  electron_paks.gni
  shell/browser/common_web_contents_delegate.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
Labels: target/10-x-y

#24901 docs: fix typo in api/ipc-renderer
  docs/api/ipc-renderer.md
Labels: documentation :notebook:

#24946 fix: pdf preview download button not working
  shell/browser/extensions/electron_extensions_api_client.cc
Labels: target/10-x-y, target/9-x-y

#24964 fix: browser contexts live forever
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/common_web_contents_delegate.cc
  shell/browser/common_web_contents_delegate.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/net/electron_url_loader_factory.cc
  spec-main/fixtures/crash-cases/in-memory-session-double-free/index.js
Labels: target/10-x-y, target/9-x-y

#25000 build: upload windows breakpad symbols
  script/release/uploaders/upload-symbols.py
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24925 fix(docs): update outdated ref to NSP
  SECURITY.md
Labels: documentation :notebook:

#25001 fix: browser contexts live forever
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/common_web_contents_delegate.cc
  shell/browser/common_web_contents_delegate.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/net/electron_url_loader_factory.cc
  spec-main/fixtures/crash-cases/in-memory-session-double-free/index.js
Labels: 10-x-y, backport

#25002 fix: browser contexts live forever
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_cookies.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/common_web_contents_delegate.cc
  shell/browser/common_web_contents_delegate.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/net/electron_url_loader_factory.cc
  spec-main/fixtures/crash-cases/in-memory-session-double-free/index.js
Labels: 9-x-y, backport

#25003 fix: [a11y] Allow focus to move into an editable combobox's listbox
  patches/chromium/.patches
  patches/chromium/allow_focus_to_move_into_an_editable_combobox_s_listbox.patch
Labels: 10-x-y, backport-check-skip, in-flight/9-x-y, new-pr 🌱

#24997 chore: cherry-pick fix from chromium issue 1113227
  patches/chromium/.patches
  patches/chromium/reconnect_p2p_socket_dispatcher_if_network_service_dies.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#24915 fix(extensions): bypass cors in requests made from background pages
  shell/browser/electron_browser_client.cc
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/ui-page/manifest.json
Labels: 9-x-y, backport

#24955 docs: update default value for `enableRemoteModule` in BrowserWindow constructor
  docs/api/browser-window.md
Labels: documentation :notebook:, target/10-x-y

#24999 test: use custom partition for sw tests
  spec-main/chromium-spec.ts
Labels: target/10-x-y

#25004 fix: [a11y] Allow focus to move into an editable combobox's listbox
  patches/chromium/.patches
  patches/chromium/allow_focus_to_move_into_an_editable_combobox_s_listbox.patch
Labels: 9-x-y, backport, backport-check-skip

#25019 fix: add handle scope in SelectClientCertificate
  shell/browser/api/electron_api_app.cc
Labels: 10-x-y, backport

#25023 fix: backport performance fix for CSS counters
  patches/chromium/.patches
  patches/chromium/counters_only_update_ancestors_if_style_boundary_is_crossed.patch
Labels: backport-check-skip

#24798 fix(extensions): enable WebSQL in background pages
  shell/browser/electron_browser_client.cc
  spec-main/extensions-spec.ts
Labels: target/10-x-y, target/9-x-y

#25022 fix: enable TLS renegotiation in node
  patches/node/.patches
  patches/node/fix_enable_tls_renegotiation.patch
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#25014 fix: calculate frame when setting window placement
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#25024 chore: cherry-pick 70579363ce7b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-70579363ce7b.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#24998 chore: cherry-pick fix from chromium issue 1113227
  patches/chromium/.patches
  patches/chromium/reconnect_p2p_socket_dispatcher_if_network_service_dies.patch
Labels: 10-x-y, backport-check-skip

#24956 feat: reinvigorate visibleOnFullscreen option
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: target/10-x-y, target/9-x-y

#25025 chore: cherry-pick 70579363ce7b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-70579363ce7b.patch
Labels: 8-x-y, backport-check-skip

#25031 chore: fix DCHECK on print job cancellation
  patches/chromium/printing.patch
Labels: target/10-x-y

#25057 fix: calculate frame when setting window placement
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: 8-x-y, backport

#25047 fix: pdf viewer template strings
  electron_paks.gni
  shell/browser/extensions/electron_component_extension_resource_manager.cc
Labels: 10-x-y, backport

#25055 fix: revert 6ecf729 to fix Linux titlebar dark mode (master)
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: in-flight/10-x-y, new-pr 🌱

#25068 fix: add handling for non-absolute extension paths
  shell/browser/api/electron_api_session.cc
Labels: fast-track 🚅, target/10-x-y

#25086 fix: reply notifs sometimes destroyed too early
  shell/browser/notifications/mac/notification_center_delegate.mm
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24802 feat: add nativeImage.createThumbnailFromPath API
  docs/api/native-image.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/module-list.ts
  lib/browser/api/module-names.ts
  lib/browser/api/native-image.ts
  lib/browser/init.ts
  lib/browser/rpc-server.ts
  lib/common/api/module-list.ts
  lib/renderer/api/module-list.ts
  lib/renderer/api/native-image.ts
  lib/sandboxed_renderer/api/module-list.ts
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  shell/common/api/electron_api_native_image_mac.mm
  shell/common/api/electron_api_native_image_win.cc
  spec/api-native-image-spec.js
Labels: api-review/approved ✅, backport/requested 🗳, in-flight/10-x-y

#25018 ci: fix WOA failing tests
  azure-pipelines-woa.yml
  spec-main/api-web-contents-spec.ts
  spec-main/fixtures/blank.png
  spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js
  spec/api-native-image-spec.js
Labels: fast-track 🚅, target/10-x-y

#24145 fix: global shortcut media keys working with accessibility
  patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch
  shell/browser/api/electron_api_global_shortcut.cc
Labels: target/10-x-y, target/9-x-y

#25076 fix: register for connected standby changes
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#25051 fix: save normal window bounds when maximizing
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#25109 refactor: wire will-navigate up to a navigation throttle instead of OpenURL
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_navigation_throttle.cc
  shell/browser/electron_navigation_throttle.h
  spec-main/api-browser-window-spec.ts
Labels: 9-x-y, backport

#25108 refactor: wire will-navigate up to a navigation throttle instead of OpenURL
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_navigation_throttle.cc
  shell/browser/electron_navigation_throttle.h
  spec-main/api-browser-window-spec.ts
Labels: 10-x-y, backport

#25075 docs: add restricted header info to ClientRequest docs
  docs/api/client-request.md
Labels: documentation :notebook:

#25112 fix: prevent crash if BrowserView webContents was destroyed
  docs/api/browser-view.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  spec-main/api-browser-view-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#25117 fix: mitigate use of private macOS font API
  patches/chromium/mas_no_private_api.patch
Labels: fast-track 🚅, target/10-x-y

#25132 fix: save normal window bounds when maximizing
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: 10-x-y, backport

#25133 fix: save normal window bounds when maximizing
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: 9-x-y, backport

#25131 chore: fix DCHECK on print job cancellation
  patches/chromium/printing.patch
Labels: 10-x-y, backport

#25072 feat: add nativeImage.createThumbnailFromPath API
  docs/api/native-image.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/module-list.ts
  lib/browser/api/module-names.ts
  lib/browser/api/native-image.ts
  lib/browser/init.ts
  lib/browser/rpc-server.js
  lib/common/api/module-list.ts
  lib/renderer/api/module-list.ts
  lib/renderer/api/native-image.ts
  lib/sandboxed_renderer/api/module-list.ts
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  shell/common/api/electron_api_native_image_mac.mm
  shell/common/api/electron_api_native_image_win.cc
  spec/api-native-image-spec.js
Labels: 10-x-y, backport, backport/requested 🗳

#25125 feat: reinvigorate visibleOnFullscreen option
  docs/api/browser-window.md
  shell/browser/api/electron_api_top_level_window.cc
  shell/browser/api/electron_api_top_level_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: 10-x-y, backport, backport/requested 🗳

#25124 fix: make shell.moveItemToTrash return false on Windows when move is unsuccessful
  shell/common/platform_util_win.cc
  spec-main/api-shell-spec.ts
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25162 fix: resolve RegisterSuspendResumeNotification dynamically
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: fast-track 🚅, in-flight/8-x-y, in-flight/9-x-y, target/10-x-y, target/11-x-y

#25166 chore: wrap add/remove view in extra check
  shell/browser/api/electron_api_base_window.cc
Labels: fast-track 🚅

#25169 fix: make shell.moveItemToTrash return false on Windows when move is unsuccessful
  shell/common/platform_util_linux.cc
  shell/common/platform_util_win.cc
  spec-main/api-shell-spec.ts
Labels: 9-x-y, backport

#25170 fix: make shell.moveItemToTrash return false on Windows when move is unsuccessful
  shell/common/platform_util_linux.cc
  shell/common/platform_util_win.cc
  spec-main/api-shell-spec.ts
Labels: 10-x-y, backport

#25172 chore: remove bv before setting owner window
  shell/browser/api/electron_api_base_window.cc
Labels: fast-track 🚅

#25171 fix: make shell.moveItemToTrash return false on Windows when move is unsuccessful
  shell/common/platform_util_win.cc
  spec-main/api-shell-spec.ts
Labels: 11-x-y, backport

#25110 refactor: wire will-navigate up to a navigation throttle instead of OpenURL
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_navigation_throttle.cc
  shell/browser/electron_navigation_throttle.h
  spec-main/api-browser-window-spec.ts
Labels: 8-x-y, backport

#25165 fix: register for connected standby changes
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: 9-x-y, backport

#25163 fix: register for connected standby changes
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: 8-x-y, backport

#25139 fix: do not reset process_id in URLLoaderFactoryParams
  shell/browser/electron_browser_client.cc
  spec-main/chromium-spec.ts
Labels: target/10-x-y, target/11-x-y, target/8-x-y, target/9-x-y

#25164 fix: save dialog extensions should be deterministic
  shell/browser/ui/file_dialog_mac.mm
Labels: target/10-x-y, target/11-x-y, target/9-x-y

#25126 feat: reinvigorate visibleOnFullscreen option
  docs/api/browser-window.md
  shell/browser/api/electron_api_top_level_window.cc
  shell/browser/api/electron_api_top_level_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: 9-x-y, backport, backport/approved ✅

#25181 fix: do not reset process_id in URLLoaderFactoryParams
  shell/browser/electron_browser_client.cc
  spec-main/chromium-spec.ts
Labels: 8-x-y, backport

#25149 docs: fix supported platforms of powerMonitor
  docs/api/power-monitor.md
Labels: target/10-x-y, target/11-x-y, target/8-x-y, target/9-x-y

#25052 fix: client area inset calculation when maximized for framless windows
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: target/10-x-y, target/11-x-y, target/8-x-y, target/9-x-y

#25212 docs: fix supported platforms of powerMonitor
  docs/api/power-monitor.md
Labels: 10-x-y, backport, target/8-x-y, target/9-x-y

#25218 fix: client area inset calculation when maximized for framless windows
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: 9-x-y, backport

#25221 fix: Avoid loading DRI via GBM when GpuMemoryBuffers are disabled
  patches/chromium/.patches
  patches/chromium/avoid_loading_dri_via_gbm_when_gpumemorybuffers_are_disabled.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#25220 fix: crash when using v8 cpu_profiler with wasm in the renderer
  patches/v8/.patches
  patches/v8/wasm_do_not_log_code_of_functions_whose_module_is_not_fully_loaded.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱

#25217 fix: client area inset calculation when maximized for frameless windows
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: 11-x-y, backport

#25216 fix: client area inset calculation when maximized for framless windows
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: 10-x-y, backport

#25219 fix: client area inset calculation when maximized for framless windows
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: 8-x-y, backport
