Repository electron/electron, pull requests merged in 2020-04, with the labels that each got.

#22867 fix: ensure standard schemes are registered in nw service process
  shell/app/electron_content_client.cc
  shell/renderer/renderer_client_base.cc
  spec-main/api-protocol-spec.ts
  spec-main/fixtures/api/custom-protocol-shutdown.js
Labels: target/9-x-y

#22903 fix: webRequest module should work with file:// protocol
  shell/browser/api/electron_api_web_request.cc
  shell/browser/electron_browser_client.cc
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  spec-main/api-web-request-spec.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#22922 test: do not trigger unhandled promise rejections
  spec-main/api-web-request-spec.ts
Labels: fast-track 🚅

#22870 chore: cherry-pick fd211b44535c from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-fd211b44535c.patch
Labels: 6-1-x

#22869 chore: cherry-pick fd211b44535c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-fd211b44535c.patch
Labels: 7-2-x

#22919 fix: webRequest module should work with file:// protocol (9-x-y)
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/browser/api/electron_api_web_request.cc
  shell/browser/electron_browser_client.cc
  shell/browser/net/proxying_url_loader_factory.cc
  spec-main/api-web-request-spec.ts
Labels: 9-x-y, backport

#22901 fix: propagate preferred color scheme to the renderer (#22896)
  patches/chromium/can_create_window.patch
  patches/chromium/feat_add_set_theme_source_to_allow_apps_to.patch
  patches/chromium/feat_allow_embedders_to_add_observers_on_created_hunspell.patch
  patches/chromium/os_metrics_mac.patch
  patches/chromium/port_aria_tree_fix_for_macos_voiceover.patch
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec-main/api-native-theme-spec.ts
Labels: 8-x-y, backport

#22911 fix: undo and redo broken in webviews
  patches/chromium/.patches
  patches/chromium/fix_undo_redo_broken_in_webviews.patch
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#22925 fix: webframe crashes for removed render frame
  shell/renderer/api/electron_api_web_frame.cc
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#22944 chore: cherry-pick db71a0afc1d0 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-db71a0afc1d0.patch
Labels: 6-1-x, backport-check-skip, new-pr 🌱

#22985 build: set merge=union for .patches
  .gitattributes
Labels: target/6-1-x, target/7-2-x, target/8-x-y, target/9-x-y

#22974 docs: note that shell can't be used in sandboxed renderers
  docs/api/shell.md
Labels: new-pr 🌱

#22946 chore: cherry-pick b5950ad76471 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/audiocontext_haspendingactivity_unless_it_s_closed.patch
  patches/common/chromium/protect_automatic_pull_handlers_with_mutex.patch
Labels: 6-1-x, backport-check-skip

#22945 chore: cherry-pick b5950ad76471 from chromium
  patches/chromium/.patches
  patches/chromium/audiocontext_haspendingactivity_unless_it_s_closed.patch
  patches/chromium/browser_compositor_mac.patch
  patches/chromium/command-ismediakey.patch
  patches/chromium/fix_disabling_compositor_recycling.patch
  patches/chromium/fix_hi-dpi_transitions_on_catalina.patch
  patches/chromium/make_autocorrect_off_and_spellcheck_false_disable_touch_bar_typing.patch
  patches/chromium/mas-cfisobjc.patch
  patches/chromium/mas_blink_no_private_api.patch
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_disable_spi_file_type_mappings.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/port_aria_tree_fix_for_macos_voiceover.patch
  patches/chromium/protect_automatic_pull_handlers_with_mutex.patch
  patches/chromium/render_widget_host_view_mac.patch
  patches/chromium/webview_cross_drag.patch
Labels: 7-2-x, backport-check-skip

#22836 docs: Update the "Electron vs NW.js" document
  docs/development/atom-shell-vs-node-webkit.md
  docs/development/electron-vs-nwjs.md
Labels: documentation :notebook:

#22988 fix: persist maximizable state when toggling fullscreen
  shell/browser/ui/cocoa/electron_ns_window.mm
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#22948 fix: nullptr check when closing windows
  shell/browser/window_list.cc
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#22975 fix: webframe crashes for removed render frame
  shell/renderer/api/electron_api_web_frame.cc
Labels: 8-x-y, backport

#22710 fix: crash on invalid zoomFactor
  docs/api/web-contents.md
  docs/api/web-frame.md
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
  shell/renderer/api/atom_api_web_frame.cc
Labels: 7-2-x, backport

#22977 chore: cherry-pick adc8f05aa3ab from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-adc8f05aa3ab.patch
Labels: 7-2-x, backport-check-skip

#22984 chore: cherry-pick a0a48e0132bc from chromium
  patches/common/chromium/.patches
  patches/common/chromium/mojovideoencodeacceleratorservice_handle_potential_later.patch
Labels: 6-1-x, backport-check-skip

#23003 build: auto-generate the codesigning cert used for macOS CI testing runs
  .circleci/config.yml
  script/codesign/.gitignore
  script/codesign/codesign.cnf
  script/codesign/gen-trust.js
  script/codesign/generate-identity.sh
  script/codesign/import-testing-cert-ci.sh
  script/codesign/signing.cer
  script/codesign/signing.p12
  script/codesign/signing.pem
  script/codesign/trust-settings.plist
  script/codesign/trust.xml
Labels: 7-2-x, backport

#22976 ci: auto-3way patches and detect changes
  .circleci/config.yml
  patches/boringssl/fix_add_RSA-PSS_keygen_functions.patch
  patches/chromium/command-ismediakey.patch
  patches/chromium/disable_compositor_recycling.patch
  patches/chromium/fix_undo_redo_broken_in_webviews.patch
  patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch
  patches/chromium/mas-cfisobjc.patch
  patches/chromium/mas_blink_no_private_api.patch
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/render_widget_host_view_mac.patch
  patches/chromium/webview_cross_drag.patch
  patches/v8/add_realloc.patch
  patches/v8/build_gn.patch
  patches/v8/dcheck.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
  patches/v8/expose_mksnapshot.patch
  patches/v8/revert_cleanup_switch_offset_of_to_offsetof_where_possible.patch
  script/export_all_patches.py
  script/git-export-patches
  script/lib/git.py
Labels: target/6-1-x, target/7-2-x, target/8-x-y, target/9-x-y

#22978 chore: cherry-pick adc8f05aa3ab from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-adc8f05aa3ab.patch
Labels: 6-1-x, backport-check-skip

#23033 ci: auto-3way patches and detect changes
  .circleci/config.yml
  DEPS
  patches/angle/gles2_use_constant_initialization_for_g_mutex.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-db71a0afc1d0.patch
  patches/chromium/handle_err_cache_race_in_dodoneheadersaddtoentrycomplete.patch
  patches/node/build_add_gn_build_files.patch
  patches/node/build_bring_back_node_with_ltcg_configuration.patch
  patches/node/chore_add_ability_to_prevent_warn_non_context-aware_native_modules.patch
  patches/node/export_environment_knodecontexttagptr.patch
  patches/node/fix_enable_worker_threads.patch
  patches/node/fix_extern_the_nativemoduleenv_and_options_parser_for_debug_builds.patch
  patches/node/fix_uv_fs_mkdir_for_invalid_names.patch
  patches/node/fixme_revert_crypto_add_support_for_rsa-pss_keys.patch
  patches/node/fsevents-regression-in-watching.patch
  patches/node/fsevents-stop-using-fsevents-to-watch-files.patch
  patches/node/win-fix-uv_spawn-ENOMEM-on-empty-env.patch
  patches/perfetto/metatrace_remove_memset_and_trivial_ctor_assumption.patch
  patches/quiche/include_ostream_in_quic_ip_address_h.patch
  patches/v8/add_realloc.patch
  patches/v8/build_gn.patch
  patches/v8/dcheck.patch
  patches/v8/deps_provide_more_v8_backwards_compatibility.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
  patches/v8/export_symbols_needed_for_windows_build.patch
  patches/v8/expose_mksnapshot.patch
  patches/v8/fix_bug_in_receiver_maps_inference.patch
  patches/v8/include_string_in_v8_h.patch
  patches/v8/objects_fix_memory_leak_in_prototypeusers_add.patch
  script/export_all_patches.py
  script/git-export-patches
  script/lib/git.py
Labels: 7-2-x, backport

#23032 ci: auto-3way patches and detect changes
  .circleci/config.yml
  DEPS
  patches/boringssl/.patches
  patches/chromium/command-ismediakey.patch
  patches/chromium/disable_compositor_recycling.patch
  patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch
  patches/chromium/mas-cfisobjc.patch
  patches/chromium/mas_blink_no_private_api.patch
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/port_aria_tree_fix_for_macos_voiceover.patch
  patches/chromium/render_widget_host_view_mac.patch
  patches/chromium/webview_cross_drag.patch
  patches/node/export_environment_knodecontexttagptr.patch
  patches/node/fix_export_node_abort_and_assert.patch
  patches/node/fix_extern_the_nativemoduleenv_and_options_parser_for_debug_builds.patch
  patches/node/fix_remove_uses_of_node_use_v8_platform.patch
  patches/node/fixme_revert_crypto_add_support_for_rsa-pss_keys.patch
  patches/node/revert_crypto_add_oaeplabel_option.patch
  patches/node/revert_tls_add_option_to_override_signature_algorithms.patch
  patches/v8/add_realloc.patch
  patches/v8/build_gn.patch
  patches/v8/dcheck.patch
  patches/v8/deps_provide_more_v8_backwards_compatibility.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
  patches/v8/export_symbols_needed_for_windows_build.patch
  patches/v8/expose_mksnapshot.patch
  patches/v8/fix_build_deprecated_attirbute_for_older_msvc_versions.patch
  patches/v8/objects_fix_memory_leak_in_prototypeusers_add.patch
  patches/v8/workaround_an_undefined_symbol_error.patch
  script/export_all_patches.py
  script/git-export-patches
  script/lib/git.py
Labels: 8-x-y, backport

#23034 ci: auto-3way patches and detect changes
  .circleci/config.yml
  DEPS
  patches/common/chromium/browser_compositor_mac.patch
  patches/common/chromium/cherry-pick-db71a0afc1d0.patch
  patches/common/chromium/command-ismediakey.patch
  patches/common/chromium/fix_disabling_compositor_recycling.patch
  patches/common/chromium/fix_hi-dpi_transitions_on_catalina.patch
  patches/common/chromium/make_autocorrect_off_and_spellcheck_false_disable_touch_bar_typing.patch
  patches/common/chromium/mas-cfisobjc.patch
  patches/common/chromium/mas_blink_no_private_api.patch
  patches/common/chromium/mas_disable_custom_window_frame.patch
  patches/common/chromium/mas_disable_remote_accessibility.patch
  patches/common/chromium/mas_disable_remote_layer.patch
  patches/common/chromium/mas_disable_spi_file_type_mappings.patch
  patches/common/chromium/mas_no_private_api.patch
  patches/common/chromium/render_widget_host_view_mac.patch
  patches/common/chromium/webview_cross_drag.patch
  patches/common/ffmpeg/build_gn.patch
  patches/common/v8/fix_bug_in_receiver_maps_inference.patch
  patches/common/v8/objects_fix_memory_leak_in_prototypeusers_add.patch
  patches/node/build_bring_back_node_with_ltcg_configuration.patch
  patches/node/fix_enable_worker_threads.patch
  patches/node/fix_extern_the_nativemoduleenv_and_options_parser_for_debug_builds.patch
  patches/node/fix_uv_fs_mkdir_for_invalid_names.patch
  patches/node/fsevents-regression-in-watching.patch
  patches/node/fsevents-stop-using-fsevents-to-watch-files.patch
  patches/node/win-fix-uv_spawn-ENOMEM-on-empty-env.patch
  script/apply_all_patches.py
  script/export_all_patches.py
  script/git-export-patches
  script/lib/git.py
Labels: 6-1-x, backport

#22979 chore: cherry-pick d4564dcc2520 from chromium
  patches/chromium/.patches
  patches/chromium/reland_sequentialise_access_to_callbacks_in.patch
Labels: 7-2-x, backport-check-skip

#22980 chore: cherry-pick d4564dcc2520 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/reland_sequentialise_access_to_callbacks_in.patch
Labels: 6-1-x, backport-check-skip

#23030 chore: remove no longer needed debugging patch
  patches/chromium/.patches
  patches/chromium/verbose_generate_breakpad_symbols.patch
Labels: new-pr 🌱

#23044 fix: backport b52f7fb5933a from WebRTC.
  patches/config.json
  patches/webrtc/.patches
  patches/webrtc/fix_vector_allocation_for_raw_data_handling.patch
Labels: 7-2-x, backport-check-skip

#23031 ci: auto-3way patches and detect changes
  .circleci/config.yml
  DEPS
  package.json
  patches/boringssl/fix_add_RSA-PSS_keygen_functions.patch
  patches/chromium/command-ismediakey.patch
  patches/chromium/disable_compositor_recycling.patch
  patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch
  patches/chromium/mas-cfisobjc.patch
  patches/chromium/mas_blink_no_private_api.patch
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/render_widget_host_view_mac.patch
  patches/chromium/webview_cross_drag.patch
  patches/v8/add_realloc.patch
  patches/v8/build_gn.patch
  patches/v8/dcheck.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
  patches/v8/expose_mksnapshot.patch
  patches/v8/revert_cleanup_switch_offset_of_to_offsetof_where_possible.patch
  script/export_all_patches.py
  script/git-export-patches
  script/lib/git.py
Labels: 9-x-y, backport

#22987 chore: cherry-pick 3030db702eee from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-3030db702eee.patch
Labels: 6-1-x, backport-check-skip

#23058 build: Update patches for 6-1-x
  patches/common/chromium/-_point_usrsctp_to_a68325e7d9ed844cc84ec134192d788586ea6cc1.patch
  patches/common/chromium/.patches
  patches/common/chromium/handle_err_cache_race_in_dodoneheadersaddtoentrycomplete.patch
Labels: fast-track 🚅

#22981 chore: cherry-pick 728c6deeffe1 from chromium
  patches/chromium/.patches
  patches/chromium/speculative_fix_for_crashes_in_filechooserimpl.patch
Labels: 7-2-x, backport-check-skip

#23061 build: update patches
  patches/chromium/fix_breakpad_symbol_generation_on_linux_arm.patch
Labels: fast-track 🚅

#23008 fix(extensions): add more properties to port.sender.tab
  shell/browser/extensions/electron_messaging_delegate.cc
Labels: 9-x-y, backport

#22986 chore: cherry-pick 3030db702eee from chromium
  patches/chromium/-_point_usrsctp_to_a68325e7d9ed844cc84ec134192d788586ea6cc1.patch
  patches/chromium/.patches
Labels: 7-2-x, backport-check-skip

#22983 chore: cherry-pick a0a48e0132bc from chromium
  patches/chromium/.patches
  patches/chromium/mojovideoencodeacceleratorservice_handle_potential_later.patch
Labels: 7-2-x, backport-check-skip

#23014 chore: cherry-pick 3ac8883297e1 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/break_connections_before_removing_from_active_source_handlers.patch
Labels: 6-1-x, backport-check-skip

#23013 chore: cherry-pick 3ac8883297e1 from chromium
  patches/chromium/.patches
  patches/chromium/break_connections_before_removing_from_active_source_handlers.patch
Labels: 7-2-x, backport-check-skip

#23064 chore: fix type check in systemPreferences module specs
  spec-main/api-system-preferences-spec.ts
Labels: fast-track 🚅

#23009 chore: cherry-pick 4c57222340cf from chromium
  patches/chromium/.patches
  patches/chromium/make_finished_source_handlers_hold_scoped_refptrs.patch
Labels: 7-2-x, backport-check-skip

#23010 chore: cherry-pick 4c57222340cf from chromium
  patches/common/chromium/.patches
  patches/common/chromium/make_finished_source_handlers_hold_scoped_refptrs.patch
Labels: 6-1-x, backport-check-skip

#23039 fix: reset node env earlier during shutdown
  shell/browser/electron_browser_main_parts.cc
Labels: target/8-x-y, target/9-x-y

#23015 chore: cherry-pick 2cd0af7ea205 from chromium
  patches/chromium/.patches
  patches/chromium/use_weakptr_for_cross-thread_posting.patch
Labels: 7-2-x, backport-check-skip

#23011 chore: cherry-pick 913247c378d5 from chromium
  patches/chromium/.patches
  patches/chromium/use_supportsweakptr_for_messaging_from_rendering_thread_to_main.patch
Labels: 7-2-x, backport-check-skip

#23017 chore: cherry-pick 54454ec7fbcb from chromium
  patches/chromium/.patches
  patches/chromium/speculative_fix_for_potential_null_pointer_in_printwarningtoconsole.patch
  patches/chromium/verify_if_the_context_is_still_available.patch
Labels: 7-2-x, backport-check-skip

#23067 chore: remove export_fetchapi... patch
  patches/chromium/.patches
  patches/chromium/export_fetchapi_mojo_traits_to_fix_component_build.patch
Labels: new-pr 🌱

#23012 chore: cherry-pick 913247c378d5 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/use_supportsweakptr_for_messaging_from_rendering_thread_to_main.patch
Labels: 6-1-x, backport-check-skip

#23046 fix: cherry-pick 09d14728ca251 from v8
  patches/common/v8/.patches
  patches/common/v8/intl_fix_intl_numberformat_constructor.patch
Labels: 6-1-x, backport-check-skip

#22672 fix: don't assign NSAlert to window which is not visible
  docs/api/dialog.md
  shell/browser/ui/message_box_mac.mm
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23047 chore: cherry-pick 85f708fa7ab8 from chromium
  patches/chromium/.patches
  patches/chromium/use_keepselfalive_on_audiocontext_to_keep_it_alive_until_rendering.patch
  patches/chromium/when_suspending_context_don_t_clear_handlers.patch
Labels: 8-x-y, backport-check-skip

#23037 fix: backport d82a02c837d3 from WebRTC.
  patches/webrtc/.patches
  patches/webrtc/acm_corrected_temporary_buffer_size.patch
Labels: 7-2-x, backport-check-skip

#23040 chore: cherry-pick e246871765f5 from chromium
  patches/chromium/.patches
  patches/chromium/worker_stop_passing_creator_s_origin_for_starting_a_dedicated_worker.patch
Labels: 7-2-x, backport-check-skip

#22825 fix: workaround for hang when preventDefault-ing nativeWindowOpen
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec-main/api-web-contents-spec.ts
Labels: backport, master

#23059 fix: cherry-pick 2aac556145af from v8
  patches/v8/.patches
  patches/v8/make_createdynamicfunction_throw_if_disallowed.patch
  patches/v8/merged_make_createdynamicfunction_switch_context_before_throwing.patch
Labels: 7-2-x, backport-check-skip

#23070 build: improve patch filename remembering
  script/lib/patches.py
Labels: target/6-1-x, target/7-2-x, target/8-x-y, target/9-x-y

#23048 chore: cherry-pick 85f708fa7ab8 from chromium
  patches/chromium/.patches
  patches/chromium/use_keepselfalive_on_audiocontext_to_keep_it_alive_until_rendering.patch
  patches/chromium/when_suspending_context_don_t_clear_handlers.patch
Labels: 7-2-x, backport-check-skip

#23060 fix: cherry-pick 2aac556145af from v8
  patches/common/v8/.patches
  patches/common/v8/make_createdynamicfunction_throw_if_disallowed.patch
  patches/common/v8/merged_make_createdynamicfunction_switch_context_before_throwing.patch
Labels: 6-1-x, backport-check-skip

#23100 chore: rename atom things to electron things in our docs / scripts
  docs/faq.md
  docs/tutorial/application-distribution.md
  docs/tutorial/windows-store-guide.md
  lib/browser/remote/objects-registry.ts
  lib/renderer/api/remote.js
  lib/sandboxed_renderer/init.js
  script/lint.js
  shell/browser/net/proxying_url_loader_factory.h
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
Labels: new-pr 🌱

#23045 fix: backport b52f7fb5933a from WebRTC.
  patches/common/config.json
  patches/common/webrtc/.patches
  patches/common/webrtc/fix_vector_allocation_for_raw_data_handling.patch
Labels: 6-1-x, backport-check-skip

#23004 build: auto-generate the codesigning cert used for macOS CI testing runs
  .circleci/config.yml
  script/codesign/.gitignore
  script/codesign/codesign.cnf
  script/codesign/gen-trust.js
  script/codesign/generate-identity.sh
  script/codesign/import-testing-cert-ci.sh
  script/codesign/signing.cer
  script/codesign/signing.p12
  script/codesign/signing.pem
  script/codesign/trust-settings.plist
  script/codesign/trust.xml
Labels: 6-1-x, backport

#23038 fix: backport d82a02c837d3 from WebRTC.
  patches/common/webrtc/.patches
  patches/common/webrtc/acm_corrected_temporary_buffer_size.patch
Labels: 6-1-x, backport-check-skip

#23062 feat: crashReporter: expose rateLimit and compress options
  docs/api/crash-reporter.md
  lib/common/crash-reporter.js
  shell/common/crash_reporter/crash_reporter.cc
  shell/common/crash_reporter/crash_reporter.h
  shell/common/crash_reporter/crash_reporter_linux.cc
  shell/common/crash_reporter/crash_reporter_linux.h
  shell/common/crash_reporter/crash_reporter_mac.h
  shell/common/crash_reporter/crash_reporter_mac.mm
  shell/common/crash_reporter/crash_reporter_win.cc
  shell/common/crash_reporter/crash_reporter_win.h
Labels: api-review-requested

#23112 ci: fix v8 cppgc files in wrong location
  patches/node/build_add_gn_build_files.patch
Labels: fast-track 🚅

#23109 fix: add missing handle scope in file_dialog_gtk
  shell/browser/ui/file_dialog_gtk.cc
Labels: new-pr 🌱

#23116 fix: deinit platform before resetting node env
  shell/browser/electron_browser_main_parts.cc
Labels: new-pr 🌱

#23117 docs: explain the swipe event on macOS
  docs/api/browser-window.md
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#22838 docs: Improve the codesigning docs
  docs/tutorial/code-signing.md
Labels: documentation :notebook:

#23129 fix: wasm codegen in script.runInNewContext
  script/node-disabled-tests.json
  shell/app/node_main.cc
Labels: target/8-x-y, target/9-x-y

#23143 docs: fix devToolsWebContents union type
  docs/api/web-contents.md
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23136 docs: remove GitHub references
  docs/development/debug-instructions-windows.md
  docs/tutorial/updates.md
Labels: documentation :notebook:

#23173 fix: print from PDF viewer not working
  chromium_src/BUILD.gn
  shell/browser/extensions/api/resources_private/resources_private_api.cc
  shell/renderer/renderer_client_base.cc
Labels: 9-x-y, backport

#23146 fix: wasm codegen in script.runInNewContext
  script/node-disabled-tests.json
  shell/app/node_main.cc
Labels: 9-x-y, backport

#23147 fix: wasm codegen in script.runInNewContext
  script/node-disabled-tests.json
  shell/app/node_main.cc
Labels: 8-x-y, backport

#23187 test: fix type errors in devToolsWebContents
  spec-main/api-web-contents-spec.ts
Labels: fast-track 🚅

#23186 fix: backport V8 promise context fix
  patches/common/v8/.patches
  patches/common/v8/use_context_of_then_function_for_promiseresolvethenablejob.patch
Labels: backport-check-skip

#23183 fix: backport V8 promise context fix
  patches/v8/.patches
  patches/v8/use_context_of_then_function_for_promiseresolvethenablejob.patch
Labels: backport-check-skip

#23177 fix: backport V8 promise context fix
  patches/v8/.patches
  patches/v8/use_context_of_then_function_for_promiseresolvethenablejob.patch
Labels: backport-check-skip

#23179 fix: cherry-pick 04dab5a91b61 from chromium
  patches/chromium/.patches
  patches/chromium/layoutng_make_hittestresult_localpoint_for_inline_element.patch
Labels: new-pr 🌱, target/7-2-x, target/8-x-y, target/9-x-y

#23145 feat: support fullScreen BrowserWindow property
  docs/api/browser-window.md
  lib/browser/api/top-level-window.js
  spec-main/api-browser-window-spec.ts
Labels: target/9-x-y

#23182 fix: heap-use-after-free in tray.popUpContextMenu
  shell/browser/ui/tray_icon_cocoa.mm
  spec-main/api-tray-spec.ts
Labels: 7-2-x, backport

#23176 docs: update versioning doc for new major-x-y format
  docs/tutorial/electron-versioning.md
Labels: new-pr 🌱

#23153 fix: use Node's microtasks policy in node_main.cc
  shell/app/node_main.cc
  spec-main/node-spec.ts
  spec/fixtures/module/node-promise-timer.js
Labels: in-flight/9-x-y

#23181 fix: heap-use-after-free in tray.popUpContextMenu
  shell/browser/ui/tray_icon_cocoa.mm
  spec-main/api-tray-spec.ts
Labels: 8-x-y, backport

#23154 fix: use Node's microtasks policy in node_main.cc
  shell/app/node_main.cc
  spec-main/node-spec.ts
  spec/fixtures/module/node-promise-timer.js
Labels: 9-x-y, backport, target/7-2-x, target/8-x-y

#23185 build: improve patch filename remembering
  script/lib/patches.py
Labels: 6-1-x, backport

#23184 build: improve patch filename remembering
  script/lib/patches.py
Labels: 7-2-x, backport

#23207 fix: ensure that functions are not retained beyond their context being released
  shell/renderer/api/context_bridge/render_frame_function_store.cc
  shell/renderer/api/context_bridge/render_frame_function_store.h
  spec-main/api-context-bridge-spec.ts
Labels: new-pr 🌱, target/7-2-x, target/8-x-y, target/9-x-y

#23206 test: fix type errors in devToolsWebContents
  spec-main/api-web-contents-spec.ts
Labels: 8-x-y, backport

#23188 fix: block custom window.open when nativeWindowOpen is true
  lib/browser/guest-window-manager.js
  spec-main/chromium-spec.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23223 fix: do not double-declare webPreferences
  lib/browser/guest-window-manager.js
Labels: fast-track 🚅

#23194 refactor: port parts of window-setup to use ctx bridge instead of being run in the main world
  filenames.auto.gni
  lib/renderer/api/context-bridge.ts
  lib/renderer/window-setup.ts
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23226 fix: do not allow child windows to specify their own preload script
  lib/common/parse-features-string.ts
Labels: new-pr 🌱, target/6-1-x, target/7-2-x, target/8-x-y, target/9-x-y

#23232 fix: ensure that functions are not retained beyond their context being released
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.cc
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.h
  spec-main/api-context-bridge-spec.ts
Labels: 7-2-x, backport

#23231 fix: ensure that functions are not retained beyond their context being released
  shell/renderer/api/context_bridge/render_frame_function_store.cc
  shell/renderer/api/context_bridge/render_frame_function_store.h
  spec-main/api-context-bridge-spec.ts
Labels: 8-x-y, backport

#23228 fix: do not allow child windows to specify their own preload script
  lib/browser/guest-window-manager.js
Labels: 6-1-x, backport

#23229 fix: do not allow child windows to specify their own preload script
  lib/browser/guest-window-manager.js
Labels: 7-2-x, backport

#23230 fix: do not allow child windows to specify their own preload script
  lib/browser/guest-window-manager.js
Labels: 8-x-y, backport

#23236 fix: do not mutate ipc instances across contexts
  lib/renderer/api/ipc-renderer.ts
  lib/renderer/ipc-renderer-internal.ts
Labels: new-pr 🌱, target/6-1-x, target/7-2-x, target/8-x-y, target/9-x-y

#23225 fix: block custom window.open when nativeWindowOpen is true (#23188)
  lib/browser/guest-window-manager.js
  spec-main/chromium-spec.ts
Labels: 8-x-y, backport

#23227 fix: do not allow child windows to specify their own preload script
  lib/browser/guest-window-manager.js
Labels: new-pr 🌱

#23238 fix: do not mutate ipc instances across contexts
  lib/renderer/api/ipc-renderer.ts
  lib/renderer/ipc-renderer-internal.ts
Labels: 9-x-y, backport, new-pr 🌱

#23240 fix: do not mutate ipc instances across contexts
  lib/renderer/api/ipc-renderer.ts
  lib/renderer/ipc-renderer-internal.ts
Labels: 8-x-y, backport

#23239 fix: do not mutate ipc instances across contexts
  lib/renderer/api/ipc-renderer.js
  lib/renderer/ipc-renderer-internal.ts
Labels: 7-2-x, backport

#23241 fix: do not mutate ipc instances across contexts
  lib/renderer/api/ipc-renderer.js
  lib/renderer/ipc-renderer-internal.ts
Labels: 6-1-x, backport

#23237 ci: robustify doc only change check
  script/doc-only-change.js
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23208 feat: add property support for remainder of BrowserWindow
  docs/api/browser-window.md
  docs/api/modernization/property-updates.md
  lib/browser/api/browser-window.js
  lib/browser/api/top-level-window.js
  spec-main/api-browser-window-spec.ts
Labels: 9-x-y, backport

#23260 refactor: precache the IsWindowStateEvent() XAtom
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: 9-x-y, backport, new-pr 🌱

#23214 fix: set default menu in will-finish-launching event
  lib/browser/init.ts
  spec-main/fixtures/api/test-menu-visibility/main.js
Labels: target/9-x-y

#23262 docs: minor grammar & spelling fixes
  docs/api/accelerator.md
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/frameless-window.md
  docs/api/menu-item.md
  docs/api/sandbox-option.md
  docs/api/system-preferences.md
  docs/development/build-instructions-linux.md
  docs/development/build-instructions-macos.md
  docs/development/debugging-instructions-macos.md
  docs/development/pull-requests.md
  docs/fiddles/menus/customize-menus/main.js
  docs/fiddles/menus/shortcuts/main.js
  docs/fiddles/native-ui/dialogs/error-dialog/main.js
  docs/fiddles/native-ui/dialogs/information-dialog/main.js
  docs/fiddles/native-ui/dialogs/open-file-or-directory/main.js
  docs/fiddles/native-ui/dialogs/save-dialog/main.js
  docs/fiddles/native-ui/drag-and-drop/main.js
  docs/fiddles/native-ui/external-links-file-manager/main.js
  docs/fiddles/native-ui/notifications/main.js
  docs/fiddles/native-ui/tray/main.js
  docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/main.js
  docs/fiddles/windows/manage-windows/frameless-window/main.js
  docs/fiddles/windows/manage-windows/manage-window-state/main.js
  docs/fiddles/windows/manage-windows/new-window/index.html
  docs/fiddles/windows/manage-windows/new-window/main.js
  docs/fiddles/windows/manage-windows/window-events/main.js
  docs/tutorial/installation.md
  docs/tutorial/macos-dock.md
  docs/tutorial/testing-widevine-cdm.md
Labels: 9-x-y, backport

#23234 fix: use Node's microtasks policy in node_main.cc
  shell/app/node_main.cc
  spec/fixtures/module/node-promise-timer.js
  spec/node-spec.js
Labels: 8-x-y, backport

#23242 test: fix crashReporter test on woa
  spec-main/api-crash-reporter-spec.ts
Labels: fast-track 🚅

#23266 style: use build/include_directory for NOLINT
  shell/app/electron_content_client.cc
  shell/app/uv_task_runner.h
  shell/browser/javascript_environment.h
  shell/common/api/electron_bindings.h
  shell/common/electron_command_line.cc
  shell/common/node_bindings.h
  shell/renderer/renderer_client_base.h
Labels: new-pr 🌱

#23224 fix: block custom window.open when nativeWindowOpen is true (#23188)
  lib/browser/guest-window-manager.js
  spec-main/chromium-spec.ts
Labels: 7-2-x, backport

#23000 docs: add links for alternate ways to handle update servers that have auth
  docs/tutorial/updates.md
Labels: documentation :notebook:

#23286 docs: remove duplicate options
  docs/api/menu-item.md
Labels: new-pr 🌱, target/9-x-y

#23235 refactor: port window.open and window.opener to use ctx bridge instead of hole punching
  filenames.auto.gni
  lib/browser/api/web-contents.js
  lib/isolated_renderer/init.js
  lib/renderer/api/context-bridge.ts
  lib/renderer/window-setup.ts
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  spec/chromium-spec.js
  spec/fixtures/pages/window-open-postMessage.html
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23303 style: use build/include_directory for NOLINT (#23266)
  shell/app/electron_content_client.cc
  shell/app/uv_task_runner.h
  shell/browser/javascript_environment.h
  shell/common/api/electron_bindings.h
  shell/common/electron_command_line.cc
  shell/common/node_bindings.h
  shell/renderer/renderer_client_base.h
Labels: 8-x-y, backport, fast-track 🚅, target/6-1-x, target/7-2-x

#23299 refactor: port window-setup to use ctx bridge instead of being run in the main world
  filenames.auto.gni
  lib/browser/api/web-contents.js
  lib/isolated_renderer/init.js
  lib/renderer/api/context-bridge.ts
  lib/renderer/window-setup.ts
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  spec-main/api-context-bridge-spec.ts
  spec/chromium-spec.js
  spec/fixtures/pages/window-open-postMessage.html
Labels: 9-x-y, backport

#23301 fix: do not add 104 to the history length
  lib/renderer/window-setup.ts
Labels: fast-track 🚅

#23302 refactor: port window-setup to use ctx bridge instead of being run in the main world
  filenames.auto.gni
  lib/browser/api/web-contents.js
  lib/isolated_renderer/init.js
  lib/renderer/api/context-bridge.ts
  lib/renderer/window-setup.ts
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  spec-main/api-context-bridge-spec.ts
  spec/chromium-spec.js
  spec/fixtures/pages/window-open-postMessage.html
Labels: 8-x-y, backport

#23297 docs: remove sccache info from build instructions
  docs/development/build-instructions-gn.md
Labels: new-pr 🌱

#23324 fix: use Node's microtasks policy in node_main.cc
  shell/app/node_main.cc
  spec/fixtures/module/node-promise-timer.js
  spec/node-spec.js
Labels: 7-2-x, backport

#23332 ci: make sure msedge isn't running at end of woa test
  azure-pipelines-woa.yml
Labels: fast-track 🚅

#23305 refactor: port window-setup to use ctx bridge instead of being run in the main world
  filenames.auto.gni
  lib/browser/api/web-contents.js
  lib/isolated_renderer/init.js
  lib/renderer/api/context-bridge.ts
  lib/renderer/window-setup.ts
  shell/renderer/api/atom_api_context_bridge.cc
  shell/renderer/api/atom_api_context_bridge.h
  shell/renderer/atom_renderer_client.cc
  shell/renderer/atom_sandboxed_renderer_client.cc
  spec-main/api-context-bridge-spec.ts
  spec/chromium-spec.js
  spec/fixtures/pages/window-open-postMessage.html
Labels: 7-2-x, backport

#23321 fix: do not leak IPC or context bridge promises
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_ipc_renderer.cc
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23341 chore: remove obsolete webview patch
  patches/chromium/.patches
  patches/chromium/fix_undo_redo_broken_in_webviews.patch
Labels: new-pr 🌱

#23336 fix: backport fix for zero-size pixels in blink
  patches/chromium/.patches
  patches/chromium/never_let_a_non-zero-size_pixel_snap_to_zero_size.patch
Labels: backport-check-skip

#23308 fix: prevent Menu.buildFromTemplate with empty array
  lib/browser/api/menu-item.js
  lib/browser/api/menu.js
  spec-main/api-menu-spec.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#21698 docs: event.newGuest for new-window in WebContents and webContents in BrowsweWindow's constructor
  docs/api/structures/new-window-event.md
  docs/api/web-contents.md
  filenames.auto.gni
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23340 refactor: remove JS for non-native extensions shim
  BUILD.gn
  build/webpack/webpack.config.content_script.js
  filenames.auto.gni
  lib/browser/chrome-extension-shim.js
  lib/browser/chrome-extension.js
  lib/browser/init.ts
  lib/browser/rpc-server.js
  lib/content_script/init.js
  lib/renderer/chrome-api.ts
  lib/renderer/init.ts
  lib/sandboxed_renderer/init.js
  script/gen-filenames.js
  spec-main/extensions-spec.ts
Labels: new-pr 🌱

#23339 fix: do not leak IPC or context bridge promises (#23321)
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_renderer_ipc.cc
Labels: 8-x-y, backport

#23362 docs: rename duplicated interface
  docs/api/structures/new-window-event.md
  docs/api/structures/new-window-web-contents-event.md
  docs/api/web-contents.md
  filenames.auto.gni
Labels: fast-track 🚅

#23367 docs: fix Chrome Tracing tool link markdown
  docs/tutorial/performance.md
Labels: new-pr 🌱

#23370 fix: undo and redo broken in webviews
  patches/chromium/.patches
  patches/chromium/fix-ensure-edit-cmds-to-sent-focused-WebContents.patch
Labels: 9-x-y, backport
