Repository electron/electron, pull requests merged in 2020-05, with the labels that each got.

#23298 docs: update autoUpdater tutorial API
  docs/tutorial/updates.md
Labels: documentation :notebook:

#23371 chore: remove unused ELECTRON_GET_CONTENT_SCRIPTS ipc handler
  lib/browser/rpc-server.js
  lib/sandboxed_renderer/init.js
Labels: new-pr 🌱

#23342 fix: ensure guest-embedder map is updated when webview is removed
  lib/browser/guest-view-manager.js
  lib/renderer/web-view/guest-view-internal.ts
  lib/renderer/web-view/web-view-element.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23271 fix: fetch fresh frame_host reference on use to avoid holding destroyed references
  shell/browser/network_hints_handler_impl.cc
  shell/browser/network_hints_handler_impl.h
Labels: target/8-x-y, target/9-x-y

#23364 refactor: make passing empty template no-op in setMenu
  lib/browser/api/menu-item.js
  lib/browser/api/menu.js
  shell/browser/api/electron_api_top_level_window.cc
  spec-main/api-menu-spec.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23398 fix: ensure guest-embedder map is updated when webview is removed
  lib/browser/guest-view-manager.js
  lib/renderer/web-view/guest-view-internal.ts
  lib/renderer/web-view/web-view-element.ts
Labels: 7-2-x, backport

#23397 fix: ensure guest-embedder map is updated when webview is removed
  lib/browser/guest-view-manager.js
  lib/renderer/web-view/guest-view-internal.ts
  lib/renderer/web-view/web-view-element.ts
Labels: 8-x-y, backport

#23396 fix: fetch fresh frame_host reference on use to avoid holding destroyed references
  shell/browser/network_hints_handler_impl.cc
  shell/browser/network_hints_handler_impl.h
Labels: 8-x-y, backport

#23401 refactor: make passing empty template no-op in setMenu
  shell/browser/api/electron_api_top_level_window.cc
  spec-main/api-menu-spec.ts
Labels: 9-x-y, backport

#23404 fix: guard pdf behind correct buildflags
  shell/renderer/renderer_client_base.cc
Labels: new-pr 🌱, target/9-x-y

#23405 fix: respect system language preferences on Windows & macOS
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/common/language_util.h
  shell/common/language_util_linux.cc
  shell/common/language_util_mac.mm
  shell/common/language_util_win.cc
  spec-main/chromium-spec.ts
Labels: 9-x-y, backport

#23403 refactor: make passing empty template no-op in setMenu
  shell/browser/api/atom_api_top_level_window.cc
  spec-main/api-menu-spec.ts
Labels: 7-2-x, backport

#23402 refactor: make passing empty template no-op in setMenu
  shell/browser/api/electron_api_top_level_window.cc
  spec-main/api-menu-spec.ts
Labels: 8-x-y, backport

#23408 chore: remove redundant release note items.
  script/release/notes/index.js
  script/release/notes/notes.js
Labels: 9-x-y, backport

#23407 fix: respect system language preferences on Windows & macOS
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/common/language_util.h
  shell/common/language_util_linux.cc
  shell/common/language_util_mac.mm
  shell/common/language_util_win.cc
  spec-main/chromium-spec.ts
Labels: 8-x-y, backport

#23409 fix: multiple extension filters on macOS
  shell/browser/ui/file_dialog_mac.mm
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23431 chore: cherry-pick b69991a9b701 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-b69991a9b701.patch
Labels: 7-2-x, backport-check-skip, new-pr 🌱

#23447 feat: add force option to app.focus()
  docs/api/app.md
  shell/browser/browser.h
  shell/browser/browser_linux.cc
  shell/browser/browser_mac.mm
  shell/browser/browser_win.cc
Labels: 9-x-y, backport, new-pr 🌱

#23459 style: use build/include_directory for NOLINT
  atom/app/atom_content_client.cc
  atom/app/uv_task_runner.h
  atom/browser/javascript_environment.h
  atom/common/api/electron_bindings.h
  atom/common/atom_command_line.cc
  atom/common/node_bindings.h
  atom/renderer/renderer_client_base.h
Labels: 6-1-x, backport, fast-track 🚅

#23432 chore: cherry-pick b69991a9b701 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-b69991a9b701.patch
Labels: 6-1-x, backport-check-skip

#23456 chore: cherry-pick 686d1bfbcb8f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-686d1bfbcb8f.patch
Labels: 8-x-y, backport-check-skip, new-pr 🌱

#23457 chore: cherry-pick 686d1bfbcb8f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-686d1bfbcb8f.patch
Labels: 7-2-x, backport-check-skip, new-pr 🌱

#22772 fix: do not initialize extension system in in-memory sessions
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  spec-main/crash-spec.ts
  spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js
Labels: target/9-x-y

#23458 chore: cherry-pick 686d1bfbcb8f from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-686d1bfbcb8f.patch
Labels: 6-1-x, backport-check-skip, new-pr 🌱

#23462 chore: cherry-pick 826a4af58b3d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-826a4af58b3d.patch
Labels: 8-x-y, backport-check-skip, new-pr 🌱

#23473 chore: fix linting
  spec-main/crash-spec.ts
  spec-main/fixtures/crash-cases/early-in-memory-session-create/index.js
Labels: new-pr 🌱

#23463 chore: cherry-pick 826a4af58b3d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-826a4af58b3d.patch
Labels: 7-2-x, backport-check-skip, new-pr 🌱

#23464 chore: cherry-pick 826a4af58b3d from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-826a4af58b3d.patch
Labels: 6-1-x, backport-check-skip, new-pr 🌱

#23465 chore: cherry-pick 45b8c2bb07d2 from v8
  patches/v8/.patches
  patches/v8/merged_regexp_reserve_space_for_all_registers_in_interpreter.patch
Labels: 8-x-y, backport-check-skip, new-pr 🌱

#23489 test: fix conditions for some tests
  spec-main/api-browser-window-spec.ts
  spec-main/node-spec.ts
  spec/webview-spec.js
Labels: target/9-x-y

#23466 chore: cherry-pick 45b8c2bb07d2 from v8
  patches/v8/.patches
  patches/v8/merged_regexp_reserve_space_for_all_registers_in_interpreter.patch
Labels: 7-2-x, backport-check-skip

#23434 docs: document supported extensions apis
  docs/README.md
  docs/api/extensions.md
  filenames.auto.gni
Labels: 9-x-y, backport, documentation :notebook:

#23494 test: fix conditions for some tests (#23489)
  spec-main/api-browser-window-spec.ts
  spec/webview-spec.js
Labels: 9-x-y, backport

#23415 test: skip "handles Promise timeouts correctly" when ELECTRON_RUN_AS_NODE is disabled
  spec-main/node-spec.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23474 docs: add document on contextIsolation
  docs/tutorial/context-isolation.md
  docs/tutorial/security.md
Labels: documentation :notebook:

#23096 feat: add new render-process-gone event
  docs/api/web-contents.md
  lib/browser/guest-view-manager.js
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: api-review/approved ✅, semver/minor

#23501 chore: add TRACE calls for heavy ctx bridge methods
  shell/renderer/api/electron_api_context_bridge.cc
Labels: new-pr 🌱

#23499 build: fix building with enable_remote_module = false
  BUILD.gn
  filenames.gni
  shell/common/api/electron_api_v8_util.cc
  shell/common/api/object_life_monitor.cc
  shell/common/api/object_life_monitor.h
  shell/common/api/remote/remote_callback_freer.h
  shell/common/api/remote/remote_object_freer.h
  shell/renderer/api/context_bridge/object_cache.cc
  shell/renderer/api/context_bridge/render_frame_function_store.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: target/9-x-y

#23495 fix: do not destroy thread in UI thread
  filenames.gni
  shell/browser/ui/file_dialog_win.cc
  shell/browser/ui/message_box_win.cc
  shell/browser/ui/win/dialog_thread.cc
  shell/browser/ui/win/dialog_thread.h
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23505 chore: cherry-pick 38990b7d56e6 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-38990b7d56e6.patch
Labels: 6-1-x, backport-check-skip, new-pr 🌱

#23536 build: use correct v8_context_snapshot_generator in mksnapshot zip
  .circleci/config.yml
  BUILD.gn
Labels: fast-track 🚅, target/6-1-x, target/7-2-x, target/8-x-y, target/9-x-y

#23419 fix: run Node.js at-exit callbacks in renderer proc
  shell/renderer/electron_renderer_client.cc
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23504 chore: cherry-pick 38990b7d56e6 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-38990b7d56e6.patch
Labels: 8-x-y, backport-check-skip

#23503 chore: cherry-pick 38990b7d56e6 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-38990b7d56e6.patch
Labels: 7-2-x, backport-check-skip

#23512 fix: leave behind the unmodified XDG_CURRENT_DESKTOP variable
  docs/api/environment-variables.md
  lib/browser/init.ts
Labels: target/7-2-x, target/8-x-y, target/9-x-y

#23519 chore: cherry-pick 67864c214770 from Chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-67864c214770.patch
Labels: 6-1-x, backport-check-skip

#23518 chore: cherry-pick 67864c214770 from Chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-67864c214770.patch
Labels: 7-2-x, backport-check-skip

#23517 chore: cherry-pick 67864c214770 from Chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-67864c214770.patch
Labels: 8-x-y, backport-check-skip

#23516 chore: cherry-pick e89fe66d0473 from usrsctp
  patches/common/config.json
  patches/common/usrsctp/.patches
  patches/common/usrsctp/cherry-pick-e89fe66d0473.patch
Labels: 6-1-x, backport-check-skip

#23515 chore: cherry-pick e89fe66d0473 from usrsctp
  patches/config.json
  patches/usrsctp/.patches
  patches/usrsctp/cherry-pick-e89fe66d0473.patch
Labels: 7-2-x, backport-check-skip

#23514 chore: cherry-pick e89fe66d0473 from usrsctp
  patches/config.json
  patches/usrsctp/.patches
  patches/usrsctp/cherry-pick-e89fe66d0473.patch
Labels: 8-x-y, backport-check-skip

#23546 fix: expose v8util.createIDWeakMap() regardless of enable_remote_module
  build/webpack/webpack.config.base.js
  shell/common/api/electron_api_v8_util.cc
Labels: fast-track 🚅

#23556 fix: expose v8util.createIDWeakMap() regardless of enable_remote_module
  shell/common/api/electron_api_v8_util.cc
Labels: 9-x-y, backport

#23551 fix: do not destroy thread in UI thread
  filenames.gni
  shell/browser/ui/file_dialog_win.cc
  shell/browser/ui/message_box_win.cc
  shell/browser/ui/win/dialog_thread.cc
  shell/browser/ui/win/dialog_thread.h
Labels: 7-2-x, backport

#23549 perf: use type-utils for desktopCapturer.getSources() result serialization
  lib/browser/desktop-capturer.ts
  lib/browser/rpc-server.js
  lib/renderer/api/desktop-capturer.ts
  shell/browser/api/electron_api_desktop_capturer.cc
  typings/internal-electron.d.ts
Labels: new-pr 🌱

#23557 test: skip remote module related tests when enable_remote_module = false
  spec-main/api-browser-window-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/fixtures/module/delete-buffer.js
  spec-main/webview-spec.ts
Labels: target/9-x-y

#23537 fix: generate symbols for the correct crashpad handler binary
  BUILD.gn
Labels: target/9-x-y

#23538 fix: exclude crashpad_handler binary on linux
  build/zip.py
  script/lib/config.py
  script/zip_manifests/dist_zip.linux.arm.manifest
  script/zip_manifests/dist_zip.linux.arm64.manifest
  script/zip_manifests/dist_zip.linux.x64.manifest
  script/zip_manifests/dist_zip.linux.x86.manifest
Labels: target/9-x-y

#23571 test: remove usage of the remote module from tests
  spec-main/fixtures/api/close-beforeunload-undefined.html
Labels: target/9-x-y

#23526 chore: cherry-pick 86c02c5dcd37 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-86c02c5dcd37.patch
Labels: 6-1-x, backport-check-skip

#23527 chore: cherry-pick 86c02c5dcd37 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-86c02c5dcd37.patch
Labels: 7-2-x, backport-check-skip

#23528 chore: cherry-pick 86c02c5dcd37 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-86c02c5dcd37.patch
Labels: 8-x-y, backport-check-skip

#23564 fix: run Node.js at-exit callbacks in renderer proc
  shell/renderer/electron_renderer_client.cc
Labels: 8-x-y, backport

#23561 chore: cherry-pick 1288aa12369e from angle
  patches/angle/.patches
  patches/angle/update_the_active_texture_cache_before_changing_the_texture_binding.patch
  patches/config.json
Labels: 8-x-y, backport-check-skip

#23531 chore: cherry-pick 7101418f85a0 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-7101418f85a0.patch
Labels: 7-2-x, backport-check-skip

#23532 chore: cherry-pick 7101418f85a0 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-7101418f85a0.patch
Labels: 8-x-y, backport-check-skip

#23562 chore: cherry-pick 1288aa12369e from angle
  patches/angle/.patches
  patches/angle/update_the_active_texture_cache_before_changing_the_texture_binding.patch
Labels: 7-2-x, backport-check-skip

#23566 fix: run Node.js at-exit callbacks in renderer proc
  shell/renderer/atom_renderer_client.cc
Labels: 7-2-x, backport

#23585 build: remove unused header from a patch
  patches/chromium/command-ismediakey.patch
Labels: target/8-x-y, target/9-x-y

#23530 chore: cherry-pick 7101418f85a0 from chromium
  patches/common/chromium/.patches
  patches/common/chromium/cherry-pick-7101418f85a0.patch
Labels: 6-1-x, backport-check-skip

#23593 chore: look harder for a commit's pull request.
  script/release/notes/notes.js
Labels: new-pr 🌱, target/9-x-y

#23582 feat: add enableWebSQL webpreference
  docs/api/browser-window.md
  filenames.auto.gni
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  shell/browser/web_contents_preferences.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/content_settings_observer.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/storage/web_sql.html
Labels: 7-2-x, backport, semver/minor

#23574 feat: add force option to app.focus()
  docs/api/app.md
  shell/browser/browser.h
  shell/browser/browser_linux.cc
  shell/browser/browser_mac.mm
  shell/browser/browser_win.cc
Labels: 8-x-y, backport, backport-approved/8-x-y, semver/minor

#23581 feat: add enableWebSQL webpreference
  docs/api/browser-window.md
  lib/browser/guest-view-manager.js
  lib/browser/guest-window-manager.js
  shell/browser/web_contents_preferences.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/content_settings_observer.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/storage/web_sql.html
Labels: 8-x-y, backport, semver/minor

#23595 chore: align crash patch with upstream
  patches/chromium/.patches
  patches/chromium/breakpad_disable_upload_compression.patch
  patches/chromium/breakpad_treat_node_processes_as_browser_processes.patch
  patches/chromium/crash_allow_embedder_to_set_crash_upload_url.patch
  patches/chromium/crash_allow_setting_more_options.patch
  shell/app/electron_crash_reporter_client.cc
  shell/app/electron_crash_reporter_client.h
Labels: fast-track 🚅

#23592 refactor: remove the RenderFrameFunctionStore and use privates to memory manage
  filenames.gni
  lib/renderer/api/context-bridge.ts
  lib/sandboxed_renderer/init.js
  shell/common/api/electron_api_v8_util.cc
  shell/common/gin_helper/callback.h
  shell/renderer/api/context_bridge/render_frame_function_store.cc
  shell/renderer/api/context_bridge/render_frame_function_store.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  spec-main/api-context-bridge-spec.ts
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: target/8-x-y, target/9-x-y

#23617 refactor: remove the RenderFrameFunctionStore and use privates to memory manage
  filenames.gni
  lib/renderer/api/context-bridge.ts
  lib/sandboxed_renderer/init.js
  shell/common/api/electron_api_v8_util.cc
  shell/common/gin_helper/callback.h
  shell/renderer/api/context_bridge/render_frame_function_store.cc
  shell/renderer/api/context_bridge/render_frame_function_store.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  spec-main/api-context-bridge-spec.ts
  typings/internal-ambient.d.ts
Labels: 9-x-y, backport

#23612 refactor: remove the RenderFrameFunctionStore and use privates to memory manage
  filenames.gni
  lib/renderer/api/context-bridge.ts
  lib/sandboxed_renderer/init.js
  shell/common/api/electron_api_v8_util.cc
  shell/renderer/api/context_bridge/render_frame_function_store.cc
  shell/renderer/api/context_bridge/render_frame_function_store.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  spec-main/api-context-bridge-spec.ts
  typings/internal-ambient.d.ts
Labels: 8-x-y, backport

#23607 test: fix conditions for some tests
  spec-main/api-browser-window-spec.ts
  spec/webview-spec.js
Labels: 8-x-y, backport

#23563 chore: cherry-pick 1288aa12369e from angle
  patches/common/angle/.patches
  patches/common/angle/update_the_active_texture_cache_before_changing_the_texture_binding.patch
  patches/common/config.json
Labels: 6-1-x, backport-check-skip

#23589 refactor: improve MoveItemToTrash error description
  shell/common/platform_util_mac.mm
Labels: target/8-x-y, target/9-x-y

#23543 fix: nativeImage remote serialization
  lib/browser/remote/server.ts
  lib/renderer/api/remote.js
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  spec-main/api-remote-spec.ts
Labels: target/7-3-x, target/8-x-y, target/9-x-y

#23634 build: save mksnapshot args in Windows mksnapshot.zip
  appveyor.yml
Labels: target/9-x-y

#23643 fix: eat octokit 422 errs when scraping commit PRs
  script/release/notes/notes.js
Labels: backport-check-skip, fast-track 🚅

#23649 refactor: revert release notes changes
  script/release/notes/notes.js
Labels: backport-check-skip, fast-track 🚅

#23496 build: allow use of BUILDFLAG directives from within JS code
  .eslintrc.json
  build/webpack/webpack.config.base.js
  build/webpack/webpack.gni
  filenames.auto.gni
  lib/browser/api/module-keys.js
  lib/browser/api/module-list.ts
  lib/browser/api/module-names.ts
  lib/browser/api/web-contents.js
  lib/browser/init.ts
  lib/browser/rpc-server.js
  lib/common/dummy.js
  lib/renderer/api/module-list.ts
  lib/renderer/api/remote.js
  lib/renderer/init.ts
  lib/sandboxed_renderer/api/module-list.ts
  lib/sandboxed_renderer/init.js
  shell/common/api/electron_api_v8_util.cc
  typings/internal-ambient.d.ts
Labels: 9-x-y, backport

#23631 fix: make sure hunspell dict file is not destroyed in UI thread
  patches/chromium/.patches
  patches/chromium/fix_hunspell_crash.patch
Labels: target/7-3-x, target/8-x-y, target/9-x-y

#23651 docs: remove note about experimental nature of sandbox
  docs/api/sandbox-option.md
Labels: new-pr 🌱

#23667 fix: wrap EmitWarning with HandleScope
  shell/common/process_util.cc
Labels: new-pr 🌱

#23386 fix: Don't ignore the referer header in net.request
  lib/browser/api/net.ts
  shell/browser/api/electron_api_url_loader.cc
  spec-main/api-net-spec.ts
  typings/internal-ambient.d.ts
Labels: api-review/approved ✅

#23675 test: call "expect()" on a correct call stack
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-ipc-spec.ts
Labels: target/7-3-x, target/8-x-y, target/9-x-y

#23548 feat: expose the desktopCapturer module in the main process
  build/webpack/webpack.config.base.js
  docs/api/desktop-capturer.md
  filenames.auto.gni
  lib/browser/api/desktop-capturer.ts
  lib/browser/api/module-list.ts
  lib/browser/api/module-names.ts
  lib/browser/desktop-capturer.ts
  lib/browser/rpc-server.js
  lib/renderer/api/desktop-capturer.ts
  spec-main/api-desktop-capturer-spec.ts
Labels: api-review/approved ✅

#23685 fix: Don't ignore the referer header in net.request
  lib/browser/api/net.js
  shell/browser/api/electron_api_url_loader.cc
  spec-main/api-net-spec.ts
Labels: 9-x-y, backport

#23671 docs: document optional scaleFactor param to nativeImage fns
  docs/api/native-image.md
Labels: documentation :notebook:

#23689 fix: don't run environment bootstrapper
  patches/node/.patches
  patches/node/build_add_gn_build_files.patch
  patches/node/chore_split_createenvironment_into_createenvironment_and.patch
  patches/node/fix_don_t_preparemainexecution_twice.patch
  script/node-disabled-tests.json
  shell/app/node_main.cc
  shell/browser/electron_browser_main_parts.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: 9-x-y, backport

#23696 test: call "expect()" on a correct call stack
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-ipc-spec.ts
Labels: 9-x-y, backport

#23695 test: multiple processes may crash in crashReporter test
  spec-main/api-crash-reporter-spec.ts
Labels: target/9-x-y

#20678 feat: Add Secure Keyboard Entry APIs in macOS
  docs/api/app.md
  shell/browser/api/electron_api_app.cc
  shell/browser/browser.h
  shell/browser/browser_mac.mm
  spec-main/api-app-spec.ts
Labels: api-review/approved ✅

#23653 docs: errors in isolated world are not dispatched to foreign worlds
  docs/api/web-frame.md
Labels: target/7-3-x, target/8-x-y, target/9-x-y

#23709 fix: support 10-x-y in the release notes generator
  script/release/notes/index.js
Labels: fast-track 🚅, target/10-x-y

#23687 fix: trigger about panel for about role on win
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.js
Labels: target/7-3-x, target/8-x-y, target/9-x-y

#23697 test: call "expect()" on a correct call stack
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-ipc-spec.ts
Labels: 8-x-y, backport

#23678 fix: read GTK dark theme setting on Linux
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
Labels: target/7-3-x, target/8-x-y, target/9-x-y

#23688 fix: Don't ignore the referer header in net.request
  lib/browser/api/net.js
  shell/browser/api/electron_api_url_loader.cc
  spec-main/api-net-spec.ts
Labels: 8-x-y, backport

#23716 chore: remove unused isolated-world-args
  lib/renderer/init.ts
  lib/sandboxed_renderer/init.js
Labels: new-pr 🌱

#23747 chore: cherry-pick d4ddf645c3ca from chromium
  patches/v8/.patches
  patches/v8/cherry-pick-d4ddf645c3ca.patch
  patches/v8/turn_some_dchecks_into_checks_in_schedule_methods.patch
Labels: 8-x-y, backport-check-skip, new-pr 🌱

#23698 test: call "expect()" on a correct call stack
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-ipc-spec.ts
Labels: 7-3-x, backport

#23748 chore: cherry-pick d4ddf645c3ca from chromium
  patches/v8/.patches
  patches/v8/cherry-pick-d4ddf645c3ca.patch
  patches/v8/turn_some_dchecks_into_checks_in_schedule_methods.patch
Labels: 7-3-x, backport-check-skip, new-pr 🌱

#23699 test: fix flaky beforeunload tests
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/common/api/api.mojom
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_api_service_impl.h
  spec-main/api-browser-window-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/fixtures/api/beforeunload-false-prevent3.html
  spec-main/fixtures/api/close-beforeunload-empty-string.html
  spec-main/fixtures/api/close-beforeunload-false.html
  spec-main/fixtures/api/close-beforeunload-undefined.html
  spec/fixtures/api/beforeunload-false.html
Labels: target/10-x-y

#23727 fix: trigger activate event when app is activated via app switcher
  shell/browser/mac/electron_application_delegate.mm
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#22701 feat: add desktopCapturer.getMediaSourceIdForWebContents() to get stream source id from web contents
  docs/api/desktop-capturer.md
  lib/browser/desktop-capturer.ts
  lib/browser/rpc-server.js
  lib/renderer/api/desktop-capturer.ts
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_desktop_capturer.h
  spec-main/api-desktop-capturer-spec.ts
  spec/ts-smoke/electron/renderer.ts
  typings/internal-ambient.d.ts
Labels: api-review/approved ✅

#23775 fix: trigger activate event when app is activated via app switcher
  shell/browser/mac/atom_application_delegate.mm
Labels: 7-3-x, backport

#23785 fix: make process.windowsStore work reliably
  shell/common/application_info_win.cc
Labels: new-pr 🌱, target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#23776 fix: asynchronous URL loading in BW Proxy
  docs/api/web-contents.md
  lib/renderer/window-setup.ts
  spec-main/api-browser-window-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23778 fix: weakly reference MenuModel from MenuController
  shell/browser/ui/cocoa/electron_menu_controller.h
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/browser/ui/electron_menu_model.h
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23779 fix: only bezel frameless windows
  shell/browser/native_window_mac.mm
Labels: target/10-x-y, target/9-x-y

#23774 test: refactor how spec files are collected
  spec-main/index.js
  spec/static/get-files.js
  spec/static/index.html
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#23821 chore: Revert "fix: trigger activate event when app is activated via app switcher"
  shell/browser/mac/electron_application_delegate.mm
Labels: backport-check-skip, fast-track 🚅

#23819 chore: Revert "fix: trigger activate event when app is activated via app switcher"
  shell/browser/mac/electron_application_delegate.mm
Labels: fast-track 🚅

#23822 chore: Revert "fix: trigger activate event when app is activated via app switcher"
  shell/browser/mac/atom_application_delegate.mm
Labels: backport-check-skip, fast-track 🚅

#23782 fix: volume key globalShortcut registration
  patches/chromium/command-ismediakey.patch
  shell/browser/api/electron_api_global_shortcut.cc
  spec-main/api-global-shortcut-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23820 chore: Revert "fix: trigger activate event when app is activated via app switcher"
  shell/browser/mac/electron_application_delegate.mm
Labels: fast-track 🚅

#23818 chore: Revert "fix: trigger activate event when app is activated via app switcher"
  shell/browser/mac/electron_application_delegate.mm
Labels: fast-track 🚅

#23788 chore: cherry-pick d795ac1209c8 and 919dd0c1244a from chromium
  patches/chromium/.patches
  patches/chromium/avoid_nullptr_dereference_in_rtcpeerconnectionhandler.patch
  patches/chromium/reland_onstate_handler_is_allowed_to_close_a_peerconnection.patch
Labels: 8-x-y, backport-check-skip

#23814 test: refactor how spec files are collected
  spec-main/index.js
  spec/static/get-files.js
  spec/static/index.html
Labels: 9-x-y, backport

#23815 test: refactor how spec files are collected
  spec-main/index.js
  spec/static/get-files.js
  spec/static/index.html
Labels: 8-x-y, backport

#23759 fix: ensure nativeImage serialization main->renderer
  lib/browser/remote/server.ts
  lib/renderer/api/remote.js
  spec-main/api-remote-spec.ts
Labels: in-flight/10-x-y, in-flight/8-x-y, in-flight/9-x-y

#23816 test: refactor how spec files are collected
  spec-main/index.js
  spec/static/get-files.js
  spec/static/index.html
Labels: 7-3-x, backport

#23794 fix: ensure nativeImage serialization main->renderer
  lib/browser/remote/server.ts
  lib/common/type-utils.ts
  lib/renderer/api/remote.js
  spec-main/api-remote-spec.ts
Labels: 10-x-y, backport

#23796 fix: nativeImage remote serialization
  lib/browser/remote/server.ts
  lib/common/type-utils.ts
  lib/renderer/api/remote.js
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  spec-main/api-remote-spec.ts
Labels: 9-x-y, backport

#23835 fix: use system installed objcopy to copy debug symbols
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/util.py
Labels: fast-track 🚅

#23802 docs: remove upgrading-node.md
  docs/development/README.md
  docs/development/upgrading-node.md
Labels: documentation :notebook:

#23844 chore: cherry-pick d3fc0ed4452c from chromium
  patches/chromium/.patches
  patches/chromium/introduce_a_mutex_for_the_rendering_loop_in_baseaudiocontext.patch
Labels: 7-3-x, backport-check-skip
