Repository electron/electron, pull requests merged in 2020-01, with the labels that each got.

#21665 docs: fix typos in security.md
  docs/tutorial/security.md
Labels: new-pr 🌱

#21643 refactor: throw an error for getLastCrashReport if crashReporter not started
  lib/common/crash-reporter.js
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21416 fix: load window-setup in sandboxed renderer
  filenames.auto.gni
  lib/browser/guest-window-manager.js
  lib/browser/rpc-server.js
  lib/renderer/window-setup.ts
  lib/sandboxed_renderer/init.js
  shell/renderer/atom_sandboxed_renderer_client.cc
  spec-main/chromium-spec.ts
Labels: in-flight/8-x-y, target/6-1-x, target/7-1-x

#20478 docs: initial document for comparing web embeds
  docs/README.md
  docs/tutorial/web-embeds.md
Labels: documentation :notebook:

#21709 fix: Notification crash in destructor on app quit
  shell/browser/api/atom_api_notification.cc
Labels: new-pr 🌱, target/6-1-x, target/7-1-x, target/8-x-y

#21704 fix: don't unnecessarily copy draggable regions
  shell/browser/api/atom_api_browser_window_mac.mm
Labels: target/7-1-x, target/8-x-y

#21690 fix: MediaKey globalShortcuts not working on macOS
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  patches/common/chromium/command-ismediakey.patch
Labels: 6-1-x, backport

#21592 fix: avoid contextBridge double free on garbage collection
  shell/renderer/api/context_bridge/render_frame_context_bridge_store.cc
Labels: target/7-1-x, target/8-x-y

#21730 docs: responseHeaders should be Record<string, string[]>
  docs/api/web-request.md
Labels: target/7-1-x, target/8-x-y

#21668 fix: don't fallback to OpenFolderViaShell
  shell/common/platform_util_win.cc
Labels: target/7-1-x, target/8-x-y

#21585 fix: avoid white flash when foregrounding occluded windows
  shell/browser/api/atom_api_browser_window.cc
Labels: target/7-1-x, target/8-x-y

#21697 fix: load window-setup in sandboxed renderer
  atom/renderer/atom_sandboxed_renderer_client.cc
  filenames.auto.gni
  lib/browser/guest-window-manager.js
  lib/browser/rpc-server.js
  lib/renderer/window-setup.ts
  lib/sandboxed_renderer/init.js
Labels: 6-1-x, backport

#21696 fix: load window-setup in sandboxed renderer
  filenames.auto.gni
  lib/browser/guest-window-manager.js
  lib/browser/rpc-server.js
  lib/renderer/window-setup.ts
  lib/sandboxed_renderer/init.js
  shell/renderer/atom_sandboxed_renderer_client.cc
Labels: 7-1-x, backport

#21431 fix: load window-setup in sandboxed renderer
  filenames.auto.gni
  lib/browser/guest-window-manager.js
  lib/browser/rpc-server.js
  lib/renderer/window-setup.ts
  lib/sandboxed_renderer/init.js
  shell/renderer/atom_sandboxed_renderer_client.cc
  spec-main/chromium-spec.ts
Labels: 8-x-y, backport

#21574 fix: disable private macOS APIs in MAS build except for CAContext/CALayerHost (8-x-y)
  patches/chromium/.patches
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
Labels: 8-x-y, backport

#21733 fix: stream protocols not completing
  shell/browser/net/node_stream_loader.cc
  spec-main/api-protocol-spec.ts
Labels: target/7-1-x, target/8-x-y

#21757 fix: double-autorelease of NSImage
  shell/browser/native_window_mac.mm
Labels: new-pr 🌱

#21761 chore: update goma documentation
  docs/development/goma.md
Labels: new-pr 🌱

#21760 fix: memory leak in javascript generator functions
  patches/v8/.patches
  patches/v8/objects_fix_memory_leak_in_prototypeusers_add.patch
Labels: 8-x-y, backport, target/6-1-x, target/7-1-x

#21762 docs: Little fix in Goma docs
  docs/development/goma.md
Labels: new-pr 🌱

#21552 fix: pass full response headers in net module
  lib/browser/api/net.js
  shell/browser/api/atom_api_url_loader.cc
  spec-main/api-net-spec.ts
Labels: target/7-1-x, target/8-x-y

#21773 fix: memory leak in javascript generator functions
  patches/v8/.patches
  patches/v8/objects_fix_memory_leak_in_prototypeusers_add.patch
Labels: 7-1-x, backport

#21774 fix: memory leak in javascript generator functions
  patches/common/v8/.patches
  patches/common/v8/objects_fix_memory_leak_in_prototypeusers_add.patch
Labels: 6-1-x, backport

#21775 docs: ignore_locks not break_repo_locks
  docs/development/build-instructions-gn.md
Labels: documentation :notebook:, new-pr 🌱

#21779 feat: [extensions] implement a couple of tabs APIs
  BUILD.gn
  chromium_src/BUILD.gn
  filenames.gni
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/api/tabs/tabs_api.h
  shell/browser/extensions/atom_extensions_browser_client.cc
  shell/browser/extensions/electron_extensions_browser_api_provider.cc
  shell/browser/extensions/electron_extensions_browser_api_provider.h
  shell/browser/extensions/electron_messaging_delegate.cc
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/tabs.json
  shell/common/extensions/atom_extensions_api_provider.cc
  shell/renderer/extensions/atom_extensions_renderer_client.cc
  shell/renderer/extensions/electron_extensions_dispatcher_delegate.cc
  shell/renderer/extensions/electron_extensions_dispatcher_delegate.h
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/chrome-api/background.js
  spec-main/fixtures/extensions/chrome-api/manifest.json
Labels: new-pr 🌱

#21783 fix: printToPDF failing to generate PDF
  patches/chromium/printing.patch
  spec-main/api-web-contents-spec.ts
Labels: target/8-x-y

#21801 fix: npm download failed when define 'npm_config_platform=mas'
  npm/install.js
Labels: new-pr 🌱

#21813 fix: crash when restoring minimized hidden window
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21846 fix: call SetCanActivate in setFocusable
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱, target/6-1-x, target/7-1-x, target/8-x-y

#21838 fix: crash when doing redirect navigation with webRequest listener
  shell/browser/atom_browser_client.cc
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  spec-main/api-web-request-spec.ts
Labels: in-flight/8-x-y

#21841 fix: crash when doing redirect navigation with webRequest listener (8-x-y)
  shell/browser/atom_browser_client.cc
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  spec-main/api-web-request-spec.ts
Labels: 8-x-y, backport

#21776 refactor: try just using regular [Sync] for MessageSync
  lib/browser/api/browser-window.js
  shell/common/api/api.mojom
  shell/renderer/api/atom_api_renderer_ipc.cc
  spec-main/api-browser-window-spec.ts
Labels: 7-1-x, backport, fast-track 🚅

#21855 fix: call SetCanActivate in setFocusable
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: 7-1-x, backport

#21856 fix: call SetCanActivate in setFocusable
  atom/browser/native_window_views.cc
Labels: 6-1-x, backport

#21852 fix: Windows checkboxChecked edge case
  shell/browser/ui/message_box_win.cc
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21858 fix: some websites using WebComponents V0 not loading
  shell/browser/feature_list.cc
Labels: new-pr 🌱, target/8-x-y

#17584 docs: added info on bookmark return values for securityScopedBookmarks
  docs/api/dialog.md
Labels: documentation :notebook:, target/7-1-x, target/8-x-y

#21872 fix: font rendering with hi-dpi display transitions on Catalina
  patches/chromium/.patches
  patches/chromium/fix_hi-dpi_transitions_on_catalina.patch
Labels: 7-1-x, new-pr 🌱, target/6-1-x

#21889 fix: recursive printing crash
  patches/chromium/printing.patch
Labels: target/8-x-y

#21892 docs: sandbox is not experimental
  docs/api/browser-window.md
Labels: 7-1-x, 8-x-y

#21883 fix: menu not updating with Tray.setContextMenu
  shell/browser/ui/tray_icon_gtk.cc
Labels: target/8-x-y

#21898 docs: offscreen-rendering - missing word "is"
  docs/tutorial/offscreen-rendering.md
Labels: new-pr 🌱

#21893 fix: window.print() only working once
  patches/chromium/printing.patch
Labels: target/7-1-x, target/8-x-y

#21905 fix: recursive printing crash
  patches/chromium/printing.patch
Labels: 8-x-y, backport

#21911 fix: window.print() only working once
  patches/chromium/printing.patch
Labels: 7-1-x, backport

#21888 docs: clean up contextBridge API docs
  docs/api/context-bridge.md
Labels: documentation :notebook:, target/7-1-x, target/8-x-y

#21878 fix: font rendering with hi-dpi display transitions on Catalina
  patches/common/chromium/.patches
  patches/common/chromium/command-ismediakey.patch
  patches/common/chromium/fix_disabling_compositor_recycling.patch
  patches/common/chromium/fix_hi-dpi_transitions_on_catalina.patch
  patches/common/chromium/make_autocorrect_off_and_spellcheck_false_disable_touch_bar_typing.patch
  patches/common/chromium/mas_disable_custom_window_frame.patch
  patches/common/chromium/mas_disable_remote_accessibility.patch
  patches/common/chromium/mas_disable_remote_layer.patch
  patches/common/chromium/mas_disable_spi_file_type_mappings.patch
Labels: 6-1-x, backport

#21913 fix: window.print() only working once
  patches/common/chromium/printing.patch
Labels: 6-1-x, backport

#21918 chore: remove commented code in renderer_ipc
  shell/renderer/api/atom_api_renderer_ipc.cc
Labels: new-pr 🌱

#21908 fix: window.print() only working once
  patches/chromium/printing.patch
Labels: 8-x-y, backport

#21880 fix: About Panel credits should be dark mode aware
  docs/api/app.md
  shell/browser/browser_mac.mm
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21904 fix: ensure tray icon is the proper size on linux
  shell/browser/ui/tray_icon_gtk.cc
Labels: target/8-x-y

#21927 fix: use powerMonitor.on() only after app is ready
  lib/browser/api/power-monitor.ts
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21930 docs: fix node.lib download link
  docs/tutorial/windows-arm.md
Labels: new-pr 🌱

#21921 docs: fix links to SECURITY and CONTRIBUTING files
  docs/tutorial/support.md
Labels: documentation :notebook:, new-pr 🌱

#21923 docs: remove references to inaccessible team pages
  docs/development/pull-requests.md
Labels: documentation :notebook:, new-pr 🌱

#21870 docs: move breaking changes out of API folder
  docs/README.md
  docs/breaking-changes-ns.md
  docs/breaking-changes.md
  docs/tutorial/support.md
  filenames.auto.gni
Labels: documentation :notebook:

#21915 fix: spelling errors
  docs/api/native-theme.md
  lib/browser/navigation-controller.js
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/native_window_mac.mm
  spec-main/chromium-spec.ts
Labels: documentation :notebook:

#21952 fix: show module name in deprecation warning for context-aware modules
  patches/node/chore_prevent_warn_non_context-aware_native_modules_being_loaded.patch
Labels: new-pr 🌱, target/8-x-y

#21948 refactor: try just using regular [Sync] for MessageSync
  lib/browser/api/browser-window.js
  shell/common/api/api.mojom
  shell/renderer/api/atom_api_renderer_ipc.cc
  spec-main/api-browser-window-spec.ts
Labels: 8-x-y, backport

#21931 chore: fix linter errors in .mm files
  script/lint.js
  shell/browser/mac/atom_application_delegate.mm
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/atom_bundle_mover.mm
  shell/browser/ui/cocoa/atom_menu_controller.mm
  shell/browser/ui/cocoa/atom_touch_bar.mm
Labels: in-flight/7-1-x, in-flight/8-x-y

#21933 chore: fix linter errors in .mm files
  script/lint.js
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/atom_bundle_mover.mm
  shell/browser/ui/cocoa/atom_menu_controller.mm
  shell/browser/ui/cocoa/atom_touch_bar.mm
Labels: 8-x-y, backport

#21934 chore: fix linter errors in .mm files
  script/lint.js
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/atom_bundle_mover.mm
  shell/browser/ui/cocoa/atom_menu_controller.mm
  shell/browser/ui/cocoa/atom_touch_bar.mm
Labels: 7-1-x, backport

#21950 fix: compilation of native modules on windows with older msvc versions
  patches/v8/.patches
  patches/v8/fix_build_deprecated_attirbute_for_older_msvc_versions.patch
Labels: new-pr 🌱, target/8-x-y

#21961 fix: add executable to ChromeDriver's rpath for electron 8+
  patches/chromium/.patches
  patches/chromium/fix_add_executable_to_chromedriver_s_rpath_for_electron_8.patch
Labels: new-pr 🌱, target/8-x-y

#21955 fix: ensure web_contents is not nullptr in UpdateDraggableRegions
  shell/browser/api/atom_api_browser_window_mac.mm
Labels: new-pr 🌱, target/7-1-x, target/8-x-y

#21962 docs: fix missing docs for <webview>.print()
  docs/api/webview-tag.md
Labels: new-pr 🌱

#21960 fix: compilation of native modules on windows with older msvc versions
  patches/v8/.patches
  patches/v8/fix_build_deprecated_attirbute_for_older_msvc_versions.patch
Labels: 8-x-y, backport

#21958 fix: show module name in deprecation warning for context-aware modules
  patches/node/chore_prevent_warn_non_context-aware_native_modules_being_loaded.patch
Labels: 8-x-y, backport

#21966 fix: add executable to ChromeDriver's rpath for electron 8+
  patches/chromium/.patches
  patches/chromium/fix_add_executable_to_chromedriver_s_rpath_for_electron_8.patch
Labels: 8-x-y, backport

#21959 fix: use the new MediaPlayPause key listener for internal chrome logic
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  patches/chromium/.patches
  patches/chromium/command-ismediakey.patch
  patches/chromium/fix_use_the_new_mediaplaypause_key_listener_for_internal_chrome.patch
Labels: new-pr 🌱

#21946 fix: prevent print crash on bad deviceName
  docs/api/web-contents.md
  shell/browser/api/atom_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
Labels: target/6-1-x, target/7-1-x, target/8-x-y

#21969 fix: crash with icu when input locale is invalid
  patches/config.json
  patches/icu/.patches
  patches/icu/date_time_generator_default_locale.patch
  patches/icu/posix_util_invalid_locale.patch
  spec/fixtures/module/icu.js
  spec/node-spec.js
Labels: new-pr 🌱, target/6-1-x

#21976 fix: don't crash on invalid certs
  shell/browser/api/atom_api_app.cc
Labels: new-pr 🌱

#21981 chore: add safety checks to RepositionTrafficLights
  shell/browser/native_window_mac.mm
Labels: new-pr 🌱

#21985 fix: return path from netLog.stopLogging
  lib/browser/api/session.js
  spec-main/api-net-log-spec.ts
Labels: fast-track 🚅, target/7-1-x, target/8-x-y

#21956 fix: default printer if none is provided
  patches/chromium/printing.patch
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
Labels: target/7-1-x, target/8-x-y

#21895 feat: Exposing methods required by capturing a hidden webContents
  docs/api/web-contents.md
  shell/browser/api/atom_api_web_contents.cc
  shell/browser/api/atom_api_web_contents.h
Labels: 8-x-y, backport

#21990 feat: custom positioning for traffic light buttons
  docs/api/browser-window.md
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/atom_ns_window_delegate.mm
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: 8-x-y, backport, new-pr 🌱
