Repository electron/electron, pull requests merged in 2020-06, with the labels that each got.

#23842 feat: add V8CacheOptions webpreference
  docs/api/browser-window.md
  shell/browser/web_contents_preferences.cc
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23864 build: fix for "enable_desktop_capturer = false"
  build/webpack/webpack.config.base.js
  lib/common/dummy.ts
  package.json
  spec-main/api-desktop-capturer-spec.ts
  yarn.lock
Labels: target/10-x-y

#23843 fix: do not use CONTEXT_MENU flag for tray menu
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#23876 build: fix for "enable_desktop_capturer = false"
  build/webpack/webpack.config.base.js
  package.json
  spec-main/api-desktop-capturer-spec.ts
  yarn.lock
Labels: 10-x-y, backport

#23855 build: make electron renderer init scripts profilable
  build/webpack/run-compiler.js
  build/webpack/webpack.config.base.js
  build/webpack/webpack.config.renderer.js
  build/webpack/webpack.config.sandboxed_renderer.js
  build/webpack/webpack.gni
  shell/browser/electron_browser_client.cc
Labels: performance :checkered_flag:, target/10-x-y, target/9-x-y

#23857 fix: expose electron/common and electron/renderer modules in sandboxed preloads
  lib/sandboxed_renderer/init.ts
Labels: target/10-x-y

#23684 fix: add patch to prevent crash during frame swap with ctx isolation enabled
  patches/chromium/.patches
  patches/chromium/fix_swap_global_proxies_before_initializing_the_windows_proxies.patch
Labels: target/8-x-y, target/9-x-y

#23886 fix: do not use CONTEXT_MENU flag for tray menu
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: 8-x-y, backport, target/7-3-x

#23874 test: wait for beforeunload handler to be installed
  spec-main/api-browser-window-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/fixtures/api/beforeunload-empty-string.html
  spec-main/fixtures/api/beforeunload-false-prevent3.html
  spec-main/fixtures/api/beforeunload-false.html
  spec-main/fixtures/api/beforeunload-undefined.html
  spec-main/fixtures/api/close-beforeunload-false.html
Labels: target/10-x-y

#23787 fix: Make the `--disable-color-correct-rendering` switch work again
  patches/chromium/disable_color_correct_rendering.patch
Labels: in-flight/8-x-y, target/10-x-y, target/9-x-y

#23856 perf: lazily load some modules in sandbox mode
  lib/sandboxed_renderer/init.ts
Labels: performance :checkered_flag:

#23902 chore: update patches for master conflicts
  patches/chromium/disable_color_correct_rendering.patch
Labels: fast-track 🚅, new-pr 🌱

#23889 chore: note quiet period in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new-pr 🌱

#23883 docs: move protocol-ns to protocol.md
  docs/api/protocol-ns.md
  docs/api/protocol.md
  docs/api/structures/protocol-request.md
  filenames.auto.gni
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  spec-main/api-browser-window-spec.ts
  spec-main/api-protocol-spec.ts
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/chromium-spec.ts
  spec-main/webview-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23827 fix: Make the `--disable-color-correct-rendering` switch work again (8-x-y)
  patches/chromium/disable_color_correct_rendering.patch
Labels: 8-x-y, backport

#23888 docs: default of allowRendererProcessReuse is true
  docs/api/app.md
Labels: new-pr 🌱, target/10-x-y, target/9-x-y

#23846 fix: default to NTLM v2 in the network service for POSIX platforms
  docs/api/command-line-switches.md
  patches/chromium/.patches
  patches/chromium/fix_default_to_ntlm_v2_in_network_service.patch
  shell/browser/api/electron_api_session.cc
  shell/browser/net/system_network_context_manager.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#23903 fix: correctly support the --inspect-brk-node flag
  shell/browser/node_debugger.cc
Labels: new-pr 🌱, target/10-x-y, target/8-x-y, target/9-x-y

#23674 fix: restore original GTK/appindicator implementation of tray icons
  BUILD.gn
  shell/browser/ui/gtk/app_indicator_icon.cc
  shell/browser/ui/gtk/app_indicator_icon.h
  shell/browser/ui/gtk/app_indicator_icon_menu.cc
  shell/browser/ui/gtk/app_indicator_icon_menu.h
  shell/browser/ui/gtk/gtk_status_icon.cc
  shell/browser/ui/gtk/gtk_status_icon.h
  shell/browser/ui/gtk/menu_util.cc
  shell/browser/ui/gtk/menu_util.h
  shell/browser/ui/gtk/status_icon.cc
  shell/browser/ui/gtk/status_icon.h
  shell/browser/ui/tray_icon_gtk.cc
  shell/browser/ui/tray_icon_gtk.h
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23901 test: load page with some content when testing extension
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/chrome-runtime/manifest.json
Labels: target/10-x-y

#23924 fix: don't run environment bootstrapper
  patches/node/.patches
  patches/node/build_add_gn_build_files.patch
  patches/node/chore_split_createenvironment_into_createenvironment_and.patch
  patches/node/fix_call_initializecontextruntime_in_initializecontext.patch
  patches/node/fix_don_t_preparemainexecution_twice.patch
  shell/app/node_main.cc
  shell/browser/electron_browser_main_parts.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: 8-x-y, backport

#23890 fix: compensate for lazy-loaded circular deps
  patches/node/build_modify_js2c_py_to_allow_injection_of_original-fs_and_custom_embedder_js.patch
  spec/asar-spec.js
  spec/fixtures/test.asar/deleteme/a.asar
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23930 fix: destroy GetSize callback at last
  shell/browser/api/electron_api_url_loader.cc
Labels: new-pr 🌱, target/10-x-y

#23949 test: skip 'handles Promise timeouts correctly' when ELECTRON_RUN_AS_…
  spec/node-spec.js
Labels: 8-x-y, backport

#23935 fix: default to NTLM v2 in the network service for POSIX platforms
  docs/api/chrome-command-line-switches.md
  patches/chromium/.patches
  patches/chromium/fix_default_to_ntlm_v2_in_network_service.patch
  shell/browser/api/atom_api_session.cc
  shell/browser/net/system_network_context_manager.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: 7-3-x, backport

#23933 fix: default to NTLM v2 in the network service for POSIX platforms
  docs/api/command-line-switches.md
  patches/chromium/.patches
  patches/chromium/fix_default_to_ntlm_v2_in_network_service.patch
  shell/browser/api/electron_api_session.cc
  shell/browser/net/system_network_context_manager.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: 8-x-y, backport

#23948 fix: volume key globalShortcut registration
  patches/chromium/command-ismediakey.patch
  shell/browser/api/electron_api_global_shortcut.cc
  spec-main/api-global-shortcut-spec.ts
Labels: 8-x-y, backport

#23952 build: fix filenames autogen with new BUILDFLAG syntax
  build/webpack/webpack.config.base.js
Labels: target/10-x-y, target/9-x-y

#23947 fix: handle asynchronous URL loading in bw proxy
  docs/api/web-contents.md
  lib/renderer/window-setup.ts
  spec-main/api-browser-window-spec.ts
Labels: 8-x-y, backport

#23929 docs: remove confusing notes on Node
  docs/tutorial/first-app.md
Labels: documentation :notebook:

#23944 fix: use acceptLanguages argument in session.setUserAgent()
  shell/browser/api/electron_api_session.cc
  spec-main/api-session-spec.ts
Labels: new-pr 🌱, target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#23936 fix: missing handlescopes in touch bar
  shell/browser/ui/cocoa/electron_touch_bar.mm
Labels: target/10-x-y

#23959 chore: update tracking bug for disable_unnecessary_ischromefirstrun_check.patch
  patches/chromium/disable_unnecessary_ischromefirstrun_check.patch
Labels: new-pr 🌱

#23917 fix: throw when using ipcRenderer after context released
  shell/renderer/api/electron_api_ipc_renderer.cc
  spec-main/api-ipc-renderer-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23965 fix: read GTK dark theme setting on Linux
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
Labels: 8-x-y, backport

#23966 fix: read GTK dark theme setting on Linux
  shell/browser/atom_browser_main_parts.cc
  shell/browser/atom_browser_main_parts.h
Labels: 7-3-x, backport

#23971 fix: add missing isComposing KeyboardEvent property
  docs/api/web-contents.md
  shell/common/gin_converters/content_converter.cc
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23934 fix: default to NTLM v2 in the network service for POSIX platforms
  build/webpack/webpack.config.base.js
  docs/api/command-line-switches.md
  package.json
  patches/chromium/.patches
  patches/chromium/fix_default_to_ntlm_v2_in_network_service.patch
  shell/browser/api/electron_api_session.cc
  shell/browser/net/system_network_context_manager.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec-main/api-desktop-capturer-spec.ts
  yarn.lock
Labels: 9-x-y, backport

#23984 fix: volume key globalShortcut deregistration
  patches/chromium/command-ismediakey.patch
Labels: target/10-x-y

#23978 fix: throw instead of crash when using ipcRenderer after context released (#23917)
  shell/renderer/api/electron_api_renderer_ipc.cc
  spec-main/api-ipc-renderer-spec.ts
Labels: 9-x-y, backport

#23909 docs: mention build-tools in the build instructions
  docs/development/build-instructions-gn.md
Labels: documentation :notebook:

#23956 fix: compensate for lazy-loaded circular deps
  patches/node/build_modify_js2c_py_to_allow_injection_of_original-fs_and_custom_embedder_js.patch
  spec/asar-spec.js
  spec/fixtures/test.asar/deleteme/a.asar
Labels: 9-x-y, backport

#23963 fix: use acceptLanguages argument in session.setUserAgent()
  shell/browser/api/electron_api_session.cc
  spec-main/api-session-spec.ts
Labels: 8-x-y, backport

#23964 fix: use acceptLanguages argument in session.setUserAgent()
  shell/browser/api/atom_api_session.cc
  spec-main/api-session-spec.js
Labels: 7-3-x, backport

#22955 fix: video/audio playing on custom stream protocols
  BUILD.gn
  docs/api/protocol.md
  docs/api/structures/custom-scheme.md
  patches/chromium/.patches
  patches/chromium/feat_add_streaming-protocol_registry_to_multibuffer_data_source.patch
  shell/browser/api/electron_api_protocol.cc
  shell/browser/electron_browser_client.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/renderer_client_base.cc
  spec-main/api-protocol-spec.ts
  spec-main/index.js
  spec-main/video-helpers.js
  spec/fixtures/pages/video.html
  spec/fixtures/video-source-image.webp
Labels: wip ⚒

#23955 fix: compensate for lazy-loaded circular deps
  patches/node/build_modify_js2c_py_to_allow_injection_of_original-fs_and_custom_embedder_js.patch
  spec/asar-spec.js
  spec/fixtures/test.asar/deleteme/a.asar
Labels: 8-x-y, backport

#24016 docs: errors in isolated world are not dispatched
  docs/api/web-frame.md
Labels: 8-x-y, backport

#23797 fix: nativeImage remote serialization
  lib/browser/remote/server.ts
  lib/common/type-utils.ts
  lib/renderer/api/remote.js
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  shell/common/gin_helper/function_template.h
  spec-main/api-remote-spec.ts
Labels: 8-x-y, backport

#24015 fix: add missing isComposing KeyboardEvent property
  docs/api/web-contents.md
  shell/common/native_mate_converters/blink_converter.cc
Labels: 8-x-y, backport

#23998 docs: update setAboutPanelOptions iconPath description
  docs/api/app.md
Labels: documentation :notebook:

#23953 chore: roll latest Node.js security release
  patches/node/.patches
  patches/node/deps_update_nghttp2_to_1_40_0.patch
  patches/node/deps_update_nghttp2_to_1_41_0.patch
  patches/node/http2_implement_support_for_max_settings_entries.patch
  patches/node/napi_fix_memory_corruption_vulnerability.patch
  patches/node/tls_emit_session_after_verifying_certificate.patch
Labels: 8-x-y, backport-check-skip

#24018 docs: errors in isolated world are not dispatched
  docs/api/web-frame.md
Labels: 7-3-x, backport

#24023 chore: use more inclusive language in a few places
  docs/api/structures/trace-config.md
  script/lint.js
  shell/browser/plugins/plugin_utils.cc
  shell/renderer/electron_renderer_pepper_host_factory.cc
Labels: new-pr 🌱

#23976 fix: Allow windows behind macOS elements if frame = false
  shell/browser/ui/cocoa/electron_ns_window.mm
  spec-main/api-browser-window-spec.ts
Labels: app/Slack, platform/macOS, target/10-x-y, target/9-x-y

#24030 fix: backport libuv patch for failure to load advapi32
  patches/node/.patches
  patches/node/win_use_rtlgenrandom_from_advapi32_dll_directly.patch
Labels: target/10-x-y, target/9-x-y

#24010 fix: Add .paks for media-internals and webrtc-internals pages
  electron_paks.gni
  spec-main/chromium-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24003 docs: fix explanation of darwin auto-quit prevention
  docs/tutorial/first-app.md
Labels: documentation :notebook:

#23997 fix: notify URLLoaderClient about redirect inside intercepted protocol (backport to 7-3-X)
  shell/browser/net/atom_url_loader_factory.cc
Labels: 7-3-x, backport

#23989 fix: assign session to remote webContents
  shell/browser/api/electron_api_web_contents.cc
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/persistent-background-page/background.js
  spec-main/fixtures/extensions/persistent-background-page/manifest.json
Labels: target/10-x-y, target/9-x-y

#24055 fix: allow IME insert zero length composition string
  patches/chromium/.patches
  patches/chromium/fix_allow_ime_to_insert_zero-length_composition_string.patch
Labels: 7-3-x, backport-check-skip, new-pr 🌱

#24021 fix: nativeImage remote serialization
  lib/browser/rpc-server.js
  lib/common/type-utils.ts
  lib/renderer/api/remote.js
  native_mate/native_mate/function_template.h
  shell/common/api/atom_api_native_image.cc
  shell/common/api/atom_api_native_image.h
  spec-main/api-remote-spec.ts
  spec-main/package.json
  spec-main/yarn.lock
Labels: 7-3-x, backport

#24065 fix: assign session to remote webContents
  shell/browser/api/electron_api_web_contents.cc
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/persistent-background-page/background.js
  spec-main/fixtures/extensions/persistent-background-page/manifest.json
Labels: 9-x-y, backport

#24063 fix: add .paks for media-internals and webrtc-internals pages
  electron_paks.gni
  spec-main/chromium-spec.ts
Labels: 8-x-y, backport

#24072 chore: update app module property support
  docs/api/app.md
  docs/api/modernization/property-updates.md
  lib/browser/api/app.ts
  shell/browser/api/electron_api_app.cc
  spec-main/api-app-spec.ts
Labels: 8-x-y, backport

#24075 chore: more modules to dual prop/fn support
  docs/api/download-item.md
  docs/api/native-image.md
  docs/api/system-preferences.md
  lib/browser/api/system-preferences.ts
  lib/common/api/native-image.js
  shell/browser/api/electron_api_system_preferences.cc
  shell/common/api/electron_api_native_image.cc
  spec-main/api-system-preferences-spec.ts
  spec/api-native-image-spec.js
Labels: 8-x-y, backport

#24074 chore: support props/fns for BrowserWindow
  docs/api/browser-window.md
  lib/browser/api/browser-window.js
  shell/browser/api/electron_api_top_level_window.cc
  spec-main/api-browser-window-spec.ts
Labels: 8-x-y, backport

#24071 chore: revert deprecated WebContents properties
  docs/api/web-contents.md
  lib/browser/api/web-contents.js
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-browser-window-spec.ts
  spec-main/api-web-contents-spec.ts
Labels: 8-x-y, backport

#24022 fix: correctly handle nexttick scheduling in stream reads
  shell/browser/net/node_stream_loader.cc
  shell/browser/net/node_stream_loader.h
  spec-main/api-protocol-spec.ts
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24054 refactor: remove renderer-side refcount in remote
  lib/browser/remote/objects-registry.ts
  lib/browser/remote/server.ts
  lib/renderer/api/remote.js
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/common/api/api.mojom
  shell/common/api/electron_api_v8_util.cc
  shell/common/api/remote/remote_object_freer.cc
  shell/common/api/remote/remote_object_freer.h
Labels: new-pr 🌱

#24061 chore: cherry-pick bc4df9dd11e609e from chromium
  patches/chromium/.patches
  patches/chromium/a11y_iterate_all_descendants_for_getselectioncount.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱, target/8-x-y

#23945 chore: roll latest Node.js security release
  patches/node/.patches
  patches/node/deps_update_nghttp2_to_1_41_0.patch
  patches/node/http2_implement_support_for_max_settings_entries.patch
  patches/node/napi_fix_memory_corruption_vulnerability.patch
  patches/node/tls_emit_session_after_verifying_certificate.patch
Labels: 10-x-y, backport-check-skip

#24078 fix: Revert "fix: do not use CONTEXT_MENU flag for tray menu"
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: fast-track 🚅

#24077 fix: Revert "fix: do not use CONTEXT_MENU flag for tray menu"
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: fast-track 🚅

#24076 fix: Revert "fix: do not use CONTEXT_MENU flag for tray menu"
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: new-pr 🌱

#24079 fix: Revert "fix: do not use CONTEXT_MENU flag for tray menu"
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: fast-track 🚅

#24060 chore: cherry-pick 867fcd45891e from chromium
  patches/chromium/.patches
  patches/chromium/a11y_allows_klistboxoption_as_an_item_to_kgroup.patch
Labels: 9-x-y, backport-check-skip, new-pr 🌱, target/7-3-x, target/8-x-y

#24042 fix: handle non-client area pointer events from pen on Win10
  patches/chromium/.patches
  patches/chromium/fix_handling_non_client_pointer_events_from_pen_on_windows_10.patch
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#24062 fix: fs.readdir/readdirSync should support withFileTypes
  lib/common/asar.js
  spec/asar-spec.js
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24091 fix: showing certificate dialog with no window
  lib/browser/api/dialog.js
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#23979 fix: throw instead of crash when using ipcRenderer after context released
  shell/renderer/api/electron_api_renderer_ipc.cc
  spec-main/api-ipc-renderer-spec.ts
Labels: 8-x-y, backport

#24080 fix: Revert "fix: do not use CONTEXT_MENU flag for tray menu"
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: fast-track 🚅

#24111 fix: emit 'shutdown' outside -[NSApplication terminate:]
  shell/browser/mac/electron_application.h
  shell/browser/mac/electron_application.mm
  shell/browser/mac/electron_application_delegate.mm
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#23831 build: remove dead symlink from MAS build
  .circleci/config.yml
  BUILD.gn
  script/check-symlinks.js
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  shell/app/electron_crash_reporter_client.h
  shell/app/electron_main_delegate.cc
  shell/app/node_main.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/electron_browser_client.cc
  shell/common/crash_keys.cc
Labels: target/10-x-y, target/9-x-y

#23872 feat: Add did-become-active event on mac
  docs/api/app.md
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/browser.cc
  shell/browser/browser.h
  shell/browser/browser_observer.h
  shell/browser/mac/electron_application_delegate.mm
Labels: api-review/approved ✅

#24162 chore: support props/fns for BrowserWindow
  docs/api/browser-window.md
  lib/browser/api/browser-window.js
  shell/browser/api/atom_api_top_level_window.cc
  spec-main/api-browser-window-spec.ts
Labels: 7-3-x, backport

#24158 build: remove dead symlink from MAS build
  .circleci/config.yml
  BUILD.gn
  script/check-symlinks.js
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  shell/app/electron_main_delegate.cc
  shell/app/node_main.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/electron_browser_client.cc
  shell/renderer/api/electron_api_crash_reporter_renderer.cc
Labels: target/10-x-y, target/9-x-y

#24167 chore: cleanup unused WebContents::DereferenceRemoteJSObject()
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/common/api/api.mojom
Labels: new-pr 🌱

#24131 fix: let Node.js perform microtask checkpoint in the main process
  filenames.gni
  shell/browser/api/electron_api_url_loader.cc
  shell/browser/electron_browser_main_parts.h
  shell/browser/javascript_environment.h
  shell/browser/microtasks_runner.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/gin_helper/microtasks_scope.cc
  shell/common/gin_helper/microtasks_scope.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/node-spec.ts
  spec/fixtures/api/gpu-info.js
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24147 docs: fix MenuItem click handler type
  docs/api/menu-item.md
Labels: documentation :notebook:, target/10-x-y, target/8-x-y, target/9-x-y

#24059 chore: cherry-pick c20afc96e36f57 from chromium
  patches/chromium/.patches
  patches/chromium/allow_ime_to_insert_zero_length_composition_string.patch
Labels: 9-x-y, backport-check-skip, target/8-x-y

#24153 fix: make pasteandmatchstyle accelerator os specific
  lib/browser/api/menu-item-roles.js
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#24181 chore: cherry-pick c20afc96e36f57 from chromium
  patches/chromium/.patches
  patches/chromium/allow_ime_to_insert_zero-length_composition_string.patch
Labels: 8-x-y, backport, backport-check-skip

#24180 fix: let Node.js perform microtask checkpoint in the main process
  native_mate/BUILD.gn
  native_mate/native_mate/function_template.h
  native_mate/native_mate/microtasks_scope.cc
  native_mate/native_mate/microtasks_scope.h
  shell/browser/api/electron_api_url_loader.cc
  shell/browser/electron_browser_main_parts.h
  shell/browser/javascript_environment.h
  shell/browser/microtasks_runner.cc
  shell/common/api/electron_bindings.cc
  shell/common/api/event_emitter_caller_deprecated.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/native_mate_converters/callback_converter_deprecated.h
  shell/common/node_bindings.cc
  shell/common/promise_util.h
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/node-spec.ts
Labels: 8-x-y, backport

#24178 fix: let Node.js perform microtask checkpoint in the main process
  filenames.gni
  shell/browser/api/electron_api_url_loader.cc
  shell/browser/electron_browser_main_parts.h
  shell/browser/javascript_environment.h
  shell/browser/microtasks_runner.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/gin_helper/microtasks_scope.cc
  shell/common/gin_helper/microtasks_scope.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
  spec-main/api-session-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/node-spec.ts
  spec/fixtures/api/gpu-info.js
Labels: 9-x-y, backport

#24097 fix: do not use CONTEXT_MENU flag for tray menu (reland)
  patches/chromium/.patches
  patches/chromium/remove_menu_window_task_item.patch
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: target/10-x-y, target/7-3-x, target/8-x-y, target/9-x-y

#24152 chore: cherry-pick eac3d9283d11 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-eac3d9283d11.patch
Labels: 8-x-y, backport-check-skip

#24133 fix: correctly handle nexttick scheduling in stream reads
  shell/browser/net/node_stream_loader.cc
  shell/browser/net/node_stream_loader.h
  spec-main/api-protocol-spec.ts
Labels: 8-x-y, backport

#24194 fix: do not use CONTEXT_MENU flag for tray menu (reland)
  patches/chromium/.patches
  patches/chromium/remove_menu_window_task_item.patch
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: 8-x-y, backport

#24165 test: skip 'handles Promise timeouts correctly' when ELECTRON_RUN_AS_NODE is disabled
  spec/node-spec.js
  spec/spec-helpers.js
Labels: 7-3-x, backport

#24200 fix: emit click events with tray context menu
  shell/browser/ui/tray_icon_cocoa.mm
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24238 build: remove dead symlink from MAS build
  .circleci/config.yml
  BUILD.gn
  script/check-symlinks.js
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  shell/app/electron_main_delegate.cc
  shell/app/node_main.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/electron_browser_client.cc
  shell/renderer/api/electron_api_crash_reporter_renderer.cc
Labels: 9-x-y, backport

#24240 fix: only notify mouse-up on mouse-up
  shell/browser/ui/tray_icon_cocoa.mm
Labels: new-pr 🌱, target/9-x-y

#24239 fix: emit click events with tray context menu
  shell/browser/ui/tray_icon_cocoa.mm
Labels: 8-x-y, backport

#24252 chore: minify internal JS code
  build/webpack/webpack.config.base.js
Labels: new-pr 🌱, performance :checkered_flag:, target/10-x-y, target/9-x-y

#24266 fix: backport nodejs/node#33682
  patches/node/.patches
  patches/node/crypto_update_root_certificates.patch
  patches/node/tools_update_certdata_txt.patch
Labels: 10-x-y, backport-check-skip

#24267 fix: backport nodejs/node#33682
  patches/node/.patches
  patches/node/crypto_update_root_certificates.patch
  patches/node/tools_update_certdata_txt.patch
Labels: 9-x-y, backport-check-skip

#24268 fix: backport nodejs/node#33682 and nodejs/node#30195
  patches/node/.patches
  patches/node/crypto_update_root_certificates_to_nss_3_47.patch
  patches/node/crypto_update_root_certificates_to_nss_3_53.patch
  patches/node/tools_update_certdata_txt_to_nss_3_47.patch
  patches/node/tools_update_certdata_txt_to_nss_3_53.patch
Labels: 8-x-y, backport-check-skip

#24269 fix: backport nodejs/node#33682 and nodejs/node#30195
  patches/node/.patches
  patches/node/crypto_update_root_certificates_to_nss_3_47.patch
  patches/node/crypto_update_root_certificates_to_nss_3_53.patch
  patches/node/tools_update_certdata_txt_to_nss_3_47.patch
  patches/node/tools_update_certdata_txt_to_nss_3_53.patch
Labels: 7-3-x, backport-check-skip

#24251 feat: support suspend/resume on Windows
  docs/api/power-monitor.md
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24250 fix: frameless vibrant modals shouldn't bezel
  shell/browser/native_window_mac.mm
Labels: target/10-x-y, target/9-x-y

#24310 test: do not check expectations inside IPC handlers
  spec-main/api-web-contents-spec.ts
Labels: backport-check-skip

#24286 fix: macOS modal focus behavior
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: target/10-x-y, target/8-x-y, target/9-x-y

#24112 feat: add app.getApplicationInfoForProtocol API
  docs/api/app.md
  shell/browser/api/electron_api_app.cc
  shell/browser/browser.h
  shell/browser/browser_mac.mm
  shell/browser/browser_win.cc
  spec-main/api-app-spec.ts
Labels: api-review/approved ✅

#24355 chore: tsify extensions shim
  filenames.auto.gni
  lib/browser/chrome-extension-shim.ts
  lib/common/api/deprecate.ts
  typings/internal-electron.d.ts
Labels: new-pr 🌱
