Repository electron/electron, pull requests merged in 2021-06, with the labels that each got.

#29401 chore: fix typos in comments
  shell/browser/api/electron_api_web_request.cc
  shell/browser/ui/accelerator_util.h
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/function_template.h
Labels: no-backport, semver/none

#29425 fix: add service worker schemes from command line in renderer
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/renderer/renderer_client_base.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/service-worker/custom-scheme-index.html
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29361 chore: use consistent parameter names
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_auto_updater.h
  shell/browser/api/electron_api_download_item.cc
  shell/browser/api/electron_api_download_item.h
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_url_loader.h
  shell/browser/auto_updater.h
  shell/browser/extensions/electron_messaging_delegate.h
  shell/browser/file_select_helper.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/notifications/mac/notification_presenter_mac.h
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/relauncher.h
  shell/browser/ui/accelerator_util.h
  shell/browser/web_dialog_helper.h
  shell/common/asar/archive.cc
  shell/renderer/api/electron_api_spell_check_client.h
  shell/renderer/renderer_client_base.h
Labels: semver/patch, target/13-x-y, target/14-x-y

#29378 chore: use HTTP status code constants
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/ui/inspectable_web_contents.cc
Labels: no-backport, semver/none

#29328 fix: correctly handle Alt+Key shortcuts
  shell/browser/ui/views/menu_bar.cc
  shell/browser/ui/views/root_view.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29379 chore: move destructors to header so they can be trivially destructible
  shell/common/gin_helper/error_thrower.cc
  shell/common/gin_helper/error_thrower.h
  shell/common/gin_helper/object_template_builder.cc
  shell/common/gin_helper/object_template_builder.h
Labels: no-backport, semver/none

#29318 fix: Alt+Click should not toggle menu bar
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29422 chore: remove duplicate option get for CustomScheme
  shell/browser/api/electron_api_protocol.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29447 fix: add service worker schemes from command line in renderer (#29425)
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/renderer/renderer_client_base.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/service-worker/custom-scheme-index.html
Labels: 12-x-y, backport, semver/patch

#29446 fix: add service worker schemes from command line in renderer
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/renderer/renderer_client_base.cc
  spec-main/chromium-spec.ts
  spec/fixtures/pages/service-worker/custom-scheme-index.html
Labels: 13-x-y, backport, semver/patch

#29404 feat: support loading debug urls with loadURL()
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/13-x-y, target/14-x-y

#29199 feat: include resize edge with will-resize event
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/browser/native_window_views_win.cc
  shell/browser/ui/cocoa/electron_ns_window_delegate.h
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  shell/common/gin_converters/gfx_converter.cc
  shell/common/gin_converters/gfx_converter.h
Labels: api-review/requested 🗳, no-backport, semver/minor

#29237 docs: Updated "progress bar" fiddle feature in docs
  docs/fiddles/features/progress-bar/index.html
  docs/fiddles/features/progress-bar/main.js
  docs/tutorial/progress-bar.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29436 fix: inspector context menu throwing an error
  lib/browser/devtools.ts
  typings/internal-electron.d.ts
Labels: semver/patch, target/14-x-y

#29168 feat: add new runningUnderARM64Translation property to detect x64 translated apps running on Windows ARM
  docs/api/app.md
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_app_mac.mm
  spec-main/api-app-spec.ts
Labels: api-review/requested 🗳, no-backport, semver/minor

#29438 chore: remove unused WebContents method types
  typings/internal-electron.d.ts
Labels: semver/patch, target/14-x-y

#29449 build: Support building Electron on msys2
  script/lib/config.py
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29468 chore: don't use after move
  shell/browser/native_window_mac.mm
Labels: new-pr 🌱, semver/patch, target/13-x-y, target/14-x-y

#29467 chore: use static_cast rather than C-style cast
  shell/common/node_bindings.cc
Labels: new-pr 🌱, no-backport, semver/none

#29202 fix: keep shifted character in menu accelerator
  patches/chromium/accelerator.patch
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/ui/accelerator_util.cc
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/common/gin_converters/blink_converter.cc
  shell/common/keyboard_util.cc
  shell/common/keyboard_util.h
  spec-main/api-menu-item-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29484 build: fix macOS build
  shell/browser/api/electron_api_app_mac.mm
Labels: fast-track 🚅, no-backport, semver/patch

#29464 refactor: eliminate duplicate C++ / JavaScript implementation of app.isPackaged
  lib/browser/api/app.ts
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/common/node_bindings.cc
Labels: new-pr 🌱, no-backport, semver/patch

#29394 refactor: point prepare-release at main
  script/release/prepare-release.js
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#29381 build: update support.md on stable version bumps
  script/release/version-bumper.js
  spec-main/fixtures/version-bumper/fixture_support.md
  spec-main/version-bump-spec.ts
Labels: semver/none, target/14-x-y

#29492 feat: add experimental cookie encryption support
  BUILD.gn
  build/args/all.gn
  build/fuses/build.py
  build/fuses/fuses.json5
  docs/tutorial/fuses.md
  patches/chromium/.patches
  patches/chromium/support_runtime_configurable_key_storage_on_linux_os_crypto.patch
  shell/browser/browser_process_impl.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/network_context_service.cc
  shell/browser/net/system_network_context_manager.cc
Labels: 14-x-y, backport, backport-check-skip, backport/approved ✅, semver/minor

#29491 feat: support loading debug urls with loadURL()
  shell/browser/api/electron_api_web_contents.cc
Labels: 13-x-y, backport, backport/requested 🗳, semver/patch

#29493 feat: add experimental cookie encryption support
  BUILD.gn
  build/args/all.gn
  build/fuses/build.py
  build/fuses/fuses.json5
  docs/tutorial/fuses.md
  patches/chromium/.patches
  patches/chromium/make_keychain_service_account_optionally_configurable_at_runtime.patch
  patches/chromium/support_runtime_configurable_key_storage_on_linux_os_crypto.patch
  shell/browser/browser_process_impl.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/network_context_service.cc
  shell/browser/net/system_network_context_manager.cc
Labels: 13-x-y, backport, backport-check-skip, backport/approved ✅, semver/minor

#29494 chore: cherry-pick 3299d70b7d0f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3299d70b7d0f.patch
Labels: 13-x-y, backport-check-skip, semver/patch

#29508 test: add spec for --require filtering in NODE_OPTIONS
  shell/common/node_bindings.cc
  spec-main/node-spec.ts
  spec/fixtures/module/fail.js
Labels: 14-x-y, backport, backport-check-skip, semver/patch

#29507 test: add spec for --require filtering in NODE_OPTIONS
  shell/common/node_bindings.cc
  spec-main/node-spec.ts
  spec/fixtures/module/fail.js
Labels: 13-x-y, backport, backport-check-skip, semver/patch

#29506 test: add spec for --require filtering in NODE_OPTIONS
  shell/common/node_bindings.cc
  spec-main/node-spec.ts
  spec/fixtures/module/fail.js
Labels: 12-x-y, backport, backport-check-skip, semver/patch

#29501 test: add spec for --require filtering in NODE_OPTIONS
  shell/browser/api/electron_api_app.cc
  spec-main/node-spec.ts
  spec/fixtures/module/fail.js
Labels: fast-track 🚅, in-flight/11-x-y, merged/12-x-y, merged/13-x-y, merged/14-x-y, semver/patch

#29448 build: Improve squirrel.mac BUILD.gn xcrun_action error
  patches/squirrel.mac/build_add_gn_config.patch
Labels: semver/none, target/13-x-y, target/14-x-y

#29457 docs: link to IncomingMessage
  docs/api/client-request.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29419 fix: pass updated NODE_OPTIONS to Node.js
  patches/node/.patches
  patches/node/process_correctly_parse_unicode_in_node_options.patch
Labels: backport-check-skip, semver/patch

#29400 refactor: replace a few usages of V8 hidden properties
  lib/asar/fs-wrapper.ts
  lib/browser/api/menu.ts
  lib/browser/default-menu.ts
  lib/sandboxed_renderer/init.ts
  typings/internal-electron.d.ts
Labels: no-backport, semver/patch

#29499 docs: remove devDependencies badge from README
  README.md
Labels: new-pr 🌱, no-backport, semver/none

#29505 test: add spec for --require filtering in NODE_OPTIONS
  shell/common/node_bindings.cc
  spec-main/node-spec.ts
  spec/fixtures/module/fail.js
Labels: 11-x-y, backport, backport-check-skip, semver/patch

#29502 refactor: use auto env = base::Environment::Create(); everywhere
  shell/app/electron_crash_reporter_client.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/browser_linux.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/linux/unity_service.cc
  shell/browser/ui/gtk/app_indicator_icon.cc
  shell/browser/ui/views/electron_views_delegate.cc
  shell/browser/ui/x/x_window_utils.cc
  shell/common/node_bindings.cc
  shell/common/platform_util_linux.cc
Labels: no-backport, semver/patch

#29293 fix: change ASAR archive cache to per-process to fix leak
  shell/browser/electron_browser_main_parts.cc
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
  shell/common/asar/asar_util.cc
  shell/common/asar/asar_util.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29511 chore: use =default for default constructors/destructors
  shell/app/electron_crash_reporter_client.cc
  shell/browser/api/electron_api_in_app_purchase.cc
  shell/browser/api/event.cc
  shell/browser/api/views/electron_api_image_view.cc
  shell/browser/badging/badge_manager_factory.cc
  shell/browser/child_web_contents_tracker.cc
  shell/browser/electron_javascript_dialog_manager.cc
  shell/browser/electron_pdf_web_contents_helper_client.cc
  shell/browser/extensions/api/management/electron_management_api_delegate.cc
  shell/browser/extensions/api/resources_private/resources_private_api.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/extensions/electron_extension_host_delegate.cc
  shell/browser/extensions/electron_extension_system_factory.cc
  shell/browser/extensions/electron_extension_web_contents_observer.cc
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/extensions/electron_kiosk_delegate.cc
  shell/browser/extensions/electron_navigation_ui_data.cc
  shell/browser/native_browser_view_mac.mm
  shell/browser/native_window_mac.mm
  shell/browser/net/asar/asar_url_loader.cc
  shell/browser/notifications/win/notification_presenter_win.cc
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/browser/printing/print_view_manager_electron.cc
  shell/browser/protocol_registry.cc
  shell/browser/serial/serial_chooser_context_factory.cc
  shell/browser/ui/cocoa/delayed_native_view_host.cc
  shell/browser/ui/cocoa/electron_native_widget_mac.mm
  shell/browser/ui/cocoa/root_view_mac.mm
  shell/browser/ui/cocoa/views_delegate_mac.mm
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/taskbar_host.cc
  shell/browser/win/scoped_hstring.cc
  shell/common/api/electron_bindings.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_win.cc
  shell/renderer/api/context_bridge/object_cache.cc
  shell/renderer/electron_renderer_pepper_host_factory.cc
  shell/renderer/extensions/electron_extensions_dispatcher_delegate.cc
  shell/renderer/extensions/electron_extensions_renderer_client.cc
  shell/renderer/pepper_helper.cc
Labels: no-backport, semver/none

#29486 chore: pull ProxyingURLLoaderFactory closer to upstream class it mirrors
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
Labels: no-backport, semver/none

#29279 chore: return early on promise rejection in cookies.set
  shell/browser/api/electron_api_cookies.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29546 fix: disable CET as v8 deoptimization is incompatible with it
  build/args/all.gn
Labels: backport-check-skip, fast-track 🚅, no-backport, semver/patch

#29512 chore: update base class name in comment
  shell/browser/electron_browser_client.cc
  shell/browser/net/electron_url_loader_factory.cc
Labels: no-backport, semver/none

#29548 fix: change ASAR archive cache to per-process to fix leak (#29293)
  shell/browser/electron_browser_main_parts.cc
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
  shell/common/asar/asar_util.cc
  shell/common/asar/asar_util.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: 12-x-y, backport, semver/patch

#29242 docs: Updated "recent documents" fiddle tutorial
  docs/fiddles/features/recent-documents/index.html
  docs/fiddles/features/recent-documents/main.js
  docs/images/recent-documents.png
  docs/tutorial/recent-documents.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29267 docs: Update notifications (renderer) docs
  docs/fiddles/features/notifications/renderer/index.html
  docs/fiddles/features/notifications/renderer/main.js
  docs/fiddles/features/notifications/renderer/renderer.js
  docs/tutorial/notifications.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29552 fix: make intermediates work with 'select-client-certificate'
  shell/browser/api/electron_api_app.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29344 build: remove individual release build workflows
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: no-backport, semver/none

#29482 fix: keep shifted character in menu accelerator
  patches/chromium/accelerator.patch
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/ui/accelerator_util.cc
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/common/gin_converters/blink_converter.cc
  shell/common/keyboard_util.cc
  shell/common/keyboard_util.h
  spec-main/api-menu-item-spec.ts
Labels: 13-x-y, backport, semver/patch

#29483 fix: keep shifted character in menu accelerator
  patches/chromium/accelerator.patch
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/ui/accelerator_util.cc
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/common/gin_converters/blink_converter.cc
  shell/common/keyboard_util.cc
  shell/common/keyboard_util.h
  spec-main/api-menu-item-spec.ts
Labels: 12-x-y, backport, semver/patch

#29528 fix: improper wrapping of fs.promises.readFile
  lib/asar/fs-wrapper.ts
  spec-main/fixtures/dogs-running.txt
  spec-main/node-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29095 feat: add new imageAnimationPolicy webpref and webContents setter
  docs/api/browser-window.md
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/web_contents_preferences.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: api-review/approved ✅, no-backport, semver/minor

#29578 ci: save artifacts before cleaning up big things on macOS
  .circleci/config.yml
Labels: no-backport, semver/none

#29553 docs: fix typo
  docs/fiddles/features/macos-dark-mode/main.js
  docs/tutorial/dark-mode.md
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#28898 fix: don't propagate GDK_BACKEND to subprocs
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
  shell/common/platform_util_linux.cc
  spec-main/chromium-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29591 fix: select-bluetooth-device on Windows
  shell/browser/lib/bluetooth_chooser.cc
  shell/browser/lib/bluetooth_chooser.h
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29610 fix: Revert "fix: don't propagate GDK_BACKEND to subprocs"
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
  shell/common/platform_util_linux.cc
  spec-main/chromium-spec.ts
Labels: fast-track 🚅, no-backport, semver/patch

#29599 fix: ensure fuse order is read in a stable way
  build/fuses/build.py
Labels: fast-track 🚅, semver/patch, target/13-x-y, target/14-x-y

#29595 fix: ensure custom traffic lights float to top
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/13-x-y, target/14-x-y

#29592 docs: fix image links in `performance.md`
  docs/tutorial/performance.md
Labels: documentation :notebook:, semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29663 fix: ensure custom traffic lights float to top
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: 13-x-y, backport, semver/patch

#29567 fix: copy received data in URLPipeLoader to prevent corruption
  shell/browser/net/url_pipe_loader.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#29650 chore: use HTTP method constants
  shell/browser/net/electron_url_loader_factory.cc
  shell/renderer/electron_renderer_client.cc
Labels: no-backport, semver/none

#29621 fix: use correct spelling of attachment with Content-Disposition header
  shell/browser/api/electron_api_web_request.cc
  spec-main/api-web-request-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29620 fix: check DCHECK_IS_ON() instead of #ifdef DCHECK_IS_ON
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/common/api/electron_api_v8_util.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#29550 refactor: use `locale` functions in `command_line_args.cc`
  shell/app/command_line_args.cc
Labels: no-backport, semver/none

#29540 chore: use consistent integer type for request ID
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
Labels: no-backport, semver/patch

#29609 docs: fix file mode of `versioning-sketch-2.png`
  docs/images/versioning-sketch-2.png
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29563 docs: fix typo in process-model.md
  docs/tutorial/process-model.md
Labels: semver/none, target/13-x-y, target/14-x-y

#29651 docs: use relative links within docs
  docs/api/app.md
  docs/api/menu.md
  docs/breaking-changes.md
  docs/tutorial/debugging-vscode.md
  docs/tutorial/using-selenium-and-webdriver.md
Labels: documentation :notebook:, no-backport, semver/none

#29465 build: restore workspace on osx builds to get docs-only-change file
  .circleci/config.yml
Labels: semver/none, target/14-x-y

#29649 refactor: use PathProvider for user-data-dir and others
  default_app/main.ts
  lib/browser/api/app.ts
  lib/browser/init.ts
  shell/app/electron_crash_reporter_client.cc
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/browser.cc
  shell/browser/browser_process_impl.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/ui/devtools_manager_delegate.cc
  shell/common/electron_paths.h
  typings/internal-electron.d.ts
Labels: semver/patch, target/14-x-y

#29637 refactor: use std::make_unique/base::MakeRefCounted when possible
  chromium_src/chrome/browser/certificate_manager_model.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_context.cc
  shell/browser/extensions/electron_extension_system.cc
  shell/renderer/electron_api_service_impl.cc
Labels: no-backport, semver/none

#29245 docs: Update represented-file fiddle tutorial
  docs/fiddles/features/represented-file/index.html
  docs/fiddles/features/represented-file/main.js
  docs/images/represented-file.png
  docs/tutorial/represented-file.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29385 docs: added guide and updated docs for Tray
  docs/fiddles/native-ui/tray/index.html
  docs/fiddles/native-ui/tray/main.js
  docs/fiddles/native-ui/tray/renderer.js
  docs/tutorial/tray.md
Labels: documentation :notebook:, semver/none, target/13-x-y, target/14-x-y

#29655 test: re-enable some skipped tests
  spec-main/api-browser-window-spec.ts
  spec-main/api-protocol-spec.ts
  spec/fixtures/pages/cache-storage.html
Labels: no-backport, semver/none

#29691 fix: warnAboutRemoteModuleWithRemoteContent
  lib/renderer/security-warnings.ts
  spec-main/security-warnings-spec.ts
Labels: backport-check-skip, semver/patch, target/11-x-y, target/12-x-y

#29690 chore: disable default async spellchecker on Windows
  shell/browser/feature_list.cc
Labels: new-pr 🌱, semver/patch, target/13-x-y, target/14-x-y

#29686 chore: bumping NAN dep to include test changes
  DEPS
  patches/config.json
  patches/nan/.patches
  patches/nan/api_simplify_scriptorigin.patch
  patches/nan/nan_string_test_alignment.patch
Labels: semver/none, target/14-x-y

#28712 fix: ensure the typescript definitions only export correct value types
  .markdownlint.json
  docs/api/browser-window-proxy.md
  docs/api/client-request.md
  docs/api/command-line.md
  docs/api/cookies.md
  docs/api/debugger.md
  docs/api/dock.md
  docs/api/download-item.md
  docs/api/incoming-message.md
  docs/api/message-port-main.md
  docs/api/native-image.md
  docs/api/service-workers.md
  docs/api/session.md
  docs/api/touch-bar-button.md
  docs/api/touch-bar-color-picker.md
  docs/api/touch-bar-group.md
  docs/api/touch-bar-label.md
  docs/api/touch-bar-other-items-proxy.md
  docs/api/touch-bar-popover.md
  docs/api/touch-bar-scrubber.md
  docs/api/touch-bar-segmented-control.md
  docs/api/touch-bar-slider.md
  docs/api/touch-bar-spacer.md
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  docs/api/web-request.md
  docs/api/webview-tag.md
  package.json
  spec-main/api-ipc-spec.ts
  yarn.lock
Labels: no-backport, semver/patch

#29712 fix: don't warn about enableRemoteModule when it's disabled at build time
  lib/renderer/security-warnings.ts
  spec-main/security-warnings-spec.ts
Labels: 12-x-y, backport-check-skip, semver/patch

#29677 fix: potential crash when setting vibrancy
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29551 docs: fix setWindowOpenHandler invocation in window.open example
  docs/api/window-open.md
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29696 fix: draggable regions with devtools open
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_browser_window_mac.mm
  shell/browser/api/electron_api_browser_window_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29724 chore: remove c-style conversion for vibrantView
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.h
Labels: new-pr 🌱, no-backport, semver/none

#29717 fix: ensure detached devtools are not always draggable
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
Labels: new-pr 🌱, semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29720 docs: clarify use of ELECTRON_SKIP_BINARY_DOWNLOAD
  docs/tutorial/installation.md
Labels: documentation :notebook:, semver/none, target/13-x-y, target/14-x-y

#29244 chore: bump Node.js to v16.2.0
  DEPS
  patches/boringssl/.patches
  patches/boringssl/ensure_name_not_null_in_evp_get_cipherbyname.patch
  patches/boringssl/src_add_impl_for_evp_pkey_get0.patch
  patches/node/.patches
  patches/node/allow_preventing_preparestacktracecallback.patch
  patches/node/build_add_gn_build_files.patch
  patches/node/build_add_mjs_support_to_js2c.patch
  patches/node/build_modify_js2c_py_to_allow_injection_of_original-fs_and_custom_embedder_js.patch
  patches/node/chore_add_context_to_context_aware_module_prevention.patch
  patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/node/chore_read_nobrowserglobals_from_global_not_process.patch
  patches/node/enable_31_bit_smis_on_64bit_arch_and_ptr_compression.patch
  patches/node/expose_get_builtin_module_function.patch
  patches/node/feat_add_flags_for_low-level_hooks_and_exceptions.patch
  patches/node/feat_add_implementation_of_v8_platform_postjob.patch
  patches/node/feat_initialize_asar_support.patch
  patches/node/fix_account_for_debugger_agent_race_condition.patch
  patches/node/fix_add_default_values_for_enable_lto_and_build_v8_with_gn_in.patch
  patches/node/fix_add_v8_enable_reverse_jsargs_defines_in_common_gypi.patch
  patches/node/fix_allow_preventing_initializeinspector_in_env.patch
  patches/node/fix_comment_out_incompatible_crypto_modules.patch
  patches/node/fix_crypto_tests_to_run_with_bssl.patch
  patches/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
  patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
  patches/node/fix_handle_new_tostring_behavior_in_v8_serdes_test.patch
  patches/node/fix_key_gen_apis_are_not_available_in_boringssl.patch
  patches/node/fix_remove_outdated_--experimental-wasm-bigint_flag.patch
  patches/node/fix_use_crypto_impls_for_compat.patch
  patches/node/fixme_comment_trace_event_macro.patch
  patches/node/make_module_globalpaths_a_reference.patch
  patches/node/node-api_faster_threadsafe_function.patch
  patches/node/pass_all_globals_through_require.patch
  patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
  patches/node/src_add_get_set_pair_for_unhandled_rejections_mode.patch
  patches/node/src_add_node_use_v8_platform_in_initializeonceperprocess.patch
  patches/node/src_allow_embedders_to_provide_a_custom_pageallocator_to.patch
  patches/node/src_inline_asynccleanuphookhandle_in_headers.patch
  patches/node/src_remove_extra_semi_after_member_fn.patch
  patches/node/src_remove_extra_semis_from_member_fns.patch
  patches/node/tls_tweak_clientcertengine_argument_parsing.patch
  patches/node/update_tests_after_increasing_typed_array_size.patch
  script/node-disabled-tests.json
  shell/app/node_main.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/javascript_environment.cc
  shell/common/node_bindings.cc
  shell/renderer/electron_renderer_client.cc
  spec-main/types-spec.ts
  spec/asar-spec.js
Labels: api-review/approved ✅, no-backport, semver/major

#29748 chore: fix BoringSSL conflict in patches
  patches/boringssl/.patches
  patches/boringssl/ensure_name_not_null_in_evp_get_cipherbyname.patch
  patches/boringssl/src_add_impl_for_evp_pkey_get0.patch
Labels: fast-track 🚅, no-backport, semver/patch

#29729 fix: color select eyedropper not working within DevTools
  chromium_src/BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_delegate.h
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29762 docs: added guide and updated docs for Tray
  docs/fiddles/native-ui/tray/index.html
  docs/fiddles/native-ui/tray/main.js
  docs/fiddles/native-ui/tray/renderer.js
  docs/tutorial/tray.md
Labels: 13-x-y, backport, semver/none

#25089 feat: bring --enable-logging functionality in line with Chromium
  docs/api/command-line-switches.md
  docs/api/environment-variables.md
  docs/tutorial/application-debugging.md
  filenames.gni
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_delegate.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_main_parts.cc
  shell/common/api/electron_api_testing.cc
  shell/common/logging.cc
  shell/common/logging.h
  shell/common/node_bindings.cc
  spec-main/api-session-spec.ts
  spec-main/fixtures/apps/remote-control/main.js
  spec-main/logging-spec.ts
  spec-main/spec-helpers.ts
Labels: api-review/approved ✅, api-review/requested 🗳, semver/minor, target/14-x-y

#29714 ci: run linux arm tests on CircleCI
  .circleci/config.yml
  patches/chromium/.patches
  patches/chromium/don_t_run_pcscan_notifythreadcreated_if_pcscan_is_disabled.patch
  spec-main/version-bump-spec.ts
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#29743 chore: remove unused and broken ipcRendererInternal.sendTo()
  lib/renderer/api/ipc-renderer.ts
  lib/renderer/ipc-renderer-internal.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_browser_handler_impl.cc
  shell/browser/electron_browser_handler_impl.h
  shell/common/api/api.mojom
  shell/renderer/api/electron_api_ipc_renderer.cc
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: no-backport, semver/patch

#29742 fix: select element not working on Windows
  patches/chromium/extend_apply_webpreferences.patch
Labels: semver/patch, target/14-x-y

#29760 fix: color select eyedropper not working within DevTools
  chromium_src/BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_delegate.h
Labels: 13-x-y, backport, semver/patch

#29764 docs: Add clarification for Visual Zoom behavior
  docs/api/web-frame.md
Labels: 13-x-y, backport, semver/patch

#29765 ci: run linux arm tests on CircleCI
  .circleci/config.yml
  patches/chromium/.patches
  patches/chromium/don_t_run_pcscan_notifythreadcreated_if_pcscan_is_disabled.patch
  spec-main/version-bump-spec.ts
Labels: 14-x-y, backport, fast-track 🚅, semver/none

#29769 ci: cleanup electron dirs after running tests on arm
  .circleci/config.yml
Labels: fast-track 🚅, no-backport, semver/none

#29721 fix: hover state bug when BrowserWindow is not resizable
  shell/browser/ui/views/frameless_view.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29744 fix: flaky extension bg page test
  spec-main/extensions-spec.ts
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29788 docs: fix frontmatter for Tray tutorial
  docs/tutorial/tray.md
Labels: documentation :notebook:, semver/none, target/13-x-y, target/14-x-y

#29534 refactor: tune-up electron::api::NetLog
  shell/browser/api/electron_api_net_log.cc
  shell/browser/api/electron_api_net_log.h
Labels: no-backport, semver/none

#29791 fix: update Squirel.Mac to fix CPU spin during update
  DEPS
  patches/squirrel.mac/build_add_gn_config.patch
  patches/squirrel.mac/fix_ensure_that_self_is_retained_until_the_racsignal_is_complete.patch
Labels: semver/patch, target/13-x-y, target/14-x-y

#29679 fix: relax app.getLocaleCountryCode() test
  spec-main/api-app-spec.ts
Labels: no-backport, semver/patch

#29531 fix: microtasks policy in CreateEnvironment
  shell/common/node_bindings.cc
  spec-main/fixtures/crash-cases/setimmediate-window-open-crash/index.html
  spec-main/fixtures/crash-cases/setimmediate-window-open-crash/index.js
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29266 fix: do not cancel CORS preflight request on proxy auth.
  shell/browser/net/proxying_url_loader_factory.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29786 chore: cherry-pick b7a1f498f1 and fad297a48a from chromium
  patches/chromium/.patches
  patches/chromium/m90-lts_longtaskdetector_remove_container_mutation_during.patch
  patches/chromium/m90-lts_reduce_memory_consumption_on.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29787 chore: cherry-pick 1856470e25 and 9037876f53 from chromium
  patches/chromium/.patches
  patches/chromium/m86-lts_longtaskdetector_remove_container_mutation_during.patch
  patches/chromium/m86-lts_reduce_memory_consumption_on.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29779 fix: cherry-pick 9a9c936879 from v8
  patches/v8/.patches
  patches/v8/m90-lts_squashed_multiple_commits.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29780 fix: cherry-pick 951a47c530 from v8
  patches/v8/.patches
  patches/v8/m86-lts_squashed_multiple_commits.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29777 chore: cherry-pick 0e36d324d6ef from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-0e36d324d6ef.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29776 chore: cherry-pick 34d5af37f9ac from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-34d5af37f9ac.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29825 refactor: migrate AdaptCallbackForRepeating to SplitOnceCallback in content_tracing
  shell/browser/api/electron_api_content_tracing.cc
Labels: new-pr 🌱, no-backport, semver/none

#29827 fix: allow ppapi processes access to resource bundle on all platforms
  shell/app/electron_main_delegate.cc
Labels: new-pr 🌱, semver/patch, target/13-x-y, target/14-x-y

#29767 ci: run linux arm tests on CircleCI
  .circleci/config.yml
  spec-main/version-bump-spec.ts
Labels: 12-x-y, backport, semver/none, target/11-x-y

#29766 ci: run linux arm tests on CircleCI
  .circleci/config.yml
  spec-main/version-bump-spec.ts
Labels: 13-x-y, backport, semver/none

#29784 chore: cherry-pick d0aadee1a60a from v8
  patches/v8/.patches
  patches/v8/cherry-pick-d0aadee1a60a.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29785 chore: cherry-pick 9da8fb7c4b80 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-9da8fb7c4b80.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29789 chore: cherry-pick 3d4f87ab5b9b from angle
  patches/angle/.patches
  patches/angle/cherry-pick-3d4f87ab5b9b.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29790 chore: cherry-pick 3d4f87ab5b9b from angle
  patches/angle/.patches
  patches/angle/cherry-pick-3d4f87ab5b9b.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29814 chore: cherry-pick b9ad6a864c79 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-b9ad6a864c79.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29815 chore: cherry-pick fd8cbdf7b888 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-fd8cbdf7b888.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29798 fix: properly handle optional requestHeaders with onBeforeSendHeaders
  shell/browser/api/electron_api_web_request.cc
  spec-main/api-web-request-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29816 chore: cherry-pick d9556a80a790 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-d9556a80a790.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29817 chore: cherry-pick d9556a80a790 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-d9556a80a790.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29782 docs: fix broken markdown in dialog.md
  docs/api/dialog.md
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#29842 chore: remove revert_remove_contentrendererclient_shouldfork.patch
  patches/chromium/.patches
  patches/chromium/don_t_use_potentially_null_getwebframe_-_view_when_get_blink.patch
  patches/chromium/revert_remove_contentrendererclient_shouldfork.patch
  patches/chromium/worker_feat_add_hook_to_notify_script_ready.patch
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_renderer_client.h
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
Labels: new-pr 🌱, semver/none, target/14-x-y

#29818 chore: cherry-pick 910e9e40d376 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-910e9e40d376.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29819 chore: cherry-pick 910e9e40d376 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-910e9e40d376.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29838 chore: cherry-pick 50de6a8ddad9 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-50de6a8ddad9.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29839 chore: cherry-pick fd9ce58ecd13 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-fd9ce58ecd13.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29823 chore: cherry-pick b77b38a3380c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-b77b38a3380c.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29822 chore: cherry-pick b77b38a3380c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-b77b38a3380c.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29813 fix: child window alwaysOnTop level persistence
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29795 fix: ensure set vibrancy with invalid value is a no-op
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29864 chore: bump chromium to 93.0.4539.0 (14-x-y)
  .circleci/config.yml
  BUILD.gn
  DEPS
  chromium_src/chrome/browser/certificate_manager_model.cc
  patches/boringssl/expose_aes-cfb.patch
  patches/boringssl/expose_des-ede3.patch
  patches/chromium/.patches
  patches/chromium/add_didinstallconditionalfeatures.patch
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/blink_local_frame.patch
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/can_create_window.patch
  patches/chromium/chore_expose_v8_initialization_isolate_callbacks.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch
  patches/chromium/disable_color_correct_rendering.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/disable_unload_metrics.patch
  patches/chromium/don_t_use_potentially_null_getwebframe_-_view_when_get_blink.patch
  patches/chromium/dump_syms.patch
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/feat_add_streaming-protocol_registry_to_multibuffer_data_source.patch
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
  patches/chromium/fix_expose_decrementcapturercount_in_web_contents_impl.patch
  patches/chromium/frame_host_manager.patch
  patches/chromium/gritsettings_resource_ids.patch
  patches/chromium/hack_to_allow_gclient_sync_with_host_os_mac_on_linux_in_ci.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
  patches/chromium/notification_provenance.patch
  patches/chromium/picture-in-picture.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_restore_base_adaptcallbackforrepeating.patch
  patches/chromium/render_widget_host_view_base.patch
  patches/chromium/resource_file_conflict.patch
  patches/chromium/revert_remove_contentrendererclient_shouldfork.patch
  patches/chromium/support_mixed_sandbox_with_zygote.patch
  patches/chromium/web_contents.patch
  patches/squirrel.mac/build_add_gn_config.patch
  patches/v8/build_gn.patch
  patches/v8/dcheck.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
  patches/v8/expose_mksnapshot.patch
  shell/browser/bluetooth/electron_bluetooth_delegate.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/extensions/electron_extension_message_filter.h
  shell/browser/net/cert_verifier_client.cc
  shell/browser/net/cert_verifier_client.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/web_contents_permission_helper.cc
  shell/renderer/renderer_client_base.cc
Labels: 14-x-y, backport-check-skip, semver/patch

#29865 refactor: use PathProvider for user-data-dir and others (#29649)
  default_app/main.ts
  lib/browser/api/app.ts
  lib/browser/init.ts
  shell/app/electron_crash_reporter_client.cc
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/browser.cc
  shell/browser/browser_process_impl.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/ui/devtools_manager_delegate.cc
  shell/common/electron_paths.h
  typings/internal-electron.d.ts
Labels: 14-x-y, backport, semver/patch

#29826 fix: deny instead of canceling when certificate-error passes false
  shell/browser/api/electron_api_app.cc
  spec-main/api-app-spec.ts
Labels: semver/patch, target/14-x-y

#29858 chore: remove revert_remove_contentrendererclient_shouldfork.patch
  patches/chromium/.patches
  patches/chromium/don_t_use_potentially_null_getwebframe_-_view_when_get_blink.patch
  patches/chromium/revert_remove_contentrendererclient_shouldfork.patch
  patches/chromium/worker_feat_add_hook_to_notify_script_ready.patch
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_renderer_client.h
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
Labels: 14-x-y, backport-check-skip, semver/none

#29851 fix: stop window.open from hanging when prevented
  lib/browser/guest-window-proxy.ts
  spec-main/guest-window-manager-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29841 fix: Inspector method overrides when contextIsolation enabled
  lib/renderer/inspector.ts
Labels: semver/patch, target/13-x-y, target/14-x-y

#29821 fix: properly order out child windows on `window.hide()`
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29892 chore: remove unused using and namespace declarations
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/api/electron_api_session.cc
  shell/browser/electron_browser_main_parts_posix.cc
  shell/common/extensions/electron_extensions_api_provider.cc
  shell/renderer/extensions/electron_extensions_dispatcher_delegate.cc
Labels: no-backport, semver/none

#29869 feat: undo nativeWindowOpen default change, warn instead
  docs/api/browser-window.md
  docs/api/window-open.md
  docs/breaking-changes.md
  shell/browser/web_contents_preferences.cc
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
  spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
  spec/static/main.js
  spec/webview-spec.js
Labels: backport-check-skip, semver/minor

#29877 chore: cherry-pick 0f8d58300b from usrsctp
  patches/usrsctp/.patches
  patches/usrsctp/improve_restart_handling.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29923 ci: fixup cross arch mksnapshot testing
  .circleci/config.yml
Labels: backport-check-skip, semver/none

#29907 docs: remove requestHeaders in webRequest.onHeadersReceived
  docs/api/web-request.md
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y
