Repository electron/electron, pull requests merged in 2021-07, with the labels that each got.

#29971 build: add support for spawning builds for a specific commit on appveyor
  script/release/ci-release-build.js
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#29973 build: add support for spawning builds for a specific commit on appveyor
  script/release/ci-release-build.js
Labels: 14-x-y, backport, semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#29956 fix: child window alwaysOnTop level persistence
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: 13-x-y, backport, semver/patch

#29253 feat: enable window controls overlay on macOS
  docs/api/browser-window.md
  docs/api/frameless-window.md
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_observer.h
  shell/browser/ui/cocoa/window_buttons_view.h
  shell/browser/ui/cocoa/window_buttons_view.mm
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/pages/overlay.html
Labels: api-review/approved ✅, semver/minor, target/13-x-y, target/14-x-y

#29906 chore: cleanup usages of const char*
  shell/app/electron_main.cc
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/gpu_info_enumerator.h
  shell/common/gin_helper/trackable_object.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_web_frame.cc
Labels: no-backport, semver/none

#29876 chore: cherry-pick 0f8d58300b from usrsctp
  patches/config.json
  patches/usrsctp/.patches
  patches/usrsctp/improve_restart_handling.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29952 fix: webview should maximize on requestFullscreen
  patches/chromium/.patches
  patches/chromium/webview_fullscreen.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/web_view_manager.h
  spec-main/fixtures/webview/fullscreen/frame.html
  spec-main/fixtures/webview/fullscreen/main.html
  spec-main/webview-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29976 chore: remove unused _grantOriginAccess method
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: new-pr 🌱, no-backport, semver/none

#29991 docs: remove mention of node-mac-notifier
  docs/tutorial/notifications.md
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29990 fix: do not leak NSUUID
  shell/browser/notifications/mac/cocoa_notification.mm
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29997 chore: cherry-pick cc20b36a5845 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-cc20b36a5845.patch
Labels: 13-x-y, backport-check-skip, semver/patch

#29985 docs: remove `Experimental` from `contextBridge.exposeInMainWorld`
  docs/api/context-bridge.md
Labels: semver/none, target/13-x-y, target/14-x-y

#29964 docs: added guide and updated docs for Tray
  docs/fiddles/native-ui/tray/index.html
  docs/fiddles/native-ui/tray/main.js
  docs/fiddles/native-ui/tray/renderer.js
  docs/tutorial/tray.md
Labels: 14-x-y, backport, documentation :notebook:, semver/none

#29955 fix: self.module.paths not working in web workers
  lib/worker/init.ts
  spec-main/chromium-spec.ts
  spec-main/fixtures/apps/self-module-paths/index.html
  spec-main/fixtures/apps/self-module-paths/main.js
  spec-main/fixtures/apps/self-module-paths/package.json
  spec-main/fixtures/apps/self-module-paths/renderer.js
  spec-main/fixtures/apps/self-module-paths/worker.js
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29963 feat: bring --enable-logging functionality in line with Chromium (#25089)
  docs/api/command-line-switches.md
  docs/api/environment-variables.md
  docs/tutorial/application-debugging.md
  filenames.gni
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_delegate.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_main_parts.cc
  shell/common/api/electron_api_testing.cc
  shell/common/logging.cc
  shell/common/logging.h
  shell/common/node_bindings.cc
  spec-main/api-session-spec.ts
  spec-main/fixtures/apps/remote-control/main.js
  spec-main/logging-spec.ts
  spec-main/spec-helpers.ts
Labels: 14-x-y, backport, backport/approved ✅, semver/minor

#30015 fix: build error caused by extra ]
  shell/browser/notifications/mac/cocoa_notification.mm
Labels: fast-track 🚅, no-backport, semver/none

#29948 chore: correct spelling of is_quitting in electron::Browser
  shell/browser/browser.cc
  shell/browser/browser.h
Labels: no-backport, semver/none

#29928 fix: fsPromises.readFile renderer crash
  patches/node/.patches
  patches/node/src_add_missing_context_scopes.patch
Labels: backport-check-skip, semver/patch

#29929 fix: fsPromises.readFile renderer crash
  patches/node/.patches
  patches/node/src_add_missing_context_scopes.patch
Labels: backport-check-skip, semver/patch

#29936 docs: match css filename in dark-mode.md
  docs/tutorial/dark-mode.md
Labels: semver/none, target/14-x-y

#29953 fix: download the arm64 version of Electron when running node under rosetta
  npm/install.js
Labels: no-backport, semver/patch

#29918 docs: mention contextIsolation in ipc-main example
  docs/api/ipc-main.md
Labels: semver/none, target/14-x-y

#30040 build: fix building with enable_plugins = false
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/none, target/14-x-y

#29902 feat: add missing resourceType conversions for webRequest listener details
  docs/api/web-request.md
  shell/browser/api/electron_api_web_request.cc
Labels: api-review/requested 🗳, semver/patch, target/14-x-y

#29900 docs: move webRequest filters definition to structures/web-request-filter.md
  docs/api/structures/web-request-filter.md
  docs/api/web-request.md
  filenames.auto.gni
Labels: no-backport, semver/patch

#29380 docs: modernize protocol-handler docs
  docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/index.html
  docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/main.js
  docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/preload.js
  docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/renderer.js
  docs/tutorial/launch-app-from-url-in-another-app.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#29857 fix: window ordering on mac
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/12-x-y, target/14-x-y

#30047 chore: remove unneeded conversions between wstring and u16string
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/browser_win.cc
  shell/browser/notifications/win/win32_desktop_notifications/common.h
  shell/browser/notifications/win/win32_desktop_notifications/desktop_notification_controller.cc
  shell/browser/notifications/win/win32_desktop_notifications/desktop_notification_controller.h
  shell/browser/notifications/win/win32_desktop_notifications/toast.cc
  shell/browser/notifications/win/win32_desktop_notifications/toast_uia.cc
  shell/browser/notifications/win/win32_desktop_notifications/toast_uia.h
  shell/browser/notifications/win/win32_notification.cc
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/browser/notifications/win/windows_toast_notification.h
  shell/browser/ui/message_box_win.cc
  shell/browser/ui/win/notify_icon.cc
Labels: no-backport, semver/none

#30081 chore: fix flaky fullscreen inheritance test
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱, no-backport, semver/none

#30083 chore: disable fullscreen test on mac arm
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱, no-backport, semver/none

#30055 fix: return RGBA values from getSystemColor
  shell/browser/api/electron_api_system_preferences_mac.mm
Labels: semver/patch, target/13-x-y, target/14-x-y

#30068 fix: crash when invoking login callback synchronously
  shell/browser/login_handler.cc
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#30093 build: decode error output as utf8
  build/npm-run.py
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#30096 test: disable failing node tests
  script/node-disabled-tests.json
Labels: fast-track 🚅, semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#30084 chore: cherry-pick 9bab573a37 from chromium
  patches/chromium/.patches
  patches/chromium/set_svgimage_page_after_document_install.patch
Labels: new-pr 🌱, semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#30086 test: fix check for electron_common_testing binding in logging-spec.ts
  spec-main/logging-spec.ts
Labels: semver/patch, target/14-x-y

#30042 feat: continue-activity event is extended to support webpageURL property
  docs/api/app.md
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/browser.h
  shell/browser/browser_mac.mm
  shell/browser/browser_observer.h
  shell/browser/mac/electron_application_delegate.mm
Labels: api-review/requested 🗳, new-pr 🌱, no-backport, semver/minor

#30109 docs: Update timeline for E15 alpha announcement
  docs/tutorial/electron-timelines.md
Labels: new-pr 🌱, semver/none, target/13-x-y, target/14-x-y

#30115 chore: update releases to 8 weeks in CONTRIBUTING
  CONTRIBUTING.md
  docs/tutorial/support.md
Labels: new-pr 🌱, semver/none, target/13-x-y, target/14-x-y

#30092 fix: crash when invoking login callback synchronously
  shell/browser/login_handler.cc
Labels: 12-x-y, backport, semver/patch

#29850 feat: expose location and modifiers on before-input-event
  docs/api/web-contents.md
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/blink_converter.h
  shell/common/gin_converters/content_converter.cc
Labels: api-review/requested 🗳, no-backport, semver/minor

#30063 fix: pressing ESC should exit fullscreen from webview
  shell/browser/api/electron_api_web_contents.cc
  spec-main/webview-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#29899 docs: add <webview> 'did-attach' event documentation
  docs/api/webview-tag.md
  spec-main/webview-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#30064 docs: update quick-start.md
  docs/tutorial/quick-start.md
Labels: semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#30113 fix: use correct userData path when unbundled
  shell/app/electron_main_delegate.cc
  shell/browser/browser.cc
  shell/browser/electron_browser_context.cc
  shell/common/application_info.cc
  shell/common/application_info.h
  shell/common/application_info_linux.cc
  spec-main/api-app-spec.ts
Labels: semver/patch, target/14-x-y

#30139 docs: fix fiddle path
  docs/tutorial/launch-app-from-url-in-another-app.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/12-x-y, target/13-x-y, target/14-x-y

#30141 test: disable flaky fullscreen test
  spec-main/api-browser-window-spec.ts
Labels: no-backport, semver/none

#29925 docs: add runtime.reload as supported extension api
  docs/api/extensions.md
Labels: semver/none, target/14-x-y

#30121 docs: update supported versions to match new release cadence
  docs/tutorial/support.md
  script/release/version-bumper.js
  spec-main/fixtures/version-bumper/fixture_support.md
Labels: new-pr 🌱, no-backport, semver/none

#26102 feat: add signal option to dialog.showMessageBox
  docs/api/dialog.md
  lib/browser/api/dialog.ts
  shell/browser/api/electron_api_dialog.cc
  shell/browser/ui/message_box.h
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/message_box_mac.mm
  shell/browser/ui/message_box_win.cc
  shell/common/gin_converters/message_box_converter.cc
  spec-main/api-dialog-spec.ts
Labels: api-review/approved ✅, semver/minor, target/14-x-y

#30114 fix: double traffic lights on exit fullscreen
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/13-x-y, target/14-x-y

#30137 fix: pressing ESC should exit fullscreen from webview
  shell/browser/api/electron_api_web_contents.cc
  spec-main/webview-spec.ts
Labels: 12-x-y, backport, semver/patch

#30138 fix: potential crash on macOS app exit
  shell/browser/native_window_mac.mm
Labels: 12-x-y, backport, semver/patch

#29796 fix: handle redirects within registered protocols
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/electron_url_loader_factory.h
  spec-main/api-protocol-spec.ts
  spec-main/api-web-request-spec.ts
Labels: semver/patch, target/13-x-y, target/14-x-y

#30136 fix: BrowserWindow transparency not working
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/14-x-y

#30146 fix: allow colored tray titles when font type is specified
  shell/browser/ui/tray_icon_cocoa.mm
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y

#30185 chore: cherry-pick e76178b896f2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-e76178b896f2.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30177 docs: fix broken context isolation link in sandbox docs
  docs/tutorial/sandbox.md
Labels: no-backport, semver/none

#30175 docs: update default branch for Electron Packager API links
  docs/tutorial/code-signing.md
  docs/tutorial/dark-mode.md
Labels: documentation :notebook:, semver/none, target/13-x-y, target/14-x-y

#30160 chore: remove unused getWebPreferences method
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
  typings/internal-electron.d.ts
Labels: no-backport, semver/patch

#29719 feat: support crashpad on linux
  .circleci/config.yml
  build/zip.py
  patches/chromium/crash_allow_setting_more_options.patch
  script/zip_manifests/dist_zip.linux.arm.manifest
  script/zip_manifests/dist_zip.linux.arm64.manifest
  script/zip_manifests/dist_zip.linux.x64.manifest
  script/zip_manifests/dist_zip.linux.x86.manifest
  shell/app/electron_crash_reporter_client.cc
  shell/app/electron_crash_reporter_client.h
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/electron_browser_client.cc
  spec-main/api-crash-reporter-spec.ts
Labels: no-backport, semver/patch

#30147 docs: mention sandboxing in security docs
  docs/tutorial/security.md
Labels: semver/none, target/14-x-y

#30165 build: update version-bumper to support alpha
  script/release/notes/index.js
  script/release/prepare-release.js
  script/release/publish-to-npm.js
  script/release/version-bumper.js
  script/release/version-utils.js
  spec-main/version-bump-spec.ts
Labels: no-backport, semver/none

#30216 build: handle release failure by exiting with code 1
  script/release/release.js
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y

#30161 chore: add additional crash key to gin::Wrappable
  patches/chromium/.patches
  patches/chromium/add_gin_wrappable_crash_key.patch
  shell/common/crash_keys.cc
  shell/common/crash_keys.h
Labels: semver/patch, target/13-x-y, target/14-x-y

#30218 fix: process.exit crash in nativeWindowOpen
  shell/browser/api/electron_api_browser_window.cc
  spec-main/fixtures/crash-cases/native-window-open-exit/index.html
  spec-main/fixtures/crash-cases/native-window-open-exit/index.js
  spec-main/fixtures/crash-cases/native-window-open-exit/preload.js
Labels: semver/patch, target/14-x-y

#30229 chore: cherry-pick e60cc80ff744 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-e60cc80ff744.patch
Labels: 13-x-y, backport-check-skip, security 🔒, semver/patch

#30196 chore: cherry-pick 3feda0244490 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3feda0244490.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30199 chore: cherry-pick 0e7f91956cec from v8
  patches/v8/.patches
  patches/v8/merged_compiler_fix_a_bug_in.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30203 chore: cherry-pick 5487040a284a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-5487040a284a.patch
Labels: 13-x-y, backport-check-skip, semver/patch

#29474 fix: increase stack size on windows x86
  shell/app/electron_main.cc
  spec-main/fixtures/crash-cases/quit-on-crashed-event/index.js
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30128 fix: pressing ESC should exit fullscreen from webview
  shell/browser/api/electron_api_web_contents.cc
  spec-main/webview-spec.ts
Labels: 13-x-y, backport, semver/patch

#30205 docs: update title of guide
  docs/tutorial/launch-app-from-url-in-another-app.md
Labels: semver/none, target/14-x-y, target/15-x-y

#30251 chore: cherry-pick cd98d7c0dae9 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-cd98d7c0dae9.patch
Labels: 13-x-y, backport-check-skip, security 🔒, semver/patch

#30252 chore: cherry-pick cd98d7c0dae9 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-cd98d7c0dae9.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30253 chore: cherry-pick cd98d7c0dae9 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-cd98d7c0dae9.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30193 refactor: remove base::Value from WebContentsPreferences
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents_mac.mm
  shell/browser/api/electron_api_web_view_manager.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/electron_javascript_dialog_manager.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  spec-main/api-browser-window-spec.ts
Labels: no-backport, semver/patch

#30263 fix: update traffic lights position for macOS 11
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/window_buttons_view.h
  shell/browser/ui/cocoa/window_buttons_view.mm
Labels: new-pr 🌱, semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30209 fix: persist permission granted to serial ports
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/serial/electron_serial_delegate.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/serial/serial_chooser_context.h
  shell/browser/serial/serial_chooser_context_factory.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/serial/serial_chooser_controller.h
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30183 chore: cherry-pick 79fc7bcbc9 from chromium.
  patches/chromium/.patches
  patches/chromium/fix_use-after-free_with_xslt_strip-space.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#29852 fix: type internal APIs that can return null properly
  lib/browser/devtools.ts
  lib/browser/guest-view-manager.ts
  lib/browser/guest-window-manager.ts
  lib/browser/guest-window-proxy.ts
  spec-main/ambient.d.ts
  typings/internal-electron.d.ts
Labels: no-backport, semver/patch

#30275 chore: update publish to npm to use GitHub token
  script/release/publish-to-npm.js
Labels: fast-track 🚅, semver/none, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30069 feat: partially support chrome.tabs.update
  docs/api/extensions.md
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/api/tabs/tabs_api.h
  shell/common/extensions/api/tabs.json
  spec-main/extensions-spec.ts
  spec-main/fixtures/extensions/chrome-api/background.js
  spec-main/fixtures/extensions/chrome-api/main.js
Labels: no-backport, semver/patch

#30272 refactor: move related code to makeWebPreferences in guest-view-manager.ts
  lib/browser/guest-view-manager.ts
Labels: no-backport, semver/patch

#30217 fix: Add missing items to menuItem.role documentation
  docs/api/menu-item.md
Labels: documentation :notebook:, semver/patch, target/14-x-y, target/15-x-y

#30266 chore: cherry-pick ac9dc1235e28 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-ac9dc1235e28.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30265 chore: cherry-pick ac9dc1235e28 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-ac9dc1235e28.patch
Labels: 13-x-y, backport-check-skip, security 🔒, semver/patch

#30246 chore: cherry-pick e38d55313ad9 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-e38d55313ad9.patch
Labels: 13-x-y, backport-check-skip, security 🔒, semver/patch

#30276 test: deflake crashReporter.getLastCrashReport test
  spec-main/api-crash-reporter-spec.ts
  spec-main/spec-helpers.ts
Labels: semver/none, target/15-x-y

#30071 docs: create documentation for browser api
  docs/tutorial/creating-api.md
Labels: no-backport, semver/none

#30313 build: set the export goma auth fallback flag for the control process
  .circleci/config.yml
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30280 refactor: remove guestInstanceId from WebPreferences
  lib/browser/guest-view-manager.ts
  lib/renderer/init.ts
  lib/renderer/web-view/web-view-init.ts
  lib/renderer/window-setup.ts
  lib/sandboxed_renderer/init.ts
  patches/chromium/allow_in-process_windows_to_have_different_web_prefs.patch
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/browser/web_view_manager.cc
  shell/browser/web_view_manager.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/api/electron_api_web_frame.cc
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: no-backport, semver/patch

#30195 chore: cherry-pick 3feda0244490 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3feda0244490.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30198 chore: cherry-pick 0e7f91956cec from v8
  patches/v8/.patches
  patches/v8/merged_compiler_fix_a_bug_in.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30200 chore: cherry-pick e76178b896f2 from v8
  patches/v8/.patches
  patches/v8/merged_json_fix_gc_issue_in_buildjsonobject.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30228 chore: cherry-pick e60cc80ff744 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-e60cc80ff744.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30227 chore: cherry-pick e60cc80ff744 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-e60cc80ff744.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30319 fix: update traffic lights position for macOS 11
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/window_buttons_view.h
  shell/browser/ui/cocoa/window_buttons_view.mm
Labels: 13-x-y, backport, semver/patch

#30267 chore: cherry-pick ac9dc1235e28 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-ac9dc1235e28.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30304 fix: guard against missing native view
  shell/browser/api/electron_api_browser_window_views.cc
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30305 fix: use `contentAspectRatio` in `setAspectRatio()` on macOS
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30237 chore: remove experimental from navigator.serial implementation
  docs/api/session.md
  shell/browser/serial/electron_serial_delegate.cc
  spec-main/chromium-spec.ts
  spec-main/index.js
Labels: api-review/approved ✅, semver/minor, target/14-x-y, target/15-x-y

#30261 chore: cherry-pick 24293de155 from chromium
  patches/chromium/.patches
  patches/chromium/replace_first_of_two_waitableevents_in_creditcardaccessmanager.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#29919 fix: BrowserViews not painting their WebContents
  shell/browser/native_browser_view_views.cc
  shell/browser/native_browser_view_views.h
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: semver/patch, target/14-x-y, target/15-x-y

#30296 chore: cherry-pick 1168f81092 from sqlite
  patches/sqlite/.patches
  patches/sqlite/utf-8_q_when_20constructing_20the_20synthensized_20select_20sta.patch
Labels: 11-x-y, backport-check-skip, security 🔒, semver/patch

#30295 chore: cherry-pick 1168f81092 from sqlite
  patches/config.json
  patches/sqlite/.patches
  patches/sqlite/utf-8_q_when_20constructing_20the_20synthensized_20select_20sta.patch
Labels: 12-x-y, backport-check-skip, security 🔒, semver/patch

#30294 chore: cherry-pick 1168f81092 from sqlite
  patches/config.json
  patches/sqlite/.patches
  patches/sqlite/utf-8_q_when_20constructing_20the_20synthensized_20select_20sta.patch
Labels: 13-x-y, backport-check-skip, security 🔒, semver/patch

#30339 chore: update deps
  yarn.lock
Labels: fast-track 🚅, semver/none, target/11-x-y, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30312 fix: respect LogJsConsoleMessages feature in InspectableWebContents::DidAddMessageToConsole
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, target/14-x-y, target/15-x-y
