Repository electron/electron, pull requests merged in 2021-12, with the labels that each got.

#32049 fix: gtk_native_dialog_run() calls show() internally
  shell/browser/ui/file_dialog_gtk.cc
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32089 fix: avoid double call in OnRefreshComplete on aura platforms (#32052)
  patches/chromium/desktop_media_list.patch
Labels: backport, semver/patch, 16-x-y

#32076 docs: change China mirror domain to npmmirror.com
  README.md
  docs/tutorial/installation.md
Labels: semver/none, no-backport

#31929 chore: cherry-pick 1fcfb942bd from chromium
  patches/chromium/.patches
  patches/chromium/cachestorage_store_partial_opaque_responses.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32055 build: add CI path-filtering for docs-only changes
  .circleci/build_config.yml
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: backport, semver/none, 16-x-y

#32056 build: add CI path-filtering for docs-only changes
  .circleci/build_config.yml
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: backport, semver/none, 15-x-y

#32058 build: add CI path-filtering for docs-only changes
  .circleci/build_config.yml
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: backport, semver/none, 14-x-y

#32097 refactor: use process type specific electron imports in default_app
  default_app/default_app.ts
  default_app/main.ts
  default_app/preload.ts
Labels: semver/none, no-backport

#32057 fix: window.open not overriding parent's webPreferences
  docs/api/window-open.md
  lib/browser/api/web-contents.ts
  lib/browser/guest-window-manager.ts
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_render_frame_observer.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
  spec-main/chromium-spec.ts
  spec-main/fixtures/crash-cases/setimmediate-window-open-crash/index.html
  spec/chromium-spec.js
  spec/static/main.js
Labels: security 🔒, semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32094 docs: Fix environment variable name
  docs/tutorial/installation.md
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32173 docs: update discord server URL in tutorial/introduction.md
  docs/tutorial/introduction.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/16-x-y, target/17-x-y

#32178 fix: ensure bluetooth devices are not returned by default
  docs/api/web-contents.md
  lib/browser/api/web-contents.ts
Labels: semver/patch, fast-track 🚅, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32046 fix: older systems crash when playing media files
  patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32229 chore: manually revert 13.6.4
  ELECTRON_VERSION
  package.json
  shell/browser/resources/win/electron.rc
Labels: backport-check-skip, semver/none

#32240 fix: check for single bluetooth listener
  lib/browser/api/web-contents.ts
Labels: fast-track 🚅, semver/none, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32194 chore: cherry-pick 418c276ef228 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-418c276ef228.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32193 chore: cherry-pick 418c276ef228 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-418c276ef228.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y
