Repository electron/electron, pull requests merged in 2021-09, with the labels that each got.

#30740 docs: improve documentation about macOS entitlement usage security
  docs/tutorial/code-signing.md
Labels: semver/none, target/13-x-y, target/14-x-y, target/15-x-y

#30716 fix(linux): OpenURI portal support for `shell.showItemInFolder()`
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30690 docs: fix code example in process-model.md
  docs/tutorial/process-model.md
Labels: documentation :notebook:, semver/none, no-backport

#30638 chore: cherry-pick fix for 1230767 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1230767.patch
Labels: semver/patch, backport-check-skip, target/11-x-y, target/12-x-y

#30785 ci: ignore pdb download failure on WOA
  azure-pipelines-woa.yml
Labels: semver/none, target/14-x-y, target/15-x-y

#29290 feat: add 'dom-ready' event to WebFrameMain
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_converters/frame_converter.cc
  shell/common/gin_converters/frame_converter.h
  shell/common/gin_helper/accessor.h
  shell/common/gin_helper/dictionary.h
  spec-main/api-web-frame-main-spec.ts
  spec-main/fixtures/sub-frames/frame-container.html
  spec-main/fixtures/sub-frames/frame-with-frame.html
Labels: semver/minor, api-review/requested 🗳, target/15-x-y

#29695 fix: remove extension warning that do not have any impact
  shell/browser/extensions/electron_extension_loader.cc
Labels: semver/patch, no-backport

#30799 ci: fix setCertificateVerifyProc tests
  spec-main/api-session-spec.ts
Labels: fast-track 🚅, semver/none, no-backport

#30802 docs: fix code example in process-model.md (#30690)
  docs/tutorial/process-model.md
Labels: documentation :notebook:, backport, semver/none, 15-x-y

#30800 docs: fix code example in process-model.md
  docs/tutorial/process-model.md
Labels: documentation :notebook:, backport, semver/none, 14-x-y

#30777 fix: BrowserWindow backgroundColor
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, backport-check-skip, target/14-x-y

#30721 feat: deprecate desktopCapturer.getSources in the renderer
  docs/breaking-changes.md
  lib/renderer/api/desktop-capturer.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, no-backport

#30825 build: temporarily revert broken dump_syms changes in breakpad
  patches/breakpad/.patches
  patches/breakpad/revert_add_inline_and_inline_origin_records_to_symbol_file.patch
  patches/breakpad/revert_remove_warning_about_unknown_abstract_origin.patch
  patches/config.json
Labels: fast-track 🚅, semver/none, no-backport

#30826 docs: move module creation guide to` /development`
  docs/development/creating-api.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, no-backport

#30820 fix: remove CHECK_EQ for swapped RFH
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, backport-check-skip, target/12-x-y, target/13-x-y

#30822 chore: cherry-pick fbfd2557c2ab from v8
  patches/v8/.patches
  patches/v8/cherry-pick-fbfd2557c2ab.patch
Labels: semver/patch, backport-check-skip, 12-x-y

#30594 refactor: Convert ProcessSingleton changes to patch
  chromium_src/BUILD.gn
  chromium_src/chrome/browser/process_singleton.h
  chromium_src/chrome/browser/process_singleton_posix.cc
  chromium_src/chrome/browser/process_singleton_win.cc
  filenames.gni
  patches/chromium/.patches
  patches/chromium/process_singleton.patch
  shell/app/command_line_args.cc
  shell/app/command_line_args.h
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  spec-main/api-app-spec.ts
Labels: semver/patch, no-backport

#30685 refactor: simplify desktop_capturer patch
  patches/chromium/desktop_media_list.patch
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_desktop_capturer.h
Labels: semver/patch, no-backport

#30816 chore: cherry-pick d727013bb543 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-d727013bb543.patch
Labels: semver/patch, backport-check-skip, 12-x-y

#30815 chore: cherry-pick d727013bb543 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-d727013bb543.patch
Labels: semver/patch, backport-check-skip, 13-x-y

#30821 chore: cherry-pick fbfd2557c2ab from v8
  patches/v8/.patches
  patches/v8/cherry-pick-fbfd2557c2ab.patch
Labels: semver/patch, backport-check-skip, 13-x-y

#30818 chore: cherry-pick d1eade9d39 from chromium
  patches/chromium/.patches
  patches/chromium/merge_m92_speculative_fix_for_crash_in.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30837 chore: move global_menu_bar_registrar_x11 out of chromium_src
  filenames.gni
  shell/browser/ui/views/global_menu_bar_registrar_x11.cc
  shell/browser/ui/views/global_menu_bar_registrar_x11.h
  shell/browser/ui/views/global_menu_bar_x11.cc
Labels: semver/none, no-backport

#30835 chore: follow-up to roll 95.0.4612.5
  build/args/all.gn
  patches/chromium/.patches
  patches/chromium/feat_expose_raw_response_headers_from_urlloader.patch
  patches/chromium/fix_expose_decrementcapturercount_in_web_contents_impl.patch
  patches/v8/.patches
  patches/v8/cppgc-js_support_eager_traced_value_in_ephemeron_pairs.patch
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_url_loader.cc
Labels: semver/none, no-backport

#30823 fix: undocked devtools not resizable on Windows
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
Labels: semver/patch, target/14-x-y, target/15-x-y

#30778 fix: BrowserWindow backgroundColor
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  spec-main/fixtures/snapshots/native-window-open.snapshot.txt
  spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
Labels: semver/patch, no-backport

#30768 docs: updated webview tag docs to reflect preload behavior with .asar
  docs/api/webview-tag.md
Labels: documentation :notebook:, semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30838 chore: move native-image.ts back into common
  filenames.auto.gni
  lib/browser/api/module-list.ts
  lib/common/api/module-list.ts
  lib/common/api/native-image.ts
  lib/renderer/api/module-list.ts
  lib/renderer/api/native-image.ts
  lib/sandboxed_renderer/api/module-list.ts
Labels: semver/none, no-backport

#30817 chore: cherry-pick d1eade9d39 from chromium
  patches/chromium/.patches
  patches/chromium/merge_m92_speculative_fix_for_crash_in.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30830 refactor: use getter for frame in webrequest details
  shell/browser/api/electron_api_web_request.cc
Labels: semver/none, target/15-x-y

#30853 chore: enable v8 oilpan
  build/args/all.gn
  patches/v8/.patches
  patches/v8/cppgc-js_fix_snapshot_node_merging.patch
  patches/v8/cppgc-js_support_eager_traced_value_in_ephemeron_pairs.patch
Labels: semver/patch, backport-check-skip, 15-x-y

#30804 fix: show maximized frameless window
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y

#30538 docs: Update windows info for auto-updater
  docs/api/auto-updater.md
Labels: documentation :notebook:, semver/none, target/13-x-y, target/14-x-y, target/15-x-y

#30729 feat: serialize NativeImage over ipc
  filenames.auto.gni
  lib/browser/guest-view-manager.ts
  lib/browser/rpc-server.ts
  lib/common/api/clipboard.ts
  lib/common/ipc-messages.ts
  lib/common/type-utils.ts
  lib/common/web-view-methods.ts
  lib/renderer/api/desktop-capturer.ts
  lib/renderer/web-view/guest-view-internal.ts
  lib/renderer/web-view/web-view-impl.ts
  shell/common/api/electron_api_native_image.h
  shell/common/v8_value_serializer.cc
  shell/renderer/renderer_client_base.cc
  typings/internal-ambient.d.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#30742 feat: warn when crash key name is longer than 39 bytes
  shell/common/crash_keys.cc
Labels: semver/patch, no-backport

#30824 chore: cherry-pick 490c04beac from chromium
  patches/chromium/.patches
  patches/chromium/attach_to_correct_frame_in.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30832 docs(protocols): simplify packaging section & cleanup
  docs/tutorial/launch-app-from-url-in-another-app.md
Labels: documentation :notebook:, semver/none, target/14-x-y, target/15-x-y

#30855 refactor: remove dead code in NeedsCompleteGpuInfoCollection
  shell/browser/api/gpuinfo_manager.cc
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30852 fix: crash when navigating with render process reuse disabled
  shell/browser/api/electron_api_web_contents.cc
  spec-main/fixtures/crash-cases/api-web-frame-main-connect/index.html
  spec-main/fixtures/crash-cases/api-web-frame-main-connect/index.js
Labels: semver/patch, backport-check-skip, 13-x-y

#30881 docs(protocols): simplify packaging section & cleanup
  docs/tutorial/launch-app-from-url-in-another-app.md
Labels: backport, semver/none, 15-x-y

#30882 docs(protocols): simplify packaging section & cleanup
  docs/tutorial/launch-app-from-url-in-another-app.md
Labels: backport, semver/none, 14-x-y

#30893 fix: crash when launching app with systemd v249
  patches/chromium/.patches
  patches/chromium/pa_make_getusablesize_handle_nullptr_gracefully.patch
Labels: semver/patch, backport-check-skip, 13-x-y

#30667 feat: add support for validating asar archives on macOS
  BUILD.gn
  build/asar.gni
  build/fuses/fuses.json5
  filenames.gni
  lib/asar/fs-wrapper.ts
  lib/browser/init.ts
  package.json
  script/gn-asar-hash.js
  script/gn-plist-but-with-hashes.js
  shell/browser/net/asar/asar_file_validator.cc
  shell/browser/net/asar/asar_file_validator.h
  shell/browser/net/asar/asar_url_loader.cc
  shell/browser/resources/mac/Info.plist
  shell/common/api/electron_api_asar.cc
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
  shell/common/asar/archive_mac.mm
  shell/common/asar/asar_util.cc
  shell/common/asar/asar_util.h
  shell/common/asar/scoped_temporary_file.cc
  shell/common/asar/scoped_temporary_file.h
  shell/common/node_bindings.cc
  spec-main/node-spec.ts
  spec/asar-spec.js
  spec/fixtures/test.asar/a.asar
  spec/fixtures/test.asar/echo.asar
  spec/fixtures/test.asar/empty.asar
  spec/fixtures/test.asar/logo.asar
  spec/fixtures/test.asar/repack.js
  spec/fixtures/test.asar/script.asar
  spec/fixtures/test.asar/unpack.asar
  spec/fixtures/test.asar/video.asar
  spec/fixtures/test.asar/web.asar
  typings/internal-ambient.d.ts
  yarn.lock
Labels: semver/minor, api-review/requested 🗳, target/15-x-y

#30903 chore: upstream changes from 15-x-y ASAR validation PR
  shell/browser/net/asar/asar_file_validator.cc
  shell/browser/net/asar/asar_file_validator.h
  shell/browser/net/asar/asar_url_loader.cc
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
Labels: fast-track 🚅, semver/none, no-backport

#30916 fix: only delete render_frame_host_ after OnDialogDone completes
  shell/browser/file_select_helper.cc
Labels: semver/patch, target/15-x-y

#30935 fix: remove conflicting RunFileChooserEnd for Mac
  shell/browser/file_select_helper.cc
Labels: semver/patch, fast-track 🚅, target/15-x-y

#30663 refactor: reuse upstream //shell_dialogs
  chromium_src/BUILD.gn
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/file_select_helper.cc
  shell/browser/file_select_helper.h
  shell/browser/web_dialog_helper.cc
  shell/browser/web_dialog_helper.h
Labels: semver/patch, target/15-x-y

#30928 fix: PepperFlashFontFileHost not included when disabling pdf viewer
  chromium_src/BUILD.gn
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30913 fix: Building on macOS with is_debug true
  shell/common/platform_util_mac.mm
Labels: semver/none, no-backport

#30905 chore: correct hierarchy of BrowserWindow headings
  docs/api/browser-window.md
Labels: documentation :notebook:, semver/none, target/14-x-y, target/15-x-y

#30898 docs: update context isolation doc
  docs/tutorial/context-isolation.md
Labels: documentation :notebook:, semver/none, target/14-x-y, target/15-x-y

#30930 fix: prevent navigator.fonts.query() from crashing
  filenames.gni
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/font/electron_font_access_delegate.cc
  shell/browser/font/electron_font_access_delegate.h
Labels: semver/patch, target/14-x-y, target/15-x-y

#30940 chore: cherry-pick 034c2003be31 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-034c2003be31.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30978 docs: add link to @electron/fuses
  docs/tutorial/fuses.md
Labels: new-pr 🌱, semver/none, no-backport

#30774 chore: update E16 node module version
  build/args/all.gn
Labels: semver/none, no-backport

#30772 chore: update E14 node module version
  build/args/all.gn
Labels: backport-check-skip, semver/none

#30773 chore: update E15 node module version
  build/args/all.gn
Labels: backport-check-skip, semver/none

#30698 feat: enable window controls overlay on macOS (#29253)
  docs/api/browser-window.md
  docs/api/frameless-window.md
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_observer.h
  shell/browser/ui/cocoa/window_buttons_proxy.h
  shell/browser/ui/cocoa/window_buttons_proxy.mm
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/pages/overlay.html
Labels: backport, semver/minor, backport/approved ✅, 13-x-y

#30938 fix: add casing for WCO edge
  shell/browser/ui/views/win_frame_view.cc
Labels: semver/patch, target/14-x-y, target/15-x-y

#30945 chore: cherry-pick 8623d711677d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-8623d711677d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30965 chore: cherry pick 9723e3c13c from chromium
  patches/chromium/.patches
  patches/chromium/content-visibility_force_range_base_extent_when_computing_visual.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30990 fix: links to images
  docs/tutorial/performance.md
  docs/tutorial/progress-bar.md
Labels: documentation :notebook:, semver/patch, target/14-x-y, target/15-x-y

#30959 chore: update links of documentation of chromes in comments
  typings/internal-electron.d.ts
Labels: documentation :notebook:, semver/none, target/13-x-y, target/14-x-y, target/15-x-y

#30999 fix: disabling and enabling resizability on macOS
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30920 refactor: make `InitWithWebContents` and `InspectableWebContents` take a `unique_ptr`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, target/14-x-y, target/15-x-y

#31027 fix: ensure web_contents() is alive before grabbing view
  shell/browser/api/electron_api_browser_window_views.cc
Labels: backport, semver/patch, 15-x-y

#30939 chore: cherry-pick 034c2003be31 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-034c2003be31.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30942 chore: cherry-pick 7699615c0d and 2f5740f50f from chromium
  patches/chromium/.patches
  patches/chromium/m93_indexeddb_add_browser-side_checks_for_committing_transactions.patch
  patches/chromium/m93_indexeddb_don_t_reportbadmessage_for_commit_calls.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30941 chore: cherry-pick 7699615c0d and 2f5740f50f from chromium
  patches/chromium/.patches
  patches/chromium/m93_indexeddb_add_browser-side_checks_for_committing_transactions.patch
  patches/chromium/m93_indexeddb_don_t_reportbadmessage_for_commit_calls.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30957 chore: cherry-pick 13842c96c2 from chromium and 018f85dea1 from angle
  patches/angle/.patches
  patches/angle/webgl_make_unsuccessful_links_fail_subsequent_draw_calls.patch
  patches/chromium/.patches
  patches/chromium/skip_webgl_conformance_programs_program-test_html_on_all_platforms.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30958 chore: cherry-pick 13842c96c2 from chromium and 018f85dea1 from angle
  patches/angle/.patches
  patches/angle/webgl_make_unsuccessful_links_fail_subsequent_draw_calls.patch
  patches/chromium/.patches
  patches/chromium/skip_webgl_conformance_programs_program-test_html_on_all_platforms.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30987 chore: add wg-security as required reviewer for security-warnings.ts
  .github/CODEOWNERS
Labels: semver/none, no-backport

#31003 fix: transparency on child windows being lost
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/14-x-y, target/15-x-y

#30944 chore: cherry-pick 6048fcd52f42 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6048fcd52f42.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30950 chore: cherry-pick 0c6f5c65fa from chromium
  patches/chromium/.patches
  patches/chromium/contentindex_add_origin_checks_to_mojo_methods.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30951 chore: cherry-pick 0c6f5c65fa from chromium
  patches/chromium/.patches
  patches/chromium/contentindex_add_origin_checks_to_mojo_methods.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30943 chore: cherry-pick 6048fcd52f42 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6048fcd52f42.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30946 chore: cherry-pick 8623d711677d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-8623d711677d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30960 chore: cherry-pick 72473550f6ff from angle
  patches/angle/.patches
  patches/angle/cherry-pick-72473550f6ff.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30961 chore: cherry-pick 72473550f6ff from angle
  patches/angle/.patches
  patches/angle/cherry-pick-72473550f6ff.patch
Labels: semver/patch, backport-check-skip, 12-x-y

#30962 chore: cherry-pick ddc4cf156505 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-ddc4cf156505.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30885 fix: suppress insecure resource warning for more local hostnames
  lib/renderer/security-warnings.ts
  spec-main/index.js
  spec-main/security-warnings-spec.ts
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#30879 feat: add isMainFrame argument to 'certificate-error' event
  docs/api/app.md
  docs/api/web-contents.md
  shell/browser/api/electron_api_app.cc
Labels: semver/minor, api-review/approved ✅, target/15-x-y

#30952 chore: cherry-pick 6215793f008f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6215793f008f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30953 chore: cherry-pick 6215793f008f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6215793f008f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30989 fix: maximized state calculation for non-resizable windows
  docs/api/browser-window.md
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y

#31031 fix: propagate window.open settings to child window
  lib/browser/api/web-contents.ts
Labels: semver/patch, new-pr 🌱, target/14-x-y, target/15-x-y

#31000 docs: update public timeline for E16
  docs/tutorial/electron-timelines.md
Labels: semver/none, target/14-x-y, target/15-x-y

#30963 chore: cherry-pick ddc4cf156505 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-ddc4cf156505.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#30964 chore: cherry pick 9723e3c13c from chromium
  patches/chromium/.patches
  patches/chromium/content-visibility_force_range_base_extent_when_computing_visual.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#30874 docs: update glossary
  docs/glossary.md
Labels: documentation :notebook:, semver/none, target/14-x-y, target/15-x-y

#30831 feat: add frame to context-menu event params
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/content_converter.h
  spec-main/api-web-contents-spec.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/15-x-y

#30888 fix: proper localization when using GtkFileChooserNative
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/gtk_util.cc
  shell/browser/ui/gtk_util.h
  shell/browser/ui/message_box_gtk.cc
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31069 chore: clarify new-window fix comment
  lib/browser/api/web-contents.ts
Labels: new-pr 🌱, semver/none, target/14-x-y, target/15-x-y, target/16-x-y

#31021 fix: update Windows' cache after changing window's style
  shell/browser/native_window_views.cc
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31034 fix: startDrag params type incorrect
  docs/api/web-contents.md
Labels: documentation :notebook:, semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#30474 feat: add textWidth option to dialog.showMessageBox()
  docs/api/dialog.md
  lib/browser/api/dialog.ts
  shell/browser/ui/message_box.h
  shell/browser/ui/message_box_mac.mm
  shell/common/gin_converters/message_box_converter.cc
Labels: semver/minor, api-review/approved ✅, target/15-x-y, target/16-x-y

#30213 feat: add support for WebHID
  BUILD.gn
  docs/api/session.md
  docs/api/structures/hid-device.md
  docs/fiddles/features/web-bluetooth/index.html
  docs/fiddles/features/web-bluetooth/main.js
  docs/fiddles/features/web-bluetooth/renderer.js
  docs/fiddles/features/web-hid/index.html
  docs/fiddles/features/web-hid/main.js
  docs/fiddles/features/web-hid/renderer.js
  docs/fiddles/features/web-serial/index.html
  docs/fiddles/features/web-serial/main.js
  docs/fiddles/features/web-serial/renderer.js
  docs/tutorial/devices.md
  electron_strings.grdp
  filenames.auto.gni
  filenames.gni
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/electron_hid_delegate.h
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/hid/hid_chooser_context.h
  shell/browser/hid/hid_chooser_context_factory.cc
  shell/browser/hid/hid_chooser_context_factory.h
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/hid/hid_chooser_controller.h
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
  shell/common/gin_converters/content_converter.cc
  spec-main/chromium-spec.ts
Labels: semver/minor, api-review/requested 🗳, target/14-x-y, target/15-x-y, target/16-x-y

#30887 feat: enable windows control overlay on Windows
  chromium_src/BUILD.gn
  docs/api/browser-window.md
  docs/api/frameless-window.md
  docs/api/structures/overlay-options.md
  electron_strings.grdp
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/dpwas_window_control_overlay_api_values_account_for_page_zoom_factor.patch
  patches/chromium/reland_make_clientview_a_child_of_the_nonclientframeview.patch
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/ui/views/frameless_view.cc
  shell/browser/ui/views/frameless_view.h
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_caption_button.h
  shell/browser/ui/views/win_caption_button_container.cc
  shell/browser/ui/views/win_caption_button_container.h
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 13-x-y

#31091 fix: crash in seccomp sandbox with glibc 2.34
  patches/chromium/.patches
  patches/chromium/linux_sandbox_return_enosys_for_clone3.patch
  patches/chromium/linux_sandbox_update_syscall_numbers_for_all_platforms.patch
Labels: semver/patch, backport-check-skip, target/12-x-y, 13-x-y

#31062 fix: first mouse not dragging BrowserView
  shell/browser/native_browser_view_mac.mm
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31075 chore: remove gin::Wrappable crash keys
  patches/chromium/.patches
  patches/chromium/add_gin_wrappable_crash_key.patch
  shell/common/crash_keys.cc
  shell/common/crash_keys.h
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y

#31077 test: re-enable some Node.js specs
  patches/node/fix_crypto_tests_to_run_with_bssl.patch
  script/node-disabled-tests.json
Labels: semver/patch, no-backport

#31086 chore: remove obsolete chunk of BoringSSL patch
  patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
Labels: semver/patch, new-pr 🌱, no-backport

#31104 fix: avoid double free when destroying WebContents
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31125 refactor: make `InitWithWebContents` and `InspectableWebContents` take a `unique_ptr`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: backport, semver/patch, 14-x-y

#31087 fix: crash creating private key with unsupported algorithm
  patches/node/.patches
  patches/node/fix_crash_creating_private_key_with_unsupported_algorithm.patch
  spec/node-spec.js
Labels: semver/patch, target/15-x-y, target/16-x-y

#31092 fix: running tests with release build
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/common/api/electron_api_v8_util.cc
  spec-main/api-menu-item-spec.ts
  typings/internal-electron.d.ts
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31102 fix: crash in v8 due to regexp reentrancy
  patches/v8/.patches
  patches/v8/regexp_add_a_currently_failing_cctest_for_irregexp_reentrancy.patch
  patches/v8/regexp_allow_reentrant_irregexp_execution.patch
  patches/v8/regexp_remove_the_stack_parameter_from_regexp_matchers.patch
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31106 docs: Update Branch Name
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/mac_app_store_private_api_rejection.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  docs/breaking-changes.md
  docs/development/README.md
  docs/development/azure-vm-setup.md
  docs/development/build-instructions-gn.md
  docs/development/electron-vs-nwjs.md
  docs/development/pull-requests.md
  docs/tutorial/fuses.md
  docs/tutorial/security.md
  docs/tutorial/support.md
Labels: semver/none, target/15-x-y, target/16-x-y

#31097 fix: add casing for WCO edge
  shell/browser/ui/views/win_frame_view.cc
Labels: backport, semver/patch, 13-x-y

#31108 fix: .lldbinit config stale (unavailable)
  docs/development/debugging-instructions-macos.md
Labels: target/12-x-y, semver/none, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31153 refactor: use native WeakRef instead of v8util.weaklyTrackValue()
  shell/common/api/electron_api_v8_util.cc
  spec-main/api-context-bridge-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/patch, fast-track 🚅, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31114 fix: BrowserView drag now delegates to the OS when possible
  shell/browser/native_browser_view_mac.mm
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31162 fix: ensure set vibrancy with invalid value is a no-op
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.h
Labels: backport, semver/patch, 14-x-y

#31148 fix: running tests with release build
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/common/api/electron_api_v8_util.cc
  spec-main/api-menu-item-spec.ts
  typings/internal-electron.d.ts
Labels: backport, semver/patch, 14-x-y

#31095 feat: add support for WebHID
  BUILD.gn
  docs/api/session.md
  docs/api/structures/hid-device.md
  docs/fiddles/features/web-bluetooth/index.html
  docs/fiddles/features/web-bluetooth/main.js
  docs/fiddles/features/web-bluetooth/renderer.js
  docs/fiddles/features/web-hid/index.html
  docs/fiddles/features/web-hid/main.js
  docs/fiddles/features/web-hid/renderer.js
  docs/fiddles/features/web-serial/index.html
  docs/fiddles/features/web-serial/main.js
  docs/fiddles/features/web-serial/renderer.js
  docs/tutorial/devices.md
  electron_strings.grdp
  filenames.auto.gni
  filenames.gni
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/electron_hid_delegate.h
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/hid/hid_chooser_context.h
  shell/browser/hid/hid_chooser_context_factory.cc
  shell/browser/hid/hid_chooser_context_factory.h
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/hid/hid_chooser_controller.h
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
  shell/common/gin_converters/content_converter.cc
  spec-main/chromium-spec.ts
Labels: backport, semver/minor, backport/requested 🗳, target/14-x-y, 15-x-y

#31169 refactor: use native WeakRef instead of v8util.weaklyTrackValue()
  shell/common/api/electron_api_v8_util.cc
  spec-main/api-context-bridge-spec.ts
  typings/internal-ambient.d.ts
Labels: backport, semver/patch, 13-x-y

#31124 refactor: make `InitWithWebContents` and `InspectableWebContents` take a `unique_ptr`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: backport, semver/patch, 15-x-y

#31189 chore: remove gin::Wrappable crash keys
  patches/chromium/.patches
  patches/chromium/add_gin_wrappable_crash_key.patch
  shell/common/crash_keys.cc
  shell/common/crash_keys.h
Labels: backport, semver/none, 15-x-y

#31187 fix: ensure web_contents() is alive before grabbing view
  shell/browser/api/electron_api_browser_window_views.cc
Labels: backport, semver/patch, 14-x-y

#31188 chore: remove gin::Wrappable crash keys
  patches/chromium/.patches
  patches/chromium/add_gin_wrappable_crash_key.patch
  shell/common/crash_keys.cc
  shell/common/crash_keys.h
Labels: backport, semver/none, 14-x-y

#31156 build: Explicitly pass the project root to cpplint.py
  script/lint.js
Labels: semver/none, no-backport

#31147 fix: running tests with release build
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/common/api/electron_api_v8_util.cc
  spec-main/api-menu-item-spec.ts
  typings/internal-electron.d.ts
Labels: backport, semver/patch, 13-x-y

#31085 fix: draggable regions in `BrowserView`s are independent
  shell/browser/api/electron_api_browser_window_mac.mm
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31184 chore: remove redundant 10.11 @available checks
  shell/browser/mac/electron_application.mm
  shell/browser/native_window_mac.mm
  shell/browser/ui/tray_icon_cocoa.mm
Labels: semver/patch, new-pr 🌱, no-backport

#31207 chore: fix pylint
  script/lib/git.py
  script/lib/native_tests.py
  script/lint.js
  script/patches-mtime-cache.py
  script/release/uploaders/upload.py
  script/verify-ffmpeg.py
Labels: backport, semver/none, 15-x-y

#31211 chore: cherry-pick f8a74d72f3 from chromium.
  patches/chromium/.patches
  patches/chromium/content-visibility_add_a_clipper_fix_for_content-visibility.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#31210 chore: cherry-pick f8a74d72f328 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f8a74d72f328.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31209 chore: cherry-pick f8a74d72f3 from chromium.
  patches/chromium/.patches
  patches/chromium/content-visibility_add_a_clipper_fix_for_content-visibility.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31213 fix: Enable X509_V_FLAG_TRUSTED_FIRST flag in BoringSSL
  patches/boringssl/.patches
  patches/boringssl/enable_x509_v_flag_trusted_first_flag.patch
Labels: semver/patch, fast-track 🚅, target/12-x-y, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31201 chore: fix pylint
  script/lib/git.py
  script/lib/native_tests.py
  script/lint.js
  script/patches-mtime-cache.py
  script/release/uploaders/upload.py
  script/verify-ffmpeg.py
Labels: backport, semver/none, 16-x-y
