Repository electron/electron, pull requests merged in 2021-11, with the labels that each got.

#31620 fix: crash on close window when webContents destroyed
  shell/browser/api/electron_api_browser_window.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31626 fix: use disable-hid-blocklist to allow FIDO devices
  shell/browser/hid/electron_hid_delegate.cc
Labels: semver/patch, target/15-x-y, target/16-x-y

#31623 fix: clipboard.read() to work consistently with clipboard.readBuffer()
  docs/api/clipboard.md
  shell/common/api/electron_api_clipboard.cc
  spec/api-clipboard-spec.js
Labels: semver/patch, target/15-x-y, target/16-x-y

#31616 fix: silent print settings
  patches/chromium/printing.patch
Labels: backport, semver/patch, 15-x-y

#31617 fix: silent print settings
  patches/chromium/printing.patch
Labels: backport, semver/patch, 14-x-y

#31628 chore: update chore_add_context_to_context_aware_module_prevention.patch
  patches/node/chore_add_context_to_context_aware_module_prevention.patch
Labels: backport, semver/patch, 15-x-y

#31618 fix: silent print settings
  patches/chromium/printing.patch
Labels: backport, semver/patch, 13-x-y

#31629 chore: update chore_add_context_to_context_aware_module_prevention.patch
  patches/node/chore_add_context_to_context_aware_module_prevention.patch
Labels: backport, semver/patch, 16-x-y

#31654 test: fix test-datetime-change-notify after daylight change
  patches/node/.patches
  patches/node/test_fix_test-datetime-change-notify_after_daylight_change.patch
Labels: semver/patch, target/15-x-y, target/16-x-y

#31627 chore: update chore_add_context_to_context_aware_module_prevention.patch
  patches/node/chore_add_context_to_context_aware_module_prevention.patch
Labels: backport, semver/patch, 14-x-y

#31606 fix: do not run dialog callback inside transaction commit
  script/lint.js
  shell/browser/ui/file_dialog_mac.mm
  shell/browser/ui/message_box_mac.mm
  shell/common/gin_helper/promise.h
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31664 chore: cherry-pick feef10137b16 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-feef10137b16.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31665 chore: cherry-pick feef10137b16 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-feef10137b16.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31666 chore: cherry-pick feef10137b16 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-feef10137b16.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#31670 chore: cherry-pick 45f9dcf5021d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-45f9dcf5021d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31672 chore: cherry-pick 014e1f857c33 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-014e1f857c33.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31674 chore: cherry-pick 014e1f857c33 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-014e1f857c33.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#31669 fix: incorrect Content-Disposition serialization
  shell/browser/api/electron_api_web_request.cc
  spec-main/api-web-request-spec.ts
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31678 chore: cherry-pick 656c2769c5 from v8
  patches/v8/.patches
  patches/v8/merged_cppgc_fix_marking_of_ephemerons_with_keys_in_construction.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31673 chore: cherry-pick 014e1f857c33 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-014e1f857c33.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31676 refactor: use upstream AutofillDriverFactory diffs
  shell/browser/electron_autofill_driver.cc
  shell/browser/electron_autofill_driver.h
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_autofill_driver_factory.h
  shell/browser/electron_browser_client.cc
Labels: semver/patch, no-backport

#31681 chore: cherry-pick 91dd4f79ab5b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-91dd4f79ab5b.patch
Labels: semver/patch, backport-check-skip, 14-x-y

#31685 fix: apply transparency settings to WebContentsPreferences
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/web_contents_preferences.cc
Labels: semver/patch, new-pr 🌱, target/16-x-y

#31677 chore: cherry-pick 656c2769c5 from v8
  patches/v8/.patches
  patches/v8/merged_cppgc_fix_marking_of_ephemerons_with_keys_in_construction.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31661 fix: second-instance additionalData parameter
  patches/chromium/feat_add_data_parameter_to_processsingleton.patch
  spec-main/api-app-spec.ts
  spec/fixtures/api/singleton-data/main.js
  spec/fixtures/api/singleton/main.js
Labels: semver/patch, target/16-x-y

#31699 docs: update test automation doc
  docs/README.md
  docs/tutorial/accessibility.md
  docs/tutorial/automated-testing-with-a-custom-driver.md
  docs/tutorial/automated-testing.md
  docs/tutorial/using-selenium-and-webdriver.md
Labels: backport, semver/none, 15-x-y

#31683 chore: cherry-pick 91dd4f79ab5b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-91dd4f79ab5b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 12-x-y

#31668 fix: crash dump location on Linux
  shell/app/electron_main_delegate.cc
  shell/browser/electron_browser_client.cc
Labels: semver/patch, target/15-x-y, target/16-x-y

#31702 test: deflake <webview> tag loads devtools extensions on WOA
  spec-main/fixtures/devtools-extensions/foo/panel.js
Labels: target/12-x-y, semver/none, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y

#31116 fix: clipboard.writeBuffer raw format access
  patches/chromium/.patches
  patches/chromium/add_ui_scopedcliboardwriter_writeunsaferawdata.patch
  shell/common/api/electron_api_clipboard.cc
  spec/api-clipboard-spec.js
Labels: semver/patch, target/15-x-y, target/16-x-y

#31680 chore: cherry-pick 91dd4f79ab5b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-91dd4f79ab5b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31682 chore: cherry-pick 91dd4f79ab5b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-91dd4f79ab5b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31701 fix: <webview> background transparency
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, backport-check-skip, target/14-x-y

#31722 fix: <webview> background transparency
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/16-x-y

#31631 refactor: move certificate_manager_model to shell
  BUILD.gn
  filenames.gni
  package.json
  shell/browser/api/electron_api_app.h
  shell/browser/certificate_manager_model.cc
  shell/browser/certificate_manager_model.h
Labels: semver/patch, target/16-x-y

#31729 chore: remove Breakpad tests for crashReporter on Linux
  spec-main/api-crash-reporter-spec.ts
Labels: semver/patch, target/16-x-y

#31730 refactor: remove duplicate contextIsolation from getWebPreference()
  lib/renderer/api/context-bridge.ts
  lib/renderer/init.ts
  lib/renderer/web-view/web-view-init.ts
  lib/sandboxed_renderer/init.ts
  shell/renderer/api/electron_api_web_frame.cc
  spec/fixtures/api/window-open-preload.js
  typings/internal-ambient.d.ts
Labels: semver/patch, no-backport

#31750 test: fix crash in electron::NativeWindowMac::Close()
  spec-main/api-browser-window-spec.ts
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y

#31756 chore: delete unused lib/common/remote/ipc-messages.ts
  lib/common/remote/ipc-messages.ts
Labels: new-pr 🌱, semver/none, target/14-x-y, target/15-x-y, target/16-x-y

#31748 fix: failing Node.js certificate spec
  patches/node/.patches
  patches/node/test_add_fixture_trim_option.patch
  script/node-disabled-tests.json
Labels: semver/patch, target/16-x-y

#31746 fix: BrowserView setBackgroundColor()
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#31755 refactor: merge duplicate code from sandboxed/non-sandboxed renderer init
  filenames.auto.gni
  lib/renderer/common-init.ts
  lib/renderer/init.ts
  lib/renderer/security-warnings.ts
  lib/sandboxed_renderer/init.ts
Labels: semver/patch, no-backport

#31757 fix: generate angle brackets in release notes
  script/release/notes/notes.js
Labels: semver/none, no-backport

#31780 chore: move libs only used in browser out of common
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  lib/browser/guest-view-manager.ts
  lib/browser/guest-window-manager.ts
  lib/browser/parse-features-string.ts
  lib/browser/web-view-events.ts
  spec-main/internal-spec.ts
Labels: semver/patch, new-pr 🌱, no-backport

#31786 docs: Update E17 release dates
  docs/tutorial/electron-timelines.md
Labels: new-pr 🌱, semver/none, target/16-x-y, target/17-x-y

#31804 fix: crash caused by GetHostNameW on Windows 7
  patches/node/.patches
  patches/node/fix_crash_caused_by_gethostnamew_on_windows_7.patch
Labels: semver/patch, target/16-x-y

#31799 fix: in GTK open dialog, do not preview huge files
  shell/browser/ui/file_dialog_gtk.cc
Labels: component/dialog, semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31798 fix: correct default text for button labels in gtk dialogs
  shell/browser/ui/gtk_util.cc
  shell/browser/ui/gtk_util.h
Labels: component/dialog, semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31794 fix: crash on browserView.webContents.destroy()
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-browser-view-spec.ts
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31805 fix: media shouldn't open permissions dialog
  patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
Labels: semver/patch, target/15-x-y, target/16-x-y

#31800 fix: change cookie default from NO_RESTRICTION to LAX_MODE
  docs/api/cookies.md
  shell/browser/api/electron_api_cookies.cc
  spec-main/api-net-spec.ts
Labels: semver/patch, target/15-x-y, target/16-x-y

#31844 fix: BrowserView setBackgroundColor()
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: backport, semver/patch, 15-x-y

#31848 fix: revert "refactor: only create webContents after 'will-attach-webview'…
  lib/browser/guest-view-manager.ts
  lib/common/ipc-messages.ts
  lib/renderer/web-view/guest-view-internal.ts
  lib/renderer/web-view/web-view-element.ts
  lib/renderer/web-view/web-view-impl.ts
  shell/browser/api/electron_api_web_view_manager.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  typings/internal-electron.d.ts
Labels: backport, semver/patch, fast-track 🚅, 16-x-y

#31852 fix: provide paths for all NetworkContextFilePaths keys
  chromium_src/BUILD.gn
  shell/browser/net/network_context_service.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/net/system_network_context_manager.h
Labels: backport, semver/patch, fast-track 🚅, 16-x-y

#31777 fix: provide paths for all NetworkContextFilePaths keys
  chromium_src/BUILD.gn
  shell/browser/net/network_context_service.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/net/system_network_context_manager.h
Labels: semver/patch, fast-track 🚅, merged/16-x-y, target/16-x-y

#31817 chore: use `std::forward()` in `ConvertToV8()`
  shell/common/gin_converters/std_converter.h
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y

#31843 chore: fix malformed mojom::CreateNewWindowParams patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
Labels: backport, semver/patch, 15-x-y

#31845 fix: BrowserView setBackgroundColor()
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: backport, semver/patch, 14-x-y

#31791 docs: Fix typo in distribution docs
  docs/tutorial/application-distribution.md
Labels: documentation :notebook:, semver/none, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#31778 chore: update nmv to 103 for Electron 18
  build/args/all.gn
Labels: semver/major, api-review/requested 🗳, no-backport

#31881 fix: add resource strings for file selection
  electron_strings.grdp
  shell/browser/file_select_helper.cc
Labels: semver/patch, fast-track 🚅, target/16-x-y, target/17-x-y

#31923 fix: lint Objective-C header files
  script/lint.js
  shell/browser/mac/electron_application.h
  shell/browser/mac/electron_application_delegate.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#31887 fix: ninja build failed on some system
  script/generate-config-gypi.py
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#31863 fix: BrowserView setBackgroundColor needs two calls
  shell/browser/api/electron_api_browser_view.cc
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#29101 fix: aspect ratio when max width/height is set
  patches/chromium/.patches
  patches/chromium/fix_aspect_ratio_with_max_size.patch
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#31899 chore: cherry-pick a5f54612590d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-a5f54612590d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31900 chore: cherry-pick a5f54612590d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-a5f54612590d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31910 chore: cherry-pick 5d2b5e7c006c from v8
  patches/v8/.patches
  patches/v8/cherry-pick-5d2b5e7c006c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31911 chore: cherry-pick 5d2b5e7c006c from v8
  patches/v8/.patches
  patches/v8/cherry-pick-5d2b5e7c006c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31902 chore: cherry-pick 1a8af2da50e4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1a8af2da50e4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31920 chore: cherry-pick 56de3b2004, bbca3704f9 and f2b0985ac3 from chromium
  patches/chromium/.patches
  patches/chromium/allow_null_skbitmap_to_be_transferred_across_threads.patch
  patches/chromium/introduce_crossthreadcopier_skbitmap.patch
  patches/chromium/use_weakptrs_for_the_threadediconloader_s_background_tasks.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31927 chore: cherry-pick 1fcfb942bd from chromium
  patches/chromium/.patches
  patches/chromium/cachestorage_store_partial_opaque_responses.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31928 chore: cherry-pick 1fcfb942bd from chromium
  patches/chromium/.patches
  patches/chromium/cachestorage_store_partial_opaque_responses.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31963 fix: console windows from ELECTRON_RUN_AS_NODE instances
  shell/app/node_main.cc
Labels: semver/patch, new-pr 🌱, target/16-x-y, target/17-x-y

#31961 docs: add playwright e2e testing docs
  docs/tutorial/automated-testing.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/16-x-y, target/17-x-y

#31919 chore: cherry-pick 56de3b2004, bbca3704f9 and f2b0985ac3 from chromium
  patches/chromium/.patches
  patches/chromium/allow_null_skbitmap_to_be_transferred_across_threads.patch
  patches/chromium/introduce_crossthreadcopier_skbitmap.patch
  patches/chromium/use_weakptrs_for_the_threadediconloader_s_background_tasks.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31988 chore: update patches
  patches/chromium/fix_aspect_ratio_with_max_size.patch
Labels: fast-track 🚅, semver/none, no-backport

#31921 chore: cherry-pick 56de3b2004, bbca3704f9 and f2b0985ac3 from chromium
  patches/chromium/.patches
  patches/chromium/allow_null_skbitmap_to_be_transferred_across_threads.patch
  patches/chromium/introduce_crossthreadcopier_skbitmap.patch
  patches/chromium/use_weakptrs_for_the_threadediconloader_s_background_tasks.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31912 chore: cherry-pick 5d2b5e7c006c from v8
  patches/v8/.patches
  patches/v8/cherry-pick-5d2b5e7c006c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#31903 chore: cherry-pick 1a8af2da50e4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1a8af2da50e4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31991 docs: make Discord invite non-vanity
  README.md
  docs/tutorial/support.md
  lib/browser/default-menu.ts
Labels: documentation :notebook:, semver/none, no-backport

#31741 build: add CI path-filtering for docs-only changes
  .circleci/build_config.yml
  .circleci/config.yml
  script/release/ci-release-build.js
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32063 build: account for path-filtering workflow in release-build script
  script/release/ci-release-build.js
Labels: fast-track 🚅, semver/none, no-backport

#31979 docs: add debug build
  docs/development/debugging.md
Labels: semver/none, no-backport

#31901 chore: cherry-pick a5f54612590d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-a5f54612590d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32052 fix: avoid double call in OnRefreshComplete on aura platforms
  patches/chromium/desktop_media_list.patch
Labels: semver/patch, target/16-x-y, target/17-x-y
