Repository electron/electron, pull requests merged in 2021-03, with the labels that each got.

#27915 build: update docker images to node 14
  .circleci/config.yml
  vsts-arm32v7.yml
  vsts-arm64v8.yml
Labels: semver/none

#27916 build: remove node-gyp arm64 tricks
  script/spec-runner.js
Labels: semver/none

#27911 chore: bump node in DEPS to v14.16.0
  DEPS
  patches/node/build_add_gn_build_files.patch
  patches/node/build_bring_back_node_with_ltcg_configuration.patch
  patches/node/build_modify_js2c_py_to_allow_injection_of_original-fs_and_custom_embedder_js.patch
  patches/node/chore_prevent_warn_non_context-aware_native_modules_being_loaded.patch
  patches/node/chore_read_nobrowserglobals_from_global_not_process.patch
  patches/node/enable_31_bit_smis_on_64bit_arch_and_ptr_compression.patch
  patches/node/feat_initialize_asar_support.patch
  patches/node/fix_add_default_values_for_enable_lto_and_build_v8_with_gn_in.patch
  patches/node/fix_add_v8_enable_reverse_jsargs_defines_in_common_gypi.patch
  patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
  patches/node/remove_makeexternal_case_for_uncached_internal_strings.patch
Labels: 12-x-y, backport, semver/patch

#27926 chore: revert webFrameMain.executeJavaScriptInIsolatedWorld method
  docs/api/web-frame-main.md
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  spec-main/api-web-frame-main-spec.ts
Labels: semver/patch, target/12-x-y

#27927 fix: navigator.bluetooth.requestDevice
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/bluetooth/electron_bluetooth_delegate.cc
  shell/browser/bluetooth/electron_bluetooth_delegate.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/lib/bluetooth_chooser.cc
  shell/browser/lib/bluetooth_chooser.h
  spec-main/chromium-spec.ts
Labels: 12-x-y, backport, semver/patch

#27938 fix: prevent race-condition in electron.net
  lib/browser/api/net.ts
Labels: 12-x-y, backport, semver/patch

#27939 ci: ignore errors deleting user app directories on WOA testing
  azure-pipelines-woa.yml
Labels: 12-x-y, backport, semver/none

#27940 fix: values return from the ctx bridge with dynamic property support should themselves support dynamic properties
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: 12-x-y, backport, semver/patch

#27941 fix: navigator.bluetooth.requestDevice crash
  shell/browser/lib/bluetooth_chooser.cc
  shell/browser/lib/bluetooth_chooser.h
  spec-main/chromium-spec.ts
Labels: 11-x-y, backport, semver/patch

#27944 fix: set WebContents background color ubiquitously
  shell/browser/api/electron_api_web_contents.cc
Labels: 11-x-y, backport, semver/patch

#27786 fix: ensure owner window is valid in ResetBrowserViews
  shell/browser/api/electron_api_base_window.cc
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y

#27942 fix: set WebContents background color ubiquitously
  shell/browser/api/electron_api_web_contents.cc
Labels: 12-x-y, backport, semver/patch

#27937 chore: revert webFrameMain.executeJavaScriptInIsolatedWorld method
  docs/api/web-frame-main.md
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  spec-main/api-web-frame-main-spec.ts
Labels: 12-x-y, backport, backport-check-skip, fast-track 🚅, semver/none

#27956 test: add more logging for a few tests.
  spec-main/api-app-spec.ts
  spec-main/extensions-spec.ts
Labels: semver/none

#27815 fix: check web_contents() for destroyed WebContents
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
  spec-main/fixtures/apps/quit/main.js
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y

#27928 fix: warning when worldSafeExecuteJavaScript is disabled
  lib/renderer/api/web-frame.ts
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y

#27952 fix: offset browserview drag regions on macOS
  shell/browser/native_browser_view_mac.mm
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y

#27970 docs: update fiddles/quick-start to set contextIsolation: false
  docs/fiddles/quick-start/main.js
Labels: semver/none

#27897 feat: expose des-ede3 cipher
  patches/boringssl/.patches
  patches/boringssl/expose_des-ede3.patch
Labels: api-review/requested 🗳, semver/minor, target/10-x-y, target/11-x-y, target/12-x-y

#27998 test: fix contextIsolation value for later added test
  spec-main/fixtures/apps/quit/main.js
Labels: fast-track 🚅, semver/none, target/12-x-y, target/13-x-y

#27991 chore: cherry-pick 67fe5a41bff from chromium
  patches/chromium/.patches
  patches/chromium/word_break_between_space_and_alphanumeric.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#27958 docs: suspend and resume are available on Linux
  docs/api/power-monitor.md
Labels: documentation :notebook:, semver/patch

#27950 fix: navigator.setAppBadge/clearAppBadge from a service worker
  shell/browser/badging/badge_manager.cc
  shell/browser/badging/badge_manager.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  spec-main/chromium-spec.ts
  spec/fixtures/pages/service-worker/badge-index.html
  spec/fixtures/pages/service-worker/service-worker-badge.js
Labels: semver/patch, target/12-x-y

#27953 chore: Add a condition to crashReporter deprecate log
  lib/browser/api/crash-reporter.ts
Labels: semver/patch, target/11-x-y, target/12-x-y

#27974 fix: warning when worldSafeExecuteJavaScript is disabled
  lib/renderer/api/web-frame.ts
Labels: 10-x-y, backport, semver/patch

#28016 test: exit after app.relaunch is called
  spec-main/api-app-spec.ts
  spec-main/extensions-spec.ts
  spec/fixtures/api/relaunch/main.js
Labels: semver/none, target/13-x-y

#27920 refactor: cleanup how WebContents is destroyed
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view_mac.mm
Labels: semver/patch

#28015 docs: `setWindowOpenHandler` should show object return
  docs/api/window-open.md
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#27984 docs: update WebPreferences default values for Electron 12
  docs/api/browser-window.md
Labels: semver/patch, target/12-x-y

#27888 docs: auto update downloading multiple times
  docs/api/auto-updater.md
Labels: documentation :notebook:, semver/patch

#28039 test: ignore the ready event from PDF Viewer
  spec-main/extensions-spec.ts
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28040 test: print more information in locale test
  spec-main/chromium-spec.ts
Labels: semver/none

#28047 chore: cherry-pick 7e0e52df283c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-7e0e52df283c.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28046 chore: cherry-pick 7e0e52df283c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-7e0e52df283c.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#23760 chore: remove obsolete native node module patch
  patches/node/.patches
  patches/node/build_bring_back_node_with_ltcg_configuration.patch
  patches/node/enable_31_bit_smis_on_64bit_arch_and_ptr_compression.patch
  patches/node/fix_add_v8_enable_reverse_jsargs_defines_in_common_gypi.patch
Labels: semver/patch, target/12-x-y, target/13-x-y

#28053 build: call goma_ctl.py ensure_start directly
  .circleci/config.yml
Labels: fast-track 🚅, semver/none, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28062 test: show full object diff
  spec-main/extensions-spec.ts
  spec-main/index.js
  spec/static/index.html
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#27883 fix: capturePage not resolving with hidden windows
  docs/api/browser-window.md
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#27971 chore: convert bug report template to form
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: semver/none

#28091 chore: cherry-pick 6ed1c0c425e0 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6ed1c0c425e0.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28100 chore: convert Mac App Store Private API Rejection template to form
  .github/ISSUE_TEMPLATE/mac_app_store_private_api_rejection.md
  .github/ISSUE_TEMPLATE/mac_app_store_private_api_rejection.yml
Labels: new-pr 🌱, semver/none

#28085 test: enable locale test for asan build
  spec-main/chromium-spec.ts
Labels: semver/none

#28089 chore: cherry-pick aeb6bc551b60 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-aeb6bc551b60.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28067 chore: cherry-pick 1fe571a from node
  patches/node/.patches
  patches/node/src_inline_asynccleanuphookhandle_in_headers.patch
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28054 fix: ensure child window transparency works
  lib/browser/api/web-contents.ts
  patches/chromium/.patches
  patches/chromium/moves_background_color_setter_of_webview_to_blinks_webprefs_logic.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/renderer/renderer_client_base.cc
Labels: in-flight/12-x-y, semver/patch, target/10-x-y, target/11-x-y, target/13-x-y

#28107 fix: ensure child window transparency
  lib/browser/api/web-contents.ts
  patches/chromium/.patches
  patches/chromium/moves_background_color_setter_of_webview_to_blinks_webprefs_logic.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/renderer/renderer_client_base.cc
Labels: 12-x-y, backport, fast-track 🚅, semver/patch

#28115 docs: fix cookies event documentation for type generation
  docs/api/cookies.md
Labels: new-pr 🌱, semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28102 fix: change #if defined(OS_MACOSX) to #if defined(OS_MAC)
  shell/browser/api/electron_api_browser_window.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28118 test: reliably wait for spellchecker to load
  shell/common/api/electron_api_v8_util.cc
  spec-main/spellchecker-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28050 chore: cherry-pick 38781b86f0 from chromium
  patches/chromium/.patches
  patches/chromium/mediarecorder_tolerate_non-gmb_nv12_frames_for_h264.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28051 chore: cherry-pick 38781b86f0 from chromium
  patches/chromium/.patches
  patches/chromium/mediarecorder_tolerate_non-gmb_nv12_frames_for_h264.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28077 docs(quick-start): make import command npm 7-compatible
  docs/tutorial/quick-start.md
Labels: documentation :notebook:, semver/none

#28087 docs(breaking-changes): contextIsolation disables require in renderer
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch

#28093 chore: cherry-pick eb0c0353bf24 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-eb0c0353bf24.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28092 chore: cherry-pick a4faa754a9ef from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-a4faa754a9ef.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28146 docs: use :syntax: for emoji in feature request template
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: new-pr 🌱, semver/none

#28145 docs: add bug label to bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: new-pr 🌱, semver/none

#28101 chore: cherry-pick 157601b9b9 from pdfium
  patches/config.json
  patches/pdfium/.patches
  patches/pdfium/m89_upgrade_openjpeg_to_2_4_0.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28160 fix: values return from the ctx bridge with dynamic property support should themselves support dynamic properties
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: 10-x-y, backport, semver/patch

#28136 docs: remove "Additional information" section from issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: semver/none

#28094 chore: cherry-pick 3910c9f5cde6 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3910c9f5cde6.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28097 chore: cherry-pick 18d3f86206e8 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-18d3f86206e8.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28111 fix: delay emitting NotifyIcon events on Windows
  shell/browser/ui/win/notify_icon.h
  shell/browser/ui/win/notify_icon_host.cc
Labels: 12-x-y, backport, semver/patch

#28117 docs: fixed typo in api/window-open.md
  docs/api/window-open.md
Labels: semver/none

#28121 fix: convert system colors to device color space in systemPreferences
  shell/browser/api/electron_api_system_preferences_mac.mm
  shell/common/color_util.cc
  shell/common/color_util.h
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28120 fix: handle a nil backgroundColor in win.getBackgroundColor()
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  spec-main/fixtures/crash-cases/transparent-window-get-background-color/index.js
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28159 fix: documentEdited property on BrowserWindow
  lib/browser/api/top-level-window.js
Labels: 10-x-y, backport, semver/patch

#28098 chore: cherry-pick b772b48067c4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-b772b48067c4.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28135 docs: expand OS version prompt in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: semver/none

#28168 test: reliably wait for spellchecker to load
  shell/common/api/electron_api_v8_util.cc
  spec-main/spellchecker-spec.ts
  typings/internal-ambient.d.ts
Labels: 13-x-y, backport, semver/none, target/11-x-y, target/12-x-y

#28129 docs: remove unnecessary enableBlinkFeatures
  docs/api/session.md
Labels: semver/none

#28166 chore: cherry-pick 6e8856624cbb from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6e8856624cbb.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28165 chore: cherry-pick 6e8856624cbb from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6e8856624cbb.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28133 chore: cherry-pick b3dc4c4b349d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-b3dc4c4b349d.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28137 fix: revert "refactor: mmap asar files (#24470)"
  lib/asar/fs-wrapper.ts
  shell/common/api/electron_api_asar.cc
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
  shell/common/asar/scoped_temporary_file.cc
  shell/common/asar/scoped_temporary_file.h
  typings/internal-ambient.d.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28198 chore: cherry-pick 5651fb858b75 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-5651fb858b75.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28132 chore: cherry-pick 33861dcf6d15 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-33861dcf6d15.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28161 fix: values return from the ctx bridge with dynamic property support …
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: 11-x-y, backport, semver/patch

#28189 docs: document the parameter structure of hookWindowMessage
  docs/api/browser-window.md
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28150 fix: recalibrate simpleFullscreen when display metrics change
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28199 chore: cherry-pick 5651fb858b75 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-5651fb858b75.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28196 docs: remove no longer relevant link
  docs/development/issues.md
Labels: semver/none

#28156 test: disable some tests under ASan which might receive SIGKILL because of OOM
  spec-main/api-app-spec.ts
  spec-main/api-protocol-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/api-web-contents-view-spec.ts
  spec-main/chromium-spec.ts
  spec-main/crash-spec.ts
  spec-main/fixtures/crash-cases/quit-on-crashed-event/index.js
  spec-main/fixtures/crash-cases/webcontents-create-leak-exit/index.js
  spec-main/fixtures/crash-cases/webcontentsview-create-leak-exit/index.js
  spec-main/node-spec.ts
  spec-main/spellchecker-spec.ts
  spec-main/webview-spec.ts
Labels: semver/none, target/13-x-y

#28223 docs: update Quick Start Guide for Electron 12
  docs/fiddles/quick-start/index.html
  docs/fiddles/quick-start/main.js
  docs/fiddles/quick-start/preload.js
  docs/tutorial/quick-start.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/12-x-y, target/13-x-y

#28007 feat: add process.contextId used by @electron/remote
  docs/api/process.md
  lib/renderer/init.ts
  lib/sandboxed_renderer/init.ts
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/module/preload-sandbox.js
  spec/api-process-spec.js
Labels: api-review/requested 🗳, semver/minor, target/13-x-y

#28030 feat: add process.contextIsolation property
  docs/api/process.md
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/module/preload-sandbox.js
  spec/fixtures/api/isolated-process.js
Labels: api-review/requested 🗳, semver/minor, target/13-x-y

#28227 docs: Update Quick Start Guide for Electron 12
  docs/fiddles/quick-start/index.html
  docs/fiddles/quick-start/main.js
  docs/fiddles/quick-start/preload.js
  docs/tutorial/quick-start.md
Labels: 12-x-y, backport, semver/none

#28229 docs: Update Quick Start Guide to work with contextIsolation
  docs/fiddles/quick-start/index.html
  docs/fiddles/quick-start/main.js
  docs/fiddles/quick-start/preload.js
  docs/tutorial/quick-start.md
Labels: 13-x-y, backport, semver/none

#28233 chore: cherry-pick e1505713dc31 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-e1505713dc31.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28236 chore: cherry-pick 53c4d05797 and 6e8f04c980 from v8
  patches/v8/.patches
  patches/v8/regexp_throw_when_length_of_text_nodes_in_alternatives_is_too.patch
  patches/v8/reland_regexp_hard-crash_on_invalid_offsets_in.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28237 chore: cherry-pick 53c4d05797 and 6e8f04c980 from v8
  patches/v8/.patches
  patches/v8/regexp_throw_when_length_of_text_nodes_in_alternatives_is_too.patch
  patches/v8/reland_regexp_hard-crash_on_invalid_offsets_in.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28248 chore: cherry-pick 37210e5ab006 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-37210e5ab006.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28253 docs: add missing curly brace to quick start example code
  docs/tutorial/quick-start.md
Labels: documentation :notebook:, new-pr 🌱, semver/none

#28231 docs: updated example to work with latest versions of selenium-webdriver
  docs/tutorial/using-selenium-and-webdriver.md
Labels: semver/none

#28224 fix: bad menu position when no positioning item specified
  shell/browser/api/electron_api_menu_mac.mm
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28273 fix: DesktopCapturer gc'd prior to capture completion
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_desktop_capturer.h
Labels: new-pr 🌱, semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28249 chore: cherry-pick c6d6f7aee733 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c6d6f7aee733.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28259 chore: rename process.contextIsolation to process.contextIsolated
  docs/api/process.md
  shell/renderer/renderer_client_base.cc
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/module/preload-sandbox.js
  spec/fixtures/api/isolated-process.js
Labels: new-pr 🌱, semver/patch

#28105 feat: allow omitting submitURL when uploadToServer is false
  docs/api/crash-reporter.md
  lib/browser/api/crash-reporter.ts
  spec-main/api-crash-reporter-spec.ts
Labels: api-review/requested 🗳, semver/minor

#28250 chore: cherry-pick c6d6f7aee733 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c6d6f7aee733.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28266 fix: missing HandleScope in ResetBrowserViews
  shell/browser/api/electron_api_base_window.cc
Labels: new-pr 🌱, semver/patch

#28268 fix: drag region offsets in BrowserViews
  shell/browser/native_browser_view_mac.mm
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28230 test: spellchecker may take several minutes to load under ASan
  spec-main/spellchecker-spec.ts
Labels: semver/none, target/13-x-y

#28286 fix: destroy MessageDispatcher before WebContents
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/none

#28247 chore: cherry-pick 93ce5606cd9a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-93ce5606cd9a.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28245 docs: update Node global symbols example to use contextBridge
  docs/api/browser-window.md
  docs/api/context-bridge.md
  docs/api/process.md
Labels: documentation :notebook:, semver/patch, target/13-x-y

#28271 refactor: prefer embedder-focused InitializeNodeWithArgs
  shell/common/node_bindings.cc
Labels: semver/patch, target/12-x-y, target/13-x-y

#28294 chore: cherry-pick a66dbdcf6493 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-a66dbdcf6493.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28299 chore: cherry-pick a66dbdcf6493 from chromium
  patches/chromium/.patches
  patches/chromium/reland_reland_fsa_add_issafepathcomponent_checks_to.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#27348 feat: add ContextBridgeMutability feature
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
  spec-main/fixtures/api/context-bridge/context-bridge-mutability/index.html
  spec-main/fixtures/api/context-bridge/context-bridge-mutability/main.js
  spec-main/fixtures/api/context-bridge/context-bridge-mutability/package.json
  spec-main/fixtures/api/context-bridge/context-bridge-mutability/preload.js
Labels: api-review/requested 🗳, semver/minor

#28329 ci: cleanup directories on arm64 machines after running tests
  .circleci/config.yml
Labels: fast-track 🚅, semver/none, target/13-x-y

#28330 chore: add unit tests for findInPage/findInFrame
  spec-main/api-web-contents-spec.ts
  spec-main/api-web-frame-main-spec.ts
  spec-main/fixtures/sub-frames/frame-with-frames.html
Labels: new-pr 🌱

#28175 fix: libuv hang on Windows
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  spec-main/fixtures/apps/libuv-hang/index.html
  spec-main/fixtures/apps/libuv-hang/main.js
  spec-main/fixtures/apps/libuv-hang/preload.js
  spec-main/fixtures/apps/libuv-hang/renderer.js
  spec-main/node-spec.ts
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28334 fix: escape URL passed to shell.openExternal on windows
  shell/common/platform_util_win.cc
Labels: new-pr 🌱, semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28328 fix: window.print() in pdf plugin
  lib/browser/api/web-contents.ts
  shell/renderer/printing/print_render_frame_helper_delegate.cc
Labels: semver/patch, target/12-x-y, target/13-x-y

#28326 fix: make sure service worker scheme is registered with allowServiceWorkers
  shell/browser/api/electron_api_protocol.cc
  shell/browser/electron_browser_client.cc
  spec-main/api-protocol-spec.ts
  spec-main/index.js
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28234 chore: cherry-pick e1505713dc31 from chromium
  patches/chromium/.patches
  patches/chromium/css_make_fetches_from_inline_css_use_the_document_s_url_as_referrer.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28357 docs: MessagePorts guide (#27678)
  docs/tutorial/message-ports.md
Labels: 12-x-y, backport, documentation :notebook:, semver/none

#28332 fix: isolate Pepper plugins
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, target/12-x-y, target/13-x-y

#28285 perf: do not double-proxy methods being return over the contextBridge
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: performance :checkered_flag:, semver/patch

#28371 docs: update Node API renderer example to use contextBridge
  docs/api/browser-window.md
  docs/api/context-bridge.md
  docs/api/process.md
Labels: 12-x-y, backport, semver/patch

#28370 docs: update Node API renderer example to use contextBridge
  docs/api/browser-window.md
  docs/api/context-bridge.md
  docs/api/process.md
Labels: 13-x-y, backport, semver/patch

#28360 fix: export patches not retaining CRLF line endings
  script/lib/git.py
  script/lint.js
Labels: semver/none

#28366 fix: disappearing thumbar after win.hide()
  shell/browser/native_window_views.cc
  shell/browser/ui/win/taskbar_host.cc
  shell/browser/ui/win/taskbar_host.h
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28386 test: load minimal dict for spellchecker
  spec-main/spellchecker-spec.ts
Labels: semver/none, target/13-x-y

#28376 docs: add missing line in web-contents.md
  docs/api/web-contents.md
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28305 feat: initialize field trials from command line arguments
  docs/api/command-line-switches.md
  shell/browser/electron_browser_main_parts.cc
  shell/browser/feature_list.cc
  shell/browser/feature_list.h
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28427 test: increase timeout for spellchecker under ASan
  spec-main/spellchecker-spec.ts
Labels: semver/none

#28411 fix: make TouchBarPopover and TouchBarGroup work (#27901)
  lib/browser/api/touch-bar.ts
  shell/browser/ui/cocoa/electron_touch_bar.mm
Labels: 12-x-y, backport, semver/patch

#28412 fix: make TouchBarPopover and TouchBarGroup work
  lib/browser/api/touch-bar.ts
  shell/browser/ui/cocoa/electron_touch_bar.mm
Labels: 11-x-y, backport, semver/patch

#28398 test: load minimal dict for spellchecker
  spec-main/spellchecker-spec.ts
Labels: 13-x-y, backport, semver/none

#28369 refactor: remove more uses of `v8::Isolate::GetCurrent()`
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_download_item.cc
  shell/browser/api/electron_api_download_item.h
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_url_loader.cc
  shell/browser/native_window_mac.mm
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/patch, target/12-x-y, target/13-x-y

#28358 fix: put RemoteCertVerifier upstream from the caching and coalescing layers
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28346 fix: errors thrown in functions over the `contextBridge`
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28397 docs: backport current tutorials to 13-x-y
  docs/README.md
  docs/breaking-changes.md
  docs/development/issues.md
  docs/tutorial/quick-start.md
  docs/tutorial/security.md
  docs/tutorial/using-selenium-and-webdriver.md
Labels: backport-check-skip, documentation :notebook:, semver/none

#28396 docs: backport current tutorials to 12-x-y
  docs/README.md
  docs/breaking-changes.md
  docs/development/build-instructions-gn.md
  docs/development/build-instructions-linux.md
  docs/development/coding-style.md
  docs/development/issues.md
  docs/development/pull-requests.md
  docs/fiddles/quick-start/index.html
  docs/styleguide.md
  docs/tutorial/application-debugging.md
  docs/tutorial/application-distribution.md
  docs/tutorial/code-signing.md
  docs/tutorial/dark-mode.md
  docs/tutorial/debugging-vscode.md
  docs/tutorial/devtools-extension.md
  docs/tutorial/electron-timelines.md
  docs/tutorial/electron-versioning.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/macos-dock.md
  docs/tutorial/native-file-drag-drop.md
  docs/tutorial/notifications.md
  docs/tutorial/offscreen-rendering.md
  docs/tutorial/online-offline-events.md
  docs/tutorial/progress-bar.md
  docs/tutorial/quick-start.md
  docs/tutorial/recent-documents.md
  docs/tutorial/represented-file.md
  docs/tutorial/security.md
  docs/tutorial/snapcraft.md
  docs/tutorial/spellchecker.md
  docs/tutorial/support.md
  docs/tutorial/using-native-node-modules.md
  docs/tutorial/using-selenium-and-webdriver.md
  docs/tutorial/web-embeds.md
Labels: backport-check-skip, documentation :notebook:, semver/none

#28432 fix: handle an unparsable pdf manifest
  shell/browser/extensions/electron_extension_system.cc
Labels: semver/patch, target/12-x-y, target/13-x-y

#28447 fix: errors thrown in functions over the `contextBridge`
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: 12-x-y, backport, semver/patch

#28449 chore: update Community link in default menu
  lib/browser/default-menu.ts
Labels: new-pr 🌱, semver/patch, target/12-x-y, target/13-x-y

#28457 docs: remove application-packaging.md
  docs/tutorial/application-packaging.md
Labels: backport-check-skip, documentation :notebook:, semver/patch

#28454 build: fix unicode patch file comparison in git.py
  script/lib/git.py
Labels: semver/none

#28465 fix: put RemoteCertVerifier upstream from the caching and coalescing layers (#28358)
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: 12-x-y, backport, semver/patch

#28435 docs: add frameName note for window.open
  docs/api/window-open.md
Labels: documentation :notebook:, semver/patch
