Repository electron/electron, pull requests merged in 2021-04, with the labels that each got.

#28467 refactor: remove unneeded patch_count variable
  script/lib/git.py
Labels: semver/none

#19159 feat: Use GtkFileChooserNative to support the XDG Desktop Portal specification
  shell/browser/ui/file_dialog_gtk.cc
Labels: api-review/requested 🗳, semver/minor

#28469 fix: free IsolateData in ~NodeEnvironment
  shell/browser/javascript_environment.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28471 fix: crash when exiting app with active nodejs worker_threads
  patches/node/.patches
  patches/node/src_make_freeenvironment_perform_all_necessary_cleanup.patch
  shell/app/node_main.cc
  shell/browser/javascript_environment.cc
  shell/renderer/electron_renderer_client.cc
Labels: 11-x-y, backport-check-skip, semver/patch

#28455 chore: add types for electron_renderer_web_frame binding
  lib/renderer/api/web-frame.ts
  typings/internal-ambient.d.ts
Labels: semver/patch

#28480 docs: the minimum supported version of macOS is now 10.11
  docs/tutorial/support.md
  shell/browser/resources/mac/Info.plist
Labels: semver/none, target/12-x-y, target/13-x-y

#28485 fix: reject task append to JumpList when description exceeds 260 characters
  docs/api/app.md
  docs/api/structures/jump-list-category.md
  docs/api/structures/jump-list-item.md
  shell/browser/ui/win/jump_list.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28207 fix: enable system maximization for frameless windows except if transparent
  docs/api/frameless-window.md
  shell/browser/native_window_views.cc
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28494 docs: Remove GoDaddy from Windows code signing options
  docs/tutorial/code-signing.md
Labels: semver/none

#28514 build: ignore ninja summary print failures
  .circleci/config.yml
Labels: semver/none

#28478 fix: dialog DCHECK on Linux
  shell/browser/ui/file_dialog_gtk.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28498 fix: invoke the window open handler for _blank links
  lib/browser/api/web-contents.ts
  lib/browser/guest-window-manager.ts
  spec-main/guest-window-manager-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y

#28509 test: disable "fs in renderer process" test under ASan
  spec-main/node-spec.ts
Labels: semver/none, target/13-x-y

#28513 fix: pass postData to new-window event
  docs/api/structures/upload-file.md
  docs/api/structures/upload-raw-data.md
  lib/browser/guest-window-manager.ts
  lib/common/parse-features-string.ts
  spec-main/api-browser-window-spec.ts
Labels: new-pr 🌱, semver/patch, target/12-x-y, target/13-x-y

#28539 ci: Add goma fallback flag
  .circleci/config.yml
  appveyor.yml
Labels: semver/none

#28470 fix: put RemoteCertVerifier upstream from the caching and coalescing layers
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: 11-x-y, backport, semver/patch

#28486 fix: call `UnregisterIsolate` consistently
  shell/app/node_main.cc
  shell/browser/javascript_environment.cc
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28543 fix: pass postData to new-window event
  docs/api/structures/upload-file.md
  docs/api/structures/upload-raw-data.md
  lib/browser/guest-window-manager.ts
  lib/common/parse-features-string.ts
  spec-main/api-browser-window-spec.ts
Labels: 12-x-y, backport, semver/patch

#28489 fix: allow accessing file:// when web security is disabled
  shell/browser/electron_browser_client.cc
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  spec-main/chromium-spec.ts
  spec/webview-spec.js
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28531 fix: backport 3b21b6d from v8 to fix profiler crash
  patches/v8/.patches
  patches/v8/patch_profiler_allow_empty_source_url_for_asm_modules.patch
Labels: backport, backport-check-skip, semver/patch

#28446 fix: errors thrown in functions over the `contextBridge`
  shell/renderer/api/electron_api_context_bridge.cc
  spec-main/api-context-bridge-spec.ts
Labels: 13-x-y, backport, semver/patch

#28382 fix: beforeunload and unload firing in BrowserViews
  docs/api/web-contents.md
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-web-contents-spec.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28418 docs: remove checkbox options in dialog.showMessageBoxSync
  docs/api/dialog.md
Labels: documentation :notebook:, semver/patch

#28551 docs: fix typo in breaking-changes.md
  docs/breaking-changes.md
Labels: new-pr 🌱, semver/none

#28535 fix: support wasm-eval csp behind WebAssemblyCSP flag
  patches/chromium/.patches
  patches/chromium/blink_wasm_eval_csp.patch
  spec-main/chromium-spec.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28517 build: add safety net for mac_deployment_target
  BUILD.gn
Labels: semver/none

#28575 fix: support wasm-eval csp behind WebAssemblyCSP flag
  patches/chromium/.patches
  patches/chromium/blink_wasm_eval_csp.patch
  spec-main/chromium-spec.ts
Labels: 12-x-y, backport, semver/patch

#28549 docs: note that new-window event is deprecated
  docs/breaking-changes.md
Labels: semver/patch, target/13-x-y

#28576 fix: support wasm-eval csp behind WebAssemblyCSP flag
  patches/chromium/.patches
  patches/chromium/blink_wasm_eval_csp.patch
  spec-main/chromium-spec.ts
Labels: 11-x-y, backport, semver/patch

#28456 chore: remove deprecated `worldSafeExecuteJavaScript` option
  docs/api/browser-window.md
  lib/renderer/api/web-frame.ts
  lib/renderer/security-warnings.ts
  lib/renderer/web-frame-init.ts
  patches/chromium/allow_in_process_windows_to_have_different_web_prefs.patch
  shell/browser/web_contents_preferences.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/api/electron_api_web_frame.cc
  spec-main/api-web-frame-spec.ts
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: api-review/approved ✅, semver/major

#28571 chore: don't minimize js in development
  build/webpack/webpack.config.base.js
  build/webpack/webpack.gni
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28560 fix: allow accessing file:// when web security is disabled
  shell/browser/electron_browser_client.cc
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  spec-main/chromium-spec.ts
  spec/webview-spec.js
Labels: 12-x-y, backport, semver/patch, target/11-x-y

#28567 build: give ASAN tests more memory to avoid SIGKILL or disabling tests
  .circleci/config.yml
  spec-main/api-app-spec.ts
  spec-main/api-protocol-spec.ts
  spec-main/chromium-spec.ts
  spec-main/crash-spec.ts
  spec-main/node-spec.ts
  spec-main/webview-spec.ts
Labels: semver/none, target/13-x-y

#28589 fix: allow accessing file:// when web security is disabled
  shell/browser/electron_browser_client.cc
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  spec-main/chromium-spec.ts
  spec/webview-spec.js
Labels: 11-x-y, backport, semver/patch

#28583 refactor: use URL API in resolveURL
  lib/renderer/web-view/web-view-attributes.ts
Labels: semver/patch

#28597 docs: define the name of the preload script
  docs/tutorial/quick-start.md
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28588 docs: systemPreferences.subscribeWorkspaceNotification return type
  docs/api/system-preferences.md
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28573 fix: load source maps from custom protocols and asar bundles
  filenames.gni
  shell/browser/net/asar/asar_url_loader_factory.cc
  shell/browser/net/asar/asar_url_loader_factory.h
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28616 fix: load source maps from custom protocols and asar bundles
  filenames.gni
  shell/browser/net/asar/asar_url_loader_factory.cc
  shell/browser/net/asar/asar_url_loader_factory.h
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  shell/browser/ui/inspectable_web_contents.cc
Labels: 12-x-y, backport-check-skip, semver/patch, target/11-x-y

#28601 chore: cherry-pick 162efe98330e from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-162efe98330e.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28602 fix: crash on invalid select-serial-port callback
  shell/browser/serial/serial_chooser_controller.cc
  spec-main/chromium-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y

#28497 refactor: clean up webFrame implementation to use gin wrappers
  lib/renderer/api/context-bridge.ts
  lib/renderer/api/web-frame.ts
  lib/renderer/init.ts
  lib/sandboxed_renderer/init.ts
  shell/common/gin_helper/error_thrower.cc
  shell/common/gin_helper/error_thrower.h
  shell/renderer/api/electron_api_web_frame.cc
  typings/internal-ambient.d.ts
Labels: semver/none

#28621 build: better error handling for release builds
  script/release/ci-release-build.js
Labels: semver/none, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28622 fix: enable system maximization for frameless windows except if transparent
  docs/api/frameless-window.md
  shell/browser/native_window_views.cc
  shell/browser/native_window_views_win.cc
Labels: 12-x-y, backport, semver/patch, target/11-x-y

#28518 feat: add more info in setWindowOpenHandler details
  docs/api/browser-window.md
  docs/api/structures/post-body.md
  docs/api/structures/post-data.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  lib/browser/guest-window-manager.ts
  lib/browser/guest-window-proxy.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/blink_converter.h
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
  spec-main/guest-window-manager-spec.ts
  typings/internal-electron.d.ts
Labels: api-review/requested 🗳, semver/minor, target/13-x-y

#28552 feat: enable nativeWindowOpen by default
  docs/api/browser-window.md
  docs/api/window-open.md
  docs/breaking-changes.md
  shell/browser/web_contents_preferences.cc
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
  spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
  spec/static/main.js
  spec/webview-spec.js
Labels: api-review/requested 🗳, new-pr 🌱, semver/major

#28643 build: do not require vsts token for releases
  .env.example
  script/release/ci-release-build.js
Labels: semver/none, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28666 build: provide line numbers of bad patch lines when linting
  script/lint.js
Labels: semver/none

#28664 fix: invoke the window open handler for _blank links
  lib/browser/api/web-contents.ts
  lib/browser/guest-window-manager.ts
  spec-main/guest-window-manager-spec.ts
Labels: 12-x-y, backport, semver/patch

#28655 fix: increase corner radius for vibrancy view on big sur
  shell/browser/native_window_mac.mm
Labels: Big Sur 🍎, semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28671 fix: end attached sheet when calling window.hide()
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28682 fix: do not handle write errors after request is aborted
  lib/browser/api/net.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28690 chore: cherry-pick 3c80bb2a594f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3c80bb2a594f.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28689 chore: cherry-pick 3c80bb2a594f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3c80bb2a594f.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28698 chore: cherry-pick 254c7945ee from v8
  patches/v8/.patches
  patches/v8/merged_deoptimizer_fix_bug_in_optimizedframe_summarize.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28674 docs(build-instructions): clarify that these are for building Electron itself
  docs/development/build-instructions-gn.md
  docs/development/build-instructions-linux.md
  docs/development/build-instructions-macos.md
  docs/development/build-instructions-windows.md
Labels: documentation :notebook:, semver/none, target/12-x-y, target/13-x-y

#28680 chore: clean up some spec things
  .gitignore
  spec-main/chromium-spec.ts
Labels: semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28700 build: unify machine-mac-large-arm and machine-mac-large
  .circleci/config.yml
Labels: semver/none

#28709 chore: update ts parser for description comment fixes and generic types
  docs/api/structures/user-default-types.md
  docs/api/system-preferences.md
  filenames.auto.gni
  package.json
  spec/ts-smoke/electron/main.ts
  yarn.lock
Labels: semver/none

#28548 feat: remove deprecated additionalFeatures
  docs/api/web-contents.md
  docs/api/window-open.md
  docs/breaking-changes.md
  lib/browser/guest-window-manager.ts
  lib/common/parse-features-string.ts
  spec-main/api-browser-window-spec.ts
  spec-main/internal-spec.ts
Labels: api-review/requested 🗳, semver/major

#28737 build: fix docs only change script to pull all files not just 30
  script/doc-only-change.js
Labels: semver/none, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28745 fix: backport patch to fix crash on m1 mac
  patches/chromium/.patches
  patches/chromium/cherry-pick-162efe98330e.patch
Labels: backport, backport-check-skip, semver/patch

#28738 chore: cherry-pick 872b8c13d7 from skia
  patches/skia/.patches
  patches/skia/skscalercontext_getimage_less_brittle.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28725 chore: cherry-pick 012e9baf46c9 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-012e9baf46c9.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28724 chore: cherry-pick 012e9baf46c9 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-012e9baf46c9.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28697 chore: cherry-pick 254c7945ee from v8
  patches/v8/.patches
  patches/v8/merged_deoptimizer_fix_bug_in_optimizedframe_summarize.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28681 fix: ensure widget size is set correctly on linux on small screens
  shell/browser/native_window_views.cc
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28739 chore: cherry-pick 872b8c13d7 from skia
  patches/skia/.patches
  patches/skia/skscalercontext_getimage_less_brittle.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28642 feat: add BrowserWindow.isFocusable()
  docs/api/browser-window.md
  lib/browser/api/base-window.ts
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  spec-main/api-browser-window-spec.ts
Labels: api-review/approved ✅, semver/minor

#28703 chore: cherry-pick 6a6361c9f31c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6a6361c9f31c.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28704 chore: cherry-pick 8c3eb9d1c409 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-8c3eb9d1c409.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#25470 fix: handle async nature of [NSWindow -toggleFullScreen]
  shell/browser/native_window.cc
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y

#28705 chore: cherry-pick 8c3eb9d1c409 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-8c3eb9d1c409.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28702 chore: cherry-pick 6a6361c9f31c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6a6361c9f31c.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28550 feat: remove BrowserWindow option inheritance
  docs/api/web-contents.md
  docs/api/window-open.md
  docs/breaking-changes.md
  lib/browser/guest-window-manager.ts
  lib/browser/guest-window-proxy.ts
  lib/renderer/window-setup.ts
  shell/browser/api/electron_api_browser_window.cc
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
  spec-main/fixtures/snapshots/native-window-open.snapshot.txt
  spec/chromium-spec.js
  spec/fixtures/pages/window-open-postMessage-driver.html
  spec/fixtures/pages/window-opener-targetOrigin.html
Labels: api-review/requested 🗳, semver/major

#26874 chore: remove `app.allowRendererProcessReuse` and BrowserWindow `affinity` options
  docs/api/app.md
  docs/api/browser-window.md
  docs/breaking-changes.md
  lib/browser/api/app.ts
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  spec-main/api-app-spec.ts
  spec-main/api-browser-window-affinity-spec.ts
  spec-main/api-browser-window-spec.ts
  spec/fixtures/api/site-instance-overrides/index.html
  spec/fixtures/api/site-instance-overrides/main.js
  spec/fixtures/api/site-instance-overrides/package.json
  spec/fixtures/api/site-instance-overrides/preload.js
Labels: api-review/requested 🗳, semver/major

#28766 build: disable pseudolocales in Electron
  build/args/all.gn
  script/zip_manifests/dist_zip.linux.arm.manifest
  script/zip_manifests/dist_zip.linux.arm64.manifest
  script/zip_manifests/dist_zip.linux.x64.manifest
  script/zip_manifests/dist_zip.linux.x86.manifest
  script/zip_manifests/dist_zip.mac.arm64.manifest
  script/zip_manifests/dist_zip.mac.x64.manifest
  script/zip_manifests/dist_zip.mac_mas.arm64.manifest
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
  script/zip_manifests/dist_zip.win.arm64.manifest
  script/zip_manifests/dist_zip.win.ia32.manifest
  script/zip_manifests/dist_zip.win.x64.manifest
Labels: semver/none

#28763 fix: handle async nature of [NSWindow -toggleFullScreen]
  shell/browser/native_window.cc
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
Labels: 13-x-y, backport, semver/patch

#28760 chore: cherry-pick 74c9ad9a53 from chromium
  patches/chromium/.patches
  patches/chromium/use_idtype_for_permission_change_subscriptions.patch
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
Labels: 11-x-y, backport-check-skip, semver/patch

#28706 feat: add WebFrameMain.visibilityState
  docs/api/web-frame-main.md
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  spec-main/api-web-frame-main-spec.ts
  spec-main/spec-helpers.ts
Labels: api-review/requested 🗳, new-pr 🌱, semver/minor

#28769 refactor: clean up unused parts of the render_frame_host patch file
  patches/chromium/frame_host_manager.patch
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
Labels: new-pr 🌱, semver/none

#28767 docs: fix unintentional emoji in win.getMediaSourceId description
  docs/api/browser-window.md
Labels: new-pr 🌱, semver/patch, target/12-x-y, target/13-x-y

#28764 chore: restore "Additional Information" section in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: semver/none

#28761 chore: cherry-pick 74c9ad9a53 from chromium
  patches/chromium/.patches
  patches/chromium/use_idtype_for_permission_change_subscriptions.patch
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
Labels: 10-x-y, backport-check-skip, semver/patch

#28773 fix: handle async nature of [NSWindow -toggleFullScreen]
  shell/browser/native_window.cc
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
Labels: 11-x-y, backport, semver/patch

#28748 fix: shell.trashItem crash when called in renderer
  shell/common/platform_util.cc
  spec-main/api-shell-spec.ts
Labels: semver/patch, target/12-x-y, target/13-x-y

#28786 refactor: remove ProcessPreferences
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
Labels: semver/patch

#23128 refactor: be more precise when creating api::WebContents
  shell/browser/api/electron_api_app.cc
  shell/browser/extensions/electron_extension_host_delegate.cc
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/browser/extensions/electron_extensions_api_client.h
  shell/browser/ui/inspectable_web_contents.cc
  spec-main/chromium-spec.ts
  spec-main/extensions-spec.ts
Labels: semver/patch

#28807 chore: cherry-pick 6b84dc72351b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6b84dc72351b.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28808 chore: cherry-pick 6b84dc72351b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6b84dc72351b.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28809 chore: cherry-pick c87b3c1157 from v8
  patches/v8/.patches
  patches/v8/merged_squashed_multiple_commits.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28810 chore: cherry-pick 8ebd894186 and 1e35f64725 from v8
  patches/v8/.patches
  patches/v8/lts-m86_builtins_fix_array_prototype_concat_with_species.patch
  patches/v8/lts-m86_builtins_harden_array_prototype_concat.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28796 chore: cherry-pick d5d222b6ca and 1627015c84 from webrtc
  patches/config.json
  patches/webrtc/.patches
  patches/webrtc/merge_m86_-_fix_race_with_sctptransport_destruction_and_usrsctp.patch
  patches/webrtc/merge_m86_-_reland_fix_race_between_destroying_sctptransport_and.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28791 refactor: use rfh instead of process id in permission manager
  shell/browser/electron_permission_manager.cc
Labels: semver/patch

#28792 fix: only set backgroundColor in default-app for default index.html
  default_app/default_app.ts
Labels: semver/patch, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28800 chore: cherry-pick ffde6ee0e4 from v8
  patches/v8/.patches
  patches/v8/merged_squashed_multiple_commits.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28806 chore: cherry-pick e4abe032f3ad from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-e4abe032f3ad.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28772 fix: handle async nature of [NSWindow -toggleFullScreen]
  shell/browser/native_window.cc
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
Labels: 12-x-y, backport, semver/patch

#28780 chore: cherry-pick fe20b05a0e5e from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-fe20b05a0e5e.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28797 chore: cherry-pick fe85e04a1797 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-fe85e04a1797.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28812 chore: cherry-pick 1536a564d959 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1536a564d959.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28799 chore: cherry-pick ffde6ee0e4 from v8
  patches/v8/.patches
  patches/v8/merged_squashed_multiple_commits.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28811 chore: cherry-pick 8ebd894186 and 1e35f64725 from v8
  patches/v8/.patches
  patches/v8/lts-m86_builtins_fix_array_prototype_concat_with_species.patch
  patches/v8/lts-m86_builtins_harden_array_prototype_concat.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28819 chore: cherry-pick 7dd3b1c86795 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-7dd3b1c86795.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28823 chore: cherry-pick 8f054c5df2 and de1dbdb608 from chromium
  patches/chromium/.patches
  patches/chromium/m86-lts_add_null_pointer_check_in_renderwidgethostinputeventrouter.patch
  patches/chromium/m86-lts_add_weak_pointer_to_rwhier_framesinkidownermap_and.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28851 build: fix releases that failed halfway through npm publish actions
  script/release/publish-to-npm.js
Labels: semver/none, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28818 chore: cherry-pick 7dd3b1c86795 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-7dd3b1c86795.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28822 chore: cherry-pick 8f054c5df2 and de1dbdb608 from chromium
  patches/chromium/.patches
  patches/chromium/m86-lts_add_null_pointer_check_in_renderwidgethostinputeventrouter.patch
  patches/chromium/m86-lts_add_weak_pointer_to_rwhier_framesinkidownermap_and.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28814 chore: cherry-pick 406ae3e8a9a8 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-406ae3e8a9a8.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28779 chore: cherry-pick f79751ee25 from chromium
  patches/chromium/.patches
  patches/chromium/m90_devtools_expect_pagehandler_may_be_destroyed_during.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28798 chore: cherry-pick fe85e04a1797 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-fe85e04a1797.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28815 chore: cherry-pick 66b9ad64f4a4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-66b9ad64f4a4.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28816 chore: cherry-pick 1028ffc9bd83 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1028ffc9bd83.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28861 chore: cherry-pick aa2154a9c1 from v8
  patches/v8/.patches
  patches/v8/merged_compiler_fix_a_bug_in_visitspeculativeintegeradditiveop.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28863 chore: cherry-pick aa2154a9c1 from v8
  patches/v8/.patches
  patches/v8/merged_compiler_fix_a_bug_in_visitspeculativeintegeradditiveop.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28858 test: worker should be able to load asar files
  spec-main/asar-spec.ts
  spec/fixtures/workers/load_shared_worker.html
  spec/fixtures/workers/load_worker.html
  spec/fixtures/workers/workers.asar
Labels: semver/none

#28665 feat: add session.storagePath to get path on disk for session data
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec-main/api-session-spec.ts
Labels: api-review/approved ✅, semver/minor, target/13-x-y

#28868 test: disable shell.trashItem in renderer test on win-ia32
  spec-main/api-shell-spec.ts
Labels: semver/none, target/12-x-y, target/13-x-y

#28839 refactor: remove internal navigation controller
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  lib/browser/navigation-controller.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/none

#28873 chore: cherry-pick ed5f62c36d from angle.
  patches/angle/.patches
  patches/angle/d3d11_skip_blits_if_there_is_no_intersection_of_dest_areas.patch
  patches/config.json
Labels: 11-x-y, backport-check-skip, semver/patch

#28870 fix: recalibrate simpleFullscreen when display metrics change
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: 11-x-y, backport, semver/patch

#28862 chore: cherry-pick aa2154a9c1 from v8
  patches/v8/.patches
  patches/v8/merged_compiler_fix_a_bug_in_visitspeculativeintegeradditiveop.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28859 docs: Remove mentions of the old external_binaries directory
  .gitignore
  docs/development/source-code-directory-structure.md
Labels: semver/none

#28869 fix: recalibrate simpleFullscreen when display metrics change
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: 12-x-y, backport, semver/patch

#28801 chore: cherry-pick 809231f0c9 from chromium.
  patches/chromium/.patches
  patches/chromium/privacy_budget_remove_unnecessary_kcanvasreadback_metrics.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28802 chore: cherry-pick 5745eaf16077 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-5745eaf16077.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28882 docs: the tools folder does not exist anymore
  docs/development/source-code-directory-structure.md
Labels: new-pr 🌱, semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28883 build: remove the vendor directory
  .gitignore
  DEPS
  docs/development/pull-requests.md
  docs/development/source-code-directory-structure.md
  docs/tutorial/using-native-node-modules.md
  script/lib/config.py
  script/lib/native_tests.py
  script/release/notes/notes.js
  vendor/third_party/lss/linux_syscall_support.h
Labels: semver/none

#28885 build: actually use SSL when downloading things via python
  script/lib/util.py
Labels: semver/none, target/10-x-y, target/11-x-y, target/12-x-y, target/13-x-y

#28884 build: remove dead python methods and helper
  script/lib/env_util.py
  script/lib/git.py
  script/lib/gn.py
  script/lib/util.py
  script/release/uploaders/upload.py
Labels: semver/none, target/12-x-y, target/13-x-y

#28813 chore: cherry-pick 406ae3e8a9a8 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-406ae3e8a9a8.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28872 chore: cherry-pick ed5f62c36d from angle.
  patches/angle/.patches
  patches/angle/d3d11_skip_blits_if_there_is_no_intersection_of_dest_areas.patch
  patches/config.json
Labels: 12-x-y, backport-check-skip, semver/patch

#28821 chore: cherry-pick c768895b3f, 58393127e7 and c2f6803bdd from chromium
  patches/chromium/.patches
  patches/chromium/add_crashkeys_to_identify_where_target_is_assigned_to_a_stale_value.patch
  patches/chromium/add_null_pointer_check_in_renderwidgethostinputeventrouter.patch
  patches/chromium/add_weak_pointer_to_rwhier_framesinkidownermap_and_rwhier_targetmap.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28874 chore: cherry-pick ed5f62c36d from angle.
  patches/angle/.patches
  patches/angle/d3d11_skip_blits_if_there_is_no_intersection_of_dest_areas.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28817 chore: cherry-pick 1028ffc9bd83 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1028ffc9bd83.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28904 chore: cherry-pick 619083c7d8 from v8
  patches/v8/.patches
  patches/v8/merged_turbofan_harden_arrayprototypepop_and_arrayprototypeshift.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28867 fix: emit window-all-closed after closing the window
  shell/browser/native_window.cc
  spec-main/api-app-spec.ts
Labels: semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28910 build: fix dump_syms.py to work with python 3
  build/dump_syms.py
Labels: fast-track 🚅, semver/none

#28901 chore: cherry-pick 7c299aede5 from v8
  patches/v8/.patches
  patches/v8/merged_compiler_fix_off-by-one_error_in_kadditivesafeinteger.patch
Labels: 12-x-y, backport-check-skip, semver/patch

#28902 chore: cherry-pick 00245033cf from v8
  patches/v8/.patches
  patches/v8/m86-lts_compiler_fix_off-by-one_error_in_kadditivesafeinteger.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28903 chore: cherry-pick 00245033cf from v8
  patches/v8/.patches
  patches/v8/m86-lts_compiler_fix_off-by-one_error_in_kadditivesafeinteger.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28911 docs: remove `api/locales` page
  docs/api/app.md
  docs/api/locales.md
  filenames.auto.gni
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/11-x-y, target/12-x-y, target/13-x-y

#28916 build: temporarily disable WOA testing
  appveyor.yml
Labels: fast-track 🚅, semver/none

#28860 docs: Add clarification for Visual Zoom behavior
  docs/api/web-frame.md
Labels: documentation :notebook:, semver/patch, target/11-x-y, target/12-x-y, target/13-x-y

#28906 chore: cherry-pick 619083c7d8 from v8
  patches/v8/.patches
  patches/v8/merged_turbofan_harden_arrayprototypepop_and_arrayprototypeshift.patch
Labels: 10-x-y, backport-check-skip, semver/patch

#28905 chore: cherry-pick 619083c7d8 from v8
  patches/v8/.patches
  patches/v8/merged_turbofan_harden_arrayprototypepop_and_arrayprototypeshift.patch
Labels: 11-x-y, backport-check-skip, semver/patch

#28915 fix: provide no-op implementation of app.setUserModelId
  lib/browser/api/app.ts
Labels: fast-track 🚅, semver/patch, target/13-x-y

#28827 chore: Update husky v6.0.0
  .husky/.gitignore
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: semver/none

#28920 docs: uniformize module API doc format
  docs/README.md
  docs/api/browser-view.md
  docs/api/menu.md
  docs/api/message-channel-main.md
  docs/api/message-port-main.md
  docs/api/share-menu.md
  docs/api/touch-bar.md
  docs/api/tray.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/12-x-y, target/13-x-y

#28931 chore: cherry-pick 668cf831e912 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-668cf831e912.patch
Labels: 10-x-y, backport-check-skip, semver/patch
