Repository electron/electron, pull requests merged in 2022-06, with the labels that each got.

#34411 fix: crash in WebFrameMain mojo connection when RenderFrameHost is nullptr
  shell/browser/api/electron_api_web_frame_main.cc
Labels: semver/patch, fast-track 🚅, target/18-x-y, target/19-x-y, target/20-x-y

#34407 chore: remove redundant @available checks
  shell/browser/api/electron_api_system_preferences_mac.mm
  shell/browser/mac/electron_application_delegate.mm
  shell/browser/mac/in_app_purchase_product.mm
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  shell/browser/ui/cocoa/electron_touch_bar.h
  shell/browser/ui/cocoa/electron_touch_bar.mm
Labels: semver/patch, no-backport

#34427 chore: increase timeout for electron-build step
  .circleci/config/base.yml
Labels: new-pr 🌱, semver/none, target/20-x-y

#34379 fix: fullscreen windows aren't resizable on macOS
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34365 fix: on macOS show BrowserWindow on maximize if not currently shown
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/patch, 19-x-y

#34452 test: fix for flaky renderer crash test
  spec-main/api-web-frame-main-spec.ts
Labels: semver/none, target/18-x-y, target/19-x-y, target/20-x-y

#34457 build: switch to --use-color flag for clang-tidy
  script/run-clang-tidy.ts
Labels: semver/none, no-backport

#34447 chore: fix nan spec runner on macOS
  script/nan-spec-runner.js
Labels: semver/none, target/18-x-y, target/19-x-y, target/20-x-y

#34456 chore: use --root instead of --project_root for cpplint
  script/lint.js
Labels: semver/none, target/20-x-y

#34473 fix: update normal bounds prior to minimizing
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34451 docs: add macOS height option info
  docs/tutorial/window-customization.md
Labels: documentation :notebook:, semver/patch, no-backport

#34491 fix: don't require glibc 2.29+ on linux arm64 builds
  script/sysroots.json
Labels: semver/patch, target/19-x-y, target/20-x-y

#34481 fix: make navigator.userAgentData non-empty
  BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  spec-main/chromium-spec.ts
Labels: semver/patch, target/20-x-y

#34514 test: use webContents.setWindowOpenHandler() in specs
  spec-main/api-browser-window-spec.ts
  spec-main/chromium-spec.ts
  spec-main/webview-spec.ts
Labels: semver/none, no-backport

#34529 test: add missing page-title-updated event spec for webview
  spec/webview-spec.js
Labels: semver/none, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#34523 fix: crash when `setWindowOpenHandler` callback throws
  lib/browser/api/web-contents.ts
  spec-main/guest-window-manager-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34388 feat: add panel support for BrowserWindow
  docs/api/browser-window.md
  filenames.gni
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_native_widget_mac.h
  shell/browser/ui/cocoa/electron_native_widget_mac.mm
  shell/browser/ui/cocoa/electron_ns_panel.h
  shell/browser/ui/cocoa/electron_ns_panel.mm
  shell/browser/ui/cocoa/electron_ns_window.h
  shell/browser/ui/cocoa/electron_ns_window.mm
Labels: semver/minor, no-backport

#33624 feat: add immersive dark mode on windows
  BUILD.gn
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  filenames.gni
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
  shell/browser/win/dark_mode.cc
  shell/browser/win/dark_mode.h
  shell/common/api/features.cc
  typings/internal-ambient.d.ts
Labels: semver/minor, api-review/requested 🗳, target/18-x-y, target/19-x-y, target/20-x-y

#34537 chore: cherry-pick 9768648fffc9 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-9768648fffc9.patch
  patches/config.json
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34535 chore: cherry-pick 21139756239b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-21139756239b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34534 chore: cherry-pick 21139756239b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-21139756239b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34541 chore: cherry-pick f1504440487f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f1504440487f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34561 chore: cherry-pick f1dd785e021e from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f1dd785e021e.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34568 chore: cherry-pick 03aa5ae75c29 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-03aa5ae75c29.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34556 chore: cherry-pick f3d01ff794dc from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f3d01ff794dc.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34566 chore: cherry-pick 801b904aea7d from angle
  patches/angle/.patches
  patches/angle/cherry-pick-801b904aea7d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34559 chore: cherry-pick e481fc655a62 from ffmpeg
  patches/ffmpeg/.patches
  patches/ffmpeg/cherry-pick-e481fc655a62.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34570 chore: cherry-pick 2782c7bc5bbe from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-2782c7bc5bbe.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34531 fix: make preload calculation identical between sandbox & non-sandboxed
  lib/browser/rpc-server.ts
  lib/common/ipc-messages.ts
  lib/renderer/init.ts
  patches/chromium/allow_in-process_windows_to_have_different_web_prefs.patch
  shell/browser/electron_browser_client.cc
  shell/browser/web_contents_preferences.cc
  shell/renderer/api/electron_api_web_frame.cc
  spec-main/api-browser-window-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/patch, target/20-x-y

#34598 chore: add ffmpeg patch dir to config.json
  patches/config.json
  patches/ffmpeg/cherry-pick-e481fc655a62.patch
Labels: semver/patch, backport-check-skip

#34597 chore: add ffmpeg patch dir to config.json
  patches/config.json
  patches/ffmpeg/cherry-pick-e481fc655a62.patch
Labels: semver/patch, backport-check-skip

#34582 fix: draggable regions updating on bounds change
  shell/browser/native_browser_view_views.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34600 build: Revert "Bump v19.0.6" & "Bump v19.0.5"
  ELECTRON_VERSION
  package.json
  shell/browser/resources/win/electron.rc
Labels: fast-track 🚅, backport-check-skip, semver/none, 19-x-y

#34588 chore: cleanup undocumented keys from webFrame.getWebPreference()
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/patch, no-backport

#34077 refactor: use stubs for gdk-pixbuf dependency
  BUILD.gn
  patches/chromium/make_gtk_getlibgtk_public.patch
  shell/browser/electron_browser_main_parts.cc
  shell/browser/ui/electron_gdk_pixbuf.sigs
  shell/browser/ui/electron_gtk.fragment
  shell/browser/ui/electron_gtk.sigs
  shell/browser/ui/gtk_util.cc
  shell/browser/ui/message_box_gtk.cc
Labels: semver/patch, in-flight/18-x-y, in-flight/19-x-y, target/20-x-y

#34615 refactor: remove deprecated drag-and-drop code
  shell/browser/ui/drag_util_mac.mm
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34652 refactor: remove deprecated drag-and-drop code
  shell/browser/ui/drag_util_mac.mm
Labels: backport, semver/patch, 19-x-y

#34644 build: mark existing Node.js flakes as dontcare
  script/node-spec-runner.js
Labels: semver/none, target/19-x-y, target/20-x-y

#34653 refactor: remove deprecated drag-and-drop code
  shell/browser/ui/drag_util_mac.mm
Labels: backport, semver/patch, 18-x-y

#34680 chore: Revert "build: build & release libcxx objects on darwin (#34586)"
  .circleci/config/base.yml
  script/release/release.js
  script/release/uploaders/upload.py
Labels: fast-track 🚅, semver/none, no-backport

#34667 chore: modernize base::Value usage in WebRequest
  shell/browser/api/electron_api_web_request.cc
Labels: semver/patch, no-backport

#34656 chore: modernize ListValue code in session
  shell/browser/api/electron_api_session.cc
  shell/browser/electron_browser_context.cc
Labels: semver/patch, no-backport

#34657 fix: modernize ListValue in net converters
  shell/common/gin_converters/net_converter.cc
Labels: semver/patch, no-backport

#34692 chore: cherry-pick 44c4e56fea2c from v8
  patches/v8/.patches
  patches/v8/cherry-pick-44c4e56fea2c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34682 chore: modernize base::Value usage in shell/renderer/printing
  shell/renderer/printing/print_render_frame_helper_delegate.cc
Labels: semver/patch, no-backport

#34691 chore: cherry-pick 44c4e56fea2c from v8
  patches/v8/.patches
  patches/v8/cherry-pick-44c4e56fea2c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34677 fix: WCO respects maximizable/closable/minimizable
  shell/browser/native_window_views.cc
  shell/browser/ui/views/win_caption_button_container.cc
  shell/browser/ui/views/win_caption_button_container.h
  shell/browser/ui/views/win_frame_view.h
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34714 chore: cherry-pick 22c61cfae5d1 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-22c61cfae5d1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34712 chore: cherry-pick 22c61cfae5d1 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-22c61cfae5d1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#34735 refactor: load webFrame via process._linkedBinding in security-warnings.ts
  lib/renderer/security-warnings.ts
Labels: semver/patch, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#34740 test: use maximize event instead of resize event
  spec-main/api-browser-window-spec.ts
Labels: semver/none, no-backport

#34729 docs: replace broken Windows taskbar images
  docs/images/windows-taskbar-icon-overlay.png
  docs/images/windows-taskbar-jumplist.png
  docs/images/windows-taskbar-thumbnail-toolbar.png
  docs/tutorial/windows-taskbar.md
Labels: documentation :notebook:, semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34732 chore: remove spurious trailing namespace comments
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_url_loader.cc
  shell/browser/electron_autofill_driver.cc
  shell/browser/extensions/api/runtime/electron_runtime_api_delegate.cc
Labels: semver/none, no-backport

#34711 build: fix building with enable_basic_printing false
  patches/chromium/printing.patch
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/none, no-backport

#34777 chore: update printing patch for main gclient sync
  patches/chromium/printing.patch
Labels: fast-track 🚅, semver/none, no-backport

#34666 chore: modernize base::Value usage in accessibility_ui
  shell/browser/ui/webui/accessibility_ui.cc
Labels: semver/patch, no-backport

#34782 build: update makeRequest parameters
  script/release/ci-release-build.js
Labels: fast-track 🚅, semver/none, no-backport

#34759 fix: `<datalist>` bounds vertical cutoff
  shell/browser/ui/views/autofill_popup_view.cc
Labels: semver/patch, target/19-x-y, target/20-x-y

#34573 build: fix release_dependency_versions workflow
  .github/workflows/release_dependency_versions.yml
Labels: semver/none, no-backport

#34789 build: remove appveyor hook to defunct service
  appveyor.yml
Labels: semver/none, target/18-x-y, target/19-x-y, target/20-x-y

#34655 chore: modernize some devtools code using deprecated ListValue
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, no-backport

#34662 chore: modernize ListValue usage in permission manager
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
Labels: semver/patch, no-backport

#34774 fix: potential crash caused by dlopen different gtk libraries
  BUILD.gn
  patches/chromium/.patches
  patches/chromium/make_gtk_getlibgtk_public.patch
  patches/chromium/ui_gtk_public_header.patch
  shell/browser/browser_linux.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/notifications/linux/libnotify_notification.cc
  shell/browser/ui/electron_gtk.fragment
  shell/browser/ui/electron_gtk.sigs
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/menu_bar.cc
  shell/common/application_info_linux.cc
  shell/common/platform_util_linux.cc
Labels: backport, semver/patch, 17-x-y

#34787 docs: document the removal of IA32 Linux support
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, target/19-x-y, target/20-x-y

#34798 docs: expand tutorial (#34604)
  .markdownlint.json
  docs/README.md
  docs/fiddles/tutorial-first-app/index.html
  docs/fiddles/tutorial-first-app/main.js
  docs/fiddles/tutorial-preload/index.html
  docs/fiddles/tutorial-preload/main.js
  docs/fiddles/tutorial-preload/preload.js
  docs/fiddles/tutorial-preload/renderer.js
  docs/images/gatekeeper.png
  docs/images/preload-example.png
  docs/tutorial/application-distribution.md
  docs/tutorial/code-signing.md
  docs/tutorial/distribution-overview.md
  docs/tutorial/examples.md
  docs/tutorial/introduction.md
  docs/tutorial/process-model.md
  docs/tutorial/tutorial-1-prerequisites.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-4-adding-features.md
  docs/tutorial/tutorial-5-packaging.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
Labels: backport, semver/patch, 19-x-y

#34799 docs: expand tutorial (#34604)
  .markdownlint.json
  docs/README.md
  docs/fiddles/tutorial-first-app/index.html
  docs/fiddles/tutorial-first-app/main.js
  docs/fiddles/tutorial-preload/index.html
  docs/fiddles/tutorial-preload/main.js
  docs/fiddles/tutorial-preload/preload.js
  docs/fiddles/tutorial-preload/renderer.js
  docs/images/gatekeeper.png
  docs/images/preload-example.png
  docs/tutorial/application-distribution.md
  docs/tutorial/code-signing.md
  docs/tutorial/distribution-overview.md
  docs/tutorial/examples.md
  docs/tutorial/introduction.md
  docs/tutorial/process-model.md
  docs/tutorial/tutorial-1-prerequisites.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-4-adding-features.md
  docs/tutorial/tutorial-5-packaging.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
Labels: backport, semver/patch, 18-x-y

#34797 docs: expand tutorial (#34604)
  .markdownlint.json
  docs/README.md
  docs/fiddles/tutorial-first-app/index.html
  docs/fiddles/tutorial-first-app/main.js
  docs/fiddles/tutorial-preload/index.html
  docs/fiddles/tutorial-preload/main.js
  docs/fiddles/tutorial-preload/preload.js
  docs/fiddles/tutorial-preload/renderer.js
  docs/images/gatekeeper.png
  docs/images/preload-example.png
  docs/tutorial/application-distribution.md
  docs/tutorial/code-signing.md
  docs/tutorial/distribution-overview.md
  docs/tutorial/examples.md
  docs/tutorial/introduction.md
  docs/tutorial/process-model.md
  docs/tutorial/tutorial-1-prerequisites.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-4-adding-features.md
  docs/tutorial/tutorial-5-packaging.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
Labels: backport, semver/patch, 20-x-y
