Repository electron/electron, pull requests merged in 2022-07, with the labels that each got.

#34794 chore: modernize Value usage in converters
  filenames.gni
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_content_tracing.cc
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_cookies.h
  shell/browser/api/electron_api_debugger.cc
  shell/browser/api/electron_api_debugger.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_system_preferences_mac.mm
  shell/browser/browser.h
  shell/browser/browser_linux.cc
  shell/browser/browser_mac.mm
  shell/browser/browser_win.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/url_pipe_loader.cc
  shell/browser/net/url_pipe_loader.h
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  shell/common/gin_converters/extension_converter.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/value_converter.cc
  shell/common/gin_converters/value_converter.h
  shell/common/v8_value_converter.cc
  shell/common/v8_value_converter.h
  spec-main/api-system-preferences-spec.ts
Labels: semver/patch, no-backport

#34684 chore: cherry-pick f427936d32db from chromium
  patches/chromium/.patches
  patches/chromium/m102_ensure_raw_ptr_t_and_t_are_treated_identically_in_base.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34686 chore: cherry-pick d0882b3dff76 from v8
  patches/v8/.patches
  patches/v8/version_10_2_154_10_cherry-pick.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34687 chore: cherry-pick d0882b3dff76 from v8
  patches/v8/.patches
  patches/v8/version_10_2_154_10_cherry-pick.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34731 chore: fix typos
  docs/api/environment-variables.md
  docs/tutorial/process-model.md
  lib/browser/api/auto-updater/squirrel-update-win.ts
  lib/browser/api/menu.ts
  script/lint.js
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.cc
Labels: semver/none, no-backport

#34730 chore: update Discord invite links
  README.md
  docs/tutorial/examples.md
  docs/tutorial/introduction.md
  docs/tutorial/tutorial-4-adding-features.md
  docs/tutorial/tutorial-6-publishing-updating.md
  lib/browser/default-menu.ts
Labels: documentation :notebook:, semver/patch, no-backport

#34796 chore: modernize base::Value useage in asar/archive
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
Labels: semver/patch, no-backport

#34685 chore: cherry-pick f427936d32db from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f427936d32db.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34771 fix: WCO pressed background state updates
  shell/browser/native_window_views_win.cc
  shell/browser/ui/views/win_caption_button_container.h
Labels: semver/patch, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#34827 test: add first-party-set chromium tests
  spec-main/chromium-spec.ts
  spec/fixtures/api/first-party-sets/base/main.js
  spec/fixtures/api/first-party-sets/base/package.json
  spec/fixtures/api/first-party-sets/command-line/main.js
  spec/fixtures/api/first-party-sets/command-line/package.json
Labels: semver/none, target/20-x-y

#34834 fix: `setRepresentedFilename` with non-default `titlebarStyle`
  shell/browser/native_window_mac.mm
Labels: semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y, target/20-x-y

#34844 fix: ensure v8 pointer compression + sandbox is enabled on 64bit native modules
  patches/node/.patches
  patches/node/build_ensure_v8_pointer_compression_sandbox_is_enabled_on_64bit.patch
  script/generate-config-gypi.py
Labels: semver/patch, new-pr 🌱, target/20-x-y

#34833 fix: safer check for WCO button updates
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34846 build: use third_party DEPOT_TOOLS when running lint scripts
  script/lint.js
Labels: semver/none, no-backport

#34736 chore: improve run-clang-tidy.ts behavior when filenames < jobs
  script/run-clang-tidy.ts
Labels: semver/none, no-backport

#34855 fix: set Wayland application ID
  shell/browser/native_window_views.cc
  shell/browser/notifications/linux/libnotify_notification.cc
  shell/common/platform_util.h
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#32869 feat: sandbox preloads by default
  shell/browser/web_contents_preferences.cc
  spec-main/fixtures/apps/libuv-hang/main.js
  spec/webview-spec.js
Labels: semver/major, api-review/approved ✅, no-backport

#34882 chore: cherry-pick 763d847f1e5a from webrtc
  patches/webrtc/.patches
  patches/webrtc/cherry-pick-763d847f1e5a.patch
Labels: semver/patch, backport-check-skip, 18-x-y

#34880 chore: cherry-pick 13ffdf63a471 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-13ffdf63a471.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34790 fix: update Windows caption buttons to match Win11 style
  filenames.gni
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_caption_button.h
  shell/browser/ui/views/win_icon_painter.cc
  shell/browser/ui/views/win_icon_painter.h
Labels: semver/patch, target/20-x-y

#34886 fix: ensure that requestMediaKeySystemAccess resolves
  shell/app/electron_content_client.cc
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y, target/20-x-y

#34881 chore: cherry-pick 13ffdf63a471 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-13ffdf63a471.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34883 chore: cherry-pick 763d847f1e5a from webrtc
  patches/webrtc/.patches
  patches/webrtc/cherry-pick-763d847f1e5a.patch
Labels: semver/patch, backport-check-skip, 17-x-y

#34897 fix: `base::DictionaryValue` usage in APNS notifs
  shell/browser/api/electron_api_push_notifications.h
  shell/browser/api/electron_api_push_notifications_mac.mm
  shell/browser/mac/electron_application_delegate.mm
Labels: semver/patch, fast-track 🚅, no-backport

#34766 fix: alwaysOnTop browser window option for X11 Linux
  shell/browser/native_window_views.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34910 fix: call loadUrl when opening new windows from links
  lib/browser/guest-window-manager.ts
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/apps/open-new-window-from-link/index.html
  spec-main/fixtures/apps/open-new-window-from-link/main.js
  spec-main/fixtures/apps/open-new-window-from-link/new-window-page.html
  spec-main/fixtures/apps/open-new-window-from-link/package.json
  spec-main/fixtures/apps/open-new-window-from-link/preload.js
Labels: backport, semver/patch, 18-x-y

#34906 fix: fullscreen windows aren't resizable on macOS
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/patch, 19-x-y

#34907 fix: fullscreen windows aren't resizable on macOS
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/patch, 18-x-y

#34931 chore: cherry-pick 5e227bebf193 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-5e227bebf193.patch
Labels: semver/patch, backport-check-skip, no-backport, main

#34932 fix: do not define _LIBCPP_ABI_NAMESPACE=Cr for all native modules
  patches/node/.patches
  patches/node/build_define_libcpp_abi_namespace_as_cr_to_align_with_chromium.patch
  patches/node/build_ensure_v8_pointer_compression_sandbox_is_enabled_on_64bit.patch
  script/nan-spec-runner.js
Labels: semver/patch, fast-track 🚅, target/20-x-y

#34929 fix: prevent brief display of "Ozone X11" in window title on Linux
  patches/chromium/.patches
  patches/chromium/remove_default_window_title.patch
Labels: semver/patch, backport-check-skip, target/18-x-y, 19-x-y

#34944 fix: do not define _LIBCPP_ABI_NAMESPACE=Cr for all native modules
  patches/node/.patches
  patches/node/build_define_libcpp_abi_namespace_as_cr_to_align_with_chromium.patch
  script/nan-spec-runner.js
Labels: backport, semver/patch, 20-x-y

#34956 ci: wait longer for goma to be ready
  .circleci/config/base.yml
Labels: fast-track 🚅, semver/none, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#34892 fix: potential hang on print settings failure
  patches/chromium/printing.patch
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34899 test: optionally validate disabled Node.js specs
  script/node-disabled-tests.json
  script/node-spec-runner.js
Labels: semver/none, no-backport

#34904 fix: crash on `BrowserWindow.setEnabled()`
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34893 fix: delegate to `PrintViewManagerBase` on failed print
  shell/browser/printing/print_view_manager_electron.cc
Labels: semver/patch, target/20-x-y

#34795 fix: merge crash annotations instead of overwriting
  shell/app/electron_crash_reporter_client.cc
Labels: semver/patch, no-backport

#34982 build: run CI tests on Xcode 13.3.0
  .circleci/config/base.yml
Labels: backport, semver/none, 18-x-y

#34895 refactor: unduplicate MediaStreamDevicesController
  BUILD.gn
  filenames.gni
  patches/chromium/.patches
  patches/chromium/short-circuit_permissions_checks_in_mediastreamdevicescontroller.patch
  shell/browser/media/media_capture_devices_dispatcher.cc
  shell/browser/media/media_capture_devices_dispatcher.h
  shell/browser/media/media_stream_devices_controller.cc
  shell/browser/media/media_stream_devices_controller.h
  shell/browser/web_contents_permission_helper.cc
  spec-main/chromium-spec.ts
Labels: semver/patch, no-backport

#34918 build: consolidate gn templates
  build/asar.gni
  build/node.gni
  patches/node/build_add_gn_build_files.patch
Labels: semver/none, no-backport

#34995 build: update mediastreamdevicescontroller.patch
  patches/chromium/short-circuit_permissions_checks_in_mediastreamdevicescontroller.patch
Labels: fast-track 🚅, semver/none, no-backport

#35000 chore: cherry-pick 8ea66a7833e2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-8ea66a7833e2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35002 chore: cherry-pick 3cbd5973d704 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3cbd5973d704.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35001 chore: cherry-pick 3cbd5973d704 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3cbd5973d704.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34937 fix: add support for --ozone-platform-hint flag on Linux
  filenames.gni
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
  shell/browser/electron_browser_main_parts_linux.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#32941 refactor: only create webContents after 'will-attach-webview'
  lib/browser/guest-view-manager.ts
  lib/common/ipc-messages.ts
  lib/renderer/web-view/guest-view-internal.ts
  lib/renderer/web-view/web-view-element.ts
  lib/renderer/web-view/web-view-impl.ts
  shell/browser/api/electron_api_web_view_manager.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  typings/internal-electron.d.ts
Labels: semver/patch, new-pr 🌱, target/20-x-y

#34894 fix: clean up callback handling in `webContents.print()`
  patches/chromium/printing.patch
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35010 chore: remove unused WebContents._sendToFrameInternal
  lib/browser/api/web-contents.ts
  typings/internal-electron.d.ts
Labels: semver/patch, new-pr 🌱, no-backport

#34997 chore: cherry-pick d7a5d6b38ea8 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-d7a5d6b38ea8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#35004 chore: cherry-pick 22abbad430b6 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-22abbad430b6.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#34983 build: run CI tests on Xcode 13.3.0
  .circleci/config/base.yml
  script/zip_manifests/dist_zip.mac.arm64.manifest
  script/zip_manifests/dist_zip.mac.x64.manifest
  script/zip_manifests/dist_zip.mac_mas.arm64.manifest
  script/zip_manifests/dist_zip.mac_mas.x64.manifest
Labels: backport, semver/none, 17-x-y

#35024 docs: update build dependencies for Fedora
  docs/development/build-instructions-linux.md
Labels: documentation :notebook:, semver/patch, no-backport

#35022 refactor: use Get/SetID from views:View in Button
  shell/browser/ui/views/menu_bar.cc
  shell/browser/ui/views/menu_delegate.cc
Labels: semver/none, no-backport

#34999 chore: cherry-pick 8ea66a7833e2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-8ea66a7833e2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#34998 chore: cherry-pick d7a5d6b38ea8 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-d7a5d6b38ea8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35035 docs: Add missing link to tutorial page
  docs/tutorial/introduction.md
Labels: documentation :notebook:, semver/patch, target/19-x-y, target/20-x-y

#34958 fix: properly fire serial-port-added and serial-port-removed events
  shell/browser/serial/electron_serial_delegate.cc
  shell/browser/serial/electron_serial_delegate.h
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/serial/serial_chooser_context.h
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/serial/serial_chooser_controller.h
Labels: semver/patch, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#34689 chore: cherry-pick ecad352cd614 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-ecad352cd614.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35051 fix: inertial scroll is broken when the scrollable element has an overlay with pointer-events: none
  patches/chromium/.patches
  patches/chromium/keep_handling_scroll_update_if_you_can.patch
Labels: semver/patch, backport-check-skip, 19-x-y

#35059 test: migrate clipboard spec to spec-main
  spec-main/api-clipboard-spec.ts
Labels: semver/none, no-backport

#35062 test: migrate nativeImage specs to main
  docs/api/native-image.md
  spec-main/api-native-image-spec.ts
Labels: semver/none, no-backport

#35055 test: remove unused spec/expect-helpers
  spec/chromium-spec.js
  spec/expect-helpers.js
Labels: semver/none, no-backport

#35064 test: remove references to robotjs
  spec-main/api-global-shortcut-spec.ts
  spec-main/api-web-contents-spec.ts
  spec/package.json
Labels: semver/none, no-backport

#35056 test: migrate process module specs to spec-main
  spec-main/api-process-spec.ts
  spec/api-process-spec.js
Labels: semver/none, no-backport

#35050 fix: Make disable_color_correct_rendering patch work again
  patches/chromium/disable_color_correct_rendering.patch
Labels: semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y, target/20-x-y

#35063 test: move chromium spec config to its own folder
  spec-chromium/BUILD.gn
  spec-chromium/configs/browsertests.yml
  spec-chromium/configs/unittests.yml
Labels: semver/none, no-backport

#35071 test: remove duplicate test that is causing hang in Windows
  spec/chromium-spec.js
Labels: semver/none, no-backport

#35070 fix: handle WCO pressed state when going maximized -> minimized
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
Labels: semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y, target/20-x-y

#35057 test: add process module tests for main process
  spec-main/api-process-spec.ts
Labels: semver/none, no-backport

#34843 fix: allow setsize to be called within a move or resize for preventDefault
  shell/browser/native_window_views.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35078 fix: use win_clang_x64 binary for x86 extract symbols
  appveyor.yml
  build/extract_symbols.gni
  script/release/release.js
  script/release/uploaders/upload.py
Labels: semver/patch, new-pr 🌱, blocks-release, target/18-x-y, target/19-x-y, target/20-x-y

#35075 fix: crash on startup in X11
  shell/browser/electron_browser_main_parts.cc
Labels: semver/patch, new-pr 🌱, blocks-release, target/20-x-y

#35087 fix: Make disable_color_correct_rendering patch work again
  patches/chromium/disable_color_correct_rendering.patch
Labels: backport, semver/patch, 20-x-y

#35081 test: migrate more chromium specs to main
  spec-main/chromium-spec.ts
  spec/chromium-spec.js
  spec/fixtures/pages/shared_worker.html
  spec/fixtures/pages/worker.html
Labels: semver/none, no-backport

#35080 test: migrate the rest of the webFrame tests to main
  spec-main/api-web-frame-spec.ts
  spec/api-web-frame-spec.js
Labels: semver/none, no-backport

#35065 chore: add electon deps to //src gitignore
  patches/chromium/.patches
  patches/chromium/chore_add_electron_deps_to_gitignores.patch
Labels: semver/none, no-backport

#35019 docs: don't wait for ready event to register open-url listener
  docs/api/app.md
Labels: documentation :notebook:, semver/none, no-backport

#35058 test: migrate shell specs to main process
  shell/common/api/electron_api_shell.cc
  spec-main/api-shell-spec.ts
  spec/api-shell-spec.js
Labels: semver/none, no-backport

#35105 ci: explicitly use pylint-1.5 for pylint
  script/lint.js
Labels: fast-track 🚅, semver/none, target/17-x-y

#35096 fix: use win_clang_x64 binary for x86 extract symbols (#35078)
  build/extract_symbols.gni
Labels: backport, semver/patch, 18-x-y

#35088 fix: Make disable_color_correct_rendering patch work again
  patches/chromium/disable_color_correct_rendering.patch
Labels: backport, semver/patch, 18-x-y

#35079 fix: Make disable_color_correct_rendering patch work again
  patches/chromium/disable_color_correct_rendering.patch
Labels: backport, semver/patch, 19-x-y

#35103 chore: cherry-pick 664e0d8b4cfb from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-664e0d8b4cfb.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#35102 chore: cherry-pick 664e0d8b4cfb from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-664e0d8b4cfb.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35101 chore: cherry-pick 2a2d7536227b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-2a2d7536227b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#35100 chore: cherry-pick 3466cc056b05 from pdfium
  patches/pdfium/.patches
  patches/pdfium/cherry-pick-3466cc056b05.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#35099 chore: cherry-pick 3466cc056b05 from pdfium
  patches/config.json
  patches/pdfium/.patches
  patches/pdfium/cherry-pick-3466cc056b05.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35109 ci: switch to GHA for WOA
  .github/workflows/electron_woa_testing.yml
  appveyor.yml
  azure-pipelines-arm.yml
  azure-pipelines-woa.yml
  script/release/ci-release-build.js
  vsts-arm-test-steps.yml
  vsts-arm32v7.yml
  vsts-arm64v8.yml
Labels: semver/none, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#35122 docs: update E21 release date
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/20-x-y

#35120 ci: switch to GHA for WOA
  .github/workflows/electron_woa_testing.yml
  appveyor.yml
  azure-pipelines-arm.yml
  azure-pipelines-woa.yml
  script/release/ci-release-build.js
  vsts-arm-test-steps.yml
  vsts-arm32v7.yml
  vsts-arm64v8.yml
Labels: backport, semver/none, target/18-x-y, target/19-x-y, 20-x-y

#35121 ci: switch to GHA for WOA
  .github/workflows/electron_woa_testing.yml
  appveyor.yml
  azure-pipelines-arm.yml
  azure-pipelines-woa.yml
  script/release/ci-release-build.js
  vsts-arm-test-steps.yml
  vsts-arm32v7.yml
  vsts-arm64v8.yml
Labels: backport, semver/none, 17-x-y

#35098 chore: cherry-pick 902f0d144a5b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-902f0d144a5b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#35097 chore: cherry-pick 902f0d144a5b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-902f0d144a5b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35069 fix: empty result of `webContents.getUserAgent()`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  spec-main/api-web-contents-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#34978 docs: new main -> renderers messageChannel example
  docs/tutorial/message-ports.md
Labels: documentation :notebook:, semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35137 fix: ensure that v8 sandbox isnt enabled for arm
  patches/node/build_ensure_v8_pointer_compression_sandbox_is_enabled_on_64bit.patch
Labels: backport, semver/patch, 20-x-y

#35125 feat: sandbox preloads by default
  shell/browser/web_contents_preferences.cc
  spec-main/fixtures/apps/libuv-hang/main.js
  spec/webview-spec.js
Labels: backport, semver/major, backport/requested 🗳, 20-x-y
