Repository electron/electron, pull requests merged in 2022-01, with the labels that each got.

#32217 chore: cherry-pick 05ccacee14 from v8.
  patches/v8/.patches
  patches/v8/version_9_6_180_13_cherry-pick.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32282 docs: fix typo in quick-start.md
  docs/tutorial/quick-start.md
Labels: semver/none, target/16-x-y, target/17-x-y

#32208 docs: fix typo in bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation :notebook:, semver/none, target/17-x-y

#32235 chore: cherry-pick 04a58fedd5 from v8
  patches/v8/.patches
  patches/v8/merged_allow_compiled_module_invalidation_at_wasmstreaming_finish.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32304 build: remove stale dependency for webrtc desktop capture module
  BUILD.gn
Labels: semver/none, target/17-x-y

#32257 chore: cherry-pick f781748dcb3c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f781748dcb3c.patch
Labels: semver/patch, backport-check-skip, 15-x-y

#32293 docs: Docs rendering issue with rendering on electronjs quick-start
  docs/tutorial/quick-start.md
Labels: semver/patch, target/17-x-y

#32053 docs: add Bugsnag as a 3rd party crash server
  docs/api/crash-reporter.md
Labels: semver/none, no-backport

#32227 chore: cherry-pick 809830f1b3 from webrtc
  patches/webrtc/.patches
  patches/webrtc/merge_to_m96_sdp_reject_large_number_of_channels.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32010 chore: cherry-pick 6bb320d134b1 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6bb320d134b1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32256 fix: crash caused by `app.getLocaleCountryCode()`
  shell/browser/api/electron_api_app.cc
Labels: semver/patch, target/16-x-y, target/17-x-y

#32109 fix: window.open not overriding parent's webPreferences
  docs/api/window-open.md
  lib/browser/api/web-contents.ts
  lib/browser/guest-window-manager.ts
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_render_frame_observer.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
  spec-main/chromium-spec.ts
  spec-main/fixtures/crash-cases/setimmediate-window-open-crash/index.html
  spec/chromium-spec.js
  spec/static/main.js
Labels: backport, semver/patch, target/14-x-y, 15-x-y

#32236 chore: cherry-pick 04a58fedd5 from v8
  patches/v8/.patches
  patches/v8/merged_allow_compiled_module_invalidation_at_wasmstreaming_finish.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32237 chore: cherry-pick 04a58fedd5 from v8
  patches/v8/.patches
  patches/v8/merged_allow_compiled_module_invalidation_at_wasmstreaming_finish.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32232 chore: cherry-pick 2b978fb482 from chromium
  patches/chromium/.patches
  patches/chromium/m96_fileapi_move_origin_checks_in_bloburlstore_sooner.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32233 chore: cherry-pick 2b978fb482 from chromium
  patches/chromium/.patches
  patches/chromium/m96_fileapi_move_origin_checks_in_bloburlstore_sooner.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32234 chore: cherry-pick 2b978fb482 from chromium
  patches/chromium/.patches
  patches/chromium/m96_fileapi_move_origin_checks_in_bloburlstore_sooner.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32205 docs: correct webFrame description
  docs/api/web-frame.md
Labels: documentation :notebook:, semver/none, target/16-x-y, target/17-x-y

#32220 fix: register wrong command for setAsDefaultProtocolClient
  shell/browser/browser_win.cc
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32218 chore: cherry-pick 05ccacee14 from v8.
  patches/v8/.patches
  patches/v8/version_9_6_180_13_cherry-pick.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32182 chore: cherry-pick da11d71a0227 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-da11d71a0227.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32324 fix: rename patch file to .patch to conform to naming standard which utilizes .gitattributes settings
  patches/chromium/.patches
  patches/chromium/mas_gate_private_enterprise_APIs.patch
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32011 chore: cherry-pick 109fde1088be from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-109fde1088be.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32349 fix: older systems crash when playing media files
  patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
Labels: backport, semver/patch, 14-x-y

#32339 fix: use allocationtype kold in v8 scriptormodule legacy lifetime
  patches/v8/.patches
  patches/v8/fix_use_allocationtype_kold_in_v8_scriptormodule_legacy_lifetime.patch
Labels: semver/patch, new-pr 🌱, target/17-x-y

#32348 fix: older systems crash when playing media files
  patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
Labels: backport, semver/patch, 13-x-y

#32352 fix: text input performance regression
  patches/chromium/.patches
  patches/chromium/revert_do_not_display_grammar_error_if_there_it_overlaps_with_spell.patch
Labels: semver/patch, backport-check-skip, 16-x-y

#32279 docs: fix wording on testing documentation
  docs/development/testing.md
Labels: documentation :notebook:, semver/patch, target/16-x-y, target/17-x-y

#32098 docs: improve BrowserView example
  docs/api/browser-view.md
Labels: documentation :notebook:, semver/none, target/16-x-y, target/17-x-y

#32187 chore: cherry-pick 2b98abd8cb6c from angle
  patches/angle/.patches
  patches/angle/cherry-pick-2b98abd8cb6c.patch
  patches/config.json
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32116 chore: deprecate nativeWindowOpen in Electron 17
  docs/breaking-changes.md
  lib/browser/api/web-contents.ts
Labels: semver/major, api-review/approved ✅, target/17-x-y

#32009 chore: cherry-pick 6bb320d134b1 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6bb320d134b1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#29405 feat: remove nativeWindowOpen option
  docs/README.md
  docs/api/browser-window-proxy.md
  docs/api/browser-window.md
  docs/api/structures/post-body.md
  docs/api/window-open.md
  docs/breaking-changes.md
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  lib/browser/guest-view-manager.ts
  lib/browser/guest-window-manager.ts
  lib/browser/guest-window-proxy.ts
  lib/browser/init.ts
  lib/common/ipc-messages.ts
  lib/renderer/common-init.ts
  lib/renderer/window-setup.ts
  patches/chromium/allow_in-process_windows_to_have_different_web_prefs.patch
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/electron_browser_client.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/api/electron_api_v8_util.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/api/electron_api_web_frame.cc
  spec-main/api-browser-window-spec.ts
  spec-main/api-ipc-renderer-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/chromium-spec.ts
  spec-main/fixtures/api/new-window-preload.js
  spec-main/fixtures/api/window-open-preload.js
  spec-main/fixtures/crash-cases/setimmediate-window-open-crash/index.js
  spec-main/fixtures/snapshots/native-window-open.snapshot.txt
  spec-main/fixtures/snapshots/proxy-window-open.snapshot.txt
  spec-main/guest-window-manager-spec.ts
  spec-main/webview-spec.ts
  spec/webview-spec.js
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/major, api-review/requested 🗳, no-backport

#32024 feat: add Substitutions menu roles on macOS
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.ts
  shell/browser/ui/cocoa/electron_menu_controller.mm
  spec-main/api-menu-item-spec.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#32370 fix: drop nativeWindowOpen deprecation warning
  lib/browser/api/web-contents.ts
Labels: semver/patch, fast-track 🚅, no-backport

#32188 chore: cherry-pick 2b98abd8cb6c from angle
  patches/angle/.patches
  patches/angle/cherry-pick-2b98abd8cb6c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32340 fix: Don't create console window when creating process
  patches/node/.patches
  patches/node/fix_don_t_create_console_window_when_creating_process.patch
Labels: semver/patch, target/16-x-y, target/17-x-y

#32363 chore: cleanup spec-main/ambient.d.ts
  shell/browser/api/electron_api_web_contents.h
  spec-main/ambient.d.ts
  spec-main/api-protocol-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/chromium-spec.ts
Labels: semver/patch, no-backport

#32266 fix: Allow x64 arch on Mac Rosetta
  npm/install.js
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32372 docs: left is a valid mode in contents.openDevTools() options
  docs/api/web-contents.md
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32364 fix: incorrect `skipTransformProcessType` option parsing in `win.setVisibleOnAllWorkspaces()`
  shell/browser/api/electron_api_base_window.cc
Labels: semver/patch, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32362 docs: fix note for `will-move` event
  docs/api/browser-window.md
Labels: documentation :notebook:, semver/none, target/16-x-y, target/17-x-y

#32216 chore: cherry-pick 05ccacee14 from v8.
  patches/v8/.patches
  patches/v8/version_9_6_180_13_cherry-pick.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32222 docs: clarify case insensitive dictionary hosting
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, target/16-x-y, target/17-x-y

#32210 chore: cherry-pick dbde8795233a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-dbde8795233a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32224 chore: cherry-pick 891020ed64d4 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-891020ed64d4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31460 feat: Add `first-instance-ack` event to the `app.requestSingleInstanceLock()` flow
  docs/api/app.md
  patches/chromium/.patches
  patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  spec-main/api-app-spec.ts
  spec/fixtures/api/singleton-data/main.js
Labels: semver/minor, api-review/requested 🗳, no-backport

#32172 chore: cherry-pick 6bb320d134b1 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6bb320d134b1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32303 fix: Support running git-[im,ex]port-patches with Python3 too
  script/git-export-patches
  script/git-import-patches
  script/lib/git.py
Labels: semver/none, target/16-x-y, target/17-x-y

#32403 docs: left is a valid mode in contents.openDevTools() options
  docs/api/web-contents.md
Labels: backport, semver/patch, 16-x-y

#32404 docs: left is a valid mode in contents.openDevTools() options
  docs/api/web-contents.md
Labels: backport, semver/patch, 15-x-y

#32405 docs: left is a valid mode in contents.openDevTools() options
  docs/api/web-contents.md
Labels: backport, semver/patch, 14-x-y

#32191 chore: cherry-pick 05e69c75905f from angle
  patches/angle/.patches
  patches/angle/cherry-pick-05e69c75905f.patch
  patches/angle/cherry-pick-891020ed64d4.patch
Labels: semver/patch, backport-check-skip, 14-x-y

#32408 fix: node test failure
  patches/node/.patches
  patches/node/test_fix_test-fs-utimes_on_non-y2k38_file_systems.patch
Labels: backport-check-skip, semver/none

#32226 chore: cherry-pick 809830f1b3 from webrtc
  patches/webrtc/.patches
  patches/webrtc/merge_to_m96_sdp_reject_large_number_of_channels.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32225 chore: cherry-pick 891020ed64d4 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-891020ed64d4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32212 chore: cherry-pick dbde8795233a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-dbde8795233a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32211 chore: cherry-pick dbde8795233a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-dbde8795233a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32190 chore: cherry-pick 05e69c75905f from angle
  patches/angle/.patches
  patches/angle/cherry-pick-05e69c75905f.patch
  patches/angle/cherry-pick-891020ed64d4.patch
Labels: semver/patch, backport-check-skip, 15-x-y

#32185 chore: cherry-pick bdffa0ea5148 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-bdffa0ea5148.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32181 chore: cherry-pick da11d71a0227 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-da11d71a0227.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32023 chore: cherry-pick f781748dcb3c from chromium
  patches/chromium/.patches
  patches/chromium/show_the_origin_of_the_last_redirecting_server_in_external_protocol.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32034 chore: cherry-pick 855df1837e from chromium
  patches/chromium/.patches
  patches/chromium/sandbox_fix_sandbox_inheritance_m96_merge.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32033 chore: cherry-pick 855df1837e from chromium
  patches/chromium/.patches
  patches/chromium/sandbox_fix_sandbox_inheritance_m96_merge.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32420 build: pin colors to v1.4.0 in package.json
  package.json
  yarn.lock
Labels: semver/patch, fast-track 🚅, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32415 chore: update notification provenance patch
  patches/chromium/notification_provenance.patch
Labels: new-pr 🌱, semver/none, no-backport

#32413 chore: fix incorrect usage of reference
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
Labels: semver/none, no-backport

#32414 chore: update DesktopMediaList patch
  patches/chromium/desktop_media_list.patch
Labels: semver/none, no-backport

#32386 fix: `will-attach-webview` handler modifying `params.instanceId` does not break `<webview>`
  lib/browser/guest-view-manager.ts
  lib/renderer/web-view/web-view-impl.ts
  spec/static/main.js
  spec/webview-spec.js
  typings/internal-electron.d.ts
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32186 chore: cherry-pick bdffa0ea51 from angle
  patches/angle/.patches
  patches/angle/m96_fix_changing_attached_renderbuffer_from_msrtt_to_non-msrtt.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32184 chore: cherry-pick bdffa0ea5148 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-bdffa0ea5148.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32183 chore: cherry-pick da11d71a0227 from chromium
  patches/chromium/.patches
  patches/chromium/mojo_ipc_drop_messages_targeting_invalid_task_runner.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32032 chore: cherry-pick 855df1837e from chromium
  patches/chromium/.patches
  patches/chromium/sandbox_fix_sandbox_inheritance_m96_merge.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32022 chore: cherry-pick f781748dcb3c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f781748dcb3c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32356 feat: expose blowfish cipher family
  patches/boringssl/.patches
  patches/boringssl/expose_blowfish_ciphers.patch
  patches/chromium/boringssl_build_gn.patch
  spec/node-spec.js
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/17-x-y

#32017 chore: cherry-pick 27eb11a28555 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-27eb11a28555.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32016 chore: cherry-pick 27eb11a28555 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-27eb11a28555.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32015 chore: cherry-pick 27eb11a28555 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-27eb11a28555.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32421 chore: update IsWebContentsCreationOverridden patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
Labels: semver/none, no-backport

#32014 chore: cherry-pick f0a63e1f361f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f0a63e1f361f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32422 docs: explicitly allow string for MessageBoxOptions.icon
  docs/api/dialog.md
Labels: documentation :notebook:, semver/patch, target/17-x-y

#32443 build: pin colors to v1.4.0 in package.json
  package.json
  yarn.lock
Labels: backport, semver/patch, 14-x-y

#32444 build: pin colors to v1.4.0 in package.json
  package.json
  yarn.lock
Labels: backport, semver/patch, 13-x-y

#32013 chore: cherry-pick f0a63e1f361f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f0a63e1f361f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32012 chore: cherry-pick f0a63e1f361f from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f0a63e1f361f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#31904 chore: cherry-pick 1a8af2da50e4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1a8af2da50e4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32433 fix: optional postMessage transfer arg
  shell/browser/api/electron_api_web_frame_main.cc
  shell/renderer/api/electron_api_ipc_renderer.cc
  spec-main/api-ipc-spec.ts
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32478 docs: fix anchors for broken relative links
  docs/api/browser-window.md
  docs/api/environment-variables.md
Labels: documentation :notebook:, semver/patch, target/15-x-y, target/16-x-y, target/17-x-y

#32442 fix: re-enable PartitionAlloc on macOS
  BUILD.gn
  filenames.gni
  patches/chromium/.patches
  patches/chromium/build_disable_partitionalloc_on_mac.patch
  shell/app/electron_main.h
  shell/app/electron_main_linux.cc
  shell/app/electron_main_mac.cc
  shell/app/electron_main_win.cc
  shell/app/uv_stdio_fix.cc
  shell/app/uv_stdio_fix.h
Labels: semver/patch, no-backport

#32441 fix: maximize/unmaximize firing on linux
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32438 fix: check for maximized window before unmaximizing
  shell/browser/native_window_views.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32228 chore: cherry-pick 809830f1b3 from webrtc
  patches/webrtc/.patches
  patches/webrtc/merge_to_m96_sdp_reject_large_number_of_channels.patch
Labels: security 🔒, semver/patch, backport-check-skip, 13-x-y

#32448 docs: Remove broken link and update CircleCI's name
  docs/tutorial/testing-on-headless-ci.md
Labels: semver/none, no-backport

#32093 docs: Clarify `will-redirect` event
  docs/api/web-contents.md
Labels: semver/none, no-backport

#32485 docs: fix broken images for symbol server setup
  docs/development/debugging-with-symbol-server.md
  docs/images/vs-options-debugging-symbols.png
  docs/images/vs-tools-options.png
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32497 fix: maximize/unmaximize firing on linux
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: backport, semver/patch, 16-x-y

#32499 fix: maximize/unmaximize firing on linux
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: backport, semver/patch, 14-x-y

#32498 fix: maximize/unmaximize firing on linux
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: backport, semver/patch, 15-x-y

#32512 fix: crash when saving edited PDF files
  patches/chromium/.patches
  patches/chromium/fix_crash_when_saving_edited_pdf_files.patch
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y

#32517 fix: undefined backgroundColor
  shell/browser/api/electron_api_browser_window.cc
Labels: semver/patch, target/16-x-y, target/17-x-y

#32540 fix: strip crashpad_handler binary
  script/lib/config.py
Labels: semver/patch, new-pr 🌱, target/15-x-y, target/16-x-y, target/17-x-y

#32542 test: disable flaky test on WOA
  spec-main/webview-spec.ts
Labels: semver/none, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32547 chore: cherry-pick cc44ae61f37b from angle
  patches/angle/.patches
  patches/angle/cherry-pick-cc44ae61f37b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#32546 chore: cherry-pick cc44ae61f37b from angle
  patches/angle/.patches
  patches/angle/cherry-pick-cc44ae61f37b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#32563 docs: fix supported versions
  docs/tutorial/support.md
Labels: documentation :notebook:, backport-check-skip, semver/none, 16-x-y

#32543 fix: undisable AXTextMarker and related APIs on MAS
  patches/chromium/mas_no_private_api.patch
Labels: semver/patch, target/17-x-y

#32569 ci: call autoninja without ninjalog_uploader_wrapper.py
  .circleci/build_config.yml
Labels: fast-track 🚅, semver/none, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32564 fix: bundle a11y strings in resources
  electron_paks.gni
Labels: semver/patch, new-pr 🌱, target/17-x-y

#32566 docs: fix anchors for broken relative links
  docs/api/browser-window.md
  docs/api/environment-variables.md
Labels: backport, semver/patch, 16-x-y

#32568 docs: fix anchors for broken relative links
  docs/api/browser-window.md
  docs/api/environment-variables.md
Labels: backport, semver/patch, 15-x-y

#31853 feat: add rawHeaders to IncomingMessage
  docs/api/incoming-message.md
  lib/browser/api/net.ts
  shell/browser/api/electron_api_url_loader.cc
  spec-main/api-net-spec.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#31739 feat: Added missing info to IAP transaction and product structures
  docs/api/structures/payment-discount.md
  docs/api/structures/product-discount.md
  docs/api/structures/product-subscription-period.md
  docs/api/structures/product.md
  docs/api/structures/transaction.md
  filenames.auto.gni
  shell/browser/api/electron_api_in_app_purchase.cc
  shell/browser/mac/in_app_purchase_observer.h
  shell/browser/mac/in_app_purchase_observer.mm
  shell/browser/mac/in_app_purchase_product.h
  shell/browser/mac/in_app_purchase_product.mm
Labels: semver/minor, api-review/requested 🗳, target/17-x-y

#32567 fix: undisable AXTextMarker and related APIs on MAS
  patches/chromium/mas_no_private_api.patch
Labels: backport, semver/patch, 17-x-y

#32353 chore: cherry-pick c5571653d932 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c5571653d932.patch
Labels: semver/patch, backport-check-skip, 15-x-y

#31222 feat: add WCO height option
  docs/api/browser-window.md
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/ui/cocoa/window_buttons_proxy.h
  shell/browser/ui/cocoa/window_buttons_proxy.mm
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_caption_button.h
  shell/browser/ui/views/win_caption_button_container.cc
  shell/browser/ui/views/win_caption_button_container.h
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec-main/api-browser-window-spec.ts
Labels: semver/minor, api-review/requested 🗳, target/13-x-y, target/14-x-y, target/15-x-y

#32597 fix: make windows without rounded corners closable
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y

#32604 fix: webContents.setZoomFactor crash
  shell/browser/web_view_guest_delegate.cc
Labels: semver/patch, new-pr 🌱, target/13-x-y, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32595 docs: correct requestSingleInstanceLock parameter
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/16-x-y, target/17-x-y

#32613 ci: update ts-compile-doc-change to properly use src cache
  .circleci/build_config.yml
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32607 docs: separate the dependency list for ubuntu
  docs/development/build-instructions-linux.md
Labels: semver/none, no-backport

#32474 fix: uploadData is in webRequest.onBeforeSendHeaders but not shown in api document
  docs/api/web-request.md
Labels: semver/none, no-backport

#29618 fix: Add support for Wayland window decorations
  filenames.gni
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_features.cc
  shell/browser/native_window_features.h
  shell/browser/native_window_views.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/client_frame_view_linux.h
  shell/browser/ui/views/frameless_view.cc
  shell/browser/ui/views/frameless_view.h
Labels: semver/patch, no-backport

#32628 fix: maxWidth not being respected
  shell/browser/native_window.cc
Labels: semver/patch, target/17-x-y

#32533 docs: update context bridge docs about Promises and Errors
  docs/api/context-bridge.md
Labels: documentation :notebook:, semver/none, target/15-x-y, target/16-x-y, target/17-x-y

#32354 chore: cherry-pick c5571653d932 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c5571653d932.patch
Labels: semver/patch, backport-check-skip, 14-x-y

#32593 fix: css transparent background being lost
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/apps/background-color-transparent/index.html
  spec-main/fixtures/apps/background-color-transparent/main.js
  spec-main/fixtures/apps/background-color-transparent/package.json
  spec-main/fixtures/apps/background-color-transparent/renderer.js
  spec-main/package.json
  spec-main/yarn.lock
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y

#32656 ci: revert update to Ubuntu 20.04 docker image
  .circleci/build_config.yml
Labels: fast-track 🚅, semver/none, no-backport

#32638 chore: cherry-pick f5101995acd2 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-f5101995acd2.patch
Labels: semver/patch, backport-check-skip, 17-x-y

#32641 docs: Remove the latin phrase "Nota Bene" from docs
  docs/api/dock.md
  docs/api/menu-item.md
  docs/development/build-instructions-gn.md
Labels: documentation :notebook:, semver/patch, no-backport

#32654 fix: undefined backgroundColor
  shell/browser/api/electron_api_browser_window.cc
Labels: backport, semver/patch, 16-x-y

#32666 fix: Missing comma in config.py
  script/lib/config.py
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y

#32663 docs: Update the build docs for electron to improve doc readability
  docs/development/build-instructions-gn.md
Labels: documentation :notebook:, semver/patch, target/16-x-y, target/17-x-y

#32596 chore: update to latest TypeScript
  default_app/main.ts
  lib/browser/api/auto-updater/squirrel-update-win.ts
  lib/browser/ipc-main-impl.ts
  package.json
  spec-main/api-context-bridge-spec.ts
  spec-main/api-ipc-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/node-spec.ts
  tsconfig.spec.json
  typings/internal-ambient.d.ts
  yarn.lock
Labels: semver/patch, no-backport

#32652 fix: ensure that chromium binds to wayland interface versions it supports
  patches/chromium/.patches
  patches/chromium/fix_wayland_bugs_related_to_bad_versioning.patch
Labels: backport, semver/patch, 13-x-y

#32653 fix: undefined backgroundColor
  shell/browser/api/electron_api_browser_window.cc
Labels: backport, semver/patch, 17-x-y

#32651 fix: expose all serial devices to setDevicePermissionHandler
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/serial/serial_chooser_context.h
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y

#32643 fix: transparent window max/unmax event firing
  shell/browser/native_window_views.cc
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y
