Repository electron/electron, pull requests merged in 2022-08, with the labels that each got.

#35123 fix: remove skip-taskbar feature on Linux.
  docs/api/browser-window.md
  shell/browser/native_window_views.cc
Labels: platform/linux, semver/patch, target/20-x-y

#35141 fix: clean up callback handling in `webContents.print()`
  patches/chromium/printing.patch
Labels: backport, semver/patch, 20-x-y

#35159 fix: ensure native modules use the correct config
  BUILD.gn
  patches/node/.patches
  patches/node/build_ensure_native_module_compilation_fails_if_not_using_a_new.patch
Labels: semver/patch, new-pr 🌱, blocks-release, target/20-x-y

#35161 build: use macos.x86.medium.gen2 for macos publish jobs
  .circleci/config/base.yml
Labels: fast-track 🚅, backport-check-skip, semver/none

#35111 fix: DCHECK entering fullscreen while loading url
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/19-x-y, target/20-x-y

#35142 ci: turn off windows on arm test result comments
  .github/workflows/electron_woa_testing.yml
Labels: semver/none, target/17-x-y, target/18-x-y, target/19-x-y, target/20-x-y

#34723 fix: modify file extension generation on Windows
  shell/browser/electron_download_manager_delegate.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35117 fix: touch events not recognized by WCO on windows
  patches/chromium/.patches
  patches/chromium/chore_allow_chromium_to_handle_synthetic_mouse_events_for_touch.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35176 fix: touch events not recognized by WCO on windows
  patches/chromium/.patches
  patches/chromium/chore_allow_chromium_to_handle_synthetic_mouse_events_for_touch.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: backport, semver/patch, 19-x-y

#35179 chore: remove unsupported skiptaskbar linux impl
  shell/browser/native_window_views.cc
Labels: new-pr 🌱, semver/none, target/20-x-y

#35177 fix: touch events not recognized by WCO on windows (#35117)
  patches/chromium/.patches
  patches/chromium/chore_allow_chromium_to_handle_synthetic_mouse_events_for_touch.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: backport, semver/patch, 18-x-y

#35138 fix: fail non-fatally when InitLogging fails
  shell/common/logging.cc
Labels: semver/patch, target/20-x-y

#35124 chore: update NMV for Electron 21
  build/args/all.gn
Labels: new-pr 🌱, semver/none, no-backport

#35178 chore: fix linking with component ffmpeg
  BUILD.gn
  build/config/BUILD.gn
  patches/chromium/.patches
  patches/chromium/v8_context_snapshot_generator.patch
  patches/config.json
  patches/ffmpeg/.patches
  patches/ffmpeg/link_with_loader_path.patch
  patches/v8/build_gn.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
  patches/v8/expose_mksnapshot.patch
Labels: new-pr 🌱, semver/none, no-backport

#34955 fix: Wayland general CSD fixes
  patches/chromium/.patches
  patches/chromium/add_maximized_parameter_to_linuxui_getwindowframeprovider.patch
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/client_frame_view_linux.h
Labels: semver/patch, target/19-x-y, target/20-x-y

#35194 fix: consider dock space when showing menu
  shell/browser/api/electron_api_menu_mac.mm
Labels: semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y, target/20-x-y

#35185 chore: cherry-pick 6265ef99615 from chromium
  patches/chromium/.patches
  patches/chromium/disable_gpu_acceleration_on_vmware_on_linux.patch
Labels: semver/patch, backport-check-skip, 19-x-y

#35196 docs: update categories to match sidebar
  docs/tutorial/introduction.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/19-x-y, target/20-x-y

#35192 docs: fix link in tutorial
  docs/tutorial/tutorial-4-adding-features.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/20-x-y

#35175 docs: Fix the URL bugs at tutorial-6-publishing-updating.md
  docs/tutorial/tutorial-6-publishing-updating.md
Labels: documentation :notebook:, semver/patch

#35184 chore: cherry-pick 97193a64b431 from chromium
  patches/chromium/.patches
  patches/chromium/do_not_reduce_page_size_from_64k_to_4k_on_linux_arm64.patch
Labels: semver/patch, backport-check-skip, 18-x-y

#34990 build: upgrade webpack and related deps
  build/webpack/webpack.config.base.js
  build/webpack/webpack.gni
  package.json
  script/gen-filenames.ts
  yarn.lock
Labels: semver/none, no-backport

#35076 test: migrate webview attribute specs to spec-main
  spec-main/webview-spec.ts
  spec/webview-spec.js
Labels: semver/none, no-backport

#35077 test: migrate <webview> tag event specs to main runner
  spec-main/webview-spec.ts
  spec/static/main.js
  spec/webview-spec.js
Labels: backport-check-skip, semver/none, no-backport

#34959 feat: add WebContents.ipc
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  lib/browser/api/ipc-main.ts
  lib/browser/api/web-contents.ts
  lib/browser/api/web-frame-main.ts
  lib/browser/ipc-main-impl.ts
  lib/browser/ipc-main-internal.ts
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  spec-main/api-ipc-spec.ts
  spec-main/fixtures/preload-expose-ipc.js
  typings/internal-ambient.d.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#35136 docs: update tray docs with info for mac menubar icons
  docs/api/tray.md
Labels: documentation :notebook:, semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35206 fix: Wayland general CSD fixes
  patches/chromium/.patches
  patches/chromium/add_maximized_parameter_to_linuxui_getwindowframeprovider.patch
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/client_frame_view_linux.h
Labels: backport, semver/patch, 20-x-y

#35207 fix: Wayland general CSD fixes
  patches/chromium/.patches
  patches/chromium/add_maximized_parameter_to_linuxui_getwindowframeprovider.patch
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/client_frame_view_linux.h
Labels: backport, semver/patch, 19-x-y

#35228 docs: remove reference to electron/i18n in README
  README.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, no-backport

#35212 test: migrate node specs to main
  spec-main/node-spec.ts
  spec-main/spec-helpers.ts
  spec-main/webview-spec.ts
  spec/node-spec.js
  spec/static/main.js
Labels: semver/none, no-backport

#35227 build: fix webpack prod failure
  package.json
  yarn.lock
Labels: fast-track 🚅, semver/none, no-backport

#35226 test: temporarily disable tests on mas arm64 that are causing a crash
  spec-main/api-browser-window-spec.ts
Labels: semver/none, target/20-x-y, target/21-x-y

#35237 chore: cherry-pick 94a8bdafc8c6 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-94a8bdafc8c6.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35217 refactor: use optional chaining / nullish coalescing operator
  lib/asar/fs-wrapper.ts
  lib/browser/api/auto-updater/squirrel-update-win.ts
  lib/browser/api/desktop-capturer.ts
  lib/browser/api/touch-bar.ts
  lib/browser/guest-view-manager.ts
Labels: semver/patch, no-backport

#35108 fix: app.relaunch loses args when execPath specified
  shell/browser/api/electron_api_app.cc
  spec-main/api-app-spec.ts
  spec/fixtures/api/relaunch/main.js
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35238 chore: cherry-pick 06aea31d10f8 from webrtc
  patches/webrtc/.patches
  patches/webrtc/cherry-pick-06aea31d10f8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35260 build: fix building with enable_plugins = false
  patches/chromium/.patches
  patches/chromium/fix_mac_build_with_enable_plugins_false.patch
  patches/chromium/fix_windows_build_with_enable_plugins_false.patch
Labels: semver/patch, backport-check-skip, 19-x-y

#35261 build: fix building with enable_plugins = false
  patches/chromium/.patches
  patches/chromium/fix_mac_build_with_enable_plugins_false.patch
  patches/chromium/fix_windows_build_with_enable_plugins_false.patch
Labels: semver/patch, backport-check-skip, 18-x-y

#35259 build: fix building with enable_plugins = false
  patches/chromium/.patches
  patches/chromium/fix_mac_build_with_enable_plugins_false.patch
  patches/chromium/fix_windows_build_with_enable_plugins_false.patch
Labels: semver/patch, backport-check-skip, 20-x-y

#35258 build: fix error in the `ts-compile-doc-change` step
  .circleci/config/base.yml
Labels: fast-track 🚅, semver/none, no-backport

#35239 chore: cherry-pick 06aea31d10f8 from webrtc
  patches/webrtc/.patches
  patches/webrtc/cherry-pick-06aea31d10f8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35236 chore: cherry-pick 94a8bdafc8c6 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-94a8bdafc8c6.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35230 test: migrate asar specs to main runner
  spec-main/asar-spec.ts
  spec-main/spec-helpers.ts
  spec/asar-spec.js
Labels: backport-check-skip, semver/none, no-backport

#35274 chore: cherry-pick 54e32332750c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-54e32332750c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35271 chore: cherry-pick c643d18a078d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c643d18a078d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35275 chore: cherry-pick bd9724c9fe63 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-bd9724c9fe63.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35270 chore: cherry-pick 60d8559e150a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-60d8559e150a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35256 fix(docs): fix a typo in section on debugging with VSCode
  docs/tutorial/tutorial-2-first-app.md
Labels: documentation :notebook:, semver/none, target/19-x-y, target/20-x-y, target/21-x-y

#34526 chore: remove deprecated 'new-window' event
  docs/api/structures/new-window-web-contents-event.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  docs/breaking-changes.md
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  lib/browser/guest-view-manager.ts
  lib/browser/guest-window-manager.ts
  spec-main/api-browser-window-spec.ts
  spec-main/api-web-contents-spec.ts
  spec-main/fixtures/snapshots/native-window-open.snapshot.txt
  spec-main/guest-window-manager-spec.ts
  spec-main/webview-spec.ts
  spec/ts-smoke/electron/renderer.ts
Labels: semver/major, api-review/requested 🗳, no-backport

#35288 docs: fix getStoragePath return type
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/19-x-y, target/20-x-y, target/21-x-y

#35209 fix: WCO occlusion of DevTools
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35301 build: bump @electron/get to 2.0.0, node to >= 12+
  npm/package.json
Labels: semver/none, no-backport

#35303 refactor: simplify `Browser::SetLoginItemSettings`
  shell/browser/browser_mac.mm
Labels: semver/patch, target/20-x-y, target/21-x-y

#35267 chore: cherry-pick 54a7927b19f9 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-54a7927b19f9.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35268 chore: cherry-pick 54a7927b19f9 from chromium
  patches/chromium/.patches
  patches/chromium/merge_104_speculative_fix_for_isvalidcodepointinindex_range_crash.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35283 docs: add Electron deps to license credits file
  patches/chromium/.patches
  patches/chromium/add_electron_deps_to_license_credits_file.patch
Labels: documentation :notebook:, semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35324 docs: removes unused import in preload script
  docs/fiddles/features/drag-and-drop/preload.js
  docs/tutorial/native-file-drag-drop.md
Labels: documentation :notebook:, semver/none, target/20-x-y, target/21-x-y

#35272 chore: cherry-pick c643d18a078d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c643d18a078d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35213 test: migrate remaining webview specs to main
  spec-main/webview-spec.ts
  spec/webview-spec.js
Labels: semver/none, no-backport

#35311 refactor: don't expose deprecate as an internal module
  filenames.auto.gni
  lib/browser/api/app.ts
  lib/browser/api/crash-reporter.ts
  lib/browser/api/web-contents.ts
  lib/common/api/deprecate.ts
  lib/common/api/module-list.ts
  lib/common/define-properties.ts
  lib/common/deprecate.ts
  lib/sandboxed_renderer/api/module-list.ts
  spec-main/deprecate-spec.ts
  typings/internal-electron.d.ts
Labels: semver/patch, no-backport

#35322 fix: add uv_loop_close when object release to fix crash
  shell/common/node_bindings.cc
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35317 fix: prevent brief display of "Ozone X11" in window title on Linux
  patches/chromium/.patches
  patches/chromium/remove_default_window_title.patch
Labels: backport, semver/patch, backport-check-skip, 20-x-y

#35314 fix: WCO restore button is off-center
  filenames.gni
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_caption_button.h
  shell/browser/ui/views/win_icon_painter.cc
  shell/browser/ui/views/win_icon_painter.h
Labels: backport, semver/patch, 19-x-y

#35306 fix: `serialPort.open()` failing
  shell/browser/serial/electron_serial_delegate.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/serial/serial_chooser_context.h
Labels: semver/patch, target/20-x-y, target/21-x-y

#35320 fix: IPC emit order in -ipc-ports handler
  lib/browser/api/web-contents.ts
Labels: semver/patch, no-backport

#35269 chore: cherry-pick 60d8559e150a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-60d8559e150a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35276 chore: cherry-pick bd9724c9fe63 from chromium
  patches/chromium/.patches
  patches/chromium/m104_background_fetch_passing.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35273 chore: cherry-pick 54e32332750c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-54e32332750c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35189 fix: Frameless window shows frame while opening
  patches/chromium/.patches
  patches/chromium/feat_add_set_can_resize_mutator.patch
  shell/browser/native_window_views.cc
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35348 fix: Make the disable_color_correct_rendering flag work with textured images
  patches/chromium/disable_color_correct_rendering.patch
Labels: semver/patch, backport-check-skip, 19-x-y

#34841 build: allow Linux distros to build against system shared libraries
  patches/node/build_add_gn_build_files.patch
Labels: semver/none, no-backport

#35292 fix: promise support with webFrameMain.executeJavaScript
  shell/browser/api/electron_api_web_frame_main.cc
  spec/api-web-frame-main-spec.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/20-x-y, target/21-x-y

#35345 docs: add dependencies and troubleshooting section to build-instructions
  docs/development/build-instructions-gn.md
  docs/development/build-instructions-macos.md
Labels: documentation :notebook:, semver/patch, no-backport

#35357 fix: don't bypass redirect checks
  shell/browser/electron_browser_client.cc
Labels: semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y, target/20-x-y, target/21-x-y

#35377 ci: use AppVeyor workflows
  appveyor.yml
Labels: semver/none, target/19-x-y, target/20-x-y, target/21-x-y

#35376 chore: update process singleton patch
  patches/chromium/feat_add_data_parameter_to_processsingleton.patch
  patches/chromium/process_singleton.patch
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
Labels: semver/none, no-backport

#35034 fix: ensure chrome colors are initialized
  chromium_src/BUILD.gn
  shell/browser/electron_browser_main_parts.cc
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35397 build: update libcxx filenames
  .circleci/config/base.yml
  filenames.libcxx.gni
Labels: fast-track 🚅, semver/none, no-backport

#30702 feat: session.setDisplayMediaRequestHandler
  docs/api/session.md
  filenames.gni
  package.json
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/web_contents_permission_helper.cc
  shell/common/gin_converters/frame_converter.cc
  shell/common/gin_converters/frame_converter.h
  shell/common/gin_converters/media_converter.cc
  shell/common/gin_converters/media_converter.h
  spec-main/api-media-handler-spec.ts
  yarn.lock
Labels: semver/minor, api-review/approved ✅, no-backport

#35281 fix: undefined details.requestingUrl from session.setPermissionCheckHandler
  shell/browser/electron_permission_manager.cc
  spec/api-session-spec.ts
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35370 chore: apply chromium commit 30a32e6
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_icon_painter.cc
Labels: semver/none, no-backport

#35342 fix: add restore event for minimized maximization
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35426 chore: cherry-pick 96306321286a from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-96306321286a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35432 build: fix export patches to work when source directory does not exist
  script/lib/git.py
Labels: fast-track 🚅, semver/none, target/21-x-y

#35431 ci: fixup doc-only-change on Windows
  appveyor.yml
Labels: semver/none, target/18-x-y, target/19-x-y, target/20-x-y, target/21-x-y

#35406 ci: fix appveyor x64 tests
  appveyor.yml
Labels: semver/none, no-backport

#35425 chore: cherry-pick 1121a459f094 from angle
  patches/angle/.patches
  patches/angle/m104_vulkan_fix_xfb_buffer_redefine_to_smaller_size.patch
  patches/config.json
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35424 chore: cherry-pick 1121a459f094 from angle
  patches/angle/.patches
  patches/angle/m104_vulkan_fix_xfb_buffer_redefine_to_smaller_size.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35415 fix: Node.js `atob` input validation
  patches/node/.patches
  patches/node/buffer_fix_atob_input_validation.patch
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35405 chore: remove unused `GuestViewContainer`
  filenames.gni
  shell/renderer/guest_view_container.cc
  shell/renderer/guest_view_container.h
Labels: semver/none, no-backport

#35421 fix: fullscreen crashing with `roundedCorners: false`
  docs/api/browser-window.md
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35427 chore: cherry-pick 4a65a669e11b from angle
  patches/angle/.patches
  patches/angle/m104_vulkan_fix_garbage_collection_vs_outside-rp-only_flush.patch
  patches/angle/m104_vulkan_fix_xfb_buffer_redefine_to_smaller_size.patch
Labels: security 🔒, semver/patch, wip ⚒, backport-check-skip, 19-x-y

#35439 test: fix some broken globs for spec-main
  .circleci/config/base.yml
  .gitignore
Labels: semver/none, no-backport

#35451 build: fix missing patch config dir error
  script/export_all_patches.py
Labels: semver/none, target/20-x-y, target/21-x-y

#35434 chore: cherry-pick 2f19801aeb77 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-2f19801aeb77.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35419 fix: pass rfh instances through to the permission helper
  docs/api/session.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_client.cc
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y, target/21-x-y

#35452 chore: delete implicit fallthrough patch
  patches/node/.patches
  patches/node/chore_fix_-wimplicit-fallthrough.patch
Labels: semver/patch, target/20-x-y, target/21-x-y

#35144 docs: update docs description to match sidebar
  docs/tutorial/introduction.md
Labels: documentation :notebook:, semver/none, target/20-x-y, target/21-x-y

#35449 chore: use nghttp2's config.h on all platforms
  patches/node/build_add_gn_build_files.patch
Labels: semver/patch, target/20-x-y, target/21-x-y

#35466 fix: crash when switching origins with emulation settings set
  patches/chromium/.patches
  patches/chromium/fix_revert_emulationhandler_update_functions_to_early_return.patch
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/21-x-y

#35422 fix: crash on WebWorker destruction
  patches/node/feat_add_uv_loop_interrupt_on_io_change_option_to_uv_loop_configure.patch
  shell/common/node_bindings.cc
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#34713 fix: compensate for title bar height when setting bounds on `BrowserView`
  shell/browser/native_browser_view_mac.mm
  spec/api-browser-view-spec.ts
Labels: semver/patch, target/18-x-y, target/19-x-y, target/20-x-y

#35485 fix: crash loading non-standard schemes in iframes
  patches/chromium/.patches
  patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
  spec/api-protocol-spec.ts
  spec/fixtures/pages/iframe-protocol.html
Labels: semver/patch, target/19-x-y, target/20-x-y, target/21-x-y

#35510 refactor: simplify WebContents::Destroy
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, new-pr 🌱, no-backport

#35498 chore: drop unresponsive suppressor for menus
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/api/electron_api_menu_views.cc
Labels: semver/patch, no-backport
