Repository electron/electron, pull requests merged in 2022-10, with the labels that each got.

#35850 fix: `TryCatch` scope in node_bindings
  shell/common/node_bindings.cc
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#35845 build: move from stale GH app to stale action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: semver/none, no-backport

#35864 fix: ensure mas builds of the same application can use safestorage
  patches/chromium/.patches
  patches/chromium/feat_ensure_mas_builds_of_the_same_application_can_use_safestorage.patch
Labels: semver/patch, no-backport

#35892 chore: cherry-pick 2f6a2939514f from v8
  patches/v8/.patches
  patches/v8/cherry-pick-2f6a2939514f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#35890 chore: cherry-pick 2f6a2939514f from v8
  patches/v8/.patches
  patches/v8/cherry-pick-2f6a2939514f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35885 chore: cherry-pick 9bebe8549a36 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9bebe8549a36.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35880 chore: cherry-pick 1eb1e18ad41d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1eb1e18ad41d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#35888 chore: cherry-pick 8b040cb69e96 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-8b040cb69e96.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35889 chore: cherry-pick 8b040cb69e96 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-8b040cb69e96.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#35884 chore: cherry-pick 9bebe8549a36 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9bebe8549a36.patch
Labels: security 🔒, semver/patch, backport-check-skip, 18-x-y

#35891 chore: cherry-pick 2f6a2939514f from v8
  patches/v8/.patches
  patches/v8/cherry-pick-2f6a2939514f.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35904 chore: update libcxx filenames
  filenames.libcxx.gni
  patches/chromium/feat_ensure_mas_builds_of_the_same_application_can_use_safestorage.patch
Labels: fast-track 🚅, semver/none, no-backport

#35894 docs: update bluetooth fiddle example event name to trigger correct event
  docs/fiddles/features/web-bluetooth/preload.js
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/21-x-y, target/22-x-y

#35911 docs: update supported Mac versions
  README.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/20-x-y, target/21-x-y, target/22-x-y

#35879 chore: cherry-pick 1eb1e18ad41d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1eb1e18ad41d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35917 build: clean up patch linting errors
  script/lint.js
Labels: semver/none, no-backport

#35710 refactor: eliminate `DecrementCapturerCount` patch
  docs/api/browser-window.md
  docs/api/web-contents.md
  docs/breaking-changes.md
  shell/browser/api/electron_api_web_contents.cc
  spec/api-browser-window-spec.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#35926 chore: cherry-pick c83640db21b5 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c83640db21b5.patch
Labels: semver/patch, backport-check-skip, 20-x-y

#35925 chore: cherry-pick c83640db21b5 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-c83640db21b5.patch
Labels: semver/patch, backport-check-skip, 21-x-y

#35940 docs: remove pywin32 mention in Windows build instructions
  docs/development/build-instructions-windows.md
Labels: documentation :notebook:, semver/patch, no-backport

#35930 fix: expose the built-in electron module via the ESM loader
  patches/node/.patches
  patches/node/fix_expose_the_built-in_electron_module_via_the_esm_loader.patch
  spec/modules-spec.ts
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#35932 fix: override `content::ContentMainDelegate::CreateContentClient()`
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_delegate.h
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#35929 chore: cherry-pick 05a0d99c9715 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-05a0d99c9715.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#35968 chore: cherry-pick 30a32e6 from chromium (#35370)
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_icon_painter.cc
Labels: backport, semver/none, 20-x-y

#35931 test: add tests for valid electron module names
  lib/common/reset-search-paths.ts
  spec/modules-spec.ts
Labels: semver/none, no-backport

#35963 fix: drag and drop should copy on macOS
  shell/browser/ui/drag_util_mac.mm
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#33215 test: remove redundant color diffing dependency
  spec/api-browser-window-spec.ts
  spec/fixtures/apps/background-color-transparent/index.html
  spec/fixtures/apps/background-color-transparent/main.js
  spec/fixtures/apps/background-color-transparent/package.json
  spec/fixtures/apps/background-color-transparent/renderer.js
  spec/fixtures/pages/css-transparent.html
  spec/package.json
  spec/screen-helpers.ts
  spec/yarn.lock
Labels: semver/none, no-backport

#35921 fix: on-screen-keyboard hides on input blurred in webview
  patches/chromium/.patches
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
Labels: component/webview, semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#35970 chore: cherry-pick 30a32e6 from chromium (#35370)
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_icon_painter.cc
Labels: backport, semver/patch, 21-x-y

#35985 fix: pass rfh instances through to the permission helper
  docs/api/session.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_client.cc
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
Labels: backport, semver/patch, 20-x-y

#35986 fix: pass rfh instances through to the permission helper
  docs/api/session.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_client.cc
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
Labels: backport, semver/patch, 19-x-y

#35980 docs: remove references to Widevine
  docs/README.md
  docs/tutorial/testing-widevine-cdm.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/20-x-y, target/21-x-y, target/22-x-y

#35975 fix: `webContents.printToPDF` option plumbing
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, new-pr 🌱, target/21-x-y, target/22-x-y

#35882 chore: cherry-pick fefd6198da31 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-fefd6198da31.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35966 chore: remove WebKit leftovers after it was renamed to Blink
  .circleci/config/base.yml
  appveyor.yml
  docs/development/build-instructions-gn.md
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/api/electron_api_spell_check_client.h
  spec/node-spec.ts
Labels: semver/none, no-backport

#35883 chore: cherry-pick fefd6198da31 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-fefd6198da31.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#35988 build: fix building with enable_ppapi = false
  BUILD.gn
  chromium_src/BUILD.gn
Labels: semver/none, target/20-x-y, target/21-x-y, target/22-x-y

#35918 chore: cherry-pick 05a0d99c9715 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-05a0d99c9715.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#35824 docs: use webContents.mainFrame.on() in MessagePort tutorial
  docs/tutorial/message-ports.md
Labels: documentation :notebook:, semver/patch, no-backport

#35919 fix: disable `nodeIntegrationInWorker` for certain Worker types
  docs/tutorial/multithreading.md
  shell/renderer/electron_renderer_client.cc
  spec/chromium-spec.ts
  spec/fixtures/pages/service-worker/empty.html
  spec/fixtures/pages/service-worker/worker-no-node.js
  spec/fixtures/pages/shared_worker.html
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/21-x-y, target/22-x-y

#36015 test: re-enable power monitor tests on arm64
  spec/api-power-monitor-spec.ts
Labels: semver/none, target/20-x-y, target/21-x-y, target/22-x-y

#35365 fix: Windows 7 frame showing for frameless non-resizable windows
  patches/chromium/.patches
  patches/chromium/feat_add_set_can_resize_mutator.patch
  patches/chromium/fix_remove_caption-removing_style_call.patch
  shell/browser/native_window_views.cc
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#36016 docs: fix erroneous removal warning for decrementCapturerCount
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#36028 ci: use AppVeyor workflows
  appveyor.yml
Labels: backport, semver/none, 21-x-y

#36013 chore: remove useless Node.js V8 patch
  patches/node/.patches
  patches/node/build_ensure_native_module_compilation_fails_if_not_using_a_new.patch
  patches/node/build_ensure_v8_pointer_compression_sandbox_is_enabled_on_64bit.patch
  patches/node/fix_add_v8_enable_reverse_jsargs_defines_in_common_gypi.patch
Labels: semver/none, target/21-x-y, target/22-x-y

#36026 test: re-enable <webview> tag DOM events emits resize event
  spec/webview-spec.ts
Labels: semver/none, target/20-x-y, target/21-x-y, target/22-x-y

#35997 fix: override app's desktop name and v8 flags in default-app
  default_app/main.ts
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#36042 docs: update VS Code debugger types to remove "pwa-" prefix
  docs/tutorial/tutorial-2-first-app.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/20-x-y, target/21-x-y, target/22-x-y

#35007 chore: Move draggable regions implementation from NativeBrowserView into InspectableWebContentsView
  filenames.gni
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/native_browser_view.h
  shell/browser/native_browser_view_mac.h
  shell/browser/native_browser_view_mac.mm
  shell/browser/native_browser_view_views.cc
  shell/browser/native_browser_view_views.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/ui/inspectable_web_contents_view.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view_mac.h
  shell/browser/ui/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/frameless_view.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: semver/none, no-backport

#36046 fix: headless job tracking in printToPDF
  shell/browser/printing/print_view_manager_electron.cc
Labels: semver/patch, target/21-x-y, target/22-x-y

#36060 fix: printToPDF default margins
  lib/browser/api/web-contents.ts
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#36070 refactor: migrate from asar to @electron/asar
  package.json
  script/gn-asar-hash.js
  script/gn-asar.js
  spec/fixtures/test.asar/repack.js
  yarn.lock
Labels: new-pr 🌱, semver/none, target/19-x-y, target/20-x-y, target/21-x-y

#34980 feat: UtilityProcess API
  BUILD.gn
  build/webpack/webpack.config.utility.js
  docs/api/parent-port.md
  docs/api/process.md
  docs/api/utility-process.md
  docs/glossary.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/module-list.ts
  lib/browser/api/utility-process.ts
  lib/common/init.ts
  lib/utility/.eslintrc.json
  lib/utility/api/exports/electron.ts
  lib/utility/api/module-list.ts
  lib/utility/init.ts
  lib/utility/parent-port.ts
  patches/chromium/.patches
  patches/chromium/allow_new_privileges_in_unsandboxed_child_processes.patch
  patches/chromium/feat_configure_launch_options_for_service_process.patch
  script/gen-filenames.ts
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/event_emitter_mixin.h
  shell/browser/javascript_environment.cc
  shell/browser/javascript_environment.h
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/parent_port.cc
  shell/services/node/parent_port.h
  shell/services/node/public/mojom/BUILD.gn
  shell/services/node/public/mojom/node_service.mojom
  shell/utility/electron_content_utility_client.cc
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/crash.js
  spec/fixtures/api/utility-process/custom-exit.js
  spec/fixtures/api/utility-process/empty.js
  spec/fixtures/api/utility-process/endless.js
  spec/fixtures/api/utility-process/env-app/main.js
  spec/fixtures/api/utility-process/env-app/package.json
  spec/fixtures/api/utility-process/env-app/test.js
  spec/fixtures/api/utility-process/exception.js
  spec/fixtures/api/utility-process/inherit-stderr/main.js
  spec/fixtures/api/utility-process/inherit-stderr/package.json
  spec/fixtures/api/utility-process/inherit-stderr/test.js
  spec/fixtures/api/utility-process/inherit-stdout/main.js
  spec/fixtures/api/utility-process/inherit-stdout/package.json
  spec/fixtures/api/utility-process/inherit-stdout/test.js
  spec/fixtures/api/utility-process/log.js
  spec/fixtures/api/utility-process/post-message-queue.js
  spec/fixtures/api/utility-process/post-message.js
  spec/fixtures/api/utility-process/preload.js
  spec/fixtures/api/utility-process/receive-message.js
  spec/fixtures/api/utility-process/suid.js
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/requested 🗳, target/21-x-y, target/22-x-y

#36077 chore: cherry-pick cb9dff93f3d4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-cb9dff93f3d4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#36051 refactor: enable OOPIF printing to PDF
  chromium_src/BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/printing/print_view_manager_electron.cc
  shell/browser/printing/print_view_manager_electron.h
Labels: semver/patch, target/21-x-y, target/22-x-y

#36086 chore: cherry-pick d7feae867b83 from sqlite
  patches/sqlite/.patches
  patches/sqlite/utf-8_q_m102-lts_20enhance_20defensive_20mode_20so_20that_20i.patch
Labels: security 🔒, semver/patch, backport-check-skip, 19-x-y

#36091 test: exit properly when `node-spec-runner` validates specs
  script/node-spec-runner.js
Labels: semver/none, target/21-x-y, target/22-x-y

#36087 refactor: migrate from asar to @electron/asar (#36070)
  package.json
  script/gn-asar-hash.js
  script/gn-asar.js
  spec/fixtures/test.asar/repack.js
  yarn.lock
Labels: backport, semver/none, 21-x-y

#36112 docs: fixed MenuItem documentation to use the same formatting for all role options
  docs/api/menu-item.md
Labels: documentation :notebook:, semver/patch, target/21-x-y, target/22-x-y

#36085 chore: cherry-pick d7feae867b83 from sqlite
  patches/sqlite/.patches
  patches/sqlite/utf-8_q_m102-lts_20enhance_20defensive_20mode_20so_20that_20i.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#36082 refactor: migrate from asar to @electron/asar (#36070)
  package.json
  script/gn-asar-hash.js
  script/gn-asar.js
  spec/fixtures/test.asar/repack.js
  yarn.lock
Labels: backport, semver/none, 19-x-y

#36083 refactor: migrate from asar to @electron/asar (#36070)
  package.json
  script/gn-asar-hash.js
  script/gn-asar.js
  spec/fixtures/test.asar/repack.js
  yarn.lock
Labels: backport, semver/none, 20-x-y

#36106 build: determine electron version from tags not files
  .circleci/config/base.yml
  BUILD.gn
  ELECTRON_VERSION
  build/templates/electron_rc.tmpl
  build/templates/version_string.tmpl
  package.json
  patches/chromium/.patches
  patches/chromium/build_allow_electron_to_use_exec_script.patch
  script/generate-version-json.js
  script/lib/get-version.js
  script/lib/util.py
  script/print-version.py
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/version-bumper.js
  script/release/version-utils.js
  spec/version-bump-spec.ts
Labels: semver/none, target/19-x-y, target/20-x-y, target/21-x-y, target/22-x-y

#36128 build: ensure get-version runs in the electron git checkout
  script/lib/get-version.js
Labels: fast-track 🚅, semver/none, no-backport

#36131 build: use python3 for appveyor commands
  appveyor.yml
Labels: semver/none, target/19-x-y, target/20-x-y, target/21-x-y, target/22-x-y

#36127 docs: document that when `invoke` rejects, it gives a different Error
  docs/api/ipc-renderer.md
Labels: documentation :notebook:, semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#36129 fix: resolve loadURL properly for in-page navigations
  lib/browser/api/web-contents.ts
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#36080 chore: cherry-pick 07a2ce61e31a from skia
  patches/config.json
  patches/skia/.patches
  patches/skia/cherry-pick-07a2ce61e31a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#36079 chore: cherry-pick 65f0ef609c00 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-65f0ef609c00.patch
Labels: security 🔒, semver/patch, backport-check-skip, 20-x-y

#35484 refactor: handle uncaught promise error
  lib/renderer/web-view/web-view-attributes.ts
Labels: semver/patch, target/20-x-y, target/21-x-y, target/22-x-y

#36113 docs: correcting main example in WebRequest documentation
  docs/api/web-request.md
Labels: documentation :notebook:, semver/patch, target/21-x-y, target/22-x-y

#36074 docs: add utility process info to tutorial docs
  docs/tutorial/process-model.md
Labels: documentation :notebook:, semver/none, no-backport

#36168 test: fixup HID test for ARM CI
  spec/chromium-spec.ts
Labels: fast-track 🚅, backport-check-skip, semver/none, target/19-x-y, target/20-x-y, target/21-x-y

#36169 build: prefix version in uploader script
  script/release/uploaders/upload.py
Labels: fast-track 🚅, semver/none, target/19-x-y, target/20-x-y, target/21-x-y, target/22-x-y

#36154 fix: remove undocumented feature and flaky test for webview resize event
  lib/renderer/web-view/web-view-impl.ts
  spec/webview-spec.ts
Labels: semver/patch, no-backport

#36188 build: use npm@7 for npm view command
  script/release/publish-to-npm.js
Labels: backport-check-skip, semver/none, 22-x-y

#36187 docs: add EOL dates to timeline doc
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/21-x-y, target/22-x-y

#36135 build: determine electron version from tags not files
  .circleci/config/base.yml
  BUILD.gn
  ELECTRON_VERSION
  build/templates/electron_rc.tmpl
  build/templates/version_string.tmpl
  package.json
  patches/chromium/.patches
  patches/chromium/build_allow_electron_to_use_exec_script.patch
  script/generate-version-json.js
  script/lib/get-version.js
  script/lib/util.py
  script/print-version.py
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/version-bumper.js
  script/release/version-utils.js
  spec-main/version-bump-spec.ts
Labels: backport, semver/none, 21-x-y

#36136 build: determine electron version from tags not files
  .circleci/config/base.yml
  BUILD.gn
  ELECTRON_VERSION
  build/templates/electron_rc.tmpl
  build/templates/version_string.tmpl
  package.json
  patches/chromium/.patches
  patches/chromium/build_allow_electron_to_use_exec_script.patch
  script/generate-version-json.js
  script/lib/get-version.js
  script/lib/util.py
  script/print-version.py
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/version-bumper.js
  script/release/version-utils.js
  spec-main/version-bump-spec.ts
Labels: backport, semver/none, 20-x-y

#36137 build: determine electron version from tags not files
  .circleci/config/base.yml
  BUILD.gn
  ELECTRON_VERSION
  build/templates/electron_rc.tmpl
  build/templates/version_string.tmpl
  package.json
  patches/chromium/.patches
  patches/chromium/build_allow_electron_to_use_exec_script.patch
  script/generate-version-json.js
  script/lib/get-version.js
  script/lib/util.py
  script/print-version.py
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/version-bumper.js
  script/release/version-utils.js
  spec-main/version-bump-spec.ts
Labels: backport, semver/none, 19-x-y

#36193 build: fix building with enable_plugins = false
  BUILD.gn
  filenames.gni
Labels: semver/none, target/21-x-y, target/22-x-y
