Repository electron/electron, pull requests merged in 2022-03, with the labels that each got.

#32984 chore: cherry-pick be50c60b4225 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-be50c60b4225.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#31017 test: BrowserWindow backgroundColor and transparency
  spec-main/api-browser-window-spec.ts
  spec-main/fixtures/pages/half-background-color.html
  spec-main/screen-helpers.ts
Labels: semver/none, no-backport

#33114 fix: disable partition alloc on mac
  patches/chromium/.patches
  patches/chromium/build_disable_partition_alloc_on_mac.patch
Labels: semver/patch, new-pr 🌱, target/17-x-y, target/18-x-y

#33025 fix: max window size defaults to 0
  shell/browser/native_window.cc
Labels: semver/patch, target/17-x-y, target/18-x-y

#33115 ci: disable use-thin-lto on Mac only
  build/args/all.gn
  patches/chromium/.patches
  patches/chromium/build_disable_thin_lto_on_mac.patch
Labels: semver/none, no-backport

#32937 docs: remove platform notices from tutorial titles
  docs/tutorial/in-app-purchases.md
  docs/tutorial/launch-app-from-url-in-another-app.md
  docs/tutorial/linux-desktop-actions.md
  docs/tutorial/macos-dock.md
  docs/tutorial/progress-bar.md
  docs/tutorial/recent-documents.md
  docs/tutorial/represented-file.md
  docs/tutorial/windows-taskbar.md
Labels: documentation :notebook:, semver/none, target/17-x-y, target/18-x-y

#32991 docs: Updated list numbering
  docs/tutorial/quick-start.md
Labels: semver/none, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33141 ci: use larger machine for docs only check
  .circleci/build_config.yml
Labels: semver/none

#33145 chore: fixup 18-x-y release
  patches/chromium/.patches
  patches/chromium/build_disable_thin_lto_on_mac.patch
  shell/app/electron_main_delegate.cc
Labels: backport, fast-track 🚅, semver/none, 18-x-y

#33144 test: disable consistently flaky WOA JS test
  spec-main/chromium-spec.ts
Labels: backport-check-skip, semver/none

#33143 test: disable newly added tests on WOA
  spec-main/api-browser-window-spec.ts
Labels: fast-track 🚅, semver/none, no-backport

#33169 chore: cherry-pick 6b2643846ae3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6b2643846ae3.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33082 docs: fix missing dependencies in ipc patterns
  docs/fiddles/ipc/pattern-2/main.js
  docs/fiddles/ipc/pattern-3/main.js
Labels: documentation :notebook:, semver/patch, no-backport

#33042 docs: Fixed a typo
  docs/api/browser-window.md
Labels: documentation :notebook:, semver/patch, no-backport, documentation 📓

#33183 build: put v8_context_snapshot_generator.dSYM in its own zip file
  script/release/release.js
  script/release/uploaders/upload.py
  script/zip-symbols.py
Labels: fast-track 🚅, semver/none, target/18-x-y

#33167 chore: cherry-pick 6b2643846ae3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6b2643846ae3.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33168 chore: cherry-pick 6b2643846ae3 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-6b2643846ae3.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33062 fix: gracefully fail if app.configureHostResolver is called before ready
  shell/browser/api/electron_api_app.cc
Labels: semver/patch, no-backport

#33171 chore: add ignore revs file for GH blame UI
  .git-blame-ignore-revs
Labels: new-pr 🌱, semver/none, no-backport

#33181 chore: cherry-pick 49e8ff16f1fe from angle
  patches/angle/.patches
  patches/angle/cherry-pick-49e8ff16f1fe.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33180 chore: cherry-pick 49e8ff16f1fe from angle
  patches/angle/.patches
  patches/angle/cherry-pick-49e8ff16f1fe.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33184 chore: cherry-pick 62142d222a80 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-62142d222a80.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33182 chore: cherry-pick 49e8ff16f1fe from angle
  patches/angle/.patches
  patches/angle/cherry-pick-49e8ff16f1fe.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33170 docs: fix documented return value for getFocusedWebContents
  docs/api/web-contents.md
Labels: documentation :notebook:, semver/patch, no-backport

#33178 chore: cherry-pick 1887414c016d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1887414c016d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33160 fix: patches to use BUILDFLAG(IS_WIN) / BUILDFLAG(IS_MAC) checks
  patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
  patches/chromium/fix_media_key_usage_with_globalshortcuts.patch
  patches/chromium/process_singleton.patch
Labels: semver/patch, target/18-x-y

#33024 fix: crash when showing item in folder on DevTools
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y

#32871 fix: non-client mouse events on WCO-enabled windows
  patches/chromium/.patches
  patches/chromium/fix_non-client_mouse_tracking_and_message_bubbling_on_windows.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33186 chore: cherry-pick 62142d222a80 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-62142d222a80.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#32868 feat: warn that preloads will be sandboxed by default in v20
  docs/breaking-changes.md
  lib/browser/api/web-contents.ts
Labels: semver/minor, api-review/approved ✅, target/18-x-y

#33120 fix: settings not persisting across devtools loads
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, target/17-x-y, target/18-x-y

#33189 fix: propagate unsafely-treat-insecure-origin-as-secure to renderer children
  shell/browser/electron_browser_client.cc
Labels: semver/patch, no-backport

#33179 chore: cherry-pick 1887414c016d from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1887414c016d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33185 chore: cherry-pick 62142d222a80 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-62142d222a80.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33158 test: Formatted C++ Files According to the clang-format file.
  spec-main/fixtures/native-addon/uv-dlopen/foo.cpp
  spec-main/fixtures/native-addon/uv-dlopen/main.cpp
Labels: semver/none, no-backport

#32979 fix: fire show event when BrowserWindow shown via maximize()
  shell/browser/native_window_views.cc
  shell/browser/native_window_views_win.cc
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y

#33109 chore: cherry-pick 2ed58f4 from chromium
  patches/chromium/.patches
  patches/chromium/remove_incorrect_width_height_adjustments.patch
Labels: semver/patch, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33204 fix: prevent UAF crash in setCertificateVerifyProc
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33252 fix: cppgc/node collisions in renderer process
  patches/node/.patches
  patches/node/be_compatible_with_cppgc.patch
Labels: semver/patch, target/18-x-y

#33224 fix: add missing [[maybe_unused]] to IsEnvSet
  shell/app/electron_main_mac.cc
  shell/app/electron_main_win.cc
Labels: semver/patch, target/18-x-y

#33265 docs: reword sentence for better understanding
  docs/tutorial/process-model.md
Labels: documentation :notebook:, semver/patch, no-backport

#33063 fix: race condition where webContents can be nullptr during re-focus and a multi-window close sequence
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
Labels: semver/patch, target/17-x-y, target/18-x-y

#31154 feat: allow setting code cache directory
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec-main/api-session-spec.ts
Labels: semver/minor, api-review/requested 🗳, target/17-x-y, target/18-x-y

#33263 docs: remove "marked" from process.getBlinkMemoryInfo()
  docs/api/process.md
Labels: documentation :notebook:, semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33243 chore: cherry-pick eb967bf211 from chromium
  patches/chromium/.patches
  patches/chromium/fix_imagebitmaprenderingcontext_interaction_with_software_compositor.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33242 chore: cherry-pick eb967bf211 from chromium
  patches/chromium/.patches
  patches/chromium/fix_imagebitmaprenderingcontext_interaction_with_software_compositor.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33262 fix: fiddle ipc code pattern 3
  docs/fiddles/ipc/pattern-3/renderer.js
  docs/tutorial/ipc.md
Labels: semver/patch, target/17-x-y, target/18-x-y

#33254 fix: prevent UAF crash in setCertificateVerifyProc
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: backport, semver/patch, 17-x-y

#33266 fix: ensure external memory adjustments are balanced
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33280 fix: crash when destroying node env with pending promises
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
  spec-main/fixtures/crash-cases/fs-promises-renderer-crash/index.html
  spec-main/fixtures/crash-cases/fs-promises-renderer-crash/index.js
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33257 fix: BrowserWindow.fromWebContents should work in browser-window-created
  shell/common/gin_helper/trackable_object.h
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/18-x-y

#33228 chore: remove awkward semi-documented preloadURL WebPreference
  docs/api/web-contents.md
  docs/api/webview-tag.md
  docs/tutorial/security.md
  lib/browser/guest-view-manager.ts
  shell/browser/api/electron_api_net.cc
  shell/browser/web_contents_preferences.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec/static/main.js
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/patch, no-backport

#33312 fix: ensure external memory adjustments are balanced
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
Labels: backport, semver/patch, 16-x-y

#33311 fix: ensure external memory adjustments are balanced
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
Labels: backport, semver/patch, 15-x-y

#33319 build: fix build by removing usage of removed preloadUrl
  lib/browser/api/web-contents.ts
Labels: fast-track 🚅, semver/none, no-backport

#33310 docs: remove unused images
  docs/images/message-notification-renderer.png
  docs/images/online-event-detection.png
  docs/images/tutorial-release-schedule.svg
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#33314 fix: desktop screen capture on macOS not releasing
  patches/chromium/desktop_media_list.patch
Labels: backport, semver/patch, 16-x-y

#33309 docs: update links to Chromium source
  docs/api/app.md
  docs/api/client-request.md
  docs/api/command-line-switches.md
  docs/api/content-tracing.md
  docs/api/session.md
  docs/api/structures/protocol-response.md
  docs/api/structures/trace-config.md
  docs/api/web-contents.md
  docs/development/build-instructions-gn.md
  docs/development/build-instructions-windows.md
  docs/glossary.md
  docs/tutorial/sandbox.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#33323 fix: ensure ElectronBrowser mojo service is only bound to appropriate render frames
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/event.h
  shell/browser/electron_api_ipc_handler_impl.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/web_contents_preferences.h
  shell/common/api/api.mojom
  shell/common/gin_helper/event_emitter.cc
  shell/common/gin_helper/event_emitter.h
  shell/renderer/api/electron_api_ipc_renderer.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/electron_render_frame_observer.cc
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33339 fix: initialize FPS file in network service
  shell/browser/net/system_network_context_manager.cc
Labels: semver/patch, new-pr 🌱, target/18-x-y

#33304 fix: removed unused import
  script/lib/util.py
  script/release/uploaders/upload.py
Labels: semver/none, no-backport

#33258 chore: cherry-pick c11809b8c0 from chromium
  patches/chromium/.patches
  patches/chromium/enable_forcesynchronoushtmlparsing_by_default.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33246 chore: cherry-pick 246c10dede97 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-246c10dede97.patch
Labels: semver/patch, backport-check-skip, 14-x-y

#33245 chore: cherry-pick 246c10dede97 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-246c10dede97.patch
Labels: semver/patch, backport-check-skip, 15-x-y

#33313 fix: crash when showing item in folder on DevTools
  shell/browser/ui/inspectable_web_contents.cc
Labels: backport, semver/patch, 16-x-y

#33233 chore: fix pylint-2.7 errors
  script/add-debug-link.py
  script/check-relative-doc-links.py
  script/copy-debug-symbols.py
  script/generate-config-gypi.py
  script/generate-zip-manifest.py
  script/lib/config.py
  script/lib/git.py
  script/lib/native_tests.py
  script/lib/util.py
  script/native-tests.py
  script/release/uploaders/upload.py
  script/run-clang-format.py
  script/zip_manifests/check-zip-manifest.py
Labels: semver/none, no-backport

#33218 docs: possible change in tutorial/ipc
  docs/tutorial/ipc.md
Labels: documentation :notebook:, semver/patch, no-backport

#33207 fix: iocp integration when process is reused
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_linux.h
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_mac.h
  shell/common/node_bindings_win.cc
  shell/common/node_bindings_win.h
  shell/renderer/electron_renderer_client.cc
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33236 chore: cherry-pick 905302eb3a2b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-905302eb3a2b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#32956 feat: add nativeTheme.inForcedColorsMode
  docs/api/native-theme.md
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec-main/api-native-theme-spec.ts
Labels: semver/minor, api-review/approved ✅, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33361 fix: iocp integration when process is reused
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_linux.h
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_mac.h
  shell/common/node_bindings_win.cc
  shell/common/node_bindings_win.h
  shell/renderer/electron_renderer_client.cc
Labels: backport, semver/patch, 18-x-y

#31868 feat: support more color formats for `backgroundColor`
  docs/api/browser-view.md
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.cc
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/browser/web_contents_preferences.cc
  shell/common/color_util.cc
  shell/common/color_util.h
  spec-main/api-browser-window-spec.ts
Labels: semver/major, api-review/requested 🗳, target/18-x-y

#33348 docs: add note about supported versions to issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation :notebook:, semver/none, no-backport

#33346 chore: bump @electron/docs-parser version
  package.json
  yarn.lock
Labels: semver/none, no-backport

#33350 fix: ensure ElectronBrowser mojo service is only bound to appropriate render frames
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/event.h
  shell/browser/electron_api_ipc_handler_impl.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/web_contents_preferences.h
  shell/common/api/api.mojom
  shell/common/gin_helper/event_emitter.cc
  shell/common/gin_helper/event_emitter.h
  shell/renderer/api/electron_api_ipc_renderer.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/electron_render_frame_observer.cc
Labels: backport, semver/patch, 17-x-y

#33244 chore: cherry-pick 246c10dede97 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-246c10dede97.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33239 chore: cherry-pick 905302eb3a2b from chromium
  patches/chromium/.patches
  patches/chromium/m96-lts_roll_libxml_from_dea91c97_to_eab86522.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33237 chore: cherry-pick 905302eb3a2b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-905302eb3a2b.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33029 fix: NOTREACHED when resizing windows frameless bounds
  shell/browser/ui/views/win_frame_view.cc
Labels: semver/patch, new-pr 🌱, no-backport

#32973 fix: IncrementCapturerCount doesn't increase the capturer count
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-browser-view-spec.ts
  spec-main/api-browser-window-spec.ts
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33227 test: fix and re-enable Network.getResponseBody test
  spec-main/api-debugger-spec.ts
Labels: semver/none, no-backport

#33220 test: re-enable webview resize events test
  spec/webview-spec.js
Labels: semver/none, no-backport

#33362 fix: iocp integration when process is reused
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_linux.h
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_mac.h
  shell/common/node_bindings_win.cc
  shell/common/node_bindings_win.h
  shell/renderer/electron_renderer_client.cc
Labels: backport, semver/patch, 17-x-y

#33219 chore: cherry-pick ca32852e4f and 40bb7a43b2 from angle
  patches/angle/.patches
  patches/angle/m99_vulkan_prevent_out_of_bounds_read_in_divisor_emulation_path.patch
  patches/angle/m99_vulkan_streamvertexdatawithdivisor_write_beyond_buffer_boundary.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33288 fix: pend bounds change when moving BrowserWindows
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y

#33343 chore: cherry-pick 161f0866e8 from angle
  patches/angle/.patches
  patches/angle/m98_protect_against_deleting_a_current_xfb_buffer.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33342 chore: cherry-pick 161f0866e8 from angle
  patches/angle/.patches
  patches/angle/m98_protect_against_deleting_a_current_xfb_buffer.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33226 docs: mark skipTaskbar as unsupported on Linux
  docs/api/browser-window.md
  docs/breaking-changes.md
  shell/browser/native_window_views.cc
Labels: documentation :notebook:, semver/patch, no-backport

#33368 fix: use stricter options in SecStaticCodeCheckValidity
  patches/squirrel.mac/.patches
  patches/squirrel.mac/fix_use_kseccschecknestedcode_kseccsstrictvalidate_in_the_sec.patch
  spec-main/api-autoupdater-darwin-spec.ts
Labels: semver/patch, new-pr 🌱, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33231 chore: cherry-pick 1aa9b09 from chromium
  patches/chromium/.patches
  patches/chromium/set_dpi_correctly_during_main_window_creation.patch
Labels: semver/minor, backport-check-skip, target/15-x-y, target/16-x-y, target/17-x-y

#33188 fix: disable SIGUSR1 when --inspect is disabled
  patches/node/.patches
  patches/node/feat_add_knostartdebugsignalhandler_to_environment_to_prevent.patch
  shell/common/node_bindings.cc
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y

#33373 chore: change usages of std::vector with const elements
  patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
Labels: new-pr 🌱, semver/none, no-backport

#33194 ci: enable thin LTO on Mac
  .circleci/build_config.yml
  patches/chromium/.patches
  patches/chromium/build_disable_thin_lto_on_mac.patch
Labels: semver/none, target/18-x-y

#33366 docs: remove extra $ from npm install command
  docs/tutorial/quick-start.md
Labels: documentation :notebook:, semver/patch, no-backport

#33223 chore: cherry-pick ca32852e4f and 40bb7a43b2 from angle
  patches/angle/.patches
  patches/angle/m99_vulkan_prevent_out_of_bounds_read_in_divisor_emulation_path.patch
  patches/angle/m99_vulkan_streamvertexdatawithdivisor_write_beyond_buffer_boundary.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33222 chore: cherry-pick ca32852e4f and 40bb7a43b2 from angle
  patches/angle/.patches
  patches/angle/m99_vulkan_prevent_out_of_bounds_read_in_divisor_emulation_path.patch
  patches/angle/m99_vulkan_streamvertexdatawithdivisor_write_beyond_buffer_boundary.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33148 test: fix crash on image.crop
  spec-main/screen-helpers.ts
Labels: semver/none, target/16-x-y, target/17-x-y, target/18-x-y

#33232 chore: use pylint-2.7
  script/lint.js
  script/release/uploaders/upload.py
  script/run-clang-format.py
Labels: semver/none, no-backport

#33216 fix: initialize asar support in worker threads
  lib/asar/fs-wrapper.ts
  patches/node/.patches
  patches/node/worker_thread_add_asar_support.patch
  shell/common/api/electron_api_asar.cc
  shell/common/node_includes.h
  spec-main/asar-spec.ts
  spec/fixtures/test.asar/worker_threads.asar
  typings/internal-ambient.d.ts
Labels: semver/patch, target/17-x-y, target/18-x-y

#33369 docs: add new IPC validation section to the security tutorial
  docs/tutorial/security.md
Labels: documentation :notebook:, semver/patch, no-backport

#32747 fix: persist BrowserView content bounds when calculating layout
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
Labels: semver/patch, target/17-x-y, target/18-x-y

#33363 fix: iocp integration when process is reused
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_linux.h
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_mac.h
  shell/common/node_bindings_win.cc
  shell/common/node_bindings_win.h
  shell/renderer/electron_renderer_client.cc
Labels: backport, semver/patch, 16-x-y

#33038 chore: backport dd4c3ddadbb9 from chromium
  patches/chromium/.patches
  patches/chromium/fixed_terminate_caused_by_binding_to_wrong_version.patch
  patches/chromium/follow_wayland_specification_regarding_xkb_keymap.patch
Labels: semver/patch, backport-check-skip

#33372 docs: update Ubuntu version used for Linux prebuilt binaries
  README.md
Labels: documentation :notebook:, semver/patch, target/18-x-y

#33337 fix: libuv patches to address child_process.spawn slowness
  patches/node/.patches
  patches/node/macos_don_t_use_thread-unsafe_strtok_3524.patch
  patches/node/process_bsd_handle_kevent_note_exit_failure_3451.patch
  patches/node/process_fix_hang_after_note_exit_3521.patch
  patches/node/process_monitor_for_exit_with_kqueue_on_bsds_3441.patch
  patches/node/process_only_use_f_dupfd_cloexec_if_it_is_defined_3512.patch
  patches/node/process_reset_the_signal_mask_if_the_fork_fails_3537.patch
  patches/node/process_simplify_uv_write_int_calls_3519.patch
  patches/node/reland_macos_use_posix_spawn_instead_of_fork_3257.patch
  patches/node/unix_protect_fork_in_uv_spawn_from_signals.patch
  patches/node/unix_remove_uv_cloexec_ioctl_3515.patch
  patches/node/unix_simplify_uv_cloexec_fcntl_3492.patch
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33390 chore: cherry-pick 2b75a29bf2 from angle
  patches/angle/.patches
  patches/angle/m96-lts_vulkan_fix_issue_with_redefining_a_layered_attachment.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33409 test: Revert "test: re-enable webview resize events test"
  spec/webview-spec.js
Labels: fast-track 🚅, semver/none, no-backport

#33413 ci: abort CI if goma authentication is invalid
  .circleci/build_config.yml
  appveyor.yml
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33358 feat: add nativeTheme.inForcedColorsMode
  docs/api/native-theme.md
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec-main/api-native-theme-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 17-x-y

#33360 feat: add nativeTheme.inForcedColorsMode
  docs/api/native-theme.md
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec-main/api-native-theme-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 15-x-y

#33421 chore: update out-dated node patches
  patches/node/.patches
  patches/node/feat_add_knostartdebugsignalhandler_to_environment_to_prevent.patch
  patches/node/process_bsd_handle_kevent_note_exit_failure_3451.patch
  patches/node/process_fix_hang_after_note_exit_3521.patch
  patches/node/process_monitor_for_exit_with_kqueue_on_bsds_3441.patch
  patches/node/unix_protect_fork_in_uv_spawn_from_signals.patch
  patches/node/worker_thread_add_asar_support.patch
Labels: fast-track 🚅, semver/none, no-backport

#33402 docs: remove pywin32 from Windows build instructions
  docs/development/build-instructions-windows.md
Labels: documentation :notebook:, semver/none

#33423 test: disable webview.capturePage test
  spec/webview-spec.js
Labels: backport-check-skip, semver/none, target/15-x-y, target/16-x-y

#33415 docs: fix SCA and postMessage links in web-frame-main.md
  docs/api/web-frame-main.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/14-x-y, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33392 chore: cherry-pick c46fb3a15ec2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-c46fb3a15ec2.patch
Labels: semver/patch, backport-check-skip, 16-x-y

#33389 chore: cherry-pick 2b75a29bf241 from angle
  patches/angle/.patches
  patches/angle/cherry-pick-2b75a29bf241.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33359 feat: add nativeTheme.inForcedColorsMode
  docs/api/native-theme.md
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec-main/api-native-theme-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 16-x-y

#33341 chore: cherry-pick 161f0866e8 from angle
  patches/angle/.patches
  patches/angle/m98_protect_against_deleting_a_current_xfb_buffer.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33240 chore: cherry-pick eb967bf21108 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-eb967bf21108.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33066 feat: add WCO title bar style setters
  docs/api/browser-window.md
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/native_window.h
  shell/browser/native_window_views.h
  shell/browser/ui/views/win_caption_button.cc
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
Labels: semver/minor, new-pr 🌱, api-review/approved ✅, target/17-x-y, target/18-x-y

#33401 docs: update china npmmirror
  README.md
Labels: documentation :notebook:, semver/none, no-backport

#33429 fix: gn check when //printing component is disabled
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, new-pr 🌱, target/17-x-y, target/18-x-y

#33438 fix: non-client windows messages on legacy widget host (again)
  patches/chromium/fix_non-client_mouse_tracking_and_message_bubbling_on_windows.patch
Labels: semver/patch, new-pr 🌱, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33449 fix: non-client windows messages on legacy widget host (again)
  patches/chromium/fix_non-client_mouse_tracking_and_message_bubbling_on_windows.patch
Labels: backport, semver/patch, 15-x-y

#33391 chore: cherry-pick 2b75a29bf2 from angle
  patches/angle/.patches
  patches/angle/m96-lts_vulkan_fix_issue_with_redefining_a_layered_attachment.patch
Labels: security 🔒, semver/patch, backport-check-skip, 14-x-y

#33430 fix: IncrementCapturerCount doesn't increase the capturer count
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-browser-view-spec.ts
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/patch, 17-x-y

#33393 chore: cherry-pick c46fb3a15ec2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-c46fb3a15ec2.patch
Labels: semver/patch, backport-check-skip, 15-x-y

#33435 fix: BrowserView background color in webContents
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_web_contents.cc
  spec-main/api-browser-view-spec.ts
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y

#33355 fix: calling of X11 functions when running under Wayland
  BUILD.gn
  filenames.gni
  patches/chromium/.patches
  patches/chromium/introduce_ozoneplatform_electron_can_call_x11_property.patch
  patches/chromium/ui_gtk_public_header.patch
  shell/browser/electron_browser_main_parts.h
  shell/browser/native_window.cc
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/gtk/menu_util.cc
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y

#33340 chore: cherry-pick 2a58cc86bf from angle
  patches/angle/.patches
  patches/angle/m96-lts_fix_base_level_changes_not_updating_fbo_completeness_check.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#32936 build: store last ninja log in artifacts
  .circleci/build_config.yml
Labels: semver/none, no-backport

#33463 docs: Use Node's URL parser in the 5th security recommendation example
  docs/tutorial/security.md
Labels: documentation :notebook:, semver/patch, no-backport

#33474 chore: cherry-pick 26b7ad6967b1 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-26b7ad6967b1.patch
Labels: semver/patch, backport-check-skip, 14-x-y

#33479 docs: simplify skipTaskbar breaking changes text
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, fast-track 🚅, target/18-x-y

#33472 chore: cherry-pick 26b7ad6967b1 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-26b7ad6967b1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33473 chore: cherry-pick 26b7ad6967b1 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-26b7ad6967b1.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33452 chore: update node types version
  lib/common/webpack-provider.ts
  npm/package.json
  package.json
  spec-main/api-web-request-spec.ts
  typings/internal-ambient.d.ts
  yarn.lock
Labels: semver/none, in-flight/18-x-y

#33482 docs: docs: simplify skipTaskbar breaking changes text
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, fast-track 🚅, backport-check-skip, 18-x-y

#33477 chore: update node types version
  lib/common/webpack-provider.ts
  npm/package.json
  package.json
  spec-main/api-web-request-spec.ts
  typings/internal-ambient.d.ts
  yarn.lock
Labels: backport, backport-check-skip, semver/none, 18-x-y

#33483 chore: bump chromium in DEPS to 98.0.4758.141
  DEPS
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/chore_use_electron_resources_not_chrome_for_spellchecker.patch
  patches/chromium/resource_file_conflict.patch
Labels: semver/patch, backport-check-skip

#33069 fix: crash when WindowButtonsProxy references cleared NSWindow
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y

#33486 ci: fixup esbuild on macos
  .circleci/build_config.yml
Labels: fast-track 🚅, semver/none, target/18-x-y

#33493 chore: revert "Bump v18.0.0"
  ELECTRON_VERSION
  package.json
  shell/browser/resources/win/electron.rc
Labels: fast-track 🚅, backport-check-skip, semver/none

#33467 docs: update heading level of webFrame.insertCSS
  docs/api/web-frame.md
Labels: documentation :notebook:, semver/patch, no-backport

#31647 chore: update libuv patch for event loop integration
  patches/node/.patches
  patches/node/feat_add_uv_loop_interrupt_on_io_change_option_to_uv_loop_configure.patch
  patches/node/feat_add_uv_loop_watcher_queue_code.patch
  patches/node/unix_remove_uv_cloexec_ioctl_3515.patch
  patches/node/unix_simplify_uv_cloexec_fcntl_3492.patch
  shell/common/node_bindings.cc
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_linux.h
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_mac.h
Labels: semver/none, no-backport

#33498 fix: calling of X11 functions when running under Wayland
  BUILD.gn
  filenames.gni
  patches/chromium/.patches
  patches/chromium/introduce_ozoneplatform_electron_can_call_x11_property.patch
  patches/chromium/ui_gtk_public_header.patch
  shell/browser/electron_browser_main_parts.h
  shell/browser/native_window.cc
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/gtk/menu_util.cc
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/x/window_state_watcher.cc
  shell/browser/ui/x/window_state_watcher.h
Labels: backport, semver/patch, 18-x-y

#33471 chore: fix moveAbove desktopCapturer spec
  spec-main/api-desktop-capturer-spec.ts
Labels: semver/none, no-backport

#33497 test: re-enable `desktopCapturer` specs
  spec-main/api-desktop-capturer-spec.ts
Labels: semver/none, target/18-x-y

#33481 docs: fix type of 'value' param in setUserDefaults
  docs/api/system-preferences.md
Labels: documentation :notebook:, semver/patch, no-backport

#33470 feat: add new Squirrel.Mac bundle installation method behind flag
  patches/squirrel.mac/.patches
  patches/squirrel.mac/feat_add_new_squirrel_mac_bundle_installation_method_behind_flag.patch
  spec-main/api-autoupdater-darwin-spec.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/18-x-y
