Repository electron/electron, pull requests merged in 2022-04, with the labels that each got.

#33559 fix: create `userData` on requestSingleInstanceLock() if needed
  shell/browser/api/electron_api_app.cc
  spec-main/api-app-spec.ts
  spec/fixtures/api/singleton-userdata/main.js
  spec/fixtures/api/singleton-userdata/package.json
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33543 fix: pend bounds change when moving BrowserWindows
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
Labels: backport, semver/patch, 17-x-y

#33535 fix: on macOS show BrowserWindow on maximize if not currently shown
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/patch, 16-x-y

#33512 docs: mark platform-specific functionality for BrowserWindow
  docs/api/browser-window.md
Labels: documentation :notebook:, semver/patch, target/17-x-y, target/18-x-y, target/19-x-y

#33573 build: upload to AZ as well as S3
  package.json
  script/lib/azput.js
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload-node-checksums.py
  script/release/uploaders/upload-node-headers.py
  script/release/uploaders/upload-symbols.py
  script/release/uploaders/upload.py
  yarn.lock
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33602 fix: building with printing disabled
  shell/browser/electron_browser_handler_impl.h
Labels: backport-check-skip, semver/none

#33603 fix: building with printing disabled
  shell/browser/electron_browser_handler_impl.h
Labels: backport-check-skip, semver/none

#33599 fix: revert "fix: some frameless windows showing a frame on Windows"
  shell/browser/native_window_views.cc
Labels: semver/patch, new-pr 🌱, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33614 fix: add missing translation string for ax tree
  electron_strings.grdp
Labels: semver/patch, fast-track 🚅, target/18-x-y, target/19-x-y

#33615 test: disable newly added/failing test on Windows
  spec-main/api-browser-window-spec.ts
Labels: backport-check-skip, semver/none, 15-x-y

#33568 chore: fix typo in NotifyWindowRequestPreferredWidth method name
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: semver/none, no-backport

#33618 chore: cherry-pick be623b0f from chromium
  patches/chromium/.patches
  patches/chromium/revert_motionmark_avoid_unnecessary_ipc_on_mac.patch
Labels: semver/patch, backport-check-skip, 17-x-y

#33605 chore: cherry-pick f599381978f2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-f599381978f2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33606 chore: cherry-pick f599381978f2 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-f599381978f2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33613 chore: cherry-pick 36b66b5cc991 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-36b66b5cc991.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33595 chore: combine some smaller MAS patches
  patches/chromium/.patches
  patches/chromium/mas-audiodeviceduck.patch
  patches/chromium/mas-cfisobjc.patch
  patches/chromium/mas_avoid_usage_of_abort_report_np.patch
  patches/chromium/mas_avoid_usage_of_private_macos_apis.patch
  patches/chromium/mas_avoid_usage_of_pthread_fchdir_np.patch
  patches/chromium/mas_avoid_usage_of_setapplicationisdaemon_and.patch
  patches/chromium/mas_gate_private_enterprise_APIs.patch
Labels: semver/none, no-backport

#33255 fix: prevent UAF crash in setCertificateVerifyProc
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: backport, semver/patch, 16-x-y

#33256 fix: prevent UAF crash in setCertificateVerifyProc
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: backport, semver/patch, 15-x-y

#33536 fix: on macOS show BrowserWindow on maximize if not currently shown
  shell/browser/native_window_mac.mm
  spec-main/api-browser-window-spec.ts
Labels: backport, semver/patch, 17-x-y

#33628 docs: recommend setting e.returnValue
  docs/api/browser-window.md
Labels: documentation :notebook:, semver/none, target/17-x-y, target/18-x-y, target/19-x-y

#33629 build: fix numpy package install on mac arm64
  patches/chromium/.patches
  patches/chromium/use_numpy_1_2x_supported_1_for_vpython.patch
Labels: backport-check-skip, semver/none

#33620 fix: report more detailed errors in shell.openExternal() on Windows
  shell/common/platform_util_win.cc
Labels: semver/patch, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33653 build: temporarily disable 32-bit Windows symbol generation
  appveyor.yml
  script/release/release.js
  script/release/uploaders/upload.py
Labels: fast-track 🚅, semver/none, target/19-x-y

#33683 fix: emojis appearing black and white in Chromium 96
  patches/config.json
  patches/skia/.patches
  patches/skia/fix_when_a_glyph_has_a_path.patch
Labels: semver/patch, backport-check-skip, 16-x-y

#33699 chore: modify uploaded assets for win-ia32
  appveyor.yml
  script/release/release.js
  script/release/uploaders/upload.py
Labels: fast-track 🚅, semver/none, no-backport

#33678 chore: cherry-pick a1dc371d66 from chromium
  patches/chromium/.patches
  patches/chromium/usb_fix_oob_access_with_non-sequential_interfaces.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33689 build: temporarily disable 32-bit Windows symbol generation (#33653)
  appveyor.yml
  script/release/release.js
  script/release/uploaders/upload.py
Labels: backport, semver/none, 19-x-y

#33560 feat: implement chrome.tabs.reload to fix PDF Viewer error
  docs/api/extensions.md
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/api/tabs/tabs_api.h
  shell/common/extensions/api/tabs.json
Labels: semver/minor, api-review/requested 🗳, target/18-x-y, target/19-x-y

#33627 build: use python3 to lint
  docs/development/build-instructions-linux.md
  docs/development/build-instructions-macos.md
  docs/development/coding-style.md
  package.json
  script/check-relative-doc-links.py
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33710 chore: cherry-pick a18fddcb53e6 from webrtc
  patches/webrtc/.patches
  patches/webrtc/cherry-pick-a18fddcb53e6.patch
Labels: semver/patch, backport-check-skip, 16-x-y

#33674 chore: cherry-pick 4d26949260aa from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-4d26949260aa.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33669 chore: cherry-pick 652dd12a and d05317ce from libxml
  patches/chromium/.patches
  patches/chromium/fix_--without-valid_build.patch
  patches/chromium/use-after-free_of_id_and_idref_attributes.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33664 fix: backport unseasoned pdf support to 18.x
  BUILD.gn
  chromium_src/BUILD.gn
  shell/app/electron_content_client.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/common/electron_constants.cc
  shell/common/electron_constants.h
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
Labels: semver/patch, backport-check-skip, 18-x-y

#33715 chore: cherry-pick a48de319c521 from pdfium
  patches/config.json
  patches/pdfium/.patches
  patches/pdfium/cherry-pick-a48de319c521.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33702 test: re-enable disabled ScriptOrModule specs
  spec-main/api-web-contents-spec.ts
  spec-main/chromium-spec.ts
Labels: semver/none, no-backport

#33720 build: explicitly run scripts with python3
  build/js2c.py
  build/npm-run.py
  build/strip_framework.py
  build/zip.py
  build/zip_libcxx.py
  patches/node/build_add_gn_build_files.patch
  patches/squirrel.mac/build_add_gn_config.patch
  script/add-debug-link.py
  script/apply_all_patches.py
  script/check-relative-doc-links.py
  script/copy-debug-symbols.py
  script/dbus_mock.py
  script/export_all_patches.py
  script/generate-config-gypi.py
  script/generate-zip-manifest.py
  script/git-export-patches
  script/git-import-patches
  script/lib/config.py
  script/lib/git.py
  script/lib/patches.py
  script/lib/util.py
  script/native-tests.py
  script/patches-mtime-cache.py
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload-node-checksums.py
  script/release/uploaders/upload-node-headers.py
  script/release/uploaders/upload-symbols.py
  script/release/uploaders/upload.py
  script/run-clang-format.py
  script/strip-binaries.py
  script/verify-chromedriver.py
  script/verify-ffmpeg.py
  script/verify-mksnapshot.py
  script/zip-symbols.py
  script/zip_manifests/check-zip-manifest.py
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33724 docs: note `safeStorage.isEncryptionAvailable()` needs ready event
  docs/api/safe-storage.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/18-x-y, target/19-x-y

#33737 build: migrate urllib to python3
  script/release/uploaders/upload-index-json.py
Labels: fast-track 🚅, semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33746 docs: manually backport ipc doc
  docs/tutorial/ipc.md
Labels: documentation :notebook:, semver/none

#33747 build: add comment for enable_cet_shadow_stack
  build/args/all.gn
Labels: fast-track 🚅, semver/none, no-backport

#33748 docs: add ipc fiddle samples
  docs/fiddles/ipc/pattern-1/index.html
  docs/fiddles/ipc/pattern-1/main.js
  docs/fiddles/ipc/pattern-1/preload.js
  docs/fiddles/ipc/pattern-1/renderer.js
  docs/fiddles/ipc/pattern-2/index.html
  docs/fiddles/ipc/pattern-2/main.js
  docs/fiddles/ipc/pattern-2/preload.js
  docs/fiddles/ipc/pattern-2/renderer.js
  docs/fiddles/ipc/pattern-3/index.html
  docs/fiddles/ipc/pattern-3/main.js
  docs/fiddles/ipc/pattern-3/preload.js
  docs/fiddles/ipc/pattern-3/renderer.js
Labels: documentation :notebook:, backport, semver/none, 18-x-y

#33749 docs: note reason for is_cfi = false
  build/args/all.gn
Labels: documentation :notebook:, new-pr 🌱, semver/none, no-backport

#33707 fix: #ARGB to #RGBA conversion
  shell/common/color_util.cc
Labels: semver/patch, target/19-x-y

#33668 chore: cherry-pick 652dd12a and d05317ce from libxml
  patches/chromium/.patches
  patches/chromium/fix_--without-valid_build.patch
  patches/chromium/use-after-free_of_id_and_idref_attributes.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33751 build: filter symbols/json correctly per arch
  script/release/uploaders/upload.py
Labels: fast-track 🚅, semver/none, no-backport, 19-x-y

#33680 chore: cherry-pick 1665a1d16d46 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1665a1d16d46.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33641 feat: allow `null` when subscribing notification
  docs/api/system-preferences.md
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_system_preferences_mac.mm
  spec-main/api-system-preferences-spec.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/17-x-y, target/18-x-y, target/19-x-y

#33766 chore: interpret bytes and string args on python3 open
  script/release/uploaders/upload-index-json.py
Labels: fast-track 🚅, semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33756 fix: apply senderFrame details to ipcMain port event
  lib/browser/api/web-contents.ts
  spec-main/api-ipc-spec.ts
Labels: semver/patch, new-pr 🌱, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33761 chore: cherry-pick f546ac11eec7 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-f546ac11eec7.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33785 ci: manually install python2
  .circleci/build_config.yml
Labels: fast-track 🚅, semver/none, target/19-x-y

#33677 chore: cherry-pick a1dc371d6680 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-a1dc371d6680.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33763 chore: cherry-pick f546ac11eec7 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-f546ac11eec7.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33757 fix: event propagation after exiting fullscreen on Windows
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/18-x-y, target/19-x-y

#33679 chore: cherry-pick a1dc371d66 from chromium
  patches/chromium/.patches
  patches/chromium/usb_fix_oob_access_with_non-sequential_interfaces.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33793 ci: build python2 from source
  .circleci/build_config.yml
Labels: fast-track 🚅, semver/none, target/19-x-y

#33672 chore: cherry-pick ac341df436 from webrtc
  patches/webrtc/.patches
  patches/webrtc/adding_fuzzer_for_pcm16b_decoder_and_fixing_a_fuzzer_problem.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33670 chore: cherry-pick 652dd12a and d05317ce from libxml
  patches/chromium/.patches
  patches/chromium/fix_--without-valid_build.patch
  patches/chromium/use-after-free_of_id_and_idref_attributes.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33650 fix: potential crash caused by dlopen different gtk libraries
  BUILD.gn
  patches/chromium/.patches
  patches/chromium/make_gtk_getlibgtk_public.patch
  patches/chromium/ui_gtk_public_header.patch
  shell/browser/browser_linux.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/notifications/linux/libnotify_notification.cc
  shell/browser/ui/electron_gtk.fragment
  shell/browser/ui/electron_gtk.sigs
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/menu_bar.cc
  shell/common/application_info_linux.cc
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33544 fix: pend bounds change when moving BrowserWindows
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
Labels: backport, semver/patch, 16-x-y

#33818 chore: fix patch conflicts from 37b7e347
  BUILD.gn
  patches/chromium/make_gtk_getlibgtk_public.patch
Labels: fast-track 🚅, semver/none, no-backport

#33762 chore: cherry-pick f546ac11eec7 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-f546ac11eec7.patch
Labels: semver/patch, backport-check-skip, 16-x-y

#33807 docs: update security guide regarding ctx isolation
  docs/api/context-bridge.md
  docs/breaking-changes.md
  docs/tutorial/security.md
Labels: documentation :notebook:, semver/patch, no-backport

#33696 docs: document when `BrowserWindow` and `BrowserView` can be used
  docs/api/browser-view.md
  docs/api/browser-window.md
Labels: documentation :notebook:, semver/patch, no-backport

#33840 fix: include accessibility blink strings
  electron_paks.gni
Labels: semver/patch, fast-track 🚅, in-flight/19-x-y

#33841 fix: include accessibility blink strings
  electron_paks.gni
Labels: backport, semver/patch, fast-track 🚅, target/18-x-y, 19-x-y

#33857 chore: use semantic-commit-action
  .github/workflows/semantic.yml
Labels: fast-track 🚅, semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33838 fix: building with printing disabled
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_web_contents_utility_handler_impl.h
Labels: backport-check-skip, semver/none, 17-x-y

#33834 chore: cherry-pick b2d3ef69ef99 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-b2d3ef69ef99.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33835 chore: cherry-pick b2d3ef69ef99 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-b2d3ef69ef99.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33836 chore: cherry-pick b2d3ef69ef99 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-b2d3ef69ef99.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33832 fix: adopt partition alloc early initialization for macOS
  BUILD.gn
  shell/app/electron_main_mac.cc
Labels: semver/patch, no-backport

#33815 chore: backport 7c9b3938d from libuv
  patches/node/.patches
  patches/node/macos_avoid_posix_spawnp_cwd_bug_3597.patch
Labels: semver/patch, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33860 chore: cherry-pick 5cb934a23d from chromium
  patches/chromium/.patches
  patches/chromium/m100_change_ownership_of_blobbytesprovider.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33859 chore: cherry-pick 5cb934a23d from chromium
  patches/chromium/.patches
  patches/chromium/m100_change_ownership_of_blobbytesprovider.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33858 chore: cherry-pick 5cb934a23ddf from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-5cb934a23ddf.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33831 chore: cherry-pick e42dbcdedb7a from v8
  patches/v8/.patches
  patches/v8/cherry-pick-e42dbcdedb7a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33778 fix: requestSingleInstanceLock API sometimes hangs
  patches/chromium/feat_add_data_transfer_to_requestsingleinstancelock.patch
Labels: semver/patch, backport-check-skip, 18-x-y

#33768 build: fix intermittent compilation failures on macOS
  BUILD.gn
  shell/app/electron_main_mac.cc
Labels: semver/none, target/17-x-y, target/18-x-y, target/19-x-y

#33881 build: improve circleci config
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/yarn.lock
Labels: semver/none, no-backport

#33856 chore: cherry-pick 1a31e2110440 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1a31e2110440.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33854 chore: cherry-pick 1a31e2110440 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1a31e2110440.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33851 chore: cherry-pick 4deb522c22 and d88e959e01 from chromium
  patches/chromium/.patches
  patches/chromium/skia_renderer_-_don_t_explicitly_clip_scissor_for_large_transforms.patch
  patches/chromium/skia_renderer_use_rectf_intersect_in_applyscissor.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33830 chore: cherry-pick e42dbcdedb7a from v8
  patches/v8/.patches
  patches/v8/cherry-pick-e42dbcdedb7a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33829 chore: cherry-pick e42dbcdedb7a from v8
  patches/v8/.patches
  patches/v8/cherry-pick-e42dbcdedb7a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33883 chore: cherry-pick 2004594a46c8 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-2004594a46c8.patch
Labels: semver/patch, backport-check-skip, 16-x-y

#33675 chore: cherry-pick 4d26949260aa from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-4d26949260aa.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33915 build: fix macos release GN gen
  BUILD.gn
Labels: fast-track 🚅, semver/none, target/19-x-y

#33922 build: use dev-cdn instead of sysroots s3 bucket
  patches/chromium/sysroot.patch
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33904 build: improve CI speeds and reduce CI costs
  .circleci/config/base.yml
  BUILD.gn
  script/node-disabled-tests.json
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33945 build: improve circleci config
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/yarn.lock
  script/release/ci-release-build.js
Labels: backport, semver/none, 15-x-y

#33943 build: improve circleci config
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/yarn.lock
  script/release/ci-release-build.js
Labels: backport, semver/none, 17-x-y

#33941 build: improve circleci config
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/yarn.lock
  script/release/ci-release-build.js
Labels: backport, semver/none, 18-x-y

#33929 build: actually verify az urls too
  script/release/release.js
Labels: semver/none, target/19-x-y

#33924 build: upload to AZ as well as S3
  package.json
  script/lib/azput.js
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload-node-checksums.py
  script/release/uploaders/upload-node-headers.py
  script/release/uploaders/upload-symbols.py
  script/release/uploaders/upload.py
  yarn.lock
Labels: backport, semver/none, 18-x-y

#33926 build: upload to AZ as well as S3
  package.json
  script/lib/azput.js
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload-node-checksums.py
  script/release/uploaders/upload-node-headers.py
  script/release/uploaders/upload-symbols.py
  script/release/uploaders/upload.py
  yarn.lock
Labels: backport, semver/none, 16-x-y

#33927 build: upload to AZ as well as S3
  package.json
  script/lib/azput.js
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload-node-checksums.py
  script/release/uploaders/upload-node-headers.py
  script/release/uploaders/upload-symbols.py
  script/release/uploaders/upload.py
  yarn.lock
Labels: backport, semver/none, 15-x-y

#33925 build: upload to AZ as well as S3
  package.json
  script/lib/azput.js
  script/lib/util.py
  script/release/release.js
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload-node-checksums.py
  script/release/uploaders/upload-node-headers.py
  script/release/uploaders/upload-symbols.py
  script/release/uploaders/upload.py
  yarn.lock
Labels: backport, semver/none, 17-x-y

#33940 build: improve circleci config
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/yarn.lock
  script/release/ci-release-build.js
Labels: backport, semver/none, 19-x-y

#33949 build: ensure sync-done file exists during git cache save
  .circleci/config/base.yml
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y

#33850 chore: cherry-pick d88e959e01 from chromium
  patches/chromium/.patches
  patches/chromium/skia_renderer_use_rectf_intersect_in_applyscissor.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33882 chore: cherry-pick 2004594a46c8 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-2004594a46c8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33855 chore: cherry-pick 1a31e2110440 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1a31e2110440.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33910 docs: fix return type of setJumpList() in electron.d.ts
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/18-x-y, target/19-x-y

#33905 build: use smaller resource_class because goma
  .circleci/config/base.yml
Labels: semver/none, no-backport

#33671 chore: cherry-pick ac341df436 from webrtc
  patches/webrtc/.patches
  patches/webrtc/adding_fuzzer_for_pcm16b_decoder_and_fixing_a_fuzzer_problem.patch
Labels: security 🔒, semver/patch, backport-check-skip, 17-x-y

#33704 fix: [Mac] Disable MallocNanoZone
  shell/browser/resources/mac/Info.plist
  shell/common/resources/mac/Info.plist
  shell/renderer/resources/mac/Info.plist
Labels: semver/patch, target/18-x-y, target/19-x-y

#33885 chore: cherry-pick 38ab9c5b06a4 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-38ab9c5b06a4.patch
Labels: security 🔒, semver/patch, backport-check-skip, 16-x-y

#33968 Revert "Bump v18.2.0"
  ELECTRON_VERSION
  package.json
  shell/browser/resources/win/electron.rc
Labels: fast-track 🚅, backport-check-skip, semver/none

#33951 build: improve CI speeds and reduce CI costs (#33904)
  .circleci/config/base.yml
  BUILD.gn
  script/node-disabled-tests.json
Labels: backport, semver/none, 19-x-y

#33852 chore: cherry-pick 4deb522c22 and d88e959e01 from chromium
  patches/chromium/.patches
  patches/chromium/skia_renderer_-_don_t_explicitly_clip_scissor_for_large_transforms.patch
  patches/chromium/skia_renderer_use_rectf_intersect_in_applyscissor.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33790 refactor: better solution for resizable frameless DCHECK
  shell/browser/ui/views/frameless_view.cc
  shell/browser/ui/views/frameless_view.h
  shell/browser/ui/views/win_frame_view.cc
  shell/browser/ui/views/win_frame_view.h
Labels: semver/patch, target/18-x-y, target/19-x-y

#33676 chore: cherry-pick 4d26949260aa from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-4d26949260aa.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33971 fix: fix FirstPartySetsHandler initialization
  shell/browser/net/system_network_context_manager.cc
Labels: semver/patch, new-pr 🌱, in-flight/19-x-y

#33972 fix: fix FirstPartySetsHandler initialization
  shell/browser/net/system_network_context_manager.cc
Labels: backport, semver/patch, 19-x-y

#33884 chore: cherry-pick 2004594a46c8 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-2004594a46c8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 15-x-y

#33980 build: revert migrate urllib to python3
  script/release/uploaders/upload-index-json.py
Labels: backport-check-skip, semver/none, 15-x-y

#33983 test: allow connections to port 2049
  spec/static/main.js
Labels: semver/none, target/15-x-y, target/16-x-y, target/17-x-y, target/18-x-y, target/19-x-y
