Repository electron/electron, pull requests merged in 2023-05, with the labels that each got.

#38136 fix: crash on missing `RenderWidgetHostView`
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
Labels: backport, semver/patch, 24-x-y

#38133 chore: add missing content::WebContentsDelegate section
  shell/browser/api/electron_api_web_contents.h
Labels: semver/none, target/25-x-y

#37853 feat: net.resolveHost
  docs/api/net.md
  lib/browser/api/net.ts
Labels: semver/minor, api-review/approved ✅, target/24-x-y, target/25-x-y

#38127 chore: add OCR scaffolding to PDF Viewer
  filenames.gni
  shell/browser/extensions/api/BUILD.gn
  shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.cc
  shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.h
  shell/browser/extensions/api/resources_private/resources_private_api.cc
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/_permission_features.json
  shell/common/extensions/api/pdf_viewer_private.idl
  shell/common/extensions/electron_extensions_api_provider.cc
Labels: semver/patch, target/25-x-y

#38143 chore: correct extra qualification causing build error with gcc
  shell/browser/hid/electron_hid_delegate.h
  shell/browser/serial/electron_serial_delegate.h
Labels: backport, semver/patch, 25-x-y

#36914 fix: falsy transparent shouldn't affect webContents background
  lib/browser/api/web-contents.ts
  shell/browser/web_contents_preferences.cc
  spec/api-browser-window-spec.ts
  spec/guest-window-manager-spec.ts
  spec/lib/screen-helpers.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38147 fix: `AXManualAccessibility` showing failure
  docs/tutorial/accessibility.md
  shell/browser/mac/electron_application.mm
Labels: backport, semver/patch, 24-x-y

#38145 chore: correct extra qualification causing build error with gcc
  shell/browser/hid/electron_hid_delegate.h
  shell/browser/serial/electron_serial_delegate.h
Labels: backport, semver/patch, 24-x-y

#38151 fix: `AXManualAccessibility` showing failure
  docs/tutorial/accessibility.md
  shell/browser/mac/electron_application.mm
Labels: backport, semver/patch, 23-x-y

#37978 feat: surface more `webContents` text selection commands
  docs/api/web-contents.md
  docs/api/webview-tag.md
  lib/common/web-view-methods.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/minor, api-review/approved ✅, target/25-x-y

#38156 fix: crash in utilityProcess when generating code from strings
  shell/app/electron_main_delegate.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.cc
  shell/common/gin_helper/locker.cc
  shell/common/gin_helper/locker.h
  shell/common/gin_helper/microtasks_scope.cc
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/gin_helper/trackable_object.cc
  shell/common/node_bindings.cc
  shell/common/process_util.cc
  shell/common/process_util.h
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/eval.js
Labels: backport, semver/patch, 22-x-y

#38148 chore: add ocr scaffolding to pdf viewer
  filenames.gni
  shell/browser/extensions/api/BUILD.gn
  shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.cc
  shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.h
  shell/browser/extensions/api/resources_private/resources_private_api.cc
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/_permission_features.json
  shell/common/extensions/api/pdf_viewer_private.idl
  shell/common/extensions/electron_extensions_api_provider.cc
Labels: backport, semver/patch, 25-x-y

#38138 docs: moves icpMain.handle call in tutorial part 3
  docs/tutorial/tutorial-3-preload.md
Labels: documentation :notebook:, semver/patch, target/25-x-y

#38157 fix: falsy transparent shouldn't affect webContents background
  lib/browser/api/web-contents.ts
  shell/browser/web_contents_preferences.cc
  spec/api-browser-window-spec.ts
  spec/guest-window-manager-spec.ts
  spec/lib/screen-helpers.ts
Labels: backport, semver/patch, 25-x-y

#38141 chore: implement `WebContentsDelegate::GetFullscreenState`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/patch, target/25-x-y

#38159 fix: falsy transparent shouldn't affect webContents background
  lib/browser/api/web-contents.ts
  shell/browser/web_contents_preferences.cc
  spec/api-browser-window-spec.ts
  spec/guest-window-manager-spec.ts
  spec/screen-helpers.ts
Labels: backport, semver/patch, 23-x-y

#38166 test: use `await` to call "closeWindow"
  spec/api-web-contents-view-spec.ts
  spec/extensions-spec.ts
Labels: semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y

#38146 fix: `AXManualAccessibility` showing failure
  docs/tutorial/accessibility.md
  shell/browser/mac/electron_application.mm
Labels: backport, semver/patch, 25-x-y

#38172 test: use `await` to call "closeWindow"
  spec/api-web-contents-view-spec.ts
  spec/extensions-spec.ts
Labels: backport, semver/none, 22-x-y

#38174 test: use `await` to call "closeWindow"
  spec/api-web-contents-view-spec.ts
  spec/extensions-spec.ts
Labels: backport, semver/none, 25-x-y

#38173 test: use `await` to call "closeWindow"
  spec/api-web-contents-view-spec.ts
  spec/extensions-spec.ts
Labels: backport, semver/none, 24-x-y

#38171 test: use `await` to call "closeWindow"
  spec/api-web-contents-view-spec.ts
  spec/extensions-spec.ts
Labels: backport, semver/none, 23-x-y

#38168 chore: stop using a `RenderWidgetHost` observer in `FileSelectHelper`
  shell/browser/file_select_helper.cc
  shell/browser/file_select_helper.h
Labels: semver/patch, target/25-x-y

#38153 feat: `net.resolveHost`
  docs/api/net.md
  lib/browser/api/net.ts
Labels: backport, semver/minor, backport/approved ✅, 24-x-y

#38152 feat: `net.resolveHost`
  docs/api/net.md
  lib/browser/api/net.ts
Labels: backport, semver/minor, backport/requested 🗳, 25-x-y

#38188 docs: fix typing of session.setDevicePermissionHandler
  docs/api/session.md
  docs/tutorial/devices.md
Labels: documentation :notebook:, semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38194 build: force LF checkout of more files
  .gitattributes
Labels: semver/none, target/23-x-y, target/24-x-y, target/25-x-y

#38193 test: disable flaky asar worker test on ASan build
  spec/asar-spec.ts
Labels: semver/none, no-backport

#38187 docs: update dead link to Apple Human Interface notification guidelines
  docs/tutorial/notifications.md
Labels: documentation :notebook:, semver/patch, target/24-x-y, target/25-x-y

#38186 ci: do conditional in blocked/need-repro workflows at job level
  .github/workflows/issue-commented.yml
  .github/workflows/issue-labeled.yml
Labels: semver/none, no-backport

#38178 test: enable CircleCI's "re-run failed tests only" feature
  .circleci/config/base.yml
  spec/index.js
Labels: semver/none, no-backport

#38179 chore: fix TrustedTypes policy in `chrome://accessibility`
  shell/browser/ui/webui/accessibility_ui.cc
Labels: semver/patch, target/25-x-y

#38181 ci: automate release label tasks
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#38201 build: add pretest script to create TS definitions
  package.json
Labels: semver/none, no-backport

#38191 chore: migrate to @electron/lint-roller for Markdown linting
  .markdownlint.json
  package.json
  script/lib/markdown.ts
  script/lint-docs-links.ts
  script/markdownlint-emd001.js
  yarn.lock
Labels: semver/none, target/23-x-y, target/24-x-y, target/25-x-y

#38212 build: fix CRLF endings in messages.json
  spec/fixtures/extensions/chrome-i18n/_locales/en/messages.json
Labels: fast-track 🚅, semver/none, no-backport

#38199 chore: cherry-pick d42c3e5fb7c3 from chromium
  patches/chromium/.patches
  patches/chromium/wayland_ensure_dnd_buffer_size_is_a_multiple_of_scale.patch
Labels: semver/patch, backport-check-skip

#38142 fix: handle `AXManualAccessibility` attribute cross-protocol
  shell/browser/mac/electron_application.mm
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38221 refactor: remove IPC from `mouse_util`
  filenames.gni
  shell/browser/api/electron_api_web_contents.cc
  shell/common/mouse_util.cc
  shell/common/mouse_util.h
Labels: backport, semver/patch, 24-x-y

#38222 chore: stop using a `RenderWidgetHost` observer in `FileSelectHelper`
  shell/browser/file_select_helper.cc
  shell/browser/file_select_helper.h
Labels: backport, semver/patch, 25-x-y

#38223 fix: handle `AXManualAccessibility` attribute cross-protocol
  shell/browser/mac/electron_application.mm
Labels: backport, semver/patch, 25-x-y

#38224 fix: handle `AXManualAccessibility` attribute cross-protocol
  shell/browser/mac/electron_application.mm
Labels: backport, semver/patch, 24-x-y

#38225 fix: handle `AXManualAccessibility` attribute cross-protocol
  shell/browser/mac/electron_application.mm
Labels: backport, semver/patch, 23-x-y

#38226 docs: update dead link to Apple Human Interface notification guidelines
  docs/tutorial/notifications.md
Labels: backport, semver/patch, 25-x-y

#38227 docs: update dead link to Apple Human Interface notification guidelines
  docs/tutorial/notifications.md
Labels: backport, semver/patch, 24-x-y

#38228 docs: fix typing of `session.setDevicePermissionHandler`
  docs/api/session.md
  docs/tutorial/devices.md
Labels: backport, semver/patch, 24-x-y

#38230 fix: printing crash when settings invalid
  patches/chromium/printing.patch
Labels: backport, semver/patch, 25-x-y

#38235 build: revert builtins PGO logging file changes
  patches/v8/.patches
  patches/v8/build_revert_builtins_pgo.patch
Labels: fast-track 🚅, backport-check-skip, semver/none, 25-x-y

#38237 build: handle duplex option for Node 18 MacOS upload
  package.json
Labels: backport-check-skip, semver/none, 25-x-y

#38250 build: fix octokit resolution with patch-package
  package.json
  patches_npm/@octokit+request+6.2.3.patch
  yarn.lock
Labels: fast-track 🚅, semver/none, no-backport

#38252 build: disable v8 builtins pgo
  build/args/all.gn
Labels: fast-track 🚅, semver/none, target/25-x-y

#38232 refactor: use standard naming for enum class values
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: semver/patch, no-backport

#38279 docs: fix typing of session.setDevicePermissionHandler
  docs/api/session.md
  docs/tutorial/devices.md
Labels: backport, semver/patch, 23-x-y

#38280 chore: migrate to @electron/lint-roller for Markdown linting
  .markdownlint.json
  package.json
  script/lib/markdown.ts
  script/lint-docs-links.ts
  script/markdownlint-emd001.js
  yarn.lock
Labels: backport, semver/none, 25-x-y

#38260 chore: fix lint:js-in-markdown script
  docs/api/app.md
  docs/api/client-request.md
  docs/api/menu.md
  docs/api/session.md
  docs/api/system-preferences.md
  docs/api/web-contents.md
  docs/fiddles/features/web-serial/main.js
  docs/fiddles/features/web-usb/main.js
  docs/fiddles/ipc/pattern-2/main.js
  docs/tutorial/automated-testing.md
  docs/tutorial/code-signing.md
  docs/tutorial/devtools-extension.md
  docs/tutorial/ipc.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/macos-dock.md
  docs/tutorial/notifications.md
  docs/tutorial/process-model.md
  docs/tutorial/represented-file.md
  docs/tutorial/security.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-5-packaging.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
  package.json
  yarn.lock
Labels: semver/none, target/24-x-y, target/25-x-y

#38210 feat: add missing 'cursor-changed' type values
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/minor, api-review/approved ✅, target/25-x-y

#38249 fix: variable name should comply with naming convention
  build/generate_node_defines.py
Labels: semver/none, no-backport

#38259 build: drop python2 from CI
  .circleci/config/base.yml
  script/verify-chromedriver.py
Labels: semver/none, no-backport

#38248 chore: remove unnecessary spellchecker revert patch
  patches/chromium/.patches
  patches/chromium/revert_spellcheck_fully_launch_spell_check_delayed_initialization.patch
  shell/browser/feature_list.cc
Labels: new-pr 🌱, semver/none, no-backport

#38163 feat: support Mica/Acrylic on Windows
  docs/api/browser-window.md
  docs/api/structures/browser-window-options.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: semver/minor, api-review/approved ✅, target/24-x-y, target/25-x-y

#38300 chore: fix lint:js-in-markdown script
  docs/api/app.md
  docs/api/client-request.md
  docs/api/menu.md
  docs/api/session.md
  docs/api/system-preferences.md
  docs/api/web-contents.md
  docs/fiddles/features/web-serial/main.js
  docs/fiddles/features/web-usb/main.js
  docs/fiddles/ipc/pattern-2/main.js
  docs/tutorial/automated-testing.md
  docs/tutorial/code-signing.md
  docs/tutorial/devtools-extension.md
  docs/tutorial/ipc.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/macos-dock.md
  docs/tutorial/notifications.md
  docs/tutorial/process-model.md
  docs/tutorial/represented-file.md
  docs/tutorial/security.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-5-packaging.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
  package.json
  yarn.lock
Labels: backport, semver/none, 25-x-y

#38291 fix: `isMaximized` after minimize/fullscreen on macOS
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, new-pr 🌱, target/23-x-y, target/24-x-y, target/25-x-y

#38241 fix: enable `BrowserWindow.id` access post-destruction
  lib/browser/api/browser-window.ts
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38297 test: prewarm Node headers cache if specifying Electron version
  script/spec-runner.js
  spec/package.json
Labels: backport, semver/none, 25-x-y

#38242 fix: unify `BrowserWindow.isVisible()` logic cross-platform
  docs/api/browser-window.md
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38298 test: prewarm Node headers cache if specifying Electron version
  script/spec-runner.js
  spec/package.json
Labels: backport, semver/none, 24-x-y

#38312 build: bump brew cache to v6
  .circleci/config/base.yml
Labels: semver/none, target/23-x-y, target/25-x-y

#38294 chore: remove obsoleted `DecrementCapturerCount` patch
  patches/chromium/.patches
  patches/chromium/fix_expose_decrementcapturercount_in_web_contents_impl.patch
Labels: semver/none, target/23-x-y, target/24-x-y, target/25-x-y

#38251 test: re-enable tests that aren't broken & remove old test
  spec/api-protocol-spec.ts
  spec/disabled-tests.json
  spec/version-bump-spec.ts
Labels: semver/none, no-backport

#38282 chore: migrate to @electron/lint-roller for Markdown linting
  .markdownlint.json
  package.json
  script/lib/markdown.ts
  script/lint-docs-links.ts
  script/markdownlint-emd001.js
  yarn.lock
Labels: backport, semver/none, 24-x-y

#38271 chore: cherry-pick 81d7b3e6138c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-81d7b3e6138c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 24-x-y

#38302 chore: add smoke test for `devtools-open-url`
  spec/ts-smoke/electron/main.ts
Labels: semver/none, no-backport

#38299 test: prewarm Node headers cache if specifying Electron version
  script/spec-runner.js
  spec/package.json
Labels: backport, semver/none, 23-x-y

#38323 chore: cherry-pick e6e23ba00379 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-48a136e77e6d.patch
  patches/chromium/cherry-pick-e6e23ba00379.patch
Labels: semver/patch, backport-check-skip, main, target/25-x-y

#38316 build: remove V8 ARM undefined symbol patch
  patches/v8/.patches
  patches/v8/workaround_an_undefined_symbol_error.patch
Labels: semver/none, no-backport

#38234 fix: `win.isMaximized()` for transparent windows on Windows
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38273 chore: cherry-pick 81d7b3e613 from chromium
  patches/chromium/.patches
  patches/chromium/m112_cherry_pick_libxml_cve_fix.patch
Labels: security 🔒, semver/patch, backport-check-skip, 23-x-y

#38218 fix: `getNormalBounds()` for transparent windows on Windows
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38337 docs: update example to use app.whenReady()
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#38351 build: modify `gclient.py` with unified patch
  .circleci/config/base.yml
Labels: semver/none, target/24-x-y, target/25-x-y

#38276 chore: cherry-pick cf90db14f2 from chromium
  patches/chromium/.patches
  patches/chromium/m112_fix_scopedobservation_uaf_in.patch
Labels: security 🔒, semver/patch, backport-check-skip, 23-x-y

#38375 docs: fix typing of message box type value
  docs/api/dialog.md
  spec/api-dialog-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: backport, semver/patch, 24-x-y

#38361 feat: support Mica/Acrylic on Windows
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: backport, semver/minor, backport/approved ✅, 24-x-y

#38293 chore: eliminate a few uses of base::AdaptCallbackForRepeating()
  shell/browser/api/electron_api_session.cc
  shell/browser/bluetooth/electron_bluetooth_delegate.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/usb/usb_chooser_controller.cc
Labels: semver/patch, no-backport

#38346 build: use @octokit/request v6.2.4
  package.json
  patches_npm/@octokit+request+6.2.3.patch
Labels: semver/none, target/25-x-y

#38378 docs: update timelines for E26
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#38357 feat: support Mica/Acrylic on Windows
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: backport, semver/minor, backport/approved ✅, 25-x-y

#38329 chore: cherry-pick 8 changes from Release-1-M113
  patches/angle/.patches
  patches/angle/cherry-pick-d0ee0197ddff.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-48785f698b1c.patch
  patches/chromium/cherry-pick-675562695049.patch
  patches/chromium/cherry-pick-d6272b794cbb.patch
  patches/v8/.patches
  patches/v8/cherry-pick-b8020e1973d7.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#38376 docs: fix typing of message box type value
  docs/api/dialog.md
  spec/api-dialog-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: backport, backport-check-skip, semver/none, 23-x-y

#38391 build: try removing V8 symbol export patch for Windows
  patches/v8/.patches
  patches/v8/export_symbols_needed_for_windows_build.patch
Labels: semver/none, no-backport

#38373 docs: disablewebsecurity on webview-tag can not be changed for an active session
  docs/api/webview-tag.md
Labels: documentation :notebook:, semver/none, target/23-x-y, target/24-x-y, target/25-x-y

#38400 build: fixup patches
  patches/chromium/.patches
  patches/chromium/cherry-pick-48785f698b1c.patch
  patches/chromium/cherry-pick-675562695049.patch
  patches/chromium/cherry-pick-d6272b794cbb.patch
  patches/v8/.patches
  patches/v8/cherry-pick-b8020e1973d7.patch
Labels: fast-track 🚅, backport-check-skip, semver/none, 25-x-y

#38403 fix: `dangling_raw_ptr` warning in `electron_api_web_contents`
  shell/browser/api/electron_api_web_contents.h
Labels: semver/patch, target/25-x-y

#38281 build: disable v8 builtins pgo
  build/args/all.gn
  patches/v8/.patches
  patches/v8/build_revert_builtins_pgo.patch
Labels: backport, semver/none, 25-x-y

#38404 chore: remove dead draggable region code
  shell/browser/ui/drag_util.cc
  shell/browser/ui/drag_util.h
  shell/browser/ui/inspectable_web_contents_view_mac.mm
Labels: semver/none, no-backport

#38420 build: remove unused enable_tts build flag
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  shell/common/api/features.cc
  spec/chromium-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/none, no-backport

#38422 build: update yarn.lock
  yarn.lock
Labels: semver/none, target/25-x-y

#38390 fix: `MediaDevices` missing `DisplayMediaInformation`
  shell/browser/electron_browser_context.cc
  spec/api-media-handler-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y

#38410 refactor: cleanup global variable declarations
  lib/isolated_renderer/init.ts
  lib/sandboxed_renderer/init.ts
  typings/internal-ambient.d.ts
Labels: semver/none, no-backport

#38421 build: fix build with "enable_pdf_viewer=false"
  BUILD.gn
  filenames.gni
Labels: semver/none, target/25-x-y

#38419 build: remove unused enable_color_chooser build flag
  buildflags/BUILD.gn
  buildflags/buildflags.gni
Labels: semver/none, no-backport

#38412 build: remove enable_desktop_capturer flag
  BUILD.gn
  build/webpack/webpack.config.base.js
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  chromium_src/BUILD.gn
  filenames.gni
  lib/browser/api/module-list.ts
  shell/browser/api/electron_api_base_window.cc
  shell/common/api/features.cc
  shell/common/node_bindings.cc
  spec/api-browser-window-spec.ts
  spec/api-desktop-capturer-spec.ts
  spec/api-media-handler-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/none, no-backport

#38416 docs: ensure `app.md` examples are runnable
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/24-x-y, target/25-x-y

#38435 build: upgrade @electron/github-app-auth to 2.0.0
  package.json
  yarn.lock
Labels: semver/none, target/25-x-y

#38442 refactor: remove InspectableWebContents::GetAll()
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, new-pr 🌱, no-backport

#38468 fix: Windows FrameView always appearing inactive
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: semver/patch, new-pr 🌱, target/25-x-y

#38452 chore: `process.mainModule` -> `require.main`
  script/yarn.js
Labels: semver/none, target/24-x-y, target/25-x-y

#38450 build: make ReactiveObjC/Mantle deps format consistent
  DEPS
Labels: semver/none, target/24-x-y, target/25-x-y

#38443 refactor: prefer base::Contains() over find() + end()
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_power_save_blocker.cc
  shell/browser/api/electron_api_power_save_blocker.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/native_window.cc
  shell/browser/native_window_views.cc
  shell/browser/printing/print_view_manager_electron.cc
  shell/browser/ui/message_box_win.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_bindings.cc
  shell/common/key_weak_map.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: semver/patch, target/24-x-y, target/25-x-y

#38458 refactor: use literals instead of new RegExp() where possible
  script/prepare-appveyor.js
  script/release/prepare-release.js
Labels: semver/none, no-backport

#38472 chore: upgrade to eslint v8
  lib/browser/api/touch-bar.ts
  lib/browser/ipc-main-impl.ts
  lib/browser/message-port-main.ts
  lib/renderer/web-view/web-view-attributes.ts
  lib/renderer/web-view/web-view-impl.ts
  lib/utility/parent-port.ts
  package.json
  spec/lib/spec-helpers.ts
  yarn.lock
Labels: semver/none, no-backport

#38460 fix: DCHECK minimizing parent window with non-modal child
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38490 chore: cherry-pick 0e1cc35 from v8
  patches/v8/.patches
  patches/v8/fix_set_proper_instruction_start_for_builtin.patch
Labels: semver/patch, new-pr 🌱, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y

#38505 build: shrink unnecessary test changes in patch revert
  patches/boringssl/revert_track_ssl_error_zero_return_explicitly.patch
Labels: semver/none, target/24-x-y, target/25-x-y

#38488 chore: make `contentTracing.stopRecording()` failure clearer
  shell/browser/api/electron_api_content_tracing.cc
  spec/api-content-tracing-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38506 build: combine and elaborate on exposed `BoringSSL` ciphers
  patches/boringssl/.patches
  patches/boringssl/expose_aes-cfb.patch
  patches/boringssl/expose_blowfish_ciphers.patch
  patches/boringssl/expose_des-ede3.patch
  patches/boringssl/feat_expose_several_extra_cipher_functions.patch
  patches/boringssl/fix_sync_evp_get_cipherbynid_and_evp_get_cipherbyname.patch
Labels: semver/none, target/24-x-y, target/25-x-y

#38491 fix: `navigator.connection` not working as intended
  shell/browser/browser_process_impl.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_browser_main_parts.cc
  spec/chromium-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y

#38528 ci: set description for release labels
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#38497 refactor: remove unused switches
  shell/common/electron_constants.cc
  shell/common/electron_constants.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38469 docs: fix performance tutorial
  docs/tutorial/performance.md
Labels: documentation :notebook:, semver/patch
