Repository electron/electron, pull requests merged in 2023-07, with the labels that each got.

#38629 ci: automate release board creation
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#38666 docs: Improved the Documentation on BrowserWindow type attribute
  docs/api/structures/browser-window-options.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#38949 chore: cherry-pick 4 changes from Release-3-M114
  patches/chromium/.patches
  patches/chromium/cherry-pick-85beff6fd302.patch
  patches/chromium/m114_webcodecs_fix_crash_when_changing_temporal_layer_count_in_av1.patch
  patches/v8/.patches
  patches/v8/merged_compiler_stackcheck_can_have_side_effects.patch
  patches/v8/merged_runtime_set_instance_prototypes_directly_on_maps.patch
  patches/v8/utf-8_q_shared-struct_20fix_20using_20shared_20objects_20as.patch
  patches/webrtc/.patches
  patches/webrtc/m114_sdp_reject_duplicate_ssrcs_in_ssrc-groups.patch
Labels: security 🔒, semver/patch, backport-check-skip, 22-x-y

#38981 revert: compensate for title bar height when setting bounds on `BrowserView`
  shell/browser/native_browser_view_mac.mm
  spec/api-browser-view-spec.ts
Labels: semver/patch, target/25-x-y, target/26-x-y

#38996 fix: webview crash when removing in close event
  shell/browser/api/electron_api_web_contents.cc
  spec/fixtures/crash-cases/webview-remove-on-wc-close/index.html
  spec/fixtures/crash-cases/webview-remove-on-wc-close/index.js
  spec/fixtures/crash-cases/webview-remove-on-wc-close/webview.html
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38998 fix: menu border being created properly on Windows 11
  patches/chromium/fix_crash_on_nativetheme_change_during_context_menu_close.patch
Labels: semver/patch, target/25-x-y, target/26-x-y

#38997 fix: Notification 'Show' button visible when no actions exist
  shell/browser/notifications/mac/cocoa_notification.mm
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#39011 build: disable unneeded depot_tools update on Windows CI
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38965 feat: add `BrowserWindow.showAllTabs()` for macOS
  docs/api/browser-window.md
  docs/api/menu-item.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_menu_controller.mm
  spec/api-browser-window-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#39006 fix: set prototype names on `gin::Constructible` classes
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_view.h
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_helper/constructible.h
  shell/common/gin_helper/event.h
  spec/api-browser-view-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-menu-spec.ts
  spec/api-notification-spec.ts
  spec/api-tray-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38990 docs: add link to Travis CI headless page
  docs/tutorial/testing-on-headless-ci.md
Labels: documentation :notebook:, semver/none, no-backport

#39003 fix: remove types from GTK CSS selectors
  shell/browser/ui/views/client_frame_view_linux.cc
Labels: semver/patch, target/25-x-y, target/26-x-y

#38833 fix: use StartUpdating method for PipeWire capturer
  patches/chromium/desktop_media_list.patch
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_desktop_capturer.h
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38943 feat: `browserWindow.getBrowserViews()` to return sorted by z-index array
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  spec/api-browser-view-spec.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#39048 fix: `protocol.handle` not intercepting file protocol
  lib/browser/api/protocol.ts
  spec/api-protocol-spec.ts
Labels: semver/patch, target/25-x-y, target/26-x-y

#39041 docs: updated the markup tag i with the em
  docs/fiddles/native-ui/notifications/basic-notification/index.html
  docs/fiddles/windows/manage-windows/create-frameless-window/index.html
Labels: documentation :notebook:, semver/patch, no-backport

#39034 fix: `BrowserWindow.moveAbove()` not working for child windows
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#39058 perf: avoid redundant map lookup in NativeImage::GetHICON()
  shell/common/api/electron_api_native_image.cc
Labels: performance :checkered_flag:, semver/patch, target/26-x-y

#39059 perf: avoid redundant lookup in BluetoothChooser::AddOrUpdateDevice()
  shell/browser/lib/bluetooth_chooser.cc
Labels: semver/patch, target/26-x-y

#38873 feat: expose safestorage backend information on linux
  docs/api/safe-storage.md
  shell/browser/api/electron_api_safe_storage.cc
  shell/browser/browser_process_impl.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/system_network_context_manager.cc
  spec/api-safe-storage-spec.ts
  spec/fixtures/api/safe-storage/decrypt-app/main.js
  spec/fixtures/api/safe-storage/encrypt-app/main.js
Labels: semver/minor, api-review/approved ✅, target/24-x-y, target/25-x-y

#39069 fix: `clipboard.readImage()` should be synchronous
  shell/common/api/electron_api_clipboard.cc
Labels: semver/patch, target/26-x-y

#39099 fix: menu border being created properly on Windows 11
  patches/chromium/fix_crash_on_nativetheme_change_during_context_menu_close.patch
Labels: backport, semver/patch, 25-x-y

#39100 fix: `navigator.connection` not working as intended
  shell/browser/browser_process_impl.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_browser_main_parts.cc
  spec/chromium-spec.ts
Labels: backport, semver/patch, 24-x-y

#39083 docs: fix a capitalization problem in messagePort tutorial
  docs/tutorial/message-ports.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#38754 fix: `window.open` causing occasional Node.js crashes
  patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
  spec/chromium-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#39097 fix: file selection when disallowed on macOS
  shell/browser/ui/file_dialog_mac.mm
Labels: backport, semver/patch, 24-x-y

#39096 fix: file selection when disallowed on macOS
  shell/browser/ui/file_dialog_mac.mm
Labels: backport, semver/patch, 25-x-y

#39095 fix: `webContents.print({ silent: true })` not working correctly
  patches/chromium/printing.patch
Labels: backport, semver/patch, 25-x-y

#38901 refactor: use `Date.now()` instead of `+new Date()`
  spec/api-content-tracing-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-session-spec.ts
  spec/lib/spec-helpers.ts
Labels: semver/none, no-backport

#39138 build: fixup Codespaces build-tools setup
  .devcontainer/on-create-command.sh
Labels: semver/none, target/24-x-y, target/25-x-y, target/26-x-y

#39123 build: correct codespaces devcontainer extensions settings
  .devcontainer/devcontainer.json
Labels: semver/none, target/25-x-y, target/26-x-y

#39119 chore: revert 459fe0e from 26-x-y
  docs/api/safe-storage.md
  shell/browser/api/electron_api_safe_storage.cc
  shell/browser/browser_process_impl.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/system_network_context_manager.cc
  spec/api-safe-storage-spec.ts
  spec/fixtures/api/safe-storage/decrypt-app/main.js
  spec/fixtures/api/safe-storage/encrypt-app/main.js
Labels: fast-track 🚅, backport-check-skip, semver/none, 26-x-y

#39057 perf: small perf changes in HidChooserController
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/hid/hid_chooser_controller.h
Labels: semver/patch, target/26-x-y

#39152 docs: fix casing of _Deprecated_
  docs/api/system-preferences.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#39137 build: fix Appveyor test workflow checkout
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/24-x-y, target/25-x-y, target/26-x-y

#39066 chore: bump node 18.16.1 (26-x-y)
  DEPS
  patches/node/.patches
  patches/node/build_add_gn_build_files.patch
  patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/node/fix_crypto_tests_to_run_with_bssl.patch
  patches/node/fix_wunreachable-code_warning_in_ares_init_rand_engine.patch
  patches/node/pass_all_globals_through_require.patch
  patches/node/refactor_allow_embedder_overriding_of_internal_fs_calls.patch
Labels: backport, semver/patch, 26-x-y

#39133 docs: remove redundant IPC event sections
  docs/api/ipc-main.md
  docs/api/ipc-renderer.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#39091 feat: deprecate `ipcRenderer.sendTo()`
  docs/api/ipc-renderer.md
  docs/api/structures/ipc-renderer-event.md
  docs/breaking-changes.md
  filenames.auto.gni
  lib/renderer/api/ipc-renderer.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#39178 ci: don't set column for draft issues on new project board
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#39177 docs: update binding linking example in creating API doc
  docs/development/creating-api.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#39111 fix: use generic capturer to list both screens and windows when possible
  patches/chromium/.patches
  patches/chromium/fix_use_delegated_generic_capturer_when_available.patch
  shell/browser/api/electron_api_desktop_capturer.cc
Labels: semver/patch, target/26-x-y

#39195 refactor: replace .indexOf() with .includes()
  lib/browser/api/menu.ts
  script/release/prepare-release.js
  script/release/release.js
  spec/api-menu-spec.ts
  spec/security-warnings-spec.ts
Labels: semver/patch, no-backport

#39187 docs: fill in Node.js version for v25 release
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#39175 docs: update @electron/fuses code examples
  docs/tutorial/asar-integrity.md
  docs/tutorial/fuses.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#39162 docs: update window-open.md to include target
  docs/api/window-open.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y

#38868 feat: add `senderIsMainFrame` to messages sent via `ipcRenderer.sendTo()`
  docs/api/structures/ipc-renderer-event.md
  lib/renderer/common-init.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/electron_api_ipc_handler_impl.cc
  shell/common/api/api.mojom
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_api_service_impl.h
  spec/api-ipc-renderer-spec.ts
  spec/fixtures/module/preload-ipc-ping-pong.js
Labels: semver/minor, api-review/approved ✅, target/24-x-y, target/25-x-y, target/26-x-y

#39180 docs: document `idleDetector` permissions
  docs/api/session.md
  spec/chromium-spec.ts
  spec/fixtures/pages/button.html
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#39211 docs: update window-open.md to include target
  docs/api/window-open.md
Labels: backport, semver/patch, 25-x-y

#39210 ci: fail appveyor build if artifacts are missing
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#39209 refactor: use `TypeError` instead of generic `Error` when appropriate
  lib/browser/api/auto-updater/auto-updater-win.ts
  lib/browser/api/touch-bar.ts
  lib/browser/api/utility-process.ts
  lib/browser/api/web-contents.ts
  lib/browser/api/web-frame-main.ts
  lib/browser/ipc-main-impl.ts
  lib/renderer/web-view/guest-view-internal.ts
  script/release/uploaders/upload-to-github.ts
  spec/lib/video-helpers.js
Labels: semver/patch, no-backport

#39086 fix: `resizable: false` should disable fullscreen button at start
  shell/browser/native_window.cc
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#39225 fix: traffic lights not working when child windows are restored via parent window
  shell/browser/ui/cocoa/electron_ns_window_delegate.h
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: semver/patch, new-pr 🌱, target/24-x-y, target/25-x-y, target/26-x-y

#39236 fix: asar integration for require('node:child_process')
  lib/asar/fs-wrapper.ts
  spec/asar-spec.ts
Labels: backport, semver/patch, 24-x-y

#39235 fix: asar integration for require('node:child_process')
  lib/asar/fs-wrapper.ts
  spec/asar-spec.ts
Labels: backport, semver/patch, 25-x-y

#39234 fix: asar integration for require('node:child_process')
  lib/asar/fs-wrapper.ts
  spec/asar-spec.ts
Labels: backport, semver/patch, 26-x-y

#39194 fix: delete desktop capturers when they're not needed
  patches/webrtc/.patches
  patches/webrtc/fix_mark_pipewire_capturer_as_failed_after_session_is_closed.patch
  shell/browser/api/electron_api_desktop_capturer.cc
Labels: semver/patch, target/25-x-y, target/26-x-y

#39062 fix: reparenting after `BrowserWindow.destroy()`
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/25-x-y, target/26-x-y

#39247 fix: do not resolve electron entrypoints on disk
  patches/node/.patches
  patches/node/fix_do_not_resolve_electron_entrypoints.patch
Labels: fast-track 🚅, semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#39232 refactor: use optional catch binding
  spec/api-app-spec.ts
  spec/api-auto-updater-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-debugger-spec.ts
  spec/api-net-log-spec.ts
  spec/api-process-spec.ts
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/fixtures/api/default-menu/main.js
  spec/fixtures/module/echo-renamed.js
  spec/webview-spec.ts
Labels: semver/none, no-backport

#39223 fix: `pageVisibility` state when `backgroundThrottling` disabled
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/extend_apply_webpreferences.patch
  spec/api-browser-window-spec.ts
  spec/disabled-tests.json
  spec/fixtures/pages/visibilitychange.html
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#39258 docs: fix some string union type
  docs/api/desktop-capturer.md
  docs/api/native-image.md
  docs/api/session.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  spec/api-session-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: documentation :notebook:, semver/patch, target/26-x-y

#39262 chore: update @electron/lint-roller and improve doc type checks
  docs/development/creating-api.md
  docs/tutorial/context-isolation.md
  docs/tutorial/ipc.md
  docs/tutorial/message-ports.md
  package.json
  yarn.lock
Labels: semver/none, target/26-x-y

#39233 refactor: throw errors directly in async functions
  lib/browser/api/web-contents.ts
  lib/common/deprecate.ts
  spec/api-app-spec.ts
Labels: semver/patch, no-backport

#39266 chore: cherry-pick 4 changes from Release-0-M115
  patches/chromium/.patches
  patches/chromium/cherry-pick-aa23556ff213.patch
  patches/chromium/cherry-pick-c60a1ab717c7.patch
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#39296 fix: skip artifact validation for doc-only PRs
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#39298 fix: `pageVisibility` state when `backgroundThrottling` disabled
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/extend_apply_webpreferences.patch
  spec/api-browser-window-spec.ts
  spec/disabled-tests.json
  spec/fixtures/pages/visibilitychange.html
Labels: backport, semver/patch, 26-x-y

#39299 fix: `pageVisibility` state when `backgroundThrottling` disabled
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/extend_apply_webpreferences.patch
  spec/api-browser-window-spec.ts
  spec/disabled-tests.json
  spec/fixtures/pages/visibilitychange.html
Labels: backport, semver/patch, 25-x-y

#39297 fix: reparenting after `BrowserWindow.destroy()`
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: backport, semver/patch, target/24-x-y, target/25-x-y, 26-x-y

#39264 chore: cherry-pick 8fcc6df from webrtc
  patches/webrtc/.patches
  patches/webrtc/pipewire_capturer_increase_buffer_size_to_avoid_buffer_overflow.patch
Labels: semver/patch, backport-check-skip
