Repository electron/electron, pull requests merged in 2023-10, with the labels that each got.

#40038 chore: update extensions url handling to match upstream
  shell/browser/extensions/api/tabs/tabs_api.cc
  spec/extensions-spec.ts
  spec/fixtures/extensions/chrome-tabs/api-async/background.js
Labels: semver/patch, in-flight/26-x-y, in-flight/27-x-y

#39956 chore: remove deprecated `app.runningUnderRosettaTranslation()`
  docs/api/app.md
  docs/breaking-changes.md
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_app_mac.mm
  spec/ts-smoke/electron/main.ts
Labels: semver/major, new-pr 🌱, api-review/requested 🗳, no-backport, deprecation-review/complete ✅

#40049 fix: `BroadcastChannel` initialization location
  patches/node/.patches
  patches/node/lib_fix_broadcastchannel_initialization_location.patch
Labels: semver/patch, target/26-x-y, target/27-x-y

#40019 docs: add PipeWire integration instructions for snaps
  docs/tutorial/snapcraft.md
Labels: documentation :notebook:, semver/patch, target/27-x-y

#40053 refactor: replace remaining `NULL` with `nullptr`
  shell/app/electron_main_mac.cc
  shell/browser/api/electron_api_app_mac.mm
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_power_monitor_win.cc
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/browser_process_impl.h
  shell/browser/browser_win.cc
  shell/browser/extensions/electron_extension_message_filter.h
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/file_select_helper.cc
  shell/browser/file_select_helper_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
  shell/browser/notifications/linux/libnotify_notification.cc
  shell/browser/relauncher.cc
  shell/browser/relauncher_mac.cc
  shell/browser/relauncher_win.cc
  shell/browser/ui/certificate_trust_win.cc
  shell/browser/ui/cocoa/electron_bundle_mover.mm
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/file_dialog_win.cc
  shell/browser/ui/message_box_win.cc
  shell/browser/ui/views/electron_views_delegate_win.cc
  shell/browser/ui/win/jump_list.cc
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/ui/win/taskbar_host.cc
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image_win.cc
  shell/common/gin_converters/native_window_converter.h
  shell/common/node_bindings_win.cc
  shell/common/platform_util_mac.mm
  shell/common/platform_util_win.cc
Labels: semver/patch, no-backport

#39980 feat: add `tabbingIdentifier` property to `BrowserWindow`
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/minor, api-review/approved ✅, target/26-x-y, target/27-x-y

#40032 fix: failing build with `enable_electron_extensions=false`
  chromium_src/BUILD.gn
  shell/browser/electron_browser_client.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, target/25-x-y, target/26-x-y, target/27-x-y

#40074 feat: expose app accessibility transparency settings api
  docs/api/system-preferences.md
  shell/browser/api/electron_api_system_preferences.cc
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_system_preferences_mac.mm
  spec/ts-smoke/electron/main.ts
Labels: backport, semver/minor, component/system-preferences, backport/approved ✅, 27-x-y

#40073 feat: expose app accessibility transparency settings api
  docs/api/system-preferences.md
  shell/browser/api/electron_api_system_preferences.cc
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_system_preferences_mac.mm
Labels: backport, semver/minor, backport/approved ✅, 26-x-y

#40070 fix: error using `webcrypto.subtle.importKey()`
  patches/node/.patches
  patches/node/fix_handle_possible_disabled_sharedarraybuffer.patch
Labels: semver/patch, target/27-x-y

#40062 fix: all children showing when showing child window
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y, target/27-x-y

#40079 chore: cherry-pick 2 changes from Release-1-M117
  patches/chromium/.patches
  patches/chromium/cherry-pick-b11e7d07a6f4.patch
  patches/v8/.patches
  patches/v8/cherry-pick-b0ad701a609a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 24-x-y

#40077 chore: cherry-pick 2 changes from Release-1-M117
  patches/chromium/.patches
  patches/chromium/cherry-pick-b11e7d07a6f4.patch
  patches/v8/.patches
  patches/v8/cherry-pick-57d372c3e399.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40090 fix: crashed events deprecation
  lib/browser/api/app.ts
  lib/browser/api/web-contents.ts
  lib/common/deprecate.ts
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y, target/27-x-y

#40091 fix: toggling DevTools while minimized on Windows
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
Labels: semver/patch, target/25-x-y, target/26-x-y, target/27-x-y

#40080 chore: cherry-pick 2 changes from Release-1-M117
  patches/chromium/.patches
  patches/chromium/cherry-pick-b11e7d07a6f4.patch
  patches/v8/.patches
  patches/v8/cherry-pick-b0ad701a609a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 22-x-y

#40101 chore: cherry-pick c03569f from libuv
  patches/node/.patches
  patches/node/win_process_avoid_assert_after_spawning_store_app_4152.patch
Labels: semver/patch, new-pr 🌱, target/25-x-y, target/26-x-y, target/27-x-y

#40078 chore: cherry-pick 3 changes from Release-1-M117
  patches/chromium/.patches
  patches/chromium/cherry-pick-309b604c4e88.patch
  patches/chromium/cherry-pick-b11e7d07a6f4.patch
  patches/v8/.patches
  patches/v8/cherry-pick-b0ad701a609a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#40109 fix: fix vibrancy applying without transparency on MacOS
  shell/browser/native_window.cc
Labels: semver/patch, new-pr 🌱, target/27-x-y

#40088 refactor: eliminate duplicate code
  shell/browser/file_select_helper.cc
  shell/browser/native_window_mac.mm
Labels: semver/patch, no-backport

#40132 test: add back smoke test for removed API
  spec/ts-smoke/electron/main.ts
Labels: semver/none, target/27-x-y

#40124 chore: restore deprecate as an internal module
  filenames.auto.gni
  lib/browser/api/app.ts
  lib/browser/api/crash-reporter.ts
  lib/browser/api/web-contents.ts
  lib/common/api/deprecate.ts
  lib/common/api/module-list.ts
  lib/common/define-properties.ts
  lib/sandboxed_renderer/api/module-list.ts
  spec/api-app-spec.ts
  spec/api-web-contents-spec.ts
  spec/deprecate-spec.ts
  typings/internal-electron.d.ts
Labels: semver/patch, no-backport

#40128 fix: remove EarlyMallocZoneRegistration call
  BUILD.gn
  shell/app/electron_main_mac.cc
Labels: semver/patch, no-backport

#40135 test: fix "crashed event does not crash main process when destroying WebContents in it"
  spec/api-web-contents-spec.ts
Labels: semver/none, target/25-x-y, target/26-x-y, target/27-x-y

#40131 ci: fixup diagnose_goma_log.py call
  .circleci/config/base.yml
Labels: semver/none, target/25-x-y, target/26-x-y, target/27-x-y

#40072 feat: Add 'mouse-enter' and 'mouse-leave' Tray events for Windows.
  docs/api/tray.md
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/ui/win/notify_icon_host.h
Labels: semver/minor, api-review/approved ✅, no-backport

#40138 docs: fix typo in session docs
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, no-backport

#40140 refactor: use gin_helper::Dictionary::CreateEmpty() helper
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_content_tracing.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/bluetooth/electron_bluetooth_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/native_window.cc
  shell/browser/native_window_views.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/file_dialog_gtk.cc
  shell/browser/ui/file_dialog_mac.mm
  shell/browser/ui/file_dialog_win.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_api_shell.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, no-backport

#40143 fix: crash when calling non-reentrant function in `loadURL`
  shell/browser/api/electron_api_web_contents.cc
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y, target/27-x-y

#40158 test: make capturePage color matching timeouts consistent
  spec/api-browser-window-spec.ts
Labels: semver/none, target/25-x-y, target/26-x-y, target/27-x-y

#40154 docs: update dates for E28
  docs/tutorial/electron-timelines.md
Labels: semver/none, target/27-x-y

#40089 chore: formally deprecate `crashed` and `renderer-process-crashed` events
  docs/breaking-changes.md
Labels: semver/none, no-backport, deprecation-review/complete ✅

#39730 fix: `webContents.capturePage()` for hidden windows on Windows/Linux
  shell/browser/api/electron_api_web_contents.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/25-x-y, target/26-x-y, target/27-x-y, target/28-x-y

#40098 fix: store portal restore token under the right source ID
  patches/webrtc/.patches
  patches/webrtc/pipewire_capturer_make_restore_tokens_re-usable_more_than_one_time.patch
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40190 build: remove native specs
  .circleci/config/base.yml
  BUILD.gn
  appveyor-woa.yml
  appveyor.yml
  script/native-test-targets.json
  script/spec-runner.js
Labels: semver/none, no-backport

#40169 chore: formally deprecate `gpu-process-crashed` event
  docs/breaking-changes.md
Labels: semver/none, deprecation-review/complete ✅, target/28-x-y

#40177 docs: update supported Linux versions
  README.md
Labels: documentation :notebook:, semver/patch, no-backport

#40137 docs: rename `renderer.d.ts` in documentation
  docs/tutorial/context-isolation.md
Labels: documentation :notebook:, semver/patch, no-backport

#40180 docs: fix some string union typings
  docs/api/app.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  spec/ts-smoke/electron/main.ts
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y, target/27-x-y, target/28-x-y

#40189 fix: ensure MessagePorts get GCed when not referenced
  patches/chromium/.patches
  patches/chromium/ensure_messageports_get_gced_when_not_referenced.patch
  spec/api-ipc-spec.ts
Labels: semver/patch, target/28-x-y

#40200 refactor: use getter property for RFH
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, no-backport

#40204 docs: fix some string union typings
  docs/api/app.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  spec/ts-smoke/electron/main.ts
Labels: backport, semver/patch, 25-x-y

#40203 docs: fix some string union typings
  docs/api/app.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  spec/ts-smoke/electron/main.ts
Labels: backport, semver/patch, 26-x-y

#40202 docs: fix some string union typings
  docs/api/app.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  spec/ts-smoke/electron/main.ts
Labels: backport, semver/patch, 27-x-y

#40179 fix: incorrect wco bounds in macOS fullscreen
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/25-x-y, target/26-x-y, target/27-x-y, target/28-x-y

#40209 chore: cherry-pick 4 changes from Release-0-M118
  patches/chromium/.patches
  patches/chromium/avoid_allocating_recordid_objects_in_elementtiming_and_lcp.patch
  patches/chromium/cherry-pick-d756d71a652c.patch
  patches/chromium/cherry-pick-f218b4f37018.patch
  patches/chromium/parameterize_axtreeserializer_by_vector_type.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#37244 feat: update `app.{set|get}LoginItemSettings(settings)`
  docs/api/app.md
  shell/browser/api/electron_api_app.cc
  shell/browser/browser.h
  shell/browser/browser_mac.mm
  shell/common/platform_util.h
  shell/common/platform_util_mac.mm
  spec/api-app-spec.ts
Labels: semver/major, api-review/approved ✅, no-backport

#40221 fix: support the throwIfNoEntry option to statSync and lstatSync in asar files
  lib/asar/fs-wrapper.ts
  spec/asar-spec.ts
Labels: semver/patch, new-pr 🌱, target/28-x-y

#40083 docs: Update docs on testing Electron apps with WebdriverIO
  docs/tutorial/automated-testing.md
Labels: documentation :notebook:, semver/patch, target/27-x-y, target/28-x-y

#33981 build: re-enable partition alloc on mac
  patches/chromium/.patches
  patches/chromium/build_disable_partition_alloc_on_mac.patch
Labels: semver/patch, target/28-x-y

#40215 refactor: partition HidDelegate observers by browser context
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/electron_hid_delegate.h
  shell/browser/hid/hid_chooser_context.h
  shell/browser/hid/hid_chooser_controller.h
Labels: semver/patch, target/27-x-y, target/28-x-y

#40197 fix: Windows Toast notification dismissal from Action Center
  docs/api/notification.md
  shell/browser/api/electron_api_notification.cc
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/browser/notifications/win/windows_toast_notification.h
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40233 docs: fix represented file fiddle
  docs/fiddles/features/represented-file/main.js
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/27-x-y, target/28-x-y

#40115 chore: remove deprecated `crashed` and `renderer-process-crashed` events
  docs/api/app.md
  docs/api/web-contents.md
  docs/api/webview-tag.md
  docs/breaking-changes.md
  lib/browser/api/app.ts
  lib/browser/api/web-contents.ts
  lib/browser/web-view-events.ts
  spec/api-app-spec.ts
  spec/api-web-contents-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: semver/major, new-pr 🌱, api-review/requested 🗳, no-backport, deprecation-review/complete ✅

#40222 chore: implement no-op `chrome.action` extension APIs
  filenames.gni
  shell/browser/extensions/api/extension_action/extension_action_api.cc
  shell/browser/extensions/api/extension_action/extension_action_api.h
  shell/browser/extensions/electron_extensions_browser_api_provider.cc
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/action.json
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#39978 fix: correctly track receiver for methods called via ctx bridge
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/renderer_client_base.cc
  spec/webview-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y

#37805 docs: replace the example app using electron
  README.md
Labels: documentation :notebook:, semver/patch, no-backport

#40250 test: fix Node.js color edge snapshot stack traces
  patches/node/.patches
  patches/node/chore_update_fixtures_errors_force_colors_snapshot.patch
  patches/node/test_fix_edge_snapshot_stack_traces.patch
Labels: semver/patch, target/27-x-y, target/28-x-y

#40271 fix: potential crash calling `tray.popUpContextMenu()`
  shell/browser/api/electron_api_tray.cc
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/tray_icon.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
Labels: backport, semver/patch, 25-x-y

#40270 fix: failing build with `enable_electron_extensions=false`
  chromium_src/BUILD.gn
  shell/browser/electron_browser_client.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
  shell/renderer/renderer_client_base.cc
Labels: backport, semver/patch, 25-x-y

#40266 chore: cherry-pick f666cceb92c2 from dawn
  patches/config.json
  patches/dawn/.patches
  patches/dawn/cherry-pick-f666cceb92c2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#40216 chore: Show FIDO devices in the chooser if allowed
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/hid/hid_chooser_context.h
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/hid/hid_chooser_controller.h
Labels: semver/patch, target/27-x-y, target/28-x-y

#40265 chore: cherry-pick f666cceb92c2 from dawn
  patches/config.json
  patches/dawn/.patches
  patches/dawn/cherry-pick-f666cceb92c2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40269 fix: failing build with `enable_electron_extensions=false`
  chromium_src/BUILD.gn
  shell/browser/electron_browser_client.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
  shell/renderer/renderer_client_base.cc
Labels: backport, semver/patch, 26-x-y

#40257 refactor: options parsing in WebContents.prototype.printToPDF()
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
  spec/ts-smoke/electron/main.ts
Labels: semver/patch, target/28-x-y

#40306 test: add spec for `app.getAppMetrics()` for utility process
  spec/api-utility-process-spec.ts
Labels: semver/none, target/27-x-y, target/28-x-y

#40310 test: add spec for `child-process-gone` event for utility process
  docs/api/utility-process.md
  spec/api-utility-process-spec.ts
Labels: backport, semver/none, 25-x-y

#40317 test: add spec for `app.getAppMetrics()` for utility process
  spec/api-utility-process-spec.ts
Labels: backport, semver/none, 27-x-y

#40319 test: add spec for `app.getAppMetrics()` for utility process
  spec/api-utility-process-spec.ts
Labels: backport, semver/none, 26-x-y

#40320 test: add spec for `app.getAppMetrics()` for utility process
  spec/api-utility-process-spec.ts
Labels: backport, semver/none, 25-x-y

#40315 refactor: use non-deprecated `NSKeyedArchiver` APIs
  patches/squirrel.mac/.patches
  patches/squirrel.mac/chore_disable_api_deprecation_warnings_in_nskeyedarchiver.patch
  patches/squirrel.mac/refactor_use_non-deprecated_nskeyedarchiver_apis.patch
Labels: semver/patch, no-backport

#40291 fix: make sure classes in lib correctly implement Electron interfaces
  docs/api/crash-reporter.md
  lib/browser/api/auto-updater/auto-updater-win.ts
  lib/browser/api/crash-reporter.ts
  lib/browser/api/message-channel.ts
  lib/browser/api/power-monitor.ts
  lib/browser/api/share-menu.ts
  lib/browser/api/utility-process.ts
  lib/browser/ipc-main-impl.ts
  lib/browser/message-port-main.ts
  lib/utility/parent-port.ts
  spec/api-autoupdater-darwin-spec.ts
  typings/internal-electron.d.ts
Labels: semver/patch, no-backport

#40332 build: upload slow, more time good
  .circleci/config/base.yml
Labels: semver/none, target/25-x-y, target/26-x-y, target/27-x-y, target/28-x-y

#40308 fix: prevent `PopUpButtonHandler` premature dealloc
  shell/browser/ui/file_dialog_mac.mm
Labels: semver/patch, target/27-x-y, target/28-x-y

#40255 chore: remove deprecated `gpu-process-crashed` event
  docs/api/app.md
  docs/breaking-changes.md
  lib/browser/api/app.ts
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  spec/ts-smoke/electron/main.ts
Labels: semver/major, api-review/approved ✅, no-backport, deprecation-review/complete ✅

#40331 refactor: remove DevTools legacy UI patching
  patches/devtools_frontend/.patches
  patches/devtools_frontend/chore_expose_ui_to_allow_electron_to_set_dock_side.patch
  patches/devtools_frontend/fix_expose_globals_to_allow_patching_devtools_dock.patch
  shell/browser/ui/inspectable_web_contents.cc
  spec/extensions-spec.ts
  spec/webview-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y

#40349 build: fix ":electron_lib_arc" / "chromium_src:chrome_lib_arc" dependencies
  BUILD.gn
  chromium_src/BUILD.gn
Labels: semver/none, target/26-x-y

#40338 docs: add reference to `app.getAppMetrics()` in `serviceName` for `utilityProcess`
  docs/api/utility-process.md
Labels: documentation :notebook:, semver/patch, target/28-x-y

#40368 build: don't rename files in `electron_node/deps/base64`
  patches/node/build_add_gn_build_files.patch
Labels: semver/none, target/27-x-y, target/28-x-y

#40365 fix: `navigator.keyboard.lock()` fullscreen exit handling
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents_mac.mm
  spec/chromium-spec.ts
  spec/fixtures/pages/modal.html
  spec/webview-spec.ts
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40264 build: update @electron/docs-parser and @electron/typescript-definitions
  package.json
  yarn.lock
Labels: semver/patch, no-backport

#40253 feat: configure use remote checksums via rc
  docs/tutorial/installation.md
  npm/install.js
Labels: semver/minor, api-review/approved ✅

#40377 fix: crash when thread isolated pool is enabled in the renderer process
  build/args/all.gn
Labels: semver/patch, backport-check-skip, 26-x-y

#40393 build: actually show github upload output if verbose is true.
  script/release/uploaders/upload.py
Labels: fast-track 🚅, semver/none, target/25-x-y, target/26-x-y, target/27-x-y, target/28-x-y

#40330 refactor: ensure IpcRenderer is not bridgable
  docs/breaking-changes.md
  lib/renderer/api/ipc-renderer.ts
  lib/renderer/ipc-renderer-internal.ts
  spec/fixtures/apps/libuv-hang/preload.js
  spec/fixtures/apps/libuv-hang/renderer.js
Labels: semver/patch, no-backport
