Repository electron/electron, pull requests merged in 2023-12, with the labels that each got.

#40622 docs: add dates for e29
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, backport/requested 🗳, target/28-x-y

#40671 chore: [25-x-y] cherry-pick 2 changes from Release-3-M119
  patches/config.json
  patches/libavif/.patches
  patches/libavif/do_not_store_potentially_invalid_pointers.patch
  patches/libavif/remove_potential_out_of_bound_access_to_alphaitemindices.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#40666 fix: clean up devtools frontend_host on webcontents destroy
  shell/browser/ui/inspectable_web_contents.cc
  spec/api-web-contents-spec.ts
Labels: semver/patch, new-pr 🌱, target/28-x-y

#40650 fix: webview zoom level persistence on navigation
  shell/browser/web_contents_zoom_controller.cc
  spec/fixtures/pages/webview-zoom-change-persist-host.html
  spec/node-spec.ts
  spec/webview-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y

#40690 docs: add E28 support for ESM in tutorial.md
  docs/tutorial/tutorial-2-first-app.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/28-x-y

#40689 chore: cleanup global reject handler leaking into tests
  spec/node-spec.ts
Labels: new-pr 🌱, semver/none, no-backport

#40670 build: update typescript-definitions to 8.15.2
  package.json
  yarn.lock
Labels: semver/none, no-backport

#40598 refactor: move JS dialog handling to JS
  filenames.gni
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_javascript_dialog_manager.cc
  shell/browser/electron_javascript_dialog_manager.h
  shell/browser/web_contents_preferences.cc
  spec/chromium-spec.ts
Labels: semver/patch, no-backport

#40544 feat: enable code cache for custom protocols
  docs/api/protocol.md
  docs/api/session.md
  docs/api/structures/custom-scheme.md
  patches/chromium/.patches
  patches/chromium/feat_allow_code_cache_in_custom_schemes.patch
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_protocol.h
  shell/browser/electron_browser_client.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/renderer_client_base.cc
  spec/api-protocol-spec.ts
  spec/fixtures/apps/refresh-page/main.html
  spec/fixtures/apps/refresh-page/main.js
  spec/fixtures/apps/refresh-page/package.json
Labels: semver/minor, api-review/approved ✅, target/27-x-y, target/28-x-y

#40579 fix: prevent node mode to be used as script runner by other apps
  filenames.gni
  shell/app/node_main.cc
  shell/common/mac/codesign_util.cc
  shell/common/mac/codesign_util.h
  spec/api-autoupdater-darwin-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/lib/codesign-helpers.ts
  spec/node-spec.ts
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40716 ci: roll back the link release project board to repo automation
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#40725 chore: cherry-pick 1 changes from Release-0-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-5fde415e06f9.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40728 docs: fix year typos in electron-timelines.md
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/28-x-y, target/29-x-y

#40446 fix: Update node's simdutf to 3.2.9 to fix AVX-related crashes
  patches/node/.patches
  patches/node/fix_backport_avx_detection_fix_from_simdutf_3_2_9.patch
Labels: semver/patch, backport-check-skip, 26-x-y

#40715 fix: cherry pick 9009d76968b1ec2ed825bc95e47d086ceea07520 from chromium
  patches/chromium/.patches
  patches/chromium/fix_font_flooding_in_dev_tools.patch
Labels: backport, semver/patch, 27-x-y

#40665 fix: wrong default port in docs
  docs/tutorial/debugging-main-process.md
Labels: documentation :notebook:, semver/patch, target/27-x-y, target/28-x-y

#40737 fix: prevent node mode to be used as script runner by other apps
  filenames.gni
  shell/app/node_main.cc
  shell/common/mac/codesign_util.cc
  shell/common/mac/codesign_util.h
  spec/api-autoupdater-darwin-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/lib/codesign-helpers.ts
  spec/node-spec.ts
Labels: backport, semver/patch, 27-x-y

#40746 build: remove font flooding in devtools patch
  patches/chromium/.patches
  patches/chromium/fix_font_flooding_in_dev_tools.patch
Labels: fast-track 🚅, semver/none, no-backport

#40668 chore: cleanup tests creating crashpad handler in the test runner process
  spec/api-crash-reporter-spec.ts
  spec/api-utility-process-spec.ts
Labels: semver/none, no-backport

#40744 build: remove dcheck.patch
  patches/chromium/.patches
  patches/chromium/dcheck.patch
Labels: semver/patch, new-pr 🌱, no-backport

#40703 fix: incorrectly mapped toggleDevTools in custom menu fiddle
  docs/fiddles/menus/customize-menus/main.js
Labels: documentation :notebook:, semver/none, no-backport

#40661 fix: don't reject `loadURL()` promise from `did-fail-load` - use `did-finish-load` instead
  lib/browser/api/web-contents.ts
  spec/api-web-contents-spec.ts
Labels: semver/patch, no-backport

#40724 chore: cherry-pick 1 changes from Release-0-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-5fde415e06f9.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#40738 fix: prevent node mode to be used as script runner by other apps
  filenames.gni
  shell/app/node_main.cc
  shell/common/mac/codesign_util.cc
  shell/common/mac/codesign_util.h
  spec/api-autoupdater-darwin-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/lib/codesign-helpers.ts
  spec/node-spec.ts
Labels: backport, semver/patch, 26-x-y

#40753 fix: save to file option not working in performance tab of devtools
  patches/devtools_frontend/.patches
  patches/devtools_frontend/fix_active_trace_index_when_updating_models.patch
Labels: semver/patch, backport-check-skip, 27-x-y

#40758 ci: re-comment pdb.zip download in appveyor.yml
  appveyor.yml
Labels: semver/none, no-backport

#40757 fix: add partition alloc check for MacOS 13/14+
  patches/chromium/.patches
  patches/chromium/enable_partition_alloc_ref_count_size.patch
Labels: semver/patch, target/28-x-y, target/29-x-y

#40764 docs: corrected the ipcMain import path
  docs/tutorial/tutorial-3-preload.md
Labels: documentation :notebook:, semver/patch, target/29-x-y

#40786 refactor: use a FixedFlatMap for v8 converting ui::MenuSourceType
  shell/common/gin_converters/content_converter.cc
Labels: semver/patch, target/29-x-y

#40806 chore: cherry-pick 1 changes from Release-2-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-8d607d3921b8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 28-x-y

#40808 chore: cherry-pick 1 changes from Release-2-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-8d607d3921b8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40807 chore: cherry-pick 1 changes from Release-2-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-8d607d3921b8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#40803 chore: cherry-pick 6 changes from Release-1-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-021598ea43c1.patch
  patches/chromium/cherry-pick-4ca62c7a8b88.patch
  patches/chromium/cherry-pick-76340163a820.patch
  patches/chromium/cherry-pick-f15cfb9371c4.patch
  patches/libavif/.patches
  patches/libavif/do_not_store_colorproperties_until_alpha_item_is_found.patch
  patches/v8/.patches
  patches/v8/merged_promises_async_stack_traces_fix_the_case_when_the_closure.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y
