Repository electron/electron, pull requests merged in 2023-06, with the labels that each got.

#38498 feat: add USB protected classes handler
  docs/api/session.md
  docs/fiddles/features/web-usb/main.js
  docs/tutorial/devices.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
  shell/browser/usb/electron_usb_delegate.cc
  shell/common/gin_converters/usb_protected_classes_converter.h
Labels: backport, semver/minor, backport/approved ✅, 24-x-y

#38547 build: fix doc-only early exit on Appveyor
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none, target/24-x-y, target/25-x-y, target/26-x-y

#38549 build: drop python2 from CI (#38303)
  .circleci/config/base.yml
  script/verify-chromedriver.py
Labels: backport, fast-track 🚅, semver/none, 23-x-y

#38554 build: drop python2 from CI
  .circleci/config/base.yml
  script/verify-chromedriver.py
Labels: backport, fast-track 🚅, semver/none, 22-x-y

#38537 perf: avoid unnecessary base value clone
  shell/browser/electron_browser_context.cc
  shell/browser/mac/dict_util.mm
  shell/browser/usb/usb_chooser_context.cc
  shell/common/gin_converters/extension_converter.cc
  shell/common/gin_converters/value_converter.cc
  shell/common/gin_converters/value_converter.h
Labels: performance :checkered_flag:, semver/patch, target/25-x-y, target/26-x-y

#38561 chore: remove unused electron::api::View code
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38559 refactor: use direct aggregation in NativeWindowViews
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38568 docs: clarify which electron modules are exposed in sandboxed renderers
  docs/tutorial/sandbox.md
Labels: documentation :notebook:, semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38544 docs: fix SerialPort typing
  docs/api/structures/serial-port.md
Labels: documentation :notebook:, semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38423 chore: type check JS in docs
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/client-request.md
  docs/api/clipboard.md
  docs/api/context-bridge.md
  docs/api/desktop-capturer.md
  docs/api/dialog.md
  docs/api/incoming-message.md
  docs/api/ipc-main.md
  docs/api/ipc-renderer.md
  docs/api/menu.md
  docs/api/message-channel-main.md
  docs/api/net-log.md
  docs/api/protocol.md
  docs/api/session.md
  docs/api/touch-bar.md
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  docs/api/web-frame.md
  docs/api/webview-tag.md
  docs/tutorial/asar-archives.md
  docs/tutorial/asar-integrity.md
  docs/tutorial/automated-testing.md
  docs/tutorial/code-signing.md
  docs/tutorial/context-isolation.md
  docs/tutorial/dark-mode.md
  docs/tutorial/fuses.md
  docs/tutorial/installation.md
  docs/tutorial/ipc.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/launch-app-from-url-in-another-app.md
  docs/tutorial/message-ports.md
  docs/tutorial/multithreading.md
  docs/tutorial/native-file-drag-drop.md
  docs/tutorial/performance.md
  docs/tutorial/process-model.md
  docs/tutorial/quick-start.md
  docs/tutorial/security.md
  docs/tutorial/snapcraft.md
  docs/tutorial/spellchecker.md
  docs/tutorial/tray.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
  docs/tutorial/window-customization.md
  docs/tutorial/windows-taskbar.md
  package.json
  yarn.lock
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38572 chore: remove unused electron::api::View code
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
Labels: backport, semver/patch, target/24-x-y, 25-x-y

#38557 fix: file selection when disallowed on macOS
  shell/browser/ui/file_dialog_mac.mm
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38600 chore: type check JS in docs
  docs/api/app.md
  docs/api/browser-window.md
  docs/api/client-request.md
  docs/api/clipboard.md
  docs/api/context-bridge.md
  docs/api/desktop-capturer.md
  docs/api/dialog.md
  docs/api/incoming-message.md
  docs/api/ipc-main.md
  docs/api/ipc-renderer.md
  docs/api/menu.md
  docs/api/message-channel-main.md
  docs/api/net-log.md
  docs/api/protocol.md
  docs/api/session.md
  docs/api/touch-bar.md
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  docs/api/web-frame.md
  docs/api/webview-tag.md
  docs/tutorial/asar-archives.md
  docs/tutorial/asar-integrity.md
  docs/tutorial/automated-testing.md
  docs/tutorial/code-signing.md
  docs/tutorial/context-isolation.md
  docs/tutorial/dark-mode.md
  docs/tutorial/fuses.md
  docs/tutorial/installation.md
  docs/tutorial/ipc.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/launch-app-from-url-in-another-app.md
  docs/tutorial/message-ports.md
  docs/tutorial/multithreading.md
  docs/tutorial/native-file-drag-drop.md
  docs/tutorial/performance.md
  docs/tutorial/process-model.md
  docs/tutorial/quick-start.md
  docs/tutorial/security.md
  docs/tutorial/snapcraft.md
  docs/tutorial/spellchecker.md
  docs/tutorial/tray.md
  docs/tutorial/tutorial-2-first-app.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
  docs/tutorial/window-customization.md
  docs/tutorial/windows-taskbar.md
  package.json
  yarn.lock
Labels: backport, semver/patch, 24-x-y

#38595 refactor: in NativeWindowViews, aggregate fields directly
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: backport, semver/patch, target/24-x-y, 25-x-y

#38574 refactor: use `process_util.h` helpers
  shell/app/electron_content_client.cc
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/common/node_bindings.cc
  shell/common/process_util.cc
  shell/common/process_util.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38489 fix: account for `BrowserView` bounds in setting autofill popup bounds
  shell/browser/electron_autofill_driver.cc
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38591 build: remove V8 patch for `ArrayBuffer` DCHECK
  patches/v8/.patches
  patches/v8/fix_disable_implies_dcheck_for_node_stream_array_buffers.patch
Labels: semver/none, no-backport

#38596 refactor: remove redundant resizing strategy equality check
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38514 feat: Allow customizing the default math font
  docs/api/structures/web-preferences.md
  shell/browser/web_contents_preferences.cc
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, no-backport

#38622 docs: removed outdated Appveyor doc
  docs/development/azure-vm-setup.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38597 fix: sync api::Screen wrapper method sigs to upstream
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_screen.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38587 fix: validate response in `protocol.handle()`
  lib/browser/api/protocol.ts
  spec/api-protocol-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38612 fix: bad error passing `webContents.print(null)`
  lib/browser/api/web-contents.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38644 build: uuaw @octokit/request to 6.2.5
  yarn.lock
Labels: fast-track 🚅, backport-check-skip, semver/none, 24-x-y

#38645 build: uuaw @octokit/request to 6.2.5
  yarn.lock
Labels: fast-track 🚅, backport-check-skip, semver/none, 23-x-y

#38623 refactor: remove unused OffScreenRenderWidgetHostView fields
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38258 build: use m1 hosts to build apple silicon binaries
  .circleci/config/base.yml
  BUILD.gn
  build/fake_v8_context_snapshot_generator.py
Labels: semver/none, no-backport

#38658 build: improve error output in release.js
  script/release/release.js
Labels: semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38665 build: upgrade @electron/github-app-auth to 2.0.0
  package.json
  yarn.lock
Labels: backport, backport-check-skip, semver/none, 22-x-y

#38655 docs: use local img for contents.adjustSelection api
  docs/api/web-contents.md
  docs/images/web-contents-text-selection-after.png
  docs/images/web-contents-text-selection-before.png
Labels: documentation :notebook:, new-pr 🌱, semver/none, no-backport

#38654 chore: cherry-pick 2 changes from Release-1-M114
  patches/v8/.patches
  patches/v8/cherry-pick-0035a4a8dac2.patch
  patches/v8/cherry-pick-73af1a19a901.patch
Labels: security 🔒, semver/patch, backport-check-skip, 24-x-y

#38652 chore: cherry-pick 2 changes from Release-1-M114
  patches/v8/.patches
  patches/v8/cherry-pick-73af1a19a901.patch
  patches/v8/merged_ic_fix_store_handler_selection_for_arguments_objects.patch
Labels: security 🔒, semver/patch, backport-check-skip, 23-x-y

#38648 docs: indicate `app.setBadgeCount()` needs notifications permission to work
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#38647 build: fix semver/none label on appveyor update PR
  .github/workflows/update_appveyor_image.yml
Labels: semver/none, no-backport

#38636 chore: clean up `ElectronPermissionManager`
  shell/browser/electron_permission_manager.cc
Labels: semver/patch, new-pr 🌱, target/25-x-y, target/26-x-y

#38620 build: remove enable_picture_in_picture build flag
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  chromium_src/BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/feature_list.cc
  shell/common/api/features.cc
  spec/api-web-contents-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/none, no-backport

#38621 refactor: add ARC scaffolding for macOS
  BUILD.gn
  filenames.gni
  shell/browser/mac/dict_util.mm
  shell/browser/mac/electron_application_delegate.h
  shell/browser/mac/electron_application_delegate.mm
Labels: semver/patch, no-backport

#38603 fix: reparenting UAF crash on macOS
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38599 fix: menu bar visibility when exiting full screen
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38646 ci: remove release dependencies workflow
  .github/workflows/release_dependency_versions.yml
Labels: semver/none, no-backport

#38653 chore: cherry-pick 2 changes from Release-1-M114
  patches/v8/.patches
  patches/v8/cherry-pick-73af1a19a901.patch
  patches/v8/merged_ic_fix_store_handler_selection_for_arguments_objects.patch
Labels: security 🔒, semver/patch, backport-check-skip, 22-x-y

#38638 build: use upstream's presubmit cpplint filters.
  script/lint.js
Labels: semver/none, target/24-x-y, target/25-x-y, target/26-x-y

#38643 fix: dangling pointer warning when updating menus
  shell/browser/api/electron_api_base_window.cc
Labels: semver/patch, new-pr 🌱, target/24-x-y, target/25-x-y, target/26-x-y

#38637 chore: modify patches so we can build other chromium targets
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/build_only_use_the_mas_build_config_in_the_required_components.patch
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
Labels: semver/none, no-backport

#38332 chore: cherry-pick 8 changes from Release-1-M113
  patches/angle/.patches
  patches/angle/translator_limit_the_size_of_private_variables_in_webgl_shaders.patch
  patches/angle/webgl_limit_total_size_of_private_data.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-48785f698b1c.patch
  patches/chromium/m108-lts_return_after_readycommitnavigation_call_in_commiterrorpage.patch
  patches/config.json
  patches/dawn/.patches
  patches/dawn/change_d3d12_descriptor_allocator_to_invalidate_submitted_descriptors.patch
  patches/v8/.patches
  patches/v8/m108-lts_api_fix_v8_object_setaccessorproperty.patch
  patches/v8/merged_regexp_fix_clobbered_register_in_global_unicode_special.patch
Labels: security 🔒, semver/patch, backport-check-skip, 22-x-y

#38692 build: ensure correct dsymutil is downloaded for macOS
  .circleci/config/base.yml
Labels: fast-track 🚅, semver/none, no-backport

#38413 build: remove enable_run_as_node build flag
  .circleci/config/base.yml
  BUILD.gn
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  filenames.gni
  shell/app/electron_library_main.h
  shell/app/electron_library_main.mm
  shell/app/electron_main_linux.cc
  shell/app/electron_main_mac.cc
  shell/app/electron_main_win.cc
  shell/common/api/features.cc
  shell/common/crash_keys.cc
  shell/common/electron_constants.cc
  shell/common/electron_constants.h
  spec/asar-spec.ts
  spec/modules-spec.ts
  spec/node-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/none, no-backport

#38659 build: move uploadIndexJson to just before publishRelease
  script/release/release.js
Labels: semver/none, target/22-x-y, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38696 docs: use local img for contents.adjustSelection api
  docs/api/web-contents.md
  docs/images/web-contents-text-selection-after.png
  docs/images/web-contents-text-selection-before.png
Labels: backport, semver/none, 25-x-y

#38697 docs: use local img for contents.adjustSelection api
  docs/api/web-contents.md
  docs/images/web-contents-text-selection-after.png
  docs/images/web-contents-text-selection-before.png
Labels: backport, semver/none, 26-x-y

#38704 build: update sentry cli for m1 support
  script/release/uploaders/upload-symbols.py
Labels: fast-track 🚅, semver/none, no-backport

#38706 build: actually use m1.large for publish job
  .circleci/config/base.yml
Labels: fast-track 🚅, semver/none, no-backport

#38656 refactor: add SessionPreferences::CreateForBrowserContext()
  shell/browser/api/electron_api_session.cc
  shell/browser/session_preferences.cc
  shell/browser/session_preferences.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38693 fix: WCO transparent background
  docs/tutorial/window-customization.md
  shell/browser/ui/views/win_caption_button_container.cc
  shell/browser/ui/views/win_caption_button_container.h
  shell/browser/ui/views/win_frame_view.cc
Labels: semver/patch, new-pr 🌱, target/25-x-y, target/26-x-y

#38711 chore: cherry-pick 94af9d13a14b from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-94af9d13a14b.patch
Labels: semver/patch, backport-check-skip, 24-x-y

#38533 chore: cherry-pick 8 changes from Release-0-M114
  patches/chromium/.patches
  patches/chromium/cherry-pick-ea1cd76358e0.patch
  patches/chromium/m114_merge_fix_a_crash_caused_by_calling_trace_event.patch
  patches/chromium/mojoipcz_copy_incoming_messages_early.patch
  patches/config.json
  patches/pdfium/.patches
  patches/pdfium/m114_always_check_return_code_from_cpwl_combobox_setpopup.patch
  patches/pdfium/m114_observe_cpwl_combobox_across_all_on_methods.patch
  patches/pdfium/m114_observe_widget_across_setoptionselection_calls.patch
  patches/v8/.patches
  patches/v8/cherry-pick-3b0607d14060.patch
  patches/v8/cherry-pick-9c6dfc733fce.patch
Labels: security 🔒, semver/patch, backport-check-skip, 23-x-y

#38534 chore: cherry-pick 7 changes from Release-0-M114
  patches/chromium/.patches
  patches/chromium/cherry-pick-ea1cd76358e0.patch
  patches/chromium/m114_merge_fix_a_crash_caused_by_calling_trace_event.patch
  patches/pdfium/.patches
  patches/pdfium/m114_always_check_return_code_from_cpwl_combobox_setpopup.patch
  patches/pdfium/m114_observe_cpwl_combobox_across_all_on_methods.patch
  patches/pdfium/m114_observe_widget_across_setoptionselection_calls.patch
  patches/v8/.patches
  patches/v8/cherry-pick-3b0607d14060.patch
  patches/v8/cherry-pick-73af1a19a901.patch
  patches/v8/cherry-pick-9c6dfc733fce.patch
  patches/v8/m108-lts_api_fix_v8_object_setaccessorproperty.patch
  patches/v8/merged_ic_fix_store_handler_selection_for_arguments_objects.patch
Labels: security 🔒, semver/patch, backport-check-skip, 22-x-y

#38614 fix: `webContents.print` parameter validation error
  lib/browser/api/web-contents.ts
  spec/api-web-contents-spec.ts
  typings/internal-electron.d.ts
Labels: semver/patch, target/25-x-y, target/26-x-y

#38695 refactor: api web contents ownership
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38536 chore: cherry-pick 8 changes from Release-0-M114
  patches/chromium/.patches
  patches/chromium/cherry-pick-ea1cd76358e0.patch
  patches/chromium/m114_merge_fix_a_crash_caused_by_calling_trace_event.patch
  patches/chromium/mojoipcz_copy_incoming_messages_early.patch
  patches/config.json
  patches/pdfium/.patches
  patches/pdfium/m114_always_check_return_code_from_cpwl_combobox_setpopup.patch
  patches/pdfium/m114_observe_cpwl_combobox_across_all_on_methods.patch
  patches/pdfium/m114_observe_widget_across_setoptionselection_calls.patch
  patches/v8/.patches
  patches/v8/cherry-pick-0035a4a8dac2.patch
  patches/v8/cherry-pick-3b0607d14060.patch
  patches/v8/cherry-pick-73af1a19a901.patch
  patches/v8/cherry-pick-9c6dfc733fce.patch
Labels: security 🔒, semver/patch, backport-check-skip, 24-x-y

#38567 feat: support `node:` prefixed requires in sandboxed renderer preloads
  docs/tutorial/sandbox.md
  lib/sandboxed_renderer/init.ts
  spec/api-browser-window-spec.ts
  spec/fixtures/module/preload-sandbox.js
Labels: semver/minor, api-review/approved ✅, target/24-x-y, target/25-x-y, target/26-x-y

#38709 fix: `webContents.print()` cancellation callback
  patches/chromium/printing.patch
Labels: semver/patch, target/25-x-y, target/26-x-y

#38717 perf: prefer base::StringPiece over std::string for build-time strings
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/web_contents_permission_helper.cc
  shell/common/gin_converters/blink_converter.cc
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38705 chore: change remaining usages of `process.mainModule`
  script/lint.js
  script/nan-spec-runner.js
  script/node-spec-runner.js
  script/push-patch.js
  script/release/notes/index.js
  script/release/version-bumper.js
Labels: semver/none, no-backport

#38740 docs: clarify supported accelerator punctuation
  docs/api/accelerator.md
  shell/common/keyboard_util.cc
Labels: semver/patch, target/25-x-y, target/26-x-y

#38703 build: remove enable_osr build flag
  BUILD.gn
  buildflags/BUILD.gn
  buildflags/buildflags.gni
  filenames.gni
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_contents_impl.cc
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/views/autofill_popup_view.cc
  shell/browser/ui/views/autofill_popup_view.h
  shell/common/api/features.cc
  spec/api-browser-window-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/none, no-backport

#37940 docs: add missing isSameDocument property to will-frame-navigate event details
  docs/api/web-contents.md
Labels: documentation :notebook:, semver/patch, target/26-x-y

#38748 refactor: use compile-time cli arg sets.
  shell/app/node_main.cc
  shell/common/node_bindings.cc
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38764 build: move chrome_lib_arc to chromium_src/BUILD.gn
  BUILD.gn
  chromium_src/BUILD.gn
Labels: semver/none, target/26-x-y

#38747 build: update typescript-generator and docs-parser
  package.json
  spec/api-web-contents-spec.ts
  yarn.lock
Labels: semver/none, target/26-x-y

#38742 fix: asar integration for require('node:child_process')
  lib/asar/fs-wrapper.ts
  spec/asar-spec.ts
Labels: semver/patch, new-pr 🌱, target/24-x-y, target/25-x-y, target/26-x-y

#38761 fix: `preferCSSPageSize` error type
  lib/browser/api/web-contents.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38787 chore: cherry-pick 3 changes from Release-2-M114
  patches/chromium/.patches
  patches/chromium/base_do_not_use_va_args_twice_in_asprintf.patch
  patches/v8/.patches
  patches/v8/cherry-pick-2e76270cf65e.patch
  patches/webrtc/.patches
  patches/webrtc/m114_move_transceiver_iteration_loop_over_to_the_signaling_thread.patch
Labels: security 🔒, semver/patch, backport-check-skip, 24-x-y

#38767 chore: remove unused std includes
  shell/app/electron_crash_reporter_client.cc
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_view.h
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_debugger.cc
  shell/browser/api/electron_api_push_notifications.cc
  shell/browser/api/electron_api_safe_storage.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_system_preferences_mac.mm
  shell/browser/api/electron_api_utility_process.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/gpuinfo_manager.h
  shell/browser/badging/badge_manager_factory.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/file_select_helper.h
  shell/browser/hid/hid_chooser_context.h
  shell/browser/linux/unity_service.cc
  shell/browser/mac/electron_application.mm
  shell/browser/media/media_capture_devices_dispatcher.h
  shell/browser/native_browser_view.h
  shell/browser/native_browser_view_mac.h
  shell/browser/native_browser_view_views.cc
  shell/browser/native_browser_view_views.h
  shell/browser/native_window_views.h
  shell/browser/net/resolve_host_function.cc
  shell/browser/net/resolve_host_function.h
  shell/browser/notifications/win/windows_toast_notification.h
  shell/browser/printing/print_view_manager_electron.h
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/serial/serial_chooser_context.h
  shell/browser/ui/cocoa/electron_bundle_mover.h
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view_mac.h
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
  shell/browser/ui/views/submenu_button.h
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/usb/usb_chooser_context.h
  shell/browser/usb/usb_chooser_controller.h
  shell/browser/web_contents_permission_helper.cc
  shell/browser/zoom_level_delegate.cc
  shell/common/asar/asar_util.cc
  shell/common/color_util.cc
  shell/common/crash_keys.cc
  shell/common/gin_converters/extension_converter.h
  shell/common/gin_converters/media_converter.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  shell/common/node_bindings.cc
  shell/renderer/api/context_bridge/object_cache.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_renderer_client.h
  shell/renderer/electron_sandboxed_renderer_client.h
  shell/renderer/renderer_client_base.h
  shell/services/node/node_service.cc
  shell/utility/electron_content_utility_client.h
Labels: semver/patch, new-pr 🌱, target/26-x-y

#38788 chore: cherry-pick 3 changes from Release-2-M114
  patches/chromium/.patches
  patches/chromium/base_do_not_use_va_args_twice_in_asprintf.patch
  patches/v8/.patches
  patches/v8/cherry-pick-2e76270cf65e.patch
  patches/webrtc/.patches
  patches/webrtc/m114_move_transceiver_iteration_loop_over_to_the_signaling_thread.patch
Labels: security 🔒, semver/patch, backport-check-skip, 23-x-y

#38789 chore: cherry-pick 5 changes from Release-2-M114, Release-1-M110 and Release-0-M110
  patches/chromium/.patches
  patches/chromium/base_do_not_use_va_args_twice_in_asprintf.patch
  patches/config.json
  patches/v8/.patches
  patches/v8/cherry-pick-2e76270cf65e.patch
  patches/webrtc/.patches
  patches/webrtc/cherry-pick-218b56e51638.patch
  patches/webrtc/cherry-pick-e0efbd45ea74.patch
  patches/webrtc/m114_move_transceiver_iteration_loop_over_to_the_signaling_thread.patch
Labels: security 🔒, semver/patch, backport-check-skip, 22-x-y

#38800 refactor: constexpr lookup tables
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_url_loader.cc
Labels: backport, semver/patch, target/24-x-y, 25-x-y

#38741 fix: `webContents.print({ silent: true })` not working correctly
  patches/chromium/printing.patch
Labels: semver/patch, target/25-x-y, target/26-x-y

#38799 refactor: remove unused InspectableWebContentsView::GetWebView()
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38814 fix: `webContents.print()` cancellation callback
  patches/chromium/printing.patch
Labels: backport, semver/patch, 25-x-y

#38825 build: use Xcode 13.4.1
  .circleci/config/base.yml
Labels: backport-check-skip, semver/none, 23-x-y

#38822 build: use Xcode 13.4.1
  .circleci/config/base.yml
Labels: backport-check-skip, semver/none, 22-x-y

#38818 refactor: use constexpr lookup tables in gin helper
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_url_loader.cc
  shell/browser/api/electron_api_web_request.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/std_converter.h
Labels: semver/patch, target/26-x-y

#38838 build: rename spec/.eslintrc -> spec/.eslintrc.json
  spec/.eslintrc.json
Labels: semver/none, no-backport

#38843 refactor: use content::GlobalRenderFrameHostId
  shell/browser/electron_api_ipc_handler_impl.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
Labels: semver/patch, no-backport

#38847 refactor: use node scheme imports in default_app
  default_app/.eslintrc.json
  default_app/default_app.ts
  default_app/main.ts
Labels: semver/patch, no-backport

#38848 chore: remove deleted guest-window-proxy.ts from CODEOWNERS
  .github/CODEOWNERS
Labels: semver/none, no-backport

#38842 fix: crash calling `BrowserWindow.removeBrowserView()` with destroyed `webContents`
  shell/browser/api/electron_api_browser_view.cc
  shell/browser/api/electron_api_browser_view.h
  spec/api-browser-view-spec.ts
Labels: semver/patch, target/24-x-y, target/25-x-y, target/26-x-y

#38877 refactor: api web contents ownership
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: backport, semver/patch, target/24-x-y, 25-x-y

#38878 refactor: prefer base::Contains() over find() + end()
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_power_save_blocker.cc
  shell/browser/api/electron_api_power_save_blocker.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/native_window.cc
  shell/browser/native_window_views.cc
  shell/browser/printing/print_view_manager_electron.cc
  shell/browser/ui/message_box_win.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_bindings.cc
  shell/common/key_weak_map.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: backport, semver/patch, target/24-x-y, 25-x-y

#38894 refactor: api web contents ownership
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: backport, semver/patch, 24-x-y

#38872 refactor: use types for once() return values in spec
  spec/api-app-spec.ts
  spec/api-auto-updater-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-native-theme-spec.ts
  spec/api-session-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/guest-window-manager-spec.ts
  spec/webview-spec.ts
Labels: semver/none, no-backport

#38907 fix: `navigator.connection` not working as intended
  shell/browser/browser_process_impl.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_browser_main_parts.cc
  spec/chromium-spec.ts
Labels: backport, semver/patch, target/23-x-y, target/24-x-y, 25-x-y

#38904 chore: add missing content::WebContentsDelegate section
  shell/browser/api/electron_api_web_contents.h
Labels: backport, semver/none, 25-x-y

#38898 chore: cleanup unusued variables + enable linting
  .eslintrc.json
  script/download-circleci-artifacts.js
  script/generate-version-json.js
  script/lib/azput.js
  script/lib/utils.js
  script/lint.js
  script/release/ci-release-build.js
  script/release/notes/notes.js
  script/release/prepare-release.js
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/version-bumper.js
  script/release/version-utils.js
  script/spec-runner.js
  spec/fixtures/api/context-bridge/context-bridge-mutability/preload.js
  spec/fixtures/api/new-window-preload.js
  spec/fixtures/api/safe-storage/decrypt-app/main.js
  spec/fixtures/api/safe-storage/encrypt-app/main.js
  spec/fixtures/api/service-workers/sw-logs.js
  spec/fixtures/api/service-workers/sw.js
  spec/fixtures/api/singleton/main.js
  spec/fixtures/apps/crash/node-extra-args.js
  spec/fixtures/apps/libuv-hang/renderer.js
  spec/fixtures/apps/remote-control/main.js
  spec/fixtures/apps/self-module-paths/main.js
  spec/fixtures/chromium/other-window.js
  spec/fixtures/crash-cases/fs-promises-renderer-crash/index.js
  spec/fixtures/crash-cases/worker-multiple-destroy/worklet.js
  spec/fixtures/extensions/chrome-webRequest/background.js
  spec/fixtures/extensions/lazy-background-page/get-background-page.js
  spec/fixtures/extensions/lazy-background-page/runtime-get-background-page.js
  spec/fixtures/module/preload-context.js
  spec/fixtures/module/preload-sandbox.js
  spec/fixtures/testsnap.js
  spec/lib/video-helpers.js
Labels: semver/patch, no-backport

#38917 docs: document e27 breaking change of dropping macOS 10.13, 10.14
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/none, target/25-x-y, target/26-x-y

#38899 chore: re-enable node/no-deprecated-api linting
  .eslintrc.json
  lib/browser/api/net-client-request.ts
  lib/browser/devtools.ts
Labels: semver/patch, no-backport

#38910 fix: child window may have opener removed
  shell/renderer/electron_render_frame_observer.cc
  spec/chromium-spec.ts
Labels: semver/patch, target/23-x-y, target/24-x-y, target/25-x-y, target/26-x-y

#38895 refactor: more constexpr lookup tables
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/web_contents_preferences.cc
  shell/common/gin_converters/content_converter.cc
  shell/common/keyboard_util.cc
  shell/common/keyboard_util.h
Labels: backport, semver/patch, 26-x-y

#38929 refactor: replace Object.prototype.hasOwnProperty() with Object.hasOwn()
  lib/browser/api/dialog.ts
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/menu.ts
  lib/browser/api/net-client-request.ts
  lib/browser/api/protocol.ts
  lib/renderer/security-warnings.ts
  lib/sandboxed_renderer/init.ts
  spec/api-net-spec.ts
  spec/asar-spec.ts
  spec/lib/spec-helpers.ts
  tsconfig.json
Labels: semver/patch, no-backport

#38947 chore: cherry-pick 4 changes from Release-3-M114
  patches/chromium/.patches
  patches/chromium/cherry-pick-60b93798c991.patch
  patches/chromium/cherry-pick-85beff6fd302.patch
  patches/v8/.patches
  patches/v8/merged_compiler_stackcheck_can_have_side_effects.patch
  patches/v8/merged_runtime_set_instance_prototypes_directly_on_maps.patch
  patches/webrtc/.patches
  patches/webrtc/m114_sdp_reject_duplicate_ssrcs_in_ssrc-groups.patch
Labels: security 🔒, semver/patch, backport-check-skip, 24-x-y

#38948 chore: cherry-pick 4 changes from Release-3-M114
  patches/chromium/.patches
  patches/chromium/cherry-pick-85beff6fd302.patch
  patches/chromium/m114_webcodecs_fix_crash_when_changing_temporal_layer_count_in_av1.patch
  patches/v8/.patches
  patches/v8/merged_compiler_stackcheck_can_have_side_effects.patch
  patches/v8/merged_runtime_set_instance_prototypes_directly_on_maps.patch
  patches/v8/utf-8_q_shared-struct_20fix_20using_20shared_20objects_20as.patch
  patches/webrtc/.patches
  patches/webrtc/m114_sdp_reject_duplicate_ssrcs_in_ssrc-groups.patch
Labels: security 🔒, semver/patch, backport-check-skip, 23-x-y

#38903 feat: add support for keyboard initialized menu popup
  docs/api/menu.md
  lib/browser/api/menu.ts
  patches/chromium/.patches
  patches/chromium/fix_select_the_first_menu_item_when_opened_via_keyboard.patch
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/api/electron_api_menu_views.cc
  shell/browser/api/electron_api_menu_views.h
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/content_converter.h
  typings/internal-electron.d.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/26-x-y
