Repository electron/electron, pull requests merged in 2023-11, with the labels that each got.

#40375 chore: remove py2 compatibility code
  build/dump_syms.py
  build/npm-run.py
  build/profile_toolchain.py
  build/zip.py
  build/zip_libcxx.py
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/generate-config-gypi.py
  script/lib/config.py
  script/lib/git.py
  script/lib/native_tests.py
  script/lib/util.py
  script/native-tests.py
  script/patches-mtime-cache.py
  script/release/uploaders/upload-index-json.py
  script/release/uploaders/upload.py
  script/run-clang-format.py
  script/strip-binaries.py
  script/verify-chromedriver.py
  script/verify-ffmpeg.py
  script/verify-mksnapshot.py
  script/zip-symbols.py
Labels: new-pr 🌱, semver/none, no-backport

#40321 docs: avoid leaking the `IpcRendererEvent` in `contextBridge` examples
  docs/fiddles/ipc/pattern-3/preload.js
  docs/fiddles/ipc/pattern-3/renderer.js
  docs/tutorial/ipc.md
Labels: documentation :notebook:, semver/patch, target/27-x-y, target/28-x-y

#40409 refactor: remove DevTools legacy UI patching
  patches/devtools_frontend/.patches
  patches/devtools_frontend/chore_expose_ui_to_allow_electron_to_set_dock_side.patch
  patches/devtools_frontend/fix_expose_globals_to_allow_patching_devtools_dock.patch
  shell/browser/ui/inspectable_web_contents.cc
  spec/extensions-spec.ts
  spec/webview-spec.ts
Labels: backport, semver/patch, 28-x-y

#40373 docs: document our Node.js versioning policy
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40411 fix: webview exiting fullscreen presentation mode
  patches/chromium/.patches
  patches/chromium/fix_allow_guest_webcontents_to_enter_fullscreen.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/webview_fullscreen.patch
Labels: backport, semver/patch, 25-x-y

#40410 feat: add `tabbingIdentifier` property to `BrowserWindow`
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 26-x-y

#40358 docs: add `bypassCustomProtocolHandlers` to `ses.fetch`
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, target/25-x-y, target/26-x-y, target/27-x-y, target/28-x-y

#40419 build: remove patch for EOL MSVC version
  patches/v8/.patches
  patches/v8/fix_build_deprecated_attribute_for_older_msvc_versions.patch
Labels: semver/none, no-backport

#40436 chore: cherry-pick 1 changes from Release-0-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-80106e31c7ea.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40437 chore: cherry-pick 1 changes from Release-0-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-80106e31c7ea.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#40369 feat: `keyboard.lock()` should use permissions helper
  docs/api/session.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_permission_helper.h
  shell/common/gin_converters/content_converter.cc
Labels: semver/minor, api-review/approved ✅, target/26-x-y, target/27-x-y, target/28-x-y

#40307 fix: Do not activate app when calling focus on inactive panel window
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40450 fix: broken shader cache due to compilation error
  patches/chromium/.patches
  patches/chromium/crash_gpu_process_and_clear_shader_cache_when_skia_reports.patch
Labels: semver/patch, backport-check-skip, target/27-x-y, 28-x-y

#40452 fix: broken shader cache due to compilation error
  patches/chromium/.patches
  patches/chromium/crash_gpu_process_and_clear_shader_cache_when_skia_reports.patch
  patches/chromium/gpu_use_load_program_shader_shm_count_on_drdc_thread.patch
Labels: semver/patch, backport-check-skip, target/25-x-y, 26-x-y

#40462 docs: fix `hid-device-{added|removed|revoked}` event types
  docs/api/session.md
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40289 refactor: AutoUpdater for Windows using async/await
  lib/browser/api/auto-updater/auto-updater-win.ts
  lib/browser/api/auto-updater/squirrel-update-win.ts
Labels: semver/patch, no-backport

#40372 feat: add new fuse to treat file: identically to browsers
  build/fuses/fuses.json5
  docs/api/protocol.md
  docs/tutorial/fuses.md
  docs/tutorial/security.md
  shell/app/electron_content_client.cc
  shell/browser/electron_browser_client.cc
  shell/renderer/renderer_client_base.cc
Labels: semver/minor, api-review/approved ✅, no-backport

#40472 chore: bump node to v18.18.2
  DEPS
  patches/node/build_add_gn_build_files.patch
  patches/node/feat_add_uv_loop_interrupt_on_io_change_option_to_uv_loop_configure.patch
  patches/node/fix_suppress_clang_-wdeprecated-declarations_in_libuv.patch
  patches/node/win_process_avoid_assert_after_spawning_store_app_4152.patch
Labels: backport, semver/patch, 28-x-y

#40480 docs: update references to Electron Packager
  docs/api/app.md
  docs/fiddles/system/protocol-handler/launch-app-from-URL-in-another-app/index.html
  docs/tutorial/asar-integrity.md
  docs/tutorial/boilerplates-and-clis.md
  docs/tutorial/code-signing.md
  docs/tutorial/dark-mode.md
  docs/tutorial/launch-app-from-url-in-another-app.md
  docs/tutorial/snapcraft.md
  docs/tutorial/tutorial-5-packaging.md
  docs/tutorial/using-native-node-modules.md
  docs/tutorial/windows-store-guide.md
Labels: documentation :notebook:, semver/patch, target/28-x-y

#40491 build: fix building content_unittests
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/build_only_use_the_mas_build_config_in_the_required_components.patch
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
Labels: semver/none, no-backport

#40506 chore: fix some typos
  docs/api/structures/user-default-types.md
  lib/browser/api/browser-window.ts
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/browser_observer.h
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/microtasks_runner.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/usb/usb_chooser_controller.cc
  shell/browser/zoom_level_delegate.cc
  shell/common/api/BUILD.gn
  shell/common/gin_helper/event_emitter.h
  shell/common/node_bindings.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/services/node/node_service.cc
Labels: semver/none, no-backport

#40500 fix: `chrome.action` API registration
  shell/browser/extensions/api/BUILD.gn
  shell/common/extensions/api/BUILD.gn
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/_manifest_features.json
  shell/common/extensions/api/action.json
  shell/common/extensions/api/browser_action.json
  spec/extensions-spec.ts
  spec/fixtures/extensions/chrome-action-fail/background.js
  spec/fixtures/extensions/chrome-action-fail/main.js
  spec/fixtures/extensions/chrome-action-fail/manifest.json
  spec/fixtures/extensions/chrome-action-fail/popup.html
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40425 ci: close previous release project board after creating new one
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#40518 chore: cherry-pick 1 changes from Release-1-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-3df423a5b8de.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40519 chore: cherry-pick 1 changes from Release-1-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-3df423a5b8de.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#40390 fix: emit will-navigate for links in chrome: pages
  shell/browser/electron_navigation_throttle.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y

#40511 refactor: use new extensions Messaging API IPC
  build/args/all.gn
  filenames.gni
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
  shell/browser/electron_browser_context.cc
  shell/browser/extensions/electron_extension_message_filter.cc
  shell/browser/extensions/electron_extension_message_filter.h
Labels: semver/patch, no-backport

#40535 fix: scale rects properly in `SyncGetFirstRectForRange`
  patches/chromium/.patches
  patches/chromium/scale_rects_properly_in_syncgetfirstrectforrange.patch
Labels: semver/patch, backport-check-skip

#40534 fix: scale rects properly in `SyncGetFirstRectForRange`
  patches/chromium/.patches
  patches/chromium/scale_rects_properly_in_syncgetfirstrectforrange.patch
Labels: semver/patch, backport-check-skip

#40536 fix: add patch for simdutf base64 crash
  patches/node/.patches
  patches/node/fix_avx_detection.patch
Labels: semver/patch, new-pr 🌱, target/26-x-y, target/27-x-y, target/28-x-y

#40538 chore: cherry-pick 1 changes from Release-2-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-9384cddc7705.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y

#40526 fix: revert SameParty cookie attribute removal
  patches/chromium/.patches
  patches/chromium/revert_same_party_cookie_attribute_removal.patch
Labels: semver/patch, backport-check-skip, backport/approved ✅, 28-x-y

#40497 feat: add/update missing Display properties
  docs/api/structures/display.md
  shell/common/gin_converters/gfx_converter.cc
  spec/api-screen-spec.ts
Labels: semver/minor, api-review/approved ✅, target/28-x-y

#40313 test: convert a few more specs to async/await
  spec/api-debugger-spec.ts
  spec/api-power-monitor-spec.ts
  spec/api-web-contents-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/node-spec.ts
  spec/security-warnings-spec.ts
  spec/spellchecker-spec.ts
Labels: semver/none, no-backport

#40537 chore: cherry-pick 1 changes from Release-2-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-9384cddc7705.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40527 fix: ShowItemUsingFileManager should escape path in Linux
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#38776 feat: add webUtils module with getPathForFile method
  .circleci/config/base.yml
  docs/api/file-object.md
  docs/api/web-utils.md
  docs/tutorial/sandbox.md
  filenames.auto.gni
  filenames.gni
  lib/renderer/api/module-list.ts
  lib/renderer/api/web-utils.ts
  lib/sandboxed_renderer/api/module-list.ts
  patches/chromium/.patches
  patches/chromium/expose_webblob_path_to_allow_embedders_to_get_file_paths.patch
  shell/common/node_bindings.cc
  shell/renderer/api/electron_api_web_utils.cc
  shell/renderer/api/electron_api_web_utils.h
  spec/api-web-utils-spec.ts
  spec/fixtures/pages/file-input.html
Labels: semver/minor, api-review/approved ✅, no-backport

#36368 build: simplify mas patches
  patches/chromium/.patches
  patches/chromium/build_gn.patch
  patches/chromium/build_only_use_the_mas_build_config_in_the_required_components.patch
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
  patches/chromium/mas-cgdisplayusesforcetogray.patch
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  patches/chromium/mas_avoid_usage_of_private_macos_apis.patch
  patches/chromium/mas_blink_no_private_api.patch
  patches/chromium/mas_disable_custom_window_frame.patch
  patches/chromium/mas_disable_remote_accessibility.patch
  patches/chromium/mas_disable_remote_layer.patch
  patches/chromium/mas_no_private_api.patch
  patches/chromium/mas_use_public_apis_to_determine_if_a_font_is_a_system_font.patch
  patches/chromium/printing.patch
  patches/chromium/render_widget_host_view_mac.patch
Labels: semver/none, no-backport

#40556 docs: update quick-start.md
  docs/tutorial/quick-start.md
Labels: documentation :notebook:, semver/patch, no-backport

#40555 docs: wording in IPC tutorial docs
  docs/tutorial/ipc.md
Labels: documentation :notebook:, semver/patch, no-backport

#40487 ci: trigger Slack workflow on backport requested
  .github/workflows/pull-request-labeled.yml
Labels: semver/none, no-backport

#40503 fix: maximized window bounds when toggle setResizable
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/ui/win/electron_desktop_native_widget_aura.cc
  shell/browser/ui/win/electron_desktop_native_widget_aura.h
  spec/api-browser-window-spec.ts
Labels: platform/windows, semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40577 fix: restore performance of macOS window resizing
  patches/chromium/.patches
  patches/chromium/fix_restore_original_resize_performance_on_macos.patch
Labels: semver/patch, new-pr 🌱, target/26-x-y, target/27-x-y, target/28-x-y

#40574 fix: do not call `after()` `async_hook` for `asyncId` 0
  shell/common/node_bindings.cc
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40588 build: specify explicit typeroots for ts builds
  tsconfig.json
Labels: semver/none, target/28-x-y

#40596 chore: add patch upstream plan for resize patch
  patches/chromium/fix_restore_original_resize_performance_on_macos.patch
Labels: new-pr 🌱, semver/none, no-backport

#40570 fix: Use activateIgnoringOtherApps for non-panels
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/28-x-y

#40628 chore: allow passing more roots to lint.js
  script/lint.js
Labels: backport, semver/none, 27-x-y

#40629 fix: 28-x-y patches
  patches/chromium/revert_same_party_cookie_attribute_removal.patch
Labels: backport-check-skip, semver/none

#40623 ci: use pull_request_target for PR labeled workflows
  .github/workflows/pull-request-labeled.yml
Labels: semver/none, no-backport

#40627 chore: allow passing more roots to lint.js
  script/lint.js
Labels: backport, semver/none, 28-x-y

#40624 chore: make use of the v8_expose_public_symbols flag
  build/args/all.gn
  patches/v8/.patches
  patches/v8/build_correctly_expose_public_symbols_with_v8_expose_public_symbols.patch
  patches/v8/build_expose_mksnapshot_to_embedders.patch
  patches/v8/build_gn.patch
  patches/v8/do_not_export_private_v8_symbols_on_windows.patch
Labels: semver/none, no-backport

#40633 chore: remove fix_add_check_for_sandbox_then_result.patch
  patches/chromium/.patches
  patches/chromium/fix_add_check_for_sandbox_then_result.patch
Labels: new-pr 🌱, semver/none, no-backport

#40643 chore: cherry-pick 5 changes from Release-3-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-3f45b1af5e41.patch
  patches/chromium/cherry-pick-6cc0d9aa5b3f.patch
  patches/chromium/cherry-pick-e13061c50998.patch
  patches/config.json
  patches/openscreen/.patches
  patches/openscreen/cherry-pick-971d6055e7b7.patch
  patches/skia/.patches
  patches/skia/avoid_combining_extremely_large_meshes.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#40634 build: fix release notes script bug that omitted edited release-clerk comments
  script/release/notes/notes.js
Labels: component/build, semver/none, target/26-x-y, target/27-x-y, target/28-x-y

#40546 fix: add missing `set_wants_to_be_visible(true)` to `NativeWindowMac::ShowInactive()`
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y

#40644 chore: cherry-pick 6 changes from Release-3-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-3f45b1af5e41.patch
  patches/chromium/cherry-pick-e13061c50998.patch
  patches/config.json
  patches/libavif/.patches
  patches/libavif/do_not_store_potentially_invalid_pointers.patch
  patches/libavif/remove_potential_out_of_bound_access_to_alphaitemindices.patch
  patches/openscreen/.patches
  patches/openscreen/cherry-pick-971d6055e7b7.patch
  patches/skia/.patches
  patches/skia/avoid_combining_extremely_large_meshes.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40664 chore: fix patch conflicts after chrome roll
  patches/chromium/.patches
  patches/chromium/cherry-pick-3f45b1af5e41.patch
  patches/chromium/cherry-pick-e13061c50998.patch
  patches/config.json
  patches/libavif/.patches
  patches/libavif/do_not_store_potentially_invalid_pointers.patch
  patches/libavif/remove_potential_out_of_bound_access_to_alphaitemindices.patch
  patches/skia/.patches
  patches/skia/avoid_combining_extremely_large_meshes.patch
Labels: fast-track 🚅, backport-check-skip, semver/none, 27-x-y

#40645 chore: cherry-pick 3 changes from Release-3-M119
  patches/chromium/.patches
  patches/chromium/cherry-pick-3f45b1af5e41.patch
  patches/chromium/cherry-pick-e13061c50998.patch
  patches/skia/.patches
  patches/skia/avoid_combining_extremely_large_meshes.patch
Labels: security 🔒, semver/patch, backport-check-skip, 25-x-y
