Repository electron/electron, pull requests merged in 2024-01, with the labels that each got.

#40749 fix: titlebar incorrectly displayed on frameless windows
  patches/chromium/fix_activate_background_material_on_windows.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#40802 chore: cherry-pick 7 changes from Release-1-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-021598ea43c1.patch
  patches/chromium/cherry-pick-4ca62c7a8b88.patch
  patches/chromium/cherry-pick-76340163a820.patch
  patches/chromium/cherry-pick-998e947b265f.patch
  patches/chromium/cherry-pick-f15cfb9371c4.patch
  patches/config.json
  patches/libavif/.patches
  patches/libavif/do_not_store_colorproperties_until_alpha_item_is_found.patch
  patches/v8/.patches
  patches/v8/cherry-pick-cbd09b2ca928.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#40801 fix: make grant_file_protocol_extra_privileges fuse also block CORS fetches
  build/fuses/build.py
  shell/browser/protocol_registry.cc
  spec/fixtures/apps/remote-control/main.js
  spec/fuses-spec.ts
Labels: security 🔒, semver/patch, target/29-x-y

#40868 fix: titlebar incorrectly displayed on frameless windows
  patches/chromium/fix_activate_background_material_on_windows.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Labels: backport, semver/patch, 27-x-y

#40867 fix: titlebar incorrectly displayed on frameless windows
  patches/chromium/fix_activate_background_material_on_windows.patch
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Labels: backport, semver/patch, 28-x-y

#40860 chore: drop ada ICU requirement for parsing hostnames
  patches/node/build_add_gn_build_files.patch
Labels: semver/none, no-backport

#40770 fix: ignore all NODE_ envs from foreign parent in node process
  filenames.gni
  shell/app/node_main.cc
  shell/common/mac/codesign_util.cc
  shell/common/mac/codesign_util.h
  shell/common/node_util.h
  shell/common/node_util_mac.mm
  spec/fixtures/api/fork-with-node-options.js
  spec/node-spec.ts
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y, target/29-x-y

#40717 chore: add disclaimer to release timeline
  docs/tutorial/electron-timelines.md
Labels: semver/none, target/28-x-y, target/29-x-y

#40866 fix: BrowserView and <webview> should be transparent by default
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/29-x-y

#40783 docs: note accelerator case insensitivity
  docs/api/accelerator.md
Labels: documentation :notebook:, semver/patch, no-backport

#40804 refactor: make NativeWindow getter methods const
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: semver/patch, target/29-x-y

#40017 feat: add net module to utility process
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/net.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/net-fetch.ts
  lib/browser/api/net.ts
  lib/browser/api/session.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  lib/utility/api/module-list.ts
  lib/utility/api/net.ts
  lib/utility/init.ts
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/net/resolve_host_function.cc
  shell/browser/net/resolve_host_function.h
  shell/common/api/electron_api_net.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/node_bindings.cc
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/public/mojom/node_service.mojom
  spec/api-net-custom-protocols-spec.ts
  spec/api-net-session-spec.ts
  spec/api-net-spec.ts
  spec/fixtures/api/utility-process/api-net-spec.js
  spec/lib/net-helpers.ts
  typings/internal-ambient.d.ts
Labels: semver/minor, api-review/approved ✅, target/29-x-y

#40301 feat: add `transparent` webpreference to webview
  docs/api/webview-tag.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/fixtures/pages/flex-webview.html
  spec/webview-spec.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#40882 fix: ignore all NODE_ envs from foreign parent in node process
  filenames.gni
  shell/app/node_main.cc
  shell/common/mac/codesign_util.cc
  shell/common/mac/codesign_util.h
  shell/common/node_util.h
  shell/common/node_util_mac.mm
  spec/fixtures/api/fork-with-node-options.js
  spec/node-spec.ts
Labels: backport, semver/patch, 26-x-y

#40817 perf: use flat_set, flat_map for small, trivially-moved containers
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_menu_views.cc
  shell/browser/api/electron_api_menu_views.h
  shell/browser/api/electron_api_power_save_blocker.h
  shell/browser/api/electron_api_system_preferences_mac.mm
  shell/browser/electron_browser_client.h
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/notifications/linux/libnotify_notification.cc
  shell/browser/ui/electron_menu_model.h
  shell/browser/ui/gtk/menu_util.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/message_box_mac.mm
  shell/browser/ui/message_box_win.cc
  shell/browser/ui/views/electron_views_delegate.h
  shell/browser/ui/views/electron_views_delegate_win.cc
  shell/browser/web_view_manager.h
  shell/common/api/electron_api_native_image.h
  shell/renderer/electron_renderer_client.h
  shell/renderer/web_worker_observer.cc
  shell/renderer/web_worker_observer.h
Labels: semver/patch, no-backport

#40887 refactor: make NativeWindow getter methods const
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: backport, semver/patch, 29-x-y

#40705 fix: macOS maximize button shouldn't be disabled just because the window is non-fullscreenable
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#40891 chore: do not inject DXVA_Decoding trace category
  patches/chromium/build_add_electron_tracing_category.patch
Labels: semver/patch, target/29-x-y

#40893 docs: add missing vibrancy breaking change
  docs/breaking-changes.md
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#40892 fix: wide string concatenation
  shell/browser/browser_win.cc
  shell/browser/relauncher_win.cc
Labels: semver/patch, target/28-x-y, target/29-x-y

#40900 chore: cherry-pick 8 changes from Release-3-M120
  patches/angle/.patches
  patches/angle/m120_translator_fail_compilation_if_too_many_struct_fields.patch
  patches/angle/m120_translator_limit_private_variable_size_to_64kb.patch
  patches/angle/m120_translator_optimize_field-name-collision_check.patch
  patches/angle/m120_vulkan_don_t_crash_when_glcopyteximage2d_redefines_itself.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-50a1bddfca85.patch
  patches/chromium/cherry-pick-5b2fddadaa12.patch
  patches/config.json
  patches/sqlite/.patches
  patches/sqlite/fix_a_spurious_misuse_of_aggregate_function_error_that_could_occur.patch
  patches/v8/.patches
  patches/v8/merged_turboshaft_fix_structuraloptimization_because_of_ignored.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#40888 fix: crash using `powerMonitor` before ready event
  shell/browser/electron_browser_main_parts.cc
  shell/browser/lib/power_observer_linux.cc
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y, target/29-x-y

#40850 build: add infra for reclient support
  .circleci/config/base.yml
  DEPS
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  patches/chromium/.patches
  patches/chromium/build_run_reclient_cfg_generator_after_chrome.patch
  patches/config.json
  patches/reclient-configs/.patches
  patches/reclient-configs/build_on_windows_provide_clang_wrapper_as_toolchain_input.patch
  patches/reclient-configs/fix_add_python_remote_wrapper.patch
  patches/reclient-configs/fix_disable_compression_threshold.patch
  script/prepare-appveyor.js
  script/start-goma.ps1
Labels: semver/none, no-backport

#40875 build: use container runner for arm tests
  .circleci/config/base.yml
Labels: semver/none, target/26-x-y, target/27-x-y, target/28-x-y, target/29-x-y

#40939 chore: fix content tracing flake
  .circleci/config/base.yml
  spec/api-content-tracing-spec.ts
Labels: fast-track 🚅, semver/none, no-backport

#40726 ci: fix missing inputs for release project board automation
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#40927 refactor: migrate deprecated LazyInstance code to NoDestructor
  shell/browser/javascript_environment.cc
  shell/browser/window_list.cc
  shell/browser/window_list.h
Labels: semver/patch, target/28-x-y, target/29-x-y

#40915 chore: migrate base::StringPiece to std::string_view
  shell/app/electron_content_client.cc
  shell/app/electron_main_delegate.cc
  shell/app/node_main.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_request.cc
  shell/browser/electron_browser_main_parts_linux.cc
  shell/browser/event_emitter_mixin.h
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/node_stream_loader.cc
  shell/browser/ui/file_dialog_mac.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_preferences.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/asar/archive.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_helper/arguments.cc
  shell/common/gin_helper/arguments.h
  shell/common/gin_helper/dictionary.h
  shell/common/gin_helper/error_thrower.cc
  shell/common/gin_helper/error_thrower.h
  shell/common/gin_helper/event_emitter.h
  shell/common/gin_helper/object_template_builder.cc
  shell/common/gin_helper/object_template_builder.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/keyboard_util.cc
  shell/common/keyboard_util.h
  shell/common/logging.cc
  shell/common/node_bindings.cc
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/patch, target/28-x-y, target/29-x-y

#40953 build: remove CI cache of git cache
  .circleci/config/base.yml
Labels: semver/none, no-backport

#40938 fix: InAppPurchase pre-emptive deallocation
  shell/browser/mac/in_app_purchase.mm
  shell/browser/mac/in_app_purchase_product.mm
  spec/api-in-app-purchase-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#40958 build: fix windows remote exec of python actions
  patches/reclient-configs/fix_add_python_remote_wrapper.patch
Labels: semver/none, target/29-x-y

#40963 ci: increase "gclient sync" output timeout
  .circleci/config/base.yml
Labels: fast-track 🚅, semver/none, no-backport

#40964 ci: revert CI git cache removal
  .circleci/config/base.yml
Labels: fast-track 🚅, semver/none, no-backport

#40948 docs: add reclient docs, remove goma docs
  docs/development/goma.md
  docs/development/reclient.md
Labels: documentation :notebook:, new-pr 🌱, semver/none, no-backport

#40970 chore: cherry-pick 389ea9be7d68 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-389ea9be7d68.patch
Labels: security 🔒, semver/patch, backport-check-skip, 28-x-y

#40969 chore: cherry-pick 389ea9be7d68 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-389ea9be7d68.patch
Labels: security 🔒, semver/patch, backport-check-skip, 29-x-y

#40973 chore: migrate base::StringPiece to std::string_view (#40915)
  shell/app/electron_content_client.cc
  shell/app/electron_main_delegate.cc
  shell/app/node_main.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_request.cc
  shell/browser/electron_browser_main_parts_linux.cc
  shell/browser/event_emitter_mixin.h
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/node_stream_loader.cc
  shell/browser/ui/file_dialog_mac.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/web_contents_permission_helper.cc
  shell/browser/web_contents_preferences.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/asar/archive.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_helper/arguments.cc
  shell/common/gin_helper/arguments.h
  shell/common/gin_helper/dictionary.h
  shell/common/gin_helper/error_thrower.cc
  shell/common/gin_helper/error_thrower.h
  shell/common/gin_helper/event_emitter.h
  shell/common/gin_helper/object_template_builder.cc
  shell/common/gin_helper/object_template_builder.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/keyboard_util.cc
  shell/common/keyboard_util.h
  shell/common/logging.cc
  shell/common/node_bindings.cc
  shell/renderer/api/electron_api_web_frame.cc
Labels: backport, semver/patch, 29-x-y

#40965 build: log got error response bodies
  script/prepare-appveyor.js
  script/release/ci-release-build.js
  script/release/get-url-hash.js
Labels: semver/none, target/27-x-y, target/28-x-y, target/29-x-y

#40947 refactor: use base::NoDestructor instead of base::LazyInstance
  patches/chromium/feat_add_support_for_overriding_the_base_spellchecker_download_url.patch
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/extension_action/extension_action_api.cc
  shell/browser/extensions/electron_extension_host_delegate.cc
  shell/common/asar/asar_util.cc
  shell/common/extensions/electron_extensions_client.cc
Labels: semver/patch, target/28-x-y, target/29-x-y

#40962 refactor: fix deprecated base::Base64Encode() API calls
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/29-x-y

#40997 ci: correctly export RBE_experimental_credentials_helper_args
  .circleci/config/base.yml
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none, target/29-x-y

#40982 chore: fix building blink_tests target
  patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
Labels: semver/none, no-backport

#40993 fix: check for Node.js-created module when `contextIsolation` disabled
  patches/node/chore_expose_importmoduledynamically_and.patch
  patches/node/fix_missing_include_for_node_extern.patch
  shell/common/node_bindings.cc
  spec/esm-spec.ts
  spec/fixtures/esm/import-meta/index.html
  spec/fixtures/esm/import-meta/main.mjs
  spec/fixtures/esm/import-meta/package.json
  spec/fixtures/esm/import-meta/preload.mjs
Labels: semver/patch, target/28-x-y, target/29-x-y

#41006 build: fix `mojom_ts_generator` empty module path failure
  patches/chromium/.patches
  patches/chromium/reland_mojom_ts_generator_handle_empty_module_path_identically_to.patch
Labels: backport, backport-check-skip, semver/none, 28-x-y

#40971 chore: cherry-pick 389ea9be7d68 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-389ea9be7d68.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#41014 chore: cherry-pick 3 changes from Release-5-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-c1cda70a433a.patch
  patches/v8/.patches
  patches/v8/cherry-pick-46cb67e3b296.patch
  patches/v8/cherry-pick-78dd4b31847a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#40980 refactor: remove deprecated ToInternalValue()
  shell/browser/extensions/electron_extension_loader.cc
  shell/browser/notifications/win/notification_presenter_win.cc
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#41015 chore: cherry-pick 3 changes from Release-5-M120
  patches/chromium/.patches
  patches/chromium/cherry-pick-c1cda70a433a.patch
  patches/v8/.patches
  patches/v8/cherry-pick-46cb67e3b296.patch
  patches/v8/cherry-pick-78dd4b31847a.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40981 fix: ensure an AXContext before painting
  patches/chromium/.patches
  patches/chromium/ensure_an_axcontext_before_painting.patch
Labels: backport, semver/patch, backport-check-skip, 28-x-y

#40994 fix: use `HasStyleMask(NSWindowStyleMaskResizable)` instead of `IsResizable()` for enabling/disabling window maximize button
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#41003 fix: modal rounding on nonmodal windows
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#40996 fix: crash when `dialog.showMessageBoxSync` with missing buttons
  shell/browser/ui/message_box_mac.mm
  spec/api-dialog-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#40968 feat: add net module to utility process
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/net.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/net-fetch.ts
  lib/browser/api/net.ts
  lib/browser/api/session.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  lib/utility/api/module-list.ts
  lib/utility/api/net.ts
  lib/utility/init.ts
  package.json
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/net/resolve_host_function.cc
  shell/browser/net/resolve_host_function.h
  shell/common/api/electron_api_net.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/node_bindings.cc
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/public/mojom/node_service.mojom
  spec/api-net-custom-protocols-spec.ts
  spec/api-net-session-spec.ts
  spec/api-net-spec.ts
  spec/fixtures/api/utility-process/api-net-spec.js
  spec/lib/net-helpers.ts
  typings/internal-ambient.d.ts
  yarn.lock
Labels: backport, semver/minor, backport/approved ✅, 27-x-y

#41045 test: fixup assertNotWindows
  spec/lib/window-helpers.ts
Labels: semver/none, target/29-x-y

#40972 chore: cherry-pick 389ea9be7d68 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-389ea9be7d68.patch
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#40504 feat: Windows integrity check
  BUILD.gn
  shell/common/asar/archive.cc
  shell/common/asar/archive_win.cc
Labels: platform/windows, semver/minor, api-review/requested 🗳, no-backport

#41031 ci: add stale-exempt label to exempt issues from automation
  .github/workflows/stale.yml
Labels: semver/none, no-backport

#41049 chore: cleanup tests creating crashpad handler in the test runner process
  spec/api-crash-reporter-spec.ts
  spec/api-utility-process-spec.ts
Labels: backport, semver/none, 26-x-y

#40966 docs: fixed typos and grammatical errors
  docs/tutorial/devices.md
  docs/tutorial/in-app-purchases.md
  docs/tutorial/performance.md
  docs/tutorial/process-model.md
  docs/tutorial/sandbox.md
Labels: documentation :notebook:, semver/patch, target/29-x-y

#41081 docs: update Playwright automated-testing guide
  docs/tutorial/automated-testing.md
Labels: documentation :notebook:, semver/patch, target/26-x-y, target/27-x-y, target/28-x-y, target/29-x-y

#41087 refactor: remove banned std::to_string() calls
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/browser_mac.mm
  shell/browser/electron_browser_context.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/browser/ui/accelerator_util.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/webui/accessibility_ui.cc
  shell/browser/ui/win/notify_icon.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/web_contents_preferences.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/asar/archive.cc
  shell/common/crash_keys.cc
  shell/common/keyboard_util.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/electron_render_frame_observer.cc
Labels: semver/patch, new-pr 🌱, target/28-x-y, target/29-x-y

#41033 fix: on error, reset spawnedProcess
  lib/browser/api/auto-updater/squirrel-update-win.ts
Labels: component/auto-updater, semver/patch, target/26-x-y, target/27-x-y, target/28-x-y, target/29-x-y

#41030 fix: draggable regions not working
  patches/chromium/.patches
  patches/chromium/fix_drag_regions_not_working_after_navigation_in_wco_app.patch
  shell/renderer/electron_render_frame_observer.cc
Labels: semver/patch, target/29-x-y

#41088 fix: dangling raw_ptr in OSRWHV destructor
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
Labels: semver/patch, target/28-x-y, target/29-x-y

#41111 fix: on error, reset spawnedProcess
  lib/browser/api/auto-updater/squirrel-update-win.ts
Labels: backport, semver/patch, 28-x-y

#41113 chore: remove node patches by using the preload feature
  BUILD.gn
  build/webpack/webpack.config.asar.js
  build/webpack/webpack.config.node.js
  filenames.auto.gni
  lib/asar/init.ts
  lib/node/asar-fs-wrapper.ts
  lib/node/init.ts
  patches/node/.patches
  patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/node/enable_crashpad_linux_node_processes.patch
  patches/node/feat_initialize_asar_support.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
  patches/node/src_preload_function_for_environment.patch
  script/gen-filenames.ts
  shell/app/node_main.cc
  shell/common/api/electron_api_asar.cc
  shell/common/api/electron_bindings.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_util.cc
  typings/internal-ambient.d.ts
Labels: backport, semver/none, 29-x-y

#41114 chore: remove node patches by using the preload feature
  BUILD.gn
  build/webpack/webpack.config.asar.js
  build/webpack/webpack.config.node.js
  filenames.auto.gni
  lib/asar/init.ts
  lib/node/asar-fs-wrapper.ts
  lib/node/init.ts
  patches/node/.patches
  patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/node/chore_expose_importmoduledynamically_and.patch
  patches/node/enable_crashpad_linux_node_processes.patch
  patches/node/feat_initialize_asar_support.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
  patches/node/src_preload_function_for_environment.patch
  script/gen-filenames.ts
  shell/app/node_main.cc
  shell/common/api/electron_api_asar.cc
  shell/common/api/electron_bindings.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_util.cc
  typings/internal-ambient.d.ts
Labels: backport, semver/none, 28-x-y

#41106 chore: cherry-pick 2 changes from Release-0-M121
  patches/chromium/.patches
  patches/chromium/cherry-pick-cc07a95bc309.patch
  patches/chromium/safely_crash_on_dangling_profile.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#41120 build: remove unneeded dlls in Windows zip
  appveyor-woa.yml
  appveyor.yml
  build/args/all.gn
Labels: semver/none, target/28-x-y, target/29-x-y

#41115 chore: remove node patches by using the preload feature
  BUILD.gn
  build/webpack/webpack.config.asar.js
  build/webpack/webpack.config.node.js
  filenames.auto.gni
  lib/asar/init.ts
  lib/node/asar-fs-wrapper.ts
  lib/node/init.ts
  patches/node/.patches
  patches/node/chore_allow_the_node_entrypoint_to_be_a_builtin_module.patch
  patches/node/chore_update_fixtures_errors_force_colors_snapshot.patch
  patches/node/enable_crashpad_linux_node_processes.patch
  patches/node/feat_initialize_asar_support.patch
  patches/node/refactor_alter_child_process_fork_to_use_execute_script_with.patch
  patches/node/src_preload_function_for_environment.patch
  script/gen-filenames.ts
  shell/app/node_main.cc
  shell/common/api/electron_api_asar.cc
  shell/common/api/electron_bindings.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/common/node_util.cc
  typings/internal-ambient.d.ts
Labels: backport, semver/none, 27-x-y

#41105 chore: cherry-pick 2 changes from Release-0-M121
  patches/chromium/.patches
  patches/chromium/safely_crash_on_dangling_profile.patch
Labels: security 🔒, semver/patch, backport-check-skip, 28-x-y

#41139 fix: apply module search paths restriction on worker and child process
  filenames.auto.gni
  lib/browser/init.ts
  lib/common/init.ts
  lib/common/reset-search-paths.ts
  lib/node/init.ts
  lib/renderer/init.ts
  lib/utility/init.ts
  lib/worker/init.ts
  spec/fixtures/module/module-paths.js
  spec/node-spec.ts
Labels: backport, semver/patch, 27-x-y

#40576 fix: potential `async_hooks` crash in `NotifyWindowRestore` on Windows
  shell/browser/api/electron_api_auto_updater.cc
  shell/common/gin_helper/event_emitter_caller.cc
  shell/renderer/electron_api_service_impl.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/26-x-y, target/27-x-y, target/28-x-y, target/29-x-y

#41131 fix: update osk patch to fix more corner cases
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#41152 chore: fix outdated osk patch on main branch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
Labels: fast-track 🚅, semver/none, no-backport

#41135 chore: add extra links to issue template chooser
  .github/ISSUE_TEMPLATE/config.yml
Labels: semver/none, no-backport

#41150 fix: update osk patch to fix more corner cases
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
Labels: backport, semver/patch, 28-x-y

#41151 fix: update osk patch to fix more corner cases
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
Labels: backport, semver/patch, 27-x-y

#41107 chore: cherry-pick 2 changes from Release-0-M121
  patches/chromium/.patches
  patches/chromium/cherry-pick-cc07a95bc309.patch
  patches/chromium/safely_crash_on_dangling_profile.patch
  spec/lib/window-helpers.ts
  spec/node-spec.ts
Labels: security 🔒, semver/patch, backport-check-skip, 26-x-y

#41125 refactor: inline simple getters
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/native_window_views.cc
  shell/browser/net/network_context_service.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/osr/osr_view_proxy.cc
  shell/browser/osr/osr_view_proxy.h
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/ui/views/root_view.cc
  shell/browser/ui/views/root_view.h
  shell/browser/web_contents_zoom_controller.cc
  shell/browser/web_contents_zoom_controller.h
Labels: semver/patch, target/28-x-y, target/29-x-y

#41154 fix: ensure `WebContents` before checking draggable region
  shell/browser/api/electron_api_web_contents_view.cc
Labels: semver/patch, no-backport

#41161 fix: `shouldPrintBackgrounds` -> `printBackground` in `webContents.printToPDF`
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/28-x-y, target/29-x-y

#41162 refactor: simplify code by using base::Value::EnsureList()
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/gpu_info_enumerator.cc
Labels: semver/patch, target/28-x-y, target/29-x-y

#41160 fix: avoid potential `CHECK()` failure in `DictionaryToRect()`
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/28-x-y, target/29-x-y

#41148 refactor: type-safe imports in lib/node/init.ts
  lib/node/init.ts
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#41127 test: draggable region allows moving window
  spec/api-browser-window-spec.ts
  spec/lib/screen-helpers.ts
  spec/package.json
  spec/yarn.lock
Labels: semver/none, no-backport

#41157 fix: validate `printToPDF` `margins` against `pageSize`
  lib/browser/api/web-contents.ts
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#41166 fix: `select-usb-device` should respect `filters` option
  shell/browser/usb/usb_chooser_controller.cc
Labels: semver/patch, target/27-x-y, target/28-x-y, target/29-x-y

#41168 refactor: inline simple getters
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/native_window_views.cc
  shell/browser/net/network_context_service.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/osr/osr_view_proxy.cc
  shell/browser/osr/osr_view_proxy.h
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/ui/views/root_view.cc
  shell/browser/ui/views/root_view.h
  shell/browser/web_contents_zoom_controller.cc
  shell/browser/web_contents_zoom_controller.h
Labels: backport, semver/patch, 28-x-y

#41199 fix: move nut-js to optional spec deps
  spec/package.json
Labels: fast-track 🚅, semver/none, no-backport
