Repository electron/electron, pull requests merged in 2024-12, with the labels that each got.

#44855 docs: specify default value for `respondToAuthRequestsFromMainProcess`
  docs/api/utility-process.md
Labels: documentation :notebook:, semver/patch, target/33-x-y, target/34-x-y

#44841 docs: fix a syntax issue in document breaking changes
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44900 fix: remove unused id argument from TranslateToStock()
  shell/browser/ui/message_box_gtk.cc
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44868 fix: don't use deprecated ui::MouseEvent constructor
  shell/browser/osr/osr_render_widget_host_view.cc
Labels: semver/patch, target/34-x-y

#44907 chore: remove unused isolate argument from Cookies constructor
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_cookies.h
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44906 chore: remove unused arg from BaseWindow::GetBackgroundColor()
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44852 docs: clarify what session.clearData() with data type 'cache' deletes
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, target/33-x-y, target/34-x-y

#44908 chore: remove unused registry arg from GetPrivilegeRequiredByUrl()
  shell/browser/electron_browser_client.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44204 feat: WebFrameMain.collectJavaScriptCallStack()
  docs/api/web-frame-main.md
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  spec/api-web-frame-main-spec.ts
  spec/index.js
Labels: semver/minor, api-review/approved ✅, target/33-x-y, target/34-x-y

#44920 docs: fix grammar in `app.relaunch` docs
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/34-x-y

#44918 chore: make version parsing more tolerant
  .github/workflows/issue-opened.yml
Labels: semver/none, no-backport

#44935 fix: modernize-use-equals-default warnings
  shell/browser/auto_updater.h
  shell/browser/browser_observer.h
  shell/browser/extended_web_contents_observer.h
  shell/browser/extensions/api/extension_action/extension_action_api.h
  shell/browser/extensions/api/tabs/tabs_api.h
  shell/browser/native_window_observer.h
  shell/browser/ui/electron_menu_model.h
  shell/browser/ui/inspectable_web_contents_delegate.h
  shell/browser/ui/inspectable_web_contents_view_delegate.h
  shell/browser/ui/tray_icon_observer.h
  shell/browser/ui/views/autofill_popup_view.h
  shell/browser/window_list_observer.h
  shell/common/color_util.h
  shell/common/gin_helper/event_emitter.h
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44750 feat: Add shared dictionary management APIs
  docs/api/session.md
  docs/api/structures/shared-dictionary-info.md
  docs/api/structures/shared-dictionary-usage-info.md
  filenames.auto.gni
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec/api-session-spec.ts
  spec/fixtures/api/shared-dictionary/main.js
  spec/fixtures/api/shared-dictionary/package.json
Labels: semver/minor, api-review/approved ✅, target/33-x-y, target/34-x-y

#44940 fix: `context-menu` event with `BaseWindows`
  docs/api/menu.md
  shell/browser/ui/cocoa/delayed_native_view_host.h
  shell/browser/ui/cocoa/electron_ns_window.mm
  spec/api-web-contents-spec.ts
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44960 fix: build failure when PDF viewer is disabled
  shell/browser/extensions/electron_extension_system.cc
Labels: semver/patch, new-pr 🌱, target/33-x-y, target/34-x-y

#44968 docs: update security scoped bookmarks info
  docs/api/dialog.md
Labels: documentation :notebook:, semver/patch, no-backport

#44978 fix: context-menu emitted twice
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44985 chore: update vm module warning
  lib/renderer/init.ts
Labels: semver/none, no-backport

#44989 fix: add missing index arg in `navigationHistory.canGoToOffset`
  lib/browser/api/web-contents.ts
  typings/internal-electron.d.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44136 build: use github actions for windows
  .gitattributes
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  .github/workflows/update_appveyor_image.yml
  .gitignore
  appveyor.yml
  build/zip.py
  script/actions/move-artifacts.sh
  script/generate-deps-hash.js
  script/nan-spec-runner.js
  script/spec-runner.js
  script/zip_manifests/dist_zip.win.arm64.manifest
  script/zip_manifests/dist_zip.win.x86.manifest
  spec/api-app-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-session-spec.ts
  spec/api-shell-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-contents-view-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-frame-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/pages/zoom-factor.html
  spec/index.js
  spec/lib/fs-helpers.ts
  spec/lib/window-helpers.ts
  spec/visibility-state-spec.ts
  spec/webview-spec.ts
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#45001 fix: custom spell-checker stuck in infinite loop
  shell/renderer/api/electron_api_spell_check_client.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#45023 chore: cherry-pick 1282289030ab from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-1282289030ab.patch
Labels: semver/patch, backport-check-skip, 34-x-y

#45018 build: update build tools to correct sha
  .github/actions/install-build-tools/action.yml
Labels: semver/none, no-backport

#45011 build: use github actions for windows
  .gitattributes
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  .github/workflows/update_appveyor_image.yml
  .gitignore
  appveyor.yml
  build/zip.py
  script/actions/move-artifacts.sh
  script/generate-deps-hash.js
  script/nan-spec-runner.js
  script/spec-runner.js
  script/zip_manifests/dist_zip.win.arm64.manifest
  script/zip_manifests/dist_zip.win.x86.manifest
  spec/api-app-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-session-spec.ts
  spec/api-shell-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-contents-view-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-frame-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/pages/zoom-factor.html
  spec/index.js
  spec/lib/fs-helpers.ts
  spec/lib/window-helpers.ts
  spec/visibility-state-spec.ts
  spec/webview-spec.ts
Labels: backport, semver/none, 34-x-y

#45012 build: use github actions for windows
  .gitattributes
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  .github/workflows/update_appveyor_image.yml
  .gitignore
  appveyor.yml
  build/zip.py
  script/actions/move-artifacts.sh
  script/generate-deps-hash.js
  script/nan-spec-runner.js
  script/spec-runner.js
  script/zip_manifests/dist_zip.win.arm64.manifest
  script/zip_manifests/dist_zip.win.x86.manifest
  spec/api-app-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-session-spec.ts
  spec/api-shell-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-contents-view-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-frame-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/pages/zoom-factor.html
  spec/index.js
  spec/lib/fs-helpers.ts
  spec/lib/window-helpers.ts
  spec/visibility-state-spec.ts
  spec/webview-spec.ts
Labels: backport, semver/none, 33-x-y

#45029 docs: remove extra "
  docs/fiddles/features/web-bluetooth/index.html
Labels: documentation :notebook:, semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#45040 chore: cherry-pick 3 changes from 2-M131
  patches/dawn/.patches
  patches/dawn/msl_use_packed_vec3_for_workgroup_storage.patch
  patches/dawn/tint_validate_layout_constraints_for_all_address_spaces.patch
  patches/v8/.patches
  patches/v8/m126-lts_liftoff_fix_clobbered_scratch_register.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#45039 chore: cherry-pick 3 changes from 2-M131
  patches/dawn/.patches
  patches/dawn/msl_use_packed_vec3_for_workgroup_storage.patch
  patches/dawn/tint_validate_layout_constraints_for_all_address_spaces.patch
  patches/v8/.patches
  patches/v8/merged_liftoff_fix_clobbered_scratch_register.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45017 fix: better prompt not supported message in window-setup.ts
  lib/renderer/window-setup.ts
Labels: semver/patch, target/33-x-y, target/34-x-y

#45000 fix: add patch to fix desktopCapturer.getSources not returning electron windows on Windows
  shell/browser/api/electron_api_desktop_capturer.cc
Labels: semver/patch, no-backport

#45015 build: use github actions for windows
  .gitattributes
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  .github/workflows/update_appveyor_image.yml
  .gitignore
  appveyor.yml
  build/zip.py
  script/actions/move-artifacts.sh
  script/generate-deps-hash.js
  script/nan-spec-runner.js
  script/spec-runner.js
  script/zip_manifests/dist_zip.win.arm64.manifest
  script/zip_manifests/dist_zip.win.x86.manifest
  spec/api-app-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-session-spec.ts
  spec/api-shell-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-frame-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/pages/zoom-factor.html
  spec/index.js
  spec/lib/fs-helpers.ts
  spec/lib/window-helpers.ts
  spec/webview-spec.ts
Labels: backport, semver/none, 31-x-y

#45013 build: use github actions for windows
  .gitattributes
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/install-dependencies/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  .github/workflows/update_appveyor_image.yml
  .gitignore
  appveyor.yml
  build/zip.py
  script/actions/move-artifacts.sh
  script/generate-deps-hash.js
  script/nan-spec-runner.js
  script/spec-runner.js
  script/zip_manifests/dist_zip.win.arm64.manifest
  script/zip_manifests/dist_zip.win.x86.manifest
  spec/api-app-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-session-spec.ts
  spec/api-shell-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-contents-view-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-frame-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/pages/zoom-factor.html
  spec/index.js
  spec/lib/fs-helpers.ts
  spec/lib/window-helpers.ts
  spec/webview-spec.ts
Labels: backport, semver/none, 32-x-y

#45062 test: reenable disabled GHA windows tests
  spec/api-shell-spec.ts
  spec/chromium-spec.ts
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y
