Repository electron/electron, pull requests merged in 2024-09, with the labels that each got.

#43533 build: free up macos disk space as soon as possible
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
Labels: fast-track 🚅, semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43477 fix: -Wunsafe-buffer-usage warnings in IsUrlArg()
  shell/app/command_line_args.cc
  shell/app/command_line_args.h
  shell/app/electron_main_win.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43517 fix: systemMediaPermissionDenied should not check camera perms when the request is asking for screen share
  shell/browser/web_contents_permission_helper.cc
Labels: semver/patch, backport/requested 🗳, target/32-x-y, target/33-x-y

#43538 build: free up macos disk space as soon as possible
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
Labels: backport, semver/none, target/30-x-y, 31-x-y

#43481 fix: Use XDG_ACTIVATION_TOKEN in wayland when launched by other app
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_app.cc
Labels: platform/linux, semver/patch, wayland, target/31-x-y, target/32-x-y, target/33-x-y

#43518 fix: don't use deprecate-soon class v8::String::Value
  shell/common/gin_converters/file_path_converter.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43554 build: don't run symbol generation on PS
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43527 refactor: declare gin::Wrapper subclasses as final
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_auto_updater.h
  shell/browser/api/electron_api_cookies.h
  shell/browser/api/electron_api_data_pipe_holder.h
  shell/browser/api/electron_api_debugger.h
  shell/browser/api/electron_api_desktop_capturer.h
  shell/browser/api/electron_api_download_item.h
  shell/browser/api/electron_api_global_shortcut.h
  shell/browser/api/electron_api_in_app_purchase.h
  shell/browser/api/electron_api_native_theme.h
  shell/browser/api/electron_api_net_log.h
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_power_monitor.h
  shell/browser/api/electron_api_power_save_blocker.h
  shell/browser/api/electron_api_protocol.h
  shell/browser/api/electron_api_push_notifications.h
  shell/browser/api/electron_api_screen.h
  shell/browser/api/electron_api_service_worker_context.h
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_tray.h
  shell/browser/api/electron_api_utility_process.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.h
  shell/browser/api/electron_api_web_request.h
  shell/browser/api/message_port.h
  shell/common/api/electron_api_native_image.h
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_helper/event.h
  shell/renderer/api/electron_api_ipc_renderer.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/services/node/parent_port.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43535 chore: migrate to v8::Object::SetPrototypeV2()
  shell/common/gin_helper/event_emitter_template.cc
Labels: semver/patch, no-backport

#43519 perf: use v8::Local<v8::Object> as the key in ObjectCache
  shell/renderer/api/context_bridge/object_cache.cc
  shell/renderer/api/context_bridge/object_cache.h
Labels: performance :checkered_flag:, semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43563 build: fix telemetry error when using autoninja
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43562 ci: remove blocked/need-info label on user comment
  .github/workflows/issue-commented.yml
Labels: semver/none, no-backport

#43455 docs: explain ipcRenderer behavior in context-bridge.md
  docs/api/context-bridge.md
Labels: documentation :notebook:, semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43550 build: use proper targets for building
  .github/actions/build-electron/action.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43564 fix: -Wunsafe-buffer-usage warnings in url-loader
  shell/common/api/electron_api_url_loader.cc
Labels: semver/patch, no-backport

#43570 fix: ensure version of `xdg-dialog-portal` with `defaultPath` support
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43561 fix: delete UvTaskRunner's timers only after they're closed
  shell/app/uv_task_runner.cc
  shell/app/uv_task_runner.h
  shell/common/node_bindings.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43575 fix: confirm a `v8::Value` is a `v8::Object` before casting it
  shell/browser/api/message_port.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43576 refactor: `NativeWindow::Create()` returns a unique_ptr
  shell/browser/api/electron_api_base_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43592 refactor: take a `uint8_t` span in `ValidateIntegrityOrDie()`
  shell/common/asar/archive.cc
  shell/common/asar/asar_util.cc
  shell/common/asar/asar_util.h
  shell/common/asar/scoped_temporary_file.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43609 perf: avoid redundant Promise.GetContext calls
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43463 fix: update `BrowserView#lastWindowSize` after window resize
  lib/browser/api/browser-view.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43631 fix: ensure version of `xdg-dialog-portal` with `defaultPath` support
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Labels: backport, semver/patch, 30-x-y

#43621 refactor: use std::optional in MicrotasksScope
  shell/common/gin_helper/microtasks_scope.cc
  shell/common/gin_helper/microtasks_scope.h
Labels: semver/patch, no-backport

#43622 fix: out-of-scope Local handle in node::CallbackScope
  shell/common/gin_helper/event_emitter_caller.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43630 fix: ensure version of `xdg-dialog-portal` with `defaultPath` support
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Labels: backport, semver/patch, 31-x-y

#43624 fix: -Wunsafe-buffer-usage warnings in asar file IO
  shell/common/asar/archive.cc
  shell/common/asar/scoped_temporary_file.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43647 test: add -pdf-ready-to-print event to WebContents for testing
  BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_pdf_document_helper_client.cc
  shell/browser/electron_pdf_document_helper_client.h
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, 32-x-y

#43646 chore: remove unused ConvertableToTraceFormatWrapper
  shell/browser/javascript_environment.cc
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, 32-x-y

#43645 build: fix patchup logic only running on one platform
  .github/actions/checkout/action.yml
  .github/workflows/build.yml
Labels: backport, semver/none, target/30-x-y, target/31-x-y, 32-x-y

#43644 fix: ensure bounds stability in `OnWidgetBoundsChanged`
  shell/browser/native_window_views.cc
Labels: backport, semver/patch, target/31-x-y, 32-x-y

#43643 fix: printing occasionally showing failed when cancelled
  patches/chromium/printing.patch
Labels: backport, semver/patch, 32-x-y

#43611 fix: restore Chromium default `Content-Disposition` header parsing
  shell/browser/api/electron_api_web_request.cc
  spec/api-web-request-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43642 fix: -Wunsafe-buffer-usage warning in V8Serializer::Serialize()
  shell/common/v8_value_serializer.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43581 feat: add support for system picker in setDisplayMediaRequestHandler
  docs/api/desktop-capturer.md
  docs/api/session.md
  filenames.gni
  lib/browser/api/desktop-capturer.ts
  lib/browser/api/session.ts
  patches/chromium/.patches
  patches/chromium/feat_allow_usage_of_sccontentsharingpicker_on_supported_platforms.patch
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_desktop_capturer.h
  shell/browser/api/electron_api_desktop_capturer_mac.mm
  shell/browser/api/electron_api_session.cc
  shell/browser/feature_list.cc
  shell/browser/feature_list.h
  shell/browser/feature_list_mac.mm
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/32-x-y, needs-docs, target/33-x-y

#43667 fix: ensure `SetPluginCanSave` updated in PDFs
  shell/browser/electron_pdf_document_helper_client.cc
  shell/browser/electron_pdf_document_helper_client.h
Labels: semver/patch, target/32-x-y, target/33-x-y

#43638 fix: native `View` wrapper crash missing when adding child view
  shell/browser/ui/cocoa/delayed_native_view_host.mm
  spec/api-view-spec.ts
  spec/api-web-contents-view-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43685 fix: EyeDropper working in devtools
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43688 chore: remove unused base/ includes
  build/fuses/build.py
  shell/app/electron_main_linux.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/message_port.cc
  shell/browser/badging/badge_manager_factory.cc
  shell/browser/browser.cc
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/extension_action/extension_action_api.cc
  shell/browser/extensions/api/management/electron_management_api_delegate.cc
  shell/browser/extensions/electron_extension_host_delegate.cc
  shell/browser/extensions/electron_extension_loader.cc
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/extensions/electron_process_manager_delegate.cc
  shell/browser/fake_location_provider.cc
  shell/browser/file_system_access/file_system_access_permission_context_factory.cc
  shell/browser/javascript_environment.cc
  shell/browser/net/asar/asar_file_validator.cc
  shell/browser/notifications/win/notification_presenter_win.cc
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/special_storage_policy.cc
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/browser/ui/cocoa/window_buttons_proxy.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/views/global_menu_bar_x11.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/window_list.cc
  shell/browser/zoom_level_delegate.cc
  shell/common/api/electron_api_command_line.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/application_info_win.cc
  shell/common/color_util.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_helper/trackable_object.h
  shell/common/gin_helper/wrappable.cc
  shell/common/node_bindings_win.cc
  shell/renderer/api/electron_api_crash_reporter_renderer.cc
  shell/renderer/renderer_client_base.cc
  shell/utility/electron_content_utility_client.cc
Labels: semver/patch, no-backport

#43402 feat: hide menu bar on windows fullscreen
  docs/breaking-changes.md
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#43690 refactor: remove use of deprecated API BuildServiceInstanceFor()
  shell/browser/badging/badge_manager_factory.cc
  shell/browser/badging/badge_manager_factory.h
  shell/browser/extensions/electron_extension_system_factory.cc
  shell/browser/extensions/electron_extension_system_factory.h
  shell/browser/file_system_access/file_system_access_permission_context_factory.cc
  shell/browser/file_system_access/file_system_access_permission_context_factory.h
  shell/browser/hid/hid_chooser_context_factory.cc
  shell/browser/hid/hid_chooser_context_factory.h
  shell/browser/net/network_context_service_factory.cc
  shell/browser/net/network_context_service_factory.h
  shell/browser/serial/serial_chooser_context_factory.cc
  shell/browser/serial/serial_chooser_context_factory.h
  shell/browser/usb/usb_chooser_context_factory.cc
  shell/browser/usb/usb_chooser_context_factory.h
Labels: semver/patch, target/32-x-y, target/33-x-y

#43673 docs: document View.removeChildView edge case
  docs/api/view.md
Labels: documentation :notebook:, semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43701 ci: move Archaeologist to GHA
  .github/actions/generate-types/action.yml
  .github/workflows/archaeologist-dig.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43722 refactor: add `EmitWarning(v8::Isolate*)` helper
  shell/browser/api/electron_api_debugger.cc
  shell/browser/api/electron_api_download_item.cc
  shell/browser/api/electron_api_net_log.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/native_window_mac.mm
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/usb/usb_chooser_controller.cc
  shell/common/crash_keys.cc
  shell/common/gin_converters/osr_converter.cc
  shell/common/node_bindings_mac.cc
  shell/common/node_util.cc
  shell/common/node_util.h
  shell/common/process_util.cc
  shell/common/process_util.h
  shell/common/skia_util.cc
Labels: semver/patch, new-pr 🌱, target/33-x-y

#43716 refactor: reduce code duplication in gin_helper::Promise
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_crypto_module_delegate_nss.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/ui/devtools_manager_delegate.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
Labels: semver/patch, target/33-x-y

#43737 build: make is_mas_build a generated header instead of config
  BUILD.gn
  build/config/BUILD.gn
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/disable_compositor_recycling.patch
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
  patches/chromium/feat_ensure_mas_builds_of_the_same_application_can_use_safestorage.patch
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  patches/chromium/osr_shared_texture_remove_keyed_mutex_on_win_dxgi.patch
  patches/chromium/printing.patch
  script/generate-mas-config.py
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_mac.cc
  shell/app/node_main.cc
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/process_metric.cc
  shell/browser/auto_updater.cc
  shell/browser/browser_mac.mm
  shell/browser/notifications/mac/notification_center_delegate.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/file_dialog_mac.mm
  shell/common/api/electron_bindings.cc
  shell/common/node_bindings.cc
  shell/common/platform_util_mac.mm
  shell/renderer/api/electron_api_crash_reporter_renderer.cc
Labels: semver/none, no-backport

#43736 refactor: add `EmitWarning(v8::Isolate*)` helper
  shell/browser/api/electron_api_debugger.cc
  shell/browser/api/electron_api_download_item.cc
  shell/browser/api/electron_api_net_log.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/native_window_mac.mm
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/usb/usb_chooser_controller.cc
  shell/common/crash_keys.cc
  shell/common/node_bindings_mac.cc
  shell/common/node_util.cc
  shell/common/node_util.h
  shell/common/process_util.cc
  shell/common/process_util.h
  shell/common/skia_util.cc
Labels: backport, semver/patch, 33-x-y

#43724 fix: resizing border on Linux WCO caption buttons
  shell/browser/ui/views/opaque_frame_view.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43729 fix: in `Emit()`, don't leak converted Arg `Local<Values>` into caller's scope
  shell/common/gin_helper/event_emitter_caller.h
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43732 ci: move Archaeologist to GHA
  .github/actions/generate-types/action.yml
  .github/workflows/archaeologist-dig.yml
Labels: backport, semver/none, 33-x-y

#43741 chore: iwyu mojom-forward header files
  shell/browser/api/electron_api_cookies.h
  shell/browser/api/electron_api_power_monitor_win.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.h
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
  shell/browser/extended_web_contents_observer.h
  shell/browser/extensions/api/scripting/scripting_api.h
  shell/browser/extensions/api/streams_private/streams_private_api.h
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/hid/hid_chooser_controller.h
  shell/browser/media/media_capture_devices_dispatcher.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/net/electron_url_loader_factory.h
  shell/browser/net/network_context_service.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/net/resolve_host_function.h
  shell/browser/net/system_network_context_manager.cc
  shell/browser/net/system_network_context_manager.h
  shell/browser/serial/serial_chooser_controller.h
  shell/browser/ui/drag_util.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/win/taskbar_host.cc
  shell/browser/usb/usb_chooser_controller.h
  shell/browser/web_contents_permission_helper.cc
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/content_converter.h
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  shell/common/gin_helper/event_emitter.h
Labels: semver/patch, new-pr 🌱, target/33-x-y

#43756 build: improve logging on http errors during release process
  script/release/get-asset.js
  script/release/get-url-hash.js
  script/release/release.js
Labels: semver/none, no-backport

#43757 build: improve logging on http errors during release process (again)
  script/release/get-asset.js
  script/release/release.js
Labels: fast-track 🚅, semver/none

#43758 build: improve logging on http errors during release process (again, but more)
  script/release/release.js
Labels: fast-track 🚅, no-backport

#43759 build: improve logging on http errors during release process
  script/release/get-asset.js
  script/release/get-url-hash.js
  script/release/release.js
Labels: target/30-x-y, target/31-x-y, target/32-x-y

#43754 build: split darwin/mas macOS publish jobs
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43750 perf: hold `Emit()` arg arrays in a `std::array`
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/event_emitter_caller.h
Labels: performance :checkered_flag:, semver/patch, target/33-x-y

#43788 build: let darwin/mas run concurrently
  .github/workflows/pipeline-segment-electron-build.yml
Labels: fast-track 🚅, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43752 perf: hold `V8FunctionInvoker` args in a `std::array`
  shell/common/gin_helper/callback.h
Labels: performance :checkered_flag:, semver/patch, target/33-x-y

#43786 fix: EyeDropper working in devtools (32-x-y)
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: backport, semver/patch, 32-x-y

#43785 build: compile Node.js with C++20 support (32-x-y)
  .github/workflows/build.yml
  patches/node/.patches
  patches/node/build_compile_with_c_20_support.patch
  script/spec-runner.js
Labels: backport, semver/patch, 32-x-y

#43783 refactor: declare gin::Wrapper subclasses as final
  shell/browser/api/electron_api_app.h
  shell/browser/api/electron_api_auto_updater.h
  shell/browser/api/electron_api_cookies.h
  shell/browser/api/electron_api_data_pipe_holder.h
  shell/browser/api/electron_api_debugger.h
  shell/browser/api/electron_api_desktop_capturer.h
  shell/browser/api/electron_api_download_item.h
  shell/browser/api/electron_api_global_shortcut.h
  shell/browser/api/electron_api_in_app_purchase.h
  shell/browser/api/electron_api_native_theme.h
  shell/browser/api/electron_api_net_log.h
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_power_monitor.h
  shell/browser/api/electron_api_power_save_blocker.h
  shell/browser/api/electron_api_protocol.h
  shell/browser/api/electron_api_push_notifications.h
  shell/browser/api/electron_api_screen.h
  shell/browser/api/electron_api_service_worker_context.h
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_tray.h
  shell/browser/api/electron_api_utility_process.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.h
  shell/browser/api/electron_api_web_request.h
  shell/browser/api/message_port.h
  shell/common/api/electron_api_native_image.h
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_helper/event.h
  shell/renderer/api/electron_api_ipc_renderer.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/services/node/parent_port.h
Labels: backport, semver/patch, 31-x-y

#43777 chore: iwyu mojom-forward header files (33-x-y)
  shell/browser/api/electron_api_cookies.h
  shell/browser/api/electron_api_power_monitor_win.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.h
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
  shell/browser/extended_web_contents_observer.h
  shell/browser/extensions/api/scripting/scripting_api.h
  shell/browser/extensions/api/streams_private/streams_private_api.h
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/hid/hid_chooser_controller.h
  shell/browser/media/media_capture_devices_dispatcher.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/net/electron_url_loader_factory.h
  shell/browser/net/network_context_service.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/net/resolve_host_function.h
  shell/browser/net/system_network_context_manager.cc
  shell/browser/net/system_network_context_manager.h
  shell/browser/serial/serial_chooser_controller.h
  shell/browser/ui/drag_util.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/win/taskbar_host.cc
  shell/browser/usb/usb_chooser_controller.h
  shell/browser/web_contents_permission_helper.cc
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/content_converter.h
  shell/common/gin_converters/net_converter.cc
  shell/common/gin_converters/net_converter.h
  shell/common/gin_helper/event_emitter.h
Labels: backport, semver/patch, 33-x-y

#43780 refactor: remove use of deprecated API `BuildServiceInstanceFor()` (32-x-y)
  shell/browser/badging/badge_manager_factory.cc
  shell/browser/badging/badge_manager_factory.h
  shell/browser/extensions/electron_extension_system_factory.cc
  shell/browser/extensions/electron_extension_system_factory.h
  shell/browser/file_system_access/file_system_access_permission_context_factory.cc
  shell/browser/file_system_access/file_system_access_permission_context_factory.h
  shell/browser/hid/hid_chooser_context_factory.cc
  shell/browser/hid/hid_chooser_context_factory.h
  shell/browser/net/network_context_service_factory.cc
  shell/browser/net/network_context_service_factory.h
  shell/browser/serial/serial_chooser_context_factory.cc
  shell/browser/serial/serial_chooser_context_factory.h
  shell/browser/usb/usb_chooser_context_factory.cc
  shell/browser/usb/usb_chooser_context_factory.h
Labels: backport, semver/patch, 32-x-y

#43781 docs: update window customization tutorial (33-x-y)
  docs/tutorial/window-customization.md
Labels: documentation :notebook:, backport, semver/patch, 33-x-y

#43782 refactor: remove use of deprecated API BuildServiceInstanceFor() (31-x-y)
  shell/browser/badging/badge_manager_factory.cc
  shell/browser/badging/badge_manager_factory.h
  shell/browser/extensions/electron_extension_system_factory.cc
  shell/browser/extensions/electron_extension_system_factory.h
  shell/browser/file_system_access/file_system_access_permission_context_factory.cc
  shell/browser/file_system_access/file_system_access_permission_context_factory.h
  shell/browser/hid/hid_chooser_context_factory.cc
  shell/browser/hid/hid_chooser_context_factory.h
  shell/browser/net/network_context_service_factory.cc
  shell/browser/net/network_context_service_factory.h
  shell/browser/serial/serial_chooser_context_factory.cc
  shell/browser/serial/serial_chooser_context_factory.h
  shell/browser/usb/usb_chooser_context_factory.cc
  shell/browser/usb/usb_chooser_context_factory.h
Labels: backport, semver/patch, 31-x-y

#43778 refactor: reduce code duplication in gin_helper::Promise (33-x-y)
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_crypto_module_delegate_nss.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/ui/devtools_manager_delegate.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
Labels: backport, semver/patch, 33-x-y

#43773 chore: fix compile issue about ambiguous error of multiple methods named 'highlight'.
  shell/browser/ui/message_box_mac.mm
Labels: semver/patch, target/32-x-y, target/33-x-y

#43794 refactor: NotificationPresenter::Create() returns a std::unique_ptr<>
  shell/browser/electron_browser_client.cc
  shell/browser/notifications/linux/notification_presenter_linux.cc
  shell/browser/notifications/mac/notification_presenter_mac.mm
  shell/browser/notifications/notification_presenter.h
  shell/browser/notifications/win/notification_presenter_win.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43767 fix: third time screen sharing on macOS
  lib/browser/api/session.ts
  patches/chromium/.patches
  patches/chromium/feat_allow_-4_as_a_macos_screen_share_id.patch
Labels: semver/patch, target/32-x-y, target/33-x-y

#43795 fix: -Wunsafe-buffer-usage warnings in Clipboard::WriteBuffer()
  shell/common/api/electron_api_clipboard.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43787 docs: document Windows pitfall when updating patches
  docs/development/patches.md
Labels: documentation :notebook:, semver/patch, target/33-x-y

#43775 fix: `createWindow` shouldn't load URL for `webContents`
  lib/browser/guest-window-manager.ts
  spec/guest-window-manager-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43803 fix: -Wunsafe-buffer-usage warnings in GetNextZoomLevel()
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43755 build: enable dependabot on supported branches
  .github/dependabot.yml
Labels: semver/none, no-backport

#43871 build: stop dependabot doing things
  .github/dependabot.yml
Labels: fast-track 🚅, semver/none, no-backport

#43874 build: update-check-skip on dependabot backport PRs
  .github/dependabot.yml
Labels: semver/none, no-backport

#43808 build: add support for fetching github token from sudowoodo
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  script/release/ci-release-build.js
  script/release/find-github-release.js
  script/release/get-asset.js
  script/release/github-token.js
  script/release/notes/index.js
  script/release/notes/notes.js
  script/release/prepare-release.js
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/uploaders/upload-to-github.ts
  spec/fixtures/release-notes/cache/electron-electron-commit-029127a8b6f7c511fca4612748ad5b50e43aadaa
  spec/fixtures/release-notes/cache/electron-electron-commit-8f7a48879ef8633a76279803637cdee7f7c6cd4f
  spec/fixtures/release-notes/cache/electron-electron-commit-9d0e6d09f0be0abbeae46dd3d66afd96d2daacaa
  spec/fixtures/release-notes/cache/electron-electron-commit-d6c8ff2e7050f30dffd784915bcbd2a9f993cdb2
  spec/fixtures/release-notes/cache/electron-electron-commit-d9ba26273ad3e7a34c905eccbd5dabda4eb7b402
  spec/fixtures/release-notes/cache/electron-electron-issue-39714-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-39944-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-40045-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-40076-comments
  spec/fixtures/release-notes/cache/electron-electron-pull-39714
  spec/fixtures/release-notes/cache/electron-electron-pull-39745
  spec/fixtures/release-notes/cache/electron-electron-pull-39944
  spec/fixtures/release-notes/cache/electron-electron-pull-40045
  spec/fixtures/release-notes/cache/electron-electron-pull-40076
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#42980 docs: navigation history example
  docs/README.md
  docs/fiddles/features/navigation-history/index.html
  docs/fiddles/features/navigation-history/main.js
  docs/fiddles/features/navigation-history/preload.js
  docs/fiddles/features/navigation-history/renderer.js
  docs/fiddles/features/navigation-history/style.css
  docs/tutorial/navigation-history.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y

#43234 docs: add advanced specification for Squirrel updater
  docs/api/auto-updater.md
  docs/tutorial/updates.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y

#43877 fix: `createWindow` shouldn't load URL for `webContents`
  lib/browser/guest-window-manager.ts
  spec/guest-window-manager-spec.ts
Labels: backport, semver/patch, 32-x-y

#43878 fix: `createWindow` shouldn't load URL for `webContents`
  lib/browser/guest-window-manager.ts
  spec/guest-window-manager-spec.ts
Labels: backport, semver/patch, 31-x-y

#43887 build: add support for fetching github token from sudowoodo
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  script/release/ci-release-build.js
  script/release/find-github-release.js
  script/release/get-asset.js
  script/release/github-token.js
  script/release/notes/index.js
  script/release/notes/notes.js
  script/release/prepare-release.js
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/uploaders/upload-to-github.ts
  spec/fixtures/release-notes/cache/electron-electron-commit-029127a8b6f7c511fca4612748ad5b50e43aadaa
  spec/fixtures/release-notes/cache/electron-electron-commit-8f7a48879ef8633a76279803637cdee7f7c6cd4f
  spec/fixtures/release-notes/cache/electron-electron-commit-9d0e6d09f0be0abbeae46dd3d66afd96d2daacaa
  spec/fixtures/release-notes/cache/electron-electron-commit-d6c8ff2e7050f30dffd784915bcbd2a9f993cdb2
  spec/fixtures/release-notes/cache/electron-electron-commit-d9ba26273ad3e7a34c905eccbd5dabda4eb7b402
  spec/fixtures/release-notes/cache/electron-electron-issue-39714-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-39944-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-40045-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-40076-comments
  spec/fixtures/release-notes/cache/electron-electron-pull-39714
  spec/fixtures/release-notes/cache/electron-electron-pull-39745
  spec/fixtures/release-notes/cache/electron-electron-pull-39944
  spec/fixtures/release-notes/cache/electron-electron-pull-40045
  spec/fixtures/release-notes/cache/electron-electron-pull-40076
Labels: backport, semver/none, 30-x-y

#43888 build: add support for fetching github token from sudowoodo
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  script/release/ci-release-build.js
  script/release/find-github-release.js
  script/release/get-asset.js
  script/release/github-token.js
  script/release/notes/index.js
  script/release/notes/notes.js
  script/release/prepare-release.js
  script/release/publish-to-npm.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/release/uploaders/upload-to-github.ts
  spec/fixtures/release-notes/cache/electron-electron-commit-029127a8b6f7c511fca4612748ad5b50e43aadaa
  spec/fixtures/release-notes/cache/electron-electron-commit-8f7a48879ef8633a76279803637cdee7f7c6cd4f
  spec/fixtures/release-notes/cache/electron-electron-commit-9d0e6d09f0be0abbeae46dd3d66afd96d2daacaa
  spec/fixtures/release-notes/cache/electron-electron-commit-d6c8ff2e7050f30dffd784915bcbd2a9f993cdb2
  spec/fixtures/release-notes/cache/electron-electron-commit-d9ba26273ad3e7a34c905eccbd5dabda4eb7b402
  spec/fixtures/release-notes/cache/electron-electron-issue-39714-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-39944-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-40045-comments
  spec/fixtures/release-notes/cache/electron-electron-issue-40076-comments
  spec/fixtures/release-notes/cache/electron-electron-pull-39714
  spec/fixtures/release-notes/cache/electron-electron-pull-39745
  spec/fixtures/release-notes/cache/electron-electron-pull-39944
  spec/fixtures/release-notes/cache/electron-electron-pull-40045
  spec/fixtures/release-notes/cache/electron-electron-pull-40076
Labels: backport, semver/none, 31-x-y

#43894 fix: -Wunsafe-buffer-usage warnings in GetNextZoomLevel()
  shell/browser/ui/inspectable_web_contents.cc
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, 32-x-y

#43893 refactor: hide printing impl details in api::WebContents
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/bluetooth/electron_bluetooth_delegate.cc
Labels: semver/patch, new-pr 🌱, target/33-x-y

#43883 refactor: prefer member initializers in asar structs
  shell/common/asar/archive.cc
  shell/common/asar/archive.h
Labels: semver/patch, new-pr 🌱, target/33-x-y

#43884 refactor: remove C-style void arg type for no-arg functions
  shell/browser/osr/osr_render_widget_host_view.h
  shell/common/platform_util_win.cc
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y

#43823 refactor: add SerialChooserController::web_contents_
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/serial/serial_chooser_controller.h
Labels: semver/patch, target/33-x-y

#43627 fix: detach native view when its removed from parent on macOS
  shell/browser/ui/cocoa/delayed_native_view_host.mm
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43896 fix: -Wunsafe-buffer-usage warning in asar_util's ReadFileToString()
  shell/common/asar/asar_util.cc
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y

#43921 fix: crash when focusing `WebView` `webContents`
  shell/browser/api/electron_api_web_contents.cc
  spec/api-web-contents-spec.ts
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y

#43938 test: add tests dbus notification images
  spec/api-notification-dbus-spec.ts
  spec/fixtures/assets/notification_icon.png
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y

#43928 test: ensure `sender-pid` hint is set in Linux notifications
  BUILD.gn
  shell/browser/notifications/linux/libnotify_notification.cc
  spec/api-notification-dbus-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43905 fix: SCContentSharingPicker crash in iframes
  patches/chromium/.patches
  patches/chromium/feat_allow_-4_as_a_macos_screen_share_id.patch
  patches/chromium/feat_allow_usage_of_sccontentsharingpicker_on_supported_platforms.patch
Labels: semver/patch, target/32-x-y, target/33-x-y

#43882 build: update some build dependencies
  .eslintrc.json
  appveyor-woa.yml
  default_app/main.ts
  docs/api/base-window.md
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/session.md
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/touch-bar.ts
  lib/browser/api/web-contents.ts
  lib/browser/default-menu.ts
  lib/browser/devtools.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  npm/install.js
  package.json
  script/doc-only-change.js
  script/lib/get-version.js
  script/lib/utils.js
  script/lint.js
  script/release/prepare-release.js
  script/release/release-artifact-cleanup.js
  script/release/release.js
  script/spec-runner.js
  spec/api-browser-window-spec.ts
  spec/api-context-bridge-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-ipc-renderer-spec.ts
  spec/api-net-spec.ts
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/fixtures/api/singleton-data/main.js
  spec/fixtures/api/utility-process/net.js
  spec/fixtures/native-addon/uv-dlopen/index.js
  spec/lib/video-helpers.js
  spec/package.json
  spec/security-warnings-spec.ts
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
  spec/webview-spec.ts
  spec/yarn.lock
  tsconfig.json
  typings/internal-electron.d.ts
  yarn.lock
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43968 test: re-enable tests that were disabled in chromium rolls
  docs/breaking-changes.md
  spec/api-browser-window-spec.ts
  spec/extensions-spec.ts
Labels: semver/none, no-backport

#43956 fix: -Wunsafe-buffer-usage warnings in GdkPixbufFromSkBitmap()
  shell/browser/ui/gtk_util.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43960 perf: build g_dgettext domain name at compile time
  shell/browser/ui/gtk_util.cc
Labels: performance :checkered_flag:, semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43964 chore: remove unused nogncheck includes
  shell/app/electron_content_client.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/browser_linux.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/electron_extensions_api_client.cc
  shell/browser/notifications/linux/libnotify_notification.cc
  shell/browser/ui/file_dialog_linux.cc
  shell/common/application_info_linux.cc
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/33-x-y

#43774 feat: add error event for utility process
  docs/api/utility-process.md
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  shell/common/node_includes.h
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/public/mojom/node_service.mojom
  spec/.gitignore
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/external-ab-test.js
  spec/fixtures/native-addon/external-ab/binding.cc
  spec/fixtures/native-addon/external-ab/binding.gyp
  spec/fixtures/native-addon/external-ab/lib/test-array-buffer.js
  spec/fixtures/native-addon/external-ab/package.json
  spec/package.json
  spec/yarn.lock
Labels: semver/minor, api-review/approved ✅, target/32-x-y, target/33-x-y

#43972 fix: remove resize listener when BrowserWindow closed
  lib/browser/api/browser-view.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44002 build: use Node 20 in Appveyor images (33-x-y)
  appveyor-woa.yml
  appveyor.yml
  script/setup-win-for-dev.bat
Labels: backport, semver/none, 33-x-y

#43990 ci: write test logging to console on Windows
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43998 fix: ensure correct `WebContents` when checking `PDFReadyToPrint` (33-x-y)
  shell/browser/electron_pdf_document_helper_client.cc
  spec/api-web-contents-spec.ts
Labels: backport, semver/patch, target/31-x-y, target/32-x-y, 33-x-y

#44003 fix: FTBFS when building with `enable_plugins = false`
  BUILD.gn
  filenames.gni
  shell/browser/electron_browser_client.cc
  shell/browser/printing/printing_utils.cc
Labels: semver/patch, fast-track 🚅, target/33-x-y

#43997 feat: add error event for utility process (33-x-y)
  docs/api/utility-process.md
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  shell/common/node_includes.h
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/public/mojom/node_service.mojom
  spec/.gitignore
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/external-ab-test.js
  spec/fixtures/native-addon/external-ab/binding.cc
  spec/fixtures/native-addon/external-ab/binding.gyp
  spec/fixtures/native-addon/external-ab/lib/test-array-buffer.js
  spec/fixtures/native-addon/external-ab/package.json
  spec/package.json
  spec/yarn.lock
Labels: backport, semver/minor, backport/requested 🗳, target/32-x-y, 33-x-y

#44014 fix: -Wunsafe-buffer-usage in electron::SetFontDefaults()
  shell/browser/font_defaults.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44024 fix: -Wunsafe-buffer-usage warnings in AddComponentResourceEntries()
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/extensions/electron_component_extension_resource_manager.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44030 fix: -Wunsafe-buffer-usage in electron::SetFontDefaults() (32-x-y)
  shell/browser/font_defaults.cc
Labels: backport, semver/patch, target/31-x-y, 32-x-y

#44026 build: update appveyor to node 20.17
  appveyor-woa.yml
  appveyor.yml
  script/setup-win-for-dev.bat
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y
