Repository electron/electron, pull requests merged in 2024-04, with the labels that each got.

#41639 build: add GH Actions to release-build script
  script/release/ci-release-build.js
Labels: semver/none, no-backport

#41748 chore: cherry-pick 8 changes from Release-1-M123
  patches/angle/.patches
  patches/angle/m123_vulkan_fix_access_to_inactive_attributes.patch
  patches/chromium/.patches
  patches/chromium/fix_paintimage_deserialization_arbitrary-read_issue.patch
  patches/chromium/m122_webcodecs_disable_async_videoframe_readback_to_mitigate_a.patch
  patches/chromium/reland_sensors_winrt_call_onreadingchangedcallback_via.patch
  patches/config.json
  patches/dxc/.patches
  patches/dxc/fix_hlmatrixlowerpass_leaving_call_to_dangling_functionval.patch
  patches/libvpx/.patches
  patches/libvpx/fix_to_buffer_alloc_for_vp9_bitstream_worker_data.patch
  patches/libvpx/vp9_fix_to_integer_overflow_test.patch
  patches/v8/.patches
  patches/v8/merged_wasm_check_for_type-definition_count_limit.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#41746 chore: cherry-pick 8 changes from Release-1-M123
  patches/angle/.patches
  patches/angle/m123_vulkan_fix_access_to_inactive_attributes.patch
  patches/chromium/.patches
  patches/chromium/fix_paintimage_deserialization_arbitrary-read_issue.patch
  patches/chromium/m122_webcodecs_disable_async_videoframe_readback_to_mitigate_a.patch
  patches/chromium/reland_sensors_winrt_call_onreadingchangedcallback_via.patch
  patches/config.json
  patches/dxc/.patches
  patches/dxc/fix_hlmatrixlowerpass_leaving_call_to_dangling_functionval.patch
  patches/libvpx/.patches
  patches/libvpx/fix_to_buffer_alloc_for_vp9_bitstream_worker_data.patch
  patches/libvpx/vp9_fix_to_integer_overflow_test.patch
  patches/v8/.patches
  patches/v8/merged_wasm_check_for_type-definition_count_limit.patch
Labels: security 🔒, semver/patch, backport-check-skip, 29-x-y

#41747 chore: cherry-pick 8 changes from Release-1-M123
  patches/angle/.patches
  patches/angle/m123_vulkan_fix_access_to_inactive_attributes.patch
  patches/chromium/.patches
  patches/chromium/fix_paintimage_deserialization_arbitrary-read_issue.patch
  patches/chromium/m122_webcodecs_disable_async_videoframe_readback_to_mitigate_a.patch
  patches/chromium/reland_sensors_winrt_call_onreadingchangedcallback_via.patch
  patches/config.json
  patches/dxc/.patches
  patches/dxc/fix_hlmatrixlowerpass_leaving_call_to_dangling_functionval.patch
  patches/libvpx/.patches
  patches/libvpx/fix_to_buffer_alloc_for_vp9_bitstream_worker_data.patch
  patches/libvpx/vp9_fix_to_integer_overflow_test.patch
  patches/v8/.patches
  patches/v8/merged_wasm_check_for_type-definition_count_limit.patch
Labels: security 🔒, semver/patch, backport-check-skip, 28-x-y

#41355 feat: Options parameter for `Session.clearData` API
  docs/api/session.md
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec/api-session-spec.ts
  spec/fixtures/api/localstorage-and-indexeddb.html
Labels: semver/minor, api-review/approved ✅, no-backport

#41744 feat: add support for configuring system network context proxies
  docs/api/app.md
  docs/api/session.md
  docs/api/structures/proxy-config.md
  filenames.auto.gni
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
  shell/browser/browser_process_impl.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_browser_context.cc
  shell/browser/net/resolve_proxy_helper.cc
  shell/browser/net/resolve_proxy_helper.h
  spec/api-app-spec.ts
  spec/lib/spec-helpers.ts
Labels: backport, semver/minor, backport/approved ✅, 28-x-y

#41661 feat: add `navigationHistory.getEntryAtIndex(int index)` method
  docs/api/navigation-history.md
  docs/api/web-contents.md
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/api-web-contents-spec.ts
  spec/chromium-spec.ts
  typings/internal-electron.d.ts
Labels: backport, semver/minor, backport/approved ✅, 29-x-y

#41753 build: add Markdown lint check for unescaped angle brackets
  .markdownlint.json
  docs/api/client-request.md
  docs/tutorial/tutorial-2-first-app.md
  package.json
  yarn.lock
Labels: semver/none, target/29-x-y, target/30-x-y

#41774 docs: update node.js version for Electron 29
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, backport, semver/none, 29-x-y

#41775 chore: cherry-pick 1 change from Release-2-M123
  patches/v8/.patches
  patches/v8/merged_wasm_gc_scan_the_code_field_of_the_wasminternalfunction.patch
Labels: security 🔒, semver/patch, backport-check-skip, 29-x-y

#41779 build: add Markdown lint check for unescaped angle brackets
  .markdownlint.json
  docs/api/base-window.md
  docs/api/client-request.md
  docs/tutorial/tutorial-2-first-app.md
  package.json
  yarn.lock
Labels: backport, semver/none, 30-x-y

#41776 chore: cherry-pick 1 change from Release-2-M123
  patches/v8/.patches
  patches/v8/merged_runtime_recreate_enum_cache_on_map_update_if_any_previous.patch
Labels: security 🔒, semver/patch, backport-check-skip, 28-x-y

#41777 chore: cherry-pick 1 change from Release-2-M123
  patches/v8/.patches
  patches/v8/merged_runtime_recreate_enum_cache_on_map_update_if_any_previous.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#41789 build: add missing header for `content::SyntheticGestureTarget`
  shell/browser/osr/osr_render_widget_host_view.cc
Labels: semver/none, target/29-x-y, target/30-x-y

#41256 fix: move BrowserWindow's WebContentsView to be a child of rootview
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/frame_subscriber.cc
  shell/browser/native_window_views.cc
  shell/browser/ui/views/root_view.cc
  shell/browser/ui/views/root_view.h
  spec/api-browser-window-spec.ts
Labels: semver/minor, api-review/approved ✅, target/30-x-y

#41800 build: add Markdown lint check for unescaped angle brackets
  .markdownlint.json
  docs/api/client-request.md
  docs/tutorial/tutorial-2-first-app.md
  package.json
  yarn.lock
Labels: semver/none, 29-x-y

#41793 fix: WCO maximize button visibility when non-maximizable
  shell/browser/ui/views/win_caption_button_container.cc
Labels: semver/patch, target/28-x-y, target/29-x-y, target/30-x-y

#41728 refactor: move PDF viewer to OOPIF
  shell/browser/extensions/api/management/electron_management_api_delegate.cc
  shell/browser/extensions/api/management/electron_management_api_delegate.h
  shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.cc
  shell/browser/extensions/api/pdf_viewer_private/pdf_viewer_private_api.h
  shell/browser/extensions/api/streams_private/streams_private_api.cc
  shell/common/extensions/api/pdf_viewer_private.idl
Labels: semver/patch, no-backport

#41689 feat: support `NODE_EXTRA_CA_CERTS`
  docs/api/environment-variables.md
  docs/tutorial/fuses.md
  patches/node/feat_optionally_prevent_calling_v8_enablewebassemblytraphandler.patch
  patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
  script/node-disabled-tests.json
  shell/app/node_main.cc
  shell/common/node_bindings.cc
Labels: semver/minor, api-review/requested 🗳, target/28-x-y, target/29-x-y, target/30-x-y

#41788 fix: typos in comment section of `in_app_purchase.mm`
  shell/browser/mac/in_app_purchase.mm
Labels: semver/none, no-backport

#41419 feat: implement File System API support
  chromium_src/BUILD.gn
  docs/api/session.md
  docs/api/structures/filesystem-permission-request.md
  docs/api/structures/media-access-permission-request.md
  docs/api/structures/open-external-permission-request.md
  docs/api/structures/permission-request.md
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/refactor_expose_file_system_access_blocklist.patch
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/file_system_access/file_system_access_permission_context.cc
  shell/browser/file_system_access/file_system_access_permission_context.h
  shell/browser/file_system_access/file_system_access_permission_context_factory.cc
  shell/browser/file_system_access/file_system_access_permission_context_factory.h
  shell/browser/web_contents_permission_helper.h
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_api_clipboard.h
  shell/common/gin_converters/content_converter.cc
  spec/chromium-spec.ts
  spec/fixtures/file-system/test-writable.html
  spec/fixtures/file-system/test.txt
Labels: semver/minor, api-review/approved ✅, target/30-x-y

#41825 docs: update release timeline
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/30-x-y

#41811 fix: silent printing default dpi on Windows
  BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/printing/printing_utils.cc
  shell/browser/printing/printing_utils.h
Labels: semver/patch, target/28-x-y, target/29-x-y, target/30-x-y

#41750 fix: do not activate app when showing a panel on Mac
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
  spec/disabled-tests.json
Labels: semver/patch, target/30-x-y

#41830 fix: package <__assertion_handler> as part of libcxx headers
  BUILD.gn
Labels: semver/patch, target/29-x-y, target/30-x-y

#41855 chore: cherry-pick 4 changes from 3-M123 and M122
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-a65e511a14b4.patch
  patches/DirectXShaderCompiler/fix_hlmatrixlowerpass_leaving_call_to_dangling_functionval.patch
  patches/angle/.patches
  patches/angle/cherry-pick-f6672dbbe223.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-1b1f34234346.patch
  patches/config.json
  patches/webrtc/.patches
  patches/webrtc/m122_merge_limit_max_frame_size_in_dav1d_decoder.patch
Labels: security 🔒, semver/patch, backport-check-skip, 28-x-y

#41854 chore: cherry-pick 3 changes from 3-M123
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-a65e511a14b4.patch
  patches/angle/.patches
  patches/angle/cherry-pick-f6672dbbe223.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-1b1f34234346.patch
  patches/config.json
  patches/dxc/.patches
Labels: security 🔒, semver/patch, backport-check-skip, 29-x-y

#41843 docs: use "id" instead of "label" for positions
  docs/api/menu-item.md
  docs/api/menu.md
Labels: documentation :notebook:, semver/patch, target/30-x-y

#41849 docs: clarify before `ready` usage
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/30-x-y

#41858 build: redundant regex character class in generate-config-gypi.py
  script/generate-config-gypi.py
Labels: semver/none, no-backport

#41856 chore: cherry-pick 8 changes from 3-M123 and M1nn
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-a65e511a14b4.patch
  patches/DirectXShaderCompiler/fix_hlmatrixlowerpass_leaving_call_to_dangling_functionval.patch
  patches/angle/.patches
  patches/angle/cherry-pick-f6672dbbe223.patch
  patches/angle/m119_move_invalid_uniform_protection_to_the_frontend.patch
  patches/angle/m120_fix_off-by-one_bounds_check_on_uniform_location.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-1b1f34234346.patch
  patches/config.json
  patches/v8/.patches
  patches/v8/merged_wasm_check_the_cached_memory_for_growability.patch
  patches/webrtc/.patches
  patches/webrtc/m122_merge_limit_max_frame_size_in_dav1d_decoder.patch
  patches/webrtc/revert_2_m120_jseptransportcontroller_remove_raw_pointers_to.patch
Labels: security 🔒, semver/patch, backport-check-skip, 27-x-y

#41832 fix: stop using std::vector<const uint8_t> in ProcessingSingleton
  patches/chromium/feat_add_data_parameter_to_processsingleton.patch
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_app.h
Labels: semver/patch, no-backport

#41863 test: add tests for Storage Access API
  docs/api/session.md
  spec/chromium-spec.ts
Labels: backport, semver/patch, 29-x-y

#41864 test: add tests for Storage Access API
  docs/api/session.md
  spec/chromium-spec.ts
Labels: backport, semver/patch, 28-x-y

#41869 perf: remove unnecessary `.c_str()` calls
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/net/asar/asar_url_loader.cc
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/common/api/electron_api_command_line.cc
  shell/common/api/electron_api_shell.cc
Labels: performance :checkered_flag:, semver/patch, no-backport

#41873 refactor: fold silent print into settings
  patches/chromium/printing.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/none, no-backport

#41567 docs: update build docs,support Powershell on Windows
  docs/development/build-instructions-gn.md
Labels: documentation :notebook:, semver/patch, target/30-x-y, target/31-x-y

#41876 chore: remove unused hash function
  shell/common/api/electron_api_v8_util.cc
Labels: semver/patch, new-pr 🌱, target/28-x-y, target/29-x-y, target/30-x-y, target/31-x-y

#41889 fix: console.log() in AudioWorkletGlobalScope
  patches/devtools_frontend/.patches
  patches/devtools_frontend/fix_support_for_worklet_targets.patch
Labels: backport, semver/patch, backport-check-skip, 29-x-y

#37902 refactor: JSify BrowserWindow unresponsive handling
  lib/browser/api/browser-window.ts
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
Labels: semver/patch, no-backport

#41875 fix: `nativeImage.createThumbnailFromPath` and `shell.openExternal` in renderer
  shell/common/api/electron_api_native_image_mac.mm
  shell/common/platform_util_mac.mm
  spec/api-native-image-spec.ts
  spec/api-shell-spec.ts
Labels: semver/patch, target/28-x-y, target/29-x-y, target/30-x-y, target/31-x-y

#41211 fix: don't check for Desktop Environment in unity_service.cc
  shell/browser/linux/unity_service.cc
Labels: semver/patch, no-backport

#41900 build: update typescript-definitions to 8.15.6
  yarn.lock
Labels: semver/none, no-backport

#41880 build: enable Perfetto in Chromium
  build/args/all.gn
  patches/node/.patches
  patches/node/build_enable_perfetto.patch
  shell/browser/javascript_environment.cc
Labels: semver/none, target/31-x-y

#41881 refactor: use `std::erase()`
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/usb/usb_chooser_controller.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/window_list.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/cleaned_up_at_exit.cc
Labels: semver/patch, no-backport

#41916 build: use latest devcontainer buildimage with codespaces
  .devcontainer/docker-compose.yml
Labels: semver/none, target/30-x-y, target/31-x-y

#41904 fix: offscreen rendering does not paint after gpu process crashed
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y

#41894 fix: data corruption in `protocol.handle`
  lib/browser/api/protocol.ts
  spec/api-protocol-spec.ts
  spec/index.js
Labels: semver/patch, target/28-x-y, target/29-x-y, target/30-x-y, target/31-x-y

#41428 build: fixup codespaces on-create
  .devcontainer/devcontainer.json
  .devcontainer/on-create-command.sh
Labels: semver/none, target/30-x-y, target/31-x-y

#41926 docs: correct the return value for canceled showSaveDialog
  docs/api/dialog.md
Labels: documentation :notebook:, semver/patch, target/28-x-y, target/29-x-y, target/30-x-y, target/31-x-y

#41911 refactor: address changes and fix errors in `chrome://accessibility`
  patches/chromium/.patches
  patches/chromium/adjust_accessibility_ui_for_electron.patch
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/ui/webui/accessibility_ui.cc
  shell/browser/ui/webui/accessibility_ui.h
Labels: semver/patch, target/30-x-y, target/31-x-y

#41896 docs: Windows typo in Tutorial document
  docs/tutorial/tutorial-6-publishing-updating.md
Labels: semver/none, target/28-x-y, target/29-x-y, target/30-x-y, target/31-x-y

#41937 refactor: replace base::EndsWith() with std::ends_with()
  shell/app/electron_main_delegate_mac.mm
  shell/browser/api/electron_api_session.cc
  shell/browser/browser_linux.cc
  shell/common/mac/main_application_bundle.mm
Labels: semver/patch, no-backport

#41812 build: add GitHub Actions testing pipeline for macOS
  .github/workflows/config/evm.mas.json
  .github/workflows/config/gclient.diff
  .github/workflows/macos-build.yml
  script/actions/move-artifacts.sh
  script/actions/restore-artifacts.sh
  script/azure_cli_deb_install.sh
Labels: semver/none, no-backport

#41969 build: use env var for build-tools pinning
  .github/workflows/macos-build.yml
Labels: semver/none, no-backport

#41960 fix: `setTitleBarOverlay` should be implemented on `BaseWindow`
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y

#41600 chore: fix notes stack updates
  script/release/notes/notes.js
  spec/release-notes-spec.ts
Labels: semver/none, no-backport

#41978 fix: recentDocuments on macOS not working
  shell/browser/ui/cocoa/electron_menu_controller.h
  shell/browser/ui/cocoa/electron_menu_controller.mm
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y

#41966 fix: `requestFullscreen` from `WebContentsView`
  shell/browser/api/electron_api_web_contents_view.cc
  spec/api-web-contents-view-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y
