Repository electron/electron, pull requests merged in 2024-08, with the labels that each got.

#43112 fix: handle failing to enter fullscreen on macOS
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: platform/macOS, semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43138 feat: add transparency checking to `nativeTheme`
  docs/api/native-theme.md
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec/api-native-theme-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 30-x-y

#43137 feat: add transparency checking to `nativeTheme`
  docs/api/native-theme.md
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec/api-native-theme-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 31-x-y

#43101 fix: take bluetooth serial ports into account in `serial.getPorts()`
  shell/browser/serial/serial_chooser_context.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43148 chore: remove unused internal env.unSetVar()
  shell/common/api/electron_api_environment.cc
  typings/internal-ambient.d.ts
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43129 docs: fixed broken electron-fiddle links in the "Tutorial - Publishing and Updating" doc
  docs/tutorial/tutorial-6-publishing-updating.md
Labels: documentation :notebook:, semver/patch, target/31-x-y, target/32-x-y

#43160 chore: cherry-pick 3 changes from 0-M127
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-9463ce9cd8d9.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-44b7fbf35b10.patch
  patches/dawn/.patches
  patches/dawn/reland_deps_update_dxc_to_patched_branch.patch
Labels: security 🔒, semver/patch, backport-check-skip, 29-x-y

#43158 chore: cherry-pick 3 changes from 0-M127
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-9463ce9cd8d9.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-44b7fbf35b10.patch
  patches/config.json
  patches/dawn/.patches
  patches/dawn/reland_deps_update_dxc_to_patched_branch.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#43141 chore: cherry-pick 11 changes from 3-M126
  patches/chromium/.patches
  patches/chromium/cherry-pick-1b9040817119.patch
  patches/chromium/cherry-pick-38e4483e47f9.patch
  patches/chromium/cherry-pick-43b8b682d05c.patch
  patches/chromium/cherry-pick-99cafbf4b4b9.patch
  patches/chromium/cherry-pick-c5dd8839bfaf.patch
  patches/chromium/cherry-pick-d54105311590.patch
  patches/v8/.patches
  patches/v8/cherry-pick-70d2fe6b7c47.patch
  patches/v8/cherry-pick-901377bb2f3b.patch
  patches/v8/cherry-pick-bb28367eed73.patch
  patches/v8/cherry-pick-bc545b15a0ee.patch
  patches/v8/cherry-pick-cdbc1d9684a3.patch
Labels: security 🔒, semver/patch, backport-check-skip, 30-x-y

#43159 chore: cherry-pick 3 changes from 0-M127
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-9463ce9cd8d9.patch
  patches/chromium/.patches
  patches/chromium/cherry-pick-44b7fbf35b10.patch
  patches/dawn/.patches
  patches/dawn/deps_update_dxc_to_patched_branch.patch
Labels: security 🔒, semver/patch, backport-check-skip, 30-x-y

#43140 chore: cherry-pick 1 change from 3-M126
  patches/chromium/.patches
  patches/chromium/cherry-pick-99cafbf4b4b9.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#43184 chore: bump chromium to 129.0.6632.0
  DEPS
  patches/chromium/adjust_accessibility_ui_for_electron.patch
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/build_make_libcxx_abi_unstable_false_for_electron.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/desktop_media_list.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/feat_add_data_parameter_to_processsingleton.patch
  patches/chromium/feat_enable_offscreen_rendering_with_viz_compositor.patch
  patches/chromium/fix_add_support_for_skipping_first_2_no-op_refreshes_in_thumb_cap.patch
  patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
  patches/chromium/fix_restore_original_resize_performance_on_macos.patch
  patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  patches/chromium/notification_provenance.patch
  patches/chromium/pepper_plugin_support.patch
  patches/chromium/process_singleton.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_expose_hostimportmoduledynamically_and.patch
  patches/chromium/resource_file_conflict.patch
  patches/chromium/support_mixed_sandbox_with_zygote.patch
  patches/devtools_frontend/chore_expose_ui_to_allow_electron_to_set_dock_side.patch
  patches/v8/fix_disable_scope_reuse_associated_dchecks.patch
Labels: semver/patch, new-pr 🌱, no-backport

#43142 chore: cherry-pick 10 changes from 3-M126
  patches/chromium/.patches
  patches/chromium/cherry-pick-1b9040817119.patch
  patches/chromium/cherry-pick-38e4483e47f9.patch
  patches/chromium/cherry-pick-43b8b682d05c.patch
  patches/chromium/cherry-pick-99cafbf4b4b9.patch
  patches/chromium/cherry-pick-c5dd8839bfaf.patch
  patches/chromium/cherry-pick-d54105311590.patch
  patches/v8/.patches
  patches/v8/cherry-pick-70d2fe6b7c47.patch
  patches/v8/cherry-pick-901377bb2f3b.patch
  patches/v8/cherry-pick-bc545b15a0ee.patch
  patches/v8/cherry-pick-cdbc1d9684a3.patch
Labels: security 🔒, semver/patch, backport-check-skip, 29-x-y

#43172 refactor: prefer std::ranges over base::ranges
  shell/browser/electron_browser_context.cc
  shell/browser/file_system_access/file_system_access_permission_context.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/ui/file_dialog_linux.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/usb/usb_chooser_controller.cc
  shell/renderer/electron_renderer_client.cc
Labels: semver/patch, no-backport

#43179 fix: potential draggable regions crash in DevTools
  patches/chromium/.patches
  patches/chromium/fix_potential_draggable_region_crash_when_no_mainframeimpl.patch
Labels: semver/patch, target/31-x-y, target/32-x-y

#43182 refactor: migrate `electron_login_helper` to non-deprecated API
  shell/app/electron_login_helper.mm
Labels: semver/patch, no-backport

#43157 refactor: simplify window `moveAbove/moveTop` impl on macOS
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43185 fix: gin_helper::MicrotasksScope instantiation
  shell/browser/api/electron_api_auto_updater.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/gin_helper/microtasks_scope.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
  shell/common/v8_value_serializer.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43192 perf: don't build unused vectors in HidChooserContext
  shell/browser/hid/hid_chooser_context.cc
Labels: performance :checkered_flag:, semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43198 ci: auto label bug issues with platform
  .github/workflows/issue-opened.yml
Labels: semver/none, no-backport

#43218 build: fixup patches in main
  patches/chromium/fix_potential_draggable_region_crash_when_no_mainframeimpl.patch
Labels: fast-track 🚅, semver/none, no-backport

#43215 fix: 31-x-y gn sync fail when patching dawn, dxc
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-9463ce9cd8d9.patch
  patches/config.json
  patches/dawn/.patches
  patches/dawn/reland_deps_update_dxc_to_patched_branch.patch
Labels: semver/patch, fast-track 🚅, backport-check-skip, no-backport

#43187 build: use smaller instances for gn-check
  .github/workflows/build.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
Labels: semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43217 docs: add missing deprecations to `breaking-changes.md`
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, target/32-x-y

#43167 chore: cherry-pick 1 changes from 1-M127
  patches/chromium/.patches
  patches/chromium/cherry-pick-d9f7652c867c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 30-x-y

#43216 perf: avoid redundant calls to GetView()
  shell/browser/api/frame_subscriber.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/ui/autofill_popup.cc
Labels: performance :checkered_flag:, semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43139 build: fix patchup logic only running on one platform
  .github/actions/checkout/action.yml
  .github/workflows/build.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y

#43149 docs: Document ideal iconPath size
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43222 ci: set labels on Dependabot PRs for GitHub Actions deps
  .github/dependabot.yml
Labels: semver/none, no-backport

#43206 build: fix build when `enable_pdf_viewer` and `enable_electron_extensions` disabled
  shell/browser/api/electron_api_session.cc
  shell/browser/electron_browser_context.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43243 fix: system-context-menu with frameless BrowserWindows
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/32-x-y

#43080 fix: check screen capture permissions in `desktopCapturer`
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/api/electron_api_desktop_capturer.h
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43238 build: add nacl back to buildtools gitignore
  patches/chromium/build_run_reclient_cfg_generator_after_chrome.patch
Labels: semver/none, target/32-x-y

#43260 fix: accidental handle copying in a range loop
  shell/browser/api/message_port.cc
Labels: performance :checkered_flag:, semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43262 refactor: use url::DomainIs() to check cookie domains
  docs/api/cookies.md
  shell/browser/api/electron_api_cookies.cc
  spec/api-session-spec.ts
Labels: semver/patch, no-backport

#43283 chore: remove unused method ElectronDesktopWindowTreeHostLinux::UpdateClientDecorationHints()
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
Labels: semver/patch, target/32-x-y

#43205 refactor: update chrome.scripting extensions api impls
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/scripting/scripting_api.h
  shell/common/extensions/api/scripting.idl
Labels: semver/patch, target/31-x-y, target/32-x-y

#43286 chore: remove unused Notification fields icon_path_, has_icon_
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43285 refactor: put empty virtual function definitions in header
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/frame_subscriber.cc
  shell/browser/api/frame_subscriber.h
  shell/browser/electron_pdf_document_helper_client.cc
  shell/browser/electron_pdf_document_helper_client.h
  shell/browser/extensions/electron_extension_host_delegate.cc
  shell/browser/extensions/electron_extension_host_delegate.h
  shell/browser/media/media_capture_devices_dispatcher.cc
  shell/browser/media/media_capture_devices_dispatcher.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/net/proxying_websocket.cc
  shell/browser/net/proxying_websocket.h
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/platform_notification_service.cc
  shell/browser/notifications/platform_notification_service.h
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/osr/osr_video_consumer.h
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/osr/osr_web_contents_view.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/tray_icon.h
  shell/browser/ui/views/electron_views_delegate.cc
  shell/browser/ui/views/electron_views_delegate.h
  shell/browser/ui/views/frameless_view.cc
  shell/browser/ui/views/frameless_view.h
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/usb/usb_chooser_context.h
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/api/electron_api_spell_check_client.h
Labels: semver/patch, no-backport

#43150 feat: accept-encoding zstd
  shell/browser/net/system_network_context_manager.cc
Labels: enhancement :sparkles:, semver/minor, api-review/approved ✅, target/31-x-y, target/32-x-y

#43303 docs: fix formatting in fuses tutorial
  docs/tutorial/fuses.md
Labels: semver/patch, target/32-x-y

#42631 feat: support app#login event for utility process net requests
  docs/api/app.md
  docs/api/utility-process.md
  docs/breaking-changes.md
  filenames.gni
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  shell/browser/electron_browser_client.cc
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  shell/browser/net/url_loader_network_observer.cc
  shell/browser/net/url_loader_network_observer.h
  shell/common/api/electron_api_url_loader.cc
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/public/mojom/node_service.mojom
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/net.js
Labels: semver/minor, api-review/approved ✅, target/30-x-y, target/31-x-y, target/32-x-y

#43311 build: remove upstreamed DraggableRegions patch
  patches/chromium/.patches
  patches/chromium/fix_potential_draggable_region_crash_when_no_mainframeimpl.patch
Labels: semver/patch, no-backport

#43309 fix: blank page when printing pdf
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/printing/printing_utils.cc
  shell/browser/printing/printing_utils.h
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43161 refactor: migrate deprecated `platform_util_mac` calls
  shell/common/platform_util_mac.mm
Labels: semver/patch, no-backport

#43332 test: fixup Node.js snapshot tests to run correctly
  patches/node/ci_ensure_node_tests_set_electron_run_as_node.patch
Labels: semver/none, no-backport

#43317 feat: support app#login event for utility process net requests
  docs/api/app.md
  docs/api/utility-process.md
  docs/breaking-changes.md
  filenames.gni
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  shell/browser/electron_browser_client.cc
  shell/browser/login_handler.cc
  shell/browser/login_handler.h
  shell/browser/net/url_loader_network_observer.cc
  shell/browser/net/url_loader_network_observer.h
  shell/common/api/electron_api_url_loader.cc
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
  shell/services/node/public/mojom/node_service.mojom
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/net.js
Labels: backport, semver/minor, backport/requested 🗳, 32-x-y

#43346 build: fix valid versions in issue version parsing
  .github/workflows/issue-opened.yml
Labels: semver/none, target/32-x-y

#43325 build: update NMV to 130 for Electron 33
  build/args/all.gn
Labels: semver/none, no-backport

#42982 docs: api history
  docs/api-history.schema.json
  docs/api/base-window.md
  docs/api/browser-view.md
  docs/api/browser-window.md
  docs/api/context-bridge.md
  docs/api/ipc-renderer.md
  docs/api/native-image.md
  docs/api/protocol.md
  docs/api/web-contents.md
  docs/development/api-history-migration-guide.md
  docs/styleguide.md
  package.json
Labels: semver/patch, target/32-x-y

#43337 fix: printing occasionally showing failed when cancelled
  patches/chromium/printing.patch
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42014 feat: extend navigationHistory API
  docs/api/navigation-history.md
  docs/api/structures/navigation-entry.md
  filenames.auto.gni
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/api-web-contents-spec.ts
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#43358 build: use smaller instances for gn-check
  .github/workflows/build.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
Labels: backport, semver/none, 32-x-y

#43362 docs: add docs API history
  docs/api-history.schema.json
  docs/api/base-window.md
  docs/api/browser-view.md
  docs/api/browser-window.md
  docs/api/context-bridge.md
  docs/api/ipc-renderer.md
  docs/api/native-image.md
  docs/api/protocol.md
  docs/api/web-contents.md
  docs/development/api-history-migration-guide.md
  docs/styleguide.md
  package.json
Labels: backport, semver/patch, 32-x-y

#43348 chore: remove unused method Erase()
  shell/browser/electron_browser_main_parts.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43347 refactor: remove unused SetWMSpecState
  shell/browser/ui/x/x_window_utils.cc
  shell/browser/ui/x/x_window_utils.h
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43357 fix: `gin_helper::MicrotasksScope` instantiation
  shell/browser/api/electron_api_auto_updater.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/gin_helper/microtasks_scope.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
  shell/common/v8_value_serializer.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: backport, semver/patch, 29-x-y

#43359 build: use smaller instances for gn-check
  .github/workflows/build.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
Labels: backport, semver/none, 31-x-y

#43363 chore: remove unused method Erase()
  shell/browser/electron_browser_main_parts.cc
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, 32-x-y

#43364 refactor: remove unused SetWMSpecState
  shell/browser/ui/x/x_window_utils.cc
  shell/browser/ui/x/x_window_utils.h
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, 32-x-y

#43360 build: use smaller instances for gn-check
  .github/workflows/build.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
Labels: backport, semver/none, 30-x-y

#43361 refactor: NodeBindings::Create() returns a unique_ptr
  shell/common/node_bindings.h
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_win.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43376 chore: cherry-pick 9797576 from v8
  patches/v8/.patches
  patches/v8/spill_all_loop_inputs_before_entering_loop.patch
Labels: security 🔒, semver/patch, fast-track 🚅, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43378 chore: remove unused ConvertableToTraceFormatWrapper (33-x-y)
  shell/browser/javascript_environment.cc
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, 33-x-y

#43388 docs: update window customization tutorial
  docs/tutorial/window-customization.md
Labels: new-pr 🌱, semver/none, target/32-x-y, target/33-x-y

#43385 chore: cherry-pick 9797576 from v8
  patches/v8/.patches
  patches/v8/spill_all_loop_inputs_before_entering_loop.patch
Labels: security 🔒, backport, semver/patch, 33-x-y

#43384 chore: cherry-pick 9797576 from v8
  patches/v8/.patches
  patches/v8/spill_all_loop_inputs_before_entering_loop.patch
Labels: security 🔒, backport, semver/patch, 32-x-y

#43389 docs: update timelines for E33
  docs/tutorial/electron-timelines.md
Labels: semver/patch, new-pr 🌱, target/33-x-y

#43387 chore: cherry-pick 9797576 from v8
  patches/v8/.patches
  patches/v8/spill_all_loop_inputs_before_entering_loop.patch
Labels: backport, semver/patch, 30-x-y

#43381 refactor: NodeBindings::Create() returns a unique_ptr
  shell/common/node_bindings.h
  shell/common/node_bindings_linux.cc
  shell/common/node_bindings_mac.cc
  shell/common/node_bindings_win.cc
Labels: backport, semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, 33-x-y

#43382 chore: remove unused method Erase()
  shell/browser/electron_browser_main_parts.cc
Labels: backport, semver/patch, target/30-x-y, 31-x-y

#43383 refactor: remove unused SetWMSpecState
  shell/browser/ui/x/x_window_utils.cc
  shell/browser/ui/x/x_window_utils.h
Labels: backport, semver/patch, target/30-x-y, 31-x-y

#43223 chore: set wg-infra as CODEOWNER for GHA build configs
  .github/CODEOWNERS
Labels: new-pr 🌱, semver/none, no-backport

#43372 refactor: move impl functions into private namespace
  shell/app/node_main.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_desktop_capturer.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/common/asar/asar_util.cc
  shell/common/extensions/electron_extensions_api_provider.cc
  shell/common/gin_helper/cleaned_up_at_exit.cc
  shell/common/logging.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43377 docs: clarify icon value in Notification
  docs/api/notification.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y

#43353 fix: touch bar functionality on BaseWindow
  lib/browser/api/base-window.ts
  lib/browser/api/browser-window.ts
  lib/browser/api/touch-bar.ts
  shell/browser/api/electron_api_base_window.cc
  spec/api-touch-bar-spec.ts
  typings/internal-electron.d.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43366 fix: documentation spelling errors
  docs/api/session.md
  docs/api/touch-bar-scrubber.md
  docs/api/web-utils.md
Labels: documentation :notebook:, semver/none, target/31-x-y, target/32-x-y, target/33-x-y

#43261 build: roll sysroots
  script/sysroots.json
Labels: semver/patch, no-backport

#43404 fix: menu should allow focused `BaseWindow` where possible
  docs/api/menu-item.md
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/menu-item.ts
  lib/browser/api/menu.ts
  spec/ts-smoke/electron/main.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#42953 feat: GPU shared texture offscreen rendering
  docs/api/structures/offscreen-shared-texture.md
  docs/api/structures/web-preferences.md
  docs/api/web-contents.md
  docs/tutorial/offscreen-rendering.md
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/osr_shared_texture_remove_keyed_mutex_on_win_dxgi.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/osr/osr_host_display_client.cc
  shell/browser/osr/osr_host_display_client.h
  shell/browser/osr/osr_host_display_client_mac.mm
  shell/browser/osr/osr_paint_event.cc
  shell/browser/osr/osr_paint_event.h
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/osr/osr_video_consumer.h
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/osr/osr_web_contents_view.h
  shell/common/gin_converters/osr_converter.cc
  shell/common/gin_converters/osr_converter.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec/api-browser-window-spec.ts
  spec/fixtures/assets/osr.png
  spec/fixtures/native-addon/osr-gpu/binding.gyp
  spec/fixtures/native-addon/osr-gpu/binding_win.cc
  spec/fixtures/native-addon/osr-gpu/lib/osr-gpu.js
  spec/fixtures/native-addon/osr-gpu/napi_utils.h
  spec/fixtures/native-addon/osr-gpu/package.json
  spec/package.json
  spec/yarn.lock
Labels: semver/minor, api-review/approved ✅, no-backport

#43373 chore: fix typos in 'shell/' folder.
  shell/browser/api/electron_api_session.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/net/asar/asar_url_loader_factory.h
  shell/browser/net/proxying_url_loader_factory.h
  shell/browser/usb/electron_usb_delegate.h
  shell/browser/usb/usb_chooser_context.h
  shell/common/extensions/api/browser_action.json
  shell/common/gin_converters/callback_converter.h
  shell/common/gin_helper/callback.cc
  shell/common/gin_helper/callback.h
Labels: semver/patch, no-backport

#43406 chore: mention signed commit requirement
  .github/config.yml
Labels: semver/none, no-backport

#43431 fix: ensure bounds stability in `OnWidgetBoundsChanged`
  shell/browser/native_window_views.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43430 docs: `titleBarOverlay` is defined as a `BaseWindow` ctor option
  docs/api/structures/base-window-options.md
  docs/api/structures/browser-window-options.md
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43441 build: remove fix_disable_scope_reuse_associated_dchecks.patch
  patches/v8/.patches
  patches/v8/fix_disable_scope_reuse_associated_dchecks.patch
Labels: semver/none, no-backport

#43436 test: add -pdf-ready-to-print event to WebContents for testing
  BUILD.gn
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_pdf_document_helper_client.cc
  shell/browser/electron_pdf_document_helper_client.h
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43442 chore: remove unused method asar::ClearArchives()
  shell/common/asar/asar_util.cc
  shell/common/asar/asar_util.h
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#43443 perf: prefer GURL string_view getters
  shell/browser/browser_linux.cc
  shell/browser/browser_win.cc
  shell/browser/electron_web_ui_controller_factory.cc
  shell/browser/net/electron_url_loader_factory.h
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/protocol_registry.cc
  shell/browser/protocol_registry.h
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/web_contents_zoom_controller.cc
  shell/common/api/electron_api_url_loader.cc
Labels: semver/patch, target/32-x-y, target/33-x-y

#43448 chore: remove unused WinFrameView::kInactiveTitlebarFeatureAlpha
  shell/browser/ui/views/win_frame_view.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43478 chore: cleanup include groupings
  shell/browser/api/electron_api_debugger.cc
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/net/asar/asar_url_loader.cc
  shell/browser/net/url_pipe_loader.h
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/gin_helper/arguments.cc
  shell/common/process_util.cc
Labels: semver/none, no-backport

#43464 refactor: prefer std::ranges over begin() and end()
  shell/app/electron_main_win.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/notifications/notification_presenter.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/window_list.cc
  shell/common/crash_keys.cc
  shell/common/node_bindings.cc
Labels: semver/patch, target/33-x-y

#43461 refactor: simplify KeyWeakMap impl
  shell/common/key_weak_map.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43490 fix: devtools dock state with WCO on linux
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43497 chore: speed up cache only reclient for fork PRs
  appveyor-woa.yml
  appveyor.yml
Labels: new-pr 🌱, semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y
