Repository electron/electron, pull requests merged in 2024-07, with the labels that each got.

#42693 chore: cherry-pick 5 changes from 2-M126
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/cherry-pick-771e74ab497d.patch
  patches/DirectXShaderCompiler/cherry-pick-8f07d39227f6.patch
  patches/DirectXShaderCompiler/cherry-pick-b3c64851765c.patch
  patches/angle/.patches
  patches/angle/cherry-pick-5d4df51d1d7d.patch
  patches/v8/.patches
  patches/v8/merged_wasm_add_missing_type_canonicalization_for_exceptions_js.patch
Labels: security 🔒, semver/patch, backport-check-skip, 30-x-y

#42718 build: remove MacOS x64 from CircleCI
  .circleci/config/base.yml
Labels: semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#42653 fix: setTopBrowserView focus issue with reordering
  lib/browser/api/browser-window.ts
  spec/api-browser-view-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42671 build: migrate to GitHub Actions
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/fix-sync-macos/action.yml
  .github/actions/free-space-macos/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/restore-cache-aks/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  script/actions/move-artifacts.sh
  script/actions/restore-artifacts.sh
  script/actions/run-tests.sh
  script/release/ci-release-build.js
  script/split-tests.js
  spec/api-app-spec.ts
  spec/api-protocol-spec.ts
Labels: backport-check-skip, semver/none, in-flight/29-x-y, in-flight/30-x-y, in-flight/31-x-y, 32-x-y

#42720 build: migrate to GitHub Actions
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/fix-sync-macos/action.yml
  .github/actions/free-space-macos/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/restore-cache-aks/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  script/actions/move-artifacts.sh
  script/actions/restore-artifacts.sh
  script/actions/run-tests.sh
  script/release/ci-release-build.js
  script/split-tests.js
  spec/api-app-spec.ts
  spec/api-protocol-spec.ts
Labels: backport, backport-check-skip, semver/none, 31-x-y

#42721 build: migrate to GitHub Actions
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/fix-sync-macos/action.yml
  .github/actions/free-space-macos/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/restore-cache-aks/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  script/actions/move-artifacts.sh
  script/actions/restore-artifacts.sh
  script/actions/run-tests.sh
  script/release/ci-release-build.js
  script/split-tests.js
  spec/api-app-spec.ts
  spec/api-protocol-spec.ts
Labels: backport, backport-check-skip, semver/none, 30-x-y

#42738 build: remove MacOS x64 from CircleCI
  .circleci/config/base.yml
Labels: backport, semver/none, 30-x-y

#42740 build: remove MacOS x64 from CircleCI
  .circleci/config/base.yml
Labels: backport, semver/none, 29-x-y

#42691 docs - Update net.md
  docs/api/net.md
Labels: new-pr 🌱

#42692 docs: grammar fix in isBeingCaptured docs
  docs/api/web-contents.md
Labels: documentation :notebook:, semver/patch

#42741 build: strip linux release binaries
  .github/actions/build-electron/action.yml
  .github/workflows/linux-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
Labels: semver/patch, backport-check-skip, target/29-x-y, target/30-x-y, target/31-x-y, 32-x-y

#42647 fix: use `BlockedRequest` struct to handle `webRequest` data
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/electron_api_web_request.h
  spec/api-web-request-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y

#42709 docs(autoUpdater): signing is only a pre-req on macOS
  docs/tutorial/tutorial-6-publishing-updating.md
  docs/tutorial/updates.md
Labels: semver/patch, target/31-x-y, target/32-x-y

#42690 docs(autoUpdater): document static storage strategy
  docs/tutorial/updates.md
Labels: documentation :notebook:, semver/patch, target/31-x-y, target/32-x-y

#42728 refactor: make session::browser_context_ a const raw_ref
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: semver/patch, no-backport

#42763 build: remove all publish & build on macOS
  .circleci/config.yml
  .circleci/config/base.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y

#42762 chore: clean up outdated goma references
  .circleci/config/base.yml
  .devcontainer/README.md
  .devcontainer/on-create-command.sh
  .github/actions/build-electron/action.yml
  appveyor-woa.yml
  appveyor.yml
  docs/development/goma.md
Labels: semver/none, no-backport

#42758 refactor: run Windows `SelectFileDialog` out of process
  chromium_src/BUILD.gn
  shell/browser/electron_browser_main_parts.cc
  shell/utility/electron_content_utility_client.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42775 fix: video and audio capture should be separate
  shell/browser/web_contents_permission_helper.cc
  spec/chromium-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42633 fix: potentially closed webContents in BrowserView
  lib/browser/api/browser-view.ts
  lib/browser/api/browser-window.ts
  shell/browser/api/electron_api_view.cc
  spec/api-browser-view-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42786 fix: dangling raw_ptr<Session> in UserDataLink
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42785 fix: dangling raw_ptr ElectronBrowserContext::extension_system_
  shell/browser/electron_browser_context.cc
Labels: semver/patch, target/31-x-y, target/32-x-y

#42789 refactor: minor electron browser context cleanup
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42788 fix: multiple move() calls on the same unique_ptr
  shell/browser/extensions/electron_extensions_browser_client.cc
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#42730 build: clean up BoringSSL patch
  patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
Labels: semver/patch, no-backport

#42829 ci: fix CircleCI config
  .circleci/config.yml
  .circleci/config/base.yml
Labels: semver/none, no-backport

#42825 refactor: run Windows `SelectFileDialog` out of process
  chromium_src/BUILD.gn
  shell/browser/electron_browser_main_parts.cc
  shell/utility/electron_content_utility_client.cc
Labels: backport, semver/patch, 31-x-y

#42843 build: fix release, add newVersion for tagging
  script/release/prepare-release.js
Labels: fast-track 🚅, backport-check-skip, semver/none, target/29-x-y, target/30-x-y, 31-x-y

#42742 chore: speed up azcopy on src cache
  .github/actions/restore-cache-azcopy/action.yml
Labels: semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#42827 build: remove all publish & build on macOS
  .circleci/config.yml
  .circleci/config/base.yml
Labels: backport, semver/none, 31-x-y

#42806 refactor: do not subclass ElectronSpeechRecognitionManagerDelegate from SpeechRecognitionEventListener
  shell/browser/electron_speech_recognition_manager_delegate.cc
  shell/browser/electron_speech_recognition_manager_delegate.h
Labels: semver/none, no-backport

#42822 fix: dangling raw_ptr<Session> in UserDataLink
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: backport, semver/patch, target/31-x-y, 32-x-y

#42826 refactor: run Windows `SelectFileDialog` out of process
  chromium_src/BUILD.gn
  shell/browser/electron_browser_main_parts.cc
  shell/utility/electron_content_utility_client.cc
Labels: backport, semver/patch, 30-x-y

#42853 fix: High Contrast mode not working on Windows
  shell/browser/electron_browser_client.cc
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y

#42722 build: migrate to GitHub Actions
  .github/actions/build-electron/action.yml
  .github/actions/checkout/action.yml
  .github/actions/fix-sync/action.yml
  .github/actions/free-space-macos/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/restore-cache-aks/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/build.yml
  .github/workflows/config/gclient.diff
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
  patches/node/.patches
  patches/node/build_support_python_3_12.patch
  script/actions/move-artifacts.sh
  script/actions/restore-artifacts.sh
  script/actions/run-tests.sh
  script/generate-config-gypi.py
  script/release/ci-release-build.js
  script/split-tests.js
  spec/api-app-spec.ts
  spec/api-protocol-spec.ts
Labels: backport, backport-check-skip, semver/none, 29-x-y

#42781 fix: `desktopCapturer` and `screen` source ids should match screen ids
  shell/browser/api/electron_api_desktop_capturer.cc
  spec/api-screen-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y

#42863 ci: fix Nan test failure on Linux
  .github/workflows/pipeline-segment-node-nan-test.yml
  script/nan-spec-runner.js
Labels: fast-track 🚅, semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#42864 ci: fix Nan test failure on Linux
  script/nan-spec-runner.js
Labels: backport, semver/none, target/29-x-y, target/30-x-y, target/31-x-y, 32-x-y

#42828 build: remove all publish & build on macOS
  .circleci/config.yml
  .circleci/config/base.yml
Labels: backport, semver/none, 30-x-y

#42870 build: update build-tools for GHA
  .github/actions/install-build-tools/action.yml
Labels: semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#42854 chore: allow multiple OS selection on bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: semver/none, no-backport

#42881 build: use new arc runner names
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#42880 build: fixup GHA running on fork PRs
  .github/actions/install-build-tools/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
Labels: semver/none, target/31-x-y, target/32-x-y

#42885 build: use new arc runner names
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: backport, semver/none, 32-x-y

#42886 build: use new arc runner names
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: backport, semver/none, 31-x-y

#42888 build: use new arc runner names
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: backport, semver/none, 29-x-y

#42887 build: use new arc runner names
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/pipeline-electron-docs-only.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: backport, semver/none, 30-x-y

#42883 fix: `desktopCapturer` and `screen` display ids should match
  shell/browser/api/electron_api_desktop_capturer.cc
  spec/api-screen-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y

#42850 fix: File System Access API should remember last picked directory
  shell/browser/file_system_access/file_system_access_permission_context.cc
  shell/browser/file_system_access/file_system_access_permission_context.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42878 fix: crash when resolving proxy due to network service restart
  shell/browser/browser_process_impl.cc
  shell/browser/electron_browser_context.cc
  shell/browser/net/resolve_proxy_helper.cc
  shell/browser/net/resolve_proxy_helper.h
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42877 build: fix Linux binary strip on publish, Linux x64 PrintInPDF test flake
  .github/actions/build-electron/action.yml
  .github/workflows/linux-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
  script/node-disabled-tests.json
  spec/webview-spec.ts
Labels: backport-check-skip, semver/none, 29-x-y

#42851 fix: iteration issues in hid `RevokeEphemeralDevicePermission`
  shell/browser/hid/hid_chooser_context.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42281 chore: fix `npm run lint` not working on Windows
  .gitattributes
  script/lint.js
  script/run-clang-format.py
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y

#42844 build: remove CircleCI
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/params.js
  .circleci/config/yarn.lock
  .circleci/fix-known-hosts.sh
  .devcontainer/devcontainer.json
  .env.example
  README.md
  docs/development/source-code-directory-structure.md
  script/doc-only-change.js
  script/download-circleci-artifacts.js
  script/push-patch.js
  spec/api-app-spec.ts
  spec/api-media-handler-spec.ts
  spec/lib/codesign-helpers.ts
  spec/version-bump-spec.ts
Labels: semver/none, target/29-x-y, target/30-x-y, target/31-x-y, gh-actions-migration, target/32-x-y

#42856 ci: auto comment on new issues for unsupported majors
  .github/workflows/issue-opened.yml
Labels: semver/none, no-backport

#42908 build: remove CircleCI (#42844)
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/params.js
  .circleci/config/yarn.lock
  .circleci/fix-known-hosts.sh
  .devcontainer/devcontainer.json
  .env.example
  README.md
  docs/development/source-code-directory-structure.md
  script/doc-only-change.js
  script/download-circleci-artifacts.js
  script/push-patch.js
  spec/api-app-spec.ts
  spec/api-media-handler-spec.ts
  spec/lib/codesign-helpers.ts
  spec/version-bump-spec.ts
Labels: backport, semver/none, 32-x-y

#42909 build: remove CircleCI (#42844)
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/params.js
  .circleci/config/yarn.lock
  .circleci/fix-known-hosts.sh
  .devcontainer/devcontainer.json
  .env.example
  README.md
  docs/development/source-code-directory-structure.md
  script/doc-only-change.js
  script/download-circleci-artifacts.js
  script/push-patch.js
  spec/api-app-spec.ts
  spec/api-media-handler-spec.ts
  spec/lib/codesign-helpers.ts
  spec/version-bump-spec.ts
Labels: backport, semver/none, target/30-x-y, 31-x-y

#42805 feat: add `getPercentComplete` / `getCurrentBytesPerSecond` / `getEndTime` to DownloadItem
  docs/api/download-item.md
  shell/browser/api/electron_api_download_item.cc
  shell/browser/api/electron_api_download_item.h
  spec/api-session-spec.ts
Labels: semver/minor, api-review/approved ✅, target/30-x-y, target/31-x-y, target/32-x-y

#42911 build: fix clang format location helper (again)
  script/lib/util.py
  script/run-clang-format.py
Labels: semver/none, target/31-x-y, target/32-x-y

#42824 fix: `BrowserWindow.setBackgroundColor` should work with transparency
  shell/browser/api/electron_api_web_contents.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y

#42320 feat: customize border radius of Views
  chromium_src/BUILD.gn
  docs/api/view.md
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/api/electron_api_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view.cc
  shell/browser/ui/inspectable_web_contents_view.h
  spec/api-browser-view-spec.ts
  spec/api-browser-window-spec.ts
  spec/api-view-spec.ts
  spec/api-web-contents-view-spec.ts
  spec/guest-window-manager-spec.ts
  spec/lib/screen-helpers.ts
  spec/webview-spec.ts
Labels: semver/minor, api-review/requested 🗳, no-backport

#42925 ci: upload test artifacts
  .github/workflows/pipeline-segment-electron-test.yml
  spec/.gitignore
  spec/lib/screen-helpers.ts
Labels: semver/none, target/30-x-y, target/31-x-y

#42899 fix: `getUserMedia` needs macOS system permissions check
  shell/browser/web_contents_permission_helper.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42926 build: fix clang format location helper
  .github/workflows/pipeline-electron-lint.yml
  script/lib/util.py
Labels: backport, semver/none, 31-x-y

#42910 build: remove CircleCI
  .circleci/.gitignore
  .circleci/config.yml
  .circleci/config/base.yml
  .circleci/config/build.js
  .circleci/config/jobs/lint.yml
  .circleci/config/package.json
  .circleci/config/params.js
  .circleci/config/yarn.lock
  .circleci/fix-known-hosts.sh
  .devcontainer/devcontainer.json
  .env.example
  README.md
  docs/development/source-code-directory-structure.md
  script/doc-only-change.js
  script/download-circleci-artifacts.js
  script/push-patch.js
  spec/api-app-spec.ts
  spec/api-media-handler-spec.ts
  spec/lib/codesign-helpers.ts
  spec/version-bump-spec.ts
Labels: backport, semver/none, 29-x-y

#42920 fix: crash with creating OffScreenWebContentsView
  shell/browser/osr/osr_web_contents_view.h
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#41205 feat: Implement password delegate for NSS
  docs/api/app.md
  filenames.gni
  lib/browser/api/app.ts
  shell/browser/electron_browser_client.cc
  shell/browser/electron_crypto_module_delegate_nss.cc
  shell/browser/electron_crypto_module_delegate_nss.h
  typings/internal-electron.d.ts
Labels: platform/linux, semver/minor, api-review/approved ✅, no-backport

#42929 fix: dangling raw_ptr<views::View> in api::View
  shell/browser/api/electron_api_view.cc
Labels: semver/patch, target/31-x-y, target/32-x-y

#42933 fix: dangling raw_ptr NodeBindings::uv_env_
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_browser_main_parts.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42944 fix: dangling raw_ptr<Session> in UserDataLink
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
Labels: backport, semver/patch, 30-x-y

#42956 chore: remove unused field `ElectronBrowserClient::browser_main_parts_`
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_client.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42949 chore: remove unused typedef CreateDownloadPathCallback
  shell/browser/electron_download_manager_delegate.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42947 refactor: remove unused web contents preferences methods
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42974 chore: remove unused WrappableBase::AfterInit()
  shell/common/gin_helper/wrappable.cc
  shell/common/gin_helper/wrappable_base.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42973 chore: remove unused BaseWindow::GetWeakPtr()
  shell/browser/api/electron_api_base_window.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#42950 build: update @electron/lint-roller to 2.3.0
  package.json
  yarn.lock
Labels: semver/none, target/32-x-y

#42561 feat: emit an event when accessing restricted path in File System Access API
  docs/api/session.md
  shell/browser/file_system_access/file_system_access_permission_context.cc
  shell/browser/file_system_access/file_system_access_permission_context.h
Labels: semver/minor, api-review/requested 🗳, target/30-x-y, target/31-x-y, target/32-x-y, needs-docs

#42957 docs: improve desktop capture example
  docs/api/desktop-capturer.md
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42997 docs: note macOS fullscreen events in fullscreen query
  docs/api/browser-window.md
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42862 feat: add transparency checking to `nativeTheme`
  docs/api/native-theme.md
  docs/api/system-preferences.md
  docs/breaking-changes.md
  filenames.auto.gni
  lib/browser/api/system-preferences.ts
  shell/browser/api/electron_api_native_theme.cc
  shell/browser/api/electron_api_native_theme.h
  spec/api-native-theme-spec.ts
Labels: semver/minor, api-review/approved ✅, target/30-x-y, target/31-x-y, target/32-x-y

#43019 chore: use v8::Local<>, not v8::Handle<>
  shell/browser/api/electron_api_base_window.cc
  shell/browser/native_window.cc
  shell/browser/native_window_mac.mm
  shell/common/api/electron_api_shell.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_render_frame_observer.h
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_renderer_client.h
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#43038 build: update docs-parser and typescript-definitions packages
  package.json
  yarn.lock
Labels: semver/patch, target/32-x-y

#43032 refactor: move safe_storage functions into anonymous namespace
  filenames.gni
  shell/browser/api/electron_api_safe_storage.cc
  shell/browser/api/electron_api_safe_storage.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#43034 fix: revert BrowserWindow unresponsive handling refactor
  lib/browser/api/browser-window.ts
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
Labels: semver/patch, target/32-x-y

#43040 chore: avoid crash while notification removal
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification_presenter.cc
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43033 fix: remove InspectableWebContentsViewMac
  filenames.gni
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/ui/cocoa/delayed_native_view_host.h
  shell/browser/ui/cocoa/delayed_native_view_host.mm
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view_mac.h
  shell/browser/ui/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: semver/patch, target/31-x-y, target/32-x-y

#43056 fix: always terminate active Node Streams
  shell/browser/net/node_stream_loader.cc
  shell/browser/net/node_stream_loader.h
  spec/api-protocol-spec.ts
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#42981 fix: redirect webview navigation methods
  lib/browser/guest-view-manager.ts
  lib/common/web-view-methods.ts
Labels: semver/patch, target/32-x-y

#43073 perf: avoid duplicate calculations in gin_helper::Dictionary getters
  shell/common/gin_helper/dictionary.h
  shell/common/gin_helper/persistent_dictionary.h
Labels: performance :checkered_flag:, semver/patch, no-backport

#43088 fix: remove InspectableWebContentsViewMac
  filenames.gni
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/ui/cocoa/delayed_native_view_host.h
  shell/browser/ui/cocoa/delayed_native_view_host.mm
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view_mac.h
  shell/browser/ui/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: backport, semver/patch, 32-x-y

#43079 fix: `showInactive` window not showing
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/31-x-y, target/32-x-y

#43089 chore: remove unused class `electron::ObjectLifeMonitor`
  filenames.gni
  shell/common/api/object_life_monitor.cc
  shell/common/api/object_life_monitor.h
  shell/renderer/api/context_bridge/object_cache.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, new-pr 🌱, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43104 chore: remove unused class `electron::ObjectLifeMonitor`
  filenames.gni
  shell/common/api/object_life_monitor.cc
  shell/common/api/object_life_monitor.h
  shell/renderer/api/context_bridge/object_cache.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: backport, semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, 32-x-y

#43096 fix: remove InspectableWebContentsViewMac
  filenames.gni
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/ui/cocoa/delayed_native_view_host.h
  shell/browser/ui/cocoa/delayed_native_view_host.mm
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view_mac.h
  shell/browser/ui/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: backport, semver/patch, 31-x-y

#43090 chore: remove unused & undocumented function v8Util.deleteHiddenValue()
  shell/common/api/electron_api_v8_util.cc
  typings/internal-ambient.d.ts
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43093 build: fixup ffmpeg release on x64 macOS
  .github/actions/build-electron/action.yml
Labels: wip ⚒, semver/none, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y

#43078 fix: vibrant view is inserted into Views API hierarchy
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/31-x-y, target/32-x-y

#43100 docs: update Node.js stable release policy
  docs/tutorial/electron-timelines.md
Labels: semver/patch, target/30-x-y, target/31-x-y, target/32-x-y

#43105 docs: fix broken link in bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation :notebook:, semver/patch, no-backport

#43111 chore: remove unused KeyWeakMap JS bindings
  filenames.gni
  shell/common/api/electron_api_key_weak_map.h
  shell/common/api/electron_api_v8_util.cc
Labels: semver/patch, target/29-x-y, target/30-x-y, target/31-x-y, target/32-x-y
