Repository electron/electron, pull requests merged in 2024-10, with the labels that each got.

#44035 build: convert all release scripts to typescript
  package.json
  script/prepare-appveyor.js
  script/release/ci-release-build.ts
  script/release/find-github-release.ts
  script/release/get-asset.ts
  script/release/get-url-hash.ts
  script/release/github-token.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/publish-to-npm.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
  script/release/uploaders/upload.py
  script/release/version-bumper.js
  script/release/version-bumper.ts
  script/release/version-utils.ts
  spec/release-notes-spec.ts
  spec/version-bump-spec.ts
  yarn.lock
Labels: semver/none, no-backport

#44057 build: use ts-node to spawn the version-bumper
  script/release/prepare-release.ts
Labels: semver/none, no-backport

#44059 build: convert all release scripts to typescript
  package.json
  script/prepare-appveyor.js
  script/release/ci-release-build.ts
  script/release/find-github-release.ts
  script/release/get-asset.ts
  script/release/get-url-hash.ts
  script/release/github-token.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/publish-to-npm.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
  script/release/uploaders/upload.py
  script/release/version-bumper.js
  script/release/version-bumper.ts
  script/release/version-utils.ts
  spec/release-notes-spec.ts
  spec/version-bump-spec.ts
  yarn.lock
Labels: backport, semver/none, target/30-x-y, target/31-x-y, target/32-x-y, 33-x-y

#44061 build: convert all release scripts to typescript
  package.json
  script/prepare-appveyor.js
  script/release/ci-release-build.ts
  script/release/find-github-release.ts
  script/release/get-asset.ts
  script/release/get-url-hash.ts
  script/release/github-token.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/publish-to-npm.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
  script/release/uploaders/upload.py
  script/release/version-bumper.js
  script/release/version-bumper.ts
  script/release/version-utils.ts
  spec/release-notes-spec.ts
  spec/version-bump-spec.ts
  yarn.lock
Labels: backport, semver/none, 31-x-y

#44062 build: convert all release scripts to typescript
  package.json
  script/prepare-appveyor.js
  script/release/ci-release-build.ts
  script/release/find-github-release.ts
  script/release/get-asset.ts
  script/release/get-url-hash.ts
  script/release/github-token.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/publish-to-npm.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
  script/release/uploaders/upload.py
  script/release/version-bumper.js
  script/release/version-bumper.ts
  script/release/version-utils.ts
  spec/release-notes-spec.ts
  spec/version-bump-spec.ts
  yarn.lock
Labels: backport, semver/none, 30-x-y

#44054 build: remove github actions dependabot on release branches
  .github/dependabot.yml
Labels: semver/none

#44067 perf: use ArrayBuffer::Data() instead of GetBackingStore()->Data()
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_url_loader.cc
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y

#44055 fix: -Wunsafe-buffer-usage warnings in ElectronAccessibilityUI ctor
  shell/browser/ui/webui/accessibility_ui.cc
Labels: semver/patch, new-pr 🌱, target/33-x-y

#44053 fix: -Wunsafe-buffer-usage warnings in WebFrameRenderer::ExecuteJavaScript()
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y

#44069 build: update some build dependencies
  .eslintrc.json
  appveyor-woa.yml
  default_app/main.ts
  docs/api/base-window.md
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/session.md
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/touch-bar.ts
  lib/browser/api/web-contents.ts
  lib/browser/default-menu.ts
  lib/browser/devtools.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  npm/install.js
  package.json
  script/doc-only-change.js
  script/lib/get-version.js
  script/lib/utils.js
  script/lint.js
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/spec-runner.js
  spec/api-browser-window-spec.ts
  spec/api-context-bridge-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-ipc-renderer-spec.ts
  spec/api-net-spec.ts
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/fixtures/api/singleton-data/main.js
  spec/fixtures/api/utility-process/net.js
  spec/fixtures/native-addon/uv-dlopen/index.js
  spec/lib/video-helpers.js
  spec/package.json
  spec/security-warnings-spec.ts
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
  spec/webview-spec.ts
  spec/yarn.lock
  tsconfig.json
  typings/internal-electron.d.ts
  yarn.lock
Labels: backport, semver/none, 33-x-y

#44070 build: update some build dependencies
  .eslintrc.json
  appveyor-woa.yml
  appveyor.yml
  default_app/main.ts
  docs/api/base-window.md
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/session.md
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/touch-bar.ts
  lib/browser/api/web-contents.ts
  lib/browser/default-menu.ts
  lib/browser/devtools.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  npm/install.js
  package.json
  script/doc-only-change.js
  script/lib/get-version.js
  script/lib/utils.js
  script/lint.js
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/spec-runner.js
  spec/api-browser-window-spec.ts
  spec/api-context-bridge-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-ipc-renderer-spec.ts
  spec/api-net-spec.ts
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/fixtures/api/singleton-data/main.js
  spec/fixtures/api/utility-process/net.js
  spec/fixtures/native-addon/uv-dlopen/index.js
  spec/lib/video-helpers.js
  spec/package.json
  spec/security-warnings-spec.ts
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
  spec/webview-spec.ts
  spec/yarn.lock
  tsconfig.json
  typings/internal-electron.d.ts
  yarn.lock
Labels: backport, semver/none, 32-x-y

#44071 build: update some build dependencies
  .eslintrc.json
  appveyor-woa.yml
  appveyor.yml
  default_app/main.ts
  docs/api/base-window.md
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/session.md
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/touch-bar.ts
  lib/browser/api/web-contents.ts
  lib/browser/default-menu.ts
  lib/browser/devtools.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  npm/install.js
  package.json
  script/doc-only-change.js
  script/lib/get-version.js
  script/lib/utils.js
  script/lint.js
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/spec-runner.js
  spec/api-browser-window-spec.ts
  spec/api-context-bridge-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-ipc-renderer-spec.ts
  spec/api-net-spec.ts
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/fixtures/api/singleton-data/main.js
  spec/fixtures/native-addon/uv-dlopen/index.js
  spec/lib/video-helpers.js
  spec/package.json
  spec/security-warnings-spec.ts
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
  spec/webview-spec.ts
  spec/yarn.lock
  tsconfig.json
  typings/internal-electron.d.ts
  yarn.lock
Labels: backport, semver/none, 31-x-y

#44072 build: update some build dependencies
  .eslintrc.json
  appveyor-woa.yml
  appveyor.yml
  default_app/main.ts
  docs/api/base-window.md
  docs/api/client-request.md
  docs/api/incoming-message.md
  docs/api/session.md
  lib/browser/api/menu-item-roles.ts
  lib/browser/api/touch-bar.ts
  lib/browser/api/web-contents.ts
  lib/browser/default-menu.ts
  lib/browser/devtools.ts
  lib/browser/guest-view-manager.ts
  lib/common/api/net-client-request.ts
  npm/install.js
  package.json
  script/doc-only-change.js
  script/lib/get-version.js
  script/lib/utils.js
  script/lint.js
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/spec-runner.js
  spec/api-browser-window-spec.ts
  spec/api-context-bridge-spec.ts
  spec/api-crash-reporter-spec.ts
  spec/api-ipc-renderer-spec.ts
  spec/api-net-spec.ts
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/api-web-request-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/api/fork-with-node-options.js
  spec/fixtures/api/singleton-data/main.js
  spec/fixtures/native-addon/uv-dlopen/index.js
  spec/lib/video-helpers.js
  spec/package.json
  spec/security-warnings-spec.ts
  spec/ts-smoke/electron/main.ts
  spec/ts-smoke/electron/renderer.ts
  spec/webview-spec.ts
  spec/yarn.lock
  tsconfig.json
  typings/internal-electron.d.ts
  yarn.lock
Labels: backport, semver/none, 30-x-y

#44079 build: ensure consistent usage of getRepo
  script/release/uploaders/upload-to-github.ts
Labels: semver/none, target/30-x-y

#44058 build: cleanup release scripts, separate cli entrypoints from logic
  script/release/bin/README.md
  script/release/bin/cleanup-release.ts
  script/release/bin/prepare-for-release.ts
  script/release/bin/print-next-version.ts
  script/release/bin/publish-to-github.ts
  script/release/bin/publish-to-npm.ts
  script/release/bin/run-release-builds.ts
  script/release/bin/validate-before-publish.ts
  script/release/get-asset.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/run-release-ci-jobs.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#44083 build: cleanup release scripts, separate cli entrypoints from logic
  script/release/bin/README.md
  script/release/bin/cleanup-release.ts
  script/release/bin/prepare-for-release.ts
  script/release/bin/print-next-version.ts
  script/release/bin/publish-to-github.ts
  script/release/bin/publish-to-npm.ts
  script/release/bin/run-release-builds.ts
  script/release/bin/validate-before-publish.ts
  script/release/get-asset.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/run-release-ci-jobs.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
Labels: backport, semver/none, 31-x-y

#44084 build: cleanup release scripts, separate cli entrypoints from logic
  script/release/bin/README.md
  script/release/bin/cleanup-release.ts
  script/release/bin/prepare-for-release.ts
  script/release/bin/print-next-version.ts
  script/release/bin/publish-to-github.ts
  script/release/bin/publish-to-npm.ts
  script/release/bin/run-release-builds.ts
  script/release/bin/validate-before-publish.ts
  script/release/get-asset.ts
  script/release/notes/index.ts
  script/release/notes/notes.ts
  script/release/prepare-release.ts
  script/release/release-artifact-cleanup.ts
  script/release/release.ts
  script/release/run-release-ci-jobs.ts
  script/release/types.ts
  script/release/uploaders/upload-to-github.ts
Labels: backport, semver/none, 30-x-y

#44088 build: fix relative file read during npm publish
  script/release/bin/publish-to-npm.ts
Labels: fast-track 🚅, semver/none, target/30-x-y, target/31-x-y, target/33-x-y

#44065 build: use node 20.17 on Windows
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  script/nan-spec-runner.js
  script/spec-runner.js
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#44097 fix: -Wunsafe-buffer-usage warnings in WebFrameRenderer::ExecuteJavaScript() (32-x-y)
  shell/renderer/api/electron_api_web_frame.cc
Labels: backport, semver/patch, target/31-x-y, 32-x-y

#44076 fix: remove use of deprecated API base::Hash()
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44095 perf: use ArrayBuffer::Data() instead of GetBackingStore()->Data() (32-x-y)
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_url_loader.cc
Labels: backport, semver/patch, target/31-x-y, 32-x-y

#44068 fix: deprecated API and -Wunsafe-buffer-usage warnings in AsarFileValidator
  shell/browser/net/asar/asar_file_validator.cc
  shell/browser/net/asar/asar_file_validator.h
Labels: semver/patch, target/33-x-y

#44094 ci: add datadog test logging
  .github/workflows/pipeline-segment-electron-test.yml
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y

#44148 fix: context shear in cli_remove_deprecated_v8_flag.patch
  patches/node/cli_remove_deprecated_v8_flag.patch
Labels: semver/patch, fast-track 🚅, no-backport

#44152 ci: only upload to datadog when running tests
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none

#44153 refactor: revert url::DomainIs() for cookie domains
  docs/api/cookies.md
  shell/browser/api/electron_api_cookies.cc
  spec/api-session-spec.ts
Labels: new-pr 🌱, semver/none, target/33-x-y

#44149 fix: -Wunsafe-buffer-usage warnings in GetNextZoomLevel()
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44142 ci: add datadog test logging
  .github/workflows/pipeline-segment-electron-test.yml
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/30-x-y, target/31-x-y

#44134 fix: -Wunsafe-buffer-usage warning in WriteAsciiChunk()
  shell/common/heap_snapshot.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44133 fix: -Wunsafe-buffer-usage warning in HasWordCharacters()
  shell/renderer/api/electron_api_spell_check_client.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44135 build: update NMV to 132
  build/args/all.gn
Labels: semver/none, no-backport

#44127 refactor: spanify image utils
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  shell/common/api/electron_api_native_image_mac.mm
  shell/common/node_util.cc
  shell/common/node_util.h
  shell/common/skia_util.cc
  shell/common/skia_util.h
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44181 ci: don't call datadog test logging on forks
  .github/workflows/pipeline-segment-electron-test.yml
  appveyor-woa.yml
  appveyor.yml
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y

#44189 fix: clang variable configuration in generated node headers
  patches/node/.patches
  patches/node/build_restore_clang_as_default_compiler_on_macos.patch
  script/generate-config-gypi.py
Labels: semver/patch, fast-track 🚅, target/31-x-y, target/32-x-y, target/33-x-y

#44015 docs: clarify interplay between utility process events
  docs/api/utility-process.md
Labels: documentation :notebook:, semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43985 build: update ts defs and docs parser
  .github/workflows/archaeologist-dig.yml
  package.json
  script/create-api-json.js
  script/create-api-json.mjs
  yarn.lock
Labels: semver/none, target/30-x-y, target/31-x-y, target/32-x-y, target/33-x-y

#44185 fix: -Wunsafe-buffer-usage warnings when read()ing and write()ing integers
  shell/browser/electron_browser_main_parts_posix.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#43473 feat: add WebFrameMain detached property
  docs/api/session.md
  docs/api/structures/ipc-main-event.md
  docs/api/structures/ipc-main-invoke-event.md
  docs/api/web-contents.md
  docs/api/web-frame-main.md
  docs/api/web-request.md
  docs/breaking-changes.md
  lib/browser/api/web-contents.ts
  lib/browser/guest-view-manager.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_converters/frame_converter.cc
  shell/common/gin_converters/frame_converter.h
  spec/api-browser-window-spec.ts
  spec/api-ipc-spec.ts
  spec/api-web-frame-main-spec.ts
  spec/fixtures/sub-frames/preload.js
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/minor, backport/requested 🗳, api-review/approved ✅, target/33-x-y

#44216 fix: -Wunsafe-buffer-usage warnings in GetNextZoomLevel() (#44149)
  shell/browser/ui/inspectable_web_contents.cc
Labels: backport, semver/patch, 31-x-y

#44215 fix: -Wunsafe-buffer-usage warnings when read()ing and write()ing integers (31-x-y)
  shell/browser/electron_browser_main_parts_posix.cc
Labels: backport, semver/patch, 31-x-y

#44211 fix: -Wunsafe-buffer-usage warning in ChunkedDataPipeReadableStream
  filenames.gni
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/message_port.cc
  shell/browser/electron_crypto_module_delegate_nss.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/net_converter.cc
  shell/common/v8_util.cc
  shell/common/v8_util.h
  shell/renderer/api/electron_api_ipc_renderer.cc
  shell/renderer/electron_api_service_impl.cc
  shell/services/node/parent_port.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y

#44206 test: run visibility-state-spec.ts first
  script/split-tests.js
  spec/index.js
Labels: semver/none, no-backport

#44210 docs: update timelines for E34
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/33-x-y

#44228 fix: SCContentSharingPicker crash in iframes
  patches/chromium/.patches
  patches/chromium/feat_allow_-4_as_a_macos_screen_share_id.patch
  patches/chromium/feat_allow_usage_of_sccontentsharingpicker_on_supported_platforms.patch
Labels: backport, semver/patch, 33-x-y

#44231 chore: cherry-pick 3 changes from 3-M129
  patches/v8/.patches
  patches/v8/cherry-pick-81155a8f3b20.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44233 chore: cherry-pick 2 changes from 3-M129
  patches/v8/.patches
  patches/v8/cherry-pick-81155a8f3b20.patch
  patches/v8/cherry-pick-9542895cdd3d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 30-x-y

#44232 chore: cherry-pick 2 changes from 3-M129
  patches/v8/.patches
  patches/v8/cherry-pick-81155a8f3b20.patch
  patches/v8/cherry-pick-9542895cdd3d.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44229 build: update devcontainer sha
  .devcontainer/docker-compose.yml
Labels: semver/none, target/32-x-y, target/33-x-y

#44240 ci: use env variable in branch created workflow
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#43610 docs: add section on resource management to base-window.md
  docs/api/base-window.md
Labels: documentation :notebook:, semver/patch, no-backport

#44238 fix: -Wunsafe-buffer-usage warnings in TaskbarHost::SetThumbarButtons()
  shell/browser/ui/win/taskbar_host.cc
  shell/common/v8_util.cc
Labels: semver/patch, new-pr 🌱, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44243 fix: ensure `utilityProcess` only emits one 'exit' event
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  spec/api-utility-process-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44257 fix: trace-startup crashing child process on macOS
  shell/app/electron_library_main.mm
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_delegate.h
  spec/chromium-spec.ts
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44248 fix: use proper PDF save approach
  patches/chromium/fix_crash_when_saving_edited_pdf_files.patch
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44246 fix: Linux crash after `webContents.print()` with no parent window
  patches/chromium/printing.patch
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44256 build: remove dead code in prepare release script
  script/release/prepare-release.ts
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44290 ci: use Node.js 20 in Bake AppVeyor Image workflow
  .github/CODEOWNERS
  .github/workflows/update_appveyor_image.yml
Labels: semver/none, no-backport

#44261 docs: removed AngularJS Batarang from the Devtool Extension Support
  docs/tutorial/devtools-extension.md
Labels: documentation :notebook:, semver/patch, no-backport

#44280 chore: fixup reclient read only access on forks
  .github/actions/install-build-tools/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  appveyor-woa.yml
  appveyor.yml
Labels: fast-track 🚅, semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44302 build: fix main printing patch conflict
  patches/chromium/printing.patch
Labels: fast-track 🚅, semver/none, no-backport

#44306 chore: fixup reclient read only access on forks
  .github/actions/install-build-tools/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  appveyor-woa.yml
  appveyor.yml
Labels: backport, semver/none, target/31-x-y, 32-x-y

#44304 chore: fixup reclient read only access on forks
  .github/actions/install-build-tools/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  appveyor-woa.yml
  appveyor.yml
Labels: backport, semver/none, 33-x-y

#44255 chore: cherry-pick 3 changes from 1-M129
  patches/config.json
  patches/skia/.patches
  patches/skia/m126-lts_ganesh_avoid_int_overflow_in_drawatlasopimpl.patch
  patches/v8/.patches
  patches/v8/cherry-pick-f612d9a40b19.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44292 fix: trace-startup crashing child process on macOS (32-x-y)
  shell/app/electron_library_main.mm
  shell/app/electron_main_delegate.cc
  shell/app/electron_main_delegate.h
  spec/chromium-spec.ts
Labels: backport, semver/patch, 32-x-y

#44312 chore: backport 2 changes from 2-M127 to 0-M129
  patches/config.json
  patches/skia/.patches
  patches/skia/sksl_rp_prevent_overflow_when_computing_slot_allocation_size.patch
  patches/v8/.patches
  patches/v8/merged_maglev_fix_non-materialized_receiver_closure.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44078 fix: respect setAlwaysOnTop before showInactive on Linux under X11
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#43617 feat: expose frame & move properties to console-message event object
  docs/api/web-contents.md
  docs/breaking-changes.md
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_converters/blink_converter.h
  spec/api-protocol-spec.ts
  spec/api-web-contents-spec.ts
  spec/chromium-spec.ts
  spec/extensions-spec.ts
  spec/fixtures/api/context-bridge/context-bridge-mutability/main.js
  spec/security-warnings-spec.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#44341 fix: crash when generating shortcut text for super accelerator
  patches/chromium/.patches
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/ui_add_missing_shortcut_text_for_vkey_command_on_linux.patch
  spec/api-menu-spec.ts
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44318 fix: software compositing infinite loop
  patches/chromium/.patches
  patches/chromium/fix_software_compositing_infinite_loop.patch
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44333 fix: silence -Wunsafe-buffer-usage warning in GetPreferredLanguages()
  shell/common/language_util_linux.cc
Labels: semver/patch, new-pr 🌱, no-backport

#44357 chore: backport 2 changes from 0-M130
  patches/v8/.patches
  patches/v8/merged_don_t_assume_all_turbofan_frames_are_javascript.patch
  patches/v8/merged_wasm_do_not_inline_wrappers_with_ref_extern_parameter.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44356 chore: backport 2 changes from 0-M130
  patches/v8/.patches
  patches/v8/merged_don_t_assume_all_turbofan_frames_are_javascript.patch
  patches/v8/merged_wasm_do_not_inline_wrappers_with_ref_extern_parameter.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44355 chore: backport 15 changes from 2-M127 to 1-M129
  patches/DirectXShaderCompiler/.patches
  patches/DirectXShaderCompiler/fix_asan_uaf_in_dxilconditionalmem2reg_6910.patch
  patches/chromium/.patches
  patches/chromium/m126-lts_check_string_range_in_shapesegment.patch
  patches/chromium/m126-lts_don_t_perform_pseudo-element_ident_parsing_on_non-ascii.patch
  patches/chromium/m126-lts_fix_a_range_check_for_when_it_overflows.patch
  patches/chromium/m126-lts_protect_automation_rate_from_non-deterministic_change.patch
  patches/chromium/m126-lts_reland_fix_stringview_to_crash_when_offset_length.patch
  patches/config.json
  patches/skia/.patches
  patches/skia/disallow_sksl_when_deserializing_drawables_in_custom_typefaces.patch
  patches/skia/ganesh_avoid_int_overflow_in_patternhelper.patch
  patches/skia/m126-lts_ganesh_avoid_int_overflow_when_combining_regionops.patch
  patches/skia/m126-lts_ganesh_fix_meshop_index_combination_logic.patch
  patches/skia/m126-lts_sksl_rp_prevent_overflow_when_computing_slot_allocation.patch
  patches/v8/.patches
  patches/v8/m126-lts_compiler_clear_stale_data_for_zeroextendsword32toword64.patch
  patches/v8/m126-lts_wasm_don_t_catch_uncatchable_exceptions_in_the_jspi.patch
  patches/v8/merged_heap_sandbox_update_ept_s_evacuation_entries_in_scavenger.patch
  patches/v8/merged_turbofan_handle_type_none_in_samevalue.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44339 docs: clarify utilityProcess child.pid value
  docs/api/utility-process.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44349 test: fixup flaky tests
  spec/api-browser-window-spec.ts
  spec/api-protocol-spec.ts
  spec/chromium-spec.ts
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44348 fix: -Wunsafe-buffer-usage warning in didRegisterForRemoteNotificationsWithDeviceToken
  filenames.gni
  shell/browser/mac/electron_application_delegate.mm
  shell/common/api/electron_api_native_image_mac.mm
  shell/common/mac_util.h
  shell/common/mac_util.mm
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44236 chore: cherry-pick 3 changes from 2-M129
  patches/chromium/.patches
  patches/chromium/cherry-pick-c333ed995449.patch
  patches/v8/.patches
  patches/v8/cherry-pick-a7766feb0a90.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44389 test: fixup broken tests in 32-x-y
  spec/api-session-spec.ts
Labels: fast-track 🚅, backport-check-skip, semver/none

#44392 build: update linux container
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y

#44397 build: update linux container
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
Labels: backport, semver/none, 32-x-y

#44383 test: deflake flaky tests on linux
  spec/api-browser-window-spec.ts
  spec/crash-spec.ts
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44396 build: update linux container
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
Labels: backport, semver/none, 33-x-y

#44406 fix: crash on netlog connection error
  shell/browser/api/electron_api_net_log.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44412 perf: prefer NewFromUtf8Literal() over NewFromUtf8() for string literals
  shell/common/api/electron_api_asar.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: performance :checkered_flag:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44423 fix: keep gdk_pixbuf a dynamic dependency
  shell/browser/ui/electron_gdk_pixbuf.sigs
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44424 build: improve `gen-libc++-filenames` output
  .github/workflows/pipeline-segment-electron-gn-check.yml
  script/gen-libc++-filenames.js
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y

#44405 refactor: prefer `inline constexpr string_view` for string constants
  BUILD.gn
  filenames.gni
  shell/app/electron_content_client.cc
  shell/app/electron_main_linux.cc
  shell/app/electron_main_mac.cc
  shell/app/electron_main_win.cc
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/browser/native_window_views_win.cc
  shell/common/electron_constants.cc
  shell/common/electron_constants.h
Labels: semver/patch, no-backport

#44425 refactor: move node ofs script to electron
  BUILD.gn
  patches/node/build_add_gn_build_files.patch
  script/generate_node_version_header.py
  script/node/generate_node_version_header.py
  script/node/generate_original_fs.py
Labels: semver/none, no-backport

#44366 fix: -Wunsafe-buffer-usage warnings with argc, argv
  BUILD.gn
  shell/app/electron_library_main.mm
  shell/app/electron_main_linux.cc
  shell/app/electron_main_win.cc
  shell/app/node_main.cc
  shell/app/node_main.h
  shell/common/electron_command_line.cc
  shell/common/electron_command_line.h
  shell/common/node_bindings.cc
Labels: semver/patch, no-backport

#44391 docs: Fix `powerMonitor` docs for type generation of `speed-limit-change`
  docs/api/power-monitor.md
Labels: documentation :notebook:, semver/patch, no-backport

#44431 build: fix python util verbose mode logic
  .github/actions/build-electron/action.yml
  script/lib/config.py
  script/lib/util.py
  script/release/uploaders/upload.py
  script/strip-binaries.py
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y

#44455 fix: -Wunsafe-buffer-usage warnings in TaskbarHost::SetThumbarButtons() (31-x-y)
  shell/browser/ui/win/taskbar_host.cc
Labels: backport, semver/patch, no-backport, 31-x-y

#44430 docs: fix `win.getContentView(`) return type
  docs/api/base-window.md
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44408 fix: update shell.openExternal to correctly focus on external window
  shell/common/platform_util_mac.mm
  spec/api-shell-spec.ts
Labels: semver/patch, target/33-x-y, target/34-x-y

#44056 build: enable -Wunsafe-buffer-usage warnings
  build/args/all.gn
  electron_unsafe_buffers_paths.txt
Labels: component/build, semver/patch, no-backport

#44439 perf: remove isolate scope from DidProcessTask()
  shell/browser/microtasks_runner.cc
Labels: performance :checkered_flag:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44478 docs: fix win.setContentView() arg type
  docs/api/base-window.md
Labels: semver/patch, fast-track 🚅, target/32-x-y, target/33-x-y, target/34-x-y

#44451 fix: flaky utility and BrowserView tests
  spec/api-browser-view-spec.ts
  spec/api-utility-process-spec.ts
Labels: semver/none, no-backport

#44485 chore: cherry-pick 1 change from 2-M130
  patches/config.json
  patches/dawn/.patches
  patches/dawn/tint_validate_that_align_is_large_enough.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44482 chore: cherry-pick 3 changes from 1-M130
  patches/chromium/.patches
  patches/chromium/cherry-pick-8c4edae5e34d.patch
  patches/v8/.patches
  patches/v8/cherry-pick-153d4e84e5d1.patch
  patches/v8/cherry-pick-d9893f4856af.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44490 build: handle out of disk space on source cache
  .github/actions/checkout/action.yml
  .github/actions/restore-cache-aks/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/clean-src-cache.yml
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44484 chore: backport 1 change from 2-M130
  patches/config.json
  patches/dawn/.patches
  patches/dawn/tint_validate_that_align_is_large_enough.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y
