Repository electron/electron, pull requests merged in 2024-11, with the labels that each got.

#43693 docs: add custom titlebar example
  .markdownlint-cli2.jsonc
  docs/api/structures/base-window-options.md
  docs/fiddles/features/window-customization/custom-title-bar/custom-drag-region/index.html
  docs/fiddles/features/window-customization/custom-title-bar/custom-drag-region/main.js
  docs/fiddles/features/window-customization/custom-title-bar/custom-drag-region/styles.css
  docs/fiddles/features/window-customization/custom-title-bar/custom-title-bar/index.html
  docs/fiddles/features/window-customization/custom-title-bar/custom-title-bar/main.js
  docs/fiddles/features/window-customization/custom-title-bar/custom-title-bar/styles.css
  docs/fiddles/features/window-customization/custom-title-bar/native-window-controls/main.js
  docs/fiddles/features/window-customization/custom-title-bar/remove-title-bar/main.js
  docs/fiddles/features/window-customization/custom-title-bar/starter-code/main.js
  docs/fiddles/features/window-customization/custom-window-styles/frameless-windows/main.js
  docs/fiddles/features/window-customization/custom-window-styles/transparent-windows/index.html
  docs/fiddles/features/window-customization/custom-window-styles/transparent-windows/main.js
  docs/fiddles/features/window-customization/custom-window-styles/transparent-windows/styles.css
  docs/images/frameless-window.png
  docs/images/transparent-window-mission-control.png
  docs/images/transparent-window.png
  docs/tutorial/custom-title-bar.md
  docs/tutorial/custom-window-interactions.md
  docs/tutorial/custom-window-styles.md
  docs/tutorial/window-customization.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44501 perf: use v8::String::NewFromUtf8Literal in ToV8() gin converter
  shell/common/gin_converters/std_converter.h
Labels: performance :checkered_flag:, semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44500 refactor: remove unused C string ToV8() gin converter
  shell/browser/api/electron_api_web_contents.cc
  shell/common/gin_converters/std_converter.h
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44525 build: remove unused lint package
  package.json
  yarn.lock
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44516 docs: fix apostrophe typo "Electrons" -> "Electron's"
  docs/api/web-frame.md
  docs/experimental.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44487 docs: Update Squirrel Run at Login docs to be modern
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, no-backport

#44512 chore: add process memory limit details in parition_alloc oom handler
  patches/chromium/.patches
  patches/chromium/cherry-pick-8c4edae5e34d.patch
  patches/chromium/fix_software_compositing_infinite_loop.patch
  patches/chromium/oom_add_commit_limit_available_to_oom_exception_arguments.patch
  patches/chromium/printing.patch
  patches/dawn/tint_validate_that_align_is_large_enough.patch
  patches/v8/cherry-pick-153d4e84e5d1.patch
  patches/v8/cherry-pick-d9893f4856af.patch
Labels: semver/patch, backport-check-skip, target/32-x-y

#44520 fix: crash when generating shortcut text for super accelerator (33-x-y)
  patches/chromium/.patches
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/ui_add_missing_shortcut_text_for_vkey_command_on_linux.patch
  spec/api-menu-spec.ts
Labels: backport, semver/patch, no-backport, 33-x-y

#44498 refactor: more inline constexpr string view
  filenames.gni
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/electron_browser_client.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/hid/hid_chooser_context.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/serial/serial_chooser_context.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, no-backport

#44513 chore: remove use of banned absl::optional
  shell/browser/electron_browser_client.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44515 refactor: replace base::StringPrintf() calls with absl::StrFormat()
  shell/browser/api/electron_api_session.cc
  shell/browser/extensions/api/management/electron_management_api_delegate.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/hid/hid_chooser_controller.cc
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/proxying_url_loader_factory.cc
  shell/browser/net/proxying_websocket.cc
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/views/global_menu_bar_x11.cc
  shell/common/application_info.cc
  shell/common/color_util.cc
  shell/common/gin_converters/serial_port_info_converter.h
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, target/34-x-y

#44432 build: add new status to verify if all the required gha jobs have run
  .github/workflows/build.yml
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44546 docs: capitalize POSIX and Windows correctly
  docs/api/app.md
  docs/api/command-line-switches.md
  docs/api/shell.md
  docs/api/utility-process.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44555 build: add new status to verify if all the required gha jobs have run
  .github/workflows/build.yml
Labels: backport, semver/none, target/31-x-y, 32-x-y

#44514 fix: remove use of banned std::to_string()
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44545 test: fixup flaky session tests
  spec/api-session-spec.ts
Labels: semver/none, target/33-x-y, target/34-x-y

#44567 fix: ftbfs when including simdjson in Node.js
  patches/node/.patches
  patches/node/chore_disable_deprecation_ftbfs_in_simdjson_header.patch
Labels: semver/patch, fast-track 🚅, no-backport

#44572 chore: backport editcontext ime input alignment fixes
  patches/chromium/.patches
  patches/chromium/editcontext_return_physical_pixels_from_firstrectforcharacterrange.patch
  patches/chromium/editcontext_use_empty_control_and_selection_bounds_as_fallbacks.patch
  patches/chromium/oom_add_commit_limit_available_to_oom_exception_arguments.patch
Labels: semver/patch, backport-check-skip, 32-x-y

#44547 docs: clarify that sessions use cache by default
  docs/api/session.md
Labels: documentation :notebook:, semver/patch, target/34-x-y

#44548 chore: remove executable flag from docs/api/app.md file permissions
  docs/api/app.md
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44581 build: also lint mjs files
  script/create-api-json.mjs
  script/lint.js
  spec/fixtures/api/pdf-reader.mjs
  spec/fixtures/esm/import-meta/main.mjs
  spec/fixtures/esm/import-meta/preload.mjs
Labels: semver/none, no-backport

#44511 feat: GPU shared texture offscreen rendering (33-x-y)
  docs/api/structures/offscreen-shared-texture.md
  docs/api/structures/web-preferences.md
  docs/api/web-contents.md
  docs/tutorial/offscreen-rendering.md
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/osr_shared_texture_remove_keyed_mutex_on_win_dxgi.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/osr/osr_host_display_client.cc
  shell/browser/osr/osr_host_display_client.h
  shell/browser/osr/osr_host_display_client_mac.mm
  shell/browser/osr/osr_paint_event.cc
  shell/browser/osr/osr_paint_event.h
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/osr/osr_video_consumer.h
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/osr/osr_web_contents_view.h
  shell/common/gin_converters/osr_converter.cc
  shell/common/gin_converters/osr_converter.h
  shell/common/options_switches.cc
  shell/common/options_switches.h
  spec/api-browser-window-spec.ts
  spec/fixtures/assets/osr.png
  spec/fixtures/native-addon/osr-gpu/binding.gyp
  spec/fixtures/native-addon/osr-gpu/binding_win.cc
  spec/fixtures/native-addon/osr-gpu/lib/osr-gpu.js
  spec/fixtures/native-addon/osr-gpu/napi_utils.h
  spec/fixtures/native-addon/osr-gpu/package.json
  spec/package.json
  spec/yarn.lock
Labels: backport, semver/minor, backport/approved ✅, 33-x-y

#44589 chore: remove revert_mojo_force_blink_headers_to_only_be_included_in_blink.patch
  BUILD.gn
  patches/chromium/.patches
  patches/chromium/revert_mojo_force_blink_headers_to_only_be_included_in_blink.patch
Labels: semver/none, target/34-x-y

#35987 feat: add optional animation parameter to BrowserWindow.setVibrancy
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
Labels: semver/minor, api-review/approved ✅, no-backport

#44488 test: exercise fuller `globalShortcut` matrix
  spec/api-global-shortcut-spec.ts
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y

#44631 ci: remove from issue triage on issue transferred
  .github/workflows/issue-transferred.yml
Labels: semver/none, no-backport

#44114 fix: add theme data source for devtools.
  chromium_src/BUILD.gn
  filenames.gni
  shell/browser/ui/devtools_ui.cc
  shell/browser/ui/devtools_ui.h
  shell/browser/ui/devtools_ui_bundle_data_source.cc
  shell/browser/ui/devtools_ui_bundle_data_source.h
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/browser/ui/devtools_ui_theme_data_source.h
  spec/chromium-spec.ts
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44646 chore: cherry-pick 1 changes from 3-M130
  patches/chromium/.patches
  patches/chromium/cherry-pick-e699ac35ac6c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44649 chore: cherry-pick 1 changes from 0-M131
  patches/chromium/.patches
  patches/chromium/cherry-pick-923797bac925.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44645 chore: cherry-pick 1 changes from 3-M130
  patches/chromium/.patches
  patches/chromium/cherry-pick-e699ac35ac6c.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44629 refactor: unfilter unresponsive events
  lib/browser/api/browser-window.ts
  lib/browser/api/web-contents.ts
  patches/chromium/.patches
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/33-x-y, target/34-x-y

#44650 build: fix python warnings "SyntaxWarning: invalid escape sequence '\w'"
  build/generate_node_defines.py
  script/generate-config-gypi.py
  script/zip-symbols.py
Labels: component/build, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44639 fix: add theme data source for devtools.(32-x-y)
  chromium_src/BUILD.gn
  filenames.gni
  shell/browser/ui/devtools_ui.cc
  shell/browser/ui/devtools_ui.h
  shell/browser/ui/devtools_ui_bundle_data_source.cc
  shell/browser/ui/devtools_ui_bundle_data_source.h
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/browser/ui/devtools_ui_theme_data_source.h
  spec/chromium-spec.ts
Labels: backport, semver/patch, 32-x-y

#44669 refactor: unfilter unresponsive events
  lib/browser/api/browser-window.ts
  lib/browser/api/web-contents.ts
  patches/chromium/.patches
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
Labels: backport, semver/patch, 34-x-y

#44667 refactor: unfilter unresponsive events
  lib/browser/api/browser-window.ts
  lib/browser/api/web-contents.ts
  patches/chromium/.patches
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/api/electron_api_web_contents.cc
Labels: backport, semver/patch, 33-x-y

#44656 fix: `WebContentsView` removal should compare directly
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
  spec/api-web-contents-view-spec.ts
Labels: semver/patch, fast-track 🚅, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44672 fix: `WebContentsView` removal should compare directly
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
  spec/api-web-contents-view-spec.ts
Labels: backport, semver/patch, 32-x-y

#44673 fix: `WebContentsView` removal should compare directly
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
  spec/api-web-contents-view-spec.ts
Labels: backport, semver/patch, 31-x-y

#44426 fix: revert required portal version for file chooser dialogs
  docs/api/command-line-switches.md
  docs/api/dialog.md
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
  shell/browser/ui/file_dialog_linux.cc
Labels: semver/minor, api-review/approved ✅, target/32-x-y, target/33-x-y, target/34-x-y

#44648 chore: cherry-pick 1 changes from 0-M131
  patches/chromium/.patches
  patches/chromium/cherry-pick-923797bac925.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44653 chore: update extensions features
  shell/common/extensions/api/_api_features.json
  shell/common/extensions/api/_manifest_features.json
  shell/common/extensions/api/_permission_features.json
Labels: semver/patch, target/33-x-y, target/34-x-y

#44623 fix: crash when generating shortcut text for super accelerator (32-x-y)
  patches/chromium/.patches
  patches/chromium/ui_add_missing_shortcut_text_for_vkey_command_on_linux.patch
  spec/api-menu-spec.ts
Labels: backport, semver/patch, 32-x-y

#44677 fix: `utilityProcess` pid should be `undefined` after exit
  docs/api/utility-process.md
  shell/browser/api/electron_api_utility_process.cc
  spec/api-utility-process-spec.ts
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44699 build: re-enable `container_overflow` ASAN check
  .github/workflows/pipeline-segment-electron-test.yml
  patches/node/.patches
  patches/node/src_provide_workaround_for_container-overflow.patch
Labels: semver/none, no-backport

#44698 fix: utility process exit code for graceful termination
  patches/chromium/feat_enable_passing_exit_code_on_service_process_crash.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  shell/browser/api/electron_api_utility_process.cc
  spec/api-utility-process-spec.ts
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44679 chore: fix multi-version parsing in issue assignment
  .github/workflows/issue-opened.yml
Labels: semver/none, no-backport

#44651 docs: Make ipcRenderer and ipcMain listener API docs consistent
  docs/api/ipc-main.md
  docs/api/ipc-renderer.md
  spec/api-ipc-main-spec.ts
  spec/api-ipc-renderer-spec.ts
Labels: documentation :notebook:, semver/patch, target/33-x-y, target/34-x-y

#44717 chore: Revert "fix: utility process exit code for graceful termination"
  patches/chromium/feat_enable_passing_exit_code_on_service_process_crash.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  shell/browser/api/electron_api_utility_process.cc
  spec/api-utility-process-spec.ts
Labels: fast-track 🚅, semver/none, no-backport

#44706 chore: fix unsupported major comment in issue automation
  .github/workflows/issue-opened.yml
Labels: new-pr 🌱, semver/none, no-backport

#44700 fix: improve single-pixel resize handling on Windows
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44657 build: rework header generation in Node.js
  BUILD.gn
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/node/build_add_gn_build_files.patch
  patches/node/build_enable_perfetto.patch
  patches/node/fix_handle_boringssl_and_openssl_incompatibilities.patch
  script/node/generate_node_headers.py
Labels: semver/patch, no-backport

#44574 fix: destroy url loader wrapper when JS env exits
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44705 fix: cyclical #include dependency between autofill_popup.h and autofill_popup_view.h
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/autofill_popup.h
  shell/browser/ui/views/autofill_popup_view.cc
  shell/browser/ui/views/autofill_popup_view.h
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44708 fix: bugprone-narrowing-conversions warnings in NativeImage
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44745 chore: remove use of banned absl::optional (#44513)
  shell/browser/electron_browser_client.cc
Labels: backport, semver/patch, no-backport, 32-x-y

#44721 fix: tooltips in WCO caption buttons
  shell/browser/ui/views/win_caption_button_container.cc
  shell/browser/ui/views/win_caption_button_container.h
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44753 chore: cherry-pick 2ca6d60a from chromium
  patches/chromium/.patches
  patches/chromium/wayland_support_outgoing_dnd_sessions_with_no_offered_mime_types.patch
Labels: semver/patch, backport-check-skip, target/32-x-y

#44749 fix: utility process exit code for graceful termination
  patches/chromium/feat_enable_passing_exit_code_on_service_process_crash.patch
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_utility_process.h
  spec/api-utility-process-spec.ts
Labels: backport, semver/patch, 32-x-y

#44741 test: run script to help target discovery and reduce flakes
  spec/api-debugger-spec.ts
Labels: semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44754 build: allow unbundling of Node.js dependencies
  patches/node/.patches
  patches/node/build_allow_unbundling_of_node_js_dependencies.patch
Labels: semver/patch, no-backport

#44728 chore: fix textured window conditional on macOS
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44734 refactor: use gdk_display_beep() on Linux
  BUILD.gn
  shell/browser/ui/electron_gdk.sigs
  shell/browser/ui/electron_gtk.sigs
  shell/common/platform_util_linux.cc
Labels: semver/patch, no-backport

#44716 docs: removes redundant phrasing in the code signing documentation
  docs/tutorial/code-signing.md
Labels: documentation :notebook:, semver/patch, no-backport

#44296 fix: windows save dialog extension bug
  shell/browser/ui/file_dialog_win.cc
Labels: semver/patch, target/33-x-y, target/34-x-y

#44742 fix: `performance-no-automatic-move` clang-tidy warnings
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/common/logging.cc
Labels: performance :checkered_flag:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44766 docs: sync 34.0.0 release date to Chromium 132 release date
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/none, target/33-x-y, target/34-x-y

#44786 build: remove duplicate line in gn file
  chromium_src/BUILD.gn
Labels: semver/none, target/33-x-y, target/34-x-y

#44776 fix: big endian bug in V8 serialization
  shell/common/v8_util.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44761 fix: ensure `context-menu` emitted for draggable regions
  shell/browser/native_window_mac.h
  shell/browser/ui/cocoa/delayed_native_view_host.h
  shell/browser/ui/cocoa/delayed_native_view_host.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  spec/api-web-contents-spec.ts
  spec/fixtures/pages/draggable-page.html
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44784 fix: crash calling `shell.readShortcutLink`
  patches/chromium/.patches
  patches/chromium/support_bstr_pkey_appusermodel_id_in_windows_shortcuts.patch
Labels: semver/patch, target/33-x-y, target/34-x-y

#44598 feat: add query-session-end and improve session-end events on Windows
  docs/api/base-window.md
  docs/api/browser-window.md
  docs/api/structures/window-session-end-event.md
  filenames.auto.gni
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/browser/native_window_views_win.cc
  shell/common/gin_helper/event_emitter.h
Labels: semver/minor, api-review/approved ✅, no-backport

#44791 docs: update new GitHub issue link
  CONTRIBUTING.md
Labels: new-pr 🌱, semver/none, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44802 test: fixup visibility tests
  spec/api-web-contents-view-spec.ts
  spec/api-web-request-spec.ts
  spec/visibility-state-spec.ts
Labels: backport-check-skip, semver/none

#44815 fix: remove unused local variables
  shell/browser/api/electron_api_app.cc
  shell/browser/relauncher.cc
  shell/browser/ui/views/global_menu_bar_registrar_x11.cc
Labels: semver/patch, target/31-x-y, target/32-x-y, target/33-x-y, target/34-x-y

#44816 refactor: remove unnecessary constructor code
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44787 docs: fix wording in auto-updater.md
  docs/api/auto-updater.md
Labels: documentation :notebook:, semver/patch, no-backport

#44807 docs: correct stable release dates for v34.0.0
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/33-x-y, target/34-x-y

#44814 fix: clang-tidy `performance-inefficient-vector-operation` warnings (33-x-y)
  shell/browser/api/electron_api_crash_reporter.cc
  shell/common/api/electron_api_clipboard.cc
Labels: performance :checkered_flag:, backport, semver/patch, target/32-x-y, 33-x-y

#44808 fix: modernize-use-nodiscard clang-tidy warnings
  shell/browser/electron_permission_manager.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/common/gin_converters/osr_converter.cc
  shell/common/gin_helper/callback.cc
  shell/common/heap_snapshot.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44813 fix: modernize-avoid-c-arrays
  shell/app/electron_main_delegate.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/file_system_access/file_system_access_permission_context.cc
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/webui/accessibility_ui.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/zoom_level_delegate.cc
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44806 fix: modernize-use-using clang-tidy warnings
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/linux/unity_service.cc
  shell/browser/ui/views/global_menu_bar_x11.cc
  shell/common/asar/asar_util.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44838 refactor: fix modernize-return-braced-init-list warnings
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_net_log.cc
  shell/browser/api/electron_api_safe_storage.cc
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/browser_linux.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_permission_manager.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/javascript_environment.cc
  shell/browser/native_window.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/printing/printing_utils.cc
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/opaque_frame_view.cc
  shell/browser/web_contents_permission_helper.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_api_native_image.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/common/gin_helper/wrappable.cc
  shell/common/node_util.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y

#44848 fix: clang-tidy `performance-inefficient-vector-operation` warnings (32-x-y backport)
  shell/browser/api/electron_api_crash_reporter.cc
  shell/common/api/electron_api_clipboard.cc
Labels: backport, semver/patch, no-backport, 32-x-y

#44847 fix: modernize-use-using clang-tidy warnings (32-x-y backport)
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/linux/unity_service.cc
  shell/browser/ui/views/global_menu_bar_x11.cc
  shell/common/asar/asar_util.cc
Labels: backport, semver/patch, no-backport, 32-x-y

#44839 refactor: use base::Extend in AddAdditionalSchemes()
  shell/app/electron_content_client.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44843 fix: misc-use-internal-linkage warnings
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/printing/printing_utils.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/platform_util.cc
  shell/common/skia_util.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44846 fix: modernize-use-nodiscard clang-tidy warnings (32-x-y backport)
  shell/browser/electron_permission_manager.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/common/gin_helper/callback.cc
  shell/common/heap_snapshot.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/renderer_client_base.cc
Labels: backport, semver/patch, no-backport, 32-x-y

#44870 refactor: return-braced-init-list pt 2 of 2
  shell/browser/api/electron_api_data_pipe_holder.cc
  shell/browser/api/electron_api_download_item.cc
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/browser_win.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_web_ui_controller_factory.cc
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/file_select_helper.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/ui/devtools_manager_delegate.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_v8_util.cc
  shell/common/extensions/electron_extensions_api_provider.cc
  shell/common/gin_helper/event_emitter_caller.h
  shell/common/gin_helper/trackable_object.h
  shell/common/mac/codesign_util.cc
  shell/common/node_bindings.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_ipc_renderer.cc
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/renderer_client_base.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#44875 docs: clarify that sessions use cache by default (33-x-y backport)
  docs/api/session.md
Labels: backport, semver/patch, 33-x-y

#44862 build: remove context-aware patch
  patches/node/.patches
  patches/node/chore_add_context_to_context_aware_module_prevention.patch
Labels: semver/none, no-backport

#44859 chore: cherry-pick 1 change from 1-M131
  patches/dawn/.patches
  patches/dawn/ir_fix_robustness_transform_on_textureload_of_sampled_and_depth.patch
  patches/dawn/tint_validate_that_align_is_large_enough.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#44858 chore: cherry-pick 1 change from 1-M131
  patches/dawn/.patches
  patches/dawn/ir_fix_robustness_transform_on_textureload_of_sampled_and_depth.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#44860 refactor: reduce scope of relauncher's internal constants
  shell/browser/relauncher.cc
  shell/browser/relauncher.h
  shell/browser/relauncher_win.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y
