Repository electron/electron, pull requests merged in 2025-08, with the labels that each got.

#47717 refactor: replace webFrame.routingId with sync IPC
  docs/api/web-frame.md
  filenames.auto.gni
  lib/browser/rpc-server.ts
  lib/common/ipc-messages.ts
  lib/renderer/api/web-frame.ts
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/none, target/38-x-y

#47439 feat: Use DIR_ASSETS path to locate resource bundles
  docs/api/app.md
  shell/app/electron_main_delegate.cc
  shell/browser/api/electron_api_app.cc
  shell/common/asar/archive_win.cc
  shell/common/node_bindings.cc
  spec/api-app-spec.ts
Labels: semver/minor, api-review/approved ✅, target/37-x-y, target/38-x-y

#47868 fix: offscreen mode under `window.open` creation
  patches/chromium/can_create_window.patch
  patches/chromium/chore_partial_revert_of.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_fullscreen.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/guest-window-manager-spec.ts
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#47957 fix: abnormal behavior of windows background material
  patches/chromium/.patches
  patches/chromium/fix_activate_background_material_on_windows.patch
  patches/chromium/fix_resolve_dynamic_background_material_update_issue_on_windows_11.patch
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/api/electron_api_browser_window.cc
  shell/browser/api/electron_api_browser_window.h
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Labels: backport, semver/patch, 36-x-y

#47961 refactor: avoid deprecated `v8::Context::GetIsolate()` pt 4
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, target/38-x-y

#47969 test: add TS smoke test for electron/utility
  spec/ts-smoke/electron/utility.ts
  spec/ts-smoke/tsconfig.json
Labels: new-pr 🌱, semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#47982 ci: fixup mac runner hang
  .github/actions/free-space-macos/action.yml
  .github/workflows/pipeline-segment-electron-test.yml
  spec/chromium-spec.ts
Labels: semver/none, target/35-x-y, target/36-x-y

#47838 feat: allow macOS tray to maintain position
  docs/api/tray.md
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/tray_icon.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
  shell/browser/ui/tray_icon_linux.cc
  shell/browser/ui/tray_icon_win.cc
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/ui/win/notify_icon_host.h
  shell/common/gin_converters/guid_converter.h
  spec/api-tray-spec.ts
Labels: semver/minor, api-review/approved ✅, target/36-x-y, target/37-x-y, target/38-x-y

#47315 feat: `paint` event move texture data to `handle`, add `colorSpace`
  docs/api/structures/offscreen-shared-texture.md
  docs/api/structures/shared-texture-handle.md
  docs/breaking-changes.md
  shell/browser/osr/osr_paint_event.h
  shell/browser/osr/osr_video_consumer.cc
  shell/common/gin_converters/osr_converter.cc
  shell/common/gin_converters/osr_converter.h
Labels: semver/major, api-review/approved ✅, no-backport

#47992 ci: fixup mac runner hang
  .github/actions/free-space-macos/action.yml
  .github/workflows/pipeline-segment-electron-test.yml
  spec/chromium-spec.ts
Labels: backport, semver/none, 35-x-y

#47798 build: drop @types/webpack-env in favor of webpack/module types
  build/webpack/webpack.config.base.js
  lib/browser/init.ts
  lib/node/asar-fs-wrapper.ts
  lib/renderer/init.ts
  lib/utility/init.ts
  lib/worker/init.ts
  package.json
  tsconfig.json
  typings/internal-ambient.d.ts
  yarn.lock
Labels: semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#47998 fix: importing from electron/utility in ESM
  build/webpack/webpack.config.base.js
  patches/node/fix_allow_passing_fileexists_fn_to_legacymainresolve.patch
  patches/node/fix_expose_the_built-in_electron_module_via_the_esm_loader.patch
  patches/node/fix_lazyload_fs_in_esm_loaders_to_apply_asar_patches.patch
  spec/api-utility-process-spec.ts
  spec/esm-spec.ts
  spec/fixtures/api/utility-process/electron-modules/import-common.mjs
  spec/fixtures/api/utility-process/electron-modules/import-lol.mjs
  spec/fixtures/api/utility-process/electron-modules/import-main.mjs
  spec/fixtures/api/utility-process/electron-modules/import-renderer.mjs
  spec/fixtures/api/utility-process/electron-modules/import-utility.mjs
  spec/fixtures/api/utility-process/electron-modules/require-common.js
  spec/fixtures/api/utility-process/electron-modules/require-lol.js
  spec/fixtures/api/utility-process/electron-modules/require-main.js
  spec/fixtures/api/utility-process/electron-modules/require-renderer.js
  spec/fixtures/api/utility-process/electron-modules/require-utility.js
  spec/fixtures/esm/electron-modules/import-common.mjs
  spec/fixtures/esm/electron-modules/import-lol.mjs
  spec/fixtures/esm/electron-modules/import-main.mjs
  spec/fixtures/esm/electron-modules/import-renderer.mjs
  spec/fixtures/esm/electron-modules/import-utility.mjs
  spec/modules-spec.ts
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#48002 docs: deprecate `ELECTRON_OZONE_PLATFORM_HINT` env var
  docs/api/environment-variables.md
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/none, target/38-x-y

#48026 fix: offscreen mode under `window.open` creation
  patches/chromium/can_create_window.patch
  patches/chromium/chore_partial_revert_of.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_fullscreen.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/guest-window-manager-spec.ts
Labels: backport, semver/patch, 38-x-y

#48029 ci: update llvmobjdump package as part of fix sync
  .github/actions/fix-sync/action.yml
  patches/chromium/.patches
  patches/chromium/revert_use_more_binaries_from_clang_toolchain_in_mac_build.patch
Labels: backport, semver/patch, 38-x-y

#47911 test: support for multimonitor tests
  docs/development/multi-monitor-testing.md
  docs/development/testing.md
  spec/fixtures/native-addon/virtual-display/binding.gyp
  spec/fixtures/native-addon/virtual-display/include/VirtualDisplayBridge.h
  spec/fixtures/native-addon/virtual-display/lib/virtual-display.js
  spec/fixtures/native-addon/virtual-display/package.json
  spec/fixtures/native-addon/virtual-display/src/Dummy.swift
  spec/fixtures/native-addon/virtual-display/src/VirtualDisplay.swift
  spec/fixtures/native-addon/virtual-display/src/VirtualDisplayBridge.m
  spec/fixtures/native-addon/virtual-display/src/addon.mm
  spec/package.json
  spec/yarn.lock
Labels: backport-check-skip, semver/none, no-backport, GSoC 2025

#48046 build: drop @types/webpack-env in favor of webpack/module types
  build/webpack/webpack.config.base.js
  lib/browser/init.ts
  lib/node/asar-fs-wrapper.ts
  lib/renderer/init.ts
  lib/utility/init.ts
  lib/worker/init.ts
  package.json
  tsconfig.json
  typings/internal-ambient.d.ts
  yarn.lock
Labels: backport, semver/none, 37-x-y

#48013 ci: manually fetch author_association in workflow automations
  .github/workflows/issue-commented.yml
  .github/workflows/non-maintainer-dependency-change.yml
Labels: semver/none, no-backport

#48041 fix: `app.accessibilitySupportEnabled`
  shell/browser/api/electron_api_app.cc
Labels: semver/patch, target/37-x-y, target/38-x-y

#47938 build: use quick tunnels for ssh debugging
  .github/actions/ssh-debug/action.yml
  .github/actions/ssh-debug/setup-ssh.sh
  .github/actions/ssh-debug/ssh-session.sh
  .github/actions/ssh-debug/sshd_config.template
  .github/workflows/build.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
Labels: semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#48038 build: disallow non-maintainer changes to GitHub Actions workflows
  .github/workflows/non-maintainer-dependency-change.yml
Labels: semver/none, no-backport

#48082 build: revert bump @octokit/rest from 20.1.2 to 22.0.0
  package.json
  yarn.lock
Labels: semver/none, no-backport

#48079 fix: `shell.openPath` should be non-blocking
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#48106 build: correct CHECK syntax
  shell/app/electron_main_delegate.cc
Labels: fast-track 🚅, backport-check-skip, semver/none, 35-x-y

#48085 fix: system accent color parsing hex order
  shell/common/color_util.cc
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#48065 refactor: use `XmlWriter` for Windows toasts
  BUILD.gn
  shell/browser/notifications/win/windows_toast_notification.cc
  shell/browser/notifications/win/windows_toast_notification.h
Labels: semver/patch, target/37-x-y, target/38-x-y

#47781 feat: clear and restore window state
  docs/api/base-window.md
  docs/api/structures/base-window-options.md
  lib/browser/api/browser-window.ts
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  spec/api-browser-window-spec.ts
Labels: semver/minor, backport-check-skip, no-backport, GSoC 2025

#48128 build: fixup docs only condition
  .github/workflows/build.yml
Labels: fast-track 🚅, semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#48077 feat: allow macOS tray to maintain position
  docs/api/tray.md
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/tray_icon.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
  shell/browser/ui/tray_icon_linux.cc
  shell/browser/ui/tray_icon_win.cc
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/ui/win/notify_icon_host.h
  shell/common/gin_converters/guid_converter.h
  spec/api-tray-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 38-x-y

#48078 feat: allow macOS tray to maintain position
  docs/api/tray.md
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/tray_icon.h
  shell/browser/ui/tray_icon_cocoa.h
  shell/browser/ui/tray_icon_cocoa.mm
  shell/browser/ui/tray_icon_linux.cc
  shell/browser/ui/tray_icon_win.cc
  shell/browser/ui/win/notify_icon_host.cc
  shell/browser/ui/win/notify_icon_host.h
  shell/common/gin_converters/guid_converter.h
  spec/api-tray-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 36-x-y

#48117 docs: update 38.0 breaking changes
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, no-backport

#48111 fix: `net.isOnline` always true in utility processes
  shell/services/node/node_service.cc
  shell/services/node/node_service.h
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#48059 fix: webContent.fromId should be number instead of string
  lib/browser/api/web-contents.ts
Labels: semver/none, no-backport

#47534 build: use siso instead of reclient
  .github/actions/build-electron/action.yml
  .github/actions/cipd-install/action.yml
  .github/actions/fix-sync/action.yml
  .github/actions/install-build-tools/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  build/siso/backend.star
  build/siso/main.star
  patches/chromium/.patches
  patches/chromium/revert_update_siso-chromium_image.patch
  script/actions/move-artifacts.sh
  script/node/generate_original_fs.py
Labels: semver/none, target/38-x-y

#48164 build: remove no longer needed arg for siso
  .github/actions/build-electron/action.yml
  build/args/all.gn
Labels: semver/none, no-backport

#48162 chore: remove upstream OSR temp fix
  shell/browser/osr/osr_render_widget_host_view.cc
Labels: semver/patch, no-backport

#48167 docs: add release timeline for Electron 39
  docs/tutorial/electron-timelines.md
Labels: semver/none, target/38-x-y

#48048 test: multi monitor tests for save/restore window state
  docs/development/multi-monitor-testing.md
  shell/browser/native_window.cc
  spec/api-browser-window-spec.ts
  spec/fixtures/native-addon/virtual-display/include/VirtualDisplayBridge.h
  spec/fixtures/native-addon/virtual-display/src/Dummy.swift
  spec/fixtures/native-addon/virtual-display/src/VirtualDisplay.swift
  spec/fixtures/native-addon/virtual-display/src/VirtualDisplayBridge.m
  spec/fixtures/native-addon/virtual-display/src/addon.mm
Labels: semver/patch, backport-check-skip, no-backport, GSoC 2025

#47872 ci: use free GH arm runners
  .github/workflows/build.yml
  .github/workflows/pipeline-segment-electron-test.yml
Labels: semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#48177 docs: fix some module headings
  docs/api/menu-item.md
  docs/api/service-worker-main.md
Labels: documentation :notebook:, semver/patch, target/37-x-y, target/38-x-y

#47932 build: refactor Linux binary stripping to align with upstream
  .github/actions/build-electron/action.yml
  .github/workflows/linux-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
  BUILD.gn
  build/args/all.gn
  build/linux/strip_binary.gni
  build/linux/strip_binary.py
  build/zip.py
  docs/development/build-instructions-gn.md
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/util.py
  script/strip-binaries.py
Labels: semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#48196 build: bump NMV to 140
  build/args/all.gn
Labels: semver/none, no-backport

#48143 feat: add `fileBacked` and `purgeable` fields to `process.getSystemMemoryInfo()` for macOS
  docs/api/process.md
  shell/common/api/electron_bindings.cc
Labels: backport, semver/minor, backport/approved ✅, 37-x-y

#48146 feat: add `fileBacked` and `purgeable` fields to `process.getSystemMemoryInfo()` for macOS
  docs/api/process.md
  shell/common/api/electron_bindings.cc
Labels: backport, semver/minor, backport/approved ✅, 38-x-y

#48208 build: refactor Linux binary stripping to align with upstream
  .github/actions/build-electron/action.yml
  .github/workflows/linux-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
  BUILD.gn
  build/args/all.gn
  build/linux/strip_binary.gni
  build/linux/strip_binary.py
  build/zip.py
  docs/development/build-instructions-gn.md
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/util.py
  script/strip-binaries.py
Labels: backport, semver/none, 36-x-y

#48199 fix: ensure dragging works again after emitting contextmenu event
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#48207 build: refactor Linux binary stripping to align with upstream
  .github/actions/build-electron/action.yml
  .github/workflows/linux-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
  BUILD.gn
  build/args/all.gn
  build/linux/strip_binary.gni
  build/linux/strip_binary.py
  build/zip.py
  docs/development/build-instructions-gn.md
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/util.py
  script/strip-binaries.py
Labels: backport, semver/none, 37-x-y

#48209 build: refactor Linux binary stripping to align with upstream
  .github/actions/build-electron/action.yml
  .github/workflows/linux-publish.yml
  .github/workflows/pipeline-segment-electron-build.yml
  BUILD.gn
  build/args/all.gn
  build/linux/strip_binary.gni
  build/linux/strip_binary.py
  build/zip.py
  docs/development/build-instructions-gn.md
  script/add-debug-link.py
  script/copy-debug-symbols.py
  script/lib/util.py
  script/strip-binaries.py
Labels: backport, semver/none, 35-x-y
