Repository electron/electron, pull requests merged in 2025-07, with the labels that each got.

#47506 refactor: use non-deprecated macOS API in `RemoveAsDefaultProtocolClient`
  shell/browser/browser_mac.mm
Labels: semver/patch, no-backport

#47634 build: set the minimum macOS SDK to 10.15
  .github/workflows/build.yml
  .github/workflows/macos-publish.yml
  patches/chromium/.patches
  patches/chromium/build_set_mac_sdk_minimum_to_10.patch
Labels: fast-track 🚅, semver/none, no-backport

#47624 fix: silent printing of PDFs with `webContents.print`
  patches/chromium/printing.patch
Labels: backport, semver/patch, target/35-x-y, 36-x-y

#47641 fix: crash on source capture with empty thumbnail size
  shell/browser/api/electron_api_desktop_capturer.cc
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#47643 ci: fix audit workflow alerting on stale results
  .github/workflows/audit-branch-ci.yml
Labels: semver/none, no-backport

#47644 refactor: avoid a few unnecessary strings
  shell/browser/api/electron_api_web_contents.cc
  shell/common/platform_util_linux.cc
Labels: semver/patch, new-pr 🌱, target/36-x-y, target/37-x-y, target/38-x-y

#47629 fix: accent color should reflect system settings without restart
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#47664 fix: fullscreen for windows without rounded corners
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.h
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#47680 docs: update build prerequisites
  docs/development/build-instructions-linux.md
  docs/development/build-instructions-macos.md
  docs/development/build-instructions-windows.md
Labels: documentation :notebook:, semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#47685 refactor: use `dbus_thread_linux::GetSharedSessionBus()`
  shell/common/platform_util_linux.cc
Labels: semver/patch, target/38-x-y

#47695 ci: set git `core.longpaths` to true
  .github/actions/install-build-tools/action.yml
  .github/workflows/pipeline-segment-electron-test.yml
Labels: semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47692 build: deep update brace-expansion to resolve an audit alert
  yarn.lock
Labels: semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47727 build: cleanup symlinks in cache
  .github/actions/restore-cache-azcopy/action.yml
Labels: fast-track 🚅, semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47726 ci: add `kTCCServiceAppleEvents` perm override to fix AppleScript errors
  .github/workflows/pipeline-segment-electron-test.yml
Labels: semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#47627 build: add platform-specific conditions to the source_set in chromium_src
  chromium_src/BUILD.gn
Labels: semver/none, no-backport

#47694 ci: roll `BUILD_TOOLS_SHA` for macOS 15.5 SDK
  .github/actions/install-build-tools/action.yml
Labels: semver/none, target/38-x-y

#47268 docs: add `Menu` module tutorials
  .markdownlint-cli2.jsonc
  docs/api/accelerator.md
  docs/api/dock.md
  docs/api/global-shortcut.md
  docs/api/menu-item.md
  docs/api/menu.md
  docs/api/structures/keyboard-input-event.md
  docs/api/tray.md
  docs/api/web-frame.md
  docs/fiddles/features/keyboard-shortcuts/global/index.html
  docs/fiddles/features/keyboard-shortcuts/global/main.js
  docs/fiddles/features/keyboard-shortcuts/local/index.html
  docs/fiddles/features/keyboard-shortcuts/local/main.js
  docs/fiddles/features/macos-dock-menu/index.html
  docs/fiddles/features/macos-dock-menu/main.js
  docs/fiddles/menus/context-menu/dom/index.html
  docs/fiddles/menus/context-menu/dom/main.js
  docs/fiddles/menus/context-menu/dom/preload.js
  docs/fiddles/menus/context-menu/web-contents/index.html
  docs/fiddles/menus/context-menu/web-contents/main.js
  docs/fiddles/menus/customize-menus/index.html
  docs/fiddles/menus/customize-menus/main.js
  docs/fiddles/menus/customize-menus/preload.js
  docs/fiddles/menus/customize-menus/renderer.js
  docs/fiddles/menus/dock-menu/index.html
  docs/fiddles/menus/dock-menu/main.js
  docs/fiddles/menus/dock-menu/renderer.js
  docs/fiddles/menus/tray-menu/index.html
  docs/fiddles/menus/tray-menu/main.js
  docs/fiddles/native-ui/tray/index.html
  docs/fiddles/native-ui/tray/main.js
  docs/tutorial/application-menu.md
  docs/tutorial/context-menu.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/macos-dock.md
  docs/tutorial/menus.md
  docs/tutorial/tray.md
  docs/tutorial/window-customization.md
  filenames.auto.gni
Labels: documentation :notebook:, semver/patch, target/37-x-y, target/38-x-y

#47765 fix: add macos memory query fallback patch to avoid crash
  patches/chromium/.patches
  patches/chromium/fix_add_macos_memory_query_fallback_to_avoid_crash.patch
Labels: semver/patch, fast-track 🚅, target/37-x-y, target/38-x-y

#47752 test: deflake clipboard read/write specs
  spec/chromium-spec.ts
Labels: semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#47750 test: fix extensions console flake
  spec/extensions-spec.ts
Labels: semver/none, target/36-x-y, target/37-x-y, target/38-x-y

#47792 fix: corner smoothing feature gate crash (37-x-y)
  docs/api/corner-smoothing-css.md
  docs/api/structures/web-preferences.md
  patches/chromium/feat_corner_smoothing_css_rule_and_blink_painting.patch
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/options_switches.h
  shell/renderer/electron_smooth_round_rect.cc
  spec/api-corner-smoothing-spec.ts
Labels: backport, semver/patch, 37-x-y

#47746 test: cleanup RenderFrame lifespan tests
  spec/api-web-frame-main-spec.ts
  spec/chromium-spec.ts
Labels: semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47767 build(dev-deps): drop unused @types/webpack dep
  package.json
  yarn.lock
Labels: semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47665 chore: clean up `NativeWindowMac::UpdateVibrancyRadii`
  build/rules.gni
  shell/browser/native_window_mac.mm
Labels: semver/patch, no-backport

#47810 build: update codespace `on-create-command`
  .devcontainer/on-create-command.sh
Labels: semver/none, target/38-x-y

#47799 refactor: reduce scope of temporaries when getting dictionary values
  shell/browser/native_window.cc
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
Labels: backport, semver/patch, target/36-x-y, 37-x-y

#47768 build: fix ffmpeg generation on Windows non-x64
  .github/actions/build-electron/action.yml
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47625 fix: `webContents.downloadURL()` did not support referer header
  shell/browser/api/electron_api_web_contents.cc
  spec/api-session-spec.ts
Labels: semver/patch, target/36-x-y, target/37-x-y, target/38-x-y

#47877 ci: fixup mac runners
  .github/actions/free-space-macos/action.yml
  .github/workflows/pipeline-segment-electron-test.yml
  spec/chromium-spec.ts
Labels: semver/none, target/35-x-y, target/36-x-y, target/37-x-y, target/38-x-y

#47901 refactor: avoid deprecated v8::Context::GetIsolate() calls pt 3 context get isolate pt 3
  docs/development/creating-api.md
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
  shell/common/node_util.cc
  shell/common/node_util.h
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_renderer_client.h
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.h
  shell/renderer/preload_realm_context.cc
  shell/renderer/preload_realm_context.h
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
  shell/renderer/service_worker_data.cc
  shell/renderer/service_worker_data.h
Labels: semver/patch, target/38-x-y

#47869 fix: dark mode on Linux default themeing
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
Labels: semver/patch, target/37-x-y, target/38-x-y
