Repository electron/electron, pull requests merged in 2025-03, with the labels that each got.

#45852 test: service worker contextBridge leak
  spec/api-service-worker-main-spec.ts
  spec/fixtures/api/preload-realm/preload-tests.js
Labels: semver/none, no-backport

#45706 chore: cherry-pick 3 changes from 0-M133
  .gitattributes
  patches/chromium/.patches
  patches/chromium/reland_lzma_sdk_update_to_24_09.patch
  patches/v8/.patches
  patches/v8/cherry-pick-1c7ff4d5477f.patch
  patches/v8/cherry-pick-8834c16acfcc.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45719 chore: [32-x-y] cherry-pick 1 changes from 1-M133
  patches/v8/.patches
  patches/v8/merged_fix_out_of_bound_string_access.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45872 build: define `NOMINMAX` in `common.gypi`
  patches/node/.patches
  patches/node/build_define_nominmax_in_common_gypi.patch
Labels: backport, semver/patch, backport-check-skip, 33-x-y

#45871 build: define `NOMINMAX` in `common.gypi`
  patches/node/.patches
  patches/node/build_define_nominmax_in_common_gypi.patch
Labels: semver/patch, backport-check-skip, 32-x-y

#45870 build: define `NOMINMAX` in `common.gypi`
  patches/node/.patches
  patches/node/build_define_nominmax_in_common_gypi.patch
Labels: backport, semver/patch, backport-check-skip, 34-x-y

#45389 fix: correct electron gin embedder indices
  patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45878 fix: rework and improve `legacyMainResolve` patch
  patches/node/.patches
  patches/node/fix_allow_passing_fileexists_fn_to_legacymainresolve.patch
  patches/node/fix_revert_src_lb_reducing_c_calls_of_esm_legacy_main_resolve.patch
  patches/node/src_stop_using_deprecated_fields_of_fastapicallbackoptions.patch
  script/node-disabled-tests.json
Labels: backport, semver/patch, 35-x-y

#45877 ci: preserve `blocked/*` labels on collaborator comments
  .github/workflows/issue-commented.yml
Labels: semver/none, no-backport

#45667 feat: WebContents.focusedFrame
  docs/api/web-contents.md
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/api-web-contents-spec.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#45868 fix: `setContentProtection(true)` after hide on Windows
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/34-x-y, target/35-x-y

#45716 chore: cherry-pick 3 changes from 1-M133
  patches/v8/.patches
  patches/v8/cherry-pick-1c7ff4d5477f.patch
  patches/v8/cherry-pick-9209292e7898.patch
  patches/v8/cherry-pick-97e828af5cbc.patch
  patches/v8/merged_fix_out_of_bound_string_access.patch
  patches/v8/merged_wasm_replace_dead_code_set_with_is_dying_bit.patch
  patches/v8/wasm_fix_freeing_of_identical_shared_wrappers.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45639 chore: emphasize documentation style guide
  .github/PULL_REQUEST_TEMPLATE.md
  docs/development/api-history-migration-guide.md
  docs/development/style-guide.md
Labels: documentation :notebook:, semver/none, target/35-x-y, target/36-x-y

#45895 fix: javascript heap OOM is not raised
  patches/node/.patches
  patches/node/feat_add_oom_error_callback_in_node_isolatesettings.patch
  shell/common/node_bindings.cc
Labels: semver/patch, target/35-x-y, target/36-x-y

#45853 build: match upstream with unsafe buffer paths
  build/args/all.gn
  electron_unsafe_buffers_paths.txt
  patches/chromium/.patches
  patches/chromium/chore_remove_conflicting_allow_unsafe_libc_calls.patch
  patches/chromium/feat_add_data_parameter_to_processsingleton.patch
  patches/chromium/fix_enable_wrap_iter_in_string_view_and_array.patch
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_system_preferences_win.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/gin_converters/std_converter.h
  shell/common/keyboard_util.cc
Labels: semver/major, api-review/approved ✅, no-backport, api-review/skip-delay ⏰

#45905 fix: resolve font list in default prefernce values
  shell/browser/font_defaults.cc
  shell/browser/font_defaults.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#45933 chore: bump Chromium 136.0.7058.1
  DEPS
Labels: new-pr 🌱, no-backport

#45927 refactor: eliminate duplicate code in spec/api-process-spec.ts
  spec/api-process-spec.ts
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#45926 fix: race condition in utilityProcess tests
  spec/api-utility-process-spec.ts
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#45941 chore: cherry-pick 521faebc8a7c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-521faebc8a7c.patch
Labels: semver/patch, backport-check-skip, main

#45936 chore: cherry-pick 9dacf5694dfd from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9dacf5694dfd.patch
Labels: semver/patch, backport-check-skip, main

#45937 chore: cherry-pick 9dacf5694dfd from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9dacf5694dfd.patch
Labels: semver/patch, backport-check-skip, 36-x-y

#45942 chore: cherry-pick 521faebc8a7c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-521faebc8a7c.patch
Labels: semver/patch, backport-check-skip, 36-x-y

#45938 chore: cherry-pick 9dacf5694dfd from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9dacf5694dfd.patch
Labels: semver/patch, backport-check-skip, 35-x-y

#45943 chore: cherry-pick 521faebc8a7c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-521faebc8a7c.patch
Labels: semver/patch, backport-check-skip, 35-x-y

#45939 chore: cherry-pick 9dacf5694dfd from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9dacf5694dfd.patch
Labels: semver/patch, backport-check-skip, 34-x-y

#45944 chore: cherry-pick 521faebc8a7c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-521faebc8a7c.patch
Labels: semver/patch, backport-check-skip, 34-x-y

#45940 chore: cherry-pick 9dacf5694dfd from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-9dacf5694dfd.patch
Labels: semver/patch, backport-check-skip, 33-x-y

#45945 chore: cherry-pick 521faebc8a7c from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-521faebc8a7c.patch
Labels: semver/patch, backport-check-skip, 33-x-y

#45929 fix: remove redundant `MediaCaptureDevicesDispatcher::GetInstance()` call
  shell/browser/electron_browser_main_parts.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#45963 build: remove patches merged upstream
  patches/chromium/.patches
  patches/chromium/cherry-pick-521faebc8a7c.patch
  patches/chromium/cherry-pick-9dacf5694dfd.patch
Labels: semver/none, no-backport

#45882 docs: Add 'Native Code and Electron'
  docs/tutorial/native-code-and-electron.md
Labels: documentation :notebook:, semver/patch, target/35-x-y, target/36-x-y

#45966 fix: cherry-pick 3a72ebf7ec6f0 from chromium
  patches/chromium/.patches
  patches/chromium/revert_blink_fix_over_invalidation_with_view_transitions.patch
Labels: semver/patch, backport-check-skip, no-backport, 34-x-y

#45964 test: fix timing issue in `utilityProcess` test fixtures
  spec/fixtures/api/utility-process/dns-result-order.js
  spec/fixtures/api/utility-process/esm.mjs
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#45922 refactor: remove usage of V8's `{Attach|Detach}CppHeap()`
  patches/node/.patches
  patches/node/refactor_attach_cppgc_heap_on_v8_isolate_creation.patch
  patches/v8/.patches
  patches/v8/revert_api_delete_deprecated_attachcppheap_and_detachcppheap.patch
Labels: semver/patch, target/36-x-y

#45974 build: roll sysroots to pick up glibc fix
  script/sysroots.json
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#45986 ci: don't fail branch created workflow if previous board not found
  .github/workflows/branch-created.yml
Labels: semver/none, no-backport

#45973 refactor: use private inheritance from `mojo::MessageReceiver`
  shell/browser/api/electron_api_utility_process.h
  shell/browser/api/message_port.h
  shell/services/node/parent_port.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46002 fix: `system-context-menu` should only fire in draggable regions (36-x-y)
  patches/chromium/.patches
  patches/chromium/chore_modify_chromium_handling_of_mouse_events.patch
  patches/chromium/fix_activate_background_material_on_windows.patch
  patches/chromium/fix_remove_caption-removing_style_call.patch
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: backport, semver/patch, 36-x-y

#46003 fix: correct electron gin embedder indices (33-x-y)
  patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch
Labels: backport, semver/patch, 33-x-y

#46007 chore: cherry-pick 2 changes from 3-M133
  patches/chromium/.patches
  patches/chromium/cherry-pick-0adceb6159fb.patch
  patches/v8/.patches
  patches/v8/cherry-pick-91343bb45c78.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#46011 chore: cherry-pick 1 changes from 1-M134
  patches/v8/.patches
  patches/v8/cherry-pick-2b4812d502b2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#46009 chore: cherry-pick 3 changes from 0-M134
  patches/chromium/.patches
  patches/chromium/add_a_flag_to_enable_strict_js_compliance_in_audioworklet.patch
  patches/chromium/allow_denormal_flushing_to_outlive_scoped_object.patch
  patches/chromium/remove_denormalenabler_from_scriptprocessornode.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#46010 chore: cherry-pick 3 changes from 0-M134
  patches/chromium/.patches
  patches/chromium/add_a_flag_to_enable_strict_js_compliance_in_audioworklet.patch
  patches/chromium/allow_denormal_flushing_to_outlive_scoped_object.patch
  patches/chromium/remove_denormalenabler_from_scriptprocessornode.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#46012 chore: cherry-pick 1 changes from 1-M134
  patches/v8/.patches
  patches/v8/cherry-pick-2b4812d502b2.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45992 fix: don't crash Web Workers on unhandled rejections
  shell/renderer/web_worker_observer.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#45997 fix: package import existence verification
  patches/node/fix_allow_passing_fileexists_fn_to_legacymainresolve.patch
  patches/node/src_stop_using_deprecated_fields_of_fastapicallbackoptions.patch
Labels: semver/patch, target/35-x-y, target/36-x-y

#46008 chore: cherry-pick 1 changes from 3-M133
  patches/v8/.patches
  patches/v8/cherry-pick-91343bb45c78.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#46016 build: roll sysroots again
  script/sysroots.json
Labels: semver/patch, target/36-x-y

#45988 refactor: make a variadic `gin_helper::internal::InvokeFactory()`
  shell/common/gin_helper/constructor.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46025 fix: `system-context-menu` should only fire in draggable regions (33-x-y)
  patches/chromium/.patches
  patches/chromium/chore_modify_chromium_handling_of_mouse_events.patch
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: backport, semver/patch, 33-x-y

#45851 fix: emit `context-menu` event in Windows draggable regions
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#45981 fix: prevent title change for within page navigation
  shell/browser/api/electron_api_web_contents.cc
  spec/api-web-contents-spec.ts
  spec/fixtures/pages/navigation-history-anchor-in-page.html
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46006 fix: take Snapped status into account when showing a window
  patches/chromium/.patches
  patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#45921 fix: don't crash Utility Processes on unhandled rejections
  docs/breaking-changes.md
  shell/services/node/node_service.cc
Labels: semver/major, new-pr 🌱, api-review/requested 🗳, no-backport

#46015 refactor: remove unused system header includes
  shell/app/electron_content_client.cc
  shell/app/electron_main_linux.cc
  shell/app/electron_main_win.cc
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_service_worker_main.h
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/gpu_info_enumerator.h
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/extensions/api/extension_action/extension_action_api.cc
  shell/browser/extensions/api/extension_action/extension_action_api.h
  shell/browser/extensions/api/scripting/scripting_api.h
  shell/browser/file_system_access/file_system_access_permission_context.h
  shell/browser/javascript_environment.cc
  shell/browser/native_window.h
  shell/browser/net/asar/asar_file_validator.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/relauncher.cc
  shell/browser/ui/devtools_ui_bundle_data_source.cc
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/browser/zoom_level_delegate.cc
  shell/common/process_util.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/extensions/electron_extensions_renderer_client.cc
  shell/renderer/extensions/electron_extensions_renderer_client.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46046 chore: remove redundant patch
  patches/chromium/.patches
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/cherry-pick-521faebc8a7c.patch
  patches/chromium/cherry-pick-9dacf5694dfd.patch
  patches/chromium/create_browser_v8_snapshot_file_name_fuse.patch
  patches/chromium/fix_harden_blink_scriptstate_maybefrom.patch
  patches/chromium/gin_enable_disable_v8_platform.patch
  patches/chromium/revert_code_health_clean_up_stale_macwebcontentsocclusion.patch
Labels: semver/patch, fast-track 🚅, no-backport, 35-x-y

#46024 refactor: replace base::StringPrintf() calls with absl::StrFormat()
  shell/browser/api/electron_api_session.cc
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#45863 feat: ServiceWorkerMain.scriptURL
  docs/api/service-worker-main.md
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_service_worker_main.h
  spec/api-service-worker-main-spec.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#46030 fix: `ElectronBrowserContext` `raw_ptr` bug + remove dead code
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46047 build: fix compound bash conditional in patchup
  .github/actions/checkout/action.yml
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y

#46044 perf: avoid redundant map lookup in ElectronBrowserContext::From()
  shell/browser/electron_browser_context.cc
Labels: semver/patch, new-pr 🌱, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46068 chore: e patches all
  patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch
Labels: semver/patch, fast-track 🚅, no-backport

#46067 fix: warning in file picker UI
  shell/browser/file_system_access/file_system_access_permission_context.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46064 refactor: use `GetDefaultStoragePartition()` instead of `GetStoragePartition(nullptr)`
  shell/browser/api/electron_api_session.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46091 build: move set chromium cookie before build tools step
  .github/actions/checkout/action.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: fast-track 🚅, semver/none, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46110 test: fix `app.dock` for corrected type
  spec/api-app-spec.ts
  spec/api-browser-window-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: fast-track 🚅, semver/none, target/34-x-y, target/35-x-y, target/36-x-y

#46080 build: fail for out of date patches on forks
  .github/actions/checkout/action.yml
  script/push-patch.js
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y

#46093 docs: fix code example in breaking-changes.md
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, no-backport

#46105 test: disable `parallel/test-worker-resource-limits`
  script/node-disabled-tests.json
Labels: fast-track 🚅, semver/none, target/36-x-y

#46136 refactor: add `ElectronBrowserContext::GetDefaultBrowserContext()` (34-x-y)
  shell/browser/api/electron_api_session.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/ui/devtools_manager_delegate.cc
Labels: backport, semver/patch, no-backport, 34-x-y

#46119 docs: use optional chaining for `app.dock`
  docs/api/dock.md
  docs/fiddles/features/macos-dock-menu/main.js
  docs/tutorial/macos-dock.md
Labels: documentation :notebook:, semver/patch, target/35-x-y, target/36-x-y

#46129 build: combine pipewire patches
  patches/webrtc/.patches
  patches/webrtc/fix_check_pipewire_init_before_creating_generic_capturer.patch
  patches/webrtc/fix_fallback_to_x11_capturer_on_wayland.patch
  patches/webrtc/fix_handle_pipewire_capturer_initialization_and_management.patch
  patches/webrtc/fix_mark_pipewire_capturer_as_failed_after_session_is_closed.patch
Labels: semver/none, in-flight/35-x-y, target/36-x-y

#46087 fix: `webContents.print()` crash on Linux
  shell/browser/feature_list.cc
Labels: semver/patch, target/35-x-y, target/36-x-y

#46135 refactor: remove unused system header includes (34-x-y)
  shell/app/electron_content_client.cc
  shell/app/electron_main_linux.cc
  shell/app/electron_main_win.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/gpu_info_enumerator.h
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/extensions/api/extension_action/extension_action_api.cc
  shell/browser/extensions/api/extension_action/extension_action_api.h
  shell/browser/extensions/api/scripting/scripting_api.h
  shell/browser/file_system_access/file_system_access_permission_context.h
  shell/browser/javascript_environment.cc
  shell/browser/native_window.h
  shell/browser/net/asar/asar_file_validator.cc
  shell/browser/net/system_network_context_manager.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/relauncher.cc
  shell/browser/ui/devtools_ui_bundle_data_source.cc
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/browser/zoom_level_delegate.cc
  shell/common/process_util.h
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/electron_api_service_impl.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/extensions/electron_extensions_renderer_client.cc
  shell/renderer/extensions/electron_extensions_renderer_client.h
Labels: backport, semver/patch, no-backport, 34-x-y

#46134 refactor: use C++20's contains() method (33-x-y)
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_power_save_blocker.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/message_box_mac.mm
  shell/browser/ui/message_box_win.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/common/api/electron_api_clipboard.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: backport, semver/patch, no-backport, 33-x-y

#46101 fix: APNS token ids are lowercase ASCII
  docs/api/push-notifications.md
  shell/browser/api/electron_api_push_notifications_mac.mm
  shell/browser/mac/electron_application_delegate.mm
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46108 refactor: remove ToV8(isolate, const char*)
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_converters/std_converter.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46141 refactor: use base::NumberToString()
  shell/browser/serial/serial_chooser_controller.cc
  shell/common/gin_converters/serial_port_info_converter.h
Labels: semver/patch, new-pr 🌱, target/34-x-y, target/35-x-y, target/36-x-y

#46089 refactor: Add `ElectronBrowserContext::BrowserContexts()`
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46168 refactor: make URLPipeLoader private (34-x-y)
  filenames.gni
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/net/url_pipe_loader.cc
  shell/browser/net/url_pipe_loader.h
Labels: backport, semver/patch, no-backport, 34-x-y

#45887 refactor: use upstream `Widget::IsVisibleOnAllWorkspaces()`
  docs/breaking-changes.md
  shell/browser/native_window_views.cc
Labels: semver/major, api-review/approved ✅, no-backport

#46151 feat: add ffmpeg.dll to delay load configuration
  BUILD.gn
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/34-x-y, target/35-x-y, target/36-x-y

#46104 fix: add missing `cpp_heap` to Node.js worker `CreateParams`
  patches/node/refactor_attach_cppgc_heap_on_v8_isolate_creation.patch
Labels: semver/patch, target/36-x-y

#46005 fix: remove `File.path` from types
  docs/api/web-utils.md
  package.json
  yarn.lock
Labels: semver/patch, target/36-x-y

#46161 refactor: Add `ElectronBrowserContext::BrowserContexts()` (35-x-y backport)
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
  shell/browser/electron_browser_main_parts.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
Labels: backport, semver/patch, no-backport, 35-x-y

#45881 build: Use windows src cache
  .github/actions/checkout/action.yml
  .github/actions/cipd-install/action.yml
  .github/actions/fix-sync-macos/action.yml
  .github/actions/fix-sync/action.yml
  .github/actions/install-build-tools/action.yml
  .github/actions/restore-cache-aks/action.yml
  .github/actions/restore-cache-azcopy/action.yml
  .github/workflows/build.yml
  .github/workflows/clean-src-cache.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-gn-check.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46165 refactor: use `= default` to define trivial destructors
  shell/browser/api/electron_api_view.cc
  shell/browser/extensions/api/extension_action/extension_action_api.cc
  shell/browser/extensions/api/extension_action/extension_action_api.h
  shell/browser/net/web_request_api_interface.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46170 refactor: remove unused method `ElectronBrowserContext::GetWeakPtr()`
  shell/browser/electron_browser_context.cc
  shell/browser/electron_browser_context.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46178 fix: system-context-menu should only fire in draggable regions (35-x-y)
  patches/chromium/.patches
  patches/chromium/chore_modify_chromium_handling_of_mouse_events.patch
  patches/chromium/fix_activate_background_material_on_windows.patch
  patches/chromium/fix_remove_caption-removing_style_call.patch
  patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: backport, semver/patch, 35-x-y

#46171 refactor: remove unused field `ServiceWorkerMain::weak_factory_`
  shell/browser/api/electron_api_service_worker_main.h
Labels: semver/patch, target/35-x-y, target/36-x-y

#46130 docs: fix capitalization for `InputEvent.modifiers`
  docs/api/structures/input-event.md
Labels: documentation :notebook:, semver/patch, component/webcontents, target/36-x-y

#46100 fix: ensure `TraverseParent` bails on resource path exit
  patches/node/.patches
  patches/node/fix_ensure_traverseparent_bails_on_resource_path_exit.patch
Labels: semver/patch, target/35-x-y, target/36-x-y

#46202 perf: use `absl::flat_hash_map` instead of `std::unordered_map`
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/electron_autofill_driver_factory.h
  shell/browser/hid/electron_hid_delegate.h
  shell/browser/serial/electron_serial_delegate.h
  shell/browser/usb/electron_usb_delegate.h
  shell/common/asar/archive.h
  shell/common/key_weak_map.h
  shell/renderer/api/context_bridge/object_cache.h
Labels: performance :checkered_flag:, semver/patch, target/36-x-y

#46201 refactor: remove unused method ProxyingWebSocket::web_request_api()
  shell/browser/net/proxying_websocket.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46200 refactor: remove unused `weak_factory_` in electron_management_api_delegate.cc
  shell/browser/extensions/api/management/electron_management_api_delegate.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46155 fix: Wayland resizing border
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/client_frame_view_linux.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y, target/36-x-y

#46079 feat: add `BrowserWindow.isSnapped()`
  docs/api/base-window.md
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: semver/minor, api-review/approved ✅, target/36-x-y

#45185 feat: Corner Smoothing CSS rule
  docs/README.md
  docs/api/corner-smoothing-css.md
  docs/api/structures/web-preferences.md
  docs/images/corner-smoothing-example-0.svg
  docs/images/corner-smoothing-example-100.svg
  docs/images/corner-smoothing-example-30.svg
  docs/images/corner-smoothing-example-60.svg
  docs/images/corner-smoothing-summary.svg
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/feat_corner_smoothing_css_rule_and_blink_painting.patch
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/options_switches.h
  shell/renderer/electron_smooth_round_rect.cc
  shell/renderer/electron_smooth_round_rect.h
  spec/api-corner-smoothing-spec.ts
  spec/fixtures/api/corner-smoothing/shape/expected-false.png
  spec/fixtures/api/corner-smoothing/shape/expected-true.png
  spec/fixtures/api/corner-smoothing/shape/image.png
  spec/fixtures/api/corner-smoothing/shape/test.html
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-darwin.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-linux.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-win32.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/test.html
Labels: semver/minor, api-review/approved ✅, no-backport

#46228 build: fixup release builds
  .github/actions/build-electron/action.yml
  .github/workflows/macos-publish.yml
  .github/workflows/windows-publish.yml
Labels: fast-track 🚅, semver/none, target/34-x-y, target/36-x-y

#46112 fix: handle OnDelegatedSourceListDismissed asynchronously
  shell/browser/api/electron_api_desktop_capturer.cc
Labels: semver/patch, target/35-x-y, target/36-x-y

#46231 fix: Revert "feat: Corner Smoothing CSS rule"
  docs/README.md
  docs/api/corner-smoothing-css.md
  docs/api/structures/web-preferences.md
  docs/images/corner-smoothing-example-0.svg
  docs/images/corner-smoothing-example-100.svg
  docs/images/corner-smoothing-example-30.svg
  docs/images/corner-smoothing-example-60.svg
  docs/images/corner-smoothing-summary.svg
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/feat_corner_smoothing_css_rule_and_blink_painting.patch
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/options_switches.h
  shell/renderer/electron_smooth_round_rect.cc
  shell/renderer/electron_smooth_round_rect.h
  spec/api-corner-smoothing-spec.ts
  spec/fixtures/api/corner-smoothing/shape/expected-false.png
  spec/fixtures/api/corner-smoothing/shape/expected-true.png
  spec/fixtures/api/corner-smoothing/shape/image.png
  spec/fixtures/api/corner-smoothing/shape/test.html
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-darwin.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-linux.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-win32.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/test.html
Labels: fast-track 🚅, semver/none, no-backport

#46209 fix: NODE_OPTIONS parsing for child processes on macOS
  shell/browser/api/electron_api_app.cc
  spec/fixtures/apps/node-options-utility-process/fail.js
  spec/fixtures/apps/node-options-utility-process/main.js
  spec/fixtures/apps/node-options-utility-process/noop.js
  spec/fixtures/apps/node-options-utility-process/package.json
  spec/node-spec.ts
Labels: semver/patch, new-pr 🌱, target/34-x-y, target/35-x-y, target/36-x-y

#46175 fix: system-context-menu should only fire in draggable regions (34-x-y)
  patches/chromium/.patches
  patches/chromium/chore_modify_chromium_handling_of_mouse_events.patch
  patches/chromium/fix_activate_background_material_on_windows.patch
  patches/chromium/fix_remove_caption-removing_style_call.patch
  patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: backport, semver/patch, 34-x-y

#46218 fix: `webContents.printToPDF()` with cross-process subframes
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/extensions/electron_extensions_api_client.cc
  spec/api-web-contents-spec.ts
  spec/fixtures/api/print-to-pdf-same-origin.html
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46230 perf: avoid `std::map` temporaries in `IsDevToolsFileSystemAdded()`
  shell/browser/api/electron_api_web_contents.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46238 perf: avoid redundant map lookup in `WebFrameMain` constructor
  shell/browser/api/electron_api_web_frame_main.cc
Labels: performance :checkered_flag:, semver/patch, new-pr 🌱, target/34-x-y, target/35-x-y, target/36-x-y

#46283 fix: build failure when printing is disabled
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/feature_list.cc
Labels: semver/patch, fast-track 🚅, target/34-x-y, target/35-x-y, target/36-x-y

#46004 fix: hard crash on invalid command line switches
  docs/api/command-line.md
  docs/breaking-changes.md
  shell/common/api/electron_api_command_line.cc
Labels: semver/patch, target/35-x-y, target/36-x-y

#46286 fix: build failure when printing is disabled
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/feature_list.cc
Labels: backport, semver/patch, 34-x-y

#46254 perf: avoid redundant map lookup in `WebContents::DevToolsIndexPath()`
  shell/browser/api/electron_api_web_contents.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46268 perf: avoid `std::map` temporaries in `WebContents::DevToolsRequestFileSystems()`
  shell/browser/api/electron_api_web_contents.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46253 fix: crash when drag-dropping some files
  shell/renderer/api/electron_api_context_bridge.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46303 chore: cherry-pick 1 changes from 3-M134
  patches/chromium/.patches
  patches/chromium/cherry-pick-b8f80176b163.patch
Labels: security 🔒, semver/patch, backport-check-skip, 35-x-y

#46305 chore: cherry-pick 1 changes from 3-M134
  patches/chromium/.patches
  patches/chromium/cherry-pick-b8f80176b163.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#46314 chore: reconcile Chrome roll patches
  patches/chromium/.patches
  patches/chromium/cherry-pick-b8f80176b163.patch
Labels: fast-track 🚅, backport-check-skip, semver/none, 35-x-y

#46291 build: roll build-images SHAs
  .devcontainer/docker-compose.yml
  .github/workflows/build.yml
  .github/workflows/linux-publish.yml
  .github/workflows/macos-publish.yml
  .github/workflows/windows-publish.yml
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y

#46304 chore: cherry-pick 1 changes from 3-M134
  patches/chromium/.patches
  patches/chromium/cherry-pick-b8f80176b163.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#46294 fix: possible crash in `shell.readShortcutLink`
  patches/chromium/.patches
  patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
  patches/chromium/ignore_parse_errors_for_resolveshortcutproperties.patch
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46274 build: validate Chromium cookie authentication
  .github/actions/set-chromium-cookie/action.yml
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y

#46293 perf: avoid double map lookup in `WebFrameMain::UpdateRenderFrameHost()`
  shell/browser/api/electron_api_web_frame_main.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46306 perf: avoid a triple-redundant map lookup in `ViewsDelegate::GetAppbarAutohideEdges()`
  shell/browser/ui/views/electron_views_delegate_win.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46328 fix: emit `context-menu` event in Windows draggable regions
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  spec/api-web-contents-spec.ts
Labels: backport, semver/patch, 34-x-y

#46334 fix: emit `context-menu` event in Windows draggable regions
  shell/browser/native_window_views_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  spec/api-web-contents-spec.ts
Labels: backport, semver/patch, 35-x-y

#46307 fix: allow NSMenuItems to be disabled
  shell/browser/ui/cocoa/electron_menu_controller.mm
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46315 perf: avoid redundant map lookups in `GetStorageMask()`
  shell/browser/api/electron_api_session.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#45138 feat: add support for associating a Menu with a WebFrameMain
  docs/api/menu.md
  lib/browser/api/menu.ts
  patches/chromium/.patches
  patches/chromium/fix_multiple_scopedpumpmessagesinprivatemodes_instances.patch
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/api/electron_api_menu_mac.h
  shell/browser/api/electron_api_menu_mac.mm
  shell/browser/api/electron_api_menu_views.cc
  shell/browser/api/electron_api_menu_views.h
  shell/browser/api/electron_api_web_frame_main.h
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, target/36-x-y

#46338 perf: avoid a double-map lookup in `NotificationPresenter::RemoveNotification()`
  shell/browser/notifications/notification_presenter.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46339 perf: avoid 3x call to `GetID()` in RegisterPendingSiteInstance()
  shell/browser/electron_browser_client.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46343 perf: avoid double map lookup in HidChooserContext::DeviceRemoved()
  shell/browser/hid/hid_chooser_context.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46349 refactor: use `v8::String::Empty()` when creating empty strings
  shell/browser/api/electron_api_app.cc
  shell/browser/ui/cocoa/electron_bundle_mover.mm
  shell/common/gin_converters/guid_converter.h
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46348 perf: prefer `absl::flat_hash_set` over `std::unordered_set`
  shell/browser/api/message_port.cc
  shell/renderer/api/electron_api_spell_check_client.cc
Labels: performance :checkered_flag:, semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46347 perf: improve temporaries in `WebWorkerObserver::WorkerScriptReadyForEvaluation()`
  shell/renderer/web_worker_observer.cc
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y

#46363 refactor: remove field `unused weak_factory_`
  shell/browser/api/electron_api_extensions.h
Labels: semver/patch, no-backport

#46278 feat: Corner Smoothing CSS rule (Reland)
  docs/README.md
  docs/api/corner-smoothing-css.md
  docs/api/structures/web-preferences.md
  docs/images/corner-smoothing-example-0.svg
  docs/images/corner-smoothing-example-100.svg
  docs/images/corner-smoothing-example-30.svg
  docs/images/corner-smoothing-example-60.svg
  docs/images/corner-smoothing-summary.svg
  filenames.auto.gni
  filenames.gni
  patches/chromium/.patches
  patches/chromium/feat_corner_smoothing_css_rule_and_blink_painting.patch
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/options_switches.h
  shell/renderer/electron_smooth_round_rect.cc
  shell/renderer/electron_smooth_round_rect.h
  spec/api-corner-smoothing-spec.ts
  spec/fixtures/api/corner-smoothing/shape/expected-false.png
  spec/fixtures/api/corner-smoothing/shape/expected-true.png
  spec/fixtures/api/corner-smoothing/shape/image.png
  spec/fixtures/api/corner-smoothing/shape/test.html
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-darwin.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-linux.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/expected-win32.png
  spec/fixtures/api/corner-smoothing/system-ui-keyword/test.html
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, api-review/skip-delay ⏰, target/36-x-y

#46353 fix: flicker and ghosting in transparent windows on macOS
  shell/browser/native_window_mac.mm
Labels: semver/patch, target/35-x-y, target/36-x-y
