Repository electron/electron, pull requests merged in 2025-05, with the labels that each got.

#46873 fix: display id order validation on certain versions of Windows 10
  patches/chromium/.patches
  patches/chromium/do_not_check_the_order_of_display_id_order_on_windows.patch
  patches/chromium/windows_retrieve_primary_monitor_information_early.patch
Labels: semver/patch, backport-check-skip, 35-x-y

#46874 fix: display id order validation on certain versions of Windows 10
  patches/chromium/.patches
  patches/chromium/do_not_check_the_order_of_display_id_order_on_windows.patch
Labels: semver/patch, backport-check-skip, 36-x-y

#46877 feat: add support for `--js-flags=--perf-prof` on macOS
  patches/v8/.patches
  patches/v8/enable_--perf-prof_flag_on_macos.patch
Labels: backport, semver/minor, backport/requested 🗳, 35-x-y

#46876 feat: add support for `--js-flags=--perf-prof` on macOS
  patches/v8/.patches
  patches/v8/enable_--perf-prof_flag_on_macos.patch
Labels: backport, semver/minor, backport/requested 🗳, 36-x-y

#46867 test: refactor deprecate-helpers.ts to warning-helpers.ts
  spec/extensions-spec.ts
  spec/lib/deprecate-helpers.ts
  spec/lib/warning-helpers.ts
Labels: backport, semver/none, 34-x-y

#46858 refactor: don't call deprecated `WidgetDelegate` API in `NativeWindowViews`
  patches/chromium/chore_grandfather_in_electron_views_and_delegates.patch
  shell/browser/native_window_views.cc
Labels: semver/patch, new-pr 🌱, target/36-x-y, target/37-x-y

#46211 feat: support dip <-> screen conversion on Linux X11
  BUILD.gn
  docs/api/base-window.md
  docs/api/browser-window.md
  docs/api/screen.md
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_screen.h
  shell/browser/linux/x11_util.cc
  shell/browser/linux/x11_util.h
  shell/browser/native_window_views.cc
Labels: semver/minor, api-review/approved ✅, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#46875 refactor: use `base::ObserverList::Notify()`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/browser.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/native_window.cc
  shell/browser/serial/electron_serial_delegate.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/electron_menu_model.cc
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/views/menu_delegate.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/browser/web_contents_zoom_controller.cc
  shell/browser/window_list.cc
Labels: semver/patch, target/36-x-y, target/37-x-y

#46809 docs: clarified usage of createFromPath()
  docs/api/native-image.md
Labels: documentation :notebook:, semver/patch, target/36-x-y, target/37-x-y

#46888 refactor: move `IsClosed()` and `IsClosable()` tests into `NativeWindow::Close()`
  shell/browser/api/electron_api_base_window.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/window_list.cc
Labels: semver/patch, new-pr 🌱, target/37-x-y

#44413 fix: prevent log files being written to current directory on Windows
  shell/common/api/electron_api_testing.cc
  shell/common/logging.cc
  spec/fixtures/log-test.js
  spec/logging-spec.ts
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#46917 refactor: add `NativeWindow::FromWidget()` helper
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
Labels: semver/patch, target/36-x-y, target/37-x-y

#46918 refactor: simplify `NativeWindow::FullScreenTransitionState`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: semver/patch, target/36-x-y, target/37-x-y

#46919 refactor: remove some `NativeWindow` public API
  shell/browser/native_window.cc
  shell/browser/native_window.h
Labels: semver/patch, target/36-x-y, target/37-x-y

#46904 refactor: devirtualize `NativeWindow` methods
  shell/browser/native_window.h
Labels: semver/patch, target/36-x-y, target/37-x-y

#46933 refactor: simplify `NativeWindow::FullScreenTransitionState` (36-x-y)
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
Labels: backport, semver/patch, 36-x-y

#46936 fix: xdg portal version detection for file dialogs on linux
  filenames.gni
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
  shell/browser/ui/file_dialog.h
  shell/browser/ui/file_dialog_linux.cc
  shell/browser/ui/file_dialog_linux_portal.cc
Labels: backport, semver/patch, 35-x-y

#46892 docs: use correct heading level for API function
  docs/api/app.md
Labels: documentation :notebook:, semver/patch, target/36-x-y, target/37-x-y

#46934 refactor: remove some `NativeWindow` public API (37-x-y)
  shell/browser/native_window.cc
  shell/browser/native_window.h
Labels: backport, semver/patch, target/36-x-y, 37-x-y

#46900 fix: allowed dialog file types with one filter
  shell/browser/ui/file_dialog_mac.mm
Labels: semver/patch, target/36-x-y, target/37-x-y

#46927 fix: crash on macOS dialog after `window-all-closed`
  shell/browser/ui/cocoa/electron_ns_window.mm
Labels: semver/patch, new-pr 🌱, target/35-x-y, target/36-x-y, target/37-x-y

#46935 refactor: pass `gfx::ResizeEdge` by value
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_observer.h
  shell/common/gin_converters/gfx_converter.cc
  shell/common/gin_converters/gfx_converter.h
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#44634 test: test menu rendering accelerators
  spec/api-global-shortcut-spec.ts
  spec/api-menu-spec.ts
  spec/lib/accelerator-helpers.ts
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#46937 fix: printing when no `mediaSize` specified
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, target/36-x-y, target/37-x-y

#46765 refactor: use `WidgetDelegate::SetAccessibleTitle()`
  shell/browser/native_window.cc
  shell/browser/native_window.h
  spec/api-browser-window-spec.ts
Labels: semver/patch, no-backport

#46963 refactor: replace `gin_helper::MicrotasksScope` with `v8::MicrotasksScope`
  filenames.gni
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/gin_helper/microtasks_scope.cc
  shell/common/gin_helper/microtasks_scope.h
  shell/common/gin_helper/promise.cc
  shell/common/gin_helper/promise.h
  shell/common/node_bindings.cc
  shell/common/v8_util.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: semver/none, no-backport

#46989 build: move release script to new hasher function
  script/release/get-url-hash.ts
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#46988 build: remove skip_atk_toolchain_check.patch
  patches/chromium/.patches
  patches/chromium/skip_atk_toolchain_check.patch
Labels: semver/none, no-backport

#46984 test: enable `hasShadow` tests on Linux
  spec/api-browser-window-spec.ts
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#46977 feat: support system-context-menu on Linux
  docs/api/base-window.md
  docs/api/browser-window.md
  patches/chromium/.patches
  patches/chromium/add_linux_window_controls_menu.patch
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
Labels: backport, semver/minor, backport/approved ✅, 35-x-y

#46942 refactor: reduce use of `NativeWidgetPrivate`
  shell/browser/native_window_views.cc
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/36-x-y, target/37-x-y

#47009 build: update hasher return value
  script/release/get-url-hash.ts
Labels: fast-track 🚅, semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#46982 refactor: use `gin_helper::Dictionary::ValueOrDefault()`
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/electron_browser_context.cc
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/net/electron_url_loader_factory.cc
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/common/api/electron_api_url_loader.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/gin_helper/persistent_dictionary.h
Labels: semver/patch, target/36-x-y, target/37-x-y

#46690 feat: add support for `--experimental-network-inspection`
  docs/api/command-line-switches.md
  shell/common/node_bindings.cc
Labels: semver/minor, api-review/approved ✅, target/35-x-y, target/36-x-y, target/37-x-y

#47020 fix: restore previous Windows screenshotting
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: semver/patch, new-pr 🌱, target/35-x-y, target/36-x-y, target/37-x-y

#46979 fix: webview crash on focus
  patches/chromium/.patches
  patches/chromium/make_focus_methods_in_webcontentsviewchildframe_notimplemented.patch
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#46749 feat: enable innerWidth and innerHeight for window open
  lib/browser/parse-features-string.ts
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/common/options_switches.h
  spec/chromium-spec.ts
  spec/fixtures/pages/window-open-size-inner.html
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#46887 feat: enable secondary label for macOS menu
  docs/api/menu-item.md
  docs/api/menu.md
  shell/browser/ui/cocoa/electron_menu_controller.mm
Labels: semver/minor, api-review/approved ✅, target/35-x-y, target/36-x-y, target/37-x-y

#46893 docs: unify [!NOTE] structure
  docs/api/app.md
  docs/api/auto-updater.md
  docs/api/base-window.md
  docs/api/browser-view.md
  docs/api/browser-window.md
  docs/api/clipboard.md
  docs/api/command-line-switches.md
  docs/api/command-line.md
  docs/api/content-tracing.md
  docs/api/crash-reporter.md
  docs/api/desktop-capturer.md
  docs/api/dialog.md
  docs/api/dock.md
  docs/api/download-item.md
  docs/api/extensions-api.md
  docs/api/extensions.md
  docs/api/global-shortcut.md
  docs/api/ipc-renderer.md
  docs/api/menu-item.md
  docs/api/menu.md
  docs/api/native-image.md
  docs/api/net-log.md
  docs/api/net.md
  docs/api/power-save-blocker.md
  docs/api/process.md
  docs/api/protocol.md
  docs/api/screen.md
  docs/api/session.md
  docs/api/shell.md
  docs/api/structures/jump-list-category.md
  docs/api/structures/point.md
  docs/api/touch-bar-other-items-proxy.md
  docs/api/touch-bar.md
  docs/api/tray.md
  docs/api/utility-process.md
  docs/api/view.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  docs/api/webview-tag.md
  docs/development/build-instructions-gn.md
  docs/development/build-instructions-windows.md
  docs/development/creating-api.md
  docs/development/patches.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/multithreading.md
  docs/tutorial/online-offline-events.md
  docs/tutorial/process-model.md
  docs/tutorial/repl.md
  docs/tutorial/web-embeds.md
Labels: documentation :notebook:, semver/none, target/36-x-y, target/37-x-y

#47022 fix: white window flicker on window creation
  shell/browser/native_window_views.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47059 chore: remove disable_unload_metrics.patch
  patches/chromium/.patches
  patches/chromium/disable_unload_metrics.patch
Labels: semver/none, no-backport

#47079 build: remove patch that landed upstream
  patches/chromium/.patches
  patches/chromium/make_focus_methods_in_webcontentsviewchildframe_notimplemented.patch
Labels: fast-track 🚅, semver/none, no-backport

#47075 refactor: remove `introduce_ozoneplatform_electron_can_call_x11_property.patch`
  patches/chromium/.patches
  patches/chromium/introduce_ozoneplatform_electron_can_call_x11_property.patch
  shell/browser/linux/x11_util.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/gtk/menu_util.cc
Labels: new-pr 🌱, semver/none, no-backport

#46981 refactor: remove `CreateViewForWidget` patch
  patches/chromium/.patches
  patches/chromium/render_widget_host_view_base.patch
  shell/browser/osr/osr_render_widget_host_view.h
  shell/browser/osr/osr_web_contents_view.cc
  shell/browser/web_view_guest_delegate.cc
Labels: semver/patch, target/37-x-y

#47063 chore: combine all the "patch out Profiles" changes into a single patch
  patches/chromium/.patches
  patches/chromium/chore_patch_out_profile_methods.patch
  patches/chromium/chore_patch_out_profile_methods_in_chrome_browser_pdf.patch
  patches/chromium/chore_patch_out_profile_methods_in_profile_selections_cc.patch
  patches/chromium/chore_patch_out_profile_methods_in_titlebar_config.patch
  patches/chromium/fix_remove_profiles_from_spellcheck_service.patch
Labels: semver/none, no-backport

#47066 refactor: use kKeyModifiers in IsAltModifier()
  shell/browser/ui/views/root_view.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47045 feat: enable innerWidth and innerHeight for window open (#46749)
  lib/browser/parse-features-string.ts
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/common/options_switches.h
  spec/chromium-spec.ts
  spec/fixtures/pages/window-open-size-inner.html
Labels: backport, semver/patch, backport/approved ✅, 35-x-y

#47088 test: fix desktopCapturer mocha syntax
  spec/api-desktop-capturer-spec.ts
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47092 refactor: make TrackableObject::weak_map_id() constexpr
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_base_window.h
  shell/browser/native_window.h
  shell/common/gin_helper/trackable_object.h
Labels: performance :checkered_flag:, semver/patch, target/36-x-y, target/37-x-y

#47094 refactor: decouple NativeWindowViews and GlobalMenuBarX11
  shell/browser/native_window_views.cc
  shell/browser/ui/views/global_menu_bar_x11.cc
  shell/browser/ui/views/global_menu_bar_x11.h
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47080 docs: add note on DIP and DPI
  docs/api/screen.md
Labels: documentation :notebook:, semver/patch, target/36-x-y, target/37-x-y

#47100 perf: don't create unused menuitem icons
  shell/browser/ui/gtk/menu_util.cc
  shell/browser/ui/gtk/menu_util.h
Labels: performance :checkered_flag:, semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47134 fix: explicit microtask scope DCHECK condition
  shell/common/node_util.cc
Labels: semver/patch, target/37-x-y

#47131 refactor: add NativeWindow::SetShape()
  shell/browser/api/electron_api_base_window.cc
  shell/browser/native_window.cc
  shell/browser/native_window.h
Labels: semver/patch, no-backport

#47082 build(dev-deps): update @electron/lint-roller and markdownlint-cli2
  .github/workflows/archaeologist-dig.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .markdownlint-cli2.jsonc
  package.json
  yarn.lock
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#47133 refactor: NativeWindows should prefer widget() over GetWidget() for internal use
  shell/browser/native_window.cc
  shell/browser/native_window_views.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47150 build: remove `fix_linter_error.patch`
  patches/chromium/.patches
  patches/chromium/fix_linter_error.patch
Labels: semver/none, no-backport

#46987 fix: prevent gc monitor 2nd pass crash
  shell/common/gin_converters/osr_converter.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47160 build: update_depot_tools on initial install
  .github/actions/install-build-tools/action.yml
Labels: fast-track 🚅, semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#47148 refactor: add NativeWindow::IsActive()
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/native_window.h
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
Labels: semver/patch, no-backport

#47157 refactor: make `NativeWindow::pending_transitions_` a `base::queue`
  shell/browser/native_window.h
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47176 chore: cherry-pick 2 changes from 2-M136
  patches/chromium/.patches
  patches/chromium/cherry-pick-295a4a1b14b8.patch
  patches/chromium/cherry-pick-c3568ceda9d8.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#47070 chore: cherry-pick 1 changes from 0-M136
  patches/v8/.patches
  patches/v8/cherry-pick-22ac8acf3508.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#47069 chore: cherry-pick 1 changes from 0-M136
  patches/v8/.patches
  patches/v8/cherry-pick-22ac8acf3508.patch
Labels: security 🔒, semver/patch, backport-check-skip, 35-x-y

#47185 test: strip color output in ESM spec
  spec/esm-spec.ts
Labels: semver/none, no-backport

#47162 fix: remove extra 'suspend'/'resume' handling from `powerMonitor`
  shell/browser/api/electron_api_power_monitor_mac.mm
  shell/browser/api/electron_api_power_monitor_win.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47125 feat: support dip <-> screen conversion on Linux
  BUILD.gn
  docs/api/base-window.md
  docs/api/browser-window.md
  docs/api/screen.md
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_screen.h
  shell/browser/linux/x11_util.cc
  shell/browser/linux/x11_util.h
  shell/browser/native_window_views.cc
Labels: backport, semver/minor, backport/approved ✅, 36-x-y

#47124 feat: support dip <-> screen conversion on Linux
  BUILD.gn
  docs/api/base-window.md
  docs/api/browser-window.md
  docs/api/screen.md
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_screen.h
  shell/browser/linux/x11_util.cc
  shell/browser/linux/x11_util.h
  shell/browser/native_window_views.cc
Labels: backport, semver/minor, backport/approved ✅, 35-x-y

#47171 refactor: prefer `base::circular_deque` over `std::deque`
  shell/browser/net/resolve_proxy_helper.h
  shell/common/crash_keys.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47172 refactor: make `NativeWindow::transparent_` const
  shell/browser/native_window.cc
  shell/browser/native_window.h
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47177 refactor: pass views::Widget* into constructors of our TreeHosts and NativeWidgets
  shell/browser/api/electron_api_menu_views.cc
  shell/browser/native_window_views.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
  shell/browser/ui/win/electron_desktop_native_widget_aura.cc
  shell/browser/ui/win/electron_desktop_native_widget_aura.h
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.h
Labels: semver/patch, no-backport

#47194 build: fix depot tool pathing on Windows
  .github/actions/install-build-tools/action.yml
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#47208 build: revert bump @octokit/rest from 20.1.1 to 21.1.1
  package.json
  yarn.lock
Labels: fast-track 🚅, semver/none

#47195 chore: remove deps_add_v8_object_setinternalfieldfornodecore.patch (36-x-y)
  patches/v8/.patches
  patches/v8/deps_add_v8_object_setinternalfieldfornodecore.patch
Labels: backport, semver/none, 36-x-y

#47203 refactor: add `gin_helper::Dictionary::ValueOrDefault()` (35-x-y)
  shell/browser/native_window.cc
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/common/api/electron_api_native_image.cc
  shell/common/gin_helper/dictionary.h
Labels: backport, semver/patch, 35-x-y

#46577 ci: add problem matcher for clang output
  .github/actions/build-electron/action.yml
  .github/problem-matchers/clang.json
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#47183 ci: add problem matcher for patch conflict output
  .github/actions/checkout/action.yml
  .github/problem-matchers/patch-conflict.json
Labels: semver/none, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#47227 build: fix depot tool pathing on Windows (#47194)
  .github/actions/install-build-tools/action.yml
Labels: backport, semver/none, target/34-x-y, 35-x-y

#47200 refactor: make `NativeWindow::has_frame_` const
  shell/browser/native_window.cc
  shell/browser/native_window.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47201 refactor: use `base::fixed_flat_set` in `NativeWindowViews::SetAlwaysOnTop()`
  shell/browser/native_window_views.cc
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47235 refactor: make `NativeWindow::pending_transitions_` a `base::queue` (35-x-y)
  shell/browser/native_window.h
Labels: backport, semver/patch, 35-x-y

#47226 fix: possible crash in `shell.readShortcutLink` (35-x-y)
  patches/chromium/.patches
  patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
  patches/chromium/ignore_parse_errors_for_resolveshortcutproperties.patch
Labels: backport, semver/patch, target/34-x-y, 35-x-y

#45538 feat: add menu item role `palette` and `header`
  docs/api/menu-item.md
  lib/browser/api/menu-item.ts
  lib/browser/api/menu.ts
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_menu.h
  shell/browser/ui/cocoa/electron_menu_controller.mm
  shell/browser/ui/electron_menu_model.cc
  shell/browser/ui/electron_menu_model.h
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, target/37-x-y

#47236 fix: `backgroundMaterial` on initial activate (35-x-y)
  patches/chromium/chore_modify_chromium_handling_of_mouse_events.patch
  patches/chromium/fix_activate_background_material_on_windows.patch
  patches/chromium/fix_take_snapped_status_into_account_when_showing_a_window.patch
Labels: backport, semver/patch, 35-x-y

#47243 chore: debug crash on DevTools SetOwnerWindow
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents.h
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47259 fix: regression with directory selection in macOS dialogs
  shell/browser/ui/file_dialog_mac.mm
Labels: semver/patch, target/35-x-y, target/36-x-y, target/37-x-y

#47269 chore: add .eslintrc.json for `docs/fiddles`
  docs/fiddles/.eslintrc.json
Labels: new-pr 🌱, semver/none, no-backport

#47274 chore: update @electron/lint-roller to 3.1.1
  .github/workflows/archaeologist-dig.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .markdownlint-cli2.jsonc
  package.json
  script/lint.js
  yarn.lock
Labels: backport, semver/none, 34-x-y

#47283 build: remove unnecessary eslint-plugin-standard package
  package.json
  yarn.lock
Labels: semver/none, no-backport

#47286 fix: crash due to incorrect debug scope information
  patches/v8/.patches
  patches/v8/debug_fix_crash_when_pausing_in_for-of_loop_header.patch
  patches/v8/parser_set_start_end_on_materialized_scopes.patch
Labels: semver/patch, backport-check-skip, 35-x-y

#47271 fix: Squirrel.Mac crash when zip extraction fails
  patches/squirrel.mac/.patches
  patches/squirrel.mac/fix_crash_when_process_to_extract_zip_cannot_be_launched.patch
  spec/api-autoupdater-darwin-spec.ts
  spec/fixtures/auto-update/sandbox/block-ditto.sb
Labels: semver/patch, target/34-x-y, target/35-x-y, target/36-x-y, target/37-x-y

#42113 chore: lint code blocks in docs with ESLint
  docs/.eslintrc.json
  docs/api/app.md
  docs/api/base-window.md
  docs/api/browser-window.md
  docs/api/command-line-switches.md
  docs/api/command-line.md
  docs/api/context-bridge.md
  docs/api/debugger.md
  docs/api/dialog.md
  docs/api/dock.md
  docs/api/download-item.md
  docs/api/extensions-api.md
  docs/api/message-channel-main.md
  docs/api/native-image.md
  docs/api/net.md
  docs/api/protocol.md
  docs/api/service-workers.md
  docs/api/session.md
  docs/api/structures/printer-info.md
  docs/api/structures/trace-config.md
  docs/api/system-preferences.md
  docs/api/view.md
  docs/api/web-contents-view.md
  docs/api/web-contents.md
  docs/api/web-frame.md
  docs/api/web-utils.md
  docs/api/webview-tag.md
  docs/development/creating-api.md
  docs/faq.md
  docs/tutorial/asar-archives.md
  docs/tutorial/automated-testing.md
  docs/tutorial/custom-title-bar.md
  docs/tutorial/custom-window-interactions.md
  docs/tutorial/dark-mode.md
  docs/tutorial/devtools-extension.md
  docs/tutorial/esm.md
  docs/tutorial/in-app-purchases.md
  docs/tutorial/ipc.md
  docs/tutorial/launch-app-from-url-in-another-app.md
  docs/tutorial/message-ports.md
  docs/tutorial/native-code-and-electron-objc-macos.md
  docs/tutorial/native-code-and-electron.md
  docs/tutorial/navigation-history.md
  docs/tutorial/performance.md
  docs/tutorial/process-model.md
  docs/tutorial/security.md
  docs/tutorial/tutorial-3-preload.md
  docs/tutorial/windows-taskbar.md
  package.json
  script/lint.js
  yarn.lock
Labels: semver/none, no-backport

#47293 build: drop shx dependency
  package.json
  script/cp.mjs
  yarn.lock
Labels: semver/none, no-backport

#47290 docs: document commit signing requirement
  docs/development/pull-requests.md
Labels: documentation :notebook:, semver/patch, no-backport

#47242 feat: expose `win.isContentProtected()`
  docs/api/base-window.md
  docs/api/browser-window.md
  shell/browser/api/electron_api_base_window.cc
  spec/api-browser-window-spec.ts
Labels: semver/minor, api-review/approved ✅, target/36-x-y, target/37-x-y

#42628 feat: [net] add "priority" option to net.request
  docs/api/client-request.md
  lib/common/api/net-client-request.ts
  shell/common/api/electron_api_url_loader.cc
  spec/api-net-spec.ts
  typings/internal-ambient.d.ts
Labels: semver/minor, api-review/approved ✅, target/36-x-y, target/37-x-y
