Repository electron/electron, pull requests merged in 2025-01, with the labels that each got.

#45127 chore: cherry-pick 3dc17c46 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-3dc17c461b12.patch
Labels: semver/patch, backport-check-skip, target/33-x-y, 34-x-y

#45086 fix: native module compilation with gcc<=8
  patches/v8/.patches
  patches/v8/fix_compiler_failure_on_older_clang.patch
Labels: semver/patch, backport-check-skip, 33-x-y

#45108 ci: enable debugging mode when building electron_dist_zip
  .github/actions/build-electron/action.yml
Labels: semver/none, no-backport

#45135 refactor: remove redundant CreateExtensionsClient()
  shell/renderer/renderer_client_base.cc
  shell/renderer/renderer_client_base.h
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#45143 perf: cache whether or not ELECTRON_DEBUG_NOTIFICATIONS env var is set
  shell/browser/notifications/mac/cocoa_notification.mm
  shell/browser/notifications/mac/notification_center_delegate.mm
  shell/browser/notifications/mac/notification_presenter_mac.mm
  shell/browser/notifications/notification.cc
  shell/browser/notifications/notification.h
  shell/browser/notifications/win/notification_presenter_win.cc
  shell/browser/notifications/win/windows_toast_notification.cc
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y

#45152 chore: cherry-pick 4 changes from 4-M131
  patches/chromium/.patches
  patches/chromium/cherry-pick-3a6ff45cc3f4.patch
  patches/chromium/cherry-pick-a51e7ebb7663.patch
  patches/v8/.patches
  patches/v8/cherry-pick-aad648bd2af9.patch
  patches/v8/cherry-pick-cb0d9e1d7b88.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45153 chore: cherry-pick 3 changes from 4-M131
  patches/chromium/.patches
  patches/chromium/cherry-pick-3a6ff45cc3f4.patch
  patches/chromium/cherry-pick-a51e7ebb7663.patch
  patches/v8/.patches
  patches/v8/cherry-pick-aad648bd2af9.patch
Labels: security 🔒, semver/patch, backport-check-skip, 31-x-y

#45167 docs: update timelines for E35
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/34-x-y

#45173 docs: correct breaking changes versions
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/none, target/34-x-y

#45189 docs: correct breaking changes versions
  docs/breaking-changes.md
Labels: backport, semver/none, 34-x-y

#45156 chore: cherry-pick 3 changes from 5-M131
  patches/chromium/.patches
  patches/chromium/cherry-pick-f3300abe2fcd.patch
  patches/v8/.patches
  patches/v8/merged_turboshaft_wasm_wasmgctypeanalyzer_fix_phi_input_for.patch
  patches/v8/merged_turboshaft_wasm_wasmgctypeanalyzer_fix_single-block_loops.patch
  patches/v8/merged_wasm_arm_tail-call_free_scratch_register_earlier.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45132 fix: only remove the 'v' prefix from the git tag name
  script/get-git-version.py
Labels: semver/none, no-backport

#45193 fix: revert required portal version for file chooser dialogs
  docs/api/command-line-switches.md
  docs/api/dialog.md
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
  shell/browser/ui/file_dialog_linux.cc
Labels: backport, semver/minor, api-review/approved ✅, 32-x-y

#45192 build: bump actions/cache past deprecated version
  .github/actions/checkout/action.yml
  .github/actions/install-dependencies/action.yml
  .github/actions/restore-cache-azcopy/action.yml
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y

#45145 build: bump NMV to 133
  build/args/all.gn
Labels: semver/none, no-backport

#45187 fix: `session.clearData` `avoidClosingConnections` default to false
  shell/browser/api/electron_api_session.cc
Labels: semver/patch, target/33-x-y, target/34-x-y

#45194 docs: remove quickstart
  docs/README.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/process-model.md
  docs/tutorial/quick-start.md
  docs/tutorial/windows-arm.md
  docs/tutorial/windows-taskbar.md
Labels: documentation :notebook:, semver/patch, target/35-x-y

#45191 docs: Why Electron?
  docs/why-electron.md
Labels: documentation :notebook:, semver/patch, no-backport

#45222 docs: Why Electron? (#45191)
  docs/why-electron.md
Labels: backport, semver/patch, 35-x-y

#45220 chore: cherry-pick 3 changes from 0-M132
  patches/chromium/.patches
  patches/chromium/cherry-pick-3a6ff45cc3f4.patch
  patches/chromium/cherry-pick-a51e7ebb7663.patch
  patches/chromium/cherry-pick-f3300abe2fcd.patch
  patches/chromium/remove_persistentmemoryallocator_getallocsize.patch
  patches/skia/.patches
  patches/skia/ganesh_avoid_overflow_when_combining_aahairlineops.patch
  patches/v8/.patches
  patches/v8/cherry-pick-aad648bd2af9.patch
  patches/v8/merged_interpreter_fix_hole_elision_scope_for_switch_jump_tables.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45219 chore: cherry-pick 3 changes from 0-M132
  patches/chromium/.patches
  patches/chromium/cherry-pick-35f86d6a0a03.patch
  patches/config.json
  patches/skia/.patches
  patches/skia/ganesh_avoid_overflow_when_combining_aahairlineops.patch
  patches/v8/.patches
  patches/v8/cherry-pick-3c2d220ad025.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45211 docs: Why Electron?
  docs/why-electron.md
Labels: backport, semver/patch, 34-x-y

#45227 docs: remove quickstart (#45194)
  docs/README.md
  docs/tutorial/keyboard-shortcuts.md
  docs/tutorial/process-model.md
  docs/tutorial/quick-start.md
  docs/tutorial/windows-arm.md
  docs/tutorial/windows-taskbar.md
Labels: backport, semver/patch, 34-x-y

#44628 refactor: remove InspectableWebContentsViewMac in favor of the Views version
  filenames.gni
  patches/chromium/.patches
  patches/chromium/fix_add_method_which_disables_headless_mode_on_native_widget.patch
  patches/chromium/fix_put_nsvisualeffectview_before_viewscompositorsuperview.patch
  shell/browser/api/electron_api_web_contents_view.cc
  shell/browser/native_window_mac.h
  shell/browser/native_window_mac.mm
  shell/browser/native_window_views.cc
  shell/browser/ui/cocoa/delayed_native_view_host.h
  shell/browser/ui/cocoa/delayed_native_view_host.mm
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/cocoa/electron_ns_window.h
  shell/browser/ui/cocoa/electron_ns_window.mm
  shell/browser/ui/cocoa/electron_ns_window_delegate.mm
  shell/browser/ui/inspectable_web_contents.cc
  shell/browser/ui/inspectable_web_contents_view.cc
  shell/browser/ui/inspectable_web_contents_view.h
  shell/browser/ui/inspectable_web_contents_view_mac.h
  shell/browser/ui/inspectable_web_contents_view_mac.mm
  shell/browser/ui/views/frameless_view.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.cc
  shell/browser/ui/views/inspectable_web_contents_view_views.h
Labels: semver/minor, api-review/approved ✅, target/35-x-y

#45234 fix: `getAsFileSystemHandle` failure when drag-dropping two directories
  shell/browser/file_system_access/file_system_access_permission_context.cc
  shell/browser/file_system_access/file_system_access_permission_context.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45239 test: quit Finder
  spec/api-browser-window-spec.ts
Labels: semver/none, no-backport

#45214 fix: broken OOP `window.print()` on macOS/Linux
  shell/utility/electron_content_utility_client.cc
Labels: semver/patch, target/35-x-y

#45233 fix: two possible FSA crashes
  shell/browser/file_system_access/file_system_access_permission_context.cc
Labels: semver/patch, target/34-x-y, target/35-x-y

#45218 fix: page scaling in silent mode printing
  patches/chromium/printing.patch
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45235 build: fix clang-format duplicate message
  script/run-clang-format.py
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y

#45249 build: remove useless patch files on 33-x-y branch
  patches/chromium/.patches
  patches/chromium/cherry-pick-f3300abe2fcd.patch
  patches/v8/.patches
  patches/v8/cherry-pick-0d3c44362eea.patch
Labels: semver/none

#45277 chore: align `clipboard blink::web_pref::WebPreferences` with upstream
  shell/browser/electron_browser_client.cc
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45252 ci: don't fail issue triage workflows if issue not found on project
  .github/workflows/branch-created.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-opened.yml
  .github/workflows/issue-transferred.yml
  .github/workflows/issue-unlabeled.yml
  .github/workflows/pull-request-labeled.yml
  .github/workflows/stable-prep-items.yml
Labels: semver/none, no-backport

#45266 fix: `webContents.print()` with OOP printing
  patches/chromium/printing.patch
Labels: semver/patch, target/35-x-y

#45267 fix: consume the file permission callback when used
  shell/browser/file_system_access/file_system_access_permission_context.cc
Labels: semver/patch, no-backport

#45269 refactor: simplify `ParseUserScript()`
  shell/browser/extensions/api/scripting/scripting_api.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45270 refactor: in `StopTracing()`, use string literals instead of `optional<string>`
  shell/browser/api/electron_api_content_tracing.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45294 ci: fix issue workflow failures
  .github/workflows/branch-created.yml
  .github/workflows/issue-labeled.yml
  .github/workflows/issue-opened.yml
  .github/workflows/issue-transferred.yml
  .github/workflows/issue-unlabeled.yml
  .github/workflows/pull-request-labeled.yml
  .github/workflows/stable-prep-items.yml
Labels: semver/none, no-backport

#45275 docs: add DocCardList component for index doc
  docs/tutorial/window-customization.md
Labels: documentation :notebook:, semver/patch, target/34-x-y, target/35-x-y

#45171 feat: support global shortcuts via GlobalShortcutsPortal feature with ozone/wayland
  docs/api/global-shortcut.md
  patches/chromium/.patches
  patches/chromium/check_for_unit_to_activate_before_notifying_about_success.patch
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_global_shortcut.h
  shell/browser/electron_browser_context.cc
  shell/common/electron_constants.h
Labels: semver/minor, api-review/requested 🗳, target/34-x-y, target/35-x-y

#45276 fix: potential crash in `chrome.tabs.update()`
  shell/browser/extensions/api/tabs/tabs_api.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45283 fix: page scaling in silent mode printing
  patches/chromium/add_didinstallconditionalfeatures.patch
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/can_create_window.patch
  patches/chromium/cherry-pick-1282289030ab.patch
  patches/chromium/cherry-pick-3dc17c461b12.patch
  patches/chromium/chore_partial_revert_of.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/disable_unload_metrics.patch
  patches/chromium/expose_setuseragent_on_networkcontext.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/fix_software_compositing_infinite_loop.patch
  patches/chromium/network_service_allow_remote_certificate_verification_logic.patch
  patches/chromium/notification_provenance.patch
  patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
  patches/chromium/printing.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/chromium/support_mixed_sandbox_with_zygote.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_fullscreen.patch
Labels: backport, semver/patch, 34-x-y

#45286 chore: better logging if Node initialization fails
  shell/app/node_main.cc
  shell/common/node_bindings.cc
  shell/common/node_util.cc
  shell/common/node_util.h
Labels: semver/patch, target/35-x-y

#45137 build: migrate Windows release builds to GHA
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/windows-publish.yml
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  script/release/bin/run-release-builds.ts
  script/release/run-release-ci-jobs.ts
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45241 docs: Add note about directly exposing Electron APIs in preload
  docs/tutorial/security.md
Labels: documentation :notebook:, semver/patch, target/34-x-y, target/35-x-y

#45230 feat: redesign preload APIs
  docs/api/session.md
  docs/api/structures/preload-script-registration.md
  docs/api/structures/preload-script.md
  docs/breaking-changes.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/session.ts
  lib/browser/rpc-server.ts
  lib/sandboxed_renderer/init.ts
  lib/sandboxed_renderer/pre-init.ts
  lib/sandboxed_renderer/preload.ts
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/preload_script.h
  shell/browser/session_preferences.cc
  shell/browser/session_preferences.h
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, api-review/skip-delay ⏰, target/35-x-y

#45229 feat: contextBridge.executeInMainWorld
  docs/api/context-bridge.md
  lib/renderer/api/context-bridge.ts
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_context_bridge.h
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/renderer_client_base.cc
  spec/api-context-bridge-spec.ts
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, api-review/skip-delay ⏰, target/35-x-y

#45232 feat: ServiceWorkerMain
  docs/README.md
  docs/api/service-worker-main.md
  docs/api/service-workers.md
  docs/api/structures/service-worker-info.md
  docs/breaking-changes.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/module-list.ts
  lib/browser/api/service-worker-main.ts
  lib/browser/init.ts
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_service_worker_context.h
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_service_worker_main.h
  shell/common/gin_converters/service_worker_converter.cc
  shell/common/gin_converters/service_worker_converter.h
  shell/common/node_bindings.cc
  spec/api-service-worker-main-spec.ts
  spec/fixtures/api/service-workers/index.html
  spec/fixtures/api/service-workers/sw-script-error.js
  spec/fixtures/api/service-workers/sw-unregister-self.js
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, api-review/skip-delay ⏰, target/35-x-y

#45332 docs: fix broken code in drag and drop example
  docs/tutorial/native-file-drag-drop.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, target/34-x-y, target/35-x-y

#45340 build: use windows builders for win-publish
  .github/workflows/windows-publish.yml
Labels: fast-track 🚅, semver/none

#45347 build: remove generate-sas-token
  .github/workflows/windows-publish.yml
Labels: semver/patch, fast-track 🚅, no-backport

#45195 fix: crash parsing CLSID in `shell.readShortcutLink()`
  patches/chromium/.patches
  patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
  shell/common/api/electron_api_shell.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45318 build: add `NSPrefersDisplaySafeAreaCompatibilityMode` = `false` to Info.plist
  shell/browser/resources/mac/Info.plist
Labels: semver/patch, target/35-x-y

#45360 build: use Python311 exe
  .github/actions/install-build-tools/action.yml
Labels: fast-track 🚅, semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45325 docs: reference security guide in `ipcRenderer.on` docs
  docs/api/ipc-renderer.md
Labels: documentation :notebook:, semver/patch, target/34-x-y, target/35-x-y

#45368 fix: crash in gin::wrappable::secondweakcallback
  patches/chromium/.patches
  patches/chromium/feat_add_signals_when_embedder_cleanup_callbacks_run_for.patch
  patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/message_port.cc
  shell/browser/api/message_port.h
  shell/browser/javascript_environment.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/gin_helper/cleaned_up_at_exit.cc
  shell/common/gin_helper/cleaned_up_at_exit.h
  shell/common/gin_helper/wrappable.cc
Labels: semver/patch, fast-track 🚅, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45355 build: fixup concurrent builds on protected branches
  .github/workflows/pipeline-electron-build-and-test-and-nan.yml
  .github/workflows/pipeline-electron-build-and-test.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45378 fix: crash in gin::wrappable::secondweakcallback
  patches/chromium/.patches
  patches/chromium/feat_add_signals_when_embedder_cleanup_callbacks_run_for.patch
  patches/chromium/printing.patch
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/message_port.cc
  shell/browser/api/message_port.h
  shell/browser/javascript_environment.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/gin_helper/cleaned_up_at_exit.cc
  shell/common/gin_helper/cleaned_up_at_exit.h
  shell/common/gin_helper/wrappable.cc
Labels: backport, semver/patch, 35-x-y

#45379 fix: crash in gin::wrappable::secondweakcallback
  patches/chromium/.patches
  patches/chromium/cherry-pick-35f86d6a0a03.patch
  patches/chromium/feat_add_signals_when_embedder_cleanup_callbacks_run_for.patch
  patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
  patches/skia/ganesh_avoid_overflow_when_combining_aahairlineops.patch
  patches/v8/cherry-pick-3c2d220ad025.patch
  shell/browser/api/electron_api_notification.cc
  shell/browser/api/electron_api_notification.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_tray.h
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/message_port.cc
  shell/browser/api/message_port.h
  shell/browser/javascript_environment.cc
  shell/common/api/electron_api_url_loader.cc
  shell/common/api/electron_api_url_loader.h
  shell/common/gin_helper/cleaned_up_at_exit.cc
  shell/common/gin_helper/cleaned_up_at_exit.h
  shell/common/gin_helper/wrappable.cc
Labels: backport, semver/patch, 33-x-y

#45370 chore: update `pdf_viewer_private.idl`
  shell/common/extensions/api/pdf_viewer_private.idl
Labels: semver/patch, no-backport

#45369 chore: update `chrome.scripting.execute` logic
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/scripting/scripting_api.h
Labels: semver/patch, no-backport

#45373 fix: multiple directory selection on Linux
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Labels: semver/patch, target/34-x-y, target/35-x-y

#45393 build: try removing `Read/WriteBarrier` patch
  patches/node/.patches
  patches/node/fix_readbarrier_undefined_symbol_error_on_woa_arm64.patch
Labels: semver/none, no-backport

#45388 build: fix `slack-github-action` for backports
  .github/workflows/pull-request-labeled.yml
Labels: semver/none, target/34-x-y, target/35-x-y

#45341 feat: ServiceWorkerMain
  docs/README.md
  docs/api/service-worker-main.md
  docs/api/service-workers.md
  docs/api/structures/service-worker-info.md
  docs/breaking-changes.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/module-list.ts
  lib/browser/api/service-worker-main.ts
  lib/browser/init.ts
  shell/browser/api/electron_api_service_worker_context.cc
  shell/browser/api/electron_api_service_worker_context.h
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_service_worker_main.h
  shell/common/gin_converters/service_worker_converter.cc
  shell/common/gin_converters/service_worker_converter.h
  shell/common/node_bindings.cc
  spec/api-service-worker-main-spec.ts
  spec/fixtures/api/service-workers/index.html
  spec/fixtures/api/service-workers/sw-script-error.js
  spec/fixtures/api/service-workers/sw-unregister-self.js
  typings/internal-ambient.d.ts
  typings/internal-electron.d.ts
Labels: backport, semver/minor, backport/requested 🗳, 35-x-y

#44999 feat: view.getVisible()
  docs/api/view.md
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_view.h
  spec/api-view-spec.ts
Labels: semver/minor, api-review/approved ✅, target/34-x-y, target/35-x-y
