Repository electron/electron, pull requests merged in 2025-02, with the labels that each got.

#45402 fix: default path not working on KDE Linux
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45405 fix: incorrect WCO tooltip in RTL
  shell/browser/ui/views/win_caption_button_container.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45401 build: remove outdated Node.js serdes patch
  patches/node/.patches
  patches/node/fix_serdes_test.patch
Labels: semver/none, target/34-x-y, target/35-x-y

#45430 build: remove outdated Node.js serdes patch
  patches/node/.patches
  patches/node/fix_serdes_test.patch
Labels: backport, semver/none, 35-x-y

#45400 build: always use python3 in `script/lib/get-version.js`
  .github/workflows/pipeline-segment-electron-test.yml
  script/lib/get-version.js
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45413 docs: mention C++20 requirement in breaking changes document
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, target/34-x-y, target/35-x-y

#45412 docs: document deletion of `databases` directory
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45380 build: add win toolchain for release builds
  .github/actions/build-electron/action.yml
  script/lib/config.py
Labels: semver/none

#45429 build: try removing embedder exception patch
  patches/node/.patches
  patches/node/fix_capture_embedder_exceptions_before_entering_v8.patch
Labels: semver/patch, target/34-x-y, target/35-x-y

#45465 build: migrate Windows release builds to GHA
  .github/actions/build-electron/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/windows-publish.yml
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  script/lib/config.py
  script/release/bin/run-release-builds.ts
  script/release/run-release-ci-jobs.ts
Labels: backport, semver/none, 35-x-y

#45466 build: migrate Windows release builds to GHA
  .github/actions/build-electron/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/windows-publish.yml
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  script/lib/config.py
  script/release/bin/run-release-builds.ts
  script/release/run-release-ci-jobs.ts
Labels: backport, semver/none, 34-x-y

#45467 build: migrate Windows release builds to GHA
  .github/actions/build-electron/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/windows-publish.yml
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  script/lib/config.py
  script/release/bin/run-release-builds.ts
  script/release/run-release-ci-jobs.ts
Labels: backport, semver/none, 33-x-y

#45468 build: migrate Windows release builds to GHA
  .github/actions/build-electron/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/windows-publish.yml
  appveyor-bake.yml
  appveyor-woa.yml
  appveyor.yml
  script/lib/config.py
  script/release/bin/run-release-builds.ts
  script/release/run-release-ci-jobs.ts
Labels: backport, semver/none, 32-x-y

#45377 feat: route deprecated sync clipboard read through permission checks
  BUILD.gn
  docs/api/session.md
  docs/api/structures/web-preferences.md
  docs/breaking-changes.md
  patches/chromium/.patches
  patches/chromium/build_allow_electron_mojom_interfaces_to_depend_on_blink.patch
  patches/chromium/feat_separate_content_settings_callback_for_sync_and_async_clipboard.patch
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/web_contents_permission_helper.h
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/BUILD.gn
  shell/common/api/api.mojom
  shell/common/gin_converters/content_converter.cc
  shell/common/options_switches.h
  shell/common/web_contents_utility.mojom
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/content_settings_observer.cc
  shell/renderer/content_settings_observer.h
  shell/renderer/electron_api_service_impl.h
  shell/renderer/electron_render_frame_observer.cc
  spec/chromium-spec.ts
Labels: semver/minor, new-pr 🌱, api-review/requested 🗳, target/33-x-y, target/34-x-y, target/35-x-y

#45457 build: remove debugger agent timeout patch
  patches/node/.patches
  patches/node/fix_account_for_debugger_agent_race_condition.patch
Labels: semver/patch, no-backport

#45454 fix: handle exclude aliasing in InclusionStatusToString()
  shell/browser/api/electron_api_cookies.cc
Labels: semver/patch, target/34-x-y, target/35-x-y

#45421 fix: `legacyMainResolve` respecting permission model
  patches/node/fix_revert_src_lb_reducing_c_calls_of_esm_legacy_main_resolve.patch
  script/node-disabled-tests.json
Labels: semver/patch, no-backport

#45422 fix: WCO not working with some window configurations
  shell/browser/native_window_views.cc
  shell/browser/ui/views/win_caption_button_container.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45437 fix: fix typo in docs why-electron.md
  docs/why-electron.md
Labels: documentation :notebook:, semver/patch, no-backport

#45473 feat: route deprecated sync clipboard read through permission checks
  BUILD.gn
  docs/api/session.md
  docs/api/structures/web-preferences.md
  docs/breaking-changes.md
  patches/chromium/.patches
  patches/chromium/build_allow_electron_mojom_interfaces_to_depend_on_blink.patch
  patches/chromium/feat_separate_content_settings_callback_for_sync_and_async_clipboard.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/web_contents_permission_helper.h
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/BUILD.gn
  shell/common/api/api.mojom
  shell/common/gin_converters/content_converter.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/common/web_contents_utility.mojom
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/content_settings_observer.cc
  shell/renderer/content_settings_observer.h
  shell/renderer/electron_api_service_impl.h
  shell/renderer/electron_render_frame_observer.cc
  spec/chromium-spec.ts
Labels: backport, semver/minor, backport/requested 🗳, 33-x-y

#45472 feat: route deprecated sync clipboard read through permission checks
  BUILD.gn
  docs/api/session.md
  docs/api/structures/web-preferences.md
  docs/breaking-changes.md
  patches/chromium/.patches
  patches/chromium/build_allow_electron_mojom_interfaces_to_depend_on_blink.patch
  patches/chromium/feat_separate_content_settings_callback_for_sync_and_async_clipboard.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_browser_client.cc
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/browser/web_contents_permission_helper.h
  shell/browser/web_contents_preferences.cc
  shell/browser/web_contents_preferences.h
  shell/common/BUILD.gn
  shell/common/api/api.mojom
  shell/common/gin_converters/content_converter.cc
  shell/common/options_switches.cc
  shell/common/options_switches.h
  shell/common/web_contents_utility.mojom
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/content_settings_observer.cc
  shell/renderer/content_settings_observer.h
  shell/renderer/electron_api_service_impl.h
  shell/renderer/electron_render_frame_observer.cc
  spec/chromium-spec.ts
Labels: backport, semver/minor, backport/approved ✅, 34-x-y

#45458 docs: style fixes
  docs/api/structures/base-window-options.md
  docs/api/structures/display.md
Labels: documentation :notebook:, semver/patch, target/35-x-y

#45431 build: remove outdated Node.js serdes patch
  patches/node/.patches
  patches/node/fix_serdes_test.patch
Labels: backport, semver/none, 34-x-y

#45397 docs: use correct headings in tutorial/security.md
  docs/tutorial/security.md
Labels: documentation :notebook:, semver/patch, no-backport

#45495 chore: cherry-pick dd8e2822e507 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-dd8e2822e507.patch
Labels: semver/patch, backport-check-skip, main

#45497 chore: cherry-pick dd8e2822e507 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-dd8e2822e507.patch
Labels: semver/patch, backport-check-skip, 34-x-y

#45496 chore: cherry-pick dd8e2822e507 from chromium
  patches/chromium/.patches
  patches/chromium/cherry-pick-dd8e2822e507.patch
Labels: semver/patch, backport-check-skip, 35-x-y

#45484 refactor: only pass `v8::Context` to `gin_helper::MicrotasksScope` constructor
  shell/browser/api/electron_api_auto_updater.cc
  shell/common/api/electron_bindings.cc
  shell/common/gin_helper/callback.h
  shell/common/gin_helper/event_emitter_caller.cc
  shell/common/gin_helper/function_template.h
  shell/common/gin_helper/microtasks_scope.cc
  shell/common/gin_helper/microtasks_scope.h
  shell/common/gin_helper/promise.cc
  shell/common/node_bindings.cc
  shell/common/v8_util.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_render_frame_observer.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45502 fix: Update widget visibility in `NativeWindowMac::ShowInactive`
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.h
  shell/browser/ui/cocoa/electron_ns_window.mm
Labels: backport, semver/patch, backport-check-skip, 35-x-y

#45487 fix: RenderFrameHost nullptr dereference
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45506 chore: bump chromium 134.0.6989.0
  DEPS
  patches/chromium/blink_local_frame.patch
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/can_create_window.patch
  patches/chromium/cherry-pick-dd8e2822e507.patch
  patches/chromium/chore_partial_revert_of.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/desktop_media_list.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/feat_separate_content_settings_callback_for_sync_and_async_clipboard.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/fix_restore_original_resize_performance_on_macos.patch
  patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
  patches/chromium/gritsettings_resource_ids.patch
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  patches/chromium/notification_provenance.patch
  patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/chromium/support_mixed_sandbox_with_zygote.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_fullscreen.patch
Labels: semver/patch, new-pr 🌱, roller/pause, no-backport

#45331 docs: remove width and height params
  docs/tutorial/online-offline-events.md
Labels: semver/none, no-backport

#45501 build: make sure there is at least 35GB free for source cache
  .github/actions/checkout/action.yml
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y

#45339 chore: remove remaining references to AppVeyor
  .env.example
  .github/CODEOWNERS
  .github/workflows/update_appveyor_image.yml
  README.md
  script/prepare-appveyor.js
  script/release/bin/README.md
  script/release/bin/run-release-builds.ts
  script/setup-win-for-dev.bat
  spec/logging-spec.ts
  spec/package.json
  spec/yarn.lock
Labels: semver/none, no-backport

#45507 chore: bump chromium 134.0.6990.0
  DEPS
  patches/chromium/add_electron_deps_to_license_credits_file.patch
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/can_create_window.patch
  patches/chromium/cherry-pick-dd8e2822e507.patch
  patches/chromium/chore_introduce_blocking_api_for_electron.patch
  patches/chromium/chore_partial_revert_of.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/feat_add_support_for_missing_dialog_features_to_shell_dialogs.patch
  patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/fix_restore_original_resize_performance_on_macos.patch
  patches/chromium/frame_host_manager.patch
  patches/chromium/gritsettings_resource_ids.patch
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
  patches/chromium/printing.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/chromium/resource_file_conflict.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_fullscreen.patch
Labels: semver/patch, roller/pause, backport-check-skip, no-backport

#45498 refactor: follow upstream's suggestions on when to use EmptyGURL()
  shell/browser/api/electron_api_service_worker_main.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/extensions/api/management/electron_management_api_delegate.cc
Labels: semver/patch, target/35-x-y

#45427 fix: Update widget visibility in `NativeWindowMac::ShowInactive`
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.h
  shell/browser/ui/cocoa/electron_ns_window.mm
Labels: semver/patch, merged/35-x-y

#45456 fix: window maximizing with Mica
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/native_window_views_win.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45528 chore: clean up web secure context patch
  patches/chromium/cherry-pick-dd8e2822e507.patch
Labels: backport-check-skip, semver/none, 34-x-y

#45489 refactor: use `node::tracing::Agent()` directly
  patches/node/.patches
  patches/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
  shell/browser/javascript_environment.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: semver/patch, target/34-x-y, target/35-x-y

#45527 docs: `transactions-updated` event type
  docs/api/in-app-purchase.md
Labels: documentation :notebook:, semver/patch, target/35-x-y

#45488 fix: fix mksnapshot gen/v8 path
  .github/actions/build-electron/action.yml
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45435 test: make sure test window is on top for focus tests
  spec/chromium-spec.ts
  spec/lib/screen-helpers.ts
Labels: semver/none, target/35-x-y

#45434 chore: deprecate `systemPreferences.isAeroGlassEnabled()`
  docs/api/system-preferences.md
  docs/breaking-changes.md
  lib/browser/api/system-preferences.ts
  shell/browser/api/electron_api_system_preferences.cc
  shell/browser/api/electron_api_system_preferences.h
  shell/browser/api/electron_api_system_preferences_win.cc
  spec/api-system-preferences-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: semver/minor, api-review/approved ✅, deprecation-review/complete ✅, target/35-x-y

#45549 fix: context-menu emitted twice
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.h
  shell/browser/ui/cocoa/electron_inspectable_web_contents_view.mm
  shell/browser/ui/cocoa/electron_ns_window.mm
  spec/api-web-contents-spec.ts
Labels: backport, semver/patch, target/32-x-y, 33-x-y

#45499 fix: avoid IPC for renderer `webFrame.getZoom...` APIs
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/electron_web_contents_utility_handler_impl.cc
  shell/browser/electron_web_contents_utility_handler_impl.h
  shell/common/web_contents_utility.mojom
  shell/renderer/api/electron_api_web_frame.cc
  spec/api-web-frame-spec.ts
Labels: semver/patch, target/35-x-y

#45522 docs: fix grammar in preload tutorial summary
  docs/tutorial/tutorial-3-preload.md
Labels: documentation :notebook:, semver/patch, target/35-x-y

#45541 fix: asan build on macOS
  patches/node/.patches
  patches/node/build_remove_explicit_linker_call_to_libm_on_macos.patch
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45556 build: make gen-libc++-filenames.js produce the same results on Windows
  script/gen-libc++-filenames.js
Labels: semver/none, target/34-x-y, target/35-x-y

#45433 feat: Restore webContents navigation history and page state
  docs/api/navigation-history.md
  docs/api/structures/navigation-entry.md
  docs/tutorial/navigation-history.md
  lib/browser/api/web-contents.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  spec/api-web-contents-spec.ts
  typings/internal-electron.d.ts
Labels: semver/minor, api-review/approved ✅, needs-docs, target/34-x-y, target/35-x-y

#45564 chore: bump chromium to 134.0.6998.10 (main)
  DEPS
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  shell/browser/api/electron_api_cookies.cc
  shell/browser/browser_process_impl.h
  shell/browser/electron_pdf_document_helper_client.h
  shell/browser/extensions/electron_extension_loader.cc
  shell/browser/native_window_views.cc
  shell/browser/native_window_views.h
  shell/browser/osr/osr_video_consumer.cc
  shell/browser/ui/message_box_win.cc
  shell/browser/ui/win/notify_icon.cc
  shell/browser/ui/win/notify_icon.h
  shell/browser/ui/win/taskbar_host.cc
  shell/common/api/electron_api_native_image.cc
  shell/common/api/electron_api_native_image.h
  shell/common/api/electron_api_native_image_win.cc
  spec/api-content-tracing-spec.ts
Labels: semver/patch, roller/pause, backport-check-skip, target/35-x-y

#45553 test: disable unexpectedly quit dialog on macOS
  .github/workflows/pipeline-segment-electron-test.yml
Labels: semver/none, target/35-x-y

#45587 fix: misc-use-internal-linkage warnings (32-x-y)
  shell/browser/api/electron_api_menu.cc
  shell/browser/api/electron_api_utility_process.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/extensions/electron_extension_system.cc
  shell/browser/printing/printing_utils.cc
  shell/common/gin_converters/blink_converter.cc
  shell/common/platform_util.cc
  shell/common/skia_util.cc
  shell/renderer/api/electron_api_context_bridge.cc
Labels: backport, semver/patch, 32-x-y

#45535 chore: remove var declarations from DEPS that no longer have any effect
  DEPS
Labels: semver/none, no-backport

#45581 build: set chromium cookie on depot tools requests
  .github/actions/checkout/action.yml
  .github/actions/set-chromium-cookie/action.yml
  .github/workflows/build.yml
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y

#45333 docs: added missing period for consistency and readability
  CONTRIBUTING.md
Labels: documentation :notebook:, semver/patch, no-backport

#45604 build: remove PDF edited saved files patch
  patches/chromium/.patches
  patches/chromium/fix_crash_when_saving_edited_pdf_files.patch
Labels: semver/none, target/35-x-y

#45615 docs: fix powerMonitor event types (34-x-y)
  docs/api/power-monitor.md
Labels: documentation :notebook:, backport, semver/patch, target/32-x-y, target/33-x-y, 34-x-y

#45608 refactor: fix modernize-return-braced-init-list warnings (32-x-y)
  shell/browser/api/electron_api_app.cc
  shell/browser/api/electron_api_cookies.cc
  shell/browser/api/electron_api_crash_reporter.cc
  shell/browser/api/electron_api_net_log.cc
  shell/browser/api/electron_api_safe_storage.cc
  shell/browser/api/electron_api_screen.cc
  shell/browser/api/electron_api_tray.cc
  shell/browser/api/electron_api_view.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/browser_linux.cc
  shell/browser/electron_browser_client.cc
  shell/browser/electron_browser_main_parts.cc
  shell/browser/electron_permission_manager.cc
  shell/browser/extensions/electron_extensions_browser_client.cc
  shell/browser/javascript_environment.cc
  shell/browser/native_window.cc
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/printing/printing_utils.cc
  shell/browser/ui/autofill_popup.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/tray_icon.cc
  shell/browser/ui/views/client_frame_view_linux.cc
  shell/browser/ui/views/opaque_frame_view.cc
  shell/browser/web_contents_permission_helper.cc
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_api_native_image.cc
  shell/common/extensions/electron_extensions_client.cc
  shell/common/gin_helper/wrappable.cc
  shell/common/node_util.cc
  shell/renderer/api/electron_api_web_frame.cc
  shell/renderer/printing/print_render_frame_helper_delegate.cc
Labels: backport, semver/patch, 32-x-y

#45611 chore: change node test timeout from 20m to 30m
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: fast-track 🚅, semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45620 refactor: use node::tracing::Agent() directly (34-x-y)
  patches/chromium/can_create_window.patch
  patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
  patches/chromium/webview_fullscreen.patch
  patches/node/.patches
  patches/node/build_ensure_native_module_compilation_fails_if_not_using_a_new.patch
  patches/node/fix_assert_module_in_the_renderer_process.patch
  patches/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
  patches/node/src_remove_dependency_on_wrapper-descriptor-based_cppheap.patch
  patches/node/support_v8_sandboxed_pointers.patch
  shell/browser/javascript_environment.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: backport, semver/patch, 34-x-y

#45612 chore: disable flaky content tracing tests on Linux
  spec/api-content-tracing-spec.ts
Labels: fast-track 🚅, semver/none, no-backport

#45574 fix: pointer lock permission after focus loss and regain
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
Labels: semver/patch, target/34-x-y, target/35-x-y

#45573 fix: osr crash on window close
  shell/browser/osr/osr_render_widget_host_view.cc
  shell/browser/osr/osr_render_widget_host_view.h
Labels: semver/patch, target/34-x-y, target/35-x-y

#45619 refactor: use node::tracing::Agent() directly (35-x-y)
  patches/node/.patches
  patches/node/build_ensure_native_module_compilation_fails_if_not_using_a_new.patch
  patches/node/fix_assert_module_in_the_renderer_process.patch
  patches/node/fix_expose_tracing_agent_and_use_tracing_tracingcontroller_instead.patch
  patches/node/src_remove_dependency_on_wrapper-descriptor-based_cppheap.patch
  patches/node/support_v8_sandboxed_pointers.patch
  shell/browser/javascript_environment.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/web_worker_observer.cc
Labels: backport, semver/patch, 35-x-y

#45631 build: make sure chromium cookie is set everywhere
  .github/workflows/pipeline-electron-lint.yml
  .github/workflows/pipeline-segment-node-nan-test.yml
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45645 fix: support for v8.setHeapSnapshotNearHeapLimit api
  docs/api/command-line-switches.md
  shell/browser/electron_browser_main_parts.cc
  shell/browser/javascript_environment.cc
  shell/browser/javascript_environment.h
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_renderer_client.cc
  shell/services/node/node_service.cc
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/oom-grow.js
Labels: backport, semver/patch, 33-x-y

#45644 fix: support for v8.setHeapSnapshotNearHeapLimit api
  docs/api/command-line-switches.md
  shell/browser/electron_browser_main_parts.cc
  shell/browser/javascript_environment.cc
  shell/browser/javascript_environment.h
  shell/common/node_bindings.cc
  shell/common/node_bindings.h
  shell/renderer/electron_renderer_client.cc
  shell/services/node/node_service.cc
  spec/api-utility-process-spec.ts
  spec/fixtures/api/utility-process/oom-grow.js
Labels: backport, semver/patch, 34-x-y

#45652 build: run source cache clean daily
  .github/workflows/clean-src-cache.yml
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y

#44692 feat: add excludeUrls and modify urls in WebRequestFilter for better URL filtering
  docs/api/structures/web-request-filter.md
  docs/api/web-request.md
  docs/breaking-changes.md
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/electron_api_web_request.h
  spec/api-web-request-spec.ts
Labels: semver/minor, api-review/approved ✅, target/35-x-y

#45572 fix: osr stutter fix backport for electron.
  patches/chromium/.patches
  patches/chromium/fix_osr_stutter_in_both_cpu_and_gpu_capture_when_page_has_animation.patch
Labels: semver/patch, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45452 refactor: dispatch IPC messages from Session
  lib/browser/api/session.ts
  lib/browser/api/web-contents.ts
  lib/browser/guest-view-manager.ts
  lib/browser/ipc-dispatch.ts
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/browser/api/ipc_dispatcher.h
  shell/browser/electron_api_ipc_handler_impl.cc
  shell/browser/electron_api_ipc_handler_impl.h
  shell/browser/electron_api_sw_ipc_handler_impl.cc
  shell/browser/electron_api_sw_ipc_handler_impl.h
Labels: semver/none, no-backport

#45319 fix: win.closeFilePreview recreates panel when called twice
  shell/browser/native_window_mac.mm
  spec/api-browser-window-spec.ts
Labels: semver/none, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45681 chore: disable 'should lock the keyboard' test on macOS
  spec/chromium-spec.ts
Labels: ci-flake ⭕️, fast-track 🚅, semver/none, target/35-x-y

#45563 chore: remove deprecated `systemPreferences.isAeroGlassEnabled()`
  docs/api/system-preferences.md
  docs/breaking-changes.md
  lib/browser/api/system-preferences.ts
  spec/api-system-preferences-spec.ts
  spec/ts-smoke/electron/main.ts
Labels: semver/major, api-review/approved ✅, no-backport, deprecation-review/complete ✅, api-review/skip-delay ⏰

#45688 fix: dangling speculative frames
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_converters/std_converter.h
  spec/api-web-frame-main-spec.ts
  typings/internal-electron.d.ts
Labels: backport, semver/patch, 33-x-y

#45683 build: remove appveyor bake
  .github/workflows/update_appveyor_image.yml
  script/prepare-appveyor.js
Labels: backport, semver/none, 34-x-y

#45698 fix: extension web workers net request failing
  shell/browser/electron_browser_client.cc
Labels: semver/patch, new-pr 🌱, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45687 fix: dangling speculative frames
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_frame_main.h
  shell/common/gin_converters/std_converter.h
  spec/api-web-frame-main-spec.ts
  typings/internal-electron.d.ts
Labels: backport, semver/patch, 34-x-y

#45684 build: remove appveyor bake
  .github/workflows/update_appveyor_image.yml
  script/prepare-appveyor.js
Labels: backport, semver/none, 33-x-y

#45675 refactor: track downloads by guid
  shell/browser/electron_download_manager_delegate.cc
  shell/browser/electron_download_manager_delegate.h
Labels: semver/patch, target/34-x-y, target/35-x-y

#45697 fix: action.openPopup function missing
  shell/browser/extensions/api/extension_action/extension_action_api.cc
Labels: new-pr 🌱, semver/none, no-backport

#45715 chore: fix broken patches in 33-x-y
  patches/chromium/fix_osr_stutter_in_both_cpu_and_gpu_capture_when_page_has_animation.patch
Labels: semver/patch, fast-track 🚅, no-backport

#45690 fix: possible timing issue in utility-process spec
  spec/fixtures/api/utility-process/log.js
Labels: semver/patch, ci-flake ⭕️, target/32-x-y, target/33-x-y, target/34-x-y, target/35-x-y

#45721 chore: cherry-pick 1 changes from 2-M133
  patches/v8/.patches
  patches/v8/merged_reland_lower_the_maximum_js_parameter_count.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45720 chore: cherry-pick 1 changes from 2-M133
  patches/v8/.patches
  patches/v8/merged_reland_lower_the_maximum_js_parameter_count.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45694 fix: crash loading `about:blank` in subframes
  patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
  spec/api-subframe-spec.ts
Labels: semver/patch, target/35-x-y

#45735 build: skip chromium git cookie on forks
  .github/actions/set-chromium-cookie/action.yml
Labels: semver/none, target/33-x-y, target/34-x-y, target/35-x-y

#45594 feat: allow setting `roundedCorners` on Windows
  docs/api/structures/base-window-options.md
  shell/browser/native_window_views.cc
Labels: semver/minor, api-review/approved ✅, target/34-x-y, target/35-x-y

#45671 refactor: bluetooth in serial chooser when exclusively wireless serial ports are expected
  shell/browser/serial/serial_chooser_controller.cc
  shell/browser/serial/serial_chooser_controller.h
Labels: semver/patch, target/34-x-y, target/35-x-y

#45722 refactor: use base::as_string_view()
  shell/browser/api/electron_api_debugger.cc
  shell/browser/ui/inspectable_web_contents.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45724 refactor: use `base::as_bytes()` in `WriteAsciiChunk()`
  shell/common/heap_snapshot.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45723 refactor: use base::as_byte_span() in EncodeToken().
  shell/browser/serial/serial_chooser_context.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45733 fix: crash on `getUserMedia` with invalid `chromeMediaSourceId`
  shell/browser/web_contents_permission_helper.cc
  spec/api-media-handler-spec.ts
Labels: semver/patch, target/34-x-y, target/35-x-y

#45741 refactor: use base's map utills in WebFrameMain
  shell/browser/api/electron_api_web_frame_main.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45712 fix: re-enable synchronous spellcheck on Windows
  patches/chromium/.patches
  patches/chromium/fix_win32_synchronous_spellcheck.patch
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_contents.h
  shell/common/gin_converters/content_converter.cc
  shell/common/gin_converters/content_converter.h
Labels: semver/patch, target/35-x-y

#45742 refactor: use C++20's contains() method
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_power_save_blocker.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/message_box_mac.mm
  shell/browser/ui/message_box_win.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/common/api/electron_api_clipboard.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45616 docs: clarify navigationhistory offsets
  docs/api/navigation-history.md
Labels: documentation :notebook:, semver/patch, target/34-x-y, target/35-x-y

#45597 refactor: move extension APIs to session.extensions
  docs/api/extensions-api.md
  docs/api/extensions.md
  docs/api/session.md
  docs/breaking-changes.md
  docs/tutorial/devtools-extension.md
  filenames.auto.gni
  filenames.gni
  lib/browser/api/session.ts
  shell/browser/api/electron_api_extensions.cc
  shell/browser/api/electron_api_extensions.h
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_session.h
  spec/api-service-worker-main-spec.ts
  spec/extensions-spec.ts
Labels: semver/minor, api-review/approved ✅, no-backport

#45768 refactor: use C++20's contains() method (35-x-y)
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_power_save_blocker.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/message_box_mac.mm
  shell/browser/ui/message_box_win.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/common/api/electron_api_clipboard.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: backport, semver/patch, 35-x-y

#45754 fix: rework and improve `legacyMainResolve` patch
  patches/node/.patches
  patches/node/fix_allow_passing_fileexists_fn_to_legacymainresolve.patch
  patches/node/fix_revert_src_lb_reducing_c_calls_of_esm_legacy_main_resolve.patch
  patches/node/src_stop_using_deprecated_fields_of_fastapicallbackoptions.patch
  script/node-disabled-tests.json
Labels: semver/patch, target/35-x-y

#45392 docs: added upstream doc links for node, chromium, and v8 in default_app
  default_app/preload.ts
Labels: documentation :notebook:, semver/patch, no-backport

#45758 fix: crash loading `about:blank` in subframes (35-x-y)
  patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
  patches/chromium/ignore_parse_errors_for_pkey_appusermodel_toastactivatorclsid.patch
  patches/node/build_remove_explicit_linker_call_to_libm_on_macos.patch
  spec/api-subframe-spec.ts
Labels: backport, semver/patch, 35-x-y

#45767 fix: drag and drop icons on Windows
  patches/chromium/.patches
  patches/chromium/fix_drag_and_drop_icons_on_windows.patch
Labels: semver/patch, target/34-x-y, target/35-x-y

#45669 feat: remove osr framerate limit when use shared texture
  docs/tutorial/offscreen-rendering.md
  shell/browser/osr/osr_render_widget_host_view.cc
Labels: semver/patch, target/35-x-y

#45771 refactor: do not use `AdaptCallbackForRepeating()` in `electron_api_url_loader.cc`
  shell/common/api/electron_api_url_loader.cc
  shell/common/gin_helper/event_emitter_caller.h
Labels: semver/patch, upgrade-follow-up, target/33-x-y, target/34-x-y, target/35-x-y

#45779 revert: drag and drop icons on Windows
  patches/chromium/.patches
  patches/chromium/fix_drag_and_drop_icons_on_windows.patch
Labels: fast-track 🚅, semver/none, no-backport

#45773 refactor: remove unused `v8::Isolate*` arg from `GlobalShortcut` constructor
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_global_shortcut.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45770 build: re-enable unsafe buffer checks
  build/args/all.gn
  patches/chromium/.patches
  patches/chromium/chore_remove_conflicting_allow_unsafe_libc_calls.patch
Labels: security 🔒, semver/patch, upgrade-follow-up, target/35-x-y

#45775 fix: re-enable MacWebContentsOcclusion feature flag
  patches/chromium/revert_code_health_clean_up_stale_macwebcontentsocclusion.patch
  shell/browser/feature_list.cc
Labels: semver/patch, target/35-x-y

#45701 chore: cherry-pick 1 changes from 2-M132
  patches/v8/.patches
  patches/v8/cherry-pick-8131c09bc129.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45699 chore: cherry-pick 3 changes from 1-M132
  patches/v8/.patches
  patches/v8/cherry-pick-9209292e7898.patch
  patches/v8/cherry-pick-97e828af5cbc.patch
  patches/v8/cherry-pick-ca504d096c39.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45786 perf: avoid redundant method calls in EventEmitter
  shell/common/gin_helper/event_emitter.h
Labels: semver/patch, no-backport

#45793 refactor: remove unused gin_helper::WrappableBase::GetWrapper(v8::Isolate*)
  shell/common/gin_helper/wrappable.cc
  shell/common/gin_helper/wrappable_base.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45700 chore: cherry-pick 3 changes from 1-M132
  patches/v8/.patches
  patches/v8/cherry-pick-9209292e7898.patch
  patches/v8/cherry-pick-97e828af5cbc.patch
  patches/v8/cherry-pick-ca504d096c39.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45704 chore: cherry-pick 1 changes from 0-M133
  .gitattributes
  patches/chromium/.patches
  patches/chromium/reland_lzma_sdk_update_to_24_09.patch
Labels: security 🔒, semver/patch, backport-check-skip, 34-x-y

#45803 refactor: simplify Invoker::IsOK()
  shell/common/gin_helper/function_template.h
Labels: semver/patch, target/33-x-y, target/34-x-y, target/35-x-y

#45831 docs: dialog.md - typo fix s/wndow/window/
  docs/api/dialog.md
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#45814 refactor: use C++20's contains() method
  shell/browser/api/electron_api_base_window.cc
  shell/browser/api/electron_api_global_shortcut.cc
  shell/browser/api/electron_api_power_save_blocker.cc
  shell/browser/api/electron_api_protocol.cc
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
  shell/browser/api/electron_api_web_frame_main.cc
  shell/browser/api/electron_api_web_request.cc
  shell/browser/api/message_port.cc
  shell/browser/electron_autofill_driver_factory.cc
  shell/browser/electron_browser_client.cc
  shell/browser/extensions/api/scripting/scripting_api.cc
  shell/browser/extensions/api/tabs/tabs_api.cc
  shell/browser/extensions/electron_component_extension_resource_manager.cc
  shell/browser/hid/electron_hid_delegate.cc
  shell/browser/hid/hid_chooser_context.cc
  shell/browser/plugins/plugin_utils.cc
  shell/browser/serial/serial_chooser_context.cc
  shell/browser/ui/cocoa/electron_touch_bar.mm
  shell/browser/ui/message_box_gtk.cc
  shell/browser/ui/message_box_mac.mm
  shell/browser/ui/message_box_win.cc
  shell/browser/usb/electron_usb_delegate.cc
  shell/browser/usb/usb_chooser_context.cc
  shell/common/api/electron_api_clipboard.cc
  shell/renderer/api/electron_api_context_bridge.cc
  shell/renderer/api/electron_api_spell_check_client.cc
  shell/renderer/electron_renderer_client.cc
  shell/renderer/electron_sandboxed_renderer_client.cc
Labels: backport, semver/patch, 34-x-y

#45825 chore: Fix typos
  build/profile_toolchain.py
  docs/fiddles/features/window-customization/custom-title-bar/custom-drag-region/main.js
  docs/fiddles/features/window-customization/custom-title-bar/custom-title-bar/main.js
  docs/fiddles/features/window-customization/custom-title-bar/native-window-controls/main.js
  docs/tutorial/custom-title-bar.md
  docs/tutorial/custom-window-styles.md
Labels: semver/patch, new-pr 🌱, no-backport

#45702 chore: cherry-pick 5 changes from 2-M132
  patches/v8/.patches
  patches/v8/maglev_fold_converttohole_and_checknothole_for_constant_inputs.patch
  patches/v8/maglev_remove_the_default_case_in_the_switch_inside.patch
  patches/v8/maglev_sandbox_add_support_to_store_trusted_pointers_to_maglev.patch
  patches/v8/maglev_track_arm_arm64_temps_separately_from_default_tmps.patch
  patches/v8/merged_maglev_fix_phi_untagging_bug_with_checknumber_holeyfloat64.patch
Labels: security 🔒, semver/patch, backport-check-skip, 32-x-y

#45705 chore: cherry-pick 3 changes from 0-M133
  .gitattributes
  patches/chromium/.patches
  patches/chromium/reland_lzma_sdk_update_to_24_09.patch
  patches/v8/.patches
  patches/v8/cherry-pick-1c7ff4d5477f.patch
  patches/v8/cherry-pick-8834c16acfcc.patch
Labels: security 🔒, semver/patch, backport-check-skip, 33-x-y

#45670 docs: add docs about shared texture mode osr
  docs/api/web-contents.md
  docs/tutorial/offscreen-rendering.md
  shell/browser/osr/README.md
Labels: documentation :notebook:, semver/patch, no-backport

#45813 fix: context-menu event emitted in draggable regions
  shell/browser/ui/electron_desktop_window_tree_host_linux.cc
  shell/browser/ui/electron_desktop_window_tree_host_linux.h
  spec/api-web-contents-spec.ts
Labels: semver/patch, target/34-x-y, target/35-x-y

#45838 chore: remove patch that's already upstreamed
  patches/chromium/.patches
  patches/chromium/add_didinstallconditionalfeatures.patch
  patches/chromium/allow_disabling_blink_scheduler_throttling_per_renderview.patch
  patches/chromium/build_do_not_depend_on_packed_resource_integrity.patch
  patches/chromium/can_create_window.patch
  patches/chromium/check_for_unit_to_activate_before_notifying_about_success.patch
  patches/chromium/chore_partial_revert_of.patch
  patches/chromium/chore_provide_iswebcontentscreationoverridden_with_full_params.patch
  patches/chromium/disable_compositor_recycling.patch
  patches/chromium/disable_hidden.patch
  patches/chromium/fix_crash_loading_non-standard_schemes_in_iframes.patch
  patches/chromium/fix_drag_and_drop_icons_on_windows.patch
  patches/chromium/fix_on-screen-keyboard_hides_on_input_blur_in_webview.patch
  patches/chromium/fix_restore_original_resize_performance_on_macos.patch
  patches/chromium/fix_return_v8_value_from_localframe_requestexecutescript.patch
  patches/chromium/frame_host_manager.patch
  patches/chromium/gritsettings_resource_ids.patch
  patches/chromium/mas_avoid_private_macos_api_usage.patch.patch
  patches/chromium/notification_provenance.patch
  patches/chromium/partially_revert_is_newly_created_to_allow_for_browser_initiated.patch
  patches/chromium/refactor_expose_cursor_changes_to_the_webcontentsobserver.patch
  patches/chromium/refactor_expose_file_system_access_blocklist.patch
  patches/chromium/refactor_unfilter_unresponsive_events.patch
  patches/chromium/render_widget_host_view_base.patch
  patches/chromium/revert_code_health_clean_up_stale_macwebcontentsocclusion.patch
  patches/chromium/web_contents.patch
  patches/chromium/webview_fullscreen.patch
Labels: semver/patch, fast-track 🚅, no-backport, 35-x-y

#45843 docs: fix PrinterInfo info in breaking-changes.md
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/patch, fast-track 🚅, no-backport

#45822 docs: update breaking-changes.md for 35.0.0
  docs/breaking-changes.md
Labels: documentation :notebook:, semver/none, target/35-x-y

#45785 docs: update timelines for E36
  docs/tutorial/electron-timelines.md
Labels: documentation :notebook:, semver/patch, target/35-x-y

#45842 docs: fix spelling errors in code comments
  shell/browser/api/electron_api_power_monitor.h
  shell/browser/api/electron_api_web_contents.h
  shell/browser/native_window_views.h
  shell/browser/ui/devtools_ui_theme_data_source.cc
  shell/browser/ui/views/submenu_button.cc
  shell/browser/ui/win/electron_desktop_window_tree_host_win.cc
  shell/common/gin_converters/frame_converter.cc
Labels: documentation :notebook:, semver/patch, new-pr 🌱, no-backport

#45789 build: bump NMV to 135
  build/args/all.gn
Labels: semver/none, no-backport
