Repository electron/electron, pull requests merged in 2025-09, with the labels that each got.

#48227 build: use siso instead of reclient (37-x-y)
  .github/actions/build-electron/action.yml
  .github/actions/cipd-install/action.yml
  .github/actions/fix-sync/action.yml
  .github/actions/install-build-tools/action.yml
  .github/workflows/pipeline-segment-electron-build.yml
  .github/workflows/pipeline-segment-electron-test.yml
  build/siso/backend.star
  build/siso/main.star
  script/actions/move-artifacts.sh
  script/node/generate_original_fs.py
Labels: backport, semver/none, 37-x-y

#48238 build: update spec deps for clean audit
  spec/yarn.lock
Labels: semver/none, target/39-x-y

#48285 docs: update release timeline for unsupported v35
  docs/tutorial/electron-timelines.md
Labels: new-pr 🌱, semver/none, target/38-x-y

#48279 refactor: avoid unused inheritance in ServiceWorkerMain
  shell/browser/api/electron_api_service_worker_main.h
Labels: semver/patch, target/39-x-y

#48170 feat: add `fileSystem` to `ses.setPermissionCheckHandler`
  docs/api/session.md
  shell/browser/electron_permission_manager.cc
  shell/browser/electron_permission_manager.h
  shell/browser/file_system_access/file_system_access_permission_context.cc
  spec/chromium-spec.ts
  spec/fixtures/file-system/persist.txt
  spec/fixtures/file-system/test-perms.html
Labels: semver/minor, api-review/approved ✅, target/36-x-y, target/37-x-y, target/38-x-y, target/39-x-y

#48318 fix: remove unneeded handlescope from JS callbacks
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: semver/patch, new-pr 🌱, target/39-x-y

#48335 chore: cherry-pick ec6c18478382 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-ec6c18478382.patch
Labels: semver/patch, backport-check-skip, main, in-flight/36-x-y, in-flight/37-x-y, in-flight/38-x-y, in-flight/39-x-y

#48338 chore: cherry-pick ec6c18478382 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-ec6c18478382.patch
Labels: backport, semver/patch, 37-x-y

#48339 chore: cherry-pick ec6c18478382 from v8
  patches/v8/.patches
  patches/v8/cherry-pick-ec6c18478382.patch
Labels: backport, semver/patch, 36-x-y

#48344 fix: remove unneeded handlescope from JS callbacks
  shell/browser/api/electron_api_session.cc
  shell/browser/api/electron_api_web_contents.cc
Labels: backport, semver/minor, 39-x-y

#48345 build: update build tools to get siso for forks fix
  .github/actions/build-electron/action.yml
  .github/actions/install-build-tools/action.yml
Labels: fast-track 🚅, semver/none, target/36-x-y, target/37-x-y, target/38-x-y, target/39-x-y

#48354 refactor: use gin::Arguments in api::Clipboard
  shell/common/api/electron_api_clipboard.cc
  shell/common/api/electron_api_clipboard.h
Labels: semver/none, no-backport

#48361 chore: remove unused, undocumented, untested executionMode arg from `web_frame.executeJavaScriptInIsolatedWorld()`
  shell/renderer/api/electron_api_web_frame.cc
Labels: semver/none, no-backport

#48350 build: update build tools to get siso for forks fix (#48345)
  .github/actions/build-electron/action.yml
  .github/actions/install-build-tools/action.yml
Labels: backport, semver/none, target/36-x-y, target/37-x-y, 38-x-y

#48379 fix: disable NSAutoFillHeuristicController on macOS 26
  patches/chromium/.patches
  patches/chromium/disable_nsautofillheuristiccontroller_on_macos_26.patch
Labels: semver/patch, fast-track 🚅, target/37-x-y, target/38-x-y, target/39-x-y

#48386 test: rerun failed tests individually
  .github/workflows/pipeline-segment-electron-test.yml
  package.json
  script/actions/screencapture-nag-remover.sh
  script/spec-runner.js
  spec/lib/screen-helpers.ts
  spec/webview-spec.ts
  yarn.lock
Labels: backport, semver/none, 39-x-y

#48376 fix: MacOS 26 Tahoe - stop overriding private cornerMask API to fix WindowServer GPU load
  shell/browser/native_window_mac.mm
  shell/browser/ui/cocoa/electron_ns_window.h
  shell/browser/ui/cocoa/electron_ns_window.mm
Labels: semver/patch, target/37-x-y, target/38-x-y, target/39-x-y
